### ISSUE TITLE
Porting docker commands to oc equivalent 

### ISSUE THREAD

**Issue by ravishankarhassain** [openshift/origin#10088]
Hi All,

I am trying to deploy a docker image https://hub.docker.com/r/atmoz/sftp/ from docker hub to openshift. 

How can I convert the below command 

`docker run  -v /host/share:/home/foo/share -p 2222:22 -d atmoz/sftp foo:123:1001`

to oc equivalent ?

I gave the command 

`oc run sftp --image atmoz/sftp --port 2222` 

and I got some error message in the logs. I have pasted in the gist https://gist.github.com/ravishankarhassain/02ff7d192858e7ea1fe1ceb54e426031

I guess we should give username and password while issuing oc command. Is there any document or reference to port docker commands to oc equivalent ?

**Comment by ingvagabund** [comment]
Hi,

the generic rule for ``oc run`` command is here [1]. It basically shows the most important options. There is no ``1:1`` mapping of ``docker run`` command to ``oc run``. For instance, in your example you are mounting host path to container path, which is not possible for cluster container as one can not know which node your container will run on in advance. Still, with some limitations, subset of ``docker run`` commands can be translated.

Are you interested in particular commands or in full enumeration? If you compare ``oc run -h``

``Usage: oc run NAME --image=image [--env="key=value"] [--port=port] [--replicas=replicas] [--dry-run=bool] [--overrides=inline-json] [--command] -- [COMMAND] [args...] [options]``

with ``docker run --help``

``Usage:	docker run [OPTIONS] IMAGE [COMMAND] [ARG...]``

the common API is:

```vi
--attach                     Attach to STDIN, STDOUT or STDERR
--env                        Environment variables to set in the container
-i                           Keep STDIN open even if not attached
-t, --tty                    Allocate a pseudo-TTY
```
Other arguments can be mapped to corresponding ones:

```vi
IMAGE to --image IMAGE
--port to -p
COMMAND [ARG...] to --command COMMAND [ARG]
```

And possibly others.

Since one should not rely on particular containerization technology, the ``oc run`` API is more abstract than ``docker run``. In addition, it provides sup-runtime container configuration (OpenShift specific) such as setting resource limits (which helps scheduler to find more suitable node for container), restart policy, labels, etc.

It that is not enough, there is also ``--overrides`` option which gives you more control over created container. It provides richer specification such as (possibly) setting capabilities, volumes, etc.

> I gave the command
> 
> ``oc run sftp --image atmoz/sftp --port 2222``
> 
> and I got some error message in the logs. I have pasted in the gist https://gist.github.com/ravishankarhassain/02ff7d192858e7ea1fe1ceb54e426031
> 

Error messages in the logs seems ``atmoz/sftp`` specific. If the container is running, you can access it  by running ``docker run -it CONTAINER_ID /bin/sh`` and inspect.

> Is there any document or reference to port docker commands to oc equivalent ?

Not one I am aware of. The best, this can be described on example to example bases.

[1] https://docs.openshift.org/latest/cli_reference/basic_cli_operations.html#run

**Comment by ingvagabund** [comment]
@ravishankarhassain feel free to re-open the issue if you feel the clarification is still needed.
/close
