### ISSUE TITLE
cluster up and registry endpoint

### ISSUE THREAD

**Issue by mattf** [openshift/origin#10117]
i want to docker push to the docker-registry running in my openshift cluster started by oc cluster up
##### Version

oc v1.3.0-alpha.2-dirty
kubernetes v1.3.0-alpha.1-331-g0522e63
##### Steps To Reproduce
1. oc cluster up
2. oc login -u system:admin
3. REG=$(oc --namespace=default get svc docker-registry --template={{.spec.portalIP}}):5000
4. oc login -u developer -p developer
5. docker login -u developer -p $(oc whoami -t ) -e none $REG
##### Current Result

i can now docker push so long as i keep track of $REG
##### Expected Result

oc cluster up to display the docker-registry endpoint so i don't have to do steps 2-4.

better, automatically docker login as well

best, commands such as oc registry login/push that find the docker-registry automatically, ideally login wouldn't even be necessary

**Comment by csrwng** [comment]
@mattf what's the use case for pushing images to the registry? Are these images that live in your local docker that you'd like to run on openshift?

I'm trying to figure out what makes sense in this case. Only when running 'cluster up' on a linux box with docker running locally do you have direct access to the service endpoint. In the case of Mac or Windows the 'docker login' would fail (or any other external client for that matter).

For the CLI command suggestion, 'oc registry push' sounds great, but I think would only be applicable to a very narrow use case. It could only be used if you're running it on a node that's running openshift (think large multi-node cluster) and would not be of any use to users that don't have docker or only have access to the master endpoint.

@kargakis any thoughts ?

**Comment by mattf** [comment]
yes, local images to push.

the use case is more general than simply "cluster up" environments. i frequently need to push local images, even to remote openshift deployments. in the remote case there's usually a manual export, scp, import, push process that's also error prone. having this as a first class operation on the "oc" command would be nice.

in the remote case i imagine a route would be necessary to reach the registry, or an extension to the api.

**Comment by smarterclayton** [comment]
The plan is to make registries always exposed by a route.  But we have to wire in some code to do that.

**Comment by kargakis** [comment]
cc: @mfojtik @legionus @miminar re registry commands

**Comment by chouseknecht** [comment]
*Use case*: Creating demos for Ansible Container that show the Ansible community how simple it is to deploy an application to OpenShift without having to a) introduce them to the joy of first creating a local registry; or b) exposing images on public Docker hub. 

*Problem*: The `default` project seems to exists, which I assume is the same as the `default` project exposed in the All-In-One-VM, but it's not accessible. If it is indeed the same project, it includes a route and service pointing at the registry already. The route provides a hostname of 'hub.10.2.2.2', and if one adds edge terminated SSL to the route and a local entry in /etc/hosts, it actually works quite nicely. 

The project exists:

```
 $ oc new-project default
Error from server: project "default" already exists
```

But attempting to gain access to it (so that I can discover the hostname and add edge terminated SSL) does not work:

```
$ oc adm policy add-role-to-user admin system -n default
Error from server: User "system" cannot get policybindings in project "default"
```

So... could you please:

1. Expose the `default` project as you do in the All-In-One-VM
2. Deliver a route that already includes edge terminated SSL
3. At the end of `oc cluster up` in the helpful notes, mention that o' yes there is a registry and here's how you can access it.

**Comment by csrwng** [comment]
@chouseknecht You can gain access to the default project by logging in as administrator. Instructions for that are printed when `cluster up` is invoked:

```
   To login as administrator:
       oc login -u system:admin
```

A route is not currently created for the registry, but perhaps we should. At the very least we can start by adding instructions on how to access the registry in the cluster up doc.

**Comment by smarterclayton** [comment]
We should add the route.  We should also probably (in 1.5) start moving oc
cluster up to init the registry in another namespace.

On Nov 9, 2016, at 6:08 AM, Cesar Wong <notifications@github.com> wrote:

@chouseknecht <https://github.com/chouseknecht> You can gain access to the
default project by logging in as administrator. Instructions for that are
printed when cluster up is invoked:

   To login as administrator:
       oc login -u system:admin

A route is not currently created for the registry, but perhaps we should.
At the very least we can start by adding instructions on how to access the
registry in the cluster up doc.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/origin/issues/10117#issuecomment-259422561>,
or mute the thread

**Comment by mfojtik** [comment]
@smarterclayton where do we record that route? there is a card in PM board to have "shared" config map that will contain all useful infos (including registry URL) that console and users might need.

**Comment by smarterclayton** [comment]
External name vs internal name in API probably drives that.  In the
meantime we'd use the existing mechanism via env

On Nov 10, 2016, at 1:19 AM, Michal Fojtik <notifications@github.com> wrote:

@smarterclayton <https://github.com/smarterclayton> where do we record that
route? there is a card in PM board to have "shared" config map that will
contain all useful infos (including registry URL) that console and users
might need.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/origin/issues/10117#issuecomment-259639970>,
or mute the thread

**Comment by csrwng** [comment]
Submitting a doc update for what can be done today here: #12826 

Created a trello card for the route part:
https://trello.com/c/8DR2emei/1140-expose-the-openshift-registry-through-a-route-when-started-with-cluster-up
