### ISSUE TITLE
`oc status` should emit warning if no liveness probe is defined for a pod

### ISSUE THREAD

**Issue by stevekuznetsov** [openshift/origin#10271]
Since so much of our logic depends on knowing if a pod is alive, not having a liveness probe should be a big warning.

**Comment by danmcp** [comment]
A warning sounds a bit harsh.  Info with verbose I would expect.

**Comment by fabianofranz** [comment]
cc @deads2k

**Comment by deads2k** [comment]
@stevekuznetsov this is a different problem than https://github.com/openshift/origin/issues/10294 ?

**Comment by deads2k** [comment]
> A warning sounds a bit harsh. Info with verbose I would expect.

@danmcp Right now warnings are hidden behind a verbose flag.  That makes the "how do I see these" functionally equivalent between the two.

I don't really care what the marker level is.  Since so much useful information is hidden behind verbose, I always run with `-v` and kind of expect that anyone looking to get useful markers does the same.

**Comment by stevekuznetsov** [comment]
@deads2k this is different in that it's not talking about differences between client handling of missing probes... I don't think `oc status` client is looking for liveness at all. The deployment @danmcp made didn't have one and I didn't see anything about it missing.
