### ISSUE TITLE
Failed to pull docker image due to wrong digest

### ISSUE THREAD

**Issue by libnux** [openshift/origin#10555]
[provide a description of the issue]

I created a docker-image app by : oc new-app  mydomain.net/simpleserver, but it failed to pull the docker image due to wrong digest. According to the events, the generated URL is "mydomain.net/libo/simpleserver@sha256:8366a25b17ab628d004e702bd00f83d94c37e411cdfbe7a319114375e231b9b9"

However, the correct digest is "sha256:4d51ecd1c555527ff0c7ffa4fac41f1e66c53a092f01f437448a89ab859f40fd"

##### Version
[provide output of the `openshift version` or `oc version` command]
oc v1.2.1
kubernetes v1.2.0-36-g4a3f9c5
docker 1.10.3

private docker registry: github.com/docker/distribution v2.5.0

##### Steps To Reproduce
1. [step 1]
oc new-app  mydomain.net/simpleserver
2. [step 2]
The app failed to start, and check events and found message like "Failed to pull image "k8s-docker.mi-ae.net/libo/simpleserver@sha256:8366a25b17ab628d004e702bd00f83d94c37e411cdfbe7a319114375e231b9b9": image pull failed for mydomain.net/simpleserver@sha256:8366a25b17ab628d004e702bd00f83d94c37e411cdfbe7a319114375e231b9b9, this may be because there are no credentials on this request. details: (manifest unknown: manifest unknown)"
##### Current Result
Docker-image app failed to start.
##### Expected Result
Docker-image app start and run.

**Comment by mfojtik** [comment]
@legionus this does not seem like a docker 1.9 manifest issue, the docker registry is 2.5.x and docker 1.10. Can you have a look?

**Comment by legionus** [comment]
@libnux `k8s-docker.mi-ae.net/libo/simpleserver` was pushed using docker 1.10 or newer ?

**Comment by libnux** [comment]
@legionus , yes, pushed with docker 1.12.1

**Comment by legionus** [comment]
Starting `docker/distribution` [v2.3.0](https://github.com/docker/distribution/releases/tag/v2.3.0) added support for v2 schema. When pushing images, clients which support (v1.10 or newer) the new manifest format should first construct a manifest in the new format. If uploading this manifest fails, presumably because the registry only supports the old format, the client may fall back to uploading a manifest in the old format.

It means that your image in v2 schema. But `oc v1.2.1` can use only v1 schema. For these old clients, `docker/distribution` makes the conversion in the old schema. Unfortunately, in this case, the digest of manifest [will change](https://github.com/docker/distribution/blob/master/docs/compatibility.md).

In this situation, the solution may be to use a docker v1.9 or use `docker/distribution` older than v2.3. The new openshift release will support the [new format of manifests](https://github.com/openshift/origin/pull/8938).

**Comment by libnux** [comment]
@legionus , could I know the release date for openshift 1.3? 

Does the v1.3.0-alpha.3 release support new format of manifests? 

Thanks.

**Comment by legionus** [comment]
> @legionus , could I know the release date for openshift 1.3? 

@smarterclayton 

> Does the v1.3.0-alpha.3 release support new format of manifests? 

Yes.

**Comment by smarterclayton** [comment]
Very soon.

**Comment by libnux** [comment]
I tried registry:2.2.1, and it works now. Thanks.
