### ISSUE TITLE
Make resource builder more smart about suggesting what resource types are expected

### ISSUE THREAD

**Issue by mfojtik** [openshift/origin#10568]
Today, when I do:

``` console
[@dev] .../openshift/origin # oc rollout pause ruby-ex
no matches for {  ruby-ex}
```

The error is basically about not specifying a resource type, which in this case might be "dc" (or deployment?). Anyhow, I think the restmapper should give us better errors in this case, something along:

``` console
[@dev] .../openshift/origin # oc rollout pause ruby-ex
no resource type specified, must be "deployment" or "deploymentConfig"
```

**Comment by mfojtik** [comment]
@smarterclayton FYI, I believe this has to be fixed upstream.

**Comment by mfojtik** [comment]
@fabianofranz FYI

**Comment by liggitt** [comment]
that's not really the restmapper's job... it's the job of the thing querying the restmapper (in this case, the CLI command should enforce having a resource type)

**Comment by smarterclayton** [comment]
Yeah, that's resource.Builder or higher

On Aug 22, 2016, at 11:06 AM, Jordan Liggitt <notifications@github.com>
wrote:

that's not really the restmapper's job... it's the job of the thing
querying the restmapper (in this case, the CLI command should enforce
having a resource type)

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/origin/issues/10568#issuecomment-241443302>,
or mute the thread
