### ISSUE TITLE
Consider using Patch() for deployment config reaper

### ISSUE THREAD

**Issue by mfojtik** [openshift/origin#10565]
We are switching to patch deployment configs when pausing them. This PR: https://github.com/openshift/origin/pull/10564 address this in controller, but we also do pause in the reaper.

However, in the reaper we also set the revisionHistory and replicas to 0. We should consider using patch there as well. Also when we update the DC to set replicas?

**Comment by mfojtik** [comment]
@deads2k @kargakis WDYT

**Comment by deads2k** [comment]
> @deads2k @kargakis WDYT

Using patch from the CLI sounds find to me.  It's usage in a controller is a little less obvious to me, since the controller needs to be sure its observing the latest state.

**Comment by mfojtik** [comment]
@deads2k what is the distinction between using Update() and Patch() ? I'm thinking about stuff like:

1) Updating `replicas` count
2) Updating `revisionHistory`

etc. does it sound like a good fit for these items?

**Comment by deads2k** [comment]
> @deads2k what is the distinction between using Update() and Patch() ? I'm thinking about stuff like:
> 
> 1) Updating replicas count
> 2) Updating revisionHistory
> 
> etc. does it sound like a good fit for these items?

Updates are resourceVersion locked so that you're only changing the values if you've seen the current state before.  Patches are applied regardless of the resourceVersion state, so you're changing values without regard for whether the state you're changing matches what you thought you were changing.

On a CLI, you're stating an intent to change X without regard for the current state of the system.  Stomping a change from a second or two in either direction doesn't matter to you.  From a controller, I'm less certain that you don't care about state you're stomping.  I'm not saying that its inappropriate, I just haven't considered what it would mean for a controllers to say "done" without actually observing the previous state.  I suspect it varies.

**Comment by mfojtik** [comment]
@deads2k thanks for explanation :-)

**Comment by kargakis** [comment]
There is no need to patch from the controllers. We want to patch every time somebody runs `oc rollout pause/resume` and we probably want to patch on `oc delete` but that's it.
