### ISSUE TITLE
Image importer should respect the registries configured in Docker daemon

### ISSUE THREAD

**Issue by mfojtik** [openshift/origin#10638]
When importing the Docker image, we default to "docker.io" in case the repository is not set. By doing that we ignore the `--add-registry` parameter that Docker runs with.
In that case, we:

1) don't query the added registries when importing the image
2) we don't respect the order when doing imports

The `engine-api/client` is capable of querying the Docker daemon to get the information about configured registries. We should be able to call the Docker and obtain the list and use it instead of defaulting to "docker.io".

For the old servers, this is partially addressed here: https://github.com/openshift/origin/pull/10637

**Comment by mfojtik** [comment]
@csrwng PTAL

**Comment by csrwng** [comment]
@mfojtik I think this should be owned by your team, since in new-app we delegate searching for an image to the image import API endpoint. Agree?

**Comment by mfojtik** [comment]
@csrwng I think we punted-out from this (or at least I remember @smarterclayton saying we don't want to read the Docker configuration on client side).

**Comment by smarterclayton** [comment]
Yes, importer, if it needs config, needs it centrally.  Nodes are
subordinate to cluster config and I don't see a use case yet that justifies
allowing nodes to have split configurations (you can do it, but that's your
use case)

On Oct 17, 2016, at 8:18 AM, Michal Fojtik <notifications@github.com> wrote:

@csrwng <https://github.com/csrwng> I think we punted-out from this (or at
least I remember @smarterclayton <https://github.com/smarterclayton> saying
we don't want to read the Docker configuration on client side).

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/origin/issues/10638#issuecomment-254204444>,
or mute the thread
