### ISSUE TITLE
Git Flow Workflow

### ISSUE THREAD

**Issue by stevenpall** [openshift/origin#10642]
Hi there,

Reading through the docs, I was unsure whether or not a git flow workflow is currently supported by OpenShift. It seems that when you create a new app and associate a git repository with it, you can only specify a single branch to utilize for deployments, etc. This seems geared more towards a fork-and-pull model of using git. In my org, contributors to a repository simply create feature branches and then make pull requests against the master branch. 

What would be ideal to augment this workflow is to be able to create a new app (or "sub-app") per branch in a repository. I think this could be done manually at the moment simply by prepending the branch name to the app name and then specifying the git branch for builds during app creation. That said, this seems kind of hacky and could probably become unmanageable quite quickly. Do you have any suggestions on how to go about this or if there are any planned enhancements to the platform to support this workflow?

Thanks!

**Comment by bparees** [comment]
You're correct that today the assumption is you'd create multiple buildconfigs referencing your different branches.

It sounds like you're asking for new-app to automate that process by automatically creating a buildconfig(and associated resources) for every branch in the referenced repository, is that accurate?  Or do you have another model in mind that would avoid needing to have separate buildconfigs/etc to represent each branch you might want to build/deploy/test?

**Comment by stevenpall** [comment]
Thanks for the info regarding how we might go about using separate buildconfigs.

Regarding the automation of this task, it would be nice if something like that could be integrated into OpenShift, though I understand it probably isn't too common a use case. That said, we might just build something out-of-band to create new apps upon creation of new branches.

Aside from automation, though, I think what would be useful is to have some sort of logical grouping of apps that mirrors the repository's branch structure. I suppose a new project could be created per repository with apps in the projects corresponding to branches? e.g.:
```
environment: prod
|-- project: repo
|    |-- app: master
|    |-- app: feature/my_feature
```

**Comment by bparees** [comment]
Yeah I guess there are two possible constructs in openshift you could use today for that:

1) project per branch (feels heavy but it's the only easy way to avoid name collisions when you start trying to build/deploy multiple versions of your app based on different branches)

2) apply labels to resources so you can logically group them by using label selectors.  this requires you append the branch name or some other unique prefix/suffix to the names of the objects you create within the project.  You're also going to need to be careful when you start creating services since services are going to select pods based on the labels on those pods, so again you need to ensure that the labels used to select pods for loadbalancing do not cross-cut between pods from different app "branches"

Templates can help you with this.  If you define a template for the app, with a template parameter of "branchname", then you can reference that parameter value in the template all over the place:

1) as a ref value in the buildconfig
2) as a suffix on all your resource names
3) as a label on all your resources
4) as the label selector value on your services.

so that's probably what i'd recommend, though it means you must create a template for each app (hopefully they're all going to look pretty similar).

Then when you want to build/test a new branch, you just instantiate the template w/ the new branch name.

**Comment by bparees** [comment]
closing based on my suggestion (2) above.
