### ISSUE TITLE
Support for Cluster Limit Range?

### ISSUE THREAD

**Issue by andrewklau** [openshift/origin#10694]
Will there be support for a ClusterLimitRange like there is for ClusterResourceQuota?

**Comment by deads2k** [comment]
> Will there be support for a ClusterLimitRange like there is for ClusterResourceQuota?

Limit ranges are more naturally project scoped ("apply these limits to individual things in this project") based on the class of project.  There's probably a case for trying to apply a `LimitRange` via label selection of projects, but it isn't a high priority.  Since `LimitRange` is applied to a single resources, there's not an aggregation.

Do you have a specific use-case where you think its necessary?

**Comment by andrewklau** [comment]
Having a single ClusterLimitRange per user would be easier to maintain. Espically if it's required to frequently change the user's limit ranges. 

Setting a single limit which applies to group of users based on their label would be another example.
