### ISSUE TITLE
Cross linking between docker images and Openshift images

### ISSUE THREAD

**Issue by enoodle** [openshift/origin#10702]
Currently there seem to be no way to link images that are returned from Openshift (via `oc get images` or oapi/v1/images ) with the docker images stored on a docker registry.
This make it very difficult to annotate images and to identify which images exactly are running on the pods because the imageID of a running container comes from docker and not Openshift (pod.status.containerStatuses.imageID). 

A way to get the docker imageID (IIUC it is the digest as of docker 1.10) from Openshift api is required.

**Comment by mfojtik** [comment]
@enoodle I believe we do store the `imageID` (digest) inside the ICT.

**Comment by deads2k** [comment]
> @enoodle I believe we do store the imageID (digest) inside the ICT.

@mfojtik based on talking with @smarterclayton, the docker image ID getting reported by docker and placed on containerstatus.imageID isn't going to be the value in the ICT because the ICT is based on a digest, but the docker imageID is the existing digest plus data about where it was pulled from, rehashed.

**Comment by bparees** [comment]
is the dockerImageReference not what you're looking for?


pod shows the image w/ digest:
```
$ oc describe pod frontend-1-xxspk | grep Image
    Image:          172.30.165.133:5000/test/origin-ruby-sample@sha256:732b7bdad3cb38a06c6de69115756697f889e00ac8c91ae920ffe554a6b6efd1
    Image ID:       docker-pullable://172.30.165.133:5000/test/origin-ruby-sample@sha256:732b7bdad3cb38a06c6de69115756697f889e00ac8c91ae920ffe554a6b6efd1
```

getting the image by digest shows the dockerImageReference which is the pull spec:
```
$ oc get image -o yaml sha256:732b7bdad3cb38a06c6de69115756697f889e00ac8c91ae920ffe554a6b6efd1 | grep dockerImageReference

dockerImageReference: 172.30.165.133:5000/test/origin-ruby-sample@sha256:732b7bdad3cb38a06c6de69115756697f889e00ac8c91ae920ffe554a6b6efd1

```

(may not have existed at the time this issue was opened, so i am proactively closing this but we can reopen if that is not what you were asking for)

**Comment by enoodle** [comment]
@bparees Thanks for taking notice, this should have been close for some time now.

The addition of `docker-pullable://` style reference and `dockerImageReference` on the image itself really did enable me to match image more reliably with the repo-digest of the container images.
