### ISSUE TITLE
Image signatures cannot be updated by project admin

### ISSUE THREAD

**Issue by aweiteka** [openshift/origin#10825]
[Image signatures](https://docs.openshift.org/latest/rest_api/openshift_v1.html#create-a-imagesignature) have been added to the API but project admins cannot update them. In this case I'm using an external tool, [skopeo](https://github.com/projectatomic/skopeo/), to perform the API call.
##### Version

openshift v1.3.0-alpha.3+7f59726
##### Steps To Reproduce
1. Use skopeo to sign an image
   
   ```
   skopeo copy --sign-by aweiteka@gmail.com atomic:test/hello-openshift:latest atomic:test/hello-openshift:latest
   ```
##### Current Result

403: User \"aaron\" cannot create imagesignatures at the cluster scope
##### Expected Result

200
Confirmed cluster-admin can successfully make POST calls to ImageSignature objects.
##### Additional Information

Skope debug output

```
DEBU[0003] Will send body: {"kind":"ImageSignature","apiVersion":"v1","metadata":{"name":"sha256:605ec3819579d54d00bef8ef09332cdb1ed4837685e9a63fbfdd275f451ff992@5ca8bece1f04075d6e9187be41f8a544"},"type":"atomic","content":"owGbwMvMwMFYk3Vm3uPFAmKMpw+UJjGEn5c9W62UXJRZkpmcmKNkVa2UmZKaV5JZUglip+QnZ6cW6RalpqUWpeYlpypZKRka6BnrGRrqGZmaWFmYmBjrl6QWl+hnpObk5OvmF6TmFWdkppVY5SSChJVqdZQycxPTU5HMyk3My0wDyummZKaDlFgpFWckGpmaWZkZmKYmG1sYWpqaW6aYmqQYGCSlplmkphlYGhsbJackGaammFgYm5tZmKZaJpoZpyWlpaQYmZummZgapqVZWhqBLCupLAC5MbEkPzczWSE5P68kMTMvtUihODM9L7GktCgVpCi/oCQzPw/i2eSiVKDiIoQeAz1DPQPdlNQyJaBpmblAFybmFihZGZqYGxtaGhqbG9fWdjLKsDAwcjCwsTKBQo+Bi1MAFqbahez/PRcbbFNjXT/FcD/LtMQnP2b9n2K1Ka3MyjtCecns8OKXPyREo8LEOxrfXLnQkdUS4ik4d3NWTTrrHB/2bLPTO1asVr3BPU1kWei0FZNftuQ72If9aOw7GHz9ffWBB7eD7x37mdDV5pJlHuXLw21+LNEs5rMqN+vJjkDGTIefESqPath9PNek7ZwmoGCc/Jzx3gKbTSeqn0rqbm2TK+J/331p/+7E9PjTnu1J65RcZzwJ4DrxRunV+aNTUl9l/tv9rKPbac6xmSUHOaWWyiqu6BfR2/OYzatt4teQJusHsT0X7S8cufVMvDJA+1d+TmipyaT9iV4Gx+NXFXbe1w76mnL3/8az8ZcmaDycMyUaAA=="}
DEBU[0003] POST {https  <nil> 10.3.11.254:8443 /oapi/v1/imagesignatures   }
DEBU[0003] Got body: {
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "User \"aaron\" cannot create imagesignatures at the cluster scope",
  "reason": "Forbidden",
  "details": {
    "kind": "imagesignatures"
  },
  "code": 403
}

DEBU[0003] Got content-type: application/json
FATA[0003] Error writing signatures: User "aaron" cannot create imagesignatures at the cluster scope
```

cc @mtrmac

**Comment by deads2k** [comment]
> Image signatures have been added to the API but project admins cannot update them. In this case I'm using an external tool, skopeo, to perform the API call.

Project admins cannot, but we created a new role called `system:image-signer` to sign images.

**Comment by deads2k** [comment]
> Project admins cannot, but we created a new role called system:image-signer to sign images.

We do not anticipate giving that role to project admins, because they could use it to delete other people's signatures.  As of right now, we don't have a projected/virtual resource to allow signing inside of a project.  Decisions like: 
 1. who can see the signature?  
 2. most people won't want to see them, how do you filter them?
 3. can you remove the signature?

arose and we didn't have answers for them yet. For 3.3, we're leaving it as a cluster-scoped permission.

**Comment by mtrmac** [comment]
Yeah. you need `oadm policy add-cluster-role-to-group system:image-signer system:authenticated` or something similar, probably more restrictive.

See https://github.com/openshift/origin/pull/9181 for the original discussion deferring this.

**Comment by aweiteka** [comment]
> See #9181 for the original discussion deferring this.

@mtrmac ah, yes. Capturing the concise issue here so it can be more easily referenced.

> We do not anticipate giving that role to project admins, because they could use it to delete other people's signatures.

@deads2k I understand the issue so we don't have to discuss solution extensively, but I would expect to interact with these at the imagestream level. Since we're integrating with this I want to make sure we didn't expose signatures on the incorrect object. Is there an imagestream mapping that can be made to abstract these and thus provide the scoping we require?

**Comment by deads2k** [comment]
> @deads2k I understand the issue so we don't have to discuss solution extensively, but I would expect to interact with these at the imagestream level. Since we're integrating with this I want to make sure we didn't expose signatures on the incorrect object. Is there an imagestream mapping that can be made to abstract these and thus provide the scoping we require?

The `image` is the correct object, since `imagesignatures` are logically tied to the image and not to the manner in which you reference it.  If a cluster-admin wants to sign an image to indicate something like "ops-approved", you don't want to lose that signature when some just creates a new tag to it.

There are use-cases where you definitely want shared signatures and use cases where you definitely don't want shared signatures.  We designed the API so that it *could* support both with filtering techniques.  We didn't design those filtering techniques, because we're less certain of who will be signing and why, so relative frequency of X versus not-X isn't known to us yet.

**Comment by mfojtik** [comment]
@aweiteka do we still need this bug? We have image-signer role that I tested and it works. Having project scoped role is impossible now because images are cluster-scope resource (you can't give power to non-privileged user to have access to modify signature for all images).
