### ISSUE TITLE
oc cluster up   fails if ipv6.disable=1

### ISSUE THREAD

**Issue by fche** [openshift/origin#10850]
On a Fedora24 host that runs with ipv6.disable=1 (so no ipv6 support), docker etc. all run fine.  But the oc-client-tools binary is unhappy:

##### Version
oc v1.3.0-alpha.1
kubernetes v1.3.0-alpha.1-331-g0522e63
docker-1.12.0-6.gitad4812e.fc26.x86_64 rpm   (because f24 base one fails without ipv6)

##### Steps To Reproduce
# oc cluster up

##### Current Result
-- Checking Docker client ... OK
-- Checking for existing OpenShift container ... OK
-- Checking for openshift/origin:latest image ... OK
-- Checking Docker daemon configuration ... OK
-- Checking for available ports ... FAIL
   Error: Cannot get TCP port information from Kubernetes host
   Caused By:
     Error: Docker run error rc=1
     Details:
       Image: openshift/origin:latest
       Entrypoint: [/bin/bash]
       Command: [-c cat /proc/net/tcp /proc/net/tcp6]
[....] 
      Error Output:
         cat: /proc/net/tcp6: No such file or directory

**Comment by jawnsy** [comment]
Seems like this affects a few places of our code: https://github.com/openshift/origin/search?q=%2Fproc%2Fnet%2Ftcp6&type=Code

@fche While we look into this, can you work around the problem by using `ipv6.disable_ipv6=1` instead of `ipv6.disable`? This re-enables the IPv6 stack but prevents addresses from being assigned to your interfaces, documented here: https://www.kernel.org/doc/Documentation/networking/ipv6.txt
