### ISSUE TITLE
oc cluster up: a random password should be generated instead of using "AllowAll" provider

### ISSUE THREAD

**Issue by jawnsy** [openshift/origin#10919]
When running `oc cluster up`, the `AllowAll` provider is used by default (it may be because no `master-config.yaml` is generated, so this is the default for origin itself).  As a result, we currently rely on external security mechanisms like AWS Security Groups or local network firewalls (under the assumption that users will run the command on servers on their intranet) to prevent malicious users from using the cluster.

It may be a good idea to generate a random password for the `developer` account, then print that on the console as we currently do. It would be helpful to provide better security.

**Comment by jawnsy** [comment]
@csrwng If you think this would be a good idea, please assign this to me and give me some pointers for how to implement :)

**Comment by GrahamDumpleton** [comment]
People will forget a random password, so if there was an option such that a prompt could be put up to enter the password that might be better. That or provide an easy way to change the password. So output random password and then print the command to run to easily change it.

**Comment by smarterclayton** [comment]
The only password option built in would be htpasswd - I'm not sure it's useful to configure that particularly, but it's all we have.

**Comment by GrahamDumpleton** [comment]
Using htpasswd is sufficient. Better that than current situation of being accessible from outside of machine with a default password you can't change.

**Comment by marekjelen** [comment]
There could be two options

--user=developer
--password=developer

those would be the input to generate the htpasswd. For the --password there would ideally be 3 options

1) no --password specified ... uses "developer" as a default password
2) --password (without any value) ... prompts the user for password
3) --password=something ... takes "something" as a password

@jawnsy agree with @GrahamDumpleton that random password is not that useful

@smarterclayton htpasswd is enough for our use-case

**Comment by smarterclayton** [comment]
We're trying to keep the CLI options limited.  If we need to generate this, we should generate it into the htpasswd and report it back to the user instead of the default "developer" password.  If you need to set more, you can exec in and use existing htpasswd setup.  Since this will be in the kubeconfig we copy back it won't unduly complicate scripting (although you'll want to ensure that we set the permissions correctly on the file).

**Comment by jorgemoralespou** [comment]
@smarterclayton if you (we) want to promote "oc cluster up" as a tool for developers (which I totally want) we need to provide it with more usability capabilities, like this one.
I have discussed this with @csrwng during this past week, and I would hope/like that we can start bringing all the different options we have to 1 (or at most 2 including minishift). That means that I would expect some developers (those that can run Docker native) that create applications on OpenShift to use "oc cluster up" as their local development environment in some form. For this happen, in my mind, it needs to be dead simple for developers to use the basic features, like this one. I would otherwise argue that "oc login <cluster_ip> -u user -p password" is the same.
 
I understand that too many commands are not what we would like, but I would rather have a tool with flexibility and sane defaults, that most of the time I would use, but that I could easily change if I need to because of having some concerns, like SECURITY.

**Comment by csrwng** [comment]
Pull https://github.com/openshift/origin/pull/11146 should help this use case by not trying to initialize the user when you configure a different user provider.

**Comment by csrwng** [comment]
Created a trello card for this:
https://trello.com/c/foGGNMTt/1142-cluster-up-use-the-htpasswd-provider-and-generate-a-password-on-startup
