### ISSUE TITLE
Problem deploying metrics. When deploying openshift metrics it never deploys hawkular-cassandra pods. 

### ISSUE THREAD

**Issue by born2fail** [openshift/origin#10948]
When deploying openshift metrics with the default template (oc new-app -f metrics-deployer.yaml) it never deploys hawkular-cassandra pods. 

Executing 
   _oc logs -f metrics-deployer-2dug5_
We get this log:
```
persistentvolumeclaim "metrics-cassandra-1" created

The ReplicationController "hawkular-cassandra-1" is invalid.

* spec.template.spec.containers[0].env[2].valueFrom: Invalid value: "": may not have more than one field specified at a time
* spec.template.spec.containers[0].env[3].valueFrom: Invalid value: "": may not have more than one field specified at a time
``` 

And hawkular-cassandra pod(s) is nerver deployed

##### Version
openshift version
   openshift v1.2.1
   kubernetes v1.2.0-36-g4a3f9c5
   etcd 2.2.5
oc version
   oc v1.2.1
   kubernetes v1.2.0-36-g4a3f9c5

##### Steps To Reproduce
1. oc new-app -f metrics-deployer.yaml 

##### Current Result
hawkular-cassandra pods are never deployed
##### Expected Result
Full deployment of metrics stack

**Comment by mwringe** [comment]
You are running the 'latest' origin-metric images on a non-latest OpenShift Origin. These images are using features which are only available in the latest OpenShift Origin which is why you are running into this problem.

Please run the version of 'origin-metrics' designed for your version of OpenShift Origin.

You will need to set the "IMAGE_VERSION" template parameter to the version of Origin you are running (the list of available tags are available here: https://hub.docker.com/r/openshift/origin-metrics-deployer/tags/)
