### ISSUE TITLE
Usability: Console Overview doesn't show object details in a lateral bar / topology view

### ISSUE THREAD

**Issue by rafabene** [openshift/origin#10966]
In OpenShift 1.2 console (Overview) I was able to click on top of objects (Service / Route / DC / etc) and get its details (labels, ip, etc). Now In OpenShift 1.3 I must open the object details page to get those information.

I also could find that "details" lateral bar in the "topology view". Any plans to have it back to openshift 1.3+ ?

I'd like to suggest that we have a foldable lateral pane (Just like the "Monitoring") so we can see the Object details without opening the object page.
##### Version

```
oc v1.3.0
kubernetes v1.3.0+52492b4
features: Basic-Auth

Server https://192.168.64.10:8443
openshift v1.3.0
kubernetes v1.3.0+52492b4
```
##### Steps To Reproduce
1. Open Origin 1.3 console
2. Deploy any application

**Comment by jwforres** [comment]
The right sidebar details caused more usability problems than it solved, we only heard complaints about it, and it was only implemented originally because we did not have individual details pages at the time.  It took up way too much space to make it remotely usable, it was still unreadable at certain sizes, we had to take it away completely for mobile.  Add to that that its a headache to maintain because it must be kept separate from the details pages because its a different format so it requires a different layout.

Instead of immediately jumping to try to bring it back, I'd rather have a discussion about what information you feel is missing from the overview that you really need to stay in context to see vs going to the detailed page.

**Comment by jwforres** [comment]
cc @spadgett

**Comment by rafabene** [comment]
I miss Labels (for every object) first and Pod IP address (In topology view) in second.

**Comment by jwforres** [comment]
linking this discussion into the relevant trello card https://trello.com/c/6s7TGjr3
