### ISSUE TITLE
Deployment From IS

### ISSUE THREAD

**Issue by mangirdaz** [openshift/origin#10981]
I want to be able to do deployment from IS, so I can use Image streams as a abstraction.
##### Version

```
[vagrant@10 ~]$ oc version
Server https://localhost:8443
openshift v1.3.0-rc1
kubernetes v1.3.0+52492b4
```
##### Steps To Reproduce
1. Create Deployment config, and point container component to Image steam. 
2. Deployment fails due native POD description uses image as a reference, and not IS
   (Dont use Build, just Deployment config)
   ##### Current Result
   Deployment can be done from image reference only, and IS.
##### Expected Result

Use of IS streams and Images
##### Additional Information

IS:

``` json
{
   "kind":"ImageStream",
   "apiVersion":"v1",
   "metadata":{
      "name":"gotest",
      "creationTimestamp":null,
      "annotations":{
         "openshift.io/image.insecureRepository":"true"
      }
   },
   "spec":{
      "tags":[
         {
            "name":"v0.1",
            "annotations":{
               "description":"Provides a IS"
            },
            "from":{
               "kind":"DockerImage",
               "name":"mangirdas/test-go-app:v0.1"
            },
            "importPolicy":{
               "insecure":true
            }
         },
         {
            "name":"latest",
            "from":{
               "kind":"ImageStreamTag",
               "name":"v0.1"
            },
            "importPolicy":{
               "insecure":true
            }
         }
      ]
   }
}
```

Deployment Expected:

``` json
{
   "kind":"DeploymentConfig",
   "apiVersion":"v1",
   "metadata":{
      "name":"gotest",
      "creationTimestamp":null
   },
   "spec":{
      "strategy":{
         "type":"Rolling",
         "rollingParams":{
            "updatePeriodSeconds":1,
            "intervalSeconds":1,
            "timeoutSeconds":120
         },
         "resources":{

         }
      },
      "triggers":[
         {
            "type":"ImageChange",
            "imageChangeParams":{
               "automatic":true,
               "containerNames":[
                  "test-app"
               ],
               "from":{
                  "kind":"ImageStreamTag",
                  "name":"gotest:latest"
               }
            }
         },
         {
            "type":"ConfigChange"
         }
      ],
      "replicas":5,
      "selector":{
         "name":"gotest"
      },
      "template":{
         "metadata":{
            "creationTimestamp":null,
            "labels":{
               "name":"gotest"
            }
         },
         "spec":{
            "containers":[
               {
                  "name":"gotest",
                  "image":"gotest:latest",
                  "kind":"ImageStreamTag",
                  "ports":[
                     {
                        "containerPort":8080,
                        "protocol":"TCP"
                     }
                  ],
                  "resources":{

                  },
                  "terminationMessagePath":"/dev/termination-log",
                  "imagePullPolicy":"IfNotPresent",
                  "securityContext":{
                     "capabilities":{

                     },
                     "privileged":false
                  }
               }
            ],
            "restartPolicy":"Always",
            "dnsPolicy":"ClusterFirst"
         }
      }
   },
   "status":{

   }
}
```

**Comment by kargakis** [comment]
The container name you are using inside your image change trigger should be `gotest` instead of `test-app`, right? Also container spec doesn't include a "kind", did you add it manually there as the expected result you wanted to see?

**Comment by Mangirdaz** [comment]
So kind was added as a "example"... I'm not interested in triggers, as they work (i needed to remove them from copy paste, sorry). This code snip is interesting for me:
```
 {
                  "name":"gotest",
                  "image":"gotest:latest",
                  "kind":"ImageStreamTag",
                  "ports":[
                     {
                        "containerPort":8080,
                        "protocol":"TCP"
                     }
````

 I want to be able to refer to IS in my container definition and not external image stream.  I think when we do S2I, because there is internal registry added and we producing the image, its being picked up by deployment config. If I want to create image stream and refer it in DC it does not work. 

So if i dont use latest tag, but versions, i have to change by DC each time when i want to update version.

**Comment by Mangirdaz** [comment]
More simple example:
https://gist.github.com/Mangirdaz/dd8fe96bb93fed7e673b47f0b9d8c320

And expectation would be that OSE would check first IS for image and later go for external registry. Result now:

```
 FirstSeen	LastSeen	Count	From			SubobjectPath		Type		Reason		Message
  ---------	--------	-----	----			-------------		--------	------		-------
  17s		17s		1	{default-scheduler }				Normal		Scheduled	Successfully assigned gotest-2-4qmge to origin
  13s		13s		1	{kubelet origin}	spec.containers{gotest}	Warning		Failed		Failed to pull image "gotest:latest": Error: image library/gotest not found
  13s		13s		1	{kubelet origin}				Warning		FailedSync	Error syncing pod, skipping: failed to "StartContainer" for "gotest" with ErrImagePull: "Error: image library/gotest not found"

  12s	12s	1	{kubelet origin}	spec.containers{gotest}	Normal	BackOff		Back-off pulling image "gotest:latest"
  12s	12s	1	{kubelet origin}				Warning	FailedSync	Error syncing pod, skipping: failed to "StartContainer" for "gotest" with ImagePullBackOff: "Back-off pulling image \"gotest:latest\""

  15s	1s	2	{kubelet origin}	spec.containers{gotest}	Normal	Pulling	pulling image "gotest:latest"
[vagrant@10 ~]$ oc get is

```

**Comment by kargakis** [comment]
It's not possible to use ImageStreamTag references inside the container spec since the container spec comes from Kubernetes and Kubernetes has no notion of ImageStreamTags. 

You should be able to use ImageChangeTriggers as you already have in the deployment config. If you want to use a specific version of an image, you need to specify that version inside your ImageChangeTrigger from.name (and you also need the correct container name inisde your trigger, your example has a wrong name).

Can you paste the exact commands you are using for "If I want to create image stream and refer it in DC it does not work. "?

**Comment by Mangirdaz** [comment]
the thing I want to achieve is to point all DC to IS for deployment. Now as it comes from K8S space it works just with full image name from "external" registry. And I would like to use name from IS abstraction. Same as BC does.

I think this may not even be possible without up-streaming IS to k8s first...

**Comment by kargakis** [comment]
But we have ImageChangeTriggers for that :) It's still not clear to me why you can't use them.

**Comment by Mangirdaz** [comment]
Long story short. We are working on Multi-cluster deployment, where we want to have one point of contact when changing versions in the environments. IS makes very good abstraction for that as you can point your different versions of images directly to latest and in theory never modify your DC. So when new version of app appears you just change where latest points in IS and you are done.

Yes, we still can use trigger, but this implies us that we using latest tag for app versioning - and latest tag is MOST EVIL thing even created by docker (next ones following would be docker daemon, and Dockerfile)

But looks like for now we will have to use versions in the DC for images, and when our image build pipeline will get mature, we will migrate to "latest" and controlling with IS.

Having this all in mind hypothetical situation:
1. My DC points to image mangirdas/gotest:latest
2. My trigger set is for gotest:latest IS
3.I update image latest so my app is being triggered. 
4. My app is with failure and containers does not start, so automatic rollback kicks in...
5. because I didint changed my config to what it will rollback??? as my latest is already tagged. 

So only way to recover is to to version - 1 in DC for the version where my "latest" points to...

**Comment by kargakis** [comment]
> 1. My DC points to image mangirdas/gotest:latest
> 2. My trigger set is for gotest:latest IS

You don't need to set the container image if you have set an ImageChangeTrigger.

>  3.I update image latest so my app is being triggered. 

Mind clarifying how do you update the image? New build pushing to the registry or you just import an updated image?

> 4. My app is with failure and containers does not start, so automatic rollback kicks in...

What's the failure here? ImagePullBackOff?

> 5. because I didint changed my config to what it will rollback??? as my latest is already tagged. 

If you had a running instanse of your DC previously, it would rollback into that - if you don't then it will just scale down to zero. We are going to make autoRollback configurable so you may opt-out if you wish.

**Comment by Mangirdaz** [comment]
Ok, with my hypothetical question Im going sideways with this ticket. 
My goal would be to to use IS in DC for deployments, and not only triggers. But this is not possible apparently.  

For the second peace - this involves enhancing our App image build pipeline a lot. But looks like this is what we will need to do. 

So if you think Deployment from Imagestream (using IS abstraction) will not gonna happen due K8s dependencies, we can close this ticket. 
As other one is to reclassify as as enhancement. If so, i can provide detail flow what I want to achieve...

**Comment by kargakis** [comment]
> As other one is to reclassify as as enhancement. If so, i can provide detail flow what I want to achieve...

Please do, because it's still not clear to me why using an ImageChangeTrigger over a straight IS reference in the pod template doesn't work for you. ImageChangeTriggers are providing exactly the abstraction you are looking for.

**Comment by Mangirdaz** [comment]
for first assume we have Image streams:
https://gist.github.com/Mangirdaz/7ee724e8f1cc0b45769396ee9d132146
And when my new app version is created I just update IS:
```
Now: v0.1 -> latest. 
after release: v0.2 -> latest
```
So we life-cycle application using  IS only. So we point all configuration always to latest when in the background its being rotated version by version.

Expectation: 
DC:
https://gist.github.com/Mangirdaz/79dbf69995102b674fc77851feea4ba5

In our DC instead of pointing to: ```mangirdas/go-test-app:latest``` we point to IS abstraction ```gotest:latest``` . So when we change IS latest to point to v0.2 of our app, trigger is being triggered and DC is being redeployed from from new image.... So we change one IS reference and we have new deployment

Now:
We have same IS as we had in example one. But additionally we are forced to use image tag latest. So as we create new image v0.2 we tag it as tag latest,

and we point our DC to:
```
"image":"mangirdas/go-test-app:latest"
```
All this works just fine, but we are forced to use tag latest, which is confusing, and misleading overall. We are trying to have one point of interaction and not to use latest tag for our image, and use it only in the abstraction layer.

**Comment by mikz** [comment]
I think I have another compelling reason why to use IS outside of deployment. It is not possible to use PetSet or Job inside DeploymentConfig. 

So following config https://gist.github.com/mikz/fb338a52e4ba68c904c25ceda34c0809 has BuildConfig to create ImageStream, PetSet and a Job. 

I don't see a way of creating a Template, that can be reused and using PetSet or Job with ImageStream, just because it always uses external repository instead of the internal one.

The use case might be different, but the underlying issue is the same IMO.

**Comment by Mangirdaz** [comment]
I think both cases are valid. I just expressing my current organisation finding. So if this will happen, we will be happy, if no - ou well... :D 
I personally like this separation, but at the same time ability to shape CI&CD flow as per organisation need is good thing too.

**Comment by kargakis** [comment]
@mangirdaz is https://github.com/kubernetes/kubernetes/issues/33664 the same thing as what you are asking here?

**Comment by kargakis** [comment]
This is explicitly not a goal for upstream and for OpenShift, image stream flows should suffice.
