### ISSUE TITLE
digest is different for same image with different tags

### ISSUE THREAD

**Issue by lorenzvth7** [openshift/origin#10992]
digest is different for same images with different tag in OpenShift origin

##### Version
```
oc v1.2.0
kubernetes v1.2.0-36-g4a3f9c5
```

```
Client:
 Version:         1.10.3
 API version:     1.22
 Package version: docker-common-1.10.3-46.el7.centos.10.x86_64
 Go version:      go1.6.3
 Git commit:      d381c64-unsupported
 Built:           Thu Aug  4 13:21:17 2016
 OS/Arch:         linux/amd64
```

##### Steps To Reproduce
1. Jenkins (outside openshift environment) is building an image with tag `1.0`
2. We also tag that image with `latest` (the digest of the image is the same)
Images are just the same, same digest, different tag
```
image                                                                         1.0                   69a777edb6dc        5 weeks ago         643 MB
image                                                                         latest              69a777edb6dc        5 weeks ago         643 MB
```
3. Than we push both images to our OpenShift Docker Registry (on the environment)

##### Current Result
Images have different digest, but are just the same except a different tag. (so when we're taking a look to the image stream in our project we see the 2 images. Pushed on the same time, different tag but also different digest)

##### Expected Result
I would expect the images have the same digest. Okay I would accept the fact the digest on Jenkins isn't the same as on openshift because we use docker 1.12 on jenkins and RH docker 1.10 on OpenShift. But we will still expect the digest to be the same for the same image.

##### Additional Information
When we push the image (with 2 tags) to a normal Docker Registry (also on 1.12) than the digest remains the same.

**Comment by miminar** [comment]
It happens because OpenShift Docker registry does not accept manifest V2 schema 2 by default. In case of oc v1.2.0, it's not possible to store it at all (it may be later if we backport registry 2.4).

The Docker client converts the image to manifest V2 schema 1 and pushes it. As documented in [upstream documentation](https://github.com/docker/distribution/blob/master/docs/spec/manifest-v2-1.md#manifest-field-descriptions), the old schema contains name and tag. Which means, any change to these two attributes results in a different manifest and therefor different manifest digest.

If you want your manifest digest to stay the same regardless of the istag, you can use `oc tag` to give the image different aliases once pushed to the registry.

Or you can update to 1.3 and [instruct registry to accept schema 2](https://docs.openshift.org/latest/install_config/registry/extended_registry_configuration.html#docker-registry-configuration-reference-middleware) which is content addressable (neither name nor tag will affect resulting manifest digest).

**Comment by miminar** [comment]
Closing this. Feel free to re-open if provided information doesn't work for you.
