### ISSUE TITLE
Cleanup policy for builds

### ISSUE THREAD

**Issue by kargakis** [openshift/origin#11072]
I want to limit the number of old builds kept in my project and since pruning is a manual task run by an  administrator (or even automated via a scheduled job that I have no idea when it's executed) I want my old builds to be automatically cleaned up similar to how revisionHistoryLimit works for deployment configs.

@bparees I think there is a subtle difference between this and pruning since regural users won't be able to run prune.

cc: @mfojtik @smarterclayton

**Comment by smarterclayton** [comment]
Why can't regular users prune builds in their namespace?

**Comment by kargakis** [comment]
> Why can't regular users prune builds in their namespace?

Do they get to use `oadm`?

**Comment by kargakis** [comment]
```
$ oadm prune builds
Error from server: User "developer" cannot list all buildconfigs in the cluster
```

I guess we could fix prune to work on separate namespaces but then users would either need to manually prune or take an extra step and setup a scheduled job for automating it. What I was shooting for is the more fine-grained cleanup policy we have for deployments ie. you can pick up which build configs you want pruned. With a sensible default users will never really need to care about pruning.

**Comment by smarterclayton** [comment]
What happens if you specify --namespace?  We had an issue open on that.  I
thought DC prune supported it.

On Sep 23, 2016, at 10:44 AM, Michail Kargakis <notifications@github.com>
wrote:

$ oadm prune builds
Error from server: User "developer" cannot list all buildconfigs in the cluster

I guess we could fix prune to work on separate namespaces but then users
would either need to manually prune or take an extra step and setup a
scheduled job for automating it. What I was shooting for is the more
fine-grained cleanup policy we have for deployments ie. you can pick up
which build configs you want pruned. With a sensible default users will
never really need to care about pruning.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/origin/issues/11072#issuecomment-249212017>,
or mute the thread

**Comment by bparees** [comment]
trello.

**Comment by kargakis** [comment]
Trello'd: https://trello.com/c/048p7YRO/1044-cleanup-policy-for-builds

**Comment by kargakis** [comment]
cc: @csrwng what I was talking about in scrum today
