### ISSUE TITLE
time in my "origin" continer does not match time on host

### ISSUE THREAD

**Issue by jorgemoralespou** [openshift/origin#11083]
When running "oc cluster up" I see that all the times of the logging don't match the time of the system openshift is running on. 
What would be the way to have time synched? Using environment variables to oc cluster up?

**Comment by jorgemoralespou** [comment]
Restarting docker daemon on my mac OSX has synchronized time with my host.

**Comment by jorgemoralespou** [comment]
Also, is it possible to set a specific TZ, like "Europe/Madrid" so that time shows in my TZ (the same as my host) and not as UTC?

**Comment by csrwng** [comment]
@jorgemoralespou this seems to be a known issue with Docker for Mac: https://forums.docker.com/t/time-in-container-is-out-of-sync/16566. My preference would be that it get fixed on the Docker side instead of us introducing a workaround in cluster up.

For the timezone, you can pass the TZ variable with '-e' to cluster up
