### ISSUE TITLE
"Crash loop backoff " pod creating and destroying  continiously

### ISSUE THREAD

**Issue by hachiko21** [openshift/origin#11156]
[provide a description of the issue]

docker version : v1.12.1
oc version : v1.3.0
##### Version

[provide output of the `openshift version` or `oc version` command]
##### Steps To Reproduce
1. [step 1]
2. [step 2]
##### Additional Information

[try to run `$ oadm diagnostics` command if possible]
[if you are reporting issue related to builds, provide build logs with `BUILD_LOGLEVEL=5`]
[consider attaching output of the `$ oc get all -o json -n <namespace>` command to the issue]
[visit https://docs.openshift.org/latest/welcome/index.html]

**Comment by derekwaynecarr** [comment]
can you provide more info?

have you tried `oc debug`?

**Comment by gvm1111** [comment]
I've seen the same issue with Openshift Container Platform (3.6 currently).
If you set these 2 env variables in lowercase (e.g. debug instead of DEBUG) the pods will crash continuously without any explanation:

CURATOR_SCRIPT_LOG_LEVEL
CURATOR_LOG_LEVEL

I'm not sure this is the same issue but I got here by searching the error I got so I thought it might help someone else.
