### ISSUE TITLE
`make release` fails trying to find a directory under _output on a clean checkout

### ISSUE THREAD

**Issue by stevekuznetsov** [openshift/origin#11205]
Seeing this:

```
$ ssh openshiftdevel -C 'tree /data/src/github.com/openshift/origin/_output/'
/data/src/github.com/openshift/origin/_output
├── buildenv-context
└── local

2 directories, 0 files

$ ssh openshiftdevel -C 'mkdir -p /data/src/github.com/openshift/origin/_output/local/releases'

$ ssh openshiftdevel -C 'tree /data/src/github.com/openshift/origin/_output/'
/data/src/github.com/openshift/origin/_output
├── buildenv-context
└── local
    └── releases

3 directories, 0 files

$ oct make origin release
FAILURE | PLAYBOOK [main.yml] ------------------------------------------------------------------------------------------------------------ [07:12.038]
SUCCESS | PLAY [ensure we have the parameters necessary to execute a make target or targets] --------------------------------------------- [00:00.060]
FAILURE | PLAY [execute a make target or targets on the remote host] --------------------------------------------------------------------- [07:11.976]
FAILURE | TASK [make : execute make target(s) "release" in the origin repository] -------------------------------------------------------- [07:11.061]
A task failed on host `openshiftdevel`!
One or more items failed
The following error messages came from items:
...
Error response from daemon: lstat /var/lib/docker/devicemapper/mnt/d072cf4e8e17f1c1ea7daa4f0b93c78745f0d5c8590ef9e8c20532018a81df72/rootfs/go/src/github.com/openshift/origin/_output/local/releases: no such file or directory
[ERROR] PID 30631: hack/common.sh:1167: `docker cp "${container}:${workingdir}/${path}" "${parent}"` exited with status 1.
[INFO]      Stack Trace: 
[INFO]        1: hack/common.sh:1167: `docker cp "${container}:${workingdir}/${path}" "${parent}"`
[INFO]        2: hack/common.sh:1197: os::build::environment::start
[INFO]        3: hack/build-release.sh:27: os::build::environment::withsource
[INFO]   Exiting with code 1.
make: *** [release] Error 1

$ ssh openshiftdevel -C 'tree /data/src/github.com/openshift/origin/_output'
/data/src/github.com/openshift/origin/_output
├── buildenv-context
└── local

2 directories, 0 files
```

**Comment by smarterclayton** [comment]
What's special about your run?

On Oct 4, 2016, at 8:18 AM, Steve Kuznetsov <notifications@github.com>
wrote:

Seeing this:

$ tree _output/
_output/
├── buildenv-context
└── local

2 directories, 0 files

$ mkdir _output/local/releases

$ tree _output/
_output/
├── buildenv-context
└── local
    └── releases

3 directories, 0 files

$ oct make origin release
FAILURE | PLAYBOOK [main.yml]
------------------------------------------------------------------------------------------------------------
[07:12.038]
SUCCESS | PLAY [ensure we have the parameters necessary to execute a
make target or targets] ---------------------------------------------
[00:00.060]
FAILURE | PLAY [execute a make target or targets on the remote host]
---------------------------------------------------------------------
[07:11.976]
FAILURE | TASK [make : execute make target(s) "release" in the origin
repository] --------------------------------------------------------
[07:11.061]
A task failed on host `openshiftdevel`!
One or more items failed
The following error messages came from items:
...
Error response from daemon: lstat
/var/lib/docker/devicemapper/mnt/d072cf4e8e17f1c1ea7daa4f0b93c78745f0d5c8590ef9e8c20532018a81df72/rootfs/go/src/github.com/openshift/origin/_output/local/releases:
no such file or directory
[ERROR] PID 30631: hack/common.sh:1167: `docker cp
"${container}:${workingdir}/${path}" "${parent}"` exited with status
1.
[INFO]      Stack Trace:
[INFO]        1: hack/common.sh:1167: `docker cp
"${container}:${workingdir}/${path}" "${parent}"`
[INFO]        2: hack/common.sh:1197: os::build::environment::start
[INFO]        3: hack/build-release.sh:27: os::build::environment::withsource
[INFO]   Exiting with code 1.
make: *** [release] Error 1

$ ssh openshiftdevel -C 'tree /data/src/github.com/openshift/origin/_output'
/data/src/github.com/openshift/origin/_output
├── buildenv-context
└── local

2 directories, 0 files

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/origin/issues/11205>, or mute the thread

**Comment by stevekuznetsov** [comment]
Unclear what is special, it's not happening to me locally.

You can see what happens to the VM in the `origin-ci-tool` repo, but nothing crazy -- I check out the repo, sync it to my remote branch, then run the make target and WHAM issue as above.

**Comment by stevekuznetsov** [comment]
No longer an issue.
