### ISSUE TITLE
oc create doesn't honour -o json in same way that oc new-app does.

### ISSUE THREAD

**Issue by GrahamDumpleton** [openshift/origin#11242]
When you run `oc new-app` and use the `-o json` option it will run checks to see if the application creation might work, but doesn't actually do it, instead outputting what would be created in the format requested by the `-o` option, JSON in this case.

If you use `oc create`, qualifying it with the type of resource you want to create, such as a `route` and use `-o json`, then it goes off and creates the resource anyway and doesn't output anything.

I would expect, and I believe it would be much more useful, if `-o json` worked the same was as `oc new-app` when when using `oc create` to create specific resources. Thus for example, running:

```
oc create route edge myapp-ssl --service myapp --hostname example.com -o json 
```

should do nothing except output the JSON definition of what would be created.

This would be useful for validating what gets created is what you intend to be created before you do it, but also that it provides a good way of creating definitions for specific scenarios, which you could then cut and paste what would be created, into a template.

I use `route` here as an example but expect that this could be applied to all resources `oc create` can explicitly create.

I can't see that this would conflict with existing usage of `-o` option and in fact `-o` on `oc new-app` already seems to be overloaded in that can be `name` for succinct output of what would be created, and `json` or `yaml` to give definition of what would be created but don't do anything.

**Comment by fabianofranz** [comment]
So, this is an important issue because we are *very* inconsistent today. 

The way upstream commands (like `run`, `create`, and others) work (and how everything should work in my opinion) is 

* `--output` flag *only* specifies how the output of the running command will look like, but it doesn't affect in executing the action on not.
* `--dry-run` is what must be used to not really execute the action and it can be used with `--output`, a very common use case is `--dry-run --output=json` to check what would be created, copy and paste into template, etc.

Problem is, we have a number of commands where `--output=<mode>` *does not execute* but behaves like `--dry-run --output=<mode>`. To name a few, `new-app`, `new-build`, `rollback`, `set env`, `set volumes` (but not `set image`, `set deployment-hook`), and others.

But there's backwards compatibility.

@juanvallejo can you link the `--dry-run` work you are doing?
@bparees @csrwng @smarterclayton

**Comment by juanvallejo** [comment]
@fabianofranz 
> @juanvallejo can you link the --dry-run work you are doing?

Sure:
- Upstream: [adding `--dry-run` option to `kubectl apply`](https://github.com/kubernetes/kubernetes/pull/34028) (soon to be expanded to `kubectl create` sub-commands as well)
- Downstream: [adding `--dry-run` to remaining `oc create` su-commands](https://github.com/openshift/origin/pull/11238)

**Comment by smarterclayton** [comment]
We will not break back compact on create or new-app for a long time, so
let's find work arounds.

**Comment by GrahamDumpleton** [comment]
The only way to avoid backward compatibility issues would be to keep that if ``-o json`` or ``-o yaml`` is used that it implies ``--dry-run``. The ``--dry-run`` option wouldn't be redundant as still may want that just to check things if not explicitly asking for json/yaml of resources created to be output.

**Comment by juanvallejo** [comment]
Also related PR (adds `oc create` support for output formats other than `name`): https://github.com/openshift/origin/pull/12015

**Comment by soltysh** [comment]
This should be fixed by now
/remove-lifecycle frozen
/close
