### ISSUE TITLE
oc cluster up - cluster-admin role for user admin by default

### ISSUE THREAD

**Issue by rettori** [openshift/origin#11297]
Since the main purpose of oc cluster up is to be an easy openshift starter with  most of the defaults filled it, it would be helpful to have the 'cluster-admin' role assigned to the 'admin' user by default. 

I order to do this today, you have to:

$ oc login -u system:admin
$ oc adm policy add-cluster-role-to-user cluster-admin admin

ideal scenario would be:

# do nothing :-)

D.

**Comment by rettori** [comment]
@csrwng :-)

**Comment by GrahamDumpleton** [comment]
In the wrapper script Jorge wrote, the ``developer`` is given ``sudoer`` role rather than full admin rights. This is a bit safer but not as onerous as switching user.

* https://github.com/openshift-evangelists/oc-cluster-wrapper

Even so, this should probably not be the default, but left to wrapper scripts which build on extra functionality to suit different use cases.

**Comment by liggitt** [comment]
Definitely not a default, especially if we want cluster up to mimic normal usage of the platform

**Comment by rettori** [comment]
@liggitt so oc cluster up's objective is **not** to be a fast start with sensible defaults for development use?

**Comment by liggitt** [comment]
> @liggitt so oc cluster up's objective is not to be a fast start with sensible defaults for development use?

it is the objective, but running commands as a project-scoped user with cluster-admin permissions is not a sensible default, since no deployment actually works that way

**Comment by csrwng** [comment]
@rettori I'm going to close this issue ... doesn't look like it's a wise thing to do. Besides what @liggitt mentioned, we'd be potentially exposing your machine to root access without you realizing it.
