### ISSUE TITLE
PROPOSAL: Define edge kinds as types rather than const strings

### ISSUE THREAD

**Issue by juanvallejo** [openshift/origin#11415]
Right now, graph edge kinds are defined using [constant strings](https://github.com/openshift/origin/blob/master/pkg/deploy/graph/edges.go#L18-L24).

Defining different kinds as types would allow sub-typing of edges that overlap, such as [ControllerRefEdgeKinds](https://github.com/openshift/origin/pull/10363/files#diff-b07a99ef8e53f1d967e2a072b5b5272fR25) and [DeploymentEdgeKinds](https://github.com/openshift/origin/blob/master/pkg/deploy/graph/edges.go#L22) preventing situations [such as this one](https://github.com/openshift/origin/pull/10363/files#diff-b07a99ef8e53f1d967e2a072b5b5272fR77).

cc @openshift/cli-review @deads2k @stevekuznetsov @liggitt @smarterclayton

**Comment by deads2k** [comment]
I'm not opposed, but I don't see this as a blocker.

**Comment by smarterclayton** [comment]
Real graphs use edge types and multiple edges.  Why do we need types?

On Oct 18, 2016, at 1:34 PM, Juan Vallejo <notifications@github.com> wrote:

Right now, graph edge kinds are defined using constant strings
<https://github.com/openshift/origin/blob/master/pkg/deploy/graph/edges.go#L18-L24>
.

Defining different kinds as types would allow sub-typing of edges that
overlap, such as ControllerRefEdgeKinds
<https://github.com/openshift/origin/pull/10363/files#diff-b07a99ef8e53f1d967e2a072b5b5272fR25>
and DeploymentEdgeKinds
<https://github.com/openshift/origin/blob/master/pkg/deploy/graph/edges.go#L22>
preventing situations such as this one
<https://github.com/openshift/origin/pull/10363/files#diff-b07a99ef8e53f1d967e2a072b5b5272fR77>
.

cc @openshift/cli-review
<https://github.com/orgs/openshift/teams/cli-review> @deads2k
<https://github.com/deads2k> @stevekuznetsov
<https://github.com/stevekuznetsov> @liggitt <https://github.com/liggitt>
@smarterclayton <https://github.com/smarterclayton>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/origin/issues/11415>, or mute the thread

**Comment by juanvallejo** [comment]
@smarterclayton 
> Real graphs use edge types and multiple edges.  Why do we need types?

We would still have multiple kinds per edge, and they'd still be strings, they could just be typed to allow for some form of hierarchy among them. `DeploymentEdgeKind`s and `ManagedByControllerEdgeKind`s could both implement an interface `ControllerRefEdgeKind`, or something similar to this. WDYT?
