### ISSUE TITLE
flake: test_pull_requests_origin_integration timed out after 3 hrs

### ISSUE THREAD

**Issue by csrwng** [openshift/origin#11438]
No other errors are discernible from the log, the build just timed out after 3 hrs:
https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_integration/7304/

**Comment by stevekuznetsov** [comment]
Something seems to have gone wrong internally -- we do not have good metrics for these runs so it's hard to say. The integration tests all ran and succeeded but we don't have jUnit entries (still on my TODO) so we don't know if they were slower than usual. The e2e tests seem to have run in normal time. Perhaps the Docker build at the start took very long? Unclear. @danmcp if we see this a lot, other than my spending time to implement the integration test jUnit stuff, we could just bump the time since we get no logs this way.

**Comment by danmcp** [comment]
@stevekuznetsov Bump the time to what?  It normally takes less than 1.5 hours.  Double the time is already a big buffer.

**Comment by stevekuznetsov** [comment]
@danmcp six hours? Who knows. Or we should figure out a way to get the logs out of there before we nuke the instance.
