### ISSUE TITLE
Error: unknown command "cluster" for "oc"

### ISSUE THREAD

**Issue by mkjsix** [openshift/origin#11509]
I can't run the "oc cluster up" command on Linux Ubuntu 16.04

```
$ uname -a
Linux ubuntu-VirtualBox 4.4.0-45-generic #66-Ubuntu SMP Wed Oct 19 14:12:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

$ docker version
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   23cf638
 Built:        Tue, 27 Sep 2016 12:25:38 +1300
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   23cf638
 Built:        Tue, 27 Sep 2016 12:25:38 +1300
 OS/Arch:      linux/amd64
```

##### Version
oc v1.2.2
kubernetes v1.2.0-36-g4a3f9c5

##### Steps To Reproduce
1. run the command "oc cluster up"

##### Current Result
Error: unknown command "cluster" for "oc"
Run 'oc --help' for usage.

##### Expected Result
I'd expect the cluster to go up, as per https://github.com/openshift/origin/blob/master/docs/cluster_up_down.md#linux

**Comment by coreydaley** [comment]
@mkjsix , 'oc cluster' was not available in v1.2.2 of the oc command.  You will need to use a newer version.  I would suggest downloading the newest release of the oc command (v1.3.1) here https://github.com/openshift/origin/releases/tag/v1.3.1

How did you install the v1.2.2?  Did you use apt or did you download it from the releases?

**Comment by mkjsix** [comment]
Hi @coreydaley 
I was just following the [documentation](https://github.com/openshift/origin/blob/master/docs/cluster_up_down.md#linux) line by line and use the releases:

> Download the Linux oc binary from [openshift-origin-client-tools-VERSION-linux-64bit.tar.gz](https://github.com/openshift/origin/releases/tag/v1.2.2) and place it in your path.

I guess the documentation should link to the 1.3.1 tag instead of 1.2.2

**Comment by coreydaley** [comment]
@mkjsix Ah, i can see where that would be confusing.  We are linking to https://github.com/openshift/origin/releases/latest which goes to the newest post there, instead of the actual newest binaries.  99% of the time that link would be correct, except that a new version of 1.2 was released to fix issues.  We will look into a way to more accurately depict what is the "newest" version, and what is just the "most recently posted" version.

@smarterclayton Maybe there is some extra verbiage that we could add to these posts (https://github.com/openshift/origin/releases) detailing what is the latest stable release, beta release, etc?  I'm not 100% sure what the right approach is here.

**Comment by smarterclayton** [comment]
Ha.  I just need to update the release, then it puts it in the right order.

**Comment by smarterclayton** [comment]
Spoke to soon.  It doesn't.  Hrm.

**Comment by mkjsix** [comment]
On my side, after downloading the oc command v 1.3.1 things seem to work.

**Comment by coreydaley** [comment]
Great, glad that worked for you.  We will continue to look for a way to make the newer versions stand out.  Feel free to open a new issue if you encounter other problems.

**Comment by benyaminl** [comment]
@coreydaley Is it deprecated to v4.10? Thanks

**Comment by coreydaley** [comment]
@benyaminl This issue has been closed for 5 years, please start a new one if you have a question or refer to https://docs.openshift.org.
