### ISSUE TITLE
du: cannot access ‘/tmp/openshift/test-extended/core/logs/openshift.log’: No such file or directory

### ISSUE THREAD

**Issue by coreydaley** [openshift/origin#11527]
https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_conformance/7718/console

```
[INFO] Tearing down test
[INFO] Stopping k8s docker containers
[INFO] Removing k8s docker containers
[INFO] Pruning etcd data directory...
du: cannot access ‘/tmp/openshift/test-extended/core/logs/openshift.log’: No such file or directory
[INFO] Cleanup complete
[INFO] Exiting
[ERROR] PID 5865: test/extended/conformance.sh:53: `return $out` exited with status 1.
[INFO] 		Stack Trace: 
[INFO] 		  1: test/extended/conformance.sh:53: `return $out`
[INFO]   Exiting with code 1.
```

**Comment by stevekuznetsov** [comment]
@smarterclayton your commit https://github.com/openshift/origin/commit/72d80847a5e448d696b3557d50780e1271d88952 introduced the `du` call. Did we want `mv` instead of `cp` for space reasons on the remote host running this step?

@coreydaley error handling is off during this routine, so this did not cause your failure. Please investigate further.

**Comment by smarterclayton** [comment]
Either way.  I just want to know how much was lost because that helps me
debug further.
