### ISSUE TITLE
[registry] without dns, the atomic-registry-console cannot resolve hostname during login

### ISSUE THREAD

**Issue by thomasmckay** [openshift/origin#11542]
When logging into registry through cockpit, the console cannot resolve the hostname specified in /etc/sysconfig/atomic-registry-console variable KUBERNETES_SERVICE_HOST. It attempts to use dns to resolve host name but if dns is not in use login will fail.

One solution would be to provide a second variable, KUBERNETS_SERVICE_HOST_IP, to allow bypassing this situation.

https://github.com/openshift/origin/blob/master/examples/atomic-registry/systemd/install.sh#L86

**Comment by aweiteka** [comment]
@mythocelt I think this is the issue you were seeing, reported in IRC #atomic. Proposed workaround:

1. edit **/etc/systemd/system/atomic-registry-console.service**, add `--net=host` to docker run line
1. `systemctl daemon-reload`
1. `systemctl restart atomic-registry-console`

Root cause:
The browser redirect for auth works, but the console container can’t reach the atomic-registry-master container. This occurs when using a hostname that is not propigated inside the container. net=host ensures the container resolves just like the host.

**Comment by aweiteka** [comment]
Atomic registry deployment is being deprecated in favor of better tested and maintained installation methods.

- [oc cluster up](https://github.com/openshift/origin/blob/master/docs/cluster_up_down.md) for non-production "try it out" or test deployments
- [openshift-ansible](http://www.projectatomic.io/blog/2017/05/oo-standalone-registry/) for more production use cases.

This reported issue will not be addressed.
