### ISSUE TITLE
etcd clients and wrapping 

### ISSUE THREAD

**Issue by timothysc** [openshift/origin#11573]
We're using 3 different clients, some are reaching through directly vs. using wrapped storage layer. 

Clients include:  
etcd3-v2-client 
etcd3-v3-client 
go-etcd (old) client 
##### Version

latest master

Upstream we've wrapped all invocations through a factory in the storage layer, we should push all these instances through a similar mechanism or wrap appropriately to allow for switch, as etcd3 does not support a mixed-mode data.  e.g. - registry using v3mode, locking + other stuff using v2mode 

/cc @brenton @smarterclayton @mffiedler

**Comment by smarterclayton** [comment]
etcd3 does not support old and new keys at the same time?

**Comment by timothysc** [comment]
So word is the etcd folks are trying to create a v2 proxy that supports v2 API on top of 3, but mixed mode is not supported, as mixed mode snapshotting + backup and recovery wouldn't make any sense b/c the data formats and incompatible.

**Comment by smarterclayton** [comment]
We don't need backup for the election service though.  It's not a huge deal
to change though

On Oct 25, 2016, at 9:45 PM, Timothy St. Clair <notifications@github.com>
wrote:

So word is the etcd folks are trying to create a v2 proxy that supports v2
API on top of 3, but mixed mode is not supported, as mixed mode
snapshotting + backup and recovery wouldn't make any sense b/c the data
formats and incompatible.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/origin/issues/11573#issuecomment-256227503>,
or mute the thread

**Comment by smarterclayton** [comment]
I don't think we should be using go-etcd anywhere anymore.  Just haven't
removed the helper method that is unused.

I was completely unaware side by side v2/v3 mode was unsupported in the v3
client library.

On Tue, Oct 25, 2016 at 5:58 PM, Timothy St. Clair <notifications@github.com

**Comment by danmcp** [comment]
Tim is concerned about releasing the code as is.  Need to get that resolved.

**Comment by mfojtik** [comment]
@smarterclayton we still use `go-etcd` in `pkg/cmd/server/etcd/etcd.go` but I guess we can replace it with the helper.

**Comment by mfojtik** [comment]
@smarterclayton when talking about backup for leader election, you mean `newControllerPlug` in master_config.go? what you mean we don't need a backup and how you would like to change it? (I tried to remove the helper above and I think master_config is the only user of that helper atm.

**Comment by smarterclayton** [comment]
We have it in the helper, but we don't use it.

**Comment by smarterclayton** [comment]
What is the question?  Our configuration is etcd2 for v1.4 sounds like the
only plan we have at this point.
