### ISSUE TITLE
Random integration test failures

### ISSUE THREAD

**Issue by mfojtik** [openshift/origin#1158]
Today I noticed this again:

```
--- FAIL: TestSimpleImageChangeBuildTrigger (0.20 seconds)
	deploy_trigger_test.go:317: Starting test openshift
	imagechange_buildtrigger_test.go:69: Expected build with base image registry:8080/openshift/test-image:ref-2, got registry:8080/openshift/test-image:ref-1
```
(full log: https://ci.openshift.redhat.com/jenkins/job/merge_pull_requests_openshift3/1040/console)

This issue appears to be random, if I change something in my PR and push again, the Jenkins will merge without problems. Since this happened pretty often I think someone should take a look and investigate...

@bparees @smarterclayton @soltysh FYI

**Comment by soltysh** [comment]
My fears were around the same image being used in two separate test files ([comment](https://github.com/openshift/origin/pull/1138#issuecomment-75971828), although each test is run in separate process and tests are run sequentially ([comment](https://github.com/openshift/origin/pull/1138#issuecomment-76117775)) we are using under the cover only one etcd deamon. In that case using exactly the same image name in the same namespace results in unexpected behavior. Apparently @mfojtik was lucky enough to hit a situation when those two tests were modifying that image so that tests were failing. I'm hoping the referenced PR will fix this.

**Comment by smarterclayton** [comment]
We should be deleting everything in etcd before each test.  If not, that's something to be fixed in the test case

**Comment by soltysh** [comment]
Just double checked, we are calling `deleteAllEtcdKeys` in all the tests wherever we require etcd, especially the ones mentioned in this issue. I guess we'll wait for the other occurrence of the problem.

**Comment by soltysh** [comment]
Still applicable, see https://ci.openshift.redhat.com/jenkins/job/merge_pull_requests_openshift3/1081/

**Comment by bparees** [comment]
I have a theory on what is happening here...  @ironcladlou you're most familiar w/ the watch logic so maybe you can confirm.

1) we create the image repo with the "ref-1" tag
2) we create the buildconfig w/ the imagechangetrigger
3) the image change controller gets the event for the imagerepo creation *after* the buildconfig was created
4) the image change controller triggers a build using the "ref-1" tag from the imagerepo event it got.
5) the test fails
6) (unseen by the test): we update the imagerepo with the ref-2 tag
7) another build is run using the ref-2 tag.

to fix this we need to ensure the buildconfig doesn't get created until after the imagerepo event is delivered, or we need to ensure the buildconfig is created *first* and ignore the first build event.

either way if i'm right, it's a test case problem and not a product problem, so that's good.
