### ISSUE TITLE
hack/extract-release.sh won't work on MacOS

### ISSUE THREAD

**Issue by csrwng** [openshift/origin#11599]
`make release` fails when run on a Mac because the `hack/extract-release.sh` script fails. The script tries to find tars using $(os::build::host_platform). However, the release tars that were created are only linux.

**Comment by stevekuznetsov** [comment]
@smarterclayton do we want to support the release steps on non-Linux machines?

**Comment by smarterclayton** [comment]
Extract release is somewhat questionable right now but I don't see a reason
not to enable it.

On Oct 26, 2016, at 4:44 PM, Steve Kuznetsov <notifications@github.com>
wrote:

@smarterclayton <https://github.com/smarterclayton> do we want to support
the release steps on non-Linux machines?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/origin/issues/11599#issuecomment-256469489>,
or mute the thread

**Comment by csrwng** [comment]
Or maybe we shouldn't try to extract the release on a Mac because the release is linux only? We shouldn't fail 'make release' because of it though.

**Comment by smarterclayton** [comment]
Client binaries are valid release targets.

**Comment by stevekuznetsov** [comment]
superseded by https://github.com/openshift/origin/issues/13464
