### ISSUE TITLE
General Question : Running Origin on Google Cloud Compute Instance via Docker method.

### ISSUE THREAD

**Issue by rwatts3** [openshift/origin#11936]
Greetings, 

I am not sure if it is a misunderstanding of the docs or if I am missing a step.
I sshed into my Google Cloud Compute instance and installed Docker. Upon installing Docker I followed the docker run command provided in the docs to get origin running on my server.
For some reason when I navigate to the ip address of my cloud compute instance and go to :8443/console, I am not able to access origin. 

Is origin only meant to run on the local machine or is this the proper way to install via the docker method.

**Comment by detiber** [comment]
@pweil, this is referencing the docker install from the origin docs, not something that I am familiar with.

**Comment by detiber** [comment]
@smarterclayton can you recommend a better assignee for this issue?

**Comment by smarterclayton** [comment]
Not sure

**Comment by pweil-** [comment]
@rwatts3 can you confirm that you can curl the the console url from the compute instance and that OpenShift is running?  

```
curl -L -k https://<your ip>:8443/console
```

you should see a message that JavaScript is required.

Also, just for completeness are you using https://docs.openshift.org/latest/getting_started/administrators.html#running-in-a-docker-container or another set of directions?

Running the container with that command will use host networking (`--net=host`) so it will bind to the host's ports and should be accessible from the host's IP address.

**Comment by vishal-biyani** [comment]
@pweil- Even after using host for networking the OpenShift console says "loading" and after a few minutes redirects to private IP which can not be resolved from outside. The final URL in browser looks like: ```https://10.128.0.2:8443/oauth/authorize?client_id=openshift-web-console&response_type=token&state=eyJ0aGVuIjoiLyIsIm5vbmNlIjoiMTQ4NTY2MjQ1NjQ3Mi0yODkzNzY0Njk1NTM5NzkyMzE5NzA4NTE5MDEwMTQ2OTQ4MjQ4MTQxMDI1NDc0NzAyOTk2NDY2MzE3Mjk3MDkyMTM2NjI1Mjk0MjI3MzcifQ&redirect_uri=https%3A%2F%2F10.128.0.2%3A8443%2Fconsole%2Foauth```

**Comment by smarterclayton** [comment]
That isn't the external address - if your instance did not get one, you'll
need to add an external address and start the container with --master set
to this value and --public-master set to the external address.

On Jan 28, 2017, at 11:04 PM, Vishal <notifications@github.com> wrote:

@pweil- <https://github.com/pweil-> Even after using host for networking
the OpenShift console says "loading" and after a few minutes redirects to
private IP which can not be resolved from outside. The final URL in browser
looks like:
https://10.128.0.2:8443/oauth/authorize?client_id=openshift-web-console&response_type=token&state=eyJ0aGVuIjoiLyIsIm5vbmNlIjoiMTQ4NTY2MjQ1NjQ3Mi0yODkzNzY0Njk1NTM5NzkyMzE5NzA4NTE5MDEwMTQ2OTQ4MjQ4MTQxMDI1NDc0NzAyOTk2NDY2MzE3Mjk3MDkyMTM2NjI1Mjk0MjI3MzcifQ&redirect_uri=https%3A%2F%2F10.128.0.2%3A8443%2Fconsole%2Foauth

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/origin/issues/11936#issuecomment-275892516>,
or mute the thread

**Comment by vishal-biyani** [comment]
Thanks for pointer @smarterclayton and another thread also was helpful (https://github.com/openshift/origin/issues/2848)

So finally syntax looks something like: 

```sudo docker run -d --name "origin" --privileged --pid=host --net=host -v /:/rootfs:ro -v /var/run:/var/run:rw -v /sys:/sys -v /var/lib/docker:/var/lib/docker:rw -v /var/lib/origin/openshift.local.volumes:/var/lib/origin/openshift.local.volumes:rslave openshift/origin start --public-master=xxx.xx.xx.xxx --master=xxx.xx.xx.xxx```
Where the public-master is the public IP address & master is the internal address. Things to keep in mind:

- You need both - the public and private IP address
- Put only the IP address, not the protocol or ports or anything else.

**Comment by pweil-** [comment]
It looks like this is resolved.  Feel free to reopen if not.

**Comment by lpshikhar** [comment]
What if we are trying to do "oc cluster up" with version 3.4 of openshift? I dont see the option of adding public master and master with OC cli version of bringing up the cluster.

**Comment by vishal-biyani** [comment]
@lpshikhar The ```oc cluster up``` has an option called ```--public-hostname``` but I am not sure how that works.

**Comment by lpshikhar** [comment]
@vishal-biyani I tried the --public-hostname tag and also setting the public master and master as key value pairs as the env variables using **oc cluster up**, but still stuck at the main page where it waits for some authentication and finally lands on to the internal IP.

**Comment by vishal-biyani** [comment]
@lpshikhar Then it is probably best to start with ```openshift start``` command IMHO.

**Comment by lpshikhar** [comment]
@vishal-biyani Thanks for your help, the documentation from RH is pretty bad in explaining the port mapping and all other things specific to GCP.
