### ISSUE TITLE
hot deploy for openshift python image test failure

### ISSUE THREAD

**Issue by bparees** [openshift/origin#12043]
The hot deploy test for python/django is failing as seen here:
https://ci.openshift.redhat.com/jenkins/job/origin_extended_image_tests/769/consoleFull#-169259343956c60d7be4b02b88ae8c268b

it looks like the change to "count: 1337" is being picked up immediately, even when APP_CONFIG=conf/reload.py is not set.

**Comment by bparees** [comment]
(test is test/extended/image_ecosystem/s2i_python.go)

**Comment by coreydaley** [comment]
@bparees 
Looks like this commit (https://github.com/sclorg/s2i-python-container/commit/4dec209e300d45110351bd9ce7bff89259e6510a) to the s2i-python-container repo is what broke the tests.  Not sure why they changed the maxdepth to 1.   Basically it's not finding the wsgi.py file in the project directory anymore so it's starting the django server instead of the gunicorn server, and by default if you are using the django server, hot deploy is enabled.  

Would you rather we modify the django-ex repo or return the s2i-python-container to it's former glory?

**Comment by bparees** [comment]
@coreydaley i'd rather modify the django-ex repo, at least depending on the nature of the modifications.

**Comment by coreydaley** [comment]
fixed by pr https://github.com/openshift/django-ex/pull/68

**Comment by bparees** [comment]
we shall see: https://ci.openshift.redhat.com/jenkins/view/Origin%20Test%20Jobs/job/origin_extended_image_tests/774/
