### ISSUE TITLE
Extended.[k8s.io] Probing container should *not* be restarted with a /healthz http liveness probe [Conformance]

### ISSUE THREAD

**Issue by bparees** [openshift/origin#12072]
```
• Failure [138.845 seconds]
[k8s.io] Probing container
/data/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/test/e2e/framework/framework.go:793
  should *not* be restarted with a /healthz http liveness probe [Conformance] [It]
  /data/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/test/e2e/common/container_probe.go:233

  Nov 29 23:16:31.438: pod e2e-tests-container-probe-dk0xc/liveness-http - expected number of restarts: 0, found restarts: 1

  /data/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/test/e2e/common/container_probe.go:373
```

https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_conformance/8991/

**Comment by derekwaynecarr** [comment]
Same as https://github.com/kubernetes/kubernetes/issues/28084

**Comment by smarterclayton** [comment]
I disabled this on origin_gce to due to flaking

**Comment by kargakis** [comment]
https://ci.openshift.redhat.com/jenkins/job/merge_pull_request_origin/211/consoleFull#-169259343956c60d7be4b02b88ae8c268b

**Comment by gabemontero** [comment]
It got noted again in upstream via https://github.com/kubernetes/kubernetes/issues/30714

Saw it on our end again in https://github.com/openshift/origin/pull/13577

**Comment by bparees** [comment]
https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin/3104/

**Comment by bparees** [comment]
the upstream issue referenced has been closed since march, but there was no resolution other than "we haven't seen it in a while"

**Comment by kargakis** [comment]
Still an issue

https://ci.openshift.redhat.com/jenkins/view/All/job/merge_pull_request_origin/1319/

**Comment by bparees** [comment]
https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin_extended_conformance_install_update/5216/

**Comment by bparees** [comment]
referenced issue above has been closed so i am raising the priority of this issue.

**Comment by bparees** [comment]
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/16758/test_pull_request_origin_extended_conformance_install_update/7582/

**Comment by smarterclayton** [comment]
This test sucks, I think there may be a serious problem here.  Has flaked
for last two years.

On Oct 9, 2017, at 6:54 PM, Ben Parees <notifications@github.com> wrote:

https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/16758/test_pull_request_origin_extended_conformance_install_update/7582/

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/origin/issues/12072#issuecomment-335311564>,
or mute the thread

**Comment by sjenning** [comment]
@ravisantoshgudimetla PTAL

**Comment by ravisantoshgudimetla** [comment]
I have been trying to reproduce this locally but without luck. The main idea of this test is to check that a good container won't restart. Looking at the code and the history of this issue, following are my observations.

- We are bringing up a nginx container and trying to check if <container_IP:80> is available.
- While this is not a bad idea, there are many things that could go wrong because of which nginx may not come to running. Some of them could be related to underlying infrastructure on which we have no control over, some could be related to network plugin being used etc. Some were mentioned in https://github.com/kubernetes/kubernetes/issues/30714#issuecomment-243588831 as well.
For example, the latest one failed with dial tcp `10.128.1.69:80: getsockopt: no route to host`. This could be related to network setup as well.
- This makes the test indeterministic and therefore flaky.

Since the goal this test is to check that a good container won't restart based on liveness probe, would it make sense to add a liveness command that checks for the existence of a particular directory or something else instead of a HTTP GET.

**Comment by stevekuznetsov** [comment]
@ravisantoshgudimetla do you feel like you can deliver the change to the liveness probe to move away from HTTP?

**Comment by ravisantoshgudimetla** [comment]
https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin_extended_conformance_gce/15413/console
