### ISSUE TITLE
Route deletion does not guarantee that a route will no longer be exposed

### ISSUE THREAD

**Issue by marun** [openshift/origin#12280]
If a route is deleted and a router that was exposing the route misses the deletion event (e.g. due to a loss of connectivity with the master), the route will remain exposed until the router pod is stopped or restarted.  The period full sync can only deliver events for existing routes, not for deleted routes.

**Comment by ramr** [comment]
@knobunc  as discussed on the call this am - this one is a potentially invasive change to do this late in the release + rarely (if not never) seen in the "field", so could we please move this to the next release. 

The changes (am thinking off) that would required here are adding a new `reconciler` controller similar to the host admitter/unique host/status controller (in the chain, chain, chain, chain of ... ). 
Since we automatically [re]sync the cache every `resync-interval` and redo the add/modifies to the routes, this new reconciler controller would be also invoked in the chain. 

The main reconciler logic would be a background goroutine and some HandleRoute logic that would save the last time we processed any `route` specific add or modify event  - that's done for each route (map of timestamps keyed by `$namespace/$name`). And also more generically the last time the reconciler controller processed any event. 
The latter is useful to figure out if the router is getting events in case the connection to etcd goes down.  If we didn't get anything in the last `n` (say 2) resync intervals or a wee bit fuzz factor to a single/double interval then we keep the status quo and don't do any reconciliation.
Two sounded safer plus in the worst case its about half-hour from the missed delete event.

And the background goroutine would use that check to see if it needed to do the reconciliation. And if so, then just iterate over that map and remove all the routes that weren't touched in the last `n` intervals (and remove the entry from the local map).

This should handle it for both the haproxy and F5 routers. Otherwise we'd have to do this in 2 different plugins.

That sound good? Thx

**Comment by marun** [comment]
@ramr If a route is exposed by the router but doesn't appear in a successful list, would it ever reappear in subsequent lists?  If not, might it be simpler to note which exposed routes are received during a sync event and remove any that were not seen.

**Comment by ramr** [comment]
@marun  it could happen in the middle as well right (past the sync)? 
Thinking on this a wee bit more - an alternative may be to just kill the router and let the system restart a new one. It is an exceptional condition and that's probably the cheapest (code wise) way to get back to a consistent state. Thoughts?

**Comment by marun** [comment]
I think the problem is detecting when corrective action is needed.  How to know when a restart is required?

**Comment by kargakis** [comment]
@openshift/sig-networking
