### ISSUE TITLE
Should router integration tests require the HAProxy container image?

### ISSUE THREAD

**Issue by stevekuznetsov** [openshift/origin#12297]
Today, the router integration tests require the HAProxy router container image to have been built. In the future, I think we had wanted the full integration test suite to be run off of the code artifacts from checkout & merge. I think it makes more sense for tests requiring images to be in their own bucket, so we don't need to wait for image builds to run the entire integration suite.

/cc @smarterclayton @rajatchopra @knobunc @ramr

**Comment by smarterclayton** [comment]
It would be appropriate over time to move the integration test to an
extended test.  There's not much of a reason to mock the server anymore for
tests.

That said, it's not a critical priority.

On Dec 18, 2016, at 12:22 PM, Steve Kuznetsov <notifications@github.com>
wrote:

Today, the router integration tests require the HAProxy router container
image to have been built. In the future, I think we had wanted the full
integration test suite to be run off of the code artifacts from checkout &
merge. I think it makes more sense for tests requiring images to be in
their own bucket, so we don't need to wait for image builds to run the
entire integration suite.

/cc @smarterclayton <https://github.com/smarterclayton> @rajatchopra
<https://github.com/rajatchopra> @knobunc <https://github.com/knobunc> @ramr
<https://github.com/ramr>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/origin/issues/12297>, or mute the thread

**Comment by stevekuznetsov** [comment]
As a stop-gap, we need to identify and silo any tests in `test/integration` that use images, so we can cleanly run the integration suite on top of source artifacts, only.

**Comment by smarterclayton** [comment]
We already have a build tag for that.

On Dec 19, 2016, at 7:33 PM, Steve Kuznetsov <notifications@github.com>
wrote:

As a stop-gap, we need to identify and silo any tests in test/integration
that use images, so we can cleanly run the integration suite on top of
source artifacts, only.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/origin/issues/12297#issuecomment-268119510>,
or mute the thread

**Comment by stevekuznetsov** [comment]
Ah, ok. I'll update the `make test-integration` target and doc the flag. Cool.
