### ISSUE TITLE
RFE: Pass openshift requester to result PV

### ISSUE THREAD

**Issue by andrewklau** [openshift/origin#12293]
Currently it's hard to distinguish who the actual owner of the PV is.

It'd be useful if an annotation could exist to include openshift requester for the PV.
It'd also be useful if we could pass it down to the storage provider (eg. backup/disaster recovery scenarios)

eg. for EBS volumes we get the tags:
kubernetes.io/created-for/pvc/name
kubernetes.io/created-for/pv/name
kubernetes.io/created-for/pvc/namespace

maybe something like
openshift.io/created-for/requester/name ?

**Comment by smarterclayton** [comment]
You're asking for the user name?

**Comment by andrewklau** [comment]
yep

**Comment by smarterclayton** [comment]
Unfortunately I don't think we can do better than the namespace owner consistently (which in practice is also a statement we make for other actions).  For instance, a PetSet can create PVs, in which case the requester would be "system:serviceaccount:openshift-infra:petset-controller" or similar.

I would generally tend to recommend that the namespace "owner" be the responsible party for anything in its namespace.  Can you describe in more detail how you are using "owner" today in the system, so as to help make sure we are moving toward solutions that enable you?

**Comment by andrewklau** [comment]
We're currently using the "owner" for storing the user's usage, when it comes to PV usage we make 2 look ups. One for the PV and then the namespace owner (having the annotation on the PV could mean we only had to make one lookup). This only works because we watch for the events and made the look ups in real time. 

If we want to look back on data like the original issue case scenario, there's a chance the namespace could've been deleted and claimed by another user.

**Comment by smarterclayton** [comment]
For original data, if we also recorded the namespace UID (which we should
be doing in almost all of these cases) would that help?  That would allow
you to properly identify the owning namespace over time from an audit
perspective.

On Dec 29, 2016, at 6:43 PM, Andrew Lau <notifications@github.com> wrote:

We're currently using the "owner" for storing the user's usage, when it
comes to PV usage we make 2 look ups. One for the PV and then the namespace
owner (having the annotation on the PV could mean we only had to make one
lookup). This only works because we watch for the events and made the look
ups in real time.

If we want to look back on data like the original issue case scenario,
there's a chance the namespace could've been deleted and claimed by another
user.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/origin/issues/12293#issuecomment-269711107>,
or mute the thread

**Comment by andrewklau** [comment]
Yeah that would then at least allow us to verify the ownership

happy new year!

**Comment by smarterclayton** [comment]
@childsb we should spawn an issue upstream to record namespace UID in anyplace we record the namespace name (namespace name is not sufficiently unique).

**Comment by liggitt** [comment]
Doesn't the PV claimref include the PVC uid? In the case of a namespace deletion, the PVC would also be deleted, and even if an identically named one was recreated, the uid wouldn't match.
