### ISSUE TITLE
use milliseconds for hack/lib/cmd.sh time accounting 

### ISSUE THREAD

**Issue by jim-minter** [openshift/origin#12422]
`hack/cmd.sh` uses millisecond resolution for messages but second resolution for loops, meaning that when it errors it may print out error messages like the following:

```
FAILURE after 299.666s: test/cmd/newapp.sh:270: executing 'oc get pods' expecting any result and text 'Running'; re-trying every 0.2s until completion or 300.000s: the command timed out
```

The issue here is that 299.666 < 300.000.

Also note: `os::cmd::internal::run_until_text` and `os::cmd::internal::run_until_exit_code` are largely duplicated code - it would be nice to see this refactored.

**Comment by stevekuznetsov** [comment]
The [logic](https://github.com/openshift/origin/blob/master/hack/lib/cmd.sh#L578) is the [same](https://github.com/openshift/origin/blob/master/hack/lib/cmd.sh#L201) as what is used in the non-loop tests, it's just that there is a quantization of timing due to the re-try logic, I believe. We can try to improve the logic to make sure we are a little more (or less) conservative but as of yet we have not seen any use-cases.

Regarding the refactor, there is work [here](https://github.com/stevekuznetsov/exec-assert) for a Golang based back-end for `os::cmd`... any refactors should first and foremost take us away from Bash, then we can try to factor things more cleanly using a more useable language.

**Comment by jim-minter** [comment]
An example of the issue that's causing the tests to return early is as follows:

say duration = 1 second, interval = 0.2 second
00:00:00.900 test loop begins (start_time recorded as 00:00:00.900, deadline (wrongly) recorded as 00:00:00 + 1 = 00:00:01)
(test takes 20ms to fail, say)
sleep $interval
00:00:01.120 test loop exits (end_time recorded as 00:00:01.120)

So in this (contrived) example no retries are done and the test loop lasts 220ms when four retries are expected, taking >1s.

**Comment by stevekuznetsov** [comment]
I understand the issue, but what is the use-case for making this more exact? The closer a test is to hitting it's timeout, the more susceptible it is to timing flakes, bad IO latency, etc, basically we never want a successful test to be consistently succeeding close to it's timeout limit. It's definitely a bug and isn't implemented in the most clean manner but the bar for adding to this Bash codebase is unfortunately pretty high.

**Comment by jim-minter** [comment]
None - just pointing out the design issue and recording it for future improvement. Low priority.

**Comment by stevekuznetsov** [comment]
Understood, thanks for the input!

**Comment by stevekuznetsov** [comment]
Unless we feel strongly, not worth tracking this tech debt.

/close
