### ISSUE TITLE
"openshift ex login" fails with "unknown flag: --certificate-authority"

### ISSUE THREAD

**Issue by brenton** [openshift/origin#1249]
We need this for beta2 and @sdodson noticed it's failing.  I just built the lasted origin and I see the same problem.

~~~
# openshift ex login --certificate-authority=/var/lib/openshift/openshift.local.certificates/ca/root.crt --server=https://localhost:8443 --namespace=demo --name=demo
unknown flag: --certificate-authority
~~~

**Comment by deads2k** [comment]
It's a bizarre and misleading error message that I'll look into, but for now eliminating the `name` flag.  `name` doesn't exist and it's causing instigating the failure resulting in the bad message.

**Comment by brenton** [comment]
QE found this too so I'm going to assign it to you: https://bugzilla.redhat.com/show_bug.cgi?id=1199954

**Comment by brenton** [comment]
Sorry, didn't mean to hit "close". :)

**Comment by deads2k** [comment]
It's caused because of this `if` block:  https://github.com/openshift/origin/blob/master/Godeps/_workspace/src/github.com/spf13/cobra/command.go#L462

@fabianofranz You've spent some time in cobra, any idea why this is special cased?  It seems like it would be covered in one of the two cases directly above.  Upon exiting here: https://github.com/openshift/origin/blob/master/Godeps/_workspace/src/github.com/spf13/cobra/command.go#L458, `err` has the expected value.  Instead of printing that error, cobra is re-parsing the args using the root command and printing the root command's message.  It seems really strange.

**Comment by thoraxe** [comment]
Should we close this since "osc login" is now a "real" command? @brenton
