### ISSUE TITLE
1.4 release tgz has different directory name than tgz filename

### ISSUE THREAD

**Issue by cameronbraid** [openshift/origin#12576]
https://github.com/openshift/origin/releases/download/v1.4.0/openshift-origin-client-tools-v1.4.0-208f053-linux-64bit.tar.gz

extracts to folder :

openshift-origin-client-tools-v1.4.0+208f053-linux-64bit

filename uses a - after 1.4.0 
folder uses a + after 1.4.0 

other versions have a - in both

**Comment by smarterclayton** [comment]
This is because github recently changed their accepted characters lists and we just renamed the binaries.  Will be a 1.5 fix.

**Comment by hferentschik** [comment]
> This is because github recently changed their accepted characters lists 

So '-' is not allowed anymore? There are plenty of other '-' in the name. I am trying to understand what you mean. Or do you mean this is an unintended side effect of whatever changed w/i GitHub

>  Will be a 1.5 fix.

What will be the fix. Will in 1.5 the archive file name again align with the content directory name within? Also, this actually is just the case for Linux. The OS X and Windows zip files are still consistent.


and we just renamed the binaries. Will be a 1.5 fix.

**Comment by smarterclayton** [comment]
Fixed in https://github.com/openshift/origin/pull/12636

**Comment by gbraad** [comment]
@smarterclayton haven't tested this, but does this also fix the issue with the server package, as it also suffered from the same problem.

**Comment by smarterclayton** [comment]
Check 1.5.0-alpha.2 tar to see if that looks right to you

On Jan 26, 2017, at 1:58 AM, Gerard Braad <notifications@github.com> wrote:

@smarterclayton <https://github.com/smarterclayton> haven't tested this,
but does this also fix the issue with the server package, as it also
suffered from the same problem.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/origin/issues/12576#issuecomment-275320221>,
or mute the thread
