### ISSUE TITLE
oc cluster up should wipe out config dir on start

### ISSUE THREAD

**Issue by bparees** [openshift/origin#12619]
/var/lib/origin contains content that results in broken certs when it is reused after the host machine's ip changes.

oc cluster up should always wipe that content out and start fresh unless reuse existing configuration was explicitly requested.

**Comment by jorgemoralespou** [comment]
The problem I don't think is in the existence of those files, but rather in the information existing in the .kubeconfig file.
We've been bitten by this as we reuse many clusters (same IPs, name, etc,... but different clusters) and we've ended up fixing it in the .kubeconfig by setting context and clusters names, as you know already (@csrwng) https://github.com/openshift-evangelists/oc-cluster-wrapper/blob/master/oc-cluster#L259-L264

**Comment by csrwng** [comment]
@jorgemoralespou that's a different issue, I think. This is the case when your ip changes are your server-generated certs are no longer valid because now you have a different ip.

**Comment by jorgemoralespou** [comment]
@csrwng I trust your judgement. Just wanted to highlight that where I've found most issues when roaming ips with an existing configuration was with the certificate saved on .kubeconfig, and more since there's not a login (user creation) once you start up a cluster for the second time. Previously, the cluster and user in .kubeconfig got recreated on every start. Now it doesn't.
Just pay attention to this when you look into it ;-)

**Comment by bparees** [comment]
yeah in my case it was server config (wiping out /var/lib/origin resolved it for me).

**Comment by bparees** [comment]
@csrwng i haven't seen this issue lately, did you implement this, or implement something else that fixed the cert issue? (or have i just not changed my ip lately?)

**Comment by csrwng** [comment]
What has changed is that the change in IP should no longer be an issue. However we don't wipe out the config directory, and I don't think we should. There's really no need to re-generate certs every time.
