### ISSUE TITLE
How to run restart OpenShift without losing projects/namespaces?

### ISSUE THREAD

**Issue by magick93** [openshift/origin#12639]
Related to the documents on https://github.com/openshift/origin/blob/master/docs/cluster_up_down.md#linux

I followed this to install OpenShift Origin.

Everything seemed fine. Until I needed to restart docker.

I then reran 'oc cluster up' expected that it will bring up OpenShift with all previously created namespaces/projects. This was not the case. It created a new installation. All previously created projects/namespaces were lost.

How can I run OpenShift in such away that projects/namespaces are not lost on a restart?

May I suggest that you inform users of the possible lose of work in your docs.

Thanks

**Comment by GrahamDumpleton** [comment]
See sections:

  * https://github.com/openshift/origin/blob/master/docs/cluster_up_down.md#configuration
  * https://github.com/openshift/origin/blob/master/docs/cluster_up_down.md#etcd-data

Could well be useful to have ``oc cluster up`` output a warning on startup indicating when not running in persistent mode and so that any work will be lost on restart. A warning at the start of that document about persistence pointing to later sections might also be useful.

**Comment by magick93** [comment]
Thanks Graham, I overlooked this.

And agree, a warning message would be helpful.
