### ISSUE TITLE
`HostSubnet` and `NetNamespace` stored in wrong place in etcd

### ISSUE THREAD

**Issue by enj** [openshift/origin#12697]
`HostSubnet` created in #2150 are stored at `openshift.io/registry/sdnsubnets/$host` instead of `openshift.io/registry/sdnsubnets/$name` due to [this incorrect line](https://github.com/rajatchopra/origin/blob/b7d2fe8a360c0730c49f48de467180a78318bdad/pkg/sdn/registry/hostsubnet/etcd/etcd.go#L35).  This breaks `oc` (note the incorrect name completion and `selfLink`):

```
$ oc get hostsubnet -o yaml
apiVersion: v1
items:
- apiVersion: v1
  host: hostname
  hostIP: 192.168.1.1
  kind: HostSubnet
  metadata:
    creationTimestamp: 2017-01-27T18:43:27Z
    name: hs1
    namespace: ""
    resourceVersion: "965"
    selfLink: /oapi/v1/hostsubnetshs1
    uid: 7d653001-e4c0-11e6-91d5-507b9dac97ff
  subnet: 192.168.1.1/24
kind: List
metadata: {}
resourceVersion: ""
selfLink: ""
```
```
$ oc get hostsubnet hs1 # auto completed
Error from server (NotFound): hostsubnets "hs1" not found
```
```
$ oc get hostsubnet hostname
NAME      HOST       HOST IP       SUBNET
hs1       hostname   192.168.1.1   192.168.1.1/24
```
As long as `Host` is unique this should continue to work.  I do not see any easy way to fix the incorrect line without breaking old clusters.

cc @openshift/api-review

**Comment by smarterclayton** [comment]
We'll probably need to do something to fix this.  Networking team needs to
triage impact, and if this was a type we were moving somewhere else we
should consider doing that soon.

We can potentially tighten validation but I'm concerned that could break
old clusters.  We need a transition story for sure

On Jan 27, 2017, at 1:59 PM, Mo Khan <notifications@github.com> wrote:

HostSubnet created in #2150 <https://github.com/openshift/origin/pull/2150>
are stored at openshift.io/registry/sdnsubnets/$host instead of
openshift.io/registry/sdnsubnets/$name due to this incorrect line
<https://github.com/rajatchopra/origin/blob/b7d2fe8a360c0730c49f48de467180a78318bdad/pkg/sdn/registry/hostsubnet/etcd/etcd.go#L35>.
This breaks oc (note the incorrect name completion and selfLink):

$ oc get hostsubnet -o yaml
apiVersion: v1
items:
- apiVersion: v1
  host: hostname
  hostIP: 192.168.1.1
  kind: HostSubnet
  metadata:
    creationTimestamp: 2017-01-27T18:43:27Z
    name: hs1
    namespace: ""
    resourceVersion: "965"
    selfLink: /oapi/v1/hostsubnetshs1
    uid: 7d653001-e4c0-11e6-91d5-507b9dac97ff
  subnet: 192.168.1.1/24
kind: List
metadata: {}
resourceVersion: ""
selfLink: ""

$ oc get hostsubnet hs1 # auto completed
Error from server (NotFound): hostsubnets "hs1" not found

$ oc get hostsubnet hostname
NAME      HOST       HOST IP       SUBNET
hs1       hostname   192.168.1.1   192.168.1.1/24

As long as Host is unique this should continue to work. I do not see any
easy way to fix the incorrect line without breaking old clusters.

cc @openshift/api-review
<https://github.com/orgs/openshift/teams/api-review>

—
You are receiving this because you are on a team that was mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/origin/issues/12697>, or mute the thread

**Comment by liggitt** [comment]
host is not guaranteed unique, it is not required, and it is not validated to be a valid etcd path.

**Comment by enj** [comment]
[This](https://github.com/openshift/origin/blob/master/pkg/sdn/plugin/subnets.go#L81) looks like the only place where we write `Host` and we make sure that it is equal to `meta.name`.  That of course assumes that no one manually created the object.

cc @derekwaynecarr @rajatchopra

**Comment by smarterclayton** [comment]
I'm not positive but I though this was one of the create only resources (no
updates performed).

On Jan 27, 2017, at 1:59 PM, Mo Khan <notifications@github.com> wrote:

HostSubnet created in #2150 <https://github.com/openshift/origin/pull/2150>
are stored at openshift.io/registry/sdnsubnets/$host instead of
openshift.io/registry/sdnsubnets/$name due to this incorrect line
<https://github.com/rajatchopra/origin/blob/b7d2fe8a360c0730c49f48de467180a78318bdad/pkg/sdn/registry/hostsubnet/etcd/etcd.go#L35>.
This breaks oc (note the incorrect name completion and selfLink):

$ oc get hostsubnet -o yaml
apiVersion: v1
items:
- apiVersion: v1
  host: hostname
  hostIP: 192.168.1.1
  kind: HostSubnet
  metadata:
    creationTimestamp: 2017-01-27T18:43:27Z
    name: hs1
    namespace: ""
    resourceVersion: "965"
    selfLink: /oapi/v1/hostsubnetshs1
    uid: 7d653001-e4c0-11e6-91d5-507b9dac97ff
  subnet: 192.168.1.1/24
kind: List
metadata: {}
resourceVersion: ""
selfLink: ""

$ oc get hostsubnet hs1 # auto completed
Error from server (NotFound): hostsubnets "hs1" not found

$ oc get hostsubnet hostname
NAME      HOST       HOST IP       SUBNET
hs1       hostname   192.168.1.1   192.168.1.1/24

As long as Host is unique this should continue to work. I do not see any
easy way to fix the incorrect line without breaking old clusters.

cc @openshift/api-review
<https://github.com/orgs/openshift/teams/api-review>

—
You are receiving this because you are on a team that was mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/origin/issues/12697>, or mute the thread

**Comment by enj** [comment]
@smarterclayton we [do not allow](https://github.com/openshift/origin/blob/master/pkg/sdn/api/validation/validation.go#L109-L111) the `Subnet` to change.

**Comment by liggitt** [comment]
> I'm not positive but I though this was one of the create only resources (no updates performed).

the storage supports updates, and the Host field isn't validated or prevented from changing

**Comment by rajatchopra** [comment]
We do allow these objects to be manually created as well. For the new F5 integration, its is one of the steps we ask from the admin. No guarantee then that the hostname will match the name.
We should correct the code and be aware of the migration:
 - All such objects that do not have the name == host need to be moved (one way is to delete these objects before upgrade, and the recreate them after upgrade)

**Comment by liggitt** [comment]
attempting to create without a host field returns `{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"Name parameter required.","reason":"BadRequest","code":400}`, so we can assume all existing objects in etcd have the host field set

attempting to edit host on an update leads to: `{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "Operation cannot be fulfilled on hostsubnets \"foobar\": StorageError: invalid object, Code: 4, Key: /openshift.io/registry/sdnsubnets/foobar, ResourceVersion: 0, AdditionalErrorMsg: Precondition failed: UID in precondition: 0xc82e530ab0, UID in object meta: ",
  "reason": "Conflict",
  "details": {
    "name": "foobar",
    "kind": "hostsubnets"
  },
  "code": 409
}`

both metadata.name (via ValidateObjectMeta) and host (via NoNamespaceKeyFunc) are prevented from containing invalid path chars, so I think we can presume the objects are at least located in the right keyspace

it is currently possible to create an object with a mismatching host and metadata.name, which results in `{"kind":"HostSubnet","apiVersion":"v1","metadata":{"name":"foo","selfLink":"/oapi/v1/hostsubnets/foo","uid":"ec60f6f4-e4c5-11e6-8ed7-acbc32c1ca87","resourceVersion":"435","creationTimestamp":"2017-01-27T19:22:20Z"},"host":"bar","hostIP":"10.10.10.10","subnet":"10.10.10.10/12"}`, stored in etcd as if the name was "bar"

I'm not whether we would want to treat that object as if it were named "bar" and fix up the metadata.name in-place in etcd, or treat it as if it were named "foo" and try to move it in etcd and remove the old record

**Comment by enj** [comment]
More good news - `NetNamespace` from #3665 [has the same problem](https://github.com/rajatchopra/origin/blob/39870701172cef7175a15c93194195b2ee84f404/pkg/sdn/registry/netnamespace/etcd/etcd.go#L35).

**Comment by rajatchopra** [comment]
"I'm not whether we would want to treat that object as if it were named "bar" and fix up the metadata.name in-place in etcd, or treat it as if it were named "foo" and try to move it in etcd and remove the old record"
I am in favour of fixing the metadata.name in-place. Pretty sure we will not find many such objects.

**Comment by liggitt** [comment]
> I am in favour of fixing the metadata.name in-place. Pretty sure we will not find many such objects.

I think I agree. We don't have a good mechanism in place for direct-to-etcd fixup. This warrants one.

**Comment by enj** [comment]
@smarterclayton would using `k8s.io/kubernetes/pkg/api/meta` like this hurt performance (would allow us to delete all the `ObjectNameFunc`s that use the standard behavior):
```golang
if store.ObjectNameFunc == nil {
	store.ObjectNameFunc = func(obj runtime.Object) (string, error) {
		return obj.(meta.Object).GetName(), nil
	}
}
```

**Comment by danwinship** [comment]
> I'm not sure whether we would want to treat that object as if it were named "bar" and fix up the metadata.name in-place in etcd, or treat it as if it were named "foo" and try to move it in etcd and remove the old record

The docs in pkg/sdn/plugin/v1/types.go state:

    	// Host is the name of the node. (This is redundant with the object's name, and this
    	// field is not actually used any more.)

So we definitely want to keep "name". (And fix validation? And fix the docs to not only refer to "nodes".)

Likewise with NetNamespace: "`NetName is the name of the network namespace. (This is the same as the object's name, but both fields must be set.)`"

**Comment by mfojtik** [comment]
@knobunc setting this P1 for the initial triage, feel free to bump.

**Comment by smarterclayton** [comment]
Write-repair (update name on save in limited cases) is ok if we know that a) the client has always set name and hostname the same, b) a different name is ignored anyway on the server side.  That would allow `oadm migrate` to fix the value to whatever hostname is (if hostname is truth, then name should match hostname).  After all, you can't delete name != hostname today.

**Comment by enj** [comment]
@rajatchopra How would the SDN stuff react to objects being deleted and recreated?

There are two possible ways that things can be screwed up:

1:
key in `etcd` == `foo`
`meta.name` == `foo`
`hostname` == `bar`

2:
key in `etcd` == `bar`
`meta.name` == `foo`
`hostname` == `bar`

It is not possible to get into situation 3 below where neither `meta.name` nor `hostname` match the key in `etcd`.

3:
key in `etcd` == `not`
`meta.name` == `foo`
`hostname` == `bar`

1 can be fixed via an update, 2 requires delete and recreate because `meta.name` cannot be mutated.

Thus a possible fix would be:

`vOld` = some older OpenShift version
`vNew` = some newer OpenShift version with code that forces the two values to be the same on create / update

1. On `vOld` run a script to list all objects
2. Find all objects where the two fields do not match
3. Use `GET`s to figure out which field is correct
4. Delete the incorrect objects
5. Recreate the objects with corrected fields
6. Upgrade to `vNew`

This assumes you are not incorrectly creating / updating those objects while the fix is happening.

I still need to do further investigation on older versions to make sure that objects directly created by OpenShift never set those fields to different values.

**Comment by enj** [comment]
cc @openshift/networking I need info on ^ so I can determine the best fix.

**Comment by danwinship** [comment]
> How would the SDN stuff react to objects being deleted and recreated?

For HostSubnet, all nodes would delete the route to that host when its HostSubnet was deleted, and then add it back when it was recreated. So a few packets might get dropped during the change, but stuff should recover from that.

For NetNamespace, *in theory* things should be similar. However, there are more ways this could mess up than in the HostSubnet case, and more uncertainty about the correctness of the code since this is something that would never happen during normal operation.

However, we also have no evidence that the problem actually exists in the wild for NetNamespace, since OpenShift itself doesn't create "bad" NetNamespace objects, and there aren't documents encouraging people to create their own bad NetNamespaces. So (pick one) we could just skip fixing them / we could just fix them and not worry about breakage since we don't expect the code actually get run anywhere.

**Comment by mfojtik** [comment]
@rajatchopra / @enj this needs milestone (is this a blocker for 1.5?)

**Comment by eparis** [comment]
@enj are you going to take fixing this?
