### ISSUE TITLE
Unexpected EOF during watch stream event decoding: unexpected EOF

### ISSUE THREAD

**Issue by mignev** [openshift/origin#12833]
This messages appear frequently in logs:

```
origin-node: I0206 19:43:15.055366    2800 streamwatcher.go:103] Unexpected EOF during watch stream event decoding: unexpected EOF
origin-node: I0206 19:43:19.322990    2800 conversion.go:133] failed to handle multiple devices for container. Skipping Filesystem stats
```

##### Version

oc v1.4.1
openshift v1.4.1
kubernetes v1.4.0+776c994
etcd 3.1.0-rc.0

##### Steps To Reproduce
```
tail -f /var/log/messages
```

**Comment by sferich888** [comment]
From: https://github.com/openshift/origin/issues/6290#issuecomment-164551384 the:
```
origin-node: I0206 19:43:15.055366    2800 streamwatcher.go:103] Unexpected EOF during watch stream event decoding: unexpected EOF
```
message looks like its just a notice message, and if you look at https://github.com/openshift/origin/commit/e60b9b344f1b3a72d445ab2719240a0025e60a83 and the coresponding PR/convesation arround this (upstream kube), you can see this was moved to be logged at a lower informational level (because its too noisy). 

The other messages might be related to https://github.com/openshift/origin/issues/11548

**Comment by pweil-** [comment]
Duplicate: https://github.com/openshift/origin/issues/11548

**Comment by pweil-** [comment]
Also, both of these messages are information and are not indicative of an issue.
