### ISSUE TITLE
HAProxy - Ability to listen to a specific IP address

### ISSUE THREAD

**Issue by jwendell** [openshift/origin#12848]
Starting origin with the flags --listen and --master is not enough to make haproxy to listen on the specified ip address.

This would be useful in a scenario where one wants to have more than one origin instance running on the same host, having multiple IP addresses.

**Comment by jwendell** [comment]
I'm cooking a PoC patch for this enhancement.

**Comment by pweil-** [comment]
https://github.com/openshift/origin/pull/12175 is relevant to this discussion but hasn't moved in a while.  @knobunc @ramr we may just need to close it out.

**Comment by pweil-** [comment]
@jwendell @knobunc I also want to note that in the past we've recommended to just use a custom template for something like this rather than add to the variables that we already support.  [Using a config map](https://docs.openshift.com/enterprise/3.2/install_config/install/deploy_router.html#using-configmap-replace-template) would mean that you do not need to build a new image in order to consume a custom template.

**Comment by jwendell** [comment]
Here's the work in progress: https://github.com/openshift/origin/compare/master...jwendell:haproxy-bind?expand=1

It's still missing docs, but it's kind of working. Need to investigate a bug though. When I start a second openshift instance, the router on the first one stops working...
