### ISSUE TITLE
'oc process' should be able to ignore invalid parameter names via a flag

### ISSUE THREAD

**Issue by yacekmm** [openshift/origin#12909]
`oc process` in oc version 3.3.1.7 throws error and stops processing template when it encounters param in `-v` that is not defined in template. Why is that? It should be treated as a warning and processing should continue.

In fact the oc version 3.2.0.44 behaved exactly like that - it displayed warning but did not stop processing.

##### Version
3.3.1.7

##### Steps To Reproduce
1. process template file with `oc process -f template.yml -v VAR=value`, whereas `VAR` is not defined in template

##### Current Result
command fails due to unrecognized param with message: `error: unknown parameter name "VAR"`
##### Expected Result
should display warning (like it was in version 3.2.0.44, but should not fail.

**Comment by bparees** [comment]
this was changed here:
https://github.com/openshift/origin/pull/8049

because it was considered a bug for us not to error out when you provide an invalid parameter name.  I don't see a good justification to change the behavior, I think it is better to error out if someone typos the parameter name, otherwise if they are piping the output to oc create, objects are going to be created with incorrect values.

**Comment by yacekmm** [comment]
I don't think anyone would blame the `oc` tool for making a typo in parameter name. There is plenty of other places where typo can be done and you can do nothing with it.

Warning in my opinion is enough to make user aware that something is wrong and it does not block other (valid) usages. Like the one that I use: the same parameters file for different templates. Since `oc` update, my whole OpenShift configuration is locked by this behavior.

So maybe some flag to ignore unknown parameter errors would be a good compromise?

**Comment by bparees** [comment]
re-opening as an enhancement to add a `--ignore-invalid-parameters` flag to `oc process` and `oc new-app` (since new-app has the same behavior).

**Comment by matthyx** [comment]
I am working on this issue here:
https://github.com/matthyx/origin/blob/issue-12909/pkg/cmd/cli/cmd/process.go

However, I do have a question on the relevance of **injectUserVars** in `process` when other commands like `new-app` are using **TransformTemplate** from:
https://github.com/matthyx/origin/blob/issue-12909/pkg/generate/app/cmd/template.go

Should I get rid of **injectUserVars** and use **TransformTemplate** instead ?

**Comment by bparees** [comment]
I think the problem you're going to run into there is oc process has the ability to process a template locally, TransformTemplate assumes remote access.

**Comment by matthyx** [comment]
Makes sense. Alright, I will implement the switch in both locations. Thanks for your quick answer!

**Comment by matthyx** [comment]
I have created a PR for this issue. Where do I update the documentation for the new flag? Also, should I add some tests for this feature?

**Comment by bparees** [comment]
tests would be good, they can be added to https://github.com/openshift/origin/blob/master/test/cmd/templates.sh and https://github.com/openshift/origin/blob/master/test/cmd/newapp.sh

As for doc, the oc process command is documented here: https://github.com/openshift/openshift-docs/blob/master/dev_guide/templates.adoc

but i don't know that this flag rises to the level of needing explicit doc.
