### ISSUE TITLE
oc new-app with multiple parameters regression (again)

### ISSUE THREAD

**Issue by Jiri-Kremser** [openshift/origin#12939]
I can see pretty much the same as in here https://github.com/openshift/origin/issues/8668 with the oc `v1.5.0-alpha.2`

##### Version
oc v1.5.0-alpha.2+e4b43ee
kubernetes v1.5.2+43a9be4
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://10.40.0.250:8443
openshift v1.4.1+3f9807a
kubernetes v1.4.0+776c994

##### Steps To Reproduce
1. oc cluster up --version=v1.4.1
2. oc new-project test
3. oc new-app template-ephemeral.yaml --param=HAWKULAR_SERVICES_IMAGE=jkremser/hawkular-services:0.32.0-with-readiness-script,CASSANDRA_IMAGE=openshift/origin-metrics-cassandra:v1.4.1

(template-ephemeral.yaml ->
https://raw.githubusercontent.com/Jiri-Kremser/hawkular-services/2c857659ac0c8f41720cf517c88baed9c8188972/openshift/template-ephemeral.yaml)

##### Current Result
4. I'd except the app is created from that template where those 2 params were correctly substituted, but this is what I see in the openshift console:

![screenshot from 2017-02-13 17-51-33](https://cloud.githubusercontent.com/assets/535866/22893189/554e6d04-f215-11e6-8b0f-aba8c89f1224.png)

##### Expected Result
4. Both images `jkremser/hawkular-services:0.32.0-with-readiness-script` and `openshift/origin-metrics-cassandra:v1.4.1` would be downloaded correctly.

**Comment by Jiri-Kremser** [comment]
ok, so instead of `oc new-app template.yaml --param=P1=foo,P2=bar` I am now using 

```bash
oc process -f template --param P1=foo --param P2=bar | oc create -f -
```

This works with `v1.5.0-alpha.2`, but fails on `oc v1.3.1`. I was wondering if there is any backward compatible variant...

**Comment by bparees** [comment]
> Perhaps error would be better than warning, because it will probably break something somewhere later.

it can't be an error because that would prevent users from having parameter values that actually contained commas (which was why we changed the behavior in the first place).

> This works with v1.5.0-alpha.2, but fails on oc v1.3.1. I was wondering if there is any backward compatible variant...

unfortunately not, we bit the bullet on breaking compatibility on this one because there was no good way to support both models simultaneously.  The warning to people who appeared to be attempting to use the old syntax was the best we could do.

technically we could introduce a --param-old-format argument or something, but since any scripts that were working until 1.3 would still have to change to use that new flag anyway, it's not that useful.

**Comment by Jiri-Kremser** [comment]
ok, thanks for the info

> any scripts that were working until 1.3 would still have to change to use that new flag anyway

just a comment: the `1.4.1` can't handle the `--param P1=a --param P2=b` syntax so the API breakage is actually happening now with the `1.5.x` version

**Comment by bparees** [comment]
ok, I had thought we introduced it with 1.4 but i guess not.
