### ISSUE TITLE
Tests fail due to `etcdserver: not capable`

### ISSUE THREAD

**Issue by bparees** [openshift/origin#12993]
Swagger spec failed to generated because the clustered failed to come up successfully:

```
12:43:19 Running hack/lib/start.sh:296: executing 'oc get --raw /healthz --config='/openshifttmp/openshift/generate-swagger-spec//openshift.local.config/master/admin.kubeconfig'' expecting any result and text 'ok'; re-trying every 0.25s until completion or 160.000s...
12:43:19 FAILURE after 159.641s: hack/lib/start.sh:296: executing 'oc get --raw /healthz --config='/openshifttmp/openshift/generate-swagger-spec//openshift.local.config/master/admin.kubeconfig'' expecting any result and text 'ok'; re-trying every 0.25s until completion or 160.000s: the command timed out
```

https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_check_future/275/consoleFull#157290065256c015c5e4b05b79524e5a2f

**Comment by stevekuznetsov** [comment]
@smarterclayton looks like etcd comes up in some corrupted state

```
 etcdserver/api/v3rpc: grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp 127.0.0.1:34001: getsockopt: connection refused"; Reconnecting to {127.0.0.1:34001 <nil>}
 etcdserver/api/v3rpc: grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp 127.0.0.1:34001: getsockopt: connection refused"; Reconnecting to {127.0.0.1:34001 <nil>}
 etcdserver: name = openshift.local
 etcdserver: data dir = /openshifttmp/openshift/generate-swagger-spec//etcd
 etcdserver: member dir = /openshifttmp/openshift/generate-swagger-spec/etcd/member
 etcdserver: heartbeat = 100ms
 etcdserver: election = 1000ms
 etcdserver: snapshot count = 10000
 etcdserver: advertise client URLs = https://127.0.0.1:34001
 etcdserver: initial advertise peer URLs = https://127.0.0.1:37001
 etcdserver: initial cluster = openshift.local=https://127.0.0.1:37001
 etcdserver: starting member dfa70e8e25ea6de0 in cluster 3a66c6e8db3c8d30
 raft: dfa70e8e25ea6de0 became follower at term 0
 raft: newRaft dfa70e8e25ea6de0 [peers: [], term: 0, commit: 0, applied: 0, lastindex: 0, lastterm: 0]
 raft: dfa70e8e25ea6de0 became follower at term 1
 etcdserver: starting server... [version: 3.1.0, cluster version: to_be_decided]
 etcdserver/membership: added member dfa70e8e25ea6de0 [https://127.0.0.1:37001] to cluster 3a66c6e8db3c8d30
 raft: dfa70e8e25ea6de0 is starting a new election at term 1
 raft: dfa70e8e25ea6de0 became candidate at term 2
 raft: dfa70e8e25ea6de0 received MsgVoteResp from dfa70e8e25ea6de0 at term 2
 raft: dfa70e8e25ea6de0 became leader at term 2
 raft: raft.node: dfa70e8e25ea6de0 elected leader dfa70e8e25ea6de0 at term 2
 etcdserver: published {Name:openshift.local ClientURLs:[https://127.0.0.1:34001]} to cluster 3a66c6e8db3c8d30
 embed: ready to serve client requests
 run.go:77] Started etcd at 127.0.0.1:34001
 etcdserver: setting up the initial cluster version to 3.1
 embed: serving client requests on 127.0.0.1:34001
 etcdserver/api/v3rpc: Failed to dial 127.0.0.1:34001: connection error: desc = "transport: remote error: tls: bad certificate"; please retry.
 etcdserver/api/v3rpc: Failed to dial 127.0.0.1:34001: connection error: desc = "transport: remote error: tls: bad certificate"; please retry.
 etcdserver/api/v3rpc: Failed to dial 127.0.0.1:34001: connection error: desc = "transport: remote error: tls: bad certificate"; please retry.
 etcdserver/api/v3rpc: Failed to dial 127.0.0.1:34001: connection error: desc = "transport: remote error: tls: bad certificate"; please retry.
 etcdserver/api/v3rpc: Failed to dial 127.0.0.1:34001: connection error: desc = "transport: remote error: tls: bad certificate"; please retry.
 etcdserver/api/v3rpc: Failed to dial 127.0.0.1:34001: connection error: desc = "transport: remote error: tls: bad certificate"; please retry.
 reflector.go:188] github.com/openshift/origin/pkg/project/cache/cache.go:107: Failed to list *api.Namespace: Get https://127.0.0.1:38443/api/v1/namespaces?resourceVersion=0: dial tcp 127.0.0.1:38443: getsockopt: connection refused
 reflector.go:199] github.com/openshift/origin/pkg/controller/shared/shared_informer.go:101: Failed to list *api.ClusterResourceQuota: Get https://127.0.0.1:38443/oapi/v1/clusterresourcequotas?resourceVersion=0: dial tcp 127.0.0.1:38443: getsockopt: connection refused
 auth.go:160] etcdserver: not capable
```

**Comment by smarterclayton** [comment]
Are we sure this wasn't a timeout on start?  Possibly because we aren't
setting /tmp to ramdisk on the new instances, and thus triggering the etcd
fsync thing?

On Feb 16, 2017, at 2:48 PM, Steve Kuznetsov <notifications@github.com>
wrote:

@smarterclayton <https://github.com/smarterclayton> looks like etcd comes
up in some corrupted state

 etcdserver/api/v3rpc: grpc: addrConn.resetTransport failed to create
client transport: connection error: desc = "transport: dial tcp
127.0.0.1:34001: getsockopt: connection refused"; Reconnecting to
{127.0.0.1:34001 <nil>}
 etcdserver/api/v3rpc: grpc: addrConn.resetTransport failed to create
client transport: connection error: desc = "transport: dial tcp
127.0.0.1:34001: getsockopt: connection refused"; Reconnecting to
{127.0.0.1:34001 <nil>}
 etcdserver: name = openshift.local
 etcdserver: data dir = /openshifttmp/openshift/generate-swagger-spec//etcd
 etcdserver: member dir =
/openshifttmp/openshift/generate-swagger-spec/etcd/member
 etcdserver: heartbeat = 100ms
 etcdserver: election = 1000ms
 etcdserver: snapshot count = 10000
 etcdserver: advertise client URLs = https://127.0.0.1:34001
 etcdserver: initial advertise peer URLs = https://127.0.0.1:37001
 etcdserver: initial cluster = openshift.local=https://127.0.0.1:37001
 etcdserver: starting member dfa70e8e25ea6de0 in cluster 3a66c6e8db3c8d30
 raft: dfa70e8e25ea6de0 became follower at term 0
 raft: newRaft dfa70e8e25ea6de0 [peers: [], term: 0, commit: 0,
applied: 0, lastindex: 0, lastterm: 0]
 raft: dfa70e8e25ea6de0 became follower at term 1
 etcdserver: starting server... [version: 3.1.0, cluster version: to_be_decided]
 etcdserver/membership: added member dfa70e8e25ea6de0
[https://127.0.0.1:37001] to cluster 3a66c6e8db3c8d30
 raft: dfa70e8e25ea6de0 is starting a new election at term 1
 raft: dfa70e8e25ea6de0 became candidate at term 2
 raft: dfa70e8e25ea6de0 received MsgVoteResp from dfa70e8e25ea6de0 at term 2
 raft: dfa70e8e25ea6de0 became leader at term 2
 raft: raft.node: dfa70e8e25ea6de0 elected leader dfa70e8e25ea6de0 at term 2
 etcdserver: published {Name:openshift.local
ClientURLs:[https://127.0.0.1:34001]} to cluster 3a66c6e8db3c8d30
 embed: ready to serve client requests
 run.go:77] Started etcd at 127.0.0.1:34001
 etcdserver: setting up the initial cluster version to 3.1
 embed: serving client requests on 127.0.0.1:34001
 etcdserver/api/v3rpc: Failed to dial 127.0.0.1:34001: connection
error: desc = "transport: remote error: tls: bad certificate"; please
retry.
 etcdserver/api/v3rpc: Failed to dial 127.0.0.1:34001: connection
error: desc = "transport: remote error: tls: bad certificate"; please
retry.
 etcdserver/api/v3rpc: Failed to dial 127.0.0.1:34001: connection
error: desc = "transport: remote error: tls: bad certificate"; please
retry.
 etcdserver/api/v3rpc: Failed to dial 127.0.0.1:34001: connection
error: desc = "transport: remote error: tls: bad certificate"; please
retry.
 etcdserver/api/v3rpc: Failed to dial 127.0.0.1:34001: connection
error: desc = "transport: remote error: tls: bad certificate"; please
retry.
 etcdserver/api/v3rpc: Failed to dial 127.0.0.1:34001: connection
error: desc = "transport: remote error: tls: bad certificate"; please
retry.
 reflector.go:188]
github.com/openshift/origin/pkg/project/cache/cache.go:107: Failed to
list *api.Namespace: Get
https://127.0.0.1:38443/api/v1/namespaces?resourceVersion=0: dial tcp
127.0.0.1:38443: getsockopt: connection refused
 reflector.go:199]
github.com/openshift/origin/pkg/controller/shared/shared_informer.go:101:
Failed to list *api.ClusterResourceQuota: Get
https://127.0.0.1:38443/oapi/v1/clusterresourcequotas?resourceVersion=0:
dial tcp 127.0.0.1:38443: getsockopt: connection refused
 auth.go:160] etcdserver: not capable

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/origin/issues/12993#issuecomment-280438443>,
or mute the thread

**Comment by stevekuznetsov** [comment]
All tests enable RAM-disk on `/tmp`

**Comment by smarterclayton** [comment]
Positive?

On Feb 16, 2017, at 3:18 PM, Steve Kuznetsov <notifications@github.com>
wrote:

All tests enable RAM-disk on /tmp

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/origin/issues/12993#issuecomment-280446849>,
or mute the thread

**Comment by stevekuznetsov** [comment]
It's in the job def right now and you can see in `aos-cd-jobs` today there's actually no way to generate a `_future` job without it, so yes.

**Comment by mfojtik** [comment]
@stevekuznetsov seems not a 1.5 blocker, agree?

**Comment by stevekuznetsov** [comment]
Seems like failing to start `etcd` is a pretty bad problem to have, but we've only seen it once so sure.

**Comment by smarterclayton** [comment]
Ah ha!

https://github.com/coreos/etcd/issues/7131

**Comment by stevekuznetsov** [comment]
That's a little crazy ...
