### ISSUE TITLE
Set environment variables in template

### ISSUE THREAD

**Issue by tmds** [openshift/origin#13096]
I am not an experienced OpenShift user, so I don't know how relevant this use-case is.

It would be nice if the UI and oc new-app --template offered the capability to set environment variables.
The template would have to mark where those variables need to be inserted.
For backwards compat, this could be expressed as an environment variable:
```
{
 "name": "$TEMPLATE_ENVIRONMENT",
 "value": ""
}
```

**Comment by pweil-** [comment]
@tmds you can configure environment variables in templates as parameters and then have values filled in via the ui and cli.  https://docs.openshift.org/latest/dev_guide/templates.html#writing-templates has some examples and screenshots.

Please reopen if I'm not understanding the ask.

**Comment by tmds** [comment]
> Please reopen if I'm not understanding the ask.

@pweil- I cannot reopen myself.

When you try to use an application template (nodejs, ruby, python, ...), you want to specify the environment variables.

Let me compare this with a template for a database. Such a template has parameters like "Connection Username", "Connection Database Name", etc. These are the meaningful parameters to configure a database.

For the application templates, the meaningful parameters are those of the application itself (i.e. the application the GIT_URL parameter points to). So it would be nice, if instantiating a template would allow to set those parameters specific to the application.

Without the ability to specify these parameters, the application template use is mostly restricted to running the example app that comes with it.

**Comment by pweil-** [comment]
@tmds not being able to specify those variables seems more of a template authorship issue rather than a generic template issue since the feature to specify parameters exists.  

For example, in our cake php template example you can specify the [git url as a parameter](https://github.com/openshift/origin/blob/master/examples/quickstarts/cakephp-mysql-persistent.json#L488-L492) that feeds the build config and thus the resulting image and pod.  It also defines a default.  

Is that more what you were looking for?

**Comment by tmds** [comment]
Once you pointed the git URL parameter to your repo, the next thing you very often want to do is to set the environment variables specific to that app.

The feature requested here is to be able to provide environment variables when instantiating a template. Those variables would be injected at a placeholder in the template. Typically this would be in the deployment config env.

**Comment by pweil-** [comment]
I think we may be talking past each other on this one.    When instantiating via the console you should see a [parameters section](https://docs.openshift.org/latest/dev_guide/templates.html#creating-from-templates-using-the-web-console).  When instantiating from the cli you [can pass in the parameters as part of the command or as a file](https://docs.openshift.org/latest/dev_guide/application_lifecycle/new_app.html#specifying-a-template).  They will be injected into the template's placeholders.


In the previously mentioned example quite a few things are injected into the [application deployment config as environment variables.](https://github.com/openshift/origin/blob/master/examples/quickstarts/cakephp-mysql-persistent.json#L221-L283)

**Comment by tmds** [comment]
For example:
```
oc new-app --template=nodejs-example -p SOURCE_REPOSITORY_URL=https://github.com/org/somerepo -e ConnectionString="host=mydb"
```

In this example, the `ConnectionString` environment variable is not a parameter of the template. It is an environment variable to be inserted into the DeploymentConfiguration of the nodejs application.

**Comment by pweil-** [comment]
ohhhhh, I'm following you now...injecting arbitrary environment variables that **are not** already part of the template.  Sorry about the confusion. :smile: 

Templates can contain an arbitrary number of objects that may accept environment variables.  In order to do something like this we'd have the template mark where to insert them as you suggested in the description.  Marking where to put the variable(s) is essentially a parameter but without providing the ability to have a rich description, defaults, or generators.

In this case I'd suggest that creating a new template based on the existing one that accepts the value as a parameter.

**Comment by tmds** [comment]
> In this case I'd suggest that creating a new template based on the existing one that accepts the value as a parameter.

I know that is an option. It is not making it easy to do a very common thing: configure your app via environment variables.

Suppose you try out OpenShift for the first time. You click around in the UI and in no time you get the template example app up and running. Wow... this is user-friendly. Then you try to add your own app and this requires you to write a template yourself. Hmm...

**Comment by bparees** [comment]
Templates are not intended to be that generic.  If you have a specific app you want to run, the assumption is you will have a specific template for that app, which allows you to define the parameters you want/need for the app.

If you are going to take one of the existing templates and use it to run a completely different app, you will need to consider forking the template itself as well, if you want to change the parameters/environment values provided to the application.

**Comment by tmds** [comment]
@bparees this pretty much restricts the use of the application example templates to running those examples, right?

**Comment by tmds** [comment]
I mean: trying to use them with another repo won't work.

**Comment by tmds** [comment]
Being able to inject environment variables in templates would greatly increase their usability.
It would cover many cases where users are now required to create an application specific template.

**Comment by bparees** [comment]
It just pushes the problem around. Instead of a template per app, you need
an env var template per app that indicates what env vars need to be
injected and into what part of the template (do you inject the values into
every dc? If not, which DCs? What about RCs? How about defining config maps
or secrets from those values?)

Do all the env vars get exposed as template parameters or are the values
hard-coded into the template? Should any of them have auto-generated
values?

I understand your use case, but I don't think introducing what amounts to
another layer of templating solves it in a useful way.

It also seems unlikely that you're going to have a large number of apps
that only differ in what env vars they consume but not in any other way
that would require more substantial changes to the template.

One last suggestion:  you can use the ${{param}} syntax to inject arbitrary
chunks of json into a template. Combine that with a properly crafted
parameter file and the ability for oc new-app to consume a parameter file
when instantiating a template and I think you can get at least some of what
you're looking for.

Ben Parees | OpenShift

**Comment by tmds** [comment]
> It just pushes the problem around. Instead of a template per app, you need
an env var template per app that indicates what env vars need to be
injected and into what part of the template (do you inject the values into
every dc? If not, which DCs? What about RCs? How about defining config maps
or secrets from those values?)

The use case described here is for templates which have a single BC and DC.

> Do all the env vars get exposed as template parameters or are the values
hard-coded into the template? Should any of them have auto-generated
values?

The template stores a placeholder where it should inject the environment variables.
During instantiation the provided parameters are injected at that placeholder.
The environment variables are meaningful to the application. The template can not auto-generate or provide default values.

On the command line, this would be the values provided as -e arguments when invoking `oc new-app template=`. On the Web Console, this could be an additional section of environment variables that can be specified when instantiating the template.

> I understand your use case, but I don't think introducing what amounts to
another layer of templating solves it in a useful way.

I don't see it as another layer of templating. The template supports the injection of parameter values. In this case, the parameter value is the environment of the application.

> It also seems unlikely that you're going to have a large number of apps
that only differ in what env vars they consume but not in any other way
that would require more substantial changes to the template.

At least, most customer apps will be configurable by environment variables.
If that is enough, I don't know. See below.

> One last suggestion:  you can use the ${{param}} syntax to inject arbitrary
chunks of json into a template. Combine that with a properly crafted
parameter file and the ability for oc new-app to consume a parameter file
when instantiating a template and I think you can get at least some of what
you're looking for.

${{param}} is doing something similar to what I request. The difference is I think it is a common enough for environment variables to do not require a custom template.

The feature request is based on the assumption by providing the ability to inject an environment, we can write templates which are usable for a broad range of application.

I don't know how many users are creating templates just to provide the environment variables to their application. So I can't say how true or false the assumption is.

My personal experience is that a template like postgresql is quite useful to me because I can use that to setup a database service which I can use for my application. An application template (like nodejs-ex) isn't because after I set the git url, I also need to configure my application and the template doesn't support that.

**Comment by bparees** [comment]
The use case of a single DC and BC is extremely limited to the point that this feature would have very minimal value.  And if your app only consists of a single BC and DC, you really don't need a template because creating an app from source (via the web console or new-app) will give you a BC and DC and allow you to specify additional environment variable values during creation.  You can also already specify additional environment variables in your source repo via the s2i environment variable mechanism:
https://docs.openshift.org/latest/dev_guide/builds/build_strategies.html#environment-files so perhaps that will solve your use case instead.

Finally, what you propose is actually quite difficult to do because in order for the system to inject new environment variable parameters into the template, it first has to identify the source repository that's providing the file that contains the items to be injected.  But since the source repository is(or can be) itself a parameter, that means:

1) the system has to identify the parameter that's going to be used as the source repository
2) the system has to clone that repository (which may require additional values such as passwords that are also being supplied as parameters)
3) after collecting *those* parameters from the user so it can perform the clone, only then can it determine if the repository contains a file indicating additional information to be injected/collected from the user
4) it then needs to ask the user for the additional parameter values

Which turns the current flow into a multiple user interaction flow.

**Comment by tmds** [comment]
> The use case of a single DC and BC is extremely limited to the point that this feature would have very minimal value.

I think it would be a common operation to add a new service in a micro-service architecture.

> And if your app only consists of a single BC and DC, you really don't need a template because creating an app from source (via the web console or new-app) will give you a BC and DC and allow you to specify additional environment variable values during creation.

The new-app used with an imagestream is limiting in two ways (compared to the template):
- you cannot provide BC environment variables (e.g. NPM_MIRROR)
- the imagestream does not describe it's environment variables. (The template describes these as parameters.)

> You can also already specify additional environment variables in your source repo via the s2i environment variable mechanism:
https://docs.openshift.org/latest/dev_guide/builds/build_strategies.html#environment-files so perhaps that will solve your use case instead.

This is indeed also an option. It requires the user to leave the OpenShift UI and make modifications to his repository.

> Finally, what you propose is actually quite difficult to do because in order for the system to inject new environment variable parameters into the template, ...

The mechanism should be independent of the source repository. It can work in the same way as the ${{param}} mechanism: it injects the values provided by the user for the environment at a placeholder. It doesn't have to figure out what the environment variables are and whether they are valid.

**Comment by bparees** [comment]
> I think it would be a common operation to add a new service in a micro-service architecture.

such a microservice is likely to also have configmaps and or secrets which contain part of the config, which again makes your injection proposal more complicated.

And if it is indeed a microservice many people are going to deploy, there's not much overhead in creating a template specific to the microservice rather than trying to reuse an common template through some extension mechanism (and risk the microservice deployment getting broken if the template you're expecting people to use is changed because you don't control it).

> you cannot provide BC environment variables (e.g. NPM_MIRROR)

you can, actually, via --build-env.  This was recently added.

> This is indeed also an option. It requires the user to leave the OpenShift UI and make modifications to his repository.

Unless i misunderstand your proposal, it also requires the user to make modifications to the repository.  Where is this additional information about parameters to inject into the template being provided from, if not from the application repository?

> The mechanism should be independent of the source repository. It can work in the same way as the ${{param}} mechanism: it injects the values provided by the user for the environment at a placeholder. It doesn't have to figure out what the environment variables are and whether they are valid.

Then where is the content to be injected coming from?  Are you expecting the user to just know about additional environment variables they want to provide and have them added in and understand where in the template they're going to be injected?  How does a user know this information?

**Comment by tmds** [comment]
> such a microservice is likely to also have configmaps and or secrets which contain part of the config, which again makes your injection proposal more complicated.

I lack experience here, so I trust you are right :)

> How does a user know this information?

Same as for new-app: it's his app, he should know.

> you can, actually, via --build-env. This was recently added.

Super! This is a big match with my use-case!

The only minor thing it misses is the builders are not describing their own environment variables. This can help the user fill out the Build Configuration environment. Now he has to go to the builder github readme to find that out.

@bparees Thanks for discussing with me.
