### ISSUE TITLE
Central logging (logstash for pods)

### ISSUE THREAD

**Issue by Evgeniy-Bondarenko** [openshift/origin#13110]
How to enable forwarding the log of the pods in logstash (ELK)?

##### Version
oc version
oc v1.3.0
kubernetes v1.3.0+52492b4
features: Basic-Auth GSSAPI Kerberos SPNEGO
openshift v1.3.0
kubernetes v1.3.0+52492b4

##### Steps To Reproduce
1.  Go to WebUi Openshift for read and control log from each pods

##### Current Result
It is not productive

##### Expected Result
Centralization of logs in ELK (Elastic Logstash Kibana)

**Comment by lmello** [comment]
https://docs.openshift.com/enterprise/3.1/install_config/aggregate_logging.html

**Comment by jcantrill** [comment]
The OpenShift logging stack relies on the use of Fluentd instead of Logstash to forward logs from the nodes to the Elasticsearch instance.  In order to utilize Logstash, you would need to replace the fluentd instance and configure it to use the same secrets, certs, and keys that is used with Fluend in order to properly communicate with ES.

**Comment by jcantrill** [comment]
Closing under the assumption your question was answered
