### ISSUE TITLE
Properly support git uris of the form user@host:path/to/file.git in build secret injector

### ISSUE THREAD

**Issue by jim-minter** [openshift/origin#13223]
It's confusing that you currently /must/ run `oc annotate secrets/foo 'build.openshift.io/source-secret-match-uri-1=ssh://host/path/to/file.git'` (with `ssh://`, without `user@`) but then may run `oc new-app user@host:path/to/file.git` (without `ssh://`, with `user@`) or `oc new-app ssh://user@host/path/to/file.git` (with `ssh://`, with `user@`).

@mvlach

**Comment by jim-minter** [comment]
(note to self: saw 'Host key verification failed' error at build time after successful secret injection - may or may not have been down to host infrastructure).

**Comment by mvlach** [comment]
I think there is problem with the ssh:// pattern. I created new secret with my private credentials (ssh) and created the new-app. Then manually add secret and everythink build correctly.

when I create a new application like this

oc new-app wildfly~git@host:path/to.git 

then the 

build.openshift.io/source-secret-match-uri-1=ssh://host:path/to.git

doesn't work. The spec.source.sourceSecret.name is not correclty enabled.
It is very confusing. 
************************************

The correct form is:

oc annotate secrets/sshsecret 'build.openshift.io/source-secret-match-uri-1=ssh://host/path/to.git'

and

oc new-app wildfly~ssh://git@host/path/to.git

when you use new-app without ssh:// then the sourceName is not set and if you use : instead of / then the git source cannot be pulled.

**Comment by jim-minter** [comment]
Some improvements in https://github.com/openshift/origin/pull/13282

**Comment by jim-minter** [comment]
Documentation improvements in https://github.com/openshift/openshift-docs/pull/5232
