### ISSUE TITLE
flake: process_linux.go:291: setting cgroup config for ready process caused

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#13241]
https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_networking_future/840/consoleFull#201915086156cbb9a5e4b02b88ae8c2f77

```
18:30:44 Mar  5 18:30:44.675: INFO: At 2017-03-05 18:26:22 -0500 EST - event for weighted-router: {kubelet nettest-node-2} Pulling: pulling image "openshift/origin-haproxy-router"
18:30:44 Mar  5 18:30:44.675: INFO: At 2017-03-05 18:26:22.638375077 -0500 EST - event for execpod: {kubelet nettest-node-1} FailedSync: Error syncing pod, skipping: failed to "StartContainer" for "POD" with RunContainerError: "runContainer: Error response from daemon: {\"message\":\"invalid header field value \\\"oci runtime error: container_linux.go:247: starting container process caused \\\\\\\"process_linux.go:291: setting cgroup config for ready process caused \\\\\\\\\\\\\\\"failed to write a *:* rwm to devices.deny: open /sys/fs/cgroup/devices/system.slice/docker-cca42a09659036290590778ad2440762a9f488265f345d58a56d79cc381ada15.scope/system.slice/docker-cca42a09659036290590778ad2440762a9f488265f345d58a56d79cc381ada15.scope/system.slice/docker-ce71481e3d94f3471a7a48b72a661a4eec507ae799d29f49c2fcda2912fa2224.scope/devices.deny: no such file or directory\\\\\\\\\\\\\\\"\\\\\\\"\\\\n\\\"\"}"
18:30:44 
```

**Comment by smarterclayton** [comment]
@derekwaynecarr @mrunalp @sjenning @openshift/networking 

Have we seen something like that before?  This could just be the network tests and DIND, but would like to know for sure.

**Comment by knobunc** [comment]
@dcbw: Any thoughts?  Thanks.

**Comment by danwinship** [comment]
There's some sort of dind/cgroup problem. These errors often show up with weird nested cgroup paths like `/sys/fs/cgroup/devices/system.slice/docker-871fc6f89264c02a8812d6ebfe72dd6b1215652b59d7f521db3fd01d116e0d7b.scope/system.slice/docker-871fc6f89264c02a8812d6ebfe72dd6b1215652b59d7f521db3fd01d116e0d7b.scope/system.slice/docker-3c93353d77d95c6b6114de44c0ca765d0252df9a56e0321f87c80aa027133d07.scope/devices.deny`.

Almost every time you start a pod under dind you get one or two of these:

    Feb 06 17:35:20 nettest-node-1 openshift[284]: E0206 17:35:20.419986     284 remote_runtime.go:92] RunPodSandbox from runtime service failed: rpc error: code = Unknown desc = failed to start sandbox container for pod "isolation-webserver": Error response from daemon: invalid header field value "oci runtime error: container_linux.go:247: starting container process caused \"process_linux.go:327: setting cgroup config for procHooks process caused \\\"failed to write a *:* rwm to devices.deny: open /sys/fs/cgroup/devices/system.slice/docker-871fc6f89264c02a8812d6ebfe72dd6b1215652b59d7f521db3fd01d116e0d7b.scope/system.slice/docker-871fc6f89264c02a8812d6ebfe72dd6b1215652b59d7f521db3fd01d116e0d7b.scope/system.slice/docker-3c93353d77d95c6b6114de44c0ca765d0252df9a56e0321f87c80aa027133d07.scope/devices.deny: no such file or directory\\\"\"\n"

But usually eventually it succeeds. Sometimes it doesn't. The bug never seems to happen in non-dind clusters.

I'm guessing either
1. the bug only happens when you run kubelet in a non-toplevel cgroup (ie, dind), OR
2. the bug only happens when you specify `--enable-cgroups-per-qos=false` (which we do in dind because otherwise it fails at startup).

I tried to figure out why dind requires `--cgroups-per-qos=false`, but I don't really understand any of the cgroup code.

@marun?

Probably we should just kill off the extended_networking_minimal test, and instead make the conformance_gce test run the (minimal) extended networking tests, since it sets up a multi-node environment running the sdn.

**Comment by smarterclayton** [comment]
Just happened again in https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/18740/test_pull_request_origin_extended_networking_minimal/14711/

**Comment by danwinship** [comment]
> Probably we should just kill off the extended_networking_minimal test, and instead make the conformance_gce test run the (minimal) extended networking tests, since it sets up a multi-node environment running the sdn.

#18540 fixes up the tests so we'd be able to do that if you'd like to review it. (Right now the default focus/skips assume that conformance-gce runs ovs-subnet, but that PR makes the skips be figured out at runtime based on whatever plugin is selected so that we can then change conformance-gce to run multitenant and then kill networking-minimal)

**Comment by dcbw** [comment]
Investigated this for a while...  I believe the issue is due to the /proc/1/cgroup paths that a container using systemd as PID 1 has.  For a DIND container we get:

`4:cpu,cpuacct:/system.slice/docker-10cdf0bdb77cc401a9ee9faba70ce36fc712cfd7399ea55439752a49bfe9d427.scope/system.slice/docker-10cdf0bdb77cc401a9ee9faba70ce36fc712cfd7399ea55439752a49bfe9d427.scope/init.scope`

Note how the same path is duplicated.  Running 'docker -it nginx bash', results in:

`4:cpu,cpuacct:/system.slice/docker-df9ecf01a95338243adfb587373ad7781d5610e248e827287257463fda555c4c.scope`

and in fact, patching runc (eg, docker) to de-duplicate the cgroup path and using that patched docker inside the "node" container appears to prevent the problem from occurring.

```
diff -up docker-4402c09586c72e0c32b90d72bd24304f609e2b7a/runc-1c91122c1d992cf1dc971ff14f78eddbf6fb06f5/libcontainer/cgroups/systemd/apply_systemd.go.foo docker-4402c09586c72e0c32b90d72bd24304f609e2b7a/runc-1c91122c1d992cf1dc971ff14f78eddbf6fb06f5/libcontainer/cgroups/systemd/apply_systemd.go
--- docker-4402c09586c72e0c32b90d72bd24304f609e2b7a/runc-1c91122c1d992cf1dc971ff14f78eddbf6fb06f5/libcontainer/cgroups/systemd/apply_systemd.go.foo	2018-02-28 09:44:39.060985054 -0600
+++ docker-4402c09586c72e0c32b90d72bd24304f609e2b7a/runc-1c91122c1d992cf1dc971ff14f78eddbf6fb06f5/libcontainer/cgroups/systemd/apply_systemd.go	2018-02-28 09:48:44.224528821 -0600
@@ -327,6 +327,38 @@ func ExpandSlice(slice string) (string,
 	return path, nil
 }
 
+func reduce(a string) string {
+	a = strings.TrimSuffix(a, "/")
+	alen := len(a)
+	if alen % 2 != 0 {
+		return a
+	}
+	if a[0:alen/2] == a[alen/2:] {
+		return a[alen/2:]
+	}
+	return a
+}
+
 func getSubsystemPath(c *configs.Cgroup, subsystem string) (string, error) {
 	mountpoint, err := cgroups.FindCgroupMountpoint(subsystem)
 	if err != nil {
@@ -340,6 +371,8 @@ func getSubsystemPath(c *configs.Cgroup,
 	// if pid 1 is systemd 226 or later, it will be in init.scope, not the root
 	initPath = strings.TrimSuffix(filepath.Clean(initPath), "init.scope")
 
+	initPath = reduce(initPath)
+
 	slice := "system.slice"
 	if c.Parent != "" {
 		slice = c.Parent
```

So next step is tracking down why systemd-based PID1 containers have these odd cgroup paths.

**Comment by smarterclayton** [comment]
This sounds really familiar to something that derek tracked down previously.

**Comment by smarterclayton** [comment]
Actually, no, this was something we hit with docker in docker systemd when
we tried to run docker in a pod.  So same use case.  We didn't figure out
the reason, but it's definitely broken.

**Comment by dcbw** [comment]
Update: things are fine in the container before pid1/systemd migrate from the initial cgroup to the "init.scope" cgroup.  Thats when the duplicate paths appear.
