### ISSUE TITLE
Ensure Router Integration Tests Can Run Inside of a Container

### ISSUE THREAD

**Issue by stevekuznetsov** [openshift/origin#13332]
It does not seem that the router integration tests function correctly inside of the `hack/env` container, as evidenced in [recent test runs](https://ci.openshift.redhat.com/jenkins/job/merge_pull_request_origin/20/). Changes to the job definitions have been reverted, so supporting this case is not blocking for the merge queue, but it is nevertheless very important that we get integration tests running inside of the `hack/env` container as we are running with the wrong version of `go` on the AMI test hosts.

The tests should have access to the `docker.sock` inside of the container, but it seems like the router container they start either never comes up or somehow otherwise fails to be networked to the container running the test client, as the connections do not succeed.

/cc @smarterclayton @knobunc @jim-minter

**Comment by stevekuznetsov** [comment]
@knobunc this is hopefully not enough work to warrant a card, so if you can, please, assign this as necessary.

**Comment by stevekuznetsov** [comment]
Today this is blocking AMI builds:
```
KUBE_COVER=" " KUBE_RACE=" " hack/test-integration.sh
01:33:53.430 ++ Building go targets for linux/amd64: test/integration/integration.test
01:44:43.205 # testmain
01:44:43.205 /usr/lib/golang/pkg/tool/linux_amd64/link: running gcc failed: exit status 1
01:44:43.205 collect2: error: ld returned 1 exit status
01:44:43.205 
01:44:43.453 [ERROR] PID 31826: hack/common.sh:153: `local -a binaries=("$@")` exited with status 1.
01:44:43.454 [INFO] 		Stack Trace: 
01:44:43.454 [INFO] 		  1: hack/common.sh:153: `local -a binaries=("$@")`
01:44:43.458 [INFO] 		  2: hack/build-go.sh:33: os::build::build_binaries
01:44:43.459 [INFO]   Exiting with code 1.
01:44:43.465 [ERROR] PID 31755: hack/test-integration.sh:38: `"${OS_ROOT}/hack/build-go.sh" "${package}/${name}.test"` exited with status 1.
01:44:43.466 [INFO] 		Stack Trace: 
01:44:43.467 [INFO] 		  1: hack/test-integration.sh:38: `"${OS_ROOT}/hack/build-go.sh" "${package}/${name}.test"`
01:44:43.467 [INFO]   Exiting with code 1.
01:44:43.467 Complete
01:44:43.468 make: *** [test-integration] Error 1
```

**Comment by smarterclayton** [comment]
How big are the ami vms?

On Mar 10, 2017, at 8:12 AM, Steve Kuznetsov <notifications@github.com>
wrote:

Today this is blocking AMI builds:

KUBE_COVER=" " KUBE_RACE=" " hack/test-integration.sh
01:33:53.430 ++ Building go targets for linux/amd64:
test/integration/integration.test
01:44:43.205 # testmain
01:44:43.205 /usr/lib/golang/pkg/tool/linux_amd64/link: running gcc
failed: exit status 1
01:44:43.205 collect2: error: ld returned 1 exit status
01:44:43.205
01:44:43.453 [ERROR] PID 31826: hack/common.sh:153: `local -a
binaries=("$@")` exited with status 1.
01:44:43.454 [INFO] 		Stack Trace:
01:44:43.454 [INFO] 		  1: hack/common.sh:153: `local -a binaries=("$@")`
01:44:43.458 [INFO] 		  2: hack/build-go.sh:33: os::build::build_binaries
01:44:43.459 [INFO]   Exiting with code 1.
01:44:43.465 [ERROR] PID 31755: hack/test-integration.sh:38:
`"${OS_ROOT}/hack/build-go.sh" "${package}/${name}.test"` exited with
status 1.
01:44:43.466 [INFO] 		Stack Trace:
01:44:43.467 [INFO] 		  1: hack/test-integration.sh:38:
`"${OS_ROOT}/hack/build-go.sh" "${package}/${name}.test"`
01:44:43.467 [INFO]   Exiting with code 1.
01:44:43.467 Complete
01:44:43.468 make: *** [test-integration] Error 1

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/origin/issues/13332#issuecomment-285665610>,
or mute the thread

**Comment by stevekuznetsov** [comment]
Same as always,

```
$ oct configure aws-defaults --view | grep master_instance_type
                        master_instance_type: m4.xlarge
```

I'm not seeing that error in `hack/env` so I'm not sure it's the VM issue

**Comment by stevekuznetsov** [comment]
Seems like we are confident this will never happen?

/close
