### ISSUE TITLE
how to define an environment variable to know if a container is running on openshift or not?

### ISSUE THREAD

**Issue by jstrachan** [openshift/origin#13410]
Is there any easy way to define an environment variable if we are running a pod on openshift?

e.g. for consoles using the kubernetes REST API they need to know if they are on openshift or not (e.g. should they use `/api/v1/namespaces` for kubernetes or `/oapi/v1/projects`for openshift.

Consoles can try a `GET` on something like `/oapi` but it'd be nice to avoid an extra request on the client before it can request namespaces/projects; so I was hoping to pass an environment variable in the HTML so we can know before the app starts if its openshift or kubernetes.

So far the best we've figured out is to try use the downwards API to expose the `openshift.io/deployment.name` annotation and if its not blank then its on openshift. That maybe only works for `DeploymentConfig` versus `Deployment` but its not a bad option.

I wonder if there's another / better idea to expose an env var in a container; without having to write a startup container shell script to curl the REST API or something?

**Comment by pweil-** [comment]
@jstrachan I think this depends too much on how the pod is run to say there is a good answer.  You could use the downward api to expose all annotations as a volume to the pod and if there are *any* that have openshift.io you can assume it is running in openshift.

I say that because what if the pod doesn't use a deployment config and uses a kube deployment?  There is also the scc annotation but an admin could turn off that plugin (though I don't think it is a normal use case).  

I think you'd still want to do the check for at the api level though to handle errors correctly so I would go that route.  Something like a head request to `/osapi` or `/version/openshift` shouldn't be terrible, I hope.  If so I'd say the sure way is to make it a parameter on your template so it is passed explicitly.

```
$ curl -k https://0.0.0.0:8443
{
  "paths": [
    "/api",
    "/api/v1",
    "/apis",
    "/apis/apps",
    "/apis/apps/v1beta1",
    "/apis/authentication.k8s.io",
    "/apis/authentication.k8s.io/v1beta1",
    "/apis/authorization.k8s.io",
    "/apis/authorization.k8s.io/v1beta1",
    "/apis/autoscaling",
    "/apis/autoscaling/v1",
    "/apis/batch",
    "/apis/batch/v1",
    "/apis/batch/v2alpha1",
    "/apis/certificates.k8s.io",
    "/apis/certificates.k8s.io/v1alpha1",
    "/apis/extensions",
    "/apis/extensions/v1beta1",
    "/apis/policy",
    "/apis/policy/v1beta1",
    "/apis/storage.k8s.io",
    "/apis/storage.k8s.io/v1beta1",
    "/controllers",
    "/healthz",
    "/healthz/ping",
    "/healthz/poststarthook/bootstrap-controller",
    "/healthz/poststarthook/ca-registration",
    "/healthz/poststarthook/extensions/third-party-resources",
    "/healthz/ready",
    "/metrics",
    "/oapi",
    "/oapi/v1",
    "/osapi",
    "/swaggerapi/",
    "/version",
    "/version/openshift"
  ]
}
```
