### ISSUE TITLE
New type needs to be added to addLegacyKnownTypes

### ISSUE THREAD

**Issue by jim-minter** [openshift/origin#13454]
See https://github.com/jim-minter/origin/commit/a609bf8763502677c19b8431038a909d605128a7

Without the head fixup commit, I get the following error on starting origin:

```
F0320 11:05:05.680241    9581 master.go:523] Unable to initialize v1 API: [error in registering resource: templatebrokeruuidmaps, unable to locate fully qualified kind for mapper resource templatebrokeruuidmaps: unable to locate fully qualified kind for *api.TemplateBrokerUUIDMap: found [template.openshift.io/__internal, Kind=TemplateBrokerUUIDMap] when registering for v1, error in registering resource: templateinstances, unable to locate fully qualified kind for mapper resource templateinstances: unable to locate fully qualified kind for *api.TemplateInstance: found [template.openshift.io/__internal, Kind=TemplateInstance] when registering for v1]
```

**Comment by mfojtik** [comment]
@openshift/api-review basically the problem here is that we should not be adding new types into legacy API, only to groups.

While I still need to find out why Jim got this error, I think at some point we need a test that will contain a list of all "legacy" resources and give you a fat error if you try to sneak a new type to legacy.

**Comment by deads2k** [comment]
> @openshift/api-review basically the problem here is that we should not be adding new types into legacy API, only to groups.

Copy out the dead APIs and register them separately I'd think.  The external versions are abandoned and conversions are kept up to date with the moved internal versions via fuzzing.

**Comment by mfojtik** [comment]
@deads2k I believe you mean this: https://github.com/mfojtik/origin/blob/master/pkg/cmd/server/origin/master.go#L511

Basically we should distinguish between resources that are registered only into a group vs. legacy resource and we should not register them in legacy api.

For the test, I guess we need to make a snapshot of the legacy resources we have today in a list and then guard that the list is not growing (a unit test?). Is that right?

**Comment by deads2k** [comment]
> Basically we should distinguish between resources that are registered only into a group vs. legacy resource and we should not register them in legacy api.

Yeah. I expected the legacy ones go into a bucket we never look at again.  Maybe even a different file we just mark for deletion.  Otherwise the loop you referenced has to start having a check: "should I really include this" which will amount to doing the same thing.

I guess I could see an argument for keeping the construction logic the same in GetRESTStorage, but I think that we're likely to want to break that apart like we did upstream.

In either case, you're right about wanting to create a test to make sure nothing new sneaks into the legacy scheme.

**Comment by mfojtik** [comment]
> I guess I could see an argument for keeping the construction logic the same in GetRESTStorage, but I think that we're likely to want to break that apart like we did upstream.

@deads2k agree -> https://github.com/openshift/origin/issues/13479

For now, I think I will move the legacy registration into its own file (legacy.go) and just call it in master.go (so it will be easely thrown away in distant future). I will also add legacy_test.go to check we don't add anything new into the API group schema.

@jim-minter after above is done, you can remove your types from the legacy schema, I will let you know when then PR merges (or can do it as a follow up).
