### ISSUE TITLE
node --boostrap fails 

### ISSUE THREAD

**Issue by debianmaster** [openshift/origin#13500]
i'm trying to use the new node bootstrap feature to bootstrap a new node.

Step 1:    started all in one server on node1
Step 2:   copied  admin.kubeconfig to node2
Step 3:   tried to bootstrap using   --bootstrap=true --kubeconfig=admin.kubeconfig

Bootstrap faile with timeout, more details in the last section

##### Version
oc v3.6.0-alpha.0+0343989
8d-0eda-11e7-b63a-42010a800003"). 
kubernetes v1.5.2+43a9be4
                     

##### Steps To Reproduce
node1:  146.148.85.109   (internal ip 10.128.0.3)
node2: 146.148.38.249

> on node1:   

    
```sh
./openshift start --public-master='https://146.148.85.109:443' --listen='https://0.0.0.0:443' --master='https://10.128.0.3:443'
```

> copy admin.kubeconfig to node2
  
> on node2  
```sh
./openshift start node --bootstrap --kubeconfig=admin.kubecofnig  --loglevel=6
```

##### Current Result

```sh
I0322 08:39:36.752063    2374 round_trippers.go:318] GET https://10.128.0.3:443/apis/certificates.k8s.io/v1alpha1/certificatesigningrequests/node-bootstrapper-client-ocp-cluster-p0vr 200 OK in 2 milliseconds
I0322 08:39:37.752309    2374 round_trippers.go:318] GET https://10.128.0.3:443/apis/certificates.k8s.io/v1alpha1/certificatesigningrequests/node-bootstrapper-client-ocp-cluster-p0vr 200 OK in 2 milliseconds
I0322 08:39:37.754002    2374 round_trippers.go:318] GET https://10.128.0.3:443/apis/certificates.k8s.io/v1alpha1/certificatesigningrequests/node-bootstrapper-client-ocp-cluster-p0vr 200 OK in 1 milliseconds
F0322 08:39:37.754139    2374 start_node.go:139] timed out waiting for the condition
```

##### Expected Result
node 2 should join openshift cluster as new node

##### Additional Information
[Note] Summary of diagnostics execution (version v3.6.0-alpha.0+0343989):
[Note] Warnings seen: 4

**Comment by smarterclayton** [comment]
You have to approve the certificates created by the node.

    $ oc get certificates
    $ oadm certificate approve NAME

**Comment by debianmaster** [comment]
no certificates created on master

```sh
[root@master1 ocp]# ./oc get certificates --all-namespaces=true                            
[root@node1 ocp]# ls openshift.local.config/node
the server doesn't have a resource type "certificates"  
```

i checked on node too but certs, i'm i missing anything?

**Comment by smarterclayton** [comment]
Ah, typo - "certificatesigningrequests"

**Comment by debianmaster** [comment]
New node logs after i did 
```sh
./openshift start node --bootstrap --kubeconfig=admin.kubecofnig  --loglevel=6
```

```sh
I0327 00:36:17.176397    1625 bootstrap_node.go:115] Bootstrap client cert approved
F0327 00:36:17.176660    1625 start_node.go:139] bootstrap client certificate does not match private key, you may need to delete the client CSR: tls: failed to find any PEM data in certificate input
```

**Comment by debianmaster** [comment]
@smarterclayton   any input pls.

**Comment by JacksonTech** [comment]
I have the same issue. Interestingly, the master-client.crt file in openshift.local.config/node is blank. Could this be the issue?

**Comment by debianmaster** [comment]
@JacksonTech   no luck ,  this really needs documentation on how to use

**Comment by JacksonTech** [comment]
@debianmaster tell you what, if we get it working, I will document it. I have a love for documentation!

**Comment by debianmaster** [comment]
@JacksonTech  sure thing, i'll let you know when i get lucky with this

**Comment by debianmaster** [comment]
@smarterclayton  any input on the error?  or README

**Comment by smarterclayton** [comment]
You would need to delete the empty file in that case.

**Comment by debianmaster** [comment]
@smarterclayton any chances of README document for this?   or any existing document  ?  i tried searching in tickets but got confused with exact commands

**Comment by debianmaster** [comment]
@smarterclayton  can you help creating a small README on how to use `oc cluster join`

**Comment by debianmaster** [comment]
@smarterclayton which kubeconfig should be used while bootstrapping a node?  is it admin.kubeconfig   or   openshift-master.kueconfig ?
i tried both.

with admin.kubeconfig
`bootstrap client certificate does not match private key, you may need to delete the client CSR: tls: failed to find any PEM data in certificate input`
with openshift-master.kubeconfig
`openshift start node --bootstrap --kubeconfig=openshift-master.kubeconfig  --enable='dns,kubelet,plugins,proxy' `

**Comment by pilhuhn** [comment]
@debianmaster Did you get any further?

**Comment by smarterclayton** [comment]
The bootstrap kubeconfig only needs permission to get and create CSRs which
both of those have.  Once the first client csr is created an admin must
approve it via oadm certificate approve.  Then the server cert must be
approved.

On May 30, 2017, at 11:57 AM, Heiko W. Rupp <notifications@github.com>
wrote:

@debianmaster <https://github.com/debianmaster> Did you get any further?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/origin/issues/13500#issuecomment-304924708>,
or mute the thread

**Comment by pilhuhn** [comment]
On 30 May 2017, at 18:06, Clayton Coleman wrote:

> The bootstrap kubeconfig only needs permission to get and create CSRs which
> both of those have.  Once the first client csr is created an admin must
> approve it via oadm certificate approve.

Ok, that works.

> Then the server cert must be
> approved.

Which one? On the node that is joining I guess?
Where do I get that from?

Thanks

**Comment by smarterclayton** [comment]
The kubelet creates a client cert, then requests a server cert, so you should see two CSRs.

**Comment by debianmaster** [comment]
Created node-bootstrap.kubeconfig with following command
```sh
oc project kube-system
oc adm policy add-cluster-role-to-user system:node-bootstrapper -z default
oc sa create-kubeconfig default  > node-boostrap.kubeconfig
```
Then on the new node used the generated node-boostrap.kubeconfig to boostrap openshift node with NO luck 

```sh
openshift start node --bootstrap=true  --kubeconfig=node-boostrap.kubeconfig
```
```sh
I0606 20:33:41.496081   22962 bootstrap_node.go:265] Bootstrapping from API server https://172.31.24.179:8443 (experimental)
F0606 20:33:57.766880   22962 start_node.go:139] bootstrap client certificate does not match private key, you may need to delete the client CSR: tls: failed to find any PEM data in certificate input
``

**Comment by debianmaster** [comment]
@smarterclayton any comment on the last error posted?

**Comment by debianmaster** [comment]
@smarterclayton   can you take a look at my comment above

**Comment by joelsmith** [comment]
I was able to get this to work on my 3.6 cluster. The issue was that my CSRs were `Approved`, but not `Issued`. That's because in my case, the certificates controller wasn't running. The reason it wasn't running was because it wasn't configured with the paths to the CA certificate and key. Although you've already done some of these steps, I'll put everything that I did to get it working so that anybody else who happens upon this can get it working too (if their issues are like mine).

1. Configure the built-in certificates controller so that it will issue certificates for any approved CSRs. Edit your `master-config.yaml` file and change `kubernetesMasterConfig.controllerArguments` from this:
```
  controllerArguments: null
```
to this:
```
  controllerArguments:
    cluster-signing-cert-file: [ /full/path/to/your/cluster/master/config/ca.crt ]
    cluster-signing-key-file: [ /full/path/to/your/cluster/master/config/ca.key ]
```
then start or restart the master.
2. While in the process of bootstrapping nodes, leave an approval controller running which will auto-approve any CSRs created on the cluster. The idea is that anyone who is allowed to create a CSR should be issued a certificate. If that doesn't match your security model, then you can still approve CSRs by hand using `oc get csr` and then `oc adm certificate approve <csr_name>`. I run these while logged in as admin, but an account that only has privs to approve CSRs could be used instead. Here's how to run the auto-approving controller:

```
oc observe csr -- oc adm certificate approve
```

3. Bootstrap the node. You can create a service account with all the right privs, but I just used the admin account. I temporarily copied the `admin.kubeconfig` to the new node, then ran this on the new node, then removed the admin creds:
```
openshift start node --bootstrap --kubeconfig=`pwd`/admin.kubeconfig --loglevel=6
```
4. Once it's all bootstrapped and shows up in `oc get nodes`, stop the node, and restart it with the generated node config:
```
openshift start node --config=openshift.local.config/node/node-config.yaml
```

5. If you've changed the `imageConfig.format` field in your master's node config, you may need to hand-edit the node config of new nodes to make them match, then restart the node.

6. Shutdown the auto-approval controller you started in step 2

Here @smarterclayton describes the process too: https://github.com/openshift/openshift-ansible/issues/4685

**Comment by debianmaster** [comment]
thanks @joelsmith  i'll give a try.  this one is my long term dream :)
