### ISSUE TITLE
WebUI not working in Safari

### ISSUE THREAD

**Issue by benediktreichert** [openshift/origin#13506]
When trying to acces the webUI with Safari, I get into a crash loop and can't login. 
```
Error

An error has occurred

Unable to load details about the server. If the problem continues, please contact your system administrator.

Return to the console.
```

All of a sudden, I can login but I get repeated error messages in the lower right of Safari saying `Server connection interrupted`

##### Version
openshift v1.4.1
kubernetes v1.4.0+776c994
##### Steps To Reproduce
1. open standard webUI (port 8443)

##### Current Result
Error message on open shift webui and `connection interrupted` messages.
##### Expected Result
Normal webUI

**Comment by jwforres** [comment]
The server connection interrupted messages are because of how safari handles self-signed cert acceptance.  If you just click "Continue" on the popup, then it doesn't extend the cert acceptance to the websockets that will be opened.  So only the initial XHR requests succeed and the subsequent websocket watches will all fail.  This behavior is unique to Safari.  To fix this you need to actually permanently accept the cert.

**Comment by benediktreichert** [comment]
I tried various things such as accepting the certs permanently, did not help either.

**Comment by jwforres** [comment]
The certificate acceptance flow in Safari has changed with the update to High Sierra.  Would like to know if folks are still reproducing the issues now.

**Comment by snipem** [comment]
@benediktreichert Have you tried it with High Sierra as suggested above?

**Comment by wagnersza** [comment]
+1

**Comment by addozhang** [comment]
Same issue here. After click button 'Continue', it starts loop. Close tab and wait minutes, or restart safari, it works fine. But minutes later, it popups to ask client key again. 

Issue went away after delete the cert from keychain. 

![image](https://user-images.githubusercontent.com/2224492/41947140-74a62f96-79e8-11e8-894c-c1f5402d2eed.png)
