### ISSUE TITLE
Question - what is the IPfailover multi VIPs use case?

### ISSUE THREAD

**Issue by DanyC97** [openshift/origin#13561]
Hi,

Hopefully someone can help me understand better what is the IPfailover use case for having multi VIPs assigned to one DC?

So i've done a bit of research and found [this](https://github.com/openshift/origin/issues/6396#issuecomment-167022011) , [this](https://lists.openshift.redhat.com/openshift-archives/users/2015-October/msg00123.html) and [this](https://lists.openshift.redhat.com/openshift-archives/users/2015-October/msg00124.html)  however i'm not sure if that is the case with most recent versions.

For a setup as below:
* 3 nodes labeled `router=on`
* 1 router dc with 3 replicas and selector `router=on`
* 1 ipfailover dc with  3 replicas and 3 VIPs and selector `router=on`

My questions are:

* is that indicated for a production environment? 
* should the ipfailover's replicas be less than the number of nodes
* should the route's replicas be less than the number of nodes (leave extra nodes in case a new router pod needs to be spun up - ie say 1 node crashed) 
* what will be the benefit of running an ipfailover dc with multiple VIPs ?
*** if is for failover than 1 VIP will be enough since keepalived will float over and so no impact
*** if is for distributing the load traffic (due to 1 VIP <> 1 Keepalived <> 1 router) than is more of a best effort since the DNS will do a round-robin so not a clear control over traffic distribution.

**Comment by DanyC97** [comment]
@knobunc @ramr @pecameron i noticed through git history you guys might be familiar with this code and maybe able to help me understand better the IPFailover multi VIPs use case? (see above questions)

Thanks in advance !

**Comment by knobunc** [comment]
Answers:

# It is advisable to set up a VIP and more than one router for fault tolerance
# The ipfailover DC replicas and router DC replicas should be the same (but it need not be the number of nodes, and in fact would likely be much lower; but it needs to match the number of nodes with the selector set).  The ipfailover DC and router DC selectors need to be the same.  The reason being that you need the ipfailover pods to be on the same nodes as the router pods.
# The number of replias for the router and ipfailover needs to equal the number of nodes the node selector matches
# The advantage to running the dc with multiple VIPs is to provide improved bandwidth in to the cluster.  1 VIP will only be assigned to a single node, so all traffic in will to go that node (until it fails, then it will all go to a different node).  Having 3 VIPs would allow you to publish 3 addresses externally and so each node will get 1/3 of traffic.  The problem being that if one fails, and you only have 3 nodes, now one node will get 2/3 of traffic... so you may want to run 3 VIPs on 4 nodes... or make sure a single node can handle 2/3 of traffic.

**Comment by pecameron** [comment]
Answers:

1) Setup is recommended (not sure about the 3 VIPS)
keepalived negotiates for a suitable node and it may turn out all VIPs are on the same node. VIPs don't move unless a failure is detected (probe to watch port fails). So if a node that in the set that is not currently supporting a VIP goes down, nothing happens, When it comes back, nothing happens. If they were distributed when the setup came up, after a failure they will never be evenly distributed again.

2) ipfailover replicas can be more or less than the router replicas. However, that may not work in every scenario (one router node must be the same node as an ipfailover replica), also, you don't get redundancy unless 2 routers land on 2 ipfailover nodes). It is best, and easiest, to match routers and ipfailover nodes.

3) I would go for one router per ipfailover.

4) I am not sure there is a benefit using multiple VIPs and let the admin set up load balancing in dns. I would think of using router sharding to distribute the load. The cluster admin has more control. (It will use more nodes, though).

- keepalived uses the VRRP protocol to figure out which node (if any) should service the VIP. 
- I am not sure VRRP will always distribute the VIPs to different nodes.
- Once a VIP is on a node it stays there until the health probe fails or the node dies.
- Not sure what multiple VIPs buys you. keepalived negotiates for a suitable node and it may turn out all VIPs are on the same node. VIPs don't move unless a failure is detected (probe to watch port fails). So if a node that in the set that is not currently supporting a VIP goes down, nothing happens, When it comes back, nothing happens.

**Comment by DanyC97** [comment]
@knobunc @pweil- thank you for detailed answers, much appreciated !

Seems i missed the fact that after a failure the VIP doesn't "return" to its previous "home" hence the non-even VIP distribution.

Seems there is not an easy agreement with multiple VIPs value and the best answer for fault tolerance & load balancing use case.

**Comment by ramr** [comment]
@DanyC97 sorry for the delayed reply - as they say nothing is certain but death and taxes and 'twas the latter! A wee bit of clarifications - when this was done initially, the basic idea and the ideal configuration was/is:
1. `oc label node ...`
    Label a set of nodes `n` for running the routers/ipfailover. Basically define a selector on the nodes so that k8s would schedule the router/ipfailover pods on those `n` nodes.
2. `10.1.2.42, IP 10.1.2.100-102`
     Pick a range or couple of VIPs (> 1 for redundancy) and run the ipfailover with those VIPs.
3. `ipfailover-replicas >= n`
     Have the ipfailover replicas run on all the nodes allocated using the selector. The number of ipfailover replicas can be greater and doesn't hurt as the ipfailover pods can only be run one per node. There's like a port reservation thing that took care of that and it changed to some other k8s mechanism - can't remember what - @pecameron  might know. In any case, there's only one ipfailover pod on any individual node, so for `n` nodes, there would be  one-on-each-node/`n` ipfailover pods.
4. `router-replicas <= n` 
    Run the router replicas (> 1 for redundancy/failure as @knobunc  mentioned) with number of 
    router replicas less than the allocated set and of course with the selector used in 1.

That way:
A. The ipfailover pods would run on all the available nodes on the set.  
B. The router pods would run on a subset of those `n` nodes.

And on each node, the ipfailover pod would monitor/watch for the router service and if there is a router pod on that node, that node is a candidate to get one of the VIPs. I say candidate because there can be more router pods than VIPs.  

Net result is a set of VIPs distributed across the `n` nodes. Only the nodes with a router pod running on them would have one or more VIPs. 

``` ```

Which brings us to failure handling:
- On a router failure, the local  ipfailover/keepalived pods would notice that the router is down and relinquish ownership of any VIPs assigned on that node. And the VIPs would `float` over to another node in that `n` set running a router pod. 
- On a node failure, the remaining peer ipfailover/keepalived pods would notice a peer down and would then `float` over any VIPs from that node amongst themselves.
- On a ipfailover pod failing, that case is the same as above if a node fails.

``` ```

So for your use case, I'd say the only change that I'd recommend is to the router replicas. 
- 3 nodes labeled router=on
- 1 router dc with `2` replicas and selector router=on
- 1 ipfailover dc with 3 replicas and 3 VIPs and selector router=on

And possibly the VIPs as well (you could go `5`  if you have no ip address issues) as there'd be some traffic skew with one router getting double the traffic. But that said if the incoming request rate to the router is low, it should not be an issue plus in most environments, not all requests are equal (some are quick to complete and some are slower) so the in-progress request skew might not even be noticeable. 

HTH

**Comment by DanyC97** [comment]
thanks @ramr  !
