### ISSUE TITLE
bash: line 5: os::build::rpm::get_nvra_vars: command not found

### ISSUE THREAD

**Issue by sjenning** [openshift/origin#13607]
https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin_extended_conformance_install/736/console

```
+ os::build::rpm::get_nvra_vars
bash: line 5: os::build::rpm::get_nvra_vars: command not found
++ os::util::trap::err_handler
++ local -r return_code=127
++ local -r last_command=os::build::rpm::get_nvra_vars
```

**Comment by jhadvig** [comment]
This issue has been already fixed by: https://github.com/openshift/origin/commit/b95268c2cad60631429804413faa375b84dcd6f4
it appeader cause we had to update the test_pull_request_origin_extended_conformance_install job but also the function name cause we added additional architecture type to the output. I counted that this flake would appear in at least one of our jobs.
Closing this issue since other install and install_upgrade jobs are not having it.
