### ISSUE TITLE
Why three masters ?

### ISSUE THREAD

**Issue by soufiane8096** [openshift/origin#13734]
Hi,

I'm trying to understand how work OpenShift, I read a sentence that I did not understand in documentation. Can someone give more explications about it :
"If etcd is being installed on the master hosts, you must configure your cluster to use at least three masters. It cannot use only two masters, because etcd would not be able to decide which one is authoritative. The only way to successfully run only two masters is if you install etcd on hosts other than the masters." source : https://docs.openshift.com/container-platform/3.3/admin_solutions/master_node_config.html

If one of the three masters goes down, only two will work, so it's possible to work with 2 masters only ?

Thank your for your help !

**Comment by pweil-** [comment]
etcd requires the majority vote to agree on cluster state.  Starting etcd with 3 members means that the majority vote is 2.  A failure of one node during runtime is acceptable since majority can still be reached.

If starting with only 2 masters the majority vote is 2, if both masters have opposing views none can win and there is no failure tolerance since the absence of any master prevents reaching the majority.

**Comment by soufiane8096** [comment]
Thank you for your answer, but how it works if a mastrer goes down ? We will have only 2 masters : there is no majority ?
