### ISSUE TITLE
Extended.[k8s.io] Namespaces [Serial] should ensure that all pods are removed when a namespace is deleted.

### ISSUE THREAD

**Issue by bparees** [openshift/origin#13758]
```
/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/test/e2e/namespace.go:216
Expected an error to have occurred.  Got:
    <nil>: nil
/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/test/e2e/namespace.go:128
```

https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin_extended_conformance_install_update/97/

**Comment by derekwaynecarr** [comment]
weird, if the line number is accurate, we deleted a namespace, and then fetched a pod by name in that namespace and did not get an error as expected.  since we do the same thing on virtually every e2e run, i am reducing severity.  we can look to add some more debugging for when it fails here (i.e. print out the pod that was fetched if found).

**Comment by smarterclayton** [comment]
Boom, found it.

https://github.com/kubernetes/kubernetes/issues/47350#issuecomment-470802348

**Comment by smarterclayton** [comment]
(well, found one of the causes)
