### ISSUE TITLE
Dockerfile not present in committed image when building from source with override Dockerfile

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#13774]
A Docker build that sets a custom dockerfile and Git source that itself contains a dockerfile doesn't contain a dockerfile at the end of the build.  It's probably because of the default .dockerignore behavior, but still is unexpected.

Fix may not be worth it if it diverges from Docker hub too much.

**Comment by bparees** [comment]
I'm confused... the dockerfile is never present in the committed image, unless you explicitly add/reference it in your Dockerfile.

**Comment by bparees** [comment]
@smarterclayton i think maybe we talked about this and your concern was that the dockerfile from the git repo gets overwritten by the inline dockerfile, and thus is not available in the build context.  Can you confirm that?  And if so, i seem to recall you had a proposed behavior, but I can't remember what it was.  Renaming the dockerfile from git as "dockerfile.git" or some such hack?

**Comment by smarterclayton** [comment]
May the injected one should not be called Dockerfile - `Dockerfile.injected` or something.

**Comment by bparees** [comment]
@smarterclayton i have some niggling backwards compatibility concerns about that.

Someone who's inline Dockerfile currently says:

```
FROM foo
ADD Dockerfile /tmp/input_dockerfile
```

Because they want a record of the dockerfile that as used to build the image, included in the image,
is not going to get what they expected (in fact their build would now fail).

**Comment by bparees** [comment]
i don't see a backwards compatible way to address this.  we have to continue to lay down the inline dockerfile as "Dockerfile" since existing build logic could be referencing it with that name.  Users who have a "Dockerfile" in their git repo and are worried about it being clobbered by an inline dockerfile definition will just have to rename the file in their git repo to avoid it.

closing, but @smarterclayton please reopen if you see a solution (or are comfortable w/ the behavior change)
