### ISSUE TITLE
TASK [Update registry image to current version]

### ISSUE THREAD

**Issue by kargakis** [openshift/origin#13811]
```
TASK [Update registry image to current version] ********************************
task path: /usr/share/ansible/openshift-ansible/playbooks/common/openshift-cluster/upgrades/post_control_plane.yml:54
fatal: [localhost]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "generated_timestamp": "2017-04-18 15:12:42.543876", 
    "msg": {
        "cmd": "/bin/oc replace -f /tmp/docker-registry-Aa4mWj -n default", 
        "results": {}, 
        "returncode": 1, 
        "stderr": "Error from server (Conflict): error when replacing \"/tmp/docker-registry-Aa4mWj\": Operation cannot be fulfilled on deploymentconfigs.apps.openshift.io \"docker-registry\": the object has been modified; please apply your changes to the latest version and try again\n", 
        "stdout": ""
    }
}
```

**Comment by kargakis** [comment]
https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin_extended_conformance_install_update/193/consoleFull#197040384158b6e51eb7608a5981914356

**Comment by kargakis** [comment]
The job is installing openshift-ansible-3.5.53-1.git.0.8ade9f2.el7.

The openshift-ansible release-1.5 branch [seems to use patch](https://github.com/openshift/openshift-ansible/blob/29802ee84c98f71de2288093ec5bb85fa6feb4ca/playbooks/common/openshift-cluster/upgrades/post_control_plane.yml#L56) whereas in master, [an oc_edit module is used](https://github.com/openshift/openshift-ansible/blob/6978114e166ce5fd0737e0c2957a7315d4e5fa41/playbooks/common/openshift-cluster/upgrades/post_control_plane.yml#L54). Yet, the test fails because it seems like `oc replace` is actually used which is doing a PUT instead of a PATCH so it's subject to 409s that don't touch the field `replace` wants to update. I am confused.

@sdodson any ideas?

**Comment by sdodson** [comment]
Yeah, we should update oc_edit to use patch if possible. @kwoodson what do you think?

**Comment by kargakis** [comment]
FWIW, `oc edit` is using PATCH already but oc_edit seems to use `oc replace`...

**Comment by kwoodson** [comment]
The reason we are seeing this error is that it is a race condition.  The object (dc) was read out, modified, and then an `oc replace` was called from the `oc_edit` module.  The problem occurs when we attempt to replace.  The issue is that something has updated the dc which increases the `resourceVersion`.  When we go to replace the dc, our revision is behind and therefore we receive the `the object has been modified` error message.

There are a few proposals to solve this problem.  I'll discuss those at the bottom.  I'll address the issues we've had with using the `patch` command.

`oc patch` is not idempotent.  This is a major issue for us.
This is a typical workflow for us.  The first patch command succeeds and returns a 0 for the return code.
```bash
[root@ip-172-31-62-161 ~]# oc get dc router-internal -n default -o yaml | grep "intervalSeconds"
      intervalSeconds: 1
[root@ip-172-31-62-161 ~]# oc patch dc router-internal -n default -p '{"spec": {"strategy": {"rollingParams": {"intervalSeconds": 2}}}}'
"router-internal" patched
[root@ip-172-31-62-161 ~]# echo $?
0
[root@ip-172-31-62-161 ~]# oc get dc router-internal -n default -o yaml | grep "intervalSeconds"
      intervalSeconds: 2
```

Here in enters the problem.  When we rerun the `patch` command we see that the message was that the dc was patched and the returncode is the same, 0.  What did this actually do?  Did this make any changes? Did something get updated?  Does this cause a redeploy of services?  
```
[root@ip-172-31-62-161 ~]# oc patch dc router-internal -n default -p '{"spec": {"strategy": {"rollingParams": {"intervalSeconds": 2}}}}'
"router-internal" patched
[root@ip-172-31-62-161 ~]# echo $?
0
```
We need to be able to audit changes when they occur.  This is essential for administrators for a number of reasons:

- customers track changes and compare outages against them
- handlers fire on changed events
- idempotency requires changes only when required

There are a couple of proposals that we could use to fix this.

- The first proposal is to continue to use replace but do **not** pass the `resourceVersion` in our `oc replace`.  This will basically stomp any other edits that have occurred during the time that we have read the object and attempted to make our changes.
- The second proposal would be to attempt a retry when performing our changes.  This would still be vulnerable to the same error message but would build in some resiliency.  We would probably want to institute a retry limit and maybe a timeout.

**Comment by ashcrow** [comment]
@kwoodson I see what you are saying. The two proposals are doable but have some pretty frustrating downsides as you note. Short of patching upstream to give more information on ``patch`` I have one idea. What about having the modules do a more complex set of operations to ensure idempotency?

1. Retrieve the object as A
2. Patch the object
3. Retrieve the object as B
4. Diff A and B for changes (removing anything that auto changes with)

It's not perfect either but it may give you the power of ``patch`` with the results you are looking for.

**Comment by sdodson** [comment]
@deads2k any thoughts on what the right way to idempotently patch something should be? Could we just make `oc patch` let us know when there's a change?

**Comment by kargakis** [comment]
FWIW, there is discussion upstream for adding retries in the client library (https://github.com/kubernetes/kubernetes/issues/21479) and eventually in kubectl (https://github.com/kubernetes/kubernetes/issues/5762, https://github.com/kubernetes/kubernetes/issues/23993).

Whatever command is used, consider renaming the module after the command. At least for keeping future maintainers sane.

**Comment by kwoodson** [comment]
https://github.com/openshift/origin/issues/13811#issuecomment-296209565

**Comment by sdodson** [comment]
and backport to release-1.5 in https://github.com/openshift/openshift-ansible/pull/3987
