### ISSUE TITLE
Can't delete images from OpenShift registry

### ISSUE THREAD

**Issue by juanjoDiaz** [openshift/origin#13870]
Can't delete images from OpenShift registry

##### Version
v1.4.1+3f9807a

##### Steps To Reproduce
Following docker-registry documentation I get the image digest
1. GET `https://myreg/v2/myproject/myimage/manifests/mytag` with header`Accept: application/vnd.docker.distribution.manifest.v2+json`
2. Read the digest from Docker-Content-Digest  or Etag and try removing the image
3. DELETE `https://myreg/v2/myproject/myimage/manifests/mydigest`

##### Current Result
DELETE `https://myreg/v2/myproject/myimage/manifests/mydigest` fails
```
{
  "errors": [
    {
      "code": "MANIFEST_UNKNOWN",
      "message": "manifest unknown"
    }
  ]
}
```
However, GET `https://myreg/v2/myproject/myimage/manifests/mydigest` works, so the digest is correct

##### Expected Result
The image is removed from the registry

**Comment by legionus** [comment]
@juanjoDiaz You can not delete an image from the integrated registry using its API. This can not be done because in the openshift cluster this image can still be used. In the cluster, there is a system for removing unused images ([Pruning Images](https://docs.openshift.org/latest/admin_guide/pruning_resources.html#pruning-images)).
