### ISSUE TITLE
oc cluster up exits prior to checking all registries for a container image

### ISSUE THREAD

**Issue by nhorman** [openshift/origin#13878]
running oc cluster up, I receieve the following error:
oc cluster up
-- Checking OpenShift client ... OK
-- Checking Docker client ... OK
-- Checking Docker version ... OK
-- Checking for existing OpenShift container ... OK
-- Checking for registry.access.redhat.com/openshift3/ose:v3.5.5.7 image ... 
   Pulling image registry.access.redhat.com/openshift3/ose:v3.5.5.7
FAIL
   Error: error pulling Docker image registry.access.redhat.com/openshift3/ose:v3.5.5.7
   Caused By:
     Error: error parsing HTTP 404 response body: invalid character 'F' looking for beginning of value: "File not found.\""

##### Version
oc v3.5.5.7
kubernetes v1.5.2+43a9be4
features: Basic-Auth GSSAPI Kerberos SPNEGO

##### Steps To Reproduce
run oc cluster up specifying a version that doesn't exist in the canonical upstream registry

##### Current Result
exit prior to checking the next configured registry

##### Expected Result
should check all configured registries for specified container image:tag

**Comment by nhorman** [comment]
FWIW, images exist in the local registry, and earlier releases found them just fine:
[root@ibm-p8-cluster-01 ~]# docker images
REPOSITORY                       TAG                 IMAGE ID            CREATED             SIZE
test/httpd-container             latest              a0bfa7f950e1        4 days ago          518.6 MB
openshift3/ose-sti-builder       v3.5.5.7            f8f79c900b6a        4 days ago          1.015 GB
openshift3/ose-haproxy-router    v3.5.5.7            4dc0ce97f5fa        4 days ago          1.04 GB
openshift3/ose-pod               v3.5.5.7            4dc0ce97f5fa        4 days ago          1.04 GB
openshift3/ose-docker-builder    v3.5.5.7            f9e9e0c5b87d        4 days ago          1.015 GB
openshift3/ose-docker-registry   v3.5.5.7            d123c660546a        4 days ago          1.074 GB
openshift3/ose                   v3.5.5.7            c48ee786c8be        4 days ago          1.015 GB
openshift3/ose-base              v3.5.5.7            31197e0f681b        4 days ago          626.1 MB
rhel7.3                          7.3-released        1169cd3003b5        4 days ago          414.6 MB

**Comment by sudswas** [comment]
It appears that the binary was built with OS_IMAGE_PREFIX set to the redhat registry.
In such a case, the openshift code: https://github.com/openshift/origin/blob/0d82899e0ae56a855ad557c633e57dac36e85a65/pkg/bootstrap/docker/up.go#L238 will always default to using that particular registry. 

This change seems to have happened since this commit: https://github.com/openshift/origin/pull/12758/commits/5237fda6a1f1fc0ca770ac04071e07ab30b8de2a#diff-f4e81489ff94a80b6c06c769fac10d80

Which means - in order to make this work - we will have to either use oc cluster up --image=openshift/originor just simply pass a LDFLAG option where we specify the OS_IMAGE_PREFIX to suit our needs during make build.

Alternatively, we should be able to tag the docker images locally with the registry tag - for it to pick up the images from the local registry.

**Comment by nhorman** [comment]
Ok, I suppose thats a reasonable behavioral change.  The failed 404 parsing should still be fixed though.

**Comment by bparees** [comment]
the default image prefix has actually been fixed so the next 3.5 errata should not require the explicitly --image flag (nor will 3.6).  However I agree that the parsing issue should be fixed, so we'll leave this open for that.

**Comment by csrwng** [comment]
The parsing issue is in Docker ... the result that gets returned is an error returned from the pull API call.

**Comment by bparees** [comment]
sounds like we can't do much to improve the message here.
