### ISSUE TITLE
"Quota limit has been reached" gets easily misunderstood / ignored

### ISSUE THREAD

**Issue by maxandersen** [openshift/origin#13976]
I've been running with quotas for a while now and I keep getting mislead with the "Quota limit has been reached" - I keep thinking the system is wrong as I read it as "Quota limit has been exceeded" AND that I should do something about it.

If it was memory or disk size then sure - it might be useful to know, but for the case of using 2 volumes out of 2 then that is not really something as a user I need to be told on every load of the console. Especially since it makes me ignore the message when/if an *Actual* resource issue warning happens.

##### Version
3.5

##### Steps To Reproduce
1. Have all resources of some type used  (like volume mounts)
2. See a sticky warning on top in your console

##### Current Result
This is shown in my console always, even though there are no actual issue.
![quota_limit_reached](https://cloud.githubusercontent.com/assets/54129/25582600/65bb0070-2e8e-11e7-9ee7-de2f9b0e01e6.png)

##### Expected Result
Don't show me a Warning (yellow triangle) when I'm simply just using the resources made available to me.

i.e. using 2 out of 2 volume mounts is a normal thing, not a warning.
For disk and memory usage it is different - i.e. if I'm trending towards using all 1GB memory I would like to know - but for volumes it is more misleading than informative.

**Comment by jwforres** [comment]
This is being tracked in trello now https://trello.com/c/ITpnCvsj

**Comment by spadgett** [comment]
This will be greatly improved by https://github.com/openshift/origin-web-console/pull/2116

* Quota notifications are put in a notification drawer and are less intrusive.
* We've added separate notifications for each quota type instead of one generic warning.
* When you're at quota and not over, it's an info message instead of a warning.
* The usage and max is displayed in the notification message.
* You can say "Don't Show Me Again" per quota type.
* Administrators can add custom messages to the quota warning.

I think this addresses most issues you raise. Let us know!
