### ISSUE TITLE
Trigger new deployment when ICT trigger changes

### ISSUE THREAD

**Issue by mfojtik** [openshift/origin#13988]
Follow up for: https://github.com/openshift/origin/pull/13886

We should fix the generic trigger mechanism to trigger new deployment when the ICT configuration is changed. This configuration is not managed by ConfigChange trigger (it is not the podTemplate).

We can check the serialized previous ICT and if it does not match we can trigger based on that.

**Comment by mfojtik** [comment]
@smarterclayton how does the generic trigger handle changes to the annotation?

**Comment by smarterclayton** [comment]
Changes trigger fires iff the core code allows it.  But the new "object"
has to change

On May 30, 2017, at 6:17 AM, Michal Fojtik <notifications@github.com> wrote:

@smarterclayton <https://github.com/smarterclayton> how does the generic
trigger handle changes to the annotation?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/origin/issues/13988#issuecomment-304835903>,
or mute the thread
