### ISSUE TITLE
3.6 Upgrade Failure: Build quota e2e fails

### ISSUE THREAD

**Issue by stevekuznetsov** [openshift/origin#13999]
When installing Origin 1.5 and upgrading to Origin 3.6, we see 1 quota test fail on the e2e suite:

 -  Extended.[builds][Conformance] s2i build with a quota Building from a template should create an s2i build with a quota and run it

These failures can be seen in every `test_branch_origin_extended_conformance_install_update` job until [299](https://ci.openshift.redhat.com/jenkins/job/test_branch_origin_extended_conformance_install_update/299/testReport/(root)/Extended/_builds__Conformance__s2i_build_with_a_quota_Building_from_a_template_should_create_an_s2i_build_with_a_quota_and_run_it/)

Issue https://github.com/openshift/origin/pull/13906 was referenced as a fix for this but does not seem to have worked.

**Comment by stevekuznetsov** [comment]
I've added a `[testupgrade]` trigger to PRs for Origin that will trigger this test against a PR.

**Comment by bparees** [comment]
@stevekuznetsov we run this test as part of normal conformance merge also (where it is passing), so if it's failing in the upgrade test then i would speculate on an issue w/ the upgrade environment or test run(are we sure the upgrade test is running the latest master tests for example?).  

Not to mention there were 53 failures in run 299, so that hardly seems like a healthy environment to base conclusions on.

**Comment by stevekuznetsov** [comment]
> if it's failing in the upgrade test then i would speculate on an issue w/ the upgrade environment

Yes, this is absolutely the cause.

> are we sure the upgrade test is running the latest master tests

Yes.

> Not to mention there were 53 failures in run 299, so that hardly seems like a healthy environment to base conclusions on.

No. As written above, this is part of three failures that appeared more than a week before the other 50. The other 50 are #13997 and due to the rebase. These reliably happened 100% of the time without the rebase.

**Comment by bparees** [comment]
Your other comment was not clear to me, but now i'm drawing the conclusion that you've disabled this test in the normal runs?  

I strongly suspect the buildcontroller which is responsible for emitting these events was either not upgraded, or not restarted w/ new code post-upgrade.

**Comment by bparees** [comment]
(because when this test was failing in the normal case, it was a flake, not a consistent failure)

**Comment by stevekuznetsov** [comment]
> Your other comment was not clear to me, but now i'm drawing the conclusion that you've disabled this test in the normal runs?

The upgrade job does not run for merges, but does run post-merge on every commit in Origin.

> I strongly suspect the buildcontroller which is responsible for emitting these events was either not upgraded, or not restarted w/ new code post-upgrade.

@sdodson can you triage to someone who knows about this please

**Comment by sdodson** [comment]
We don't do any explicit conversion unless asked to do so, if there are upgrade steps we need to add here lets detail what those are and we'll get them added to the upgrade.

Otherwise, api and controllers are upgraded, policy is reconciled, nodes are upgraded, then router and registry are updated.

**Comment by stevekuznetsov** [comment]
@bparees are there other steps on upgrade that you would expect us to take?

**Comment by bparees** [comment]
> @bparees are there other steps on upgrade that you would expect us to take?

i don't actually know what the upgrade process looks like, it just really seems (from a blackbox perspective) for those events not to be emitted, the controller must be running at an older level that didn't have the code for emitting the events. (again because the test works fine on a pure 3.6 install....  at worst it was flaking, which i'm pretty sure is fixed, and it certainly never failed consistently).

this plus the other failing test (the imagebuilder one) all point to an environment that is not actually running 3.6 code.  How confident are we that the upgrade actually occurred and did what we expect?  Is validating that in any way part of the upgrade test?

**Comment by bparees** [comment]
I'm reasonably confident this is failing because the cluster isn't actually being upgraded (as discussed in the other issue).

**Comment by sdodson** [comment]
I agree, working on that today.

**Comment by stevekuznetsov** [comment]
Has since been fixed.
