### ISSUE TITLE
oc describe template is showing "<unknown>" objects

### ISSUE THREAD

**Issue by spadgett** [openshift/origin#14058]
DeploymentConfig and PVC are not being displayed correctly.

```
$ oc describe template rails-pgsql-persistent -n openshift
[...]
Objects:
    Secret	${NAME}
    Service	${NAME}
    Route	${NAME}
    ImageStream	${NAME}
    BuildConfig	${NAME}
    <unknown>
    <unknown>
    Service	${DATABASE_SERVICE_NAME}
    <unknown>
```

Built from current master.

```
$ oc version
oc v1.0.4+02d2097-12909
kubernetes v1.6.1+5115d708d7
features: Basic-Auth

Server https://127.0.0.1:8443
openshift v3.6.0-alpha.1+46942ad
kubernetes v1.5.2+43a9be4
```

cc @fabianofranz @jwforres

**Comment by ncdc** [comment]
We presumably broke something adapting to kube's client factory refactors. cc @sttts @liggitt @deads2k.

**Comment by jwforres** [comment]
I was seeing it with an OC client built before the rebase, I can get you
the version tmrw if it helps

On May 4, 2017 8:21 PM, "Andy Goldstein" <notifications@github.com> wrote:

We presumably broke something adapting to kube's client factory refactors.
cc @sttts <https://github.com/sttts> @liggitt <https://github.com/liggitt>
@deads2k <https://github.com/deads2k>.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/origin/issues/14058#issuecomment-299343865>,
or mute the thread

**Comment by fabianofranz** [comment]
A few kinds (dc, pvc, and ist at least) are failing in `runtime.Decode` already which is called by `DecodeList` in the `TemplateDescriber` [here](https://github.com/openshift/origin/blob/master/pkg/cmd/cli/describe/describer.go#L1070). 

Failure is `ErrFormatWrong` ("quantities must match the regular expression 'redacted'"). Investigating.

**Comment by fabianofranz** [comment]
Probably because resource limits (a `ResourceList` object) in template objects have env vars as values most the time (e.g. `"memory": "${MEMORY_POSTGRESQL_LIMIT}"` and `"memory": "${MEMORY_LIMIT}"`) and at some point `resource.Quantity` started to validate these. cc @sttts @deads2k @ncdc
