### ISSUE TITLE
oc delete bc --cascade=false still deletes all builds

### ISSUE THREAD

**Issue by spadgett** [openshift/origin#14120]
Running the command

```
$ oc delete bc node-ex --cascade=false -n test-delete
```

deletes all my builds, even though I specified `--cascade=false`. Here is the API request sent by the CLI. It looks like it includes no delete options in the request body.

```
I0509 15:53:38.992308   45266 round_trippers.go:405] DELETE https://127.0.0.1:8443/oapi/v1/namespaces/test-delete/buildconfigs/node-ex 200 OK in 155 milliseconds
I0509 15:53:38.992334   45266 round_trippers.go:411] Response Headers:
I0509 15:53:38.992339   45266 round_trippers.go:414]     Date: Tue, 09 May 2017 19:53:38 GMT
I0509 15:53:38.992343   45266 round_trippers.go:414]     Cache-Control: no-store
I0509 15:53:38.992346   45266 round_trippers.go:414]     Content-Type: application/json
I0509 15:53:38.992349   45266 round_trippers.go:414]     Content-Length: 80
I0509 15:53:38.992395   45266 request.go:991] Response Body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Success","code":200}
```

cc @jwforres

**Comment by bparees** [comment]
builds are now automatically cleaned up by garbage collection when their buildconfig is deleted, so the cascade flag is effectively useless, other than for builds that were created before we introduced the garbage collection references.

@smarterclayton is this considered an api breaking change?  We discussed it in scrum this morning and the only workaround we could do is, if someone invokes --cascade=false we could remove the garbage collection reference from the builds prior to deleting the buildconfig, but that sounds pretty ugly.

**Comment by spadgett** [comment]
@bparees This is inconsistent with the behavior I see for Deployments and ReplicaSets. If you don't specify any delete options, the ReplicaSets are orphaned and the owner reference removed.

**Comment by jwforres** [comment]
thats not how GC is supposed to work as I understand it, you pass delete options, as the user you decide whether to orphan or not.  By default the CLI should pass delete options that will cascade the deletion.  Is the build controller doing something special here to clean up the builds?  It shouldn't be. The garbage collector should be doing this.  If the garbage collector is cascading when delete options are not passed then something is broken in kube, according to @liggitt the default behavior is to NOT cascade.

**Comment by bparees** [comment]
>  Is the build controller doing something special here to clean up the builds? It shouldn't be. 

no, we just have a reaper which hasn't changed in a long time.  (the reaper should be getting invoked when cascade=true and otherwise not invoked).  I'm reasonably confident that the thing removing these builds is the GC.

So the question seems to be whether GC itself is supposed to handle removing the ownerref in this scenario, or is that something our reaper is supposed to be doing.

**Comment by jwforres** [comment]
@deads2k something seems wrong here, is there something that the build endpoint needs to be doing to make sure GC behaves correctly, its garbage collecting even when the delete options are not passed to the DELETE call

**Comment by deads2k** [comment]
@bparees How are you establishing the ownerRef for your builds?  One common bug is to do it inside of a controller and then have that controller unconditionally create the link to an object which is being delete, thus orphaning itself and resulting in deletion of the child objects due to pointing to something that doesn't exist.

**Comment by deads2k** [comment]
Since the flow is 
 1. delete request becomes update request, updating parent/foo
 2. GC observes the delete of parent/foo
 3. GC issues patch for child/bar to remove the link
 4. controller observes child/bar update from 3 and doesn't check cache for the notification of 1.
 5. controller creates an dead ownerref
 6. GC observes an child/bar has a dangling ownerref and removes it.

**Comment by bparees** [comment]
@deads2k i'm 99% certain we only created the ownerRef at the time we create the build object.  @oatmealraisin did the feature so if we're doing it anywhere else, he should know.

**Comment by bparees** [comment]
@deads2k I assume step (2) above is "GC observes the *update* of parent/foo"?  (and there's a missing step 5.5 where the GC deletes parent/foo)

**Comment by bparees** [comment]
@deads2k @liggitt so this is the only place I see us setting an ownerReference on a build, and it's when we first create it:

https://github.com/openshift/origin/blob/master/pkg/build/generator/generator.go#L469
https://github.com/openshift/origin/blob/master/pkg/build/generator/generator.go#L824

I've also confirmed our reaper is not getting invoked when cascade=false (which is to be expected).

What do we need to do to chase down what's going wrong here?

**Comment by deads2k** [comment]
> What do we need to do to chase down what's going wrong here?

controller manager logs at level 5 I'd think.  Also, @liggitt do we use quorum reads in openshift?

**Comment by deads2k** [comment]
> What do we need to do to chase down what's going wrong here?

If you have a reproducer script (it's been a long while since I made a buildconfig or build), that would help me.

**Comment by liggitt** [comment]
> @liggitt do we use quorum reads in openshift?

I don't think so, but don't CI machines run with a single etcd?

**Comment by bparees** [comment]
> If you have a reproducer script (it's been a long while since I made a buildconfig or build), that would help me.

$ oc new-app -f https://raw.githubusercontent.com/openshift/origin/master/examples/sample-app/application-template-stibuild.json"

# give it a second to import imagestreams

# run a few times to start up some additional builds
$ oc start-build ruby-sample-build 

# confirm builds present, introspect as you like
$ oc get builds

$ oc delete bc ruby-sample-build --cascade=false

# see all builds are gone
$ oc get builds

**Comment by bparees** [comment]
and yeah i can reproduce it every time on a bare bones single master/all-in-one cluster, so it's not a quorum issue.

**Comment by deads2k** [comment]
Found it.  API machinery is about to start, so I'll fill in details later, but both the symptom and cause are concerning.  Oh, and its not your fault :)

**Comment by bparees** [comment]
> Oh, and its not your fault :)

that's all i needed to know :)

**Comment by kargakis** [comment]
--cascade=false is bypassing the cli reapers. @deads2k don't we need to update our rest strategies to set DefaultGarbageCollectionPolicy?

**Comment by deads2k** [comment]
> --cascade=false is bypassing the cli reapers. @deads2k don't we need to update our rest strategies to set DefaultGarbageCollectionPolicy, eg. like this one ?

Yep, that's the one.  To be consistent with upstream, we'd only add it to things which had controllers creating resources.  I'm less sure of what we actually want to do though?  Do we really want to have the default be "leave things around"?  Who was happy with that?

**Comment by deads2k** [comment]
So, some neat thoughts:

 1. For backwards compatibility, we would only have to orphan or have reapers for `/oapi`, not for `/apis`
 1. No one really wants orphaning to happen.  It's super-rare that someone says, "hey, I want to delete this thing and leave around the dangling children it produced so that I can later recreate the thing I deleted and have it fail in a really hard to figure out way".  Why don't we just let our default change?  (don't tell @liggitt, he'll freak out)
 1. It's really easy to add the function and carry the ugly into our new groupified APIs

**Comment by jwforres** [comment]
FWIW we have already changed the default behavior of the console. We always
send delete options with the foreground propagation policy (as soon as
https://github.com/openshift/origin-web-console/pull/1534 merges)

**Comment by deads2k** [comment]
> @deads2k agreed that orphaning is much more rare than cascading. Should we make changes in the upstream cli delete code to set the propagation policy explicitly on orphaning when --cascade=false?

as it happens: https://github.com/kubernetes/kubernetes/pull/45661
