### ISSUE TITLE
Autoscaling API group is reporting the wrong preferred version

### ISSUE THREAD

**Issue by jwforres** [openshift/origin#14165]
The autoscaling API group is showing v2alpha1 as the preferred version during API discovery when it should be v1

**Comment by DirectXMan12** [comment]
the issue is at https://github.com/openshift/origin/blob/master/vendor/k8s.io/kubernetes/pkg/registry/autoscaling/rest/storage_autoscaling.go#L42.  Looks like I inadvertently overrode the "preferred versions" behavior in the announcer by putting these two blocks in the wrong order.

I'll submit a patch upstream.

**Comment by liggitt** [comment]
@DirectXMan12 can you pick this to origin?

**Comment by DirectXMan12** [comment]
it was cherry-picked to origin in https://github.com/openshift/origin/pull/14255.  I missed this issue when I was putting the "Fixes" lines in.
