### ISSUE TITLE
USER in dockerfile is not used even when scc has runasuser: runasany

### ISSUE THREAD

**Issue by nilsotto** [openshift/origin#14164]
When a container has the `USER` instruction in the dockerfile, it will only be run as that user if the serviceaccount is listed in the anyuid scc, not any other sccs even though other scc have the `runasuser: RunAsAny` - setting (e.g `hostmount-anyuid`)

If I, however put the `securityContext: runAsUser: xxx`  in the pod-spec, the `runasuser: RunAsAny` in the different scc work as intended.

##### Version

    oc version
    oc v1.5.0+031cbe4
    kubernetes v1.5.2+43a9be4
    features: Basic-Auth GSSAPI Kerberos SPNEGO
    
    Server https://master.mydomain.no
    openshift v1.5.0
    kubernetes v1.5.2+43a9be4

##### Steps To Reproduce
1. `oc new-project uidtest`
2. `oc adm policy add-scc-to-user hostmount-anyuid -z default`
3. `oc run --restart=Never -it --image=nilsotto/uidtest uidtest1`
4. UID is in openshift-range <--- Should be 1001
5. `oc adm policy add-scc-to-user anyuid -z default`
6. `oc run --restart=Never -it --image=nilsotto/uidtest uidtest2`
7. UID is 1001 <--- OK!

##### Current Result
The `USER` from dockerfile is not taken into account even if the serviceaccount is in a scc that have `runasuser: RunAsAny`

##### Expected Result
`USER` from dockerfile being used.

**Comment by php-coder** [comment]
@nilsotto First of all, thank you for spending your time to report this!

This works as expected but it looks unexpected from the first sight.

Although you have grated access `hostmount-anyuid` SCC, it wasn't used at the step 4 and that's why pod was running with UID from a range. I bet that `restricted` SCC was used in this case and you can check this by `oc desctibe pod <pod> | grep Policy`.

Why it has happened? `anyuid` SCC is a special because it has a priority set. All other SCC don't have priority and when OpenShift chooses between `restricted` and `hostmount-anyuid` SCCs it takes `restricted` because it less privileged. At the same time, when it chooses between `restricted` and `anyuid` it takes the latter, because it has priority 10.

Here is a link to docs: https://docs.openshift.org/latest/architecture/additional_concepts/authorization.html#scc-prioritization

> If I, however put the securityContext: runAsUser: xxx in the pod-spec, the runasuser: RunAsAny in the different scc work as intended.

Yes, that's because you're explicitly requesting `runAsUser`, in this case, OpenShift chooses between SCCs which have `runasuser: RunAsAny` (and that's why `restricted` is filtered out from list of possible candidates).

Thanks again for the details report! If you have some ideas about improving our documentation, please, let us know. At this time I think that we can add your examples to the docs.

Also, please, close the issue if you feel that I've answered your question.

**Comment by nilsotto** [comment]
@php-coder - Thank you for a detailed and understandable answer.
When I see the documentation you refer to, it is quite clear how it works.
