### ISSUE TITLE
Owner references not added to "old" pods owned by a replica set

### ISSUE THREAD

**Issue by spadgett** [openshift/origin#14174]
Per @mfojtik @kargakis, owner references for "old" replica sets and pods should be added automatically after updating to 3.6 by the controller. I see this behavior for replica sets owned by a deployment. Pods, however, do **not** have an owner reference set.

**Comment by mfojtik** [comment]
The issue here is:

```
I0517 14:37:49.962124   19489 wrap.go:42] PATCH /api/v1/namespaces/test/pods/nginx-701339712-0hr5n: (7.16607ms) 403 [[openshift/v1.6.1+5115d708d7 (linux/amd64) kubernetes/5115d70 system:serviceaccount:openshift-infra:replicaset-controller] 192.168.64.3:33295]
E0517 14:37:49.962994   19489 replica_set.go:424] Sync "test/nginx-701339712" failed with User "system:serviceaccount:openshift-infra:replicaset-controller" cannot "patch" "pods" with name "nginx-701339712-0hr5n" in project "test"
```

So the controllerRefManager is working properly here, however the replicaset-controller service account does not have permissions to patch the pod.

This is easy fix, but I want to wait until @deads2k finish up the migration of RBAC and migrate the old rules to new system with this fixed up.

**Comment by spadgett** [comment]
I can verify with the RBAC changes this is no longer a problem.
