### ISSUE TITLE
Deprecate DeploymentCauses in favor of Conditions

### ISSUE THREAD

**Issue by kargakis** [openshift/origin#14202]
We should be able to use a Condition for communicating the cause of a rollout.

@mfojtik @tnozicka

**Comment by kargakis** [comment]
Needs a sign-off from @openshift/api-review

**Comment by deads2k** [comment]
I'm definitely in favor of conditions.  If I recall correctly, this field is write-only for us so the loss of machine readability (types).  You'll need to set both in v1.

Can you sketch out the particular condition type, reason, and message you'd use?  The upstream conditions don't cover this case since they aren't triggered like ours.

**Comment by kargakis** [comment]
```
ConditionType: RolloutCause
Status: {True, False}
Reason: {ImageChange, ConfigChange}
Message: Deployment config updated to version N by an {image,config} change
```
Or something along those lines. For DCs with latestVersion=0, status is False, True otherwise.

**Comment by deads2k** [comment]
> Or something along those lines. For DCs with latestVersion=0, status is False, True otherwise.

I like it.  You should keep the user specified message embedded within the message.  You'll add conditions congruent to upstream deployments where applicable I presume.

**Comment by deads2k** [comment]
Ah, we already match.  Awesome.

**Comment by mfojtik** [comment]
@kargakis like it, i guess we will need to migrate the conditions to causes in one release and then remove the causes in next one?
