### ISSUE TITLE
Inconsistent oc rollout command structure

### ISSUE THREAD

**Issue by siamaksade** [openshift/origin#14212]
`oc rollout` subcommands are not consistent in their argument structure. Some require only the name of the deploymentconfig, some type/deploymentconfig:

```
$ oc rollout latest myapp
$ oc rollout statue dc/myapp
```

The command should be consistent and all rollout commands either require type/name or just name. 
##### Version
oc v3.5.5.5
kubernetes v1.5.2+43a9be4
features: Basic-Auth

Server https://api.ded-stage-aws.openshift.com:443
openshift v3.5.5.10
kubernetes v1.5.2+43a9be4

**Comment by kargakis** [comment]
Isn't `oc rollout latest dc/foo` working?

**Comment by mfojtik** [comment]
`oc rollout latest` only works for deployment configs but `oc rollout status` works for both deployments and deployment configs.

**Comment by siamaksade** [comment]
Do `oc rollout undo` and `oc rollout history` work on deployments as well? Both required the type to be specified

**Comment by kargakis** [comment]
Only `oc rollout latest` is our addition in the `rollout` command because 1) we wanted to migrate away from `oc deploy` while using the same tools used by the upstream community and 2) upstream Deployments do not support being started as part of running a command (https://github.com/kubernetes/kubernetes/issues/25142) whereas we can do that with DeploymentConfigs. I am not sure if we can do anything here and I don't see upstream Deployments getting /instantiate (the endpoint called under the covers by `rollout latest`) any time soon.

**Comment by kargakis** [comment]
It's unlike we will make other `rollout` commands default to DC. Could be fixed if the kubectl supported configuring defaults in the resource builder but I don't see that happen anytime soon (or ever).
