### ISSUE TITLE
github.com/openshift/origin/test/end-to-end/core.test/end-to-end/core.sh:439: executing 'oadm diagnostics DiagnosticPod --images='openshift/origin-${component}:074537f'' expecting success and text 'Running diagnostic

### ISSUE THREAD

**Issue by bparees** [openshift/origin#14259]
```
=== BEGIN TEST CASE ===
test/end-to-end/core.sh:439: executing 'oadm diagnostics DiagnosticPod --images='openshift/origin-${component}:074537f'' expecting success and text 'Running diagnostic: PodCheckDns'
FAILURE after 32.951s: test/end-to-end/core.sh:439: executing 'oadm diagnostics DiagnosticPod --images='openshift/origin-${component}:074537f'' expecting success and text 'Running diagnostic: PodCheckDns': the output content test failed
Standard output from the command:
[Note] Determining if client configuration exists for client/cluster diagnostics
Info:  Successfully read a client config file at '/tmp/openshift/test-end-to-end/openshift.local.config/master/admin.kubeconfig'

[Note] Running diagnostic: DiagnosticPod
       Description: Create a pod to run diagnostics from the application standpoint
       
WARN:  [DCli2006 from diagnostic DiagnosticPod@openshift/origin/pkg/diagnostics/client/run_diagnostics_pod.go:135]
       Timed out preparing diagnostic pod logs for streaming, so this diagnostic cannot run.
       It is likely that the image 'openshift/origin-deployer:074537f' was not pulled and running yet.
       Last error: (*errors.StatusError[2]) container "pod-diagnostics" in pod "pod-diagnostic-test-4fwq1" is waiting to start: ContainerCreating
       
[Note] Summary of diagnostics execution (version v3.6.0-alpha.1+074537f-686):
[Note] Warnings seen: 1

There was no error output from the command.
=== END TEST CASE ===
```
https://ci.openshift.redhat.com/jenkins/job/merge_pull_request_origin/708

**Comment by sosiouxme** [comment]
It seems like this was just a case of the pod taking too long to start up. We can extend the time limit but there will always be a possibility of that flaking in a test.

**Comment by brenton** [comment]
@sosiouxme, what should we do here?  just increase the limit for now?

**Comment by sosiouxme** [comment]
@brenton That's all I can think of ATM.

**Comment by brenton** [comment]
@sosiouxme, would you be able to make the change?

**Comment by sosiouxme** [comment]
Sure. Taking a little closer look, it is retrying 25 times with a 100ms delay between, so maybe 3 to 4 seconds for the diagnostic container to be running and logs attached. I suppose over hundreds of CI builds it wouldn't be surprising to see that time out occasionally due to random environmental factors. I would be curious what thresholds are used in other tests that wait for a pod to start (with the expectation the image is already there). Given it hasn't been a constant problem I think I'll just double the retries. I'm not sure at what point we consider it a flake versus an actual problem being detected (shouldn't take that long to start a pod). The other option if it continues to be a problem is to just take this out of the e2e test. Or, make the timeout configurable just so this test can set it (though I don't like that either).
