### ISSUE TITLE
Using new-app without cloning locally

### ISSUE THREAD

**Issue by aliscott** [openshift/origin#14294]
I'm using `oc new-app --strategy=docker <git url>`. Is there any way to get this to run without it cloning the git repo locally? I'm assuming this would also mean it wouldn't create an ImageStream from the `FROM` line in the Dockerfile.

This would be a useful option if I don't want the ImageStream created anyway and I have a large repository/a slow connection.

##### Version
```
$ oc version
oc v1.5.0+031cbe4
kubernetes v1.5.2+43a9be4
features: Basic-Auth

openshift v1.5.0
kubernetes v1.5.2+43a9be4
```

**Comment by php-coder** [comment]
CC @bparees

**Comment by bparees** [comment]
Unfortunately not, new-app has to clone your repo to detect the source type/run checks on your repo content to validate your strategy choices, etc.

If you just want to create a build w/ minimal introspection you can run "oc new-build --binary [other args]", but you'll still have to create the deploymentconfig+services yourself after the build is created, and you'll need to update the buildconfig to put your source repository in since you aren't actually going to use it as a binary build.

You could also just modify one of the quickstart templates to suit your needs and deploy that, instead of using new-app.  New-app is really targeted around use cases where you want the system to "figure out" how to build your content and deploy it.
