### ISSUE TITLE
TestProjectLifecycle integration test flaking

### ISSUE THREAD

**Issue by csrwng** [openshift/origin#14368]
From log:

```
Running TestProjectIsNamespace...
ok      TestProjectIsNamespace
Running TestProjectLifecycle...
failed  TestProjectLifecycle
=== RUN   TestProjectLifecycle
masterAddr: "127.0.0.1:12000"
Running TestProjectRequestError...
ok      TestProjectRequestError
```

https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin_integration/2595/

**Comment by csrwng** [comment]
@stevekuznetsov I didn't see any logs from the failing integration test in the console output. Is that going somewhere else now?

**Comment by stevekuznetsov** [comment]
Should be in the console, but also goes to [`scripts/test-integration/logs/raw_test_output.log`](https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin_integration/2595/s3/download/scripts/test-integration/logs/raw_test_output.log) in the S3 artifacts. All of the output should be in the jUnit report, though, as well.

We don't see anything more in the raw output:

```
=== RUN   TestProjectIsNamespace
masterAddr: "127.0.0.1:12000"
--- PASS: TestProjectIsNamespace (6.44s)
PASS

=== RUN   TestProjectLifecycle
masterAddr: "127.0.0.1:12000"

=== RUN   TestProjectRequestError
masterAddr: "127.0.0.1:12000"
--- PASS: TestProjectRequestError (12.59s)
PASS
```

Looks like the test just never had exit output? It is being flagged as failed since we never saw the `--- PASS` output from it. Weird. @jhadvig have you seen this?

**Comment by csrwng** [comment]
@stevekuznetsov I've seen other integration tests fail without any output, but when I run the test locally I do see the output. Looks like we're suppressing it somewhere.

**Comment by stevekuznetsov** [comment]
This is output from `go test` which should never be missing. Might be a bug in the recent changes to how we deal with that output from @jhadvig

**Comment by bparees** [comment]
opened https://github.com/openshift/origin/issues/14376 to deal w/ the lack of log output.  @stevekuznetsov feel free to reassign to @jhadvig if that is appropriate.

**Comment by kargakis** [comment]
https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin_integration/4906/testReport/junit/github/com_openshift_origin_test_integration /TestProjectLifecycle/
