### ISSUE TITLE
Service Broker Template Deprovision not terminating pod

### ISSUE THREAD

**Issue by jmccormick2001** [openshift/origin#14426]
when I run the service broker template example, it will provision the pod and service,  the
application works as expected,  but
when I deprovision, the pod is left in a terminating status.  This seems to be reproducible with
my postgres template example.

##### Version
oc v3.6.0-alpha.1+b2dfb64-939-dirty
kubernetes v1.6.1+5115d708d7

##### Steps To Reproduce
1. run origin/pkg/template/servicebroker/test-scripts
2. run the deprovision script to cause the error

##### Current Result

The pod that is provisioned will not terminate.

##### Expected Result

I would expect the pod to terminate like normal, usually this takes about 2 seconds
for the pod to gracefully terminate.

##### Additional Information

When this occurs, the logs of openshift throw this error in a tight loop:

```
I0531 11:29:43.051875    1242 reconciler.go:201] UnmountVolume operation started for volume "kubernetes.io/empty-dir/8cc7f05a-456a-11e7-836c-00163e5c5e06-backup.deleting~446122578.deleting~113769046.deleting~132604831.deleting~210592645.deleting~463119712" (spec.Name: "backup.deleting~446122578.deleting~113769046.deleting~132604831.deleting~210592645.deleting~463119712") from pod "8cc7f05a-456a-11e7-836c-00163e5c5e06" (UID: "8cc7f05a-456a-11e7-836c-00163e5c5e06").
```

**Comment by jim-minter** [comment]
Hi @jmccormick2001 Thanks for your issue report.  Unfortunately I wasn't able to reproduce it and things have moved on a lot since May.  There is generally more testing around this area now and more should be added with https://trello.com/c/eGPZllFr.  Is this something you are still seeing, in which case please could you update the issue, or can this be closed?
