### ISSUE TITLE
Make flex volume plugin dir configurable

### ISSUE THREAD

**Issue by php-coder** [openshift/origin#14490]
When I'm trying to use flex volumes in the OpenShift, I have to put a plugin into the `/usr/libexec/kubernetes/kubelet-plugins/volume/exec` directory. This location is surprising me, because I'd expect a directory like `/var/lib/origin` or similar.

Also I found that `controller-manager` has [option for that](https://github.com/openshift/origin/blob/0fc5f594043d15050b8db010d2766a6e82e71d04/vendor/k8s.io/kubernetes/cmd/kube-controller-manager/app/options/options.go#L168):
```sh
$ openshift start kubernetes controller-manager -h | grep flex
	  --flex-volume-plugin-dir='/usr/libexec/kubernetes/kubelet-plugins/volume/exec/': Full path of the directory in which the flex volume plugin should search for additional third party volume plugins.
```

Question: why we haven't change the defaults from Kubernetes? Is it intentionally? Should we change it/adapt for OpenShift?

Feature request: make this path configurable.

**Comment by fabianvf** [comment]
As far as I can tell this prevents the use of FlexVolumes on CoreOS/atomic systems. I've been having a lot of trouble configuring a flex volume plugin on Fedora Atomic because of this issue.

**Comment by gnufied** [comment]
For better or worse - on mutable hosts the ship has already sailed on flexvolume plugin path for Openshift. Users can still change it via controller-manager/kubelet parameter if they must. Changing the path now on mutable hosts will require creating a migration path for users and since flexvolume is mostly in maintenance mode, we are hesitant to do that.

however on Atomic an RHCOS - going forward the path has been changed to be in `/etc/origin/kubelet-plugins` , which is more consistent with Openshift - https://github.com/openshift/openshift-ansible/pull/8773/files

If you are using flexvolume on atomic/rhcos - flexvolume should be usable on 3.9/3.10 OCP versions now. 

/close
