### ISSUE TITLE
Investigate if and why automatic rollback doesn't work (+integration test)

### ISSUE THREAD

**Issue by kargakis** [openshift/origin#14561]
Forked from https://github.com/openshift/origin/issues/13995#issuecomment-307458999

@smarterclayton @mfojtik @tnozicka 

Manifests + Events: 
http://file.rdu.redhat.com/%7Ejupierce/share/free-int-data.txt
Logs: 
http://file.rdu.redhat.com/~jupierce/share/free-int-logs.tgz

**Comment by mfojtik** [comment]
@kargakis @tnozicka I can't reproduce this by deleting the pod. I think this was related to DC config controller creating 2 RC in quick succession (the GC bug) and it was never rolled back because the previous version RC did not exists?

I don't think there is a bug here now as we fix the GC everything should be working normally.

**Comment by kargakis** [comment]
We miss a test for automatic rollback

On Monday, June 19, 2017, Michal Fojtik <notifications@github.com> wrote:
> @kargakis @tnozicka I can't reproduce this by deleting the pod. I think
this was related to DC config controller creating 2 RC in quick succession
(the GC bug) and it was never rolled back because the previous version RC
did not exists?
>
> I don't think there is a bug here now as we fix the GC everything should
be working normally.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.<
https://ci5.googleusercontent.com/proxy/Qd6IrRyV0N0YfrNXvEF5PT0KMCZnBufO7B1965mpX2AY0iMdCflj74bVEY7W-KY1eclEK3X0l2dPvGGOgCDO1SoyAFzd6cYJkLe04sjGGRLoG7gj15W23D3cstAJ1xQaQtffd-UzVy76sv1bI7DGKwaJnhCddQ=s0-d-e1-ft#https://github.com/notifications/beacon/ADuFf_eGR6Mk0PPTsW4J9kzEQMZdGXAeks5sFmC3gaJpZM4N18jH.gif>

**Comment by tnozicka** [comment]
@mfojtik seems like it was probably that. We should add extended test for automatic rollback though

**Comment by kargakis** [comment]
Most flakes come from extended tests, it should be enough to have an integration test for this.

**Comment by tnozicka** [comment]
@kargakis It seems pretty critical functionality so I would be inclined to have it e2e tested. I might be wrong though.

Yes most flakes comes from extended test and most of those from those badly/quickly written. (modulo infra failures) I wouldn't condemn extended test just because those flaky ones.

**Comment by kargakis** [comment]
Tests that don't need docker and it's just the API that is tested should be integration tests.
