### ISSUE TITLE
Dind image seems broken

### ISSUE THREAD

**Issue by kargakis** [openshift/origin#14573]
https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin_extended_networking_minimal/3042/consoleFull#-14181563465898c58db7602c31c0eab717
```
[INFO] Starting 'networking' extended tests
[INFO] [CLEANUP] Cleaning up temporary directories
[INFO] Building docker-in-docker images
Building container images
/data/bin/imagebuilder
--> Image fedora:25 was not found, pulling ...
--> Pulled 0/2 layers, 4% complete
--> Pulled 1/2 layers, 50% complete
no such image
[ERROR] PID 6395: hack/common.sh:750: `imagebuilder -t 'openshift/dind' '/data/src/github.com/openshift/origin/images/dind/'` exited with status 1.
```
@openshift/networking

**Comment by smarterclayton** [comment]
It's not fully blocking queue, some are still merging

**Comment by bparees** [comment]
saw it here too
https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin_extended_networking_minimal/3055/

**Comment by kargakis** [comment]
Removing P0 since it's not blocking but adding P1 since it happens fairly often since yesterday.

**Comment by danwinship** [comment]
It looks like it's failing while pulling the fedora:25 image, which shouldn't happen. Maybe some transient docker hub problem. Let's see if it goes away by itself...

**Comment by danwinship** [comment]
no, looks like this is new since #14522. @stevekuznetsov

**Comment by stevekuznetsov** [comment]
@smarterclayton any clue why `imagebuilder` would fail to pull `fedora:25`?

**Comment by stevekuznetsov** [comment]
Haven't seen this since we `systemctl restart docker` in https://github.com/openshift/aos-cd-jobs/pull/330 ... so it's definitely a memory hog from the daemon issue. /cc @runcom we restart the daemon after instances of `docker cp` and `docker build` now since it's holding on to too much memory, and we see no adverse effects. Especially with `docker cp` once the client call is done the memory stays in use for a while. Unclear what the daemon is doing with it.
