### ISSUE TITLE
oc new-project 

### ISSUE THREAD

**Issue by zjj2wry** [openshift/origin#14584]
```
admindeMacBook-Pro:openshift-origin-client-tools-v3.6.0-alpha.2-3c221d5-mac admin$ ./oc new-project zhengjiajin
Now using project "zhengjiajin" on server "https://127.0.0.1:8443".

You can add applications to this project with the 'new-app' command. For example, try:

    oc new-app  #centos/ruby-22-centos7~https://github.com/openshift/ruby-ex.git

to build a new example application in Ruby.
```
i use **oc** create my project, but i can not find it from my ui. but when i create **zhengjiajin** project. ui occurred error```This name is already in use. Please choose a different name.```

##### Version
```
admindeMacBook-Pro:openshift-origin-client-tools-v3.6.0-alpha.2-3c221d5-mac admin$ ./oc version
oc v3.6.0-alpha.2+3c221d5
kubernetes v1.6.1+5115d708d7
features: Basic-Auth

Server https://127.0.0.1:8443
openshift v3.6.0-alpha.2+3c221d5
kubernetes v1.6.1+5115d708d7
```
##### Steps To Reproduce
1. oc new-project zhengjiajin
2. create the project from ui

##### Current Result
i can not find project from i create project in terminal.

**Comment by scheng1** [comment]
你在 ui 用 admin 用户看看

**Comment by scheng1** [comment]
oadm policy add-cluster-role-to-user cluster-admin admin

**Comment by zjj2wry** [comment]
@scheng1 我用的system-admin 登录的，我在 ui 上面创建的在终端可以看到

**Comment by scheng1** [comment]
你在UI 上用 system:admin 登录的？

**Comment by zjj2wry** [comment]
是的啊

**Comment by pweil-** [comment]
@zjj2wry are you logged in as the same user in the cli and the web console?  Since you're getting a `This name is already in use. Please choose a different name` when trying to create from the console it would appear that the cluster has the project but you don't have permissions to see it when logged in to the console.

`oc whoami` will tell you who you're logged in as in the cli.

**Comment by zjj2wry** [comment]
```
admindeMacBook-Pro:openshift-origin-client-tools-v3.6.0-alpha.2-3c221d5-mac admin$ oc whoami
system:admin
admindeMacBook-Pro:openshift-origin-client-tools-v3.6.0-alpha.2-3c221d5-mac admin$ oc projects
You have access to the following projects and can switch between them with 'oc project <projectname>':

    default
    hello
    kube-public
    kube-system
    list
    myproject - My Project
    openshift
    openshift-infra
  * test
    zhengjiajin

Using project "test" on server "https://127.0.0.1:8443".
```
this is my terminal, i relogin my ui-dashboard can not find **zhengjiajin** project. has some command to see project permission or owner?

**Comment by jwforres** [comment]
system:admin on the CLI is not a regular user, please see this recent thread on the mailing list: https://lists.openshift.redhat.com/openshift-archives/users/2017-June/msg00037.html

**Comment by pweil-** [comment]
@zjj2wry it looks like you are creating the project as system:admin rather than the user you're logging in to the web console with.  The easiest way to correct this to remove the existing project and either 

1.  log in with your regular user in the cli with `oc login` and then create the project -or-
2.  create the project directly from from the web console as your regular user

Alternatively you could [grant access to the project](https://docs.openshift.org/latest/architecture/core_concepts/projects_and_users.html) to the existing user by using the project's default roles.

**Comment by zjj2wry** [comment]
@jwendell @pweil- think you ：）

**Comment by scheng1** [comment]
好好看看文档吧。你这问题有点小儿科了。先看看os 是怎么认证用户的。
