### ISSUE TITLE
Different cluster registries using one storage

### ISSUE THREAD

**Issue by tpolekhin** [openshift/origin#14610]
Hello,

I use internal docker registry on my DEV cluster backed by S3 bucket.
I build and push images to this registry using Jenkins installed on DEV cluster.
I installed internal registry on my PROD cluster and configured it to use the same S3 bucket.
I cannot pull images on PROD cluster with MANIFEST_UNKNOWN error.

##### Version
oc v1.5.0
kubernetes v1.5.2+43a9be4
features: Basic-Auth GSSAPI Kerberos SPNEGO
openshift v1.5.0
kubernetes v1.5.2+43a9be4

##### Steps To Reproduce
1. Install registry on cluster1 configured with S3 storage
2. Build and push image to internal registry
3. Install registry to cluster2 configured with same S3 storage bucket
4. Try to pull image that you pushed in step 2

##### Current Result
Image is not pulled with MANIFEST_UNKNOWN error

##### Expected Result
Image can be pulled

**Comment by woshidagouxiong** [comment]
manifest is stored in cluster etcd

**Comment by tpolekhin** [comment]
@woshidagouxiong i see a `_manifests` folder in my S3 bucket

**Comment by miminar** [comment]
@tpolekhin that won't work. You'd have to export corresponding image objects from the first cluster to other one first. Etcd is the source of truth for our registry, not the storage.

In future versions, this setup may not work at all due to a planned pruning changes - blobs not known to registry's cluster will be pruned.

I'd advise to use a dedicated S3 bucket for each cluster.
