### ISSUE TITLE
Template without objects has null in objects field instead of empty array 

### ISSUE THREAD

**Issue by zakiva** [openshift/origin#14730]
According to https://github.com/openshift/origin/blob/master/pkg/template/api/v1/types.go#L31, the `objects` field does not have `omitempty`. However, when creating a template without objects, the template is created successfully and the objects field is set to null. Assuming it makes sense to create a template with no objects at all (does it?), shouldn't we expect the objects field to be an empty array?  

Reproducing:

1. Create a template without objects, e.g.

```
apiVersion: v1
kind: Template
metadata:
  name: test-template
```
2. oc get template test-template -o yaml

Result:
```
apiVersion: v1
kind: Template
metadata:
  creationTimestamp: 2017-06-18T14:30:41Z
  name: test-template
  namespace: pro-1
  resourceVersion: "879724"
  selfLink: /oapi/v1/namespaces/pro-1/templates/test-template
  uid: b48e501a-5432-11e7-a0b5-001a4a2314d5
objects: null
```

**Comment by bparees** [comment]
>  Assuming it makes sense to create a template with no objects at all (does it?)

it doesn't, since provisioning that template will have absolutely no effect.

as for whether it should really be represented as an empty array vs a null value, they are not the same thing... since you defined a template with, implicitly, a null value, that's what you get back.  If you want an actual empty array value, then you'd have to define a template w/ an empty array value.

omitempty would mean you would not even see "objects" in the result.

**Comment by zakiva** [comment]
> Assuming it makes sense to create a template with no objects at all (does it?)
> it doesn't, since provisioning that template will have absolutely no effect.

So shouldn't it be forced before creation? (as done for other resources, e.g. pod without containers)

**Comment by bparees** [comment]
> So shouldn't it be forced before creation? (as done for other resources, e.g. pod without containers)

it's not invalid to create it, it just won't do anything when provisioned.  I don't know that there's a use case for it, but it won't break anything so i don't think it should be a validation requirement.
