### ISSUE TITLE
webhook trigger conditions

### ISSUE THREAD

**Issue by andrewklau** [openshift/origin#14791]
Services like bitbucket don't let you use send webhooks based on a change branch, meaning if developers are pushing to the "non-release" branch that openshift builds from a new build is triggered regardless.

Is there a way to prevent this?

##### Version
oc v1.5.0+031cbe4
kubernetes v1.5.2+43a9be4
features: Basic-Auth GSSAPI Kerberos SPNEGO

**Comment by bparees** [comment]
It sounds like you're probably using the generic trigger because we didn't explicitly support bitbucket triggers in 3.5.

with 3.6 we are introducing a bitbucket trigger.  Our bitbucket webhook gets the ref branch for the change out of the event and will not trigger a build if the event ref branch does not match the buildconfig ref branch value.  (So while you might get an event based on a change to a branch, your buildconfig should not fire if it references master).

adding @gabemontero who implemented this in case there are additional nuances.

code in question:
https://github.com/openshift/origin/blob/master/pkg/build/webhook/bitbucket/bitbucket.go#L100

**Comment by andrewklau** [comment]
Thanks, that looks like it would solve the issue. Looking forward to 3.6

Is there any estimated timeline for 3.6?

**Comment by bparees** [comment]
we've got an alpha origin release out now that would include the new webhook:
https://github.com/openshift/origin/releases/tag/v3.6.0-alpha.2

For the final release, we're in final codefreeze, so relatively maybe a month or so.

Closing this issue since the feature in 3.6 should address the requirement.
