### ISSUE TITLE
arm64: failed to run Kubelet: cAdvisor is unsupported in this build

### ISSUE THREAD

**Issue by KurtStam** [openshift/origin#14870]
I successfully compiled openshift for linux/arm64. It gave me the oc, openshift and kubefed binaries. 
As per step 9 from https://github.com/openshift/origin/blob/master/CONTRIBUTING.adoc
when running sudo ./openshift start it starts up ok until it dies with

F0623 19:47:43.613104     996 node.go:297] failed to run Kubelet: cAdvisor is unsupported in this build
##### Version
openshift version
openshift v0.1+d61e8be-18962-dirty
kubernetes v1.6.1+5115d708d7
etcd 3.2.0

##### Steps To Reproduce
sudo ./openshift start

##### Current Result
failed to run Kubelet: cAdvisor is unsupported in this build

##### Expected Result
a running openshift

Why is this not supported on ARM64? Is there anything I can set at compile time?

Thx,

--Kurt

**Comment by KurtStam** [comment]
Hi @derekwaynecarr, please let me know if there is anything I can do to help, or help to provide a patch. This has been working on plain vanilla Kubernetes for a while now and I'd love to have it working on Openshift too. My distro is aarch64 centos7 (with docker). It should just be 'linux' right?

**Comment by KurtStam** [comment]
It'd be great to get a comment on this as I'd like to help out getting this fixed!

**Comment by dcbw** [comment]
I'm just doing a drive-by on this, not an expert by any means.  but it's failing because cadvisor_linux.go has this:

`// +build cgo,linux`

which means that the linux bits only build when using cgo.  Why?  I have no idea.  But as a test, change that go `// +build linux` and then change cadvisor_unsupported.go to be `// +build !linux,!windows` (eg, remove the linux,!cgo).

Then see if that fixes anything.  It  may well just create more problems, but at least you'll figure out why it thinks it wants to be built with cgo.
