### ISSUE TITLE
Allow service account to get terminating projects

### ISSUE THREAD

**Issue by arepx** [openshift/origin#14905]
We have a CI/CD pipeline that deploys a docker image to OpenShift, the pipeline access OpenShift using a service account

If the project name already exists the project is deleted and recreated, here is a snippet from the job script

```
${ocCmd} delete project ${namespace}
while ${ocCmd} get projects -o name | grep -F "project/${namespace}"; test \${PIPESTATUS[1]} -eq 0; do sleep 1 && echo "Waiting for namespace to be deleted"; done;
${ocCmd} new-project ${namespace}
```
The issue we are having is with the `oc get projects -o name`, the behavior is different for an admin account and the CI/CD service account.

For an admin account the deleted project name will continue to be returned until the project is actually removed.

For the pipeline service account the project name ceases to be returned immediately after the delete command is issued. The `oc new-project` command then fails because the project name still exists when it is called.

What we are looking for is the correct policy update command to modify the service account so that it behaves the same way as the admin account when calling `oc get projects -o name` and returns projects in the terminating state.

##### Version

```
oc v1.5.1+7b451fc
kubernetes v1.5.2+43a9be4
features: Basic-Auth

Server https://lb.distline-dev.genesaas.io:8443
openshift v1.4.1
kubernetes v1.4.0+776c994
```

##### Steps To Reproduce
1. [step 1]
Create an OpenShift project `<PROJECT_NAME>`

2. [step 2]

Create a shell and login to oc as an admin account

Run the following command:

`while ${ocCmd} get projects -o name | grep -F "project/<PROJECT_NAME>"; test \${PIPESTATUS[1]} -eq 0; do sleep 1 && echo "Waiting for namespace to be deleted"; done;`

3. [step 3]

Create a shell and login to oc as a service account

Run the following command:

`while ${ocCmd} get projects -o name | grep -F "project/<PROJECT_NAME>"; test \${PIPESTATUS[1]} -eq 0; do sleep 1 && echo "Waiting for namespace to be deleted"; done;`

4. [step 4]

Call `oc delete delete project <PROJECT_NAME>`

##### Current Result

The command running at step 3 will exit the loop immediately after step 4 

The command running at step 2 will not exit until the project has been removed

##### Desired  Result

The commands running at step 2 and step 3 will both not exit until the project has been removed.

**Comment by enj** [comment]
@openshift/security this probably does not have an easy solution since namespace termination is complicated, but it may be interesting for someone to look at.

@arepx try changing your project list command to instead use a get (so `oc get project <projectname> -o name` instead of `oc get projects -o name`).  Listing projects is probably the most complicated list command in openshift, and involves many layers of caches.  Getting a project on the other hand is the same as other gets, though those still involve some caching.  In your example, I assume `admin` is the cluster admin.  I am also curious how your SA is assigned permissions.  That being said, since you are clearly using the project as a temporary resource, why not create a new project with a random name?

**Comment by enj** [comment]
Closing due to age.  Please reopen if you are still facing this issue.
