### ISSUE TITLE
oc cluster up: use registry and router deployment commands from the image being deployed

### ISSUE THREAD

**Issue by csrwng** [openshift/origin#14913]
Recent changes to the router deployment config make the released oc binary (v3.6.0-alpha.2) incompatible with the latest router image. The deployment config used by the older oc binary for the router causes the router to fail health checks and eventually die. Going forward we can prevent this by invoking the `oc adm router` and `oc adm registry` commands on the origin container itself instead of using the in-process command from the `oc` client running `cluster up`.

**Comment by jwmatthews** [comment]
@csrwng thank you for the help in debugging this

**Comment by smarterclayton** [comment]
This is correct.  We should probably also use the templates vendored in the
image as well.

On Jul 6, 2017, at 10:18 PM, OpenShift Bot <notifications@github.com> wrote:

Closed #14913 <https://github.com/openshift/origin/issues/14913> via #15087
<https://github.com/openshift/origin/pull/15087>.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/origin/issues/14913#event-1153786543>, or mute
the thread
