### ISSUE TITLE
Could not perform yum update

### ISSUE THREAD

**Issue by coreydaley** [openshift/origin#14944]
https://ci.openshift.redhat.com/jenkins/job/test_branch_origin_extended_builds/112/display/redirect

```
Could not perform a yum update.
Errors from dependency resolution:
  2:docker-1.12.6-39.1.git6ffd653.el7.x86_64 requires atomic-registries
  2:docker-1.12.6-39.1.git6ffd653.el7.x86_64 requires container-storage-setup >= 0.3.0-1
You should resolve these issues before proceeding with an install.
You may need to remove or downgrade packages or enable/disable yum repositories.
```

**Comment by coreydaley** [comment]
Also occurred here: https://ci.openshift.redhat.com/jenkins/job/test_branch_origin_extended_templates/3/

**Comment by bparees** [comment]
i think @stevekuznetsov was looking into this this morning.

**Comment by stevekuznetsov** [comment]
@lsm5 @runcom need confirmation from where we are supposed to be installing `atomic-registries` from .. but otherwise we have merged https://github.com/openshift/aos-cd-jobs/pull/369 which allows us to sync `skopeo` and `container-storage-setup` packages to our repos... need confirmation from @rhatdan that we need or do not need to migrate the use of `docker-storage-setup` to `container-storage-setup` from this change ... 

We are waiting on [this job](https://atomic-e2e-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/aos-cd/job/package-dockertested/973/) to promote the packages into our repo, at which point this will be unblocked but may break on the `docker-storage-setup` issues. This also affects downstream consumers like [`ami_build_origin_int_rhel_base`](https://ci.openshift.redhat.com/jenkins/job/ami_build_origin_int_rhel_base/) which will remain broken until the repo progression occurs.

This is all tracked under https://trello.com/c/LddAGiyk/241-2-ci-ci-fire-fighting-repeats

**Comment by stevekuznetsov** [comment]
Update -- job linked above had a defect, job updating our repo with the correct packages will be [this one](https://atomic-e2e-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/aos-cd/job/package-dockertested/975/)

**Comment by stevekuznetsov** [comment]
Looks like the `oso-rhui-rhel-server-releases` repositories are broken for `devicemapper`:

```
--> Running transaction check
---> Package device-mapper-event.x86_64 7:1.02.107-5.el7_2.5 will be updated
--> Processing Dependency: device-mapper-event-libs = 7:1.02.135-1.el7_3.5 for package: 7:device-mapper-event-1.02.135-1.el7_3.5.x86_64
---> Package device-mapper-libs.x86_64 7:1.02.107-5.el7_2.5 will be updated
---> Package device-mapper-libs.i686 7:1.02.135-1.el7_3.4 will be installed
```

So the jobs can't even get far enough to install `docker` and push it up to our tested repos... so this is blocked on that.

**Comment by stevekuznetsov** [comment]
We have a new AMI from [`ami_build_origin_int_rhel_base` #148](https://ci.openshift.redhat.com/jenkins/job/ami_build_origin_int_rhel_base/148/console) so this is fixed.
