### ISSUE TITLE
'oc describe bc <name>' command doesnot return bitbucket webhook url

### ISSUE THREAD

**Issue by xqianwang** [openshift/origin#15095]
I confugured webhook trigger in my pipeline buildConfig. The buildConfig is deployed successfully and it works fine when I manually click start pipeline button. But I want to use bitbucket webhook to trigger the pipeline build with jenkins deployed in my openshift. When I followed the doc, I wanted to use oc describe bc <name> to get the webhook url, url is not in returned description. How Can I get the webhook url? Additional question:  my jenkins container is running in vm in Vnet on Azure, if I can get the webhook url, how can I expose the url to external services.
##### Version
oc v1.5.0
kubernetes v1.5.2+43a9be4
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://xqopenshiftmaster.canadaeast.cloudapp.azure.com:8443
openshift v1.5.0
kubernetes v1.5.2+43a9be4
##### Steps To Reproduce
1. deploy buildconfig for jenkins pipeline
2. oc describe bc xxxx

##### Current Result
Name:           xxxx-pipeline
Namespace:      poc
Created:        2 days ago
Labels:         app=xxxx-pipeline
                name=xxxx-pipeline
Annotations:    pipeline.alpha.openshift.io/uses=[{"name": "xxxx-build", "namespace": "poc", "kind": "DeploymentConfig"}]
Latest Version: 39

Strategy:               JenkinsPipeline
URL:                    git@bitbucket.org:xxxxxx/xxxx.git
Ref:                     branch-name
Source Secret:          bitbucket
Jenkinsfile path:       Jenkinsfile

Build Run Policy:       Serial
Triggered by:           <none>

Build                   Status          Duration                Creation Time
xxxx-pipeline-39   running         running for 18m7s       2017-07-07 17:09:55 +0000 UTC
xxxx-pipeline-38   failed          39m36s                  2017-07-07 16:34:57 +0000 UTC
##### Expected Result
web url in description

**Comment by php-coder** [comment]
@bparees

**Comment by bparees** [comment]
> When I followed the doc, I wanted to use oc describe bc to get the webhook url, url is not in returned description. How Can I get the webhook url? 

the bitbucket webhook is being introduced in v3.6, you'll need to update to a v3.6 client+server to be able to set and view the bitbucket trigger.  It's available in our alpha release: https://github.com/openshift/origin/releases/tag/v3.6.0-alpha.2

(note that versioning changed in 3.6, so 3.6 is the next version after 1.5).

> Additional question: my jenkins container is running in vm in Vnet on Azure, if I can get the webhook url, how can I expose the url to external services.

the url will be served via cluster api server and match its hostname, so it is implicitly exposed to anything that can reach your cluster.  If your cluster itself is not public, then in order to expose it you'd have to do some proxying, such as run a pod in your cluster that exposes a public route for the webhook, and relays the external webhook call(which would use the public route) to the actual webhook url(on the cluster api server).
