### ISSUE TITLE
Registry openshift client is still using json, should use protobuf

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#15126]
The client should be switched to prefer protobuf and fallback to JSON.  Noticed in prometheus output.

@mfojtik for 3.7

**Comment by mfojtik** [comment]
@smarterclayton @deads2k i started working on this to discover that we can't use the generated clients for things like image signatures, image stream mappings, local subject reviews and others as we don't generate clients for them (since they only implement a subset of client methods and some of them are not ObjectMeta...).

I wonder if we want to enhance the clientgen to support more comment arguments (like a list of methods to generate) or we want to fix our types (i don't think that is reasonable) or craft a manual client for those. 

I can switch "some" clients to external version and generated client but 70% of resources the registry access does not have generated client.

**Comment by mfojtik** [comment]
@smarterclayton you said on IRC that registry use the protobuf, now i'm **confused** ;-)

Now, this PR should switch the legacy client in registry to generated external clientset: https://github.com/openshift/origin/pull/15624 for most resources (I guess ImageSecrets were the only left).

**Comment by mfojtik** [comment]
This is done.
