### ISSUE TITLE
when I rolling back the deployconfig yaml didn‘t have  automatic:true .

### ISSUE THREAD

**Issue by myonlyzzy** [openshift/origin#15133]
when I rolling back to my dc histoy . I lose rolling update auto .I open bc yaml  I find automatic:true disapper. this is a buy or I use a increct way?

**Comment by pweil-** [comment]
I assume here you mean the image change triggers are disabled.  That is by design to prevent accidentally starting a  new deployment after the rollback is complete.  You can reenable them post rollback once you are ready to resume auto deploying: `$ oc set triggers dc/<name> --auto`

https://docs.openshift.org/latest/dev_guide/deployments/basic_deployment_operations.html#rolling-back-a-deployment
