### ISSUE TITLE
Better error messages on osc

### ISSUE THREAD

**Issue by fabianofranz** [openshift/origin#1516]
As a follow-up of https://github.com/openshift/origin/pull/992 we need a reliable mechanism to customize the error messages that end up being printed in `osc`. Will probably require a `printer` of messages upstream, that is used for example by the commands under `kubectl` that we reuse. 

We need to replace for example, for first-time users, things like `No server found for` with `You need to log in, use 'osc login', etc`.

**Comment by fabianofranz** [comment]
@smarterclayton @deads2k fyi

**Comment by smarterclayton** [comment]
The factory should have an interface for these sorts of things (utility messages, generic error handling).

**Comment by sosiouxme** [comment]
+1000

Any chance we can intercept k8s glogs and give something user-friendly?

**Comment by smarterclayton** [comment]
There are no more glog fatals upstream.  There would only be glog errors, which should be omitting the ugly prefix when verbosity is at lower levels.  That issue is still open.

**Comment by brenton** [comment]
I'm guessing this is related.  It would be nice if login failures didn't default to dumping the error message.  Here's an example of what happens when you type the wrong password and are using the `RequestHeaderIdentityProvider`:

~~~
[demo@dev origin]$ osc login 192.168.133.100:443
Username: demo
Authentication required for https://192.168.133.100:443 (openshift)
Password: 
Login failed (401 Unauthorized)
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>401 Unauthorized</title>
</head><body>
<h1>Unauthorized</h1>
<p>This server could not verify that you
are authorized to access the document
requested.  Either you supplied the wrong
credentials (e.g., bad password), or your
browser doesn't understand how to supply
the credentials required.</p>
</body></html>
~~~

Here's another issue that shows what happens when token expires: https://github.com/openshift/origin/issues/2132.  It definitely seems weird to print "Unauthorized" twiece whenever tokens expire.
