### ISSUE TITLE
How should terminating quota be applied?

### ISSUE THREAD

**Issue by bparees** [openshift/origin#15173]
Currently terminating quota is applied to pods w/ an activedeadline set.

This issue is to discuss whether it should also apply to pods with no activedeadline, but which have a restart policy of "never" (or possibly also a restart policy of "if failed"?)

@smarterclayton

**Comment by bparees** [comment]
Related to this discussion, should builds always have an active deadline set?  Should we also enable an active deadline default/override to be set via the build defaulter/overrider?  There are a lot of ways to skin this cat.

**Comment by smarterclayton** [comment]
If we set an ootb default, would that suddenly break existing clusters
that have this?  It's technically an API change which argues for no
new default, but I could buy Ansible deploying new clusters like this.

**Comment by bparees** [comment]
if we set the ootb default high enough (ie 1 year), it would probably break no one, while bringing the builds under the terminating quota.  I guess it could break someone in the sense of changing how quota is evaluated.  that's probably the bigger concern (and maybe the point you were making).

it's still probably something we should allow the defaulter/overrider to set, since today cluster admins don't have a way to force build pods under the terminating quota (unless they can use the admission controller that online uses?  do we ship that?).

or of course we could change how pods are qualified for terminating quota, to include any pod that a "restart never" policy, regardless of deadline.  But that would also potentially break existing clusters for the same reason as always setting a deadline.

**Comment by smarterclayton** [comment]
LimitRanger might be more appropriate, but yes, build override defaulters
is appropriate. I think though this is a max scenario, not an override
scenario.  So not clear what the best approach is

On Jul 12, 2017, at 9:52 PM, Ben Parees <notifications@github.com> wrote:

if we set the ootb default high enough (ie 1 year), it would probably break
no one, while bringing the builds under the terminating quota. I guess it
could break someone in the sense of changing how quota is evaluated. that's
probably the bigger concern (and maybe the point you were making).

it's still probably something we should allow the defaulter/overrider to
set, since today cluster admins don't have a way to force build pods under
the terminating quota (unless they can use the admission controller that
online uses? do we ship that?).

or of course we could change how pods are qualified for terminating quota,
to include any pod that a "restart never" policy, regardless of deadline.
But that would also potentially break existing clusters for the same reason
as always setting a deadline.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/origin/issues/15173#issuecomment-314947022>,
or mute the thread

**Comment by derekwaynecarr** [comment]
@bparees - this came up in the original discussion for the feature.  the original proposal was just based on restart policy, but we got feedback that that is insufficient.  the terminating quota is intended to align with a pod being time-bound.  for example, nginx running in a restart=on-failure pod could run forever, so it is insufficient.  in retrospect, we could have called the scope TimeBound and TimeUnbounded, but that was the basic idea.

**Comment by bparees** [comment]
ok, if we're officially rejecting putting non-restart pods under the terminating quota, then i think the remaining question is whether anything else should be done for build pods to ensure they always fall under the terminating quota.  In online we run an admission controller that always sets an activedeadline on them(on any runoncepod), perhaps that is sufficient for other cluster admins as well.

**Comment by bparees** [comment]
/close
(based on my last comment i guess we're happy w/ the tools we have for this)
