### ISSUE TITLE
sourceStrategy in build doesn't match to buildconfig

### ISSUE THREAD

**Issue by dmage** [openshift/origin#15233]
Builds use images from docker.io while buildconfigs specify ImageStreamTag. As a result, the builder pushes base images to the registry, but actually able to use cross-mount.

##### Version
v3.6.0-alpha.2-840-g18c573053b

##### Steps To Reproduce
1. Create an application from the catalog. For example, github.com/openshift/cakephp-ex.git.
2. Build it.

##### Current Result
```
$ oc get buildconfig/test -o json | jq .spec.strategy
{
  "sourceStrategy": {
    "from": {
      "kind": "ImageStreamTag",
      "name": "php:7.0",
      "namespace": "openshift"
    }
  },
  "type": "Source"
}
```
```
$ oc get build/test-1 -o json | jq .spec.strategy
{
  "sourceStrategy": {
    "from": {
      "kind": "DockerImage",
      "name": "centos/php-70-centos7@sha256:dfb7fea3a8aa8d0dcb6589696a6125b88050236213bab019cd0f7b86f98d33bb"
    }
  },
  "type": "Source"
}
```

##### Expected Result
build/test-1 has openshift/php:7.0 in sourceStrategy

**Comment by php-coder** [comment]
@openshift/devex

**Comment by smarterclayton** [comment]
Our ootb image streams would have to use the resolution policy, which makes sense in public cloud object store backed implementations, but not in all on prem file backed situations

**Comment by bparees** [comment]
@smarterclayton so we should consider tweaking the imagestreams in online only?

**Comment by bparees** [comment]
(not seeing how this is a p1, dropping to p2 at best)

**Comment by miminar** [comment]
The cross-mount happens for layers during a second push of the base image. First time, the layers of the base image aren't known to the docker deamon, but the deamon makes an associtation `DiffID -> TargetRepository`. Next time, the same daemon pushes an image based on the same upstream image, it attempts the cross-mount based on the remembered associations.

Nevertheless, the cross-mount will probably fail anyway because subsequent build may be done by a totally different user / service account.

**Comment by smarterclayton** [comment]
The pusher should have access to the cross mount.

@bparees in theory, anyone with a storage tier that supports content
redirect (Swift, GCS, AWS S3, Azure, a few others) should be using the
resolutionPolicy on the openshift image streams.  Anyone who doesn't do
content redirect (registry on Gluster, NFS) shouldn't, because that would
send download traffic *through* the registry.

**Comment by bparees** [comment]
@smarterclayton well the question seems to be "which behavior has more negative implications" if you use the wrong one for your env.

because we have a bunch of consumers:

1) oc cluster up/minishift/cdk (no content redirect)
2) online (content redirect)
3) on-prem OCP installs w/ unknown registry config

So unless we want the ansible install to customize the imagestreams, we're going to have to pick one or the other, at least for (3), even if we customize for 1+2.

**Comment by bparees** [comment]
@dmage i don't actually understand this issue anymore.

is the suggestion that when pulling the base image, builds should (ideally) do a pullthrough against the repository (which would require the imagestreams be defined using the local reference policy) so that when they push the application image, the base image layers are already cross-mountable?

**Comment by bparees** [comment]
(there's no bug here, the buildconfig is defined in terms of an imagestream reference, the build controller resolves that imagestream reference to an image reference as part of creating the build.  If the imagestream is being resolved to the "wrong" image reference, that's a symptom of how the imagestream is defined(not using local reference policy), not a bug in the build controller).

**Comment by dmage** [comment]
The builder should pull a base image from the internal registry to be able to crossmount its layers into another repository.

It's a problem how the image stream in the `openshift` namespace are defined. Not a registry problem.

**Comment by bparees** [comment]
> The builder should pull a base image from the internal registry to be able to crossmount its layers into another repository.

right, so it's not really up to the builder, it depends on the imagestream definition.  I think we're on the same page.

> It's a problem how image streams in the openshift namespace are defined. Not a registry problem.

@dmage yeah, i put the imageregistry label on it for lack of a better one.  "image" might have been more appropriate. sorry for any confusion.

**Comment by bparees** [comment]
trello'd https://trello.com/c/HHQn17y0

**Comment by bparees** [comment]
@dmage just to confirm, if we pullthrough a base image in the "openshift" namespace, a user who later pushes an image built on top of that base image, to their own namespace, will be able to cross-mount the base layers from the openshift namespace?

I'm surprised we can/do that level of access checking.

**Comment by dmage** [comment]
@bparees if the client gets an image from a registry, it will try to reuse its blobs in another repository on the registry. That is, the client will send the request for cross-mounting blobs and we may allow it. If Docker doesn't ask for cross-mount, we will not do it.

**Comment by bparees** [comment]
> we may allow it

this is the part i'm asking about though.  If the blob exists in an image in the "openshift" namespace, will we actually recognize the user has access to it?  What is the logic that is implemented when checking if a user has access to a particular blob?  Do we find all the imagestreams in the entire cluster that reference that blob, and see if the user has access to any of them?  Or do we only check imagestreams in the user's current project?

**Comment by dmage** [comment]
Docker, when it wants to mount a blob from another repository, sends an HTTP request like

> POST /v2/**myproject/foo**/blobs/uploads/?mount=**sha256:123abc...789def**&from=**openshift/nodejs**

The registry will just check that the client has read access to the repository *openshift/nodejs* and that the repository contains the blob.

No other imagestream is checked.

**Comment by bparees** [comment]
Ok, so this all depends on the docker client being aware that cross-mount might be possible.  Any idea how the client decides which repository to try to cross-mount from?

**Comment by dmage** [comment]
Docker remembers all places where it saw the blob. If it saw the blob in several repositories on the registry, it will try all of them, one by one.
