### ISSUE TITLE
cluster up: metrics and logging require an ansible image tagged the same as the corresponding openshift release

### ISSUE THREAD

**Issue by csrwng** [openshift/origin#15243]
Until very recently `--metrics` and `--logging` have been broken with cluster up because we don't have an `openshift/origin-ansible:[tag]` image that corresponds to the origin release tag.

We need to decide whether we want to tag openshift-ansible images according to origin release or if that tag is independent of origin, then we need to either have a default or an additional argument to cluster up to allow you to specify it.

**Comment by csrwng** [comment]
/cc @jcantrill 
@smarterclayton need your guidance on this one. Currently we don't have a good correlation between openshift-ansible branches/releases and origin releases. Should we?

**Comment by jcantrill** [comment]
I am of the opinion we should allow you to specify a specific ansible image.

**Comment by smarterclayton** [comment]
Great, more flags.  Not happy about customization going down another level.

**Comment by jorgemoralespou** [comment]
@csrwng @jcantrill @smarterclayton why not smartly use tags on images and avoid an extra parameter?

We can use multiple tags for the ansible images, one that identifies versioning of the ansible-container and one that identifies the release of origin that has been tested/certified. These tags can progress independently, allowing the ansible container to evolve and then to properly tag align to an origin release so that things work and there is no additional flag.

e.g:
````
Create ansible container:  openshift/origin-ansible:xyx
Evolve ansible container: openshift/origin-ansible:xyZ
Release origin:    tag openshift/origin-ansible:xyZ openshift/origin-ansible:v3.6.0-rc.0
Evolve ansible container: openshift/origin-ansible:xYT
# Found an issue with the ansible-container for 3.6.0-rc.0 that last evolution fixes: tag openshift/origin-ansible:xYT openshift/origin-ansible:v3.6.0-rc.0
````

I know this is a little burden on the release management side, but should make things easier for users.

**Comment by csrwng** [comment]
@sosiouxme ^^ is this possible? I was kind of neutral about this, but thinking more about it, if we allow you to specify the openshift-ansible tag, we're putting the burden on the end user to know which one will work with the version of origin they're trying to run. How do they know which one works with which version? If in the future we introduce changes to the ansible playbooks that are not backwards compatible with older versions, how do we make sure that you use the right one?

Is it possible today to cut a release/branch of openshift-ansible that is tested with a particular version of origin? /cc @sdodson

**Comment by sosiouxme** [comment]
ose-ansible versions are aligned with OCP versions; the tags and builds are created in a coordinated process.

origin-ansible versions are currently just building out of master in a daily Jenkins job. It's easy enough to run the job to build from a branch and/or tag the result with more/different tags. But there's nothing automatically creating an increasing tag every day, or aligning with Origin release tags. That would probably be a job for the CD team, and I'm sure it's somewhere down their list.

For now, if the goal is to have a tag for origin-ansible that matches one in origin, it would probably be best to git tag openshift-ansible (as we do for e.g. the logging and metrics repos - we still do that right?) and run the Jenkins job as a one-off against that tag.

There isn't currently any job to re-tag an existing origin-ansible image BTW. Someone with privs could do that manually.

Not sure I've addressed the question. But just to weigh in, even if we had perfectly aligned tags, I can imagine scenarios where QE or dev or CEE would want to specify a different version for o-a than origin.

**Comment by csrwng** [comment]
> I can imagine scenarios where QE or dev or CEE would want to specify a different version for o-a than origin.

For our internal use, we can always tag whatever we want to use manually so we can match whatever cluster up expects. I don't think it'd be a good idea to add complexity to the command just for dev.

**Comment by smarterclayton** [comment]
Yeah, we can easily tag a latest that is good enough.

On Jul 19, 2017, at 3:51 PM, Cesar Wong <notifications@github.com> wrote:

I can imagine scenarios where QE or dev or CEE would want to specify a
different version for o-a than origin.

For our internal use, we can always tag whatever we want to use manually so
we can match whatever cluster up expects. I don't think it'd be a good idea
to add complexity to the command just for dev.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/origin/issues/15243#issuecomment-316495566>,
or mute the thread
