### ISSUE TITLE
osc default help shows all options

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#1529]
Regression?  Missed upstream commit?

**Comment by smarterclayton** [comment]
@pweil- did you have a bad upstream commit on cobra by any chance?

**Comment by smarterclayton** [comment]
We should add a negative test to hack/test-cmd on showing options.

**Comment by fabianofranz** [comment]
Looking

**Comment by pweil-** [comment]
It would not surprise me although I had @fabianofranz's commit picked.

**Comment by pweil-** [comment]
I think this is a regression.  We're on the same version of spf13/cobra as upstream, which was bumped 8 days ago https://github.com/GoogleCloudPlatform/kubernetes/commit/a18ec3be8809e2f4082bf0baf539d6d35c43bbd5#diff-681659ab9abb4b4883e78e8aaa980dba.  If I revert command.go to the last rebase which has the older spf13/cobra version then it works fine.

@fabianofranz  One change that has me suspicious is the new lflags: https://github.com/openshift/origin/blob/master/Godeps/_workspace/src/github.com/spf13/cobra/command.go#L50

**Comment by fabianofranz** [comment]
The issue was introduced in https://github.com/spf13/cobra/commit/b96dd75141f233adeb39cbe63c41c962585a1c7a and https://github.com/spf13/cobra/commit/5c9146990baf14f44c4c470befa56c7ee5b62130 by the removal of `AllPersistentFlags` that we use in our templates (we fork the help templates, see [here](https://github.com/openshift/origin/blob/master/pkg/cmd/templates/templates.go)). `lflags` may also have to do with it. I'll fix and write a test so we detect it if happens again.

**Comment by fabianofranz** [comment]
Fixed in https://github.com/openshift/origin/pull/1533.

**Comment by fabianofranz** [comment]
@smarterclayton BTW should we just take the `osc` help template and make it default in every command, *including* the top-level `openshift`? I don't recall any reason not to, and it would favor consistency.

**Comment by pweil-** [comment]
:relieved:

**Comment by smarterclayton** [comment]
Yes
