### ISSUE TITLE
webhook support

### ISSUE THREAD

**Issue by charliejllewellyn** [openshift/origin#15455]
It's common to want to trigger pipelines for any new branches or on pull requests etc. This is possible with Jenkins but doesn't seem so with OpenShift. We would like to see the same flexibility the github SCM plugin provides for Jenkins.

##### Version
openshift v3.5.5.24
kubernetes v1.5.2+43a9be4

##### Steps To Reproduce
Create a new branch on a repo with a webhook enabled for OpenShift. 

##### Current Result
The pipeline is not triggered because you have to supply the branch name you wish to build in the build config which means you cannot dynamically test new branches. 

##### Expected Result
The pipeline should trigger and should pass the new branch name to Jenkins to be built.

##### Additional Information
It should also be possible to specify the type of trigger e.g. pull_request_review etc

**Comment by bparees** [comment]
You can trigger an openshift build (including pipeline builds) using the SCM webhooks we support which includes push/merge, but not opening a PR, etc:
https://docs.openshift.org/latest/dev_guide/builds/triggering_builds.html#webhook-triggers

Our philosophy is if you want that level of sophisticated triggering, then you should go ahead and use jenkins (or another CI tool) that already has strong SCM triggering integration, rather than having openshift re-invent webhook support for every SCM+triggertype that users would be interested in.  You can have your jenkins job (triggered by an SCM mechanism) launch the openshift build, passing whatever ref/branch you would like to build.  You can use the built in openshift jenkins image to run this job.

**Comment by ccpatrut** [comment]
This is weird.
You should be able to trigger builds on specific branches not only the one you statically type into the ref field
