### ISSUE TITLE
lost deploy/registry/generator in 3.6

### ISSUE THREAD

**Issue by deads2k** [openshift/origin#15495]
Found cleaning up from the 3.7 rebase.  I lost generateDeploymentConfigs (no verbs) and I think that it was actually lost in 3.6.

https://github.com/openshift/origin/blob/release-3.6/pkg/deploy/registry/generator/rest.go#L25

https://github.com/openshift/origin/blob/release-3.6/vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/registry/rest/rest.go#L91

@smarterclayton These were supposed to go away.  Shall we simply let them go?

**Comment by smarterclayton** [comment]
@mfojtik @kargakis did we have a deprecation notice on them?

**Comment by deads2k** [comment]
@mfojtik confirmed.  This was removed in 3.6 `{"name":"generatedeploymentconfigs","namespaced":true,"kind":"DeploymentConfig","verbs":[]}`.

**Comment by mfojtik** [comment]
@kargakis ^ do you remember when/where we nuked this?

**Comment by kargakis** [comment]
Hrm, I don't remember removing it...

**Comment by deads2k** [comment]
> Hrm, I don't remember removing it...

It fell out from an interface mismatch.  See where I restored it in https://github.com/openshift/origin/pull/15496 . I've added assertions to avoid similar slips, but if we announced deprecation before, I'd be happy to remove the dead code.

**Comment by smarterclayton** [comment]
Given there is ambiguouity about how we removed it, let's restore in 3.6
and announce deprecation now.

**Comment by kargakis** [comment]
Yeah, we never really announced deprecation ...

**Comment by mfojtik** [comment]
@smarterclayton @deads2k what is the proper way to announce deprecation in this case?

**Comment by smarterclayton** [comment]
Docs, public announcement, release notes, and the deprecation doc.

On Aug 1, 2017, at 7:41 AM, Michal Fojtik <notifications@github.com> wrote:

@smarterclayton <https://github.com/smarterclayton> @deads2k
<https://github.com/deads2k> what is the proper way to announce deprecation
in this case?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/origin/issues/15495#issuecomment-319346678>,
or mute the thread

**Comment by mfojtik** [comment]
opened https://github.com/openshift/origin/pull/15585 for actual 3.7 removal, will follow with docs/etc.
