### ISSUE TITLE
Automatically configure Jenkins Proxy

### ISSUE THREAD

**Issue by hahnn** [openshift/origin#15521]
Hi,

**This is a feature request.**

When OpenShift is installed in an environment that needs a PROXY for any network operations, that would be nice to automatically configure the Jenkins Proxy also when a Jenkins Pod is created in a project.

Regards.

**Comment by bparees** [comment]
Cluster administrators are free to provide their own jenkins image (likely built on top of the openshift jenkins image) w/ any configuration that is specific to their cluster environment.  

And the pod has no access to cluster configuration, so at best the only way this could be done is for the jenkins image to respect a particular env variable that would tell it to configure itself to use a proxy.

**Comment by bparees** [comment]
I don't envision a way for us to address this feature request in a way that's both:

1) going to satisfy a significant set of users  (what to do for users consuming plugins that don't respect the proxy config?  or just running shell commands in their job?  or for proxies that require additional config such as username/password?)  (see: https://wiki.jenkins.io/display/JENKINS/JenkinsBehindProxy)

2) provides a meaningful improvement in experience over users just supplying their own jenkins configuration w/ proxy details (especially since we can't know the openshift cluster proxy configuration details)

/cc @gabemontero

**Comment by gabemontero** [comment]
+1 

this has come up through a few other avenues as well

in addition to the concerns @bparees noted, even with the plugins that honor proxy, there are some short comings wrt honoring env vars and allowing for support of multiple settings; I in fact have a PR submitted to the git plugin; the maintainer is still waiting for other users to try it and confirm it works for them before he'll merge it;
