### ISSUE TITLE
Builds can go into hot loop with this failure:

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#1555]
```
E0401 15:15:15.697768   17736 factory.go:30] Build failed with error default/ruby-sample-build-1: &errors.errorString{s:"the referenced output image repository default/origin-ruby-sample does not exist"}
E0401 15:15:15.700315   17736 factory.go:30] Build failed with error default/ruby-sample-build-1: &errors.errorString{s:"the referenced output image repository default/origin-ruby-sample does not exist"}
E0401 15:15:15.701209   17736 factory.go:30] Build failed with error default/ruby-sample-build-1: &errors.errorString{s:"the referenced output image repository default/origin-ruby-sample does not exist"}
E0401 15:15:15.701950   17736 factory.go:30] Build failed with error default/ruby-sample-build-1: &errors.errorString{s:"the referenced output image repository default/origin-ruby-sample does not exist"}
E0401 15:15:15.702675   17736 factory.go:30] Build failed with error default/ruby-sample-build-1: &errors.errorString{s:"the referenced output image repository default/origin-ruby-sample does not exist"}
```

**Comment by smarterclayton** [comment]
```
apiVersion: v1beta1
creationTimestamp: null
items:
- apiVersion: v1beta1
  kind: Build
  metadata:
    creationTimestamp: 2015-03-31T23:11:35Z
    labels:
      buildconfig: ruby-sample-build
      name: ruby-sample-build
      template: application-template-custombuild
    name: ruby-sample-build-1
    namespace: default
    resourceVersion: "161"
    selfLink: /osapi/v1beta1/builds/ruby-sample-build-1?namespace=default
    uid: 472b440a-d7fb-11e4-bd0f-7831c1b76042
  parameters:
    output:
      to:
        kind: ImageRepository
        name: origin-ruby-sample
    source:
      git:
        uri: git://github.com/openshift/ruby-hello-world.git
      type: Git
    strategy:
      customStrategy:
        env:
        - name: OPENSHIFT_CUSTOM_BUILD_BASE_IMAGE
          value: openshift/origin-custom-docker-builder:latest
        exposeDockerSocket: true
        image: openshift/origin-custom-docker-builder:latest
      type: Custom
  status: New
- apiVersion: v1beta1
  kind: Build
  metadata:
    creationTimestamp: 2015-03-31T23:26:06Z
    labels:
      buildconfig: ruby-sample-build
      name: ruby-sample-build
      template: application-template-dockerbuild
    name: ruby-sample-build-2
    namespace: default
    resourceVersion: "734"
    selfLink: /osapi/v1beta1/builds/ruby-sample-build-2?namespace=default
    uid: 4df0c781-d7fd-11e4-bd0f-7831c1b76042
  parameters:
    output:
      to:
        kind: ImageRepository
        name: origin-ruby-sample
    source:
      git:
        uri: git://github.com/openshift/ruby-hello-world.git
      type: Git
    strategy:
      dockerStrategy: {}
      type: Docker
  startTimestamp: 2015-03-31T23:26:13Z
  status: Running
kind: List
resourceVersion: 8302
```

The image repository was deleted.

**Comment by smarterclayton** [comment]
Even after deleting the builds, the hot loop continues.

**Comment by smarterclayton** [comment]
By hot loop I mean it looks like the controller is continually trying this, never making any progress.  It highlights that the controller is not making progress either (it looks like this is going to the head of the queue and tried again immediately).

**Comment by bparees** [comment]
so the only broken part about this in my mind is that after deleting the buildconfig, the loop does not break.

the part where it spins because the repo doesn't exist is intentional, if you create the repo you'll resolve it and it'll make progress...  we don't consider it a fatal error for the repo to temporarily not exist.

**Comment by smarterclayton** [comment]
This was not a build config.  This was a build.

The hot loop is horrible if it never ends.  This was continuously hot looping for over an error, and no other builds could get scheduled.  That is a "bug".

----- Original Message -----

**Comment by bparees** [comment]
not denying there is a bug here, just trying to clarify the expected portion of the behavior.

it should not block other builds because this is using the requeue logic, so other events should be processed before the requeued event. 

the hot loop ends when you update your configuration to be valid by either modifying the build definition or creating the missing imagerepository.

I agree that deleting the build should also terminate the loop.

**Comment by smarterclayton** [comment]
It's also trying too fast - tens of times a second.

**Comment by bparees** [comment]
yes, that was a fundamental limitation of the retry queuing logic that @ironcladlou and I came up with, we noted it at the time that handling "backoff" is significantly more complicated due to the race conditions introduced.  All the controllers that use retry have this behavior..the only difference is that the deployment controller chose to only retry a few times, whereas for builds I elected to retry indefinitely for conditions that might be resolved at some point.

**Comment by bparees** [comment]
one way to limit the retry spinning would be for the controller to track state and when it sees the same event twice in a row, it delays itself before processing that event.  but that will also delay anything else in the queue.  (presumably nothing, which is why we got the same event twice)

**Comment by danmcp** [comment]
Closing due to age without prejudice.

**Comment by bparees** [comment]
also it was fixed :)
