### ISSUE TITLE
Can I delete application directly ?

### ISSUE THREAD

**Issue by ibuler** [openshift/origin#15556]
We use `oc new-app` to create a set of `dc`,`bc`,`is`,`service`,`router` ,

So If there any method delete this app also delete related resource like `oc delete app` or `oc delete-app`

**Comment by php-coder** [comment]
I don't know about such a command, so you have to use `oc delete` for each resource that have been created. If you're sure that in the current project no other resources except those that were created by `oc new-app` then you can use `oc delete all --all`.

CC @openshift/devex

**Comment by jim-minter** [comment]
`oc new-app` labels everything that it creates, by default with `app=<generated name>`. You can use `-l` to customise the label(s) added to create resources.  To delete, do `oc delete all -l app=<generated name>` (or whatever labels you set).

**Comment by ibuler** [comment]
Thanks

**Comment by abdennour** [comment]
If you keep in mind `kubectl` how it works, you will understand the solution of @jim-minter

**Comment by holly-cummins** [comment]
If you're using a template for the app creation (ie `oc new-app --template='openshift/redis-persistent'`) @jim-minter 's solution may need to be extended, because the behaviour of `all` is a bit counter-intuitive. The [OpenShift Cookbook](https://cookbook.openshift.org/working-with-resource-objects/how-do-i-delete-all-resource-objects-for-an-application.html) says 

> Note that all matches on a subset of all resource object types that exist. It targets the core resource objects that would be created for a build and deployment. It will not include resource objects such as persistent volume claims (pvc), config maps (configmap), secrets (secret), and others.

and recommends 

`oc delete all,configmap,pvc,serviceaccount,rolebinding --selector app=jupyterhub`

What resources have to get added to the list will depend on the exact contents app template. The good news is in the template case, the template will add a handy label to all the resources it creates (assuming you only have one per namespace). You'll need to find one of the resources with `--selector app=whatever` to work out the right template label. Once you have it, you can do something like:

```oc delete all,secrets,services,persistentvolumeclaims,deploymentconfigs.apps.openshift.io,configmap,serviceaccount,rolebinding --selector template=redis-persistent-template```
