### ISSUE TITLE
`oc cluster up --public-hostname=127.0.0.1` connections accepted from non-localhost

### ISSUE THREAD

**Issue by pvalena** [openshift/origin#15565]
Similarly to https://github.com/openshift/origin/issues/10628, when running local cluster with specified public hostname, the connections from other networks to cluster are still accepted.

##### Version
oc v3.6.0-alpha.2+3c221d5
kubernetes v1.6.1+5115d708d7
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://remote:8443
openshift v3.6.0-alpha.2+3c221d5
kubernetes v1.6.1+5115d708d7

##### Steps To Reproduce
1. On cluster 'host' (`remote`)
`oc cluster up --public-hostname=127.0.0.1`

2. On client
`oc login remote:8443 -u developer`

##### Current Result
Access to cluster granted.

##### Expected Result
Connection refused or not available.

##### Additional Information
The issue was resolved for OSX, in the above [mentioned issue]( https://github.com/openshift/origin/issues/10628), but not for Linux.

**Comment by csrwng** [comment]
@pvalena this is the default behavior in Linux because we're not running on a VM as in the other platforms. Origin will listen on all ports by default. You can easily restrict access to the origin endpoint via firewalld rules, however. 

It is definitely not consistent with the behavior on Windows and Mac, so I'll create a Trello card to track it as a feature request.

https://trello.com/c/XLEybmfF/1267-cluster-up-listen-only-on-specified-numeric-hostname-when-specified-through-public-hostname

**Comment by pvalena** [comment]
Thanks!

I'm a bit worried about this from the security POV. It seems quite non-intuitive. But like you said, the firewalld can solve this.
