### ISSUE TITLE
github.com/openshift/origin/test/integration .TestOadmPodNetwork fails

### ISSUE THREAD

**Issue by deads2k** [openshift/origin#15658]
I've seen this in several jobs: 

https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin_integration/5502/
https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin_integration/5538

**Comment by deads2k** [comment]
seven out of the top 10 failed integration tests are failing on this: https://deck-ci.svc.ci.openshift.org/?job=test_pull_request_origin_integration&state=failure.  Making it a p1

@danwinship @dcbw @knobunc I'm not sure who owns it, but it appear network-y.

**Comment by danwinship** [comment]
In #15336 (at the bottom), @liggitt said that this was actually caused by #15648, which was fixed by #15654  yesterday morning. It looks like this failure has still occurred since that merged, although I can't figure out how to tell the exact master commit a given test run merged against.

----

Assuming the problem isn't fixed, it's because the Namespace SharedInformer doesn't seem to be informing about any Namespaces. In a successful run there are logs like:

    I0809 10:02:17.079663   31523 vnids_master.go:290] Watch ADDED event for Namespace "one"
    I0809 10:02:17.080492   31523 vnids_master.go:122] Allocated netid 13639912 for namespace "one"

but those are missing in the logs of the failed test runs

**Comment by liggitt** [comment]
fixed by https://github.com/openshift/origin/pull/15700?

**Comment by danwinship** [comment]
> fixed by #15700?

yup, apparently
