### ISSUE TITLE
Cannot create https-only route

### ISSUE THREAD

**Issue by jpechane** [openshift/origin#1567]
There is no way how to configure route to not expose http protocol if TLS is configured.

**Comment by brenton** [comment]
Hmm... setting up an example in my environment and looking through `/var/lib/haproxy/conf/haproxy.config` in my router container I see that `/var/lib/haproxy/conf/os_http_be.map` will be populated whenever edge tls is set in the route.

It seems like one option would be to set 'reencrypt' or 'passthrough' but I'm not sure if that's what you want.  That would require your pod actually listening on TLS.

@pweil- , do we have a story for creating a route that would terminate at the edge but avoid the port 80 haproxy frontend?

**Comment by brenton** [comment]
Gently bumping this...

**Comment by pweil-** [comment]
Sorry, didn't see this.  Your findings are the correct cause of this: right now edge and unsecure use the same backend map since they were both unsecure http connections.  Once the connection is decrypted we're looking at the same place.  This is a pretty simple change, we need to separate them into separate files in the haproxy template.  We can still reuse the same backend.

Specifically though: no I don't have a story for it.

**Comment by pweil-** [comment]
@brenton I have this working locally.  I ran into probe failure issue on https://github.com/openshift/origin/pull/1603 and got side tracked but I should be able to open a PR for it once we come to a conclusion about the probe.

**Comment by brenton** [comment]
That's awesome Paul.  Thanks for the update.
