### ISSUE TITLE
Deploy origin in mutiple nodes

### ISSUE THREAD

**Issue by wangzhezhe** [openshift/origin#1574]
I have tested the openshift/origin in container way and binary way as the guidance in https://docs.docker.com/installation/ubuntulinux/#create-a-docker-group
It seems the overall architecture of origin is similar with the kubernetes except some extra components in master node . It's also based flannel to meet the net requirements of kubernetes in aii-in-one container way.  So, how could I deployment the origin in a kubernetes cluster which hove multiple machines to have a test ? Thank you!

**Comment by derekwaynecarr** [comment]
Instructions for kicking the tires and running OpenShift as a pod on Kubernetes can be found here:

https://github.com/GoogleCloudPlatform/kubernetes/blob/master/examples/openshift-origin/README.md

There was a latency issue cache issue post project creation that can delay seeing results when doing:

$ osc get projects

That we hope to fix soon, so after you create a project just switch to it directly (or wait 2 minutes for a list/watch to resync).

Otherwise, things should work fine.  Let me know if you have problems and/or issues and I will look to address.

**Comment by smarterclayton** [comment]
Closing due to age, reopen if there is additional discussion needed here
