### ISSUE TITLE
Is there any solution for multiple datacenter?

### ISSUE THREAD

**Issue by ibuler** [openshift/origin#15758]
Hello,

I want to know is there any solution for multiple datacenter. Because auth, policy ..etc should share to every cluster.

**Comment by pweil-** [comment]
@ibuler can you clarify what you're asking here?  If your data centers are connected then having HA masters that are across regions with shared etcd is possible and scheduling can be controlled via labels on nodes for mulitple regions.

But I'm wondering if you're talking more about federation of multiple clusters as a single cluster with distribution of resources automatically between them which is something that is still under heavy discussion upstream.

**Comment by ibuler** [comment]
I'm sorry, I want to known that I have some datacenter on different region, and have some public cloud on different provider, such as  AliCloud, AWS, Azure. Maybe a master couldn't satisfy it.
Because they connect each other through internet.  

Yes, I't a problem for every software

**Comment by pweil-** [comment]
@ibuler thanks for clarifying.  Federation of multiple clusters is in heavy discussion upstream.  The best bet here is to follow that conversation directly since it is changing rapidly.

The community repo for federation is (including sig meeting times): https://github.com/kubernetes/community/tree/master/sig-federation 

The initial federation proposal is here: https://github.com/kubernetes/community/blob/master/contributors/design-proposals/federation.md
