### ISSUE TITLE
openshift-ansible integration test failures; Failed to get D-Bus connection: Operation not permitted

### ISSUE THREAD

**Issue by sosiouxme** [openshift/origin#15769]
openshift-ansible merge/test includes integration tests to exercise the pre-install checks. These are failing quite often but not 100% of the time.

##### Examples

[1](https://ci.openshift.redhat.com/jenkins/job/merge_pull_request_openshift_ansible/846/consoleFull#-75303961958b6e51eb7608a5981914356) [2](https://ci.openshift.redhat.com/jenkins/job/test_pull_request_openshift_ansible/445/consoleFull#2162290456bf4006e4b05b79524e5923) [3](https://ci.openshift.redhat.com/jenkins/job/test_pull_request_openshift_ansible/446/consoleFull#5034335056bf4006e4b05b79524e5923)

##### Current Result
All tests fail with similar problem:

```
--- FAIL: TestPackageUpdateDepMissing (114.93s)
	common.go:54: missing in output: ["check \"package_update\":" "Could not perform a yum update." "break-yum-update-1.0-2.noarch requires package-that-does-not-exist"]
	common.go:98: 
		$ (cd /data/src/github.com/openshift/openshift-ansible/test/integration/openshift_health_checker/preflight && ansible-playbook -i /dev/null playbooks/package_update_dep_missing.yml)
		...
		localhost                  : ok=15   changed=2    unreachable=0    failed=0   
		openshift_ansible_test_20198306014053 : ok=43   changed=6    unreachable=0    failed=1   
		
		
		Failure summary:
		
		  1. Host:     openshift_ansible_test_20198306014053
		     Play:     Initialize host facts
		     Task:     os_firewall : Ensure firewalld service is not enabled
		     Message:  Failed to get D-Bus connection: Operation not permitted
```

##### Additional Information

These tests are somewhat unique in that they run using containers as install target hosts. I suspect that some change around docker has occurred, blocking a path that used to work. I haven't seen the same failure yet when running the tests locally.

**Comment by sdodson** [comment]
Yeah this is happening on all openshift_ansible test and merge jobs :-(

**Comment by sdodson** [comment]
Looking through the logs the version of docker that it's using is pre RHEL 7.4 so it's not particularly new.

**Comment by kwoodson** [comment]
@sdodson, @sosiouxme, The reason this is happening is due to the refactor of the firewall into the std_include.yml.  The std_include.yml is happening in the beginning to initialize whether we want iptables or firewalld.  Depending on which one is desired the os_firewall role attempts to start the service.  This service fails with the error message: 
```
fatal: [openshift_ansible_test_51223548473159]: FAILED! => {
    "changed": false, 
    "cmd": "/usr/bin/systemctl", 
    "failed": true, 
    "failed_when_result": true, 
    "invocation": {
        "module_args": {
            "daemon_reload": false, 
            "enabled": false, 
            "masked": true, 
            "name": "firewalld", 
            "no_block": false, 
            "state": "stopped", 
            "user": false
        }
    }, 
    "msg": "Failed to get D-Bus connection: Operation not permitted", 
    "rc": 1, 
    "stderr": "Failed to get D-Bus connection: Operation not permitted\n", 
    "stderr_lines": [
        "Failed to get D-Bus connection: Operation not permitted"
    ], 
    "stdout": "", 
    "stdout_lines": []
}
```

This is a behavior change.  I believe that we are planning to move that out of the way with this https://github.com/openshift/openshift-ansible/pull/5084.  If it is removed out of the std_include.yml then this should work.

The overall issue is that the container does not have permission to control the host's services.  It either needs to be a privileged container, overlay with some other options, etc. https://forums.docker.com/t/any-simple-and-safe-way-to-start-services-on-centos7-systemd/5695

**Comment by sosiouxme** [comment]
OK. Well I don't understand how it's happening most of the time but not all
the time, and I can't reproduce locally. Hope this PR helps, I'll keep
looking into it.

**Comment by sosiouxme** [comment]
https://github.com/openshift/openshift-ansible/pull/5084 is merged and it looks like tests are succeeding.
