### ISSUE TITLE
cluster-admins group contain what users or sa 

### ISSUE THREAD

**Issue by scheng1** [openshift/origin#15791]
How can I know that a group(like cluster-admins that appear in scc ) contains what users ? i can not 'oc get group cluster-admins '!

**Comment by enj** [comment]
It is not possible to tell what groups a user belongs to or the group membership of all groups.  This is because this information is only partially stored in the API server (the openshift user and group objects).  Since a user or group can be virtual (for example, from a x509 cert), it is impossible for us to know this information.


We can tell:

1. What permissions apply to a user
2. What permissions apply to a group

We cannot tell:

1. If a user exists
2. If a group exists
3. What groups a user belongs to or the group membership of all groups

**Comment by scheng1** [comment]
@enj  got it

**Comment by barleyer** [comment]
/retitle cluster-admins group contain what users or sas
