### ISSUE TITLE
Dashboard YAML should grow with window size.

### ISSUE THREAD

**Issue by jayunit100** [openshift/origin#15803]
[provide a description of the issue]

##### Version

OpenShift Master:
v1.5.1+7b451fc
Kubernetes Master:
v1.5.2+43a9be4

##### Steps To Reproduce
Paste a large (>100 line) YAML file into 
1. minishift start
2. Create a project <new-project>
3.  https://192.168.64.3:8443/console/project/<new-project>/create?tab=fromFile

##### Current Result

You have to scroll down to edit text, and even in a large browser, you dont get an expandable window for editing

##### Expected Result

The text editor for the import yaml expands reasonably to fit browswer size, or has a draggable tab at the bottom for manual resizing.

**Comment by jwforres** [comment]
The behavior has changed some since 1.5, this form is now in a dialog:

![importyamldialog](https://user-images.githubusercontent.com/1467629/31793269-c741fec2-b4ec-11e7-83cc-1de4a821a32e.png)

This effectively has the same problem though, since the dialog can't be resized the import textarea is limited.

@openshift/team-ux-review

**Comment by spadgett** [comment]
@beanh66 FYI, I know you are looking at this editor.

**Comment by beanh66** [comment]
Yes thanks @spadgett!
