### ISSUE TITLE
RBAC Migration Followup #14: Fix bootstrap conversion functions

### ISSUE THREAD

**Issue by enj** [openshift/origin#15827]
Fix panics() in `Convert...OrDie()` functions

**Comment by tiran** [comment]
This ticket looks simple. But it is unclear to me, how a proper fix should look like.

**Comment by enj** [comment]
@tiran 

For this I would expect:

1. All `panic`s to be removed with a useful error message and callers updated
2. Trace the uses of these funcs and see if it is possible for us to use RBAC object directly instead
3. If these funcs cannot be removed, open an issue to revisit them in 3.8

**Comment by tiran** [comment]
1. is easy, see PR #15952
2. takes a bit more effort because I'm not familiar with the API

``ConvertToOriginClusterRoles()`` is used by ``ReconcileClusterRolesOptions ChangedClusterRoles()`` which is used by ``pkg/diagnostics/cluster`` and ``oc adm policy reconcile-cluster-roles`` CLI.

``ConvertToOriginClusterRoleBindings`` has similar callers and is used in cluster diagnostics and ``oc adm policy reconcile-cluster-role-bindings``.

The diagnostic calls use only ``Name`` and ``Subject`` attributes. I'll try to convert the calls first.
