### ISSUE TITLE
node-bootstrapper service account does not exist

### ISSUE THREAD

**Issue by kwoodson** [openshift/origin#15869]
When going to 3.7 the node-bootstrapper service account is missing.

##### Version
[root@ip-172-31-48-185 ~]# oc version
oc v3.7.0-0.27.0
kubernetes v1.7.0+695f48a16f
openshift v3.7.0-0.27.0
kubernetes v1.7.0+695f48a16f

##### Steps To Reproduce
1. Install a 3.7.0-0.27.0
2. Verify node-bootstrapper service account does not exist

##### Current Result
No exist!

##### Expected Result
Exists
##### Additional Information
This was working with 3.6.171.  Something probably regressed a patch or something.  Please put it back so I can test scale group configurations with node bootstrapping!

atomic-openshift-3.7.0-0.27.0.git.0.071dcde.el7.x86_64
tuned-profiles-atomic-openshift-node-3.7.0-0.27.0.git.0.071dcde.el7.x86_64
atomic-openshift-excluder-3.7.0-0.27.0.git.0.071dcde.el7.noarch
atomic-openshift-clients-3.7.0-0.27.0.git.0.071dcde.el7.x86_64
atomic-openshift-master-3.7.0-0.27.0.git.0.071dcde.el7.x86_64
atomic-openshift-node-3.7.0-0.27.0.git.0.071dcde.el7.x86_64
atomic-openshift-docker-excluder-3.7.0-0.27.0.git.0.071dcde.el7.noarch

**Comment by smarterclayton** [comment]
Was removed in 181f498ed44c56fb4bf93a082770714b6456887a which has @deads2k name on it.

**Comment by smarterclayton** [comment]
We'll need that service account and role (or a close equivalent back).  Our current plan is for the automation to grab that kubeconfig and place it into launch config, and then periodically refresh the launch config every X hours by creating a new service account token.

**Comment by enj** [comment]
Why does it have to be a bootstrap role?  Can't you just make whatever role and bindings you need with ansible?

**Comment by kwoodson** [comment]
With the latest 3.7.0-0.27 build that I'm using I am receiving node csr's that look like this:

node-csr-Wq35fUiyWTh8CRPMUVdqqFVr2ocKfto24vRRJcyrFYc

Then once approved I don't see the Issued on the condition.  Is this something that has changed or was regressed from 3.6.171?  I had written up a [module](https://github.com/openshift/openshift-ansible/pull/5112) that takes a list of node names and matches them to the incoming csr names that included the node. 

NAME                                                   AGE       REQUESTOR                                                 CONDITION
node-csr-Wq35fUiyWTh8CRPMUVdqqFVr2ocKfto24vRRJcyrFYc   9m        system:serviceaccount:openshift-infra:node-bootstrapper   Approved

I never see the node request its next certificate.  Probably because it wasn't issued.

They used to look like this:
node-bootstrapper-client-ip-172-31-51-246-ec2-internal
node-bootstrapper-server-ip-172-31-51-246-ec2-internal

I updated my provisioning https://github.com/openshift/openshift-ansible/pull/5011/files to create the bootstrap service account, grant the permissions, create the kubeconfig for node-bootstrapper, and then write it to disk.

If the account changes or gets updated we'll need to update the code in that PR.

**Comment by smarterclayton** [comment]
Bootstrapping is core to the platform.  It is not something Ansible should
be creating, because it is the root of everything for node permission.
Less should be in Ansible, not more (in many cases) especially for config
that is identical across all clusters.

It looks like default CSR values were broken, but I need to look.


On Aug 19, 2017, at 12:23 AM, Kenny Woodson <notifications@github.com>
wrote:

With the latest 3.7.0-0.27 build that I'm using I am receiving node csr's
that look like this:

node-csr-Wq35fUiyWTh8CRPMUVdqqFVr2ocKfto24vRRJcyrFYc

Then once approved I don't see the Issued on the condition. Is this
something that has changed or was regressed from 3.6.171? I had written up
a module <https://github.com/openshift/openshift-ansible/pull/5112> that
takes a list of node names and matches them to the incoming csr names that
included the node.

NAME AGE REQUESTOR CONDITION
node-csr-Wq35fUiyWTh8CRPMUVdqqFVr2ocKfto24vRRJcyrFYc 9m
system:serviceaccount:openshift-infra:node-bootstrapper Approved

I never see the node request its next certificate. Probably because it
wasn't issued.

They used to look like this:
node-bootstrapper-client-ip-172-31-51-246-ec2-internal
node-bootstrapper-server-ip-172-31-51-246-ec2-internal

I updated my provisioning
https://github.com/openshift/openshift-ansible/pull/5011/files to create
the bootstrap service account, grant the permissions, create the kubeconfig
for node-bootstrapper, and then write it to disk.

If the account changes or gets updated we'll need to update the code in
that PR.

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/origin/issues/15869#issuecomment-323499403>,
or mute the thread

**Comment by enj** [comment]
Sounds reasonable.

@openshift/sig-security 

@tiran I believe you were tasked with understanding this area.

**Comment by smarterclayton** [comment]
Need a fix for this today or tomorrow, or a revert of the commit that
removed it.


On Aug 19, 2017, at 11:07 AM, Mo Khan <notifications@github.com> wrote:

Sounds reasonable.

@openshift/sig-security
<https://github.com/orgs/openshift/teams/sig-security>

@tiran <https://github.com/tiran> I believe you were tasked with
understanding this area.

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/origin/issues/15869#issuecomment-323528616>,
or mute the thread

**Comment by tiran** [comment]
@smarterclayton 

@simo5 and I looked into the code. We cannot simple revert the commit because the old code gone for good and has been replaced with RBAC rules. It also shouldn't be necessary to create ``system:node-bootstrapper`` in OpenShift any more. Upstream k8s code does it for us in ``rbac/bootstrappolicy/policy.go``:

https://github.com/openshift/origin/blob/master/vendor/k8s.io/kubernetes/plugin/pkg/auth/authorizer/rbac/bootstrappolicy/policy.go#L275-L280

```
ObjectMeta: metav1.ObjectMeta{Name: "system:node-bootstrapper"},
    Rules: []rbac.PolicyRule{
        // used to create a certificatesigningrequest for a node-specific client certificate, and watch for it to be signed
        rbac.NewRule("create", "get", "list", "watch").Groups(certificatesGroup).Resources("certificatesigningrequests").RuleOrDie(),
},
```

The rule looks exactly the same as the old rule that was removed in 181f498. What's is missing here? Is it the service account ``node-bootstrapper``?

**Comment by smarterclayton** [comment]
The service account is node-nootstrapper in openshift-infra and should have
that role bound by default.


On Aug 21, 2017, at 2:54 PM, Christian Heimes <notifications@github.com>
wrote:

@smarterclayton <https://github.com/smarterclayton>

@simo5 <https://github.com/simo5> and I looked into the code. We cannot
simple revert the commit because the old code gone for good and has been
replaced with RBAC rules. It also shouldn't be necessary to create
system:node-bootstrapper in OpenShift any more. Upstream k8s code does it
for us in rbac/bootstrappolicy/policy.go:

https://github.com/openshift/origin/blob/master/vendor/k8s.io/kubernetes/plugin/pkg/auth/authorizer/rbac/bootstrappolicy/policy.go#L275-L280

ObjectMeta: metav1.ObjectMeta{Name: "system:node-bootstrapper"},
    Rules: []rbac.PolicyRule{
        // used to create a certificatesigningrequest for a
node-specific client certificate, and watch for it to be signed
        rbac.NewRule("create", "get", "list",
"watch").Groups(certificatesGroup).Resources("certificatesigningrequests").RuleOrDie(),
},

The rule looks exactly the same as the old rule that was removed in 181f498
<https://github.com/openshift/origin/commit/181f498ed44c56fb4bf93a082770714b6456887a>.
What's is missing here? Is it the service account node-bootstrapper?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/origin/issues/15869#issuecomment-323822912>,
or mute the thread

**Comment by smarterclayton** [comment]
@kwoodson you should be fixed on master now
