### ISSUE TITLE
oc get projectrequests -o yaml panics

### ISSUE THREAD

**Issue by enj** [openshift/origin#16064]
```
$ oc get projectrequests -o yaml |& pp
panic: interface conversion: runtime.Object is *v1.Status, not *unstructured.Unstructured


To see all goroutines, visit https://github.com/maruel/panicparse#GOTRACEBACK

1: running
    cmd   get.go:356     RunGet(0x6e9ef60, 0xc4204d89f0, #1, 0xc42000e018, #1, #2, #6, #4, 0x1, 0x3, ...)
    cmd   get.go:121     NewCmdGet.func1(Factory(#6), Writer(0x1))
    cobra command.go:603 (*Command).execute(*Command(#6), []string(#3 len=3 cap=3), #6, #3)
    cobra command.go:689 (*Command).ExecuteC(*Command(#5), #2, #5, 0x4)
    cobra command.go:648 (*Command).Execute(*Command(#5), 0x2, #5)
    main  oc.go:36       main()
```

**Comment by juanvallejo** [comment]
@fabianofranz this one is a bit tricky since, right now, the `get` cmd [assumes that all lists of infos returned from the resource builder are *unstructured.Unstructured](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/cmd/get.go#L355). When it comes across a runtime.Object that does not convert to `*unstructured.Unstructured`, this panic happens.

Will look more into this, but any ideas on how to fix this are welcome. I was thinking maybe return an error if at least one item is found that cannot be converted?
