### ISSUE TITLE
Sync /install to openshift-ansible

### ISSUE THREAD

**Issue by deads2k** [openshift/origin#16086]
In order to install "extra" api servers, we're going to keep the install config files and templates in openshift/origin where the code is and where owners normally operate.  These files need to synchronized into a folder of @sdodson's choosing in openshift-ansible where they will normally be consumed.  This should happen whenever new images are pushed to docker hub for openshift/origin.

During origin CI runs, we want to run with latest revision of the install templates, which will be in origin.  @sdodson thought it would be possible to copy these files from openshift/origin to some location (I don't know where) so that the installer uses them during CI.

**Comment by stevekuznetsov** [comment]
I need to know full source and target paths and we can get a job set up that will merge into openshift-ansible whenever the code changes in origin.

**Comment by sdodson** [comment]
@ewolinetz Do we need to map origin/install/{tsb,prometheus,service-catalog,...} to openshift-ansible/roles/openshift_{tsb,prometheus,service-catalog,...} or can we do a more generic mapping of origin/install/* to openshift-ansible/templates/install/* and then roles pull templates/files from that path? I'm fuzzy on ansible search path.

**Comment by ewolinetz** [comment]
@sdodson I think we can do the more generic mapping. We should be able to find those templates using magic path variables ansible gives us by default [1]


[1] http://docs.ansible.com/ansible/latest/playbooks_variables.html#magic-variables-and-how-to-access-information-about-other-hosts

**Comment by stevekuznetsov** [comment]
Ok, can we do a real simple:

| `openshift/origin` path | `openshift/openshift-ansible` path |
| --- | --- |
| `install/whatever` | `somewhere/idk` | 

listing?

**Comment by sdodson** [comment]
Recursive copy of openshift/origin path install/* copies into openshift/openshift-ansible files/origin-components/* ?

**Comment by stevekuznetsov** [comment]
| `openshift/origin` path | `openshift/openshift-ansible` path |
| --- | --- |
| `install/` | `files/origin-components/` |

**Comment by sdodson** [comment]
yeah

**Comment by stevekuznetsov** [comment]
@kargakis this mirrors the web console vendor in that we need to find a way to get these into the queue and coalesce multiple updates in case they come in faster than the PRs can merge

**Comment by kargakis** [comment]
@stevekuznetsov since this change concerns openshift-ansible where tests are faster and we don't care as much about breaking batches, we could put together an external plugin that pushes commits from origin into openshift-ansible. Or batch them into bumps. This sort of syncing has some overlap with the publishing bot.

@mfojtik @sttts does the publishing bot sync code between repos based on specific paths both in the source and target repos? We want to sync code from `openshift/origin/install` to `openshift/openshift-ansible/files/origin-components/`.

**Comment by sdodson** [comment]
BTW, the structure of openshift-ansible has changed so that templates for each component are no co-located with their roles so we'll want to establish a clear structure that maps components in origin to roles in openshift-ansible. ex https://github.com/openshift/openshift-ansible/tree/master/roles/openshift_web_console/files
