### ISSUE TITLE
oc rollout latest support for deployments

### ISSUE THREAD

**Issue by kargakis** [openshift/origin#16222]
/sig master
/kind enhancement
/assign @tnozicka @mfojtik
cc @smarterclayton

**Comment by mfojtik** [comment]
Just want to confirm the expected behavior of this command used with "deployments":

1) If D has no triggers defined, should this mutate the RS template (like adding an annotation with a timestamp?)
2) If D has triggers defined but automatic=false, should this just mimic `oc set image` and update the image fields in deployment template to match the latest IS version?
3) If D has triggers defined and automatic=true, should this basically do 1) ?

Also since this is a new feature and we passed feature freeze for 3.7, I'm setting the milestone for this to 3.8.

**Comment by kargakis** [comment]
I am not sure about 1 and 3 but we definitely want to resolve the image(s) when automatic is false in the annotation.

cc: @smarterclayton

**Comment by mfojtik** [comment]
The `oc set image deployment/foo image=istag:latest` should mutate the deployment image field to match the latest tag if the "istag:latest" image. 

To be consistent with the DC, the 1) and 3) are important because for deployment they don't make a lot of sense (upstream deployments don't run as jobs that can be retried or re-runned). Not sure if trying to make them behave like DC is the right direction... Not doing 1) or 3) will make people ask why their deployment version is not bumped.

**Comment by kargakis** [comment]
WIth `oc set image` 1) I cannot use an automatic trigger that I flip between true/false as I see fit and 2) it doesn't work if I have multiple images that I need to resolve in the DC/D.

**Comment by tnozicka** [comment]
`1) ` is a rolling restart

Having multiple RS just for rolling restart seems not ideal; your history will be polluted by the same RS and when you reach revisionHistoryLimit there might not be a single RS to rollback to as all might be the same differing only in that timestamp annotation

But implementing it that way might be confusing as it wouldn't result in creating new RS. Depends if that's an issue. One option would be to tell the user that the latest is already deployed and have rolling-restart command to be separate.

**Comment by tnozicka** [comment]
We are going with rolling-restart - tracked here: https://trello.com/c/TwF44TA9
/close
