### ISSUE TITLE
'make' appears not to build binaries sometimes

### ISSUE THREAD

**Issue by pmorie** [openshift/origin#16254]
```console
$ which oc
~/code/origin/_output/local/bin/linux/amd64/oc
$ ls -l ~/code/origin/_output/local/bin/linux/amd64/oc
-rwxrwxr-x. 1 pmorie 186702488 Jul 12 09:59 /home/pmorie/code/origin/_output/local/bin/linux/amd64/oc
$ make
hack/build-go.sh  
++ Building go targets for linux/amd64: cmd/openshift cmd/oc cmd/kubefed pkg/sdn/plugin/sdn-cni-plugin vendor/github.com/containernetworking/cni/plugins/ipam/host-local vendor/github.com/containernetworking/cni/plugins/main/loopback
hack/build-go.sh took 6 seconds
$ ls -l ~/code/origin/_output/local/bin/linux/amd64/oc
-rwxrwxr-x. 1 pmorie 186702488 Jul 12 09:59 /home/pmorie/code/origin/_output/local/bin/linux/amd64/oc
$ rm -rf _output/
$ make
hack/build-go.sh  
++ Building go targets for linux/amd64: cmd/openshift cmd/oc cmd/kubefed pkg/sdn/plugin/sdn-cni-plugin vendor/github.com/containernetworking/cni/plugins/ipam/host-local vendor/github.com/containernetworking/cni/plugins/main/loopback
hack/build-go.sh took 325 seconds
$ ls -l ~/code/origin/_output/local/bin/linux/amd64/oc
-rwxrwxr-x. 1 pmorie 187063624 Sep  7 11:11 /home/pmorie/code/origin/_output/local/bin/linux/amd64/oc
$ make
hack/build-go.sh  
++ Building go targets for linux/amd64: cmd/openshift cmd/oc cmd/kubefed pkg/sdn/plugin/sdn-cni-plugin vendor/github.com/containernetworking/cni/plugins/ipam/host-local vendor/github.com/containernetworking/cni/plugins/main/loopback
hack/build-go.sh took 9 seconds
$ ls -l ~/code/origin/_output/local/bin/linux/amd64/oc
-rwxrwxr-x. 1 pmorie 187063624 Sep  7 11:11 /home/pmorie/code/origin/_output/local/bin/linux/amd64/oc
```

**Comment by stevekuznetsov** [comment]
I'm not sure `make build` rebuilt without `make clean` in the past -- /cc @smar

**Comment by smarterclayton** [comment]
make build has never required make clean.

**Comment by stevekuznetsov** [comment]
Has something changed recently with how we do builds?

**Comment by smarterclayton** [comment]
i'm not sure why this is a problem?

**Comment by stevekuznetsov** [comment]
If `make build` previously rebuilt the binaries without a `make clean` and something regressed and people are using the `make build` button to get updated binaries but are not getting them... they will be confused and frustrated when they see their compilation not working? IDK

**Comment by smarterclayton** [comment]
I don't see any evidence that builds aren't working in his paste?

On Sep 12, 2017, at 12:17 PM, Steve Kuznetsov <notifications@github.com>
wrote:

If make build previously rebuilt the binaries without a make clean and
something regressed and people are using the make build button to get
updated binaries but are not getting them... they will be confused and
frustrated when they see their compilation not working? IDK

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/origin/issues/16254#issuecomment-328904467>,
or mute the thread
