### ISSUE TITLE
Incorrectly formatted pkcs key causes new routes to not work

### ISSUE THREAD

**Issue by adbaldi** [openshift/origin#16359]
We had a user create a secure route using a PKCS#1 private key (key file should start with -----BEGIN RSA PRIVATE KEY-----) wrapped in a PKCS#8 banner (-----BEGIN PRIVATE KEY-----).  This caused haproxy to reload it's configuration and error out when it got to the newly added secure route.  Any routes added/modified after that route was added would not get pulled into haproxy and would result in an "Application is not available error" when trying to load the url.

The error reported by haproxy was as follows:

E0914 12:16:44.152014       1 ratelimiter.go:52] error reloading router: exit status 1
[ALERT] 256/121644 (49268) : parsing [/var/lib/haproxy/conf/haproxy.config:137] : 'bind 127.0.0.1:10444' : 'crt-list' : error processing line 4 in file '/var/lib/haproxy/conf/cert_config.map' : unable to load SSL private key from PEM file '/var/lib/haproxy/router/certs/<project_name>_<route_address>.pem'.
[ALERT] 256/121644 (49268) : Error(s) found in configuration file : /var/lib/haproxy/conf/haproxy.config
[ALERT] 256/121644 (49268) : Fatal errors found in configuration.

I'm guessing this will be low priority but wanted to get this out there in case someone else runs into the same problem.

##### Version
oc v1.5.1
kubernetes v1.5.2+43a9be4
features: Basic-Auth GSSAPI Kerberos SPNEGO

openshift v1.5.1
kubernetes v1.5.2+43a9be4

##### Steps To Reproduce
1. find an old pkcs#1 certificate/key pair
2. remove " RSA" from the BEGIN and END tags
3. use for a secure route

##### Current Result
OpenShift allows the route to be created

##### Expected Result
reject the route

##### Additional Information
Router image:  openshift/origin-haproxy-router:v1.5.1

**Comment by smarterclayton** [comment]
This was fixed by the 'extended validation' feature in the router in 3.6.0, where any unrecognizable cert will be rejected and the route status updated.  In 1.5.1, you can instruct the router to disable custom certificates globally, although double check that extended validation is on for your router (`EXTENDED_VALIDATION`)

**Comment by adbaldi** [comment]
Extended validation was not explicitly set on the router.  Isn't is enabled by default in 1.5 though?  Either way, i set it to true and tested the invalid private key again.  The route was still accepted and caused the router(s) to fail to progress past the invalid key in the config.

I'm guessing this means my options on 1.5 are to watch the logs for the error or disable custom certs globally?

**Comment by smarterclayton** [comment]
3.6 added more extensive validation around this area.  For 1.5 yeah that's
unfortunately the best you can do.


On Sep 19, 2017, at 10:41 AM, adbaldi <notifications@github.com> wrote:

Extended validation was not explicitly set on the router. Isn't is enabled
by default in 1.5 though? Either way, i set it to true and tested the
invalid private key again. The route was still accepted and caused the
router(s) to fail to progress past the invalid key in the config.

I'm guessing this means my options on 1.5 are to watch the logs for the
error or disable custom certs globally?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/origin/issues/16359#issuecomment-330561633>,
or mute the thread

**Comment by adbaldi** [comment]
Thanks for the info.
