### ISSUE TITLE
Strange router behavior for passthrough routes

### ISSUE THREAD

**Issue by miminar** [openshift/origin#16556]
Me and one customer find it very strange that router returns `503` HTTP code when the target service listens on `:443` while the client tries to talk to `:80`. We would expect the router to redirect the client to a 
 secured `:443` port.

The same situation applies to a service listening on `:80` and client connecting to the router on `:443` port.

Is there a reason for doing this? Could this be improved?

**Comment by miminar** [comment]
FYI @erikbsap

**Comment by erikbsap** [comment]
Thanks for creating the ticket @miminar.

My expectation would be something like this example with the non-redhat-docker-registry:

```
$ curl -k -vv localhost:5000/v2
* About to connect() to localhost port 5000 (#0)
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 5000 (#0)
> GET /v2 HTTP/1.1
> User-Agent: curl/7.29.0
> Host: localhost:5000
> Accept: */*
>
< HTTP/1.1 301 Moved Permanently
< Docker-Distribution-Api-Version: registry/2.0
< Location: /v2/
< Date: Tue, 26 Sep 2017 09:28:07 GMT
< Content-Length: 39
< Content-Type: text/html; charset=utf-8
<
<a href="/v2/">Moved Permanently</a>.
```

With that info I as the user know that I have to do something different. But currently the Redhat docker registry will return `HTTP 503`, which gives the impression the cluster is unhealthy.

Also please note that the response in my example contains a header line which says I'm actually talking to the registry. This is already important information when debugging, because it means the name was resolved correctly and openshift could forward my request to the correct pod.

**Comment by Miciah** [comment]
Use `oc create route passthrough --insecure-policy=Redirect` or this equivalent stanza in the route definition:

```yaml
spec:
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: passthrough
```

Using this, HTTP requests will get a 302 redirect to the HTTPS URL.  For the reverse (HTTPS connections to an HTTP service), you could create a second, edge route.  Does that work for your use case?

**Comment by erikbsap** [comment]
Yes, nice! This way it's also part of a policy and it makes sense that it isn't done as default. Is there a way to configure that in the hosts file for openshift advanced installation?
