### ISSUE TITLE
Always see BuildConfigInstantiateFailed warning event after creating build config

### ISSUE THREAD

**Issue by spadgett** [openshift/origin#16557]
I always see this warning after creating a build config using `oc new-app` or through the web console:

> BuildConfigInstantiateFailed
> gave up on Build for BuildConfig test/nodejs-ex (0) due to fatal error: the LastVersion(1) on build config test/nodejs-ex does not match the build request LastVersion(0)

This doesn't seem to cause a problem except that it adds noise to the events and might make the user think something's wrong. Note that this event will show up in the notifications drawer in the web console, so it's somewhat more prominent there than on the CLI.

##### Version

oc v3.7.0-alpha.1+75c64e3-653
kubernetes v1.7.0+80709908fd
features: Basic-Auth

Server https://127.0.0.1:8443
openshift v3.7.0-alpha.1+899d4c9-676
kubernetes v1.7.0+80709908fd

##### Steps To Reproduce

```
$ oc new-app https://github.com/openshift/ruby-ex.git
$ oc describe bc/ruby-ex
```

You see the `BuildConfigInstantiateFailed` warning for the build config.

**Comment by bparees** [comment]
Seems like we're racing against something else that's creating the build, possibly the imagechangetrigger vs the buildconfigchange trigger.

Not really sure it's easy to fix since we want to actually create both of those triggers on the buildconfig.

We could consider not emitting an event in this particular case, but there are legitimate cases where a buildrequest will be rejected for this reason and we'd want to alert the user.

I think we can consider super-special casing this to not emit the event when the buildrequest.lastversion==0.

**Comment by coreydaley** [comment]
It looks like the other side of this race condition si
Events:

>  
  Warning	BuildConfigTriggerFailed	4m	buildconfig-controller	error triggering Build for BuildConfig cdaley/ruby-ex: Internal error occurred: build config cdaley/ruby-ex has already instantiated a build for imageid ...
