### ISSUE TITLE
no kind is registered for the type apps.DeploymentLogOptions

### ISSUE THREAD

**Issue by kargakis** [openshift/origin#16819]
```
$ oc logs -f dc/hook
Error from server (BadRequest): no kind is registered for the type apps.DeploymentLogOptions
$ oc version
oc v3.7.0-alpha.1+36865f9-1008
kubernetes v1.7.6+a08f5eeb62
features: Basic-Auth

Server https://api.ci.openshift.org:443
openshift v3.7.0-alpha.1+70fcade-21
kubernetes v1.7.0+695f48a16f
```
/kind bug
/sig master
/assign @mfojtik

**Comment by kargakis** [comment]
Similar issue for builds
```
$ oc logs -f bc/tide
Error from server (BadRequest): no kind is registered for the type build.BuildLogOptions
```
cc @bparees

**Comment by mfojtik** [comment]
@deads2k did we broke something in the clientsets ?

**Comment by bparees** [comment]
@csrwng investigated this yesterday and found that while a master client can't talk to (get build logs from) a 3.7 alpha cluster, it can talk to a master cluster and it can talk to a 3.6 cluster.

so we concluded something probably was broken but not something that mattered since it was fixed within the 3.7 release.

**Comment by mfojtik** [comment]
@kargakis moving this off the blocker list, seems like master to master works for me.

**Comment by kargakis** [comment]
works fine now
