### ISSUE TITLE
 [Feature:Prometheus][Conformance] Prometheus when installed to the cluster should start and expose a secured proxy and unsecured metrics

### ISSUE THREAD

**Issue by bparees** [openshift/origin#16877]
```
/tmp/openshift/build-rpm-release/tito/rpmbuild-originOELGuN/BUILD/origin-3.7.0/_output/local/go/src/github.com/openshift/origin/test/extended/prometheus/prometheus.go:110
Expected error:
    <*errors.errorString | 0xc421762020>: {
        s: "host command failed: error running &{/data/src/github.com/openshift/origin/_output/local/bin/linux/amd64/kubectl [kubectl --server=https://internal-api.prtest-5a37c28-9710.origin-ci-int-gce.dev.rhcloud.com:8443 --kubeconfig=/tmp/cluster-admin.kubeconfig exec --namespace=extended-test-prometheus-k5svr-c5fss execpod7k01f -- /bin/sh -c curl -s -k -H 'Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJwcm9tZXRoZXVzLXRva2VuLXAzODI0Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQubmFtZSI6InByb21ldGhldXMiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC51aWQiOiIxMzZiMWFjNi1iMDliLTExZTctYjNlNi00MjAxMGE4MDAwMDQiLCJzdWIiOiJzeXN0ZW06c2VydmljZWFjY291bnQ6a3ViZS1zeXN0ZW06cHJvbWV0aGV1cyJ9.b1GEp4fWhpNTicLrn9CDESUCvdu5rldbXS4-ezg_zIy8JNyhuatKgseXIVCq0MUdXnkvjmf6ciKyzlmTrISS_JDF9hNpSwfAYMD6gyK6RLzPrLPTWhLlIMSzD7XO9AhFMwbcaPCPZuC0siRcj_tq64qpS1kp4qJLpCYwj5aWFNDnbif8tnEytgaFcXOvl6_DglECJ8wgR1VdpjxuDbGhW6YciSdSCIv-Mzy2OlnSVKOCanKQ2mlZcVi-yTFrQ9gwKgrp63BFagNwmbrv7kQSYz5tzz_vNTbcnk8TPh7ET2wHUZo7PgVhooIEqopicr7xVt9vN5choSG1zvqmHyXbNw' \"https://prometheus.kube-system.svc:443/api/v1/targets\"] []  <nil>  Error from server: error dialing backend: dial tcp 10.128.0.5:10250: getsockopt: connection refused\n [] <nil> 0xc420f2bc20 exit status 1 <nil> <nil> true [0xc42000e400 0xc42000e438 0xc42000e480] [0xc42000e400 0xc42000e438 0xc42000e480] [0xc42000e430 0xc42000e478] [0x17c18f0 0x17c18f0] 0xc421c9fbc0 <nil>}:\nCommand stdout:\n\nstderr:\nError from server: error dialing backend: dial tcp 10.128.0.5:10250: getsockopt: connection refused\n\nerror:\nexit status 1\n\n",
    }
    host command failed: error running &{/data/src/github.com/openshift/origin/_output/local/bin/linux/amd64/kubectl [kubectl --server=https://internal-api.prtest-5a37c28-9710.origin-ci-int-gce.dev.rhcloud.com:8443 --kubeconfig=/tmp/cluster-admin.kubeconfig exec --namespace=extended-test-prometheus-k5svr-c5fss execpod7k01f -- /bin/sh -c curl -s -k -H 'Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJwcm9tZXRoZXVzLXRva2VuLXAzODI0Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQubmFtZSI6InByb21ldGhldXMiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC51aWQiOiIxMzZiMWFjNi1iMDliLTExZTctYjNlNi00MjAxMGE4MDAwMDQiLCJzdWIiOiJzeXN0ZW06c2VydmljZWFjY291bnQ6a3ViZS1zeXN0ZW06cHJvbWV0aGV1cyJ9.b1GEp4fWhpNTicLrn9CDESUCvdu5rldbXS4-ezg_zIy8JNyhuatKgseXIVCq0MUdXnkvjmf6ciKyzlmTrISS_JDF9hNpSwfAYMD6gyK6RLzPrLPTWhLlIMSzD7XO9AhFMwbcaPCPZuC0siRcj_tq64qpS1kp4qJLpCYwj5aWFNDnbif8tnEytgaFcXOvl6_DglECJ8wgR1VdpjxuDbGhW6YciSdSCIv-Mzy2OlnSVKOCanKQ2mlZcVi-yTFrQ9gwKgrp63BFagNwmbrv7kQSYz5tzz_vNTbcnk8TPh7ET2wHUZo7PgVhooIEqopicr7xVt9vN5choSG1zvqmHyXbNw' "https://prometheus.kube-system.svc:443/api/v1/targets"] []  <nil>  Error from server: error dialing backend: dial tcp 10.128.0.5:10250: getsockopt: connection refused
     [] <nil> 0xc420f2bc20 exit status 1 <nil> <nil> true [0xc42000e400 0xc42000e438 0xc42000e480] [0xc42000e400 0xc42000e438 0xc42000e480] [0xc42000e430 0xc42000e478] [0x17c18f0 0x17c18f0] 0xc421c9fbc0 <nil>}:
    Command stdout:
    
    stderr:
    Error from server: error dialing backend: dial tcp 10.128.0.5:10250: getsockopt: connection refused
    
    error:
    exit status 1
    
    
not to have occurred
/tmp/openshift/build-rpm-release/tito/rpmbuild-originOELGuN/BUILD/origin-3.7.0/_output/local/go/src/github.com/openshift/origin/test/extended/prometheus/prometheus.go:91
```

@smarterclayton, @jcantrill  not sure who owns the prometheus component itself right now, please reassign as needed.

https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/16874/test_pull_request_origin_extended_conformance_gce/9710/

**Comment by smarterclayton** [comment]
I think this is the same as the network flakes, where we are getting
occasional failures when trying to get off the pod network.  The runner pod
is trying to access the host network, but that's not something that should
in any way be disrupted.  I'd say this looks a lot like our periodic
failure to push to registry because SDN is unavailable / in the midst of
changing.

@openshift/sig-networking

**Comment by danwinship** [comment]
> I'd say this looks a lot like our periodic failure to push to registry because SDN is unavailable / in the midst of changing.

Service IPs are complicated and have lots of ways they can fail, but the error here is with a *pod* IP, and in normal operation the SDN shouldn't be changing in ways that would make a valid pod IP temporarily unavailable.

And if the network was temporarily down, you'd expect "timed out" or "no route to host" rather than "connection refused", which implies that the packet was successfully routed to *some* IP (hopefully the correct one...), but that IP was not listening on the destination port.

I don't know the details of the test but is it possible the client is just running before the server is ready?

**Comment by danwinship** [comment]
> which implies that the packet was successfully routed to some IP (hopefully the correct one...)

actually, it has to have been routed to the correct IP, or the destination would just ignore the packet, so again you'd get timeout/no route.

**Comment by smarterclayton** [comment]
Interesting.  It was going to the kubelet from a host network pod (I
think).

On Oct 16, 2017, at 5:33 PM, Dan Winship <notifications@github.com> wrote:

which implies that the packet was successfully routed to some IP (hopefully
the correct one...)

actually, it has to have been routed to the correct IP, or the destination
would just ignore the packet, so again you'd get timeout/no route.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/origin/issues/16877#issuecomment-336925087>,
or mute the thread

**Comment by smarterclayton** [comment]
Correction, this was the exec call failing - it couldn't exec into a pod.  The master was unable to hit the node at that IP.   So e2e test running on the master connects to the apiserver to run an exec - the apiserver is reachable, but the kubelet is not.  I can't think of why a GCE master would be unable to reach a GCE node except due to some sort of node overload?

**Comment by smarterclayton** [comment]
Another one https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/16412/test_pull_request_origin_extended_conformance_gce/10915/#k8sio-proxy-version-v1-should-proxy-logs-on-node-conformance-suiteopenshiftconformanceparallel-suitek8s

**Comment by smarterclayton** [comment]
This is no longer failing (last comment was because GitHub.com didn't resolve)
