### ISSUE TITLE
Service provision fails when a deployment times out

### ISSUE THREAD

**Issue by ncameronbritt** [openshift/origin#16937]
Provisioning fails when a deployment times out and the only recourse for the user is to delete the service and try again. The 10-minute timeout for deployments does not always seem sufficient for creating the deployment. 

User can still redeploy and eventually get the deployment running, but the provision remains failed. This may leave the user in some in-between state. 

![screen shot 2017-10-18 at 3 24 09 pm](https://user-images.githubusercontent.com/8974593/31738711-8e9aa99e-b419-11e7-9cd6-929060066875.png)

@spadgett @jwforres @bparees 

##### Version
oc v3.7.0-alpha.1+6dbc13e-1132
kubernetes v1.7.6+a08f5eeb62
features: Basic-Auth

Server https://127.0.0.1:8443
openshift v3.7.0-alpha.1+75ef09b-1151
kubernetes v1.7.6+a08f5eeb62

##### Steps To Reproduce
1. [step 1]
2. [step 2]

##### Additional Information
[try to run `$ oc adm diagnostics` (or `oadm diagnostics`) command if possible]
[if you are reporting issue related to builds, provide build logs with `BUILD_LOGLEVEL=5`]
[consider attaching output of the `$ oc get all -o json -n <namespace>` command to the issue]
[visit https://docs.openshift.org/latest/welcome/index.html]

**Comment by bparees** [comment]
pretty sure this is "can't fix".

having the provision fail due to timing out on the DC is a choice made by the template author:
https://docs.openshift.org/latest/dev_guide/templates.html#waiting-for-template-readiness

And there's no way for the system to know you manually fixed the deployment after we've failed the provision.  So the only "approved" way to get back to a good state is to de-provision/delete the failed service instance and provision a new one.

that said, the timeout is supposed to be one hour, not 10 minutes.  If the DC itself is failing (vs the TSB giving up after an hour), then that's a DC problem and you'll need to talk to @mfojtik about potential workarounds/fixes.

/cc @jim-minter @pmorie

**Comment by mfojtik** [comment]
dc has default timeout set for 10m, but you can increase it using
timeoutSeconds in dc

**Comment by jim-minter** [comment]
Do we know why the deploy failed in this case?  Slow pull?

**Comment by ncameronbritt** [comment]
@jim-minter Yes, more than likely the image didn't pull in time.

**Comment by jim-minter** [comment]
> dc has default timeout set for 10m, but you can increase it using
> timeoutSeconds in dc

That timeout seems too short to me and I think we should lengthen it.  Are we able to do that (API-wise)?  Or should we/must we carry this in our templates?

**Comment by ncameronbritt** [comment]
Now that we're using the SC, it's not as simple as just redeploying in the event that a deployment fails. I'm not sure what the answer is here, but I feel like it's important to strike a balance between giving the deployment enough time so that it can deploy, but not so much that the user is stuck waiting for the provision to fail so that they can delete the service and try again.

**Comment by bparees** [comment]
I don't think there's any SC or TSB issue here (other than the other existing issues for inability to cleanup a failed provision), so assigning to @mfojtik to either close, or raise the default DC timeout so users are less likely to hit this.
