### ISSUE TITLE
Image stream conflict importing images

### ISSUE THREAD

**Issue by galderz** [openshift/origin#16966]
Using:
* OpenShift Origin 3.6
* Docker 1.13.1
* kubectl v1.6.4

Together with the service catalog and running the `start-openshift.sh` script [here](https://github.com/infinispan-demos/streaming-data-kubernetes/blob/master/start-openshift.sh) sometimes finishes with errors like this:

    Error from server (Conflict): Operation cannot be fulfilled on imagestream.image.openshift.io "infinispan": the image stream was updated from "1382" to "1398"

These errors do not seem to affect the behaviour of the OpenShift, nor my demos, but it can be confusing for the users.

What does the error really mean? What are its implications? Any workarounds?

Cheers,
Galder

**Comment by mfojtik** [comment]
Do you know which command fails with that? just stick set -x to that bash script.

**Comment by bparees** [comment]
it is almost certainly because you've created an imagestream which will automatically start an import, and then you are explicitly running an import (oc import-image), so both operations will be trying to update the imagestream.  it should be effectively benign, but there should be no reason to run the import-image at the end of your script and if you remove it, i do not think you will see this error anymore.
