### ISSUE TITLE
why mounting hostPath is not allowed by default

### ISSUE THREAD

**Issue by 2erowf** [openshift/origin#16980]
if restricted SCC doesn't allow you to run as root, why not allow hostPath in restricted SCC?
if you are not root, then whatever directories mounted from host are also protected by good old linux permission policy.
for example, if user foo cannot access /bar on host, then it must not be able to access /bar in container if /bar is mounted to container.  so not allowing hostPath doesn't seem to add extra safety IMHO.

Can someone give me an example why openshift team decide to exclude hostPath from default SCC?

I asked because many monitoring solutions relies on hostPath for monitoring and having user create a service account just so they can start monitoring their app seems unnecessary.

##### Version
oc v3.6.0+c4dd4cf

##### Steps To Reproduce
This is default behavior

##### Current Result
hostPath not allowed
##### Expected Result
hostPath should be allowed by default

**Comment by smarterclayton** [comment]
Because an admin might accidentally expose a world readable file unintentionally.  Many security escapes start by having access to the host filesystem, and completely denying it is a good way to prevent such escapes.

**Comment by php-coder** [comment]
> for example, if user foo cannot access /bar on host, then it must not be able to access /bar in container if /bar is mounted to container. so not allowing hostPath doesn't seem to add extra safety IMHO.

In addition to what @smarterclayton has said, consider also another case when all users are allowed to create files in `/tmp` and if user from a container is able to mount `/tmp` from a host, he also will be able to perform symlinks or time of check to time of use attacks.

There can be (and are) many more ways of doing something malicious, so we are protecting users by default against them. Such a proactive approach also defends against the cases that not known/unpublished yet.

> I asked because many monitoring solutions relies on hostPath for monitoring and having user create a service account just so they can start monitoring their app seems unnecessary.

While we can't allow hostPath by default for all, you as an admin can do it. Using services accounts also bring you a little more security because 1) admin have to think about the possible consequences and make an deliberate decision 2) granting different access to the different service accounts is still better than granting access to all because it reduces attack vector and a possible impact in case of compromising.
