### ISSUE TITLE
selfLink returned from ImageStreamImage and ImageStreamTag calls is not a valid link

### ISSUE THREAD

**Issue by jwforres** [openshift/origin#1701]
It returns a URL like:

`/osapi/v1beta1/imageStreamImages/b85d88371cd9f8189637e57d65844dc57547360f6aadf8b5bdd46a6e5b288505?namespace=`

Which can't be retrieved because imageStreamImages expects the name to be \<imageStreamName\>@\<imageId\>

**Comment by ncdc** [comment]
I think this comes from upstream. After we return the object in question (in this case, an image), I believe control goes to https://github.com/openshift/origin/blob/master/Godeps/_workspace/src/github.com/GoogleCloudPlatform/kubernetes/pkg/apiserver/resthandler.go#L99, where it calls https://github.com/openshift/origin/blob/master/Godeps/_workspace/src/github.com/GoogleCloudPlatform/kubernetes/pkg/apiserver/resthandler.go#L519-L521. I'm not familiar enough with this code at the moment to know if there's a way to override. Maybe instead of returning `imageapi.Image` we can just return `ImageStreamTag` or `ImageStreamImage` as appropriate, since they already embed `Image`. That would probably fix it, as well as making `Kind` and `Name` have the values you'd expect.

**Comment by ncdc** [comment]
@smarterclayton thoughts?

**Comment by smarterclayton** [comment]
We should be returning image stream tag and image stream image.

**Comment by jwforres** [comment]
@ncdc how much will this affect the response, other than kind/name?

**Comment by ncdc** [comment]
@jwforres it shouldn't affect it at all; my plan is to set the embedded `Image` to inline the json.

**Comment by ncdc** [comment]
Is this acceptable for `ImageStreamTag`? Note that it still returns what is actually an `Image`, but the `kind` is `ImageStreamTag`, and the metadata has `name=busybox:latest` and `selfLink=/osapi/v1beta1/imageStreamTags/busybox:latest?namespace=p1`. The contents of the image may change over time, but the `name` and `selfLink` will always stay the same.

```
$ osc get -n p1 istag busybox:latest -o yaml
```
```yaml
apiVersion: v1beta1
dockerImageMetadata:
  Architecture: amd64
  Author: "Jérôme Petazzoni <jerome@docker.com>"
  Config:
    Cmd:
    - /bin/sh
    Env:
    - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    Hostname: 7f674915980d
    Image: ea13149945cb6b1e746bf28032f02e9b5a793523481a0a18645fc77ad53c4ea2
  Container: 83dcf36ad1042b90f4ea8b2ebb60e61b2f1a451a883e04b388be299ad382b259
  ContainerConfig:
    Cmd:
    - /bin/sh
    - -c
    - '#(nop) CMD [/bin/sh]'
    Env:
    - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    Hostname: 7f674915980d
    Image: ea13149945cb6b1e746bf28032f02e9b5a793523481a0a18645fc77ad53c4ea2
  Created: 2014-12-31T22:23:56Z
  DockerVersion: 1.4.1
  Id: 4986bf8c15363d1c5d15512d5266f8777bfba4974ac56e3270e7760f6f0a8125
  Parent: ea13149945cb6b1e746bf28032f02e9b5a793523481a0a18645fc77ad53c4ea2
  apiVersion: "1.0"
  kind: DockerImage
dockerImageMetadataVersion: "1.0"
dockerImageReference: 172.30.221.126:5000/p1/busybox@sha256:05e90a5daafdca2a6508cde51651b19ca541d79f68d675a864b6cc745e54983c
kind: ImageStreamTag
metadata:
  creationTimestamp: 2015-04-10T20:14:01Z
  name: busybox:latest
  namespace: p1
  resourceVersion: "3130"
  selfLink: /osapi/v1beta1/imageStreamTags/busybox:latest?namespace=p1
  uid: 20bba079-dfbe-11e4-b304-001c422dcd49
```

**Comment by jwforres** [comment]
Yeah that is what I would expect for ImageStreamTag. ImageStreamImage I 
would not expect to change since it should be pointing to a specific image.

**Comment by ncdc** [comment]
@jwforres ImageStreamImage will change slightly to correct name and selfLink in a similar manner.
