### ISSUE TITLE
chown operation not permitted

### ISSUE THREAD

**Issue by adalga** [openshift/origin#17164]
Hi,

I am trying to deploy oficial mongodb image from docker hub through openshift container platform. When I mount the "/data/db" to persistent volume claim I got an error like 
"chown: changing ownership of '/data/db': Operation not permitted".

I tried to give anyuid policy to service account.However it doesn't work.

my openshift version is 3.5.5.26 and kubernetes is 1.5.2+

I also tried to use bitnami-docker-mongodb image and when I tried to persist data I faced with similar error.

**Comment by xiaods** [comment]
https://developers.redhat.com/blog/2017/10/26/configure-persistent-storage-openshift-kubernetes-development-environment/

you can try create pv first.

**Comment by akd31** [comment]
I already have created pv. I don't get what do you mean.

**Comment by xiaods** [comment]
https://github.com/openshift/openshift-docs/pull/868/files

**Comment by xiaods** [comment]
https://github.com/openshift/origin/issues/9131

**Comment by xiaods** [comment]
oadm policy add-scc-to-user anyuid -z default

**Comment by akd31** [comment]
> I tried to give anyuid policy to service account.However it doesn't work.

I did that as I mentioned. It doesn't work.

**Comment by php-coder** [comment]
@akd31 In order to help you, could I ask you to post the output of the command `oc get pod <pod> -o yaml` here?

Also, have you tried https://github.com/sclorg/mongodb-container that is 100% OpenShift-compatible MongoDB docker image.

**Comment by ankushchadha** [comment]
Try following - 

oc adm policy add-scc-to-user anyuid $THE_USER
oc adm policy add-scc-to-user privileged $THE_USER
oc adm policy add-scc-to-group anyuid system:authenticated

Though the certified image i.e. part of https://github.com/sclorg/mongodb-container  shouldn't require root access as the user is being changed as part of the Dockerfile.

**Comment by akd31** [comment]
I can't share the yaml file since I am working offline and it has kinda long output. 

I fixed my issue by extending official mongo image by adding changing user to mongodb at Dockerfile. Thanks for your attention btw.

**Comment by php-coder** [comment]
@akd31 OK, Here are some advice how to debug it:

1) first check under what SCC the pod was admitted: execute `oc get pod <pod> -o yaml | grep scc`. I suspect that it will be `restricted`

2) how do you create a MongoDB pod? Is it plain Pod or you're using StatefulSets/something else? This question is important because depending on the answer, you need to grant access to a different accounts (to a user in case of a pod and to service account if it's not a plain pod).

3) Does a pod specification has `serviceAccountName`? This question is important because depending on the answer, you need to grant access to a different accounts (to the specified or to the `default` if there is no service account).

4) Do you have `privileged: true`/`runAsUser: 0` in pod's security context or container's security context? This question is important because you if pod doesn't request privileged mode/root user, it could always be admitted by the most strict SCC.

**Comment by akd31** [comment]
1. It is openshift.io/scc: anyuid
2. I am usign openshift container platform gui to deploy image and edit deployment config via YAML. I don't create pod manually.
3. Yes it does have both serviceAccount and serviceAccountName.
4. I don't know it how I could check this.

**Comment by php-coder** [comment]
> It is openshift.io/scc: anyuid

It means that pod was admitted correctly. As far I can see, in the official mongodb image, user is created in the Dockerfile and its UID doesn't match with the owner of the `/data/db` directory. The UIDs should match or the directory should have write access for the root group.

**Comment by akd31** [comment]
As I mentioned when I change user to mongodb at Dockerfile it works, otherwise it checks the uid and if it is not mongodb (which is root by default) tries to chown and it causes our situation.
