### ISSUE TITLE
SCC not revoked after SA deletion

### ISSUE THREAD

**Issue by immens** [openshift/origin#17216]
After deletion of SA/project SCC permissions not revoked

##### Version
oc v3.6.0+c4dd4cf
kubernetes v1.6.1+5115d708d7
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://master.exmplae.com:8443
openshift v3.6.0+c4dd4cf
kubernetes v1.6.1+5115d708d7

##### Steps To Reproduce
1. create project
`# oc new-project sa-priv-test`
2. create SA
`# oc create serviceaccount priv-sa -n sa-priv-test`
3. grant privileges
`# oc adm policy add-scc-to-user privileged -z sa-priv-test -n sa-priv-test`
4. check privilegies
`# oc describe scc privileged`
`<ommited>`
`  Users: <ommited>,system:serviceaccount:sa-priv-test:sa-priv-test`
`<ommited>`
5. delete project
`# oc delete project sa-priv-test`

##### Current Result

`# oc describe scc privileged`
`<ommited>`
`  Users: <ommited>,system:serviceaccount:sa-priv-test:sa-priv-test`
`<ommited>`

##### Expected Result

SA deleted from SCC

**Comment by php-coder** [comment]
This is by design and most likely this behavior won't be changed. It also possible to grant access to SCC to non-existent users by the way.

@pweil- @liggitt Did we document such behavior? What are the benefits?

**Comment by pweil-** [comment]
This is expected behavior and exists because you may be using an identity provider that provisions users on the fly.  In other words, we do not require having a complete view of all potential users but still allow management of those users for the OpenShift concepts.  You may grant or revoke items to the user before they've logged in, including SCC and other access control items within OpenShift.
