### ISSUE TITLE
Flake:  deploymentconfigs with enhanced status [Conformance] should include various info in status

### ISSUE THREAD

**Issue by pmorie** [openshift/origin#17228]
Test flake found in CI testing for https://github.com/openshift/origin/pull/17205:

[Feature:DeploymentConfig] deploymentconfigs with enhanced status [Conformance] should include various info in status [Suite:openshift/conformance/parallel]

Link to build: https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/17205/test_pull_request_origin_extended_conformance_gce/11012/

```
[BeforeEach] [Top Level]
  /tmp/openshift/build-rpm-release/tito/rpmbuild-origincSL9WO/BUILD/origin-3.7.0/_output/local/go/src/github.com/openshift/origin/test/extended/util/test.go:53
[BeforeEach] [Feature:DeploymentConfig] deploymentconfigs
  /tmp/openshift/build-rpm-release/tito/rpmbuild-origincSL9WO/BUILD/origin-3.7.0/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/test/e2e/framework/framework.go:130
STEP: Creating a kubernetes client
Nov  7 22:05:44.350: INFO: >>> kubeConfig: /tmp/cluster-admin.kubeconfig
STEP: Building a namespace api object
Nov  7 22:05:48.877: INFO: EOF
```

**Comment by stevekuznetsov** [comment]
Seems like a client failure? Weird.

**Comment by pmorie** [comment]
Yeah, i saw the same test flake earlier with a more conventional failure.

**Comment by juanvallejo** [comment]
My best guess for this is that it is happening in our custom `createTestingNS` func [https://github.com/openshift/origin/blob/master/test/extended/util/test.go#L201]().

The `EOF` happens after the log info `Building a namespace api object`, but before the expected `About to run a Kube e2e test, ensuring namespace is privileged` message (which is logged in the custom func linked above).

Since `EOF` is the only error message returned, I am assuming that it might be happening while reading a configuration file [here](https://github.com/openshift/origin/blob/master/test/extended/util/test.go#L215) or [here](https://github.com/openshift/origin/blob/master/test/extended/util/test.go#L219)

cc @ncdc  @deads2k

**Comment by juanvallejo** [comment]
@pmorie is this still happening?

Lowering severity for now
