### ISSUE TITLE
DefaultRegistry resolver continues pointing to removed registry

### ISSUE THREAD

**Issue by liggitt** [openshift/origin#1723]
It looks like the default registry resolver only resolves a single time.

Create an image stream, and see that it has no dockerImageRepository:
```
osc create -f test/integration/fixtures/test-image-stream.json
osc get imageStreams test -o json
```

Create a registry, and see that the image stream now has a dockerImageRepository:
```
openshift ex registry --create --credentials=${CERT_DIR}/openshift-registry/.kubeconfig
osc get imageStreams test -o json
```

Delete the registry, service, pods, and replication controllers:
```
osc delete replicationcontrollers docker-registry-1
osc delete pods -l deployment=docker-registry-1
osc delete service docker-registry
osc delete deploymentconfig docker-registry
```

See that the image stream (and new image streams) still remember the old registry:
```
osc get imageStreams test -o json

osc delete imageStreams test
osc create -f test/integration/fixtures/test-image-stream.json
osc get imageStreams test -o json
```

Recreate the registry (which gives it a new IP):
```
openshift ex registry --create --credentials=${CERT_DIR}/openshift-registry/.kubeconfig
```

See that the image stream (and new image streams) still remember the old registry:
```
osc get imageStreams test -o json

osc delete imageStreams test
osc create -f test/integration/fixtures/test-image-stream.json
osc get imageStreams test -o json
```

**Comment by liggitt** [comment]
@ncdc

**Comment by ncdc** [comment]
I believe this was intentional; I'll have to defer to @smarterclayton on this question.

**Comment by smarterclayton** [comment]
Yes, you have to restart the masters.

**Comment by brenton** [comment]
I don't necessarily think this should be a GA blocker as long as our diagnostic tooling can detect this situation and provide guidance.  Changing the registry service IP shouldn't happen too often.

However, this is definitely a bad experience for admins.  My vote would be to leave this issue open or create a card to track this.  It's going to be surprising for admins to have to restart masters because of this.

**Comment by liggitt** [comment]
Definitely looks intentional. In ServiceResolverCache:
```
// only load the value once
```

Still feels weird when so many other parts of the system watch and react

**Comment by brenton** [comment]
Is resolving services expensive enough to require a cache?

**Comment by smarterclayton** [comment]
There really should be no reason to delete the docker registry service ever.

**Comment by brenton** [comment]
I agree with that in practice.  Production environments shouldn't hit this and therefore it's technically not a GA blocker.  However, here's what happens in non-prod environments:

* Admin fat fingers the `osc ex registry --create` arguments (but doesn't realize it)
* Builds are failing and the admin investigates
* Admin realizes the wrong kubeconfig was passed in for the registry creation
* Admin wants to simply rerun the `osc ex registry --create` command with the fixed arguments however since things still exist that won't work.
* Admin cleans everything up the way they expect a clean slate to be
* Builds still don't work because of this issue

**Comment by smarterclayton** [comment]
We should really prevent users from deleting services - rerunning `osadm registry` should be updating the deployment config, and everything should Just Work (tm).

----- Original Message -----

**Comment by smarterclayton** [comment]
This is WAD, but highlights a gap in osadm registry, so it should be an enhancement to that call (in general, we want to be able to update the registry definition and force a deployment).

**Comment by smarterclayton** [comment]
The update of registry has been fixed with apply

**Comment by metal3d** [comment]
I don't know how you applied but even after restarting the master, I've got the same error.

Image are pushed to the right registry,, pulls are made on latest IP...
