### ISSUE TITLE
GCE latest builds: no SRPM

### ISSUE THREAD

**Issue by stevekuznetsov** [openshift/origin#17282]
/kind bug

@smarterclayton our GCE latest RPMbuilds aren't pushing up the SRPMs anymore since the refactor. Is there a strong reason not to?

/cc @arilivigni 

/assign @smarterclayton

**Comment by smarterclayton** [comment]
2 minutes of build time.  That can be changed if necessary for branch pushes

**Comment by stevekuznetsov** [comment]
Yeah I'd expect to have it optional and run during publish jobs

**Comment by arilivigni** [comment]
@smarterclayton are you fixing this since current CentOS-PaaS-SIG is broken.  Can you revert the change you made?

**Comment by smarterclayton** [comment]
Not going to revert, but I can provide a workaround.  However, what context
is using the SRPMs?  Something calling make build-rpms?  Grabbing from
GCS?  Another path?

On Nov 14, 2017, at 5:30 PM, Ari LiVigni <notifications@github.com> wrote:

@smarterclayton <https://github.com/smarterclayton> are you fixing this
since current CentOS-PaaS-SIG is broken. Can you revert the change you made?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/origin/issues/17282#issuecomment-344421344>,
or mute the thread

**Comment by arilivigni** [comment]
Yes a workaround would work as well.  We need a SRPM to feed to CBS in CentOS.  In fact it would be best to build the SRPM every time since we are eventually going to grab the RPMs that get created from the Openshift CI.  Can we actually make this a default?

Currently I am calling the following:
OS_BUILD_ENV_PRESERVE=_output/local hack/env RPM_BUILD_OPTS="--define 'dist .el7'" OS_ONLY_BUILD_PLATFORMS='linux/amd64' hack/build-rpm-release.sh

**Comment by stevekuznetsov** [comment]
@smarterclayton until we get publishing in the works for the pipeline, let's add in the `rpmbuild` step so that the user-facing call that Ari's making still gives him the SRPM?

**Comment by arilivigni** [comment]
What is the command line to build the SRPM now if I choose to?

**Comment by arilivigni** [comment]
@smarterclayton Can you please provide an update and a solution for this issue you broke the API we are using.

**Comment by smarterclayton** [comment]
OS_BUILD_SRPM=y

**Comment by stevekuznetsov** [comment]
@arilivigni can you confirm that using the `OS_BUILD_SRPM=y` option is working for you?

**Comment by smarterclayton** [comment]
SRPMS have been added to the build jobs

https://ci.openshift.redhat.com/jenkins/job/test_branch_origin_extended_conformance_gce/2516/
will be the v3.7.1 SRPM, the release branches all have SRPMs

https://storage.googleapis.com/origin-ci-test/releases/openshift/origin/release-3.8/origin.repo
https://storage.googleapis.com/origin-ci-test/releases/openshift/origin/release-3.7/origin.repo
https://storage.googleapis.com/origin-ci-test/releases/openshift/origin/master/origin.repo

See

https://storage.googleapis.com/origin-ci-test/releases/openshift/origin/v3.7.1/origin.repo

when that job completes
