### ISSUE TITLE
An error occurred while starting the build in Open shift web console

### ISSUE THREAD

**Issue by MichaelHeJianRong** [openshift/origin#17291]
I came across an error when I wanted to build the .net codes on open shift web console.
Error : An error occurred while starting the build.Error resolving ImageStreamTag dotnet:1.0 in namespace openshift: imagestreams "dotnet" not found

What can I do for this error?
![2017-11-14_11-18-45](https://user-images.githubusercontent.com/12246429/32761343-c849154e-c92d-11e7-9ae2-e9328f43a7c5.png)

**Comment by pweil-** [comment]
It looks like this is telling you that you are missing the `dotnet` image stream.  Please review the documentation for build inputs and outputs (below).  If you are still having trouble I would recommend the developer mailing list rather than a bug report.  If you find your build is set up correctly but not working and you believe it is a bug please include build logs and the build config when you open a new ticket.  Thank you

https://docs.openshift.org/latest/dev_guide/builds/index.html
