### ISSUE TITLE
Support rolling tags in image change triggers

### ISSUE THREAD

**Issue by kargakis** [openshift/origin#17380]
I want to trigger rollouts from image stream and not image stream tag updates. By pushing continuously to an ImageStreamTag we cannot trivially perform rollbacks to previous revisions in case of a broken image (`oc rollout undo` is essentially broken).

cc @smarterclayton @tnozicka @mfojtik 

/sig master

**Comment by kargakis** [comment]
> oc rollout undo is essentially broken

Ok, this is not true since we resolve the image to the full path.

**Comment by kargakis** [comment]
I would still like to version image stream tags based on git commits.

**Comment by tnozicka** [comment]
I am not sure about this but let's see what others think. Tags are just labels and DC always resolve them to sha, so that way rollback/new pods/.. all work with exactly the same image.

You can have multiple tags with commits, why not, just then push the one you want also to latest and it will get deployed. @mfojtik I think this is similar to what we've turned down on last grooming.

**Comment by kargakis** [comment]
Yeah, we need a process in place that promotes images.
