### ISSUE TITLE
Image change triggers do not work with apply,replace,et al

### ISSUE THREAD

**Issue by kargakis** [openshift/origin#17404]
Known issue but I stumbled across it today in our CI cluster and I was wondering if this can ever be solved somehow and what do we suggest to customers.

For clarity, the issue is that we have checked in git DCs with image change triggers and the changes caused by the triggers inside the cluster (image pullspec is resolved in `dc.spec.containers.image`) are never reflected back in git. Thus, it's impossible for us to easily automate getting the manifests from git every time there is an update and apply them in the cluster because we end up overwritting the image field.

cc: @smarterclayton @tnozicka @mfojtik @stevekuznetsov 
/sig master

**Comment by kargakis** [comment]
@smarterclayton is it possible to blacklist/whitelist fields with server-side apply?

**Comment by tnozicka** [comment]
Upstream uses an annotation with serialization of the last applied configuration, that should help us to solve it. I don't think triggers are the only issue; seems like any defaulting field or e.g. image plugin present the same challenge.

**Comment by stevekuznetsov** [comment]
Hmmm maybe _this_ is what was screwing up all of our image resolution ...

**Comment by smarterclayton** [comment]
Don't use triggers if you're driving config from git....

**Comment by smarterclayton** [comment]
No, it won't be possible to blacklist fields.  If you're doing a git driven config from tags, you should relying on dynamic resolution (at the pod level) via image lookup, not triggers.

**Comment by smarterclayton** [comment]
Actually, if the initial deployment / obj has a nil empty image that would
allow apply to work

**Comment by kargakis** [comment]
> Actually, if the initial deployment / obj has a nil empty image that would allow apply to work

The DC image is update to an empty field because we allow it but the RC never runs because that is invalid:
```
message: 'ReplicationController "sinker-37" is invalid: spec.template.spec.containers[0].image:
      Required value'
    reason: ReplicationControllerCreateError
```

**Comment by smarterclayton** [comment]
The trigger should be filling it out (if you want triggers).  Also,
starting in 1.8 image may be empty on everything except pods.

On Nov 21, 2017, at 7:19 PM, Michalis Kargakis <notifications@github.com>
wrote:

Actually, if the initial deployment / obj has a nil empty image that would
allow apply to work

The DC image is update to an empty field because we allow it but the RC
never runs because that is invalid:

message: 'ReplicationController "sinker-37" is invalid:
spec.template.spec.containers[0].image:
      Required value'
    reason: ReplicationControllerCreateError

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/origin/issues/17404#issuecomment-346203388>,
or mute the thread

**Comment by tnozicka** [comment]
I don't think this is related only to apply. The issue is the whatever way user manages to set image to "" (or anything in general) and there is a valid trigger for it we should first resolve the trigger and rewrite the image field to that value. We somehow manage to deploy RC when the state is image="" - that seems like a bug in DC controller.

**Comment by kargakis** [comment]
> We somehow manage to deploy RC when the state is image="" - that seems like a bug in DC controller.

I think I also noticed that. Shouldn't be hard to reproduce.

**Comment by tnozicka** [comment]
I have a fix for DC but the issue is that it won't get reconciled (resolved) again. See https://github.com/openshift/origin/issues/17535
