### ISSUE TITLE
Question - SCC restricted is reset during upgrade

### ISSUE THREAD

**Issue by DanyC97** [openshift/origin#17453]
Before upgrading my Origin env from 1.5 to 3.6 (1.6) i had my default scc `restricted` set to 

```
oc get scc/restricted
NAME         PRIV      CAPS      SELINUX     RUNASUSER   FSGROUP     SUPGROUP   PRIORITY   READONLYROOTFS   VOLUMES
restricted   true      []        MustRunAs   RunAsAny    MustRunAs   RunAsAny   <none>     false            [configMap downwardAPI emptyDir hostPath persistentVolumeClaim secret]
```
After the upgrade it was reset (lost `hostPath`) to 

```
oc get scc/restricted
NAME         PRIV      CAPS      SELINUX     RUNASUSER   FSGROUP     SUPGROUP   PRIORITY   READONLYROOTFS   VOLUMES
restricted   true      []        MustRunAs   RunAsAny    MustRunAs   RunAsAny   <none>     false            [configMap downwardAPI emptyDir persistentVolumeClaim secret]
```
Anyone can help me understand if this is the expected behavior and if so where is that covered (code, doc) so i can understand better?

I know that ideally i should have my own sa with my own extended scc rather than rely on the default one.

**Comment by php-coder** [comment]
> Anyone can help me understand if this is the expected behavior

Yes, this is expected behavior.

> and if so where is that covered (code, doc) so i can understand better?

During upgrade, `oc adm policy reconcile-sccs` is being executed and ["set all SCC policies to the default values but retain any additional users, groups, labels, and annotations as well as priorities you may have already set"](https://docs.openshift.org/latest/admin_guide/manage_scc.html#updating-security-context-constraints). This is documented in the section about SCC.

**Comment by DanyC97** [comment]
much thanks @php-coder !!!
