### ISSUE TITLE
TestTriggerController is racy

### ISSUE THREAD

**Issue by mfojtik** [openshift/origin#17472]
Seen here: https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/17469/test_pull_request_origin_unit/6070/

Not going to paste the 2k+ lines in output, but the race detector detected a race in that test.

@smarterclayton not sure if this is something I broke in DeepCopy() PR or something that is broken for long time...

**Comment by smarterclayton** [comment]
So I have never seen a race here, so my guess is deep copy isn’t actually copying, or we’re using it incorrectly.

**Comment by smarterclayton** [comment]
I can’t find an earlier failure before

https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/17457/test_pull_request_origin_unit/6063/

What changed in master around that time?

On Nov 27, 2017, at 10:00 AM, Michal Fojtik <notifications@github.com>
wrote:

@smarterclayton <https://github.com/smarterclayton> i switched
<https://github.com/openshift/origin/pull/17444/commits/d4859926e1725c6f685e38aeff2dc4acee216111>
the trigger controller from interface{} to runtime.Object, wonder if that
messed it up...

But I never seen this failure in that PR.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/origin/issues/17472#issuecomment-347208073>,
or mute the thread

**Comment by sjenning** [comment]
3 new ones:

https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/17143/test_pull_request_origin_unit/6172/
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/17314/test_pull_request_origin_unit/6171/
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/17299/test_pull_request_origin_unit/6170/

100% hit rate in the last 3 runs

https://openshift-gce-devel.appspot.com/builds/origin-ci-test/pr-logs/directory/test_pull_request_origin_unit

**Comment by smarterclayton** [comment]
Found it - i think a bug in the test, never triggered before because everything ran faster/slower

**Comment by mfojtik** [comment]
@smarterclayton not sure if related, but https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/17492/test_pull_request_origin_unit/6166/ is another race...

**Comment by smarterclayton** [comment]
Not related, should be easy for someone to fix.
