### ISSUE TITLE
Can't open my deployed nodejs app

### ISSUE THREAD

**Issue by kaveh981** [openshift/origin#17633]
Just created a very simple hello world app using node put it on github and deployed it on openshift. pod created and server running fine but when I browse [the route](http://kavehnode-kaveh.193b.starter-ca-central-1.openshiftapps.com/) which I could find it in Application>>routes menu it says:
```
Application is not available

The application is currently not serving requests at this endpoint. It may not have been started or is still starting.
```
I guess I'm using the latest version of openshift since just created an account.

**Comment by pweil-** [comment]
@kaveh981 unfortunately this is not the best location for general support.  I would suggest stack overflow or the dev mailing list.

That said, usually when a route is showing unavailable for the app it is because endpoints are not available.   I would take a look at the following:

1.  Your service is using the right selector
2.  `oc get endpoints <service name>` shows the ips of the pods
3.  the pod is running and serving the traffic you think
4.  the route is pointing to the correct service/port

**Comment by kaveh981** [comment]
@pweil- ok right for the next time
so the pod is running as the screen shot shows and i put a console.log in the code to show me on which ip and port is it running basically this is the whole code just for test:
```
var express = require('express');
var app = express();
app.get('/', function (req, res) {
  res.send('Hello World!');
});
var server_port = process.env.OPENSHIFT_NODEJS_PORT || 8080
var server_ip_address = process.env.OPENSHIFT_NODEJS_IP || '127.0.0.1'
 
app.listen(server_port, server_ip_address, function () {
  console.log( "Listening on " + server_ip_address + ", port " + server_port )
});

```
<img width="1033" alt="screen shot 2017-12-07 at 1 24 47 pm" src="https://user-images.githubusercontent.com/12487716/33731845-67da9958-db52-11e7-8bcd-41315ca45f1d.png">

it means the service should be running and in the root route i should be expecting to get " Hello World!"

not sure what i missing 
Thanks!

**Comment by kaveh981** [comment]
I'll take this to overflow

**Comment by HimajaMachavaram** [comment]
can I know if this is fixed

**Comment by mpandav** [comment]
@kaveh981I'm facing the exactly same problem. Can I know the solution if this has been resolved?
