### ISSUE TITLE
Patternfly Icons stopped working in templates

### ISSUE THREAD

**Issue by ctron** [openshift/origin#17745]
In the past (and according to documentation is still is) possible to use Patternfly icons in templates:
See: https://docs.openshift.org/latest/dev_guide/templates.html#writing-description – Number 6

##### Version
oc v3.6.1+008f2d5
kubernetes v1.6.1+5115d708d7
features: Basic-Auth GSSAPI Kerberos SPNEGO

##### Steps To Reproduce
1. Create template.xml with "pficon-"
2. Process template with Web UI

##### Current Result

Shows unknown unicode icon:

![image](https://user-images.githubusercontent.com/202474/33944644-0fea45d4-e01d-11e7-9850-2e0f39da7994.png)

##### Expected Result

Show correct patternfly icon

##### Additional Information

None

**Comment by rhamilto** [comment]
@ctron, try using "pficon pficon-*" in your template.  The icon won't render without the standalone "pficon" being specified, too.

**Comment by jwforres** [comment]
we should fix either our docs or the patternfly docs to make it clear that the extra class is needed

**Comment by ctron** [comment]
Adding "pficon" does not fix this. I already tried that.

**Comment by rhamilto** [comment]
@ctron, it's possible the icon you're trying to use isn't part of the PatternFly distribution included in the code.  @jwforres mentioned you're running OpenShift v3.6.x, which should include PatternFly v3.24.0.  Unfortunately, there isn't an easy way to see which icons are included in that specific version of PatternFly.  Can you supply the name of the icon you're trying to use?  Additionally, can you supply a copy of the template you're authoring?

**Comment by ctron** [comment]
I am using `pficon-topology`. But I tried a few others. None worked. I haven't tried all of course.

The template is available on GitHub: https://github.com/ctron/hono/blob/feature/support_s2i/openshift/hono.yml

**Comment by rhamilto** [comment]
D'oh!  Sorry, @ctron.  This is indeed a bug.  We've got a CSS specificity issue with the different icon fonts: [Font Awesome](http://fontawesome.io/icons/) ("fa"), PatternFly ("pficon"), and [OpenShift](https://rawgit.com/openshift/openshift-logos-icon/master/demo.html) ("font-icon").  It looks like [we put in a fix so that Font Awesome would work with OpenShift](https://github.com/openshift/origin-web-console/blob/0ff66a1afde90ba50e379747651912b3e2d0fe1c/app/views/directives/_custom-icon.html#L1), but did not apply the same fix for PatternFly.  Unfortunately this means you're unable to use PatternFly icons until the issue is fixed.  :(  

@jwforres, in reviewing the code back to v1.2.0, it's possible pficons have never worked.

**Comment by jwforres** [comment]
Ok I don't see us backporting this more than 1 release if it wasn't working
at all before, I think we just assumed it worked because the font was there.
@rhamilto we should update the previous enterprise branches of the docs
that claimed it worked and remove that reference.  For 3.7 if its a small
change we should backport to that release.  And then a fix for master of
course.

**Comment by rhamilto** [comment]
> Ok I don't see us backporting this more than 1 release if it wasn't working
at all before, I think we just assumed it worked because the font was there.
@rhamilto we should update the previous enterprise branches of the docs
that claimed it worked and remove that reference.

Done.  https://github.com/openshift/openshift-docs/pull/6809

> For 3.7 if its a small change we should backport to that release. 

The solution is relatively simple, but it is spread across all three repos, so it's not easy to backport.  As a result, I'm assuming we don't want to bother with a backport.
