### ISSUE TITLE
Openshift Origin Multi Master Setup: how many masters must be online

### ISSUE THREAD

**Issue by helletheone** [openshift/origin#17854]
We have a Multi-Master Setup with the following Setup:

1 LB
3 Master
3 Nodes

We test the Failover from our Cluster and we fail .... 
If 2 Masters are offline the api dont deliever any Informations back to the cli
It looks like the Cluster is down but the webconsole is there... 

Any Ideas?

##### Version
oc v3.6.1+008f2d5
kubernetes v1.6.1+5115d708d7
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://lb.example.de:8443
openshift v3.6.1+008f2d5
kubernetes v1.6.1+5115d708d7

##### Steps To Reproduce
1. Shutdown 2 Master Servers
2. try oc get node oder oc get pods
3. No Feedback from the Console

**Comment by php-coder** [comment]
>  If 2 Masters are offline the api dont deliever any Informations back to the cli

This is expected behavior. It happens because every master also has etcd instance. etcd uses [RAFT](https://raft.github.io/) algorithm that is responsible for persisting the data. RAFT requires to have a majority of the nodes to be available, otherwise it doesn't provide you access to the data:

> Consensus involves multiple servers agreeing on values. Once they reach a decision on a value, that decision is final. Typical consensus algorithms make progress when any majority of their servers is available; for example, a cluster of 5 servers can continue to operate even if 2 servers fail. If more servers fail, they stop making progress (but will never return an incorrect result).

In other words, when you turn down 2 masters, you loose the majority and etcd stopped to response. Hence, API server stopped working too as it need the data from etcd.

@helletheone while you can keep asking here, it's not the best place actually. We're trying to use GitHub for development-related issues, all other questions better to [ask on StackOverflow](https://stackoverflow.com/questions/tagged/openshift-origin) or [mailing list](http://lists.openshift.redhat.com/openshiftmm/listinfo/users). Thank you!
