### ISSUE TITLE
Project-local image streams not showing up in catalog

### ISSUE THREAD

**Issue by jerboaa** [openshift/origin#17852]
When importing an ImageStream into a local project the ImageStream does not show up in the web console's catalog. Not even when "Select from Project" is being clicked.

##### Version

    openshift v3.7.0+7ed6862
    kubernetes v1.7.6+a08f5eeb62

##### Steps To Reproduce
1. `oc project myproject`
2. `oc create -f https://raw.githubusercontent.com/redhat-developer/s2i-dotnetcore/master/dotnet_imagestreams_centos.json`
3. Attempt to locate the builder image `.NET Core` in the catalog. It's not present.

##### Current Result
No way to use 3.6.0 web console's "Try It" feature on a local image stream. In 3.6.0 there was: "Add to Project" => ".NET Core (latest)" => select => Give it some name => Click "Try It".

It appears the "Select from Project" wizard only expects templates?
![screenshot from 2017-12-18 12-18-55](https://user-images.githubusercontent.com/357222/34103669-e515f568-e3ed-11e7-8bf8-44695335ecba.png)

##### Expected Result
Image stream shows up in catalog and there is a "Try It" feature. I'd also expect ".NET Core" image stream items to show up in the "Select from Project" wizard.

**Comment by jerboaa** [comment]
FWIW this used to work fine with:

     OpenShift Master:  v3.6.0+c4dd4cf
     Kubernetes Master: v1.6.1+5115d708d7

**Comment by jerboaa** [comment]
$ oc describe is dotnet
    Name:			dotnet
    Namespace:		myproject
    Created:		About an hour ago
    Labels:			<none>
    Annotations:		openshift.io/display-name=.NET Core Builder Images
                            openshift.io/image.dockerRepositoryCheck=2017-12-18T11:14:18Z
    Docker Pull Spec:	172.30.1.1:5000/myproject/dotnet
    Image Lookup:		local=false
    Unique Images:		4
    Tags:			4

    2.0 (latest)
      tagged from registry.centos.org/dotnet/dotnet-20-centos7:latest

      Build and run .NET Core 2.0 applications on CentOS 7. For more information about using this builder image, including OpenShift considerations, see https://github.com/redhat-developer/s2i-dotnetcore/tree/master/2.0/build/README.md.
      Tags: builder, .net, dotnet, dotnetcore, rh-dotnet20
      Supports: dotnet:2.0, dotnet
      Example Repo: https://github.com/redhat-developer/s2i-dotnetcore-ex.git

      * registry.centos.org/dotnet/dotnet-20-centos7@sha256:95412c436e23a0e318a9baeb99f1a0be45bcdb84f47583b12281953c26914e9c
          13 minutes ago

**Comment by jerboaa** [comment]
@bparees Thoughts?

**Comment by bparees** [comment]
@spadgett @jwforres would be the ones to ask on this.

**Comment by buehner** [comment]
same problem here!
custom s2i image showed up in v3.6.0, but does not show up in the catalog in v3.7.0

**Comment by spadgett** [comment]
This was a functional gap when we moved to the new catalog in 3.7. The new catalog was not in the context of a project, so image streams from a specific project won't show up. Select from Project unfortunately only shows templates as you've found.

The problem has been fixed in 3.9 when we added back the ability to browse the catalog from within a specific project in https://github.com/openshift/origin-web-console/pull/2563. Due to the size of the change, it has not been back-ported to 3.7.

For now, you'll need to either

1. Import the image stream into the `openshift` namespace.
2. Use `oc new-app` to create your app.
3. Select a different builder, then use the web console build config editor to change the builder to the one from your project. (Image Configuration -> Build From -> Image Stream Tag)

/assign
/close

Closing as this has been fixed in 3.9.
