### ISSUE TITLE
oc cluster status = OpenShift cluster is not running but the Cluster is running... 

### ISSUE THREAD

**Issue by helletheone** [openshift/origin#17851]
We Setup a HA-Setup with 7 Nodes:

1 LB
3 Masters
3 Nodes

the Cluster is running. Webconsole, Router, Registry etc. is running.
But i got this Error:

[root@master1 ~]# oc cluster status
Error: OpenShift cluster is not running

i dont know why

##### Version
oc v3.6.1+008f2d5
kubernetes v1.6.1+5115d708d7
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://lb.example.de:8443
openshift v3.6.1+008f2d5
kubernetes v1.6.1+5115d708d7

##### Steps To Reproduce
1. oc cluster status

##### Current Result
Error: OpenShift cluster is not running

**Comment by php-coder** [comment]
@helletheone Looks like you have a fully-featured OpenShift server that was configured and run with commands/scripts other than `oc cluster up`. I don't know the details of your installation, but most likely you are using systemd, so the following commands should help: `systemctl status origin-master` (on masters) and `systemctl status origin-node` (on nodes).

`oc cluster status` and `oc cluster down` only work for all-in-one OpenShift clusters that was run by `oc cluster up` command.

I'm adding @openshift/sig-developer-experience in order to correct me if I'm wrong in my assumptions.

**Comment by helletheone** [comment]
systemctl status origin-master
● origin-master.service
   Loaded: masked (/dev/null; bad)
   Active: inactive (dead)


@php-coder i hope you are right ;)

**Comment by php-coder** [comment]
@helletheone Could you close the issue then?

**Comment by helletheone** [comment]
./close
