### ISSUE TITLE
Re-enable `oc cluster up --service-catalog --version=v3.7.0` test

### ISSUE THREAD

**Issue by jim-minter** [openshift/origin#17867]
```
oc cluster up --service-catalog --loglevel=2 --image=docker.io/openshift/origin --version=v3.7.0
...
-- Installing service catalog ... 
FAIL
   Error: could not reconcile service catalog cluster role admin
   Caused By:
     Error: the server could not find the requested resource
```

**Comment by jim-minter** [comment]
I think that master `oc` is trying to GET the admin cluster role via /apis/rbac.authorization.k8s.io/v1/clusterroles/admin - which doesn't work on 3.7 ?

**Comment by jim-minter** [comment]
https://ci.openshift.redhat.com/jenkins/view/All/job/test_branch_origin_extended_clusterup/61/console

**Comment by jim-minter** [comment]
@coreydaley fyi

**Comment by jim-minter** [comment]
Adding @liggitt - 1.9 rebase breakage?

**Comment by liggitt** [comment]
Looks like the test hardcodes 3.7.0, which is not the previous version for 3.9 dev. Hardcoding a moving target into the test seems pretty fragile. 

It's clear that `cluster up` is not currently designed to support multiple versions of the cluster setup… it mostly lucked into that working previously.

**Comment by jim-minter** [comment]
Also adding @bparees

**Comment by bparees** [comment]
> Looks like the test hardcodes 3.7.0, which is not the previous version for 3.9 dev. Hardcoding a moving target into the test seems pretty fragile.

@liggitt we are moving to N-1 support for cluster up and we have added explicilt logic to attempt to make this more supportable (and may have to continue to add more such logic).

This aligns with what the oc client is supposed to support.  I realize the 3.7 is not technically "N-1" from v3.9 but i have started several threads on this subject trying to get to the bottom of what we're actually going to support there.  If the statement really is that v3.9 oc clients will only work back to v3.8 clusters, then the master team needs to inform the CDK team that they are going to be broken since they are likely assuming N-1 means "effective versions".

**Comment by jim-minter** [comment]
#17887 will disable this test for now.  I'm repurposing this issue to re-enable the test.  I don't know who the assignee should be.

**Comment by bparees** [comment]
I'm converting this to a blocking bug since we don't seem to have a good process for ensuring github issues get resolved before shipping.
https://bugzilla.redhat.com/show_bug.cgi?id=1530069
