### ISSUE TITLE
'oc describe -f <file>" requires that object to exist in current project

### ISSUE THREAD

**Issue by tomcooperca** [openshift/origin#17870]
Using `oc describe -f myTemplateFile.yml` with the filename option fails if the object described in the filename does not exist as the corresponding Openshift object (for example, a template). Either the usage output of `oc describe` should clarify this or possibly remove the `--filename` option altogether if that's not the intended use.

##### Version
```
oc v3.6.1+008f2d5
kubernetes v1.6.1+5115d708d7
features: Basic-Auth GSSAPI Kerberos SPNEGO

openshift v3.6.173.0.21
kubernetes v1.6.1+5115d708d7
```
##### Steps To Reproduce
1. Execute `oc describe -f anyTemplate.yml` file without first creating it inside a project (omit `oc create -f anyTemplate.yml`.

##### Current Result
```
Error from server (NotFound): templates.template.openshift.io "template-formal-name" not found
```
##### Expected Result
Detailed output that normally displays from `oc describe TYPE [NAME_PREFIX | -l label]`

**Comment by juanvallejo** [comment]
Because describe outputs properties about resources that (for the most part) only exist once an object has been created, it would not make much sense to infer an offline output when the `-f ...` flag is used. I believe other commands already work this way, with a few commands providing an extra `--local` option which then explicitly avoids making remote calls / checking if a resource exists in the cluster.
