### ISSUE TITLE
create a --mobile flag in the oc cluster up command

### ISSUE THREAD

**Issue by philbrookes** [openshift/origin#18089]
## Motivation

The Red Hat Mobile team is developing a set of Mobile Services, Tools & UI (https://github.com/aerogear/mobile-core) that leverages the OpenShift platform. In order to encourage developers of mobile applications to use a combination of the Mobile Core and OpenShift to run the back-end applications for the mobile apps we would like to make it as easy as possible to get a local copy of their local OpenShift cluster configured for use by a mobile developer.

## Problem

It is currently quite an involved process for a mobile app developer to setup OpenShift locally with the service broker, Ansible service broker and the Mobile Core extension configured. This will have a negative impact on adoption of the Mobile Core product, and use of the OpenShift platform with mobile application developers.

## Solution

Running an `oc cluster up --mobile=true` will provision the local oc cluster as if the `--service-broker` flag were present. 

The ansible-service-broker will need to be reconfigured to read APB images from the `aerogearcatalog` dockerhub org (though this will be configurable by an environment variable). 

The OpenShift configuration will also be modified to enable the Mobile UI extension inside the OpenShift web UI.

The OpenShift cluster will have a Custom Resource Definition added to it, as defined in this template:
https://raw.githubusercontent.com/aerogear/mobile-cli/master/artifacts/mobileclient_crd.yaml

In order for a mobile application developer to get a local cluster running with everything they need to start local development running should be:
```sh
oc cluster --mobile=true
```
​

**Comment by matzew** [comment]
This would be very handy to bring in the mobile services !

**Comment by david-martin** [comment]
@philbrookes 1 potential point of confusion that might come up is what 'runs on top of the OpenShift platform' for mobile? What is the Mobile Core?.
Could we rephrase that better?
There is nothing mobile that 'runs' per-se. There is no Mobile Core component.
Mobile Services can run, but only after a developer provisions the ones they want.

Doing Mobile things on OpenShift will require:
* OpenShift Ansbile Broker (in proposal)
* Mobile UI extension to be enabled (in proposal)
* Mobile Client Custom Resource Definition (CRD) (Is this still the route we're proposing? If yes, this should be part of the proposal)

**Comment by philbrookes** [comment]
Thanks @david-martin I have updated the description now, let me know if I have overlooked anything.

**Comment by david-martin** [comment]
> The Red Hat Mobile team is developing a Mobile Core (https://github.com/aerogear/mobile-core) which runs on top of the OpenShift platform

@philbrookes would something like this be better?

"The Red Hat Mobile team is developing a set of Mobile Services, Tools & UI (https://github.com/aerogear/mobile-core) that leverages the OpenShift platform."

**Comment by johnfriz** [comment]
@philbrookes - is there any work in progress that could be linked to here to provide a concrete example of what we want to do here?

**Comment by david-martin** [comment]
@johnfriz  @philbrookes related work that this could follow the pattern of.
Metrics & Logging: https://github.com/openshift/origin/blob/master/pkg/oc/bootstrap/docker/up.go#L1089-L1131
Which run the associated ansible playbooks
* https://github.com/openshift/openshift-ansible/tree/master/roles/openshift_logging
* https://github.com/openshift/openshift-ansible/tree/master/roles/openshift_metrics

**Comment by wei-lee** [comment]
+1

**Comment by php-coder** [comment]
Could it be implemented as a plugin to Minikube?

CC @openshift/sig-developer-experience

**Comment by philbrookes** [comment]
@php-coder I don't think that's possible at the moment as it requires the ansible-service-broker, which - as I understand - requires OpenShift?

**Comment by david-martin** [comment]
@bparees What is the core mission of cluster up?
Would there be value in taking parts of what this proposal is and making them available in a more generic way?

For example:
* --ansible-broker-org - Which docker hub org to point to for the openshift ansible broker
* --ui-extension - A path or config file that for a UI extension on the local filesystem

**Comment by pweil-** [comment]
Agree that this is more than we probably want to support in that command on the core OpenShift side.  Will leave this open for discussion of the question above.

**Comment by jorgemoralespou** [comment]
@david-martin this should be implemented in minishift, but if OC cluster up is still desired, you can look into https://github.com/openshift-evangelists/oc-cluster-wrapper which provides a plug-in mechanism to oc cluster for doing what you ask

**Comment by bparees** [comment]
> @bparees What is the core mission of cluster up?

standing up a basic openshift cluster as quickly/easily as possible.

Service catalog was added to cluster up because the service catalog was/is the default experience for openshift, so it's considered a fundamental part of the cluster (along w/ things like the router, registry, etc).

Logging and metrics install/config is something that was added to cluster up but probably exceeds what should have been done in the core cluster up logic.

> Would there be value in taking parts of what this proposal is and making them available in a more generic way?

a more generic way, yes, but in my mind that more generic way is "so you've got an openshift cluster w/ admin access...  great, point our playbooks to it and we'll setup the mobile experience".  ie not something specific to the cluster up workflow.

**Comment by david-martin** [comment]
@philbrookes based on what @pweil- @bparees and @jorgemoralespou are saying, this issue will probably be closed.

But there are some takeaways:
* see if https://github.com/openshift-evangelists/oc-cluster-wrapper could give some benefit over our current approach (evoking oc cluster up and various playbooks)
* see if we can push forward with a minishift plugin/environment that includes the broker, and the mobile ui extension

Also, I'm thinking there could be value in extending our playbooks to make them work with remote clusters (like metrics & logging do) rather than just with a local cluster.

@philbrookes Would this be your take on it too?

**Comment by jorgemoralespou** [comment]
If you're looking into long term sustainable solution, that can provision a
local cluster or a cluster in the cloud, then ansible is the way to go.

If you just want a way to spin up a cluster and configure it with the
mobile UI in order to work and develop, then plugins in oc-cluster or
addons in minishift are easy to create.

**Comment by philbrookes** [comment]
@david-martin we have already made a lot of progress with a [minishift mobile core addon](https://github.com/aerogear/minishift-mobilecore-addon). 

It does seem that oc-cluster-wrapper would be the best alternative, if this idea is not suitable.

**Comment by bparees** [comment]
closing based on the recommendations to either do this in minishift, or use the oc cluster wrapper, but it's "too big" to fit into the core cluster up mission.
