### ISSUE TITLE
Make immortal namespace  configurable

### ISSUE THREAD

**Issue by wanghaoran1988** [openshift/origin#18180]
Feature Request:

We are adding more projects after a fresh installation, logging, kube-service-catalog(if we enable this in ansible) openshift-console ..., and currently the immortal namespace are hard coded, when we enable like service-catalog in openshift ansible, we should make sure this is a immotal namespace, also some customer want to preserve some projects that created themself, and I think we can make this an configuration item in the master-config.yaml 

@mfojtik @liggitt WDYT?

**Comment by liggitt** [comment]
the current immortal namespaces are designated as such because they house system controllers that would be required in order to recreate those namespaces.

it is not a catch-all for "important namespaces". it is only to prevent deleting namespaces that would require going to etcd to restore cluster operations

/close
