### ISSUE TITLE
When only set the quota but not set the limit range, it couldn't be deployed.

### ISSUE THREAD

**Issue by YueHuali** [openshift/origin#18434]
Steps To Reproduce
1. Set quota
2. Deploy any one like nginx

My version:
openshift v1.4.1

BTW, I couldn't install the latest version in my host.

**Comment by wtrocki** [comment]
Cannot replicate that on current version of OpenShift. 
Can you provide version and actual error you are getting?

**Comment by jwforres** [comment]
It sounds like you are hitting expected behavior because you have not explicitly set requests / limits on your pod template.

If you want defaulting behavior, you must have a limit range.  Adding quota that affects resources like cpu and memory without also having a limit range generally creates a subpar user experience.

If you want quota on cpu / mem but do not want the defaulting behavior of a limit range, then you must explicitly configure resource constraints on every deployment / statefulset / job / build / etc that you create in that namespace (whichever ones are covered by the scope of your quota).
