### ISSUE TITLE
Routes should support Generation and ObservedGeneration

### ISSUE THREAD

**Issue by tnozicka** [openshift/origin#18467]
> If the primary resource your controller is reconciling supports ObservedGeneration in its status, make sure you correctly set it to metadata.Generation whenever the values between the two fields mismatches.
> 
> This lets clients know that the controller has processed a resource. Make sure that your controller is the main controller that is responsible for that resource, otherwise if you need to communicate observation via your own controller, you will need to create a different kind of ObservedGeneration in the Status of the resource.
https://github.com/kubernetes/community/blob/master/contributors/devel/controllers.md

It's hard to build controllers on top of it otherwise because they have no way of reporting what generation they have already reconciled. And you end up with flaky tests full of sleep(magic_number).

Should be an easy change: 
1. In admission set `generation==1` on Create.
1. In admission raise `generation` for every Spec change.
1. Set `status.observedGeneration` to `generation` at the end of sync loop if they don't already match.

@openshift/sig-networking @smarterclayton

**Comment by smarterclayton** [comment]
For routes it’s a bit more complex.  Routes can have multiple controllers.
The status field is subdivided.  We also are very judicious about routers
setting status because it can generate write storms.

We should add generation for sure.  We should probably output generation
into the template for debugging.  Not sure how much further we should go.

On Feb 5, 2018, at 11:43 PM, Tomáš Nožička <notifications@github.com> wrote:

If the primary resource your controller is reconciling supports
ObservedGeneration in its status, make sure you correctly set it to
metadata.Generation whenever the values between the two fields mismatches.

This lets clients know that the controller has processed a resource. Make
sure that your controller is the main controller that is responsible for
that resource, otherwise if you need to communicate observation via your
own controller, you will need to create a different kind of
ObservedGeneration in the Status of the resource.
https://github.com/kubernetes/community/blob/master/contributors/devel/controllers.md

It's hard to build controllers on top of it otherwise because they have no
way of reporting what generation they have already reconciled. And you end
up with flaky tests full of sleep(magic_number).

Should be an easy change:

   1. In admission set generation==1 on Create.
   2. In admission raise generation for every Spec change.
   3. Set status.observedGeneration to generation at the end of sync loop
   if they don't already match.

@openshift/sig-networking
<https://github.com/orgs/openshift/teams/sig-networking> @smarterclayton
<https://github.com/smarterclayton>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/origin/issues/18467>, or mute the thread

**Comment by tnozicka** [comment]
I am fine with having at least Generation as that will provide a base for higher level controllers to report their own observedGeneration (using an annotation). 

I guess observedGeneration wouldn't really mean that much for Routes as the controller doesn't do a lot that's externally visible as the admission is set by the appropriate router.

On a side note, if I recall correctly, I couldn't figure out a way to find out if Route is exposed. I could find out that it's admitted but that doesn't mean its exposed. Am I missing something or do we need to report such status better?
