### ISSUE TITLE
can we get `ist` as shorhand for imagestreamtag

### ISSUE THREAD

**Issue by stevekuznetsov** [openshift/origin#18506]
Works:

```
$ oc get is
```

Does not:

```
$ oc get ist
```

Every time I need to type out the (lengthy) `ImageStreamTag` I cry inside.

/cc @deads2k @bparees @smarterclayton

**Comment by kargakis** [comment]
```
oc get istag
```

**Comment by kargakis** [comment]
^works

**Comment by jwforres** [comment]
@stevekuznetsov sufficient?  close?

**Comment by stevekuznetsov** [comment]
That's still two extra chars :D

**Comment by smarterclayton** [comment]
istag

On Feb 7, 2018, at 8:34 AM, Steve Kuznetsov <notifications@github.com>
wrote:

Works:

$ oc get is

Does not:

$ oc get ist

Every time I need to type out the (lengthy) ImageStreamTag I cry inside.

/cc @deads2k <https://github.com/deads2k> @bparees
<https://github.com/bparees> @smarterclayton
<https://github.com/smarterclayton>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/origin/issues/18506>, or mute the thread
