### ISSUE TITLE
Feedback on `oc new-app` behavior for deploying from local code

### ISSUE THREAD

**Issue by containscafeine** [openshift/origin#18571]
If I need to deploy an application with from local source code, I need to follow the following steps:

`oc new-app  <path to code>`
This will detect the language, choose a builder image, and deploy the application from the "origin" remote found at the path. _this does not deploy the code that's there at the path_
If I need to deploy the local code, I need to run an additional `oc start-build --from-dir=<path>` again for OpenShift to package my local contents and deploy those in the application.

I understand that this behavior is well documented, etc, but this is very unintuitive, imo.

- What if I do not want to deploy the origin remote, or heck, I don't have an origin remote, I just want to do a deployment from my local code, how do I do that?

Also, if I had to do a deployment from a git repo, I would mention it already with `oc new-app <git repo>`, why would I provide a local path, wanting OpenShift to detect my origin and deploy from there, and not my local code.

Like I wrote earlier, this behavior seems very unintuitive to me, and a couple of friends who use this. Just wanted to give some feedback :)

**Comment by php-coder** [comment]
@openshift/sig-developer-experience

**Comment by bparees** [comment]
> What if I do not want to deploy the origin remote, or heck, I don't have an origin remote, I just want to do a deployment from my local code, how do I do that?

As you note, you can always run a binary build against the buildconfig that is produced, even if the buildconfig references your remote repo.

if you use oc new-build, you can do `oc new-build --binary` to avoid building/deploying your remote code.

> Also, if I had to do a deployment from a git repo, I would mention it already with oc new-app <git repo>, why would I provide a local path, wanting OpenShift to detect my origin and deploy from there, and not my local code.

because new-app predates the ability to run binary builds, meaning when it was created, the *only* way for it to work was if you had a valid git remote and the buildconfig had to be defined in terms of that git remote.

Changing the behavior now would break compatibility.

Things we could conceivably do here: add the --binary flag to `oc new-app`.  However new-build does not do language discovery when you indicate you want a binary build (we assume the source isn't presently available) so you have to explicitly indicate the builder image you want to use in that case.

**Comment by bparees** [comment]
also if you remove your .git folder, new-app will create a binary build for you.  I realize that may not be an ideal solution but fyi.

converting this to a trello card since it's an RFE: https://trello.com/c/XJSisZuD
