### ISSUE TITLE
OpenShift webcosole naming inconsistency

### ISSUE THREAD

**Issue by tnozicka** [openshift/origin#18689]
namespace: `openshift-web-console`
deployment.Name: `webconsole`
deployment.labels.webconsole
command: `/usr/bin/origin-web-console`
config: `webconsole-config.yaml`
image: registry.reg-aws.openshift.com:443/openshift3/ose-web-console:v3.9.0-0.42.0
...

We might want to consider how we spell `webconsole` (or `web-console`) and use it in unified way. Ideally before shipping this with 3.9 where it first appears.

/assign @spadgett

**Comment by spadgett** [comment]
This is very difficult to fix at this point because

1. We've deployed 3.9 to several clusters already
2. The proxy in master find the service by its name

We'd probably need to create services with both the old and new names for a time to avoid having a window where the install and CI is broken since this requires change to both openshift-ansible and the origin proxy.

There will be a downtime for the web console in any cluster already running 3.9 during next upgrade. The master is upgraded before the web console, so there will be a window where the new service name does not exist and you'll get a 404 trying to hit the console through the proxy.

We'd need to migrate the data from the webconsole-config config map to the new config map in any cluster already running 3.9, either manually or in the installer. The installer already has logic to migrate data from master-config.yaml, so this would add more complexity.

Ideally we'd remove resources with the old names in any existing 3.9 cluster, either manually or in the upgrade.

I'm uneasy with this change at this point in the release.

Note that these resource names themselves consistently use `webconsole`, even though this is different than the project and image name.

cc @smarterclayton @deads2k @jwforres

**Comment by deads2k** [comment]
I don't feel strongly, but if we're going to do it, doing it now is more reasonable than doing it after 3.9.

**Comment by spadgett** [comment]
@sdodson

**Comment by sdodson** [comment]
The image name is going to be impossible to change at this point, so if we change anything I think we should gravitate towards 'web-console'. I'm not too worried about internal clusters where the old deployment exists, we can manually clean that up.
