### ISSUE TITLE
[RFE] Create a --user-created-all flag to select everything project namespaced  that has been created by the user

### ISSUE THREAD

**Issue by jorgemoralespou** [openshift/origin#18701]
There should be a flag that selects every single resource that has been created by a user so he can clean everything he has deployed/created.
In the scenario where a user is not given project auto provision capabilities, he might want to delete everything that's there and he created so he can get back to a clean initial state.

It can be a command like __oc project --clean__ or similar. Not suggesting the syntax but the feature.

cc/ @thesteve0

**Comment by jwforres** [comment]
@openshift/sig-master

**Comment by mfojtik** [comment]
@jorgemoralespou how about things that were created by a controller on behalf of the user? (secrets/configmaps/builds/etc.). 
If you want to cleanup everything, isn't it better to recreate the project?

**Comment by jorgemoralespou** [comment]
@mfojtik As I said, there's many installs where developers can not create projects, and hence, they should not delete them (sometimes permissions to delete a project is not provided when they can't autoprovision, some other times, they will need to go through a request process again).
So, project recreation is not an option in this cases. It is exactly in this scenario where we found the problem and opened the issue. 

Yes, in this case, it should also delete everything created by controllers, that are not in a clean/new project, like the 3 required service accounts and whatever comes with them.

**Comment by jorgemoralespou** [comment]
This request also could entail the case where you want to delete every object, but --all does not work, as not every resource is in the --all alias.
User should be able to delete everything that has a specific label. When a user says --all, sometimes he means "totally all", even the things openshift does on my behalf.

**Comment by soltysh** [comment]
What's wrong with using labels? I don't feel too strongly convinced that adding additional flag, which will most probably just do what I said is needed.

**Comment by tnozicka** [comment]
> What's wrong with using labels?

@soltysh If you forget to/mess up/create it manually without them how do you clean it when you don't have permission to delete/create project?

We need at least a way to cleanup the whole namespace without delete/create because of permissions. `oc delete all` just selects few resources, so that's unusable. I am probably fine if we could just delete **really all** and the openshift provided resources would get recreated by reconciliation.

**Comment by liggitt** [comment]
> We need at least a way to cleanup the whole namespace without delete/create

`oc delete project foo`?

**Comment by liggitt** [comment]
> every single resource that has been created by a user 

That isn't tracked or knowable.

**Comment by jorgemoralespou** [comment]
@liggitt premise is avoid deleting a namespace as user might not be able to autoprovision it.

**Comment by soltysh** [comment]
> I am probably fine if we could just delete really all and the openshift provided resources would get recreated by reconciliation.

I doubt this **all** you're talking about will solve the issue here. There's always this one other type of resources that was created and will cause problems when trying to re-create the app. Even adding that flag won't solve the problem, because someone else will add this one tiny thing that's needed to make the app work and completely invalidate the purpose this flag was created for. It's the users responsibility to track and remove what he wants. There are multiple options we provide to easily manage these.
