### ISSUE TITLE
manually deleting a service created via the TSB does not delete the Serviceinstance and binding

### ISSUE THREAD

**Issue by jorgemoralespou** [openshift/origin#18702]
If I deploy a service through the TSB (e.g. mongodb) and then I do an "oc delete all --all" which will delete the service and deployment, then the ServiceInstance and Binding remains, but with invalid information as the service implementation is no longer available or valid.

##### Version
3.7.1

##### Steps To Reproduce
1. Create a mongodb through the service broker with a binding
2. oc delete all --all

##### Current Result
ServiceInstance and ServiceBinding remains

##### Expected Result
They get removed.

cc/ @thesteve0

**Comment by jwforres** [comment]
The question here is should `oc delete all --all` be deleting service instances and service bindings if the CLI sees types exist during API discovery.

**Comment by jwforres** [comment]
@openshift/sig-master

**Comment by liggitt** [comment]
> The question here is should oc delete all --all be deleting service instances and service bindings if the CLI sees types exist during API discovery.

If the service catalog wants service instances and bindings to be included in the `all` category, it can choose to do so by adding the "all" category. See an example here:

https://github.com/kubernetes/kubernetes/blob/2a604f6358698ae63de1861ef2f214709de674b3/pkg/registry/batch/job/storage/storage.go#L78-L84

It is unclear to me who is considered to own those objects:
* should the broker decorate those objects with finalizers that prevent their deletion until the parent service instance or service binding is flagged for deletion?
* should a controller watch for service instances whose services have been deleted and clean them up proactively?

**Comment by jwforres** [comment]
@openshift/sig-ansible-service-broker @pmorie @jboyd01 @jpeeler 

based on jordan's comment above there are two issues here, one for svc cat team, and one for the TSB

**Comment by jwforres** [comment]
@jim-minter @bparees for TSB part of the discussion since this is 3.9

**Comment by jim-minter** [comment]
Note that GC is involved with TemplateInstances. `oc delete all --all` doesn't delete all object kinds (e.g. Secrets), but if `oc delete all --all` ends up causing a TemplateInstance to be deleted and that TemplateInstance previously instantiated Secrets, GC propagation will cause those Secrets to be deleted.  That could surprise someone one day.

If just ServiceInstances are added to the "all" category, and if deleting a ServiceInstance causes the SC to send a deprovision request to the TSB, then in principle `oc delete all --all` will end up causing everything laid down by the TSB to be deleted after the deprovision call completes.

TemplateInstances could be added into the "all" category in addition/instead.  I think that adding both shouldn't cause problems.  Note that if TemplateInstances are added and ServiceInstances are not, or if deleting a ServiceInstance does not provoke a deprovision call, as things stand BrokerTemplateInstance objects and Secret objects associated with TemplateInstances would be "leaked".  At the moment we have no automated mechanism to detect or delete "leaked" BrokerTemplateInstances: I'll trello that.

**Comment by pmorie** [comment]
I have code ready to add `ServiceInstance` and `ServiceBinding` to `all`, but this gave me some pause:

https://github.com/kubernetes/community/blob/master/contributors/devel/kubectl-conventions.md#rules-for-extending-special-resource-alias---all

..specifically, this verbiage: _"No resources that are potentially unrecoverable (secrets and pvc)"_

It's not exactly clear what 'unrecoverable' means here - if it means application state, then it's arguable that `ServiceInstance` and `ServiceBinding` should _not_ be included in `all`.

Another dimension of this: `ServiceBindings` have a secret strongly associated with them. Deleting a binding will result in a secret being deleted as well. That makes it sound like bindings, at least, **shouldn't** be included in `all`.

If `ServiceBindings` aren't included in all, then we shouldn't include `ServiceInstance` either, because deleting the instance but not the bindings will but the instance in a state where it is pending deprovision once the bindings have been deleted.

In general, as I write this comment, I'm starting to think that the service catalog resources shouldn't be included in `all`, since they are related to potentially unrecoverable application state like databases and tied into the existence of secrets.

I don't think we should feed information back into the catalog resources once this happens because:

1. I'm not sure how that would work
2. I do not want to open the door to awkward use cases that don't work cleanly in the context of the OSB API and catalog metaphors

Consider this: if you have a ServiceInstance that represents an external DB, and someone comes along and deletes that DB out of band to the catalog, you won't have any information about that in the catalog. It seems like this situation has parity with that example, with the extra complication that since the resources for the service are put into your namespace, you have a chance of deleting them via `delete all`.

It seems to me at this point like ideally we would block deletion of TSB resources until the corresponding `ServiceInstance` and `ServiceBindings` were deleted.

**Comment by juanvallejo** [comment]
> In general, as I write this comment, I'm starting to think that the service catalog resources shouldn't be included in all, since they are related to potentially unrecoverable application state like databases and tied into the existence of secrets.

I think based on this point, I'm inclined to agree with excluding service catalog resources from "all".

> It seems to me at this point like ideally we would block deletion of TSB resources until the corresponding ServiceInstance and ServiceBindings were deleted.

cc @soltysh

**Comment by jorgemoralespou** [comment]
This comment:
> It seems to me at this point like ideally we would block deletion of TSB resources until the corresponding ServiceInstance and ServiceBindings were deleted.

I think this can also work, making deletion of these services that have been created through the catalog only be able to be deleted once the ServiceInstance and ServiceBinding are deleted. In any case, what we want is to avoid inconsistent state in the platform, while providing a correct user experience.

@pmorie How would you then act when __delete -l app=mydatabase__ or __delete --all__ happens in a project with a ServiceInstance and/or ServiceBinding? Would you error out? How? What I see most problematic is to provide a good user experience in these situations.
