### ISSUE TITLE
Cannot oc login https://10.2.2.2:8443 - error: Missing configuration

### ISSUE THREAD

**Issue by simplenotezy** [openshift/origin#18719]
Followinng the OpenShift For Developers Red Hat free e-book, on page 36 at "Now Log In from the Command Line", it tells you to run `oc login https://10.2.2.2:8443`, however it fails.

	[simplenotezy:~/openshift/project]$ oc login https://10.2.2.2:8443                     (openshift✱)
	The server uses a certificate signed by an unknown authority.
	You can bypass the certificate check, but any data you send to the server could be intercepted by others.
	Use insecure connections? (y/n): y

	error: Missing configuration - verify you have provided the correct host and port and that the server is currently running.
	error: Missing configuration

I have indeed verified that openshift is runnning. If I go to `https://10.2.2.2:8443` in the browser, I can login without issues.

##### Version
Version
oc v3.7.1+ab0f056
kubernetes v1.7.6+a08f5eeb62
features: Basic-Auth

openshift v3.7.9
kubernetes v1.7.6+a08f5eeb62

**Comment by jwforres** [comment]
@openshift/sig-master

**Comment by jwforres** [comment]
@GrahamDumpleton added you since the steps are coming from the book

**Comment by GrahamDumpleton** [comment]
That chapter was written for old VirtualBox all in one, which isn't available any more. The link in the book will send you to Minishift, which is different. Use the instructions on the Minishift site for installing it and logging in. Minishift shouldn't use address 10.2.2.2 that I know of and there is definitely no 3.7 version of old all in one VM.

Can you explain how you installed OpenShift and got it running?

**Comment by neisw** [comment]
Greetings Graham.  I too found myself in a similar situation.  Pulling down minishift was easy enough and resolved the issue.

I think what happened was:
The ebook points to https://openshift.org/vm for the latest install instructions.

https://openshift.com/vm is not found (note the missing www)

The url in the ebook for the vagrant file is https://www.openshift.org/vm/Vagrantfile and it works properly (though maybe you intend for it to redirect now).  If you go to https://www.openshift.org/vm you are redirected to minishift, but since the Vagrant file is there you might just go on your merry way eager to get things running.

Th oc Command Line tool section again points https://openshift.org/vm.  This doesn't work  But a quick google fixes that.  At this point if you aren't aware that things have changed you wind up in the situation where you have the latest oc version and an old vagrant file / VirtualBox image.

Again, easy enough to resolve and glad I found this page.  Might be a couple additional redirects will keep others from the same situation.

Thanks!

**Comment by GrahamDumpleton** [comment]
I believe they have changed where openshift.org site is hosted. In moving it they likely forgot to implement a redirect from openshift.org to www.openshift.org. I will chase it up.

**Comment by GrahamDumpleton** [comment]
The problem with ``https://openshift.org`` not redirecting, plain ``http://openshift.org`` does, is now being looked at.

FWIW, we hope to start working on updating that book to latest OpenShift version, including Minishift, and adding new material, some time this year. We will also have a completely new book on OpenShift available around May.

**Comment by GrahamDumpleton** [comment]
The redirect for ``https://openshift.org`` has now been fixed. I am going to close this issue since nothing to be done in OpenShift itself.
