### ISSUE TITLE
Poor to no documentation around persistent volume permissions

### ISSUE THREAD

**Issue by calston** [openshift/origin#18717]
With the automated PV provisioning disks are created with root ownership and 0755 permission, which means by default no container can actually write to it.

This could sometimes be fixed with the hostpath-anyuid SCC however the documentation for this is sparse, confusing, and offers conflicting statements in may parts. 

In fact, in the VSphere provider configuration documentation this issue isn't even mentioned. A reasonable user following that documentation word for word will be left with a solution which does not in fact work. 

This needs to be significantly improved!

##### Version
OCP 3.7

##### Steps To Reproduce
1. Follow documentation
2. Become confused and frustrated every step of the way about SCC's. 

##### Current Result
Everything is broken and requires manual intervention and deep dive hacking

##### Expected Result
People expect their automated system to automate common issues for them and provide clean sensible interfaces to do so.

##### Additional Information
This sucks: https://docs.openshift.com/container-platform/3.7/install_config/persistent_storage/persistent_storage_vsphere.html

**Comment by jwforres** [comment]
@openshift/team-documentation

**Comment by jwforres** [comment]
@openshift/sig-storage

**Comment by php-coder** [comment]
@calston I feel your pain and I'm sorry to hear about the experience that you had :(

> With the automated PV provisioning disks are created with root ownership and 0755 permission, which means by default no container can actually write to it.

Yes, you're right. As far I understand, in this case the advice is to leverage `securityContext.fsGroup` field to specify a group explicitly. We have a dedicated chapter about it: https://docs.openshift.com/container-platform/3.7/install_config/persistent_storage/pod_security_context.html#fsgroup

@openshift/sig-storage Please, correct me if I'm mistaken about how do we handle "permissions on volumes" issues and specially the **vsphere** volumes.

> This could sometimes be fixed with the hostpath-anyuid SCC however the documentation for this is sparse, confusing, and offers conflicting statements in may parts.

The SCC documentation is another story. I suspect that `hostpath-anyuid` helps only because a pod is running under `root` user and that matches the default volume permissions. If it's possible, it's better to configure permissions appropriately from the beginning.

> This sucks: https://docs.openshift.com/container-platform/3.7/install_config/persistent_storage/persistent_storage_vsphere.html

Let me remind you, that you've filled the issue against wrong repository. You aren't satisfied with documentation but this repository about project itself. Documentation issues are tracked there: https://github.com/openshift/openshift-docs

Let's get back to the discussion about how we can improve the situation. If the link that I provided above helps you to configure permissions on PVs, will it be enough to add this link to the "Persistent Storage Using VMWare vSphere Volume" chapter?

CC @gaurav-nelson

**Comment by calston** [comment]
Thanks a lot. Sorry wasn't aware of the other repository. Should I move the issue?

Since this stuff basically seems mandatory it feels like the flow of the documentation should hilight it all better

**Comment by gaurav-nelson** [comment]
@tmorriso-rh PTAL

**Comment by tmorriso-rh** [comment]
@calston When you have a chance to read over the docs, please contact me to discuss creating a PR. The PR will need to be reviewed by the development and QE teams before merging into the live docs. Thanks.

Cc: @vikram-redhat

**Comment by calston** [comment]
Okay so I've been bashing my head on this some more. It's actually pretty unreliable to reproduce but the default SCC's fsGroup are pretty all over the place. You set priviledged SCC and get fewer permissions?

The primary issue I find these two sections in almost direct conflict. 

> As with supplementalGroups, all containers in the above pod (assuming the matching SCC or project allows the group 5555) will be members of the group 5555, and will have access to the block volume, regardless of the container’s user ID. If the pod matches the restricted SCC, whose fsGroup strategy is MustRunAs, then the pod will fail to run. **However, if the SCC has its fsGroup strategy set to RunAsAny, then any fsGroup ID (including 5555) will be accepted**. Note that if the SCC has its fsGroup strategy set to RunAsAny and no fsGroup ID is specified, the "taking over" of the block storage does not occur and permissions may be denied to the pod.

But then earlier 

> Allowing access to SCCs with a RunAsAny FSGroup strategy can also prevent users from accessing their block devices. **Pods need to specify an fsGroup in order to take over their block devices. Normally, this is done when the SCC FSGroup strategy is set to MustRunAs**. If a user’s pod is assigned an SCC with a RunAsAny FSGroup strategy, then the user may face permission denied errors until they discover that they need to specify an fsGroup themselves.

Can anyone explain what is actually going on?

Testing reveals yes, it must be set to MustRunAs. My English brain interprets "Must" as a restriction, not a permission....

**Comment by php-coder** [comment]
@calston Keep in mind that the SCC not only allow/reject a pod but also is used to fill the default values for the missing fields. That's why when you use `MustRunAs` strategy you can omit `fsGroup` field in the pod spec as it will be defaulted by this strategy. When you use `RunAsAny`, it allows any requested `fsGroup` but because it doesn't provide default value for this field you have to specify it explicitly.

Also note that there could be another distinction between `MustRunAs` strategies. In one case, SCC may have explicitly specify allowed ID and in another case it won't have such a default. In the latter case, this default value will be computed based on annotation on a namespace. Why does it matter? Because each namespace has different values in this annotation and you can't be sure what the value`fsGroup` will have (it changes from namespaces to namespace and "semi-random"). So, if you want to be 100% sure that pod without fsGroup will have a fixed fsGroup, then it's better to have a custom SCC with `MustRunAs` strategy that explicitly allows (and defaults) only this particular value.

Hope this helps.

**Comment by calston** [comment]
Great explanation @php-coder ! Thank you for this. 

I do think the above explanation should be highlighted in the documentation, but having it in this issue for others to find is also good.
