### ISSUE TITLE
Openshift Persistent MySQL & MongoDB Deployments Fail with anyuid feature enabled

### ISSUE THREAD

**Issue by svarlamov** [openshift/origin#18962]
When starting the openshift persistent mysql or mongodb templates on a project that has had the `oc adm policy add-scc-to-user anyuid -z default` command run, experiences permissions exceptions and a subsequent crash loop. Note: the PVs are being mounted through AWS EBS. I haven't done enough testing yet to see if this occurs on other PV types yet. When the project is recreated without running that `anyuid` command, then everything works fine. Things also seem to work when the `anyuid` command is run after the database pods are running. 

##### Version

oc v3.6.1+008f2d5
kubernetes v1.6.1+5115d708d7
features: Basic-Auth GSSAPI Kerberos SPNEGO

##### Steps To Reproduce
1. Create project
2. Run `oc adm policy add-scc-to-user anyuid -z default` on the project
3. Launch a MySQL or MongoDB persistent template from the catalog (openshift)
4. The deployment enters a crash loop (if you can get the logs pulled up, you will see corresponding permissions errors for MySQL/MongoDB)

##### Expected Result

The built-in persistent templates should work out of the box when the project has the `anyuid` feature enabled -- same as they work without that enabled.

**Comment by php-coder** [comment]
@svarlamov Thank you for the report! If it's possible more details would be helpful:
1) pod definition (`oc get pod <pod> -o yaml` and don't forget to mask sensitive information like AWS EBS credentials)
2) error message(s)

> Launch a MySQL or MongoDB persistent template from the catalog (openshift)

CC @openshift/sig-developer-experience Is it possible that the issue related to the images itself?

**Comment by bparees** [comment]
It's either a storage issue or an image issue. Does the issue occur when using empty dir volumes?

@coreydaley can you investigate this?

Logs from the crash looping pod would be useful. (oc logs -p)

**Comment by coreydaley** [comment]
@svarlamov Are you able to provide the logs from the crash looping pod as requested by @bparees ?

**Comment by svarlamov** [comment]
Sure, sorry for the delay! Thank you for the help! In the meantime, we were able to get most of our images to run without root, which I assume is the best practice, so it is no longer critical for my team, but I'm certain that others would benefit from this conversation!

#### MongoDB Logs (PV via AWS EBS):

```
=> sourcing 10-check-env-vars.sh ...
--
  | => sourcing 20-setup-wiredtiger-cache.sh ...
  | => [Wed Mar 21 09:17:40] wiredTiger cacheSizeGB set to 1
  | => sourcing 30-set-config-file.sh ...
  | => sourcing 35-setup-default-datadir.sh ...
  | ERROR: Couldn't write into /var/lib/mongodb/data
  | CAUSE: current user doesn't have permissions for writing to /var/lib/mongodb/data directory
  | DETAILS: current user id = 184, user groups: 997 0
  | DETAILS: directory permissions: drwxrwsr-x owned by 0:1000360000, SELinux: system_u:object_r:svirt_sandbox_file_t:s0:c9,c19
```

#### MySQL Logs (PV via AWS EBS):

```
=> sourcing 20-validate-variables.sh ...
--
  | => sourcing 25-validate-replication-variables.sh ...
  | => sourcing 30-base-config.sh ...
  | ---> 09:19:56     Processing basic MySQL configuration files ...
  | => sourcing 60-replication-config.sh ...
  | => sourcing 70-s2i-config.sh ...
  | ---> 09:19:56     Processing additional arbitrary  MySQL configuration provided by s2i ...
  | => sourcing 40-paas.cnf ...
  | => sourcing 50-my-tuning.cnf ...
  | ---> 09:19:56     Initializing database ...
  | ---> 09:19:56     Running mysqld --initialize-insecure ...
  | mysqld: Can't create/write to file '/var/lib/mysql/data/is_writable' (Errcode: 13 - Permission denied)
  | 2018-03-21T09:19:56.154342Z 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).
  | 2018-03-21T09:19:56.162092Z 0 [Warning] Duplicate ignore-db-dir directory name 'lost+found' found in the config file(s). Ignoring the duplicate.
  | 2018-03-21T09:19:56.162243Z 0 [ERROR] --initialize specified but the data directory exists and is not writable. Aborting.
  | 2018-03-21T09:19:56.162263Z 0 [ERROR] Aborting
```

**Comment by svarlamov** [comment]
@bparees I'm not certain that I know what you mean by "empty dir volumes" but I assume that it would be using non-AWS PVs? I'm not certain how to do that on my cluster... I would have to speak to our cluster admin about that if that's indeed what you're asking for. However, I can confirm that this only happens when the root user is enabled.

**Comment by bparees** [comment]
emptydir volumes are the most basic form of volume, they are always enabled and don't require any special permissions.  They are non-persistent storage, think "/tmp".

Your failure logs imply that the storage you are using is not writable by the container uid, so that is a configuration issue w/ your storage setup (no surprise running as root got you around it since root can presumably write to the storage dir).

emptydir:
https://kubernetes.io/docs/tasks/configure-pod-container/configure-volume-storage/
https://kubernetes.io/docs/concepts/storage/volumes/#emptydir

I'm handing this issue off to the storage team to further assist you w/ getting your PVs configured properly so they are writable by non-root users.

@openshift/sig-storage

**Comment by svarlamov** [comment]
@bparees Thank you for your comment and explanation. You say that running as root 'got me around it,' but in fact, running as root causes the error. When I am **not** root, then it works fine

**Comment by adibalsa** [comment]
Hi @svarlamov , I'm getting exactly the same issue with MongoDB and MySQL running on OpenShift on Azure and using PVs hosted on Azure Storage Accounts. 
What do you mean when you say that you "were able to get most of our images to run without root" ?
Can you please describe how you did that ? Sorry for the newbie question, but I'm not an OpenShift expert. Thanks.  @bparees

**Comment by gnufied** [comment]
@adibalsa Please check what is the security policy (scc) applied to your pods. You can do `oc get pod <pod_name> -o json` and look for annotation `openshift.io/scc` to verify SCC being applied to the pod.


Running as non-root could fix the problem because, then fsGroup applied to your pod is `MustRunAsRange`  which will cause openshift to assign a group to the pod and same group is assigned to the volume during mount. This ensures that pod and volume's permission match.

Sometimes users incorrectly use `RunAsAny` fsGroup and causes Openshift to assume that pod explicitly use a group. But if no fsGroup is assigned to pod then even though pod is running with elevated permissions writes may fail because Openshift does not know about group being assigned to pod. 

This is documented in https://docs.openshift.com/container-platform/3.9/admin_guide/manage_scc.html and https://docs.openshift.com/container-platform/3.9/install_config/persistent_storage/pod_security_context.html

**Comment by adibalsa** [comment]
@gnufied Thanks, I understand now. That's clear ! 
Have a great weekend :-)

**Comment by svarlamov** [comment]
@gnufied Thank you for explaining the root cause of this issue -- good to know! I think that we can close this issue then?

@adibalsa The workaround that we use for projects that still require root access (albeit without a PV), creates a special service role for those pods. So you end up deploying your DBs, etc., into the default configuration (non-root) and then the services that require root access use the service role that has `anyuid` enabled
