### ISSUE TITLE
Listing all sibling pods within a pod | Adding a role to user within a template

### ISSUE THREAD

**Issue by exploadingkittens** [openshift/origin#18986]
We are making a template that creates a service, a route and a deploymentconfig.

When a new pod is created we want to "tell" its siblings (in the deployment) that they need to add their new "brother" to a group, and therefore we are trying to list all the siblings pods within a pod, as in we have a replica that wants to know the podIP of the other pods, we can successfully do it with: https://$KUBERNETES_SERVICE_HOST/api/v1/namespaces/$Namespace/pods

The thing is you are required to add a header with an authorization token ("Authorization Bearer `<token>`" of a user with the required privileges. 

We thought we can use system:serviceaccount:$namespace:default, but since it is only allowed to run the pods, hence, we've added a view permission with: `oc policy add-role-to-user view system:service:$namespace:default`
and used the default service account token.

All seemed to be well.

So basically the question is divided to two sections:
a. Finding an alternative to list all the sibling pods within a pod
or
b.1 Adding `view` permission to `system:serviceaccount:$namespace:default` in a template.
b.2 Creating a new service account with view permissions in a template

##### Version
`oc version
oc v3.7.14
kubernetes v1.7.6+a08f5eeb62
features: Basic-Auth GSSAPI Keberos SPNEGO

Server https://`<server>`:8443
openshift v3.7.14
kubernetes v1.7.6+a08f5eeb62`

##### Steps To Reproduce
1. Create a deployment config with 2 pods
2. Open a terminal to one of the pods
3. Run the command within the pod: `curl -k https://$KUBERNETES_SERVICE_HOST/api/v1/namespaces/$Namespace/pods`
(that's without a token, we will call this result 1)
4. Run the command within the pod: `curl -k -H "Authorization: Bearer <token_of_system:serviceaccount:$namespace:default>`
(that's with default token, without view permissions, we will call this result 2)
5. Run the command in a node (after the correct project is selected) `oc policy add-role-to-user view system:service:$namespace:default`
6. Repeat step 4, we will call this result 3

##### Current Result
Result 1: 

> User "system:anonymous" cannot list pods in the namespace "$namespace": User "system:anonymous" cannot list pods in project "$namespace"

Result 2: 

> User "system:serviceaccount:$namespace:default" cannot list pods in the namespace "$namespace": User "system:serviceaccount:$namespace:default" cannot list pods in project "$namespace"

Result 3: 
json with the correct result

##### Expected Result
All of the results are expected

I hope I was able to explain myself thoroughly, if more data is required, I'd be happy to provide it.

**Comment by jwforres** [comment]
Are you asking whether b.1 and b.2 are possible? Or are you asking how to do it?

b.1 should just mean adding a RoleBinding in the template, b.2 would be adding both a ServiceAccount and a RoleBinding in the template, no limits on this AFAIK other than the user instantiating the template needs the perms to create those objects.  Since it includes RoleBinding, that means it has to be a project Admin who is instantiating the template.

@openshift/sig-security 

For (a) I'm including @openshift/sig-pod @openshift/sig-networking in case they have other suggestions for discovering the IPs for the other pods for a given replicationcontroller

**Comment by enj** [comment]
I am not fully sure what the question is, but I would generally go with `b.2` because it gives a custom SA the permissions it needs to run your app (and not the generic default SA).  If you are particularly paranoid, you create a custom role that only grants `get pod` and have a role binding that references it (so your custom SA has the bare minimum permissions).

**Comment by sjenning** [comment]
For (a), if you have a Service selecting the same set of pods as the Deployment, there will be an Endpoints resource that contains the IPs of the pods selected by the Service.
