### ISSUE TITLE
openshift-merge-robot is not allowed to merge PRs

### ISSUE THREAD

**Issue by kargakis** [openshift/origin#18987]
```
I0315 00:50:50.565957       1 github.go:2074] Merging PR# 18973
I0315 00:50:50.565994       1 github.go:2299] Commenting in 18973: "Automatic merge from submit-queue."
E0315 00:50:51.157001       1 github.go:2141] Failed to merge PR: 18973: PUT https://api.github.com/repos/openshift/origin/pulls/18973/merge: 405 You're not authorized to push to this branch. Visit https://help.github.com/articles/about-protected-branches/ for more information. []
...
I0314 22:23:59.371825       1 github.go:2299] Commenting in 18977: "Automatic merge from submit-queue."
E0314 22:23:59.948110       1 github.go:2141] Failed to merge PR: 18977: PUT https://api.github.com/repos/openshift/origin/pulls/18977/merge: 405 You're not authorized to push to this branch. Visit https://help.github.com/articles/about-protected-branches/ for more information. []
```
/priority P0

@smarterclayton @stevekuznetsov @jupierce

**Comment by smarterclayton** [comment]
I fixed 3.8 and 3.9, somehow @nhr ended up as the only user.

On Mar 15, 2018, at 6:31 AM, Michalis Kargakis <notifications@github.com>
wrote:

I0315 00:50:50.565957       1 github.go:2074] Merging PR# 18973
I0315 00:50:50.565994       1 github.go:2299] Commenting in 18973:
"Automatic merge from submit-queue."
E0315 00:50:51.157001       1 github.go:2141] Failed to merge PR:
18973: PUT https://api.github.com/repos/openshift/origin/pulls/18973/merge:
405 You're not authorized to push to this branch. Visit
https://help.github.com/articles/about-protected-branches/ for more
information. []
...
I0314 22:23:59.371825       1 github.go:2299] Commenting in 18977:
"Automatic merge from submit-queue."
E0314 22:23:59.948110       1 github.go:2141] Failed to merge PR:
18977: PUT https://api.github.com/repos/openshift/origin/pulls/18977/merge:
405 You're not authorized to push to this branch. Visit
https://help.github.com/articles/about-protected-branches/ for more
information. []

/priority P0

@smarterclayton <https://github.com/smarterclayton> @stevekuznetsov
<https://github.com/stevekuznetsov> @jupierce <https://github.com/jupierce>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/origin/issues/18987>, or mute the thread

**Comment by smarterclayton** [comment]
Looks like a communication problem - harrison deliberately did this since
we don't have a bot driven central approval flow.

**Comment by jupierce** [comment]
@nhr had requested this specifically to help control changes after devcut. The impact is expected and not ideal, but our only way of keeping Harrison in control of merges into these branches. We need to revisit how we do this for subsequent releases (merge gating labels per branch).

For now, merge permissions have been reverted back to nhr.

**Comment by kargakis** [comment]
> we don't have a bot driven central approval flow.

Do we need something more strict than OWNERS files?

> merge gating labels per branch

Once we switch prow to do Origin merges (soon I hope), this will be possible.
