### ISSUE TITLE
oc rollout latest gets wrong completion

### ISSUE THREAD

**Issue by nak3** [openshift/origin#19088]
~~~
$ oc rollout latest <TAB>
~~~

gets

~~~
$ oc rollout latest deploymentconfig
~~~

But `oc rollout latest deploymentconfig sti-php` will get invalid
number of args.

It is easy to fix by removing ValidArgs in below:

https://github.com/openshift/origin/blob/248eabbd43cc3b677ce96cc4fdc4c00eda0c44b7/pkg/oc/cli/cmd/rollout/latest.go#L83

However if it is assumed that `oc rollout latest` will supprots
deployments in the future discussed in
https://github.com/openshift/origin/issues/16222, `oc rollout latest`
should have two args <TYPE> <NAME> like other `oc rollout` command family.

**Comment by mfojtik** [comment]
@nak3 it is unlikely the oc rollout latest will support deployments anytime soon. With @tnozicka we discussed that rather than artificially modifying deployment replica set template to cause it to rollout, we will rather want to implement a "restart" operation that will reload all containers created by the deployment (and other workload apis)...

**Comment by nak3** [comment]
@mfojtik Thank you. I see. Then it should fix by just dropping `deploymentconfig` in `ValidArgs` from `oc rollout latest`.

**Comment by tnozicka** [comment]
I think the autocompletion is wrong in completing just `deplyomentconfig` instead of `deploymentconfig/`. I'd suspect the valid args may be used to determine allowed resources, but I haven't checked.

/cc @soltysh

The syntax is `oc rollout latest deploymentconfig/sti-php` the short one is for backwards compatibility and nothing is pressing us to deprecate that as we don't support more resources in this command yet. (And deployments won't be one of them as @mfojtik mentioned.)

**Comment by nak3** [comment]
I see. It is easy to update the patch https://github.com/openshift/origin/pull/19097 to

```
ValidArgs: []string{"deploymentconfig/"}
```

or

```
ValidArgs: []string{"dc/"}
```

But it will complete the command with extra space like:

```
$ oc rollout latest <TAB>

$ oc rollout latest deploymentconfig/[ ]
                                      ^
				      +---- insert space here!
```

So, it could be a (very) small frustration.
