### ISSUE TITLE
hostsubnet and netnamespace controllers can hang on start

### ISSUE THREAD

**Issue by danwinship** [openshift/origin#19217]
test provisioning failure "Verify that the web console is running" due to missing NetNamespace

eg, https://openshift-gce-devel.appspot.com/build/origin-ci-test/logs/test_branch_origin_extended_conformance_gce/2794/:

    TASK [openshift_web_console : Verify that the web console is running] **********
    Tuesday 03 April 2018  05:30:13 +0000 (0:00:00.044)       0:19:01.544 ********* 
    FAILED - RETRYING: Verify that the web console is running (60 retries left).
    FAILED - RETRYING: Verify that the web console is running (59 retries left).
    ...
    FAILED - RETRYING: Verify that the web console is running (1 retries left).
    fatal: [ci-prtest-3c63a87-2794-ig-m-4ntb]: FAILED! => {"attempts": 60, "changed": false, "cmd": ["curl", "-k", "https://webconsole.openshift-web-console.svc/healthz"], "delta": "0:00:01.013229", "end": "2018-04-03 05:41:31.168908", "msg": "non-zero return code", "rc": 7, "start": "2018-04-03 05:41:30.155679", "stderr": "  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current\n                                 Dload  Upload   Total   Spent    Left  Speed\n\r  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0\r  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0curl: (7) Failed connect to webconsole.openshift-web-console.svc:443; Connection refused", "stderr_lines": ["  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current", "                                 Dload  Upload   Total   Spent    Left  Speed", "", "  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0", "  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0curl: (7) Failed connect to webconsole.openshift-web-console.svc:443; Connection refused"], "stdout": "", "stdout_lines": []}
    ...
    Failure summary:
    
    
      1. Hosts:    ci-prtest-3c63a87-2794-ig-m-4ntb
         Play:     Web Console
         Task:     Report console errors
         Message:  Console install failed.
    ++ export status=FAILURE
    ++ status=FAILURE
    + set +o xtrace
    ########## FINISHED STAGE: FAILURE: PROVISION TEST CLUSTER [00h 30m 37s] ##########

The output include the error

    Failed create pod sandbox: rpc error: code = Unknown desc = NetworkPlugin cni failed to set up pod \"webconsole-76667b6c95-mvlgq_openshift-web-console\" network: CNI request failed with status 400: 'failed to find netid for namespace: openshift-web-console, netnamespaces.network.openshift.io \"openshift-web-console\" not found", 

suggesting possible fallout from #18911.

@dcbw was looking at this yesterday but I don't know what he found

**Comment by dcbw** [comment]
@danwinship basically that the SDN master never saw the openshift-web-console Namespace creation, then never created the NetNamespace, so the SDN nodes can't find the NetNamespace and give the error listed.

In fact, the logs at https://ci.openshift.redhat.com/jenkins/job/test_branch_origin_extended_conformance_gce/2794/s3/download/masters/4ntb/generated/containers.log dont' show *any* Namespace event from vnids.go whatsoever, and we should be seeing at least "Watch ADD event for namespace 'default'" at the very least, because the AddEventHandler() function should be calling the ADD event for every Namespace already known to the informer.

We do get a bunch of hits from networkpolicy.go but that's on the Node side.  So I don't know, maybe now that we're running the SDN process in both master & node modes at the same time, that screws things up?

**Comment by danwinship** [comment]
I think everything runs at --loglevel=4 ?

**Comment by dcbw** [comment]
@danwinship you mean on the CI?  The nodes are explicitly set to V(5), so I'm thinking the master should do the same.

**Comment by dcbw** [comment]
See https://github.com/openshift/openshift-ansible/pull/7785 which tries to allow setting debug loglevel on master static pods.
