### ISSUE TITLE
Controller should exit/log when enough reflector errors occur 

### ISSUE THREAD

**Issue by soltysh** [openshift/origin#19274]
This issue is coming from https://github.com/openshift/origin/pull/19225#issuecomment-378924125. Quoting @smarterclayton:

> Router for example loops forever at 1s intervals if the admin didn’t grant access to services at namespace scope, without backoff or any ability to report that failure. For most components that’s ok, for a lot of others it may not be. At some point we need to fix that so that backoff or failure is possible.

> In this case observe typically deals with a single resource - if you cannot access that resource the controller is worthless.

> I suspect we would just add something to reflector and informer which is an error handler.

@openshift/sig-master I think we might want to try to tackle this in 3.10?

**Comment by smarterclayton** [comment]
We probably should consider check two scenarios - controllers which are
accidentally not given the correct permissions and no one ever figures it
out, and controllers running outside the controller manager (router, etc)
that watch a single resource and are never able to establish an initial
watch or list.  How does an admin know, and how do we limp in those cases.

On Apr 9, 2018, at 9:30 AM, Maciej Szulik <notifications@github.com> wrote:

This issue is coming from #19225 (comment)
<https://github.com/openshift/origin/pull/19225#issuecomment-378924125>.
Quoting @smarterclayton <https://github.com/smarterclayton>:

Router for example loops forever at 1s intervals if the admin didn’t grant
access to services at namespace scope, without backoff or any ability to
report that failure. For most components that’s ok, for a lot of others it
may not be. At some point we need to fix that so that backoff or failure is
possible.

In this case observe typically deals with a single resource - if you cannot
access that resource the controller is worthless.

I suspect we would just add something to reflector and informer which is an
error handler.

@openshift/sig-master <https://github.com/orgs/openshift/teams/sig-master>
I think we might want to try to tackle this in 3.10?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/origin/issues/19274>, or mute the thread
