### ISSUE TITLE
Service Instance is not deleted and is blocking project deletion

### ISSUE THREAD

**Issue by gbaufake** [openshift/origin#19351]
After creating Deleting a Jenkins Persistent Project (from catalog), the project stays on a zombie state like https://github.com/openshift/origin/issues/18125. Service instances is not being deleted

##### Version
oc v3.9.14
kubernetes v1.9.1+a0ce1bc657
features: Basic-Auth GSSAPI Kerberos SPNEGO
openshift v3.9.14
kubernetes v1.9.1+a0ce1bc657

##### Steps To Reproduce
1. Install Openshift 3.9 Cluster
2. Install Jenkins Persistent Project using Service Catalog
3 . Delete Jenkins Project

##### Current Result
- Projected is not Deleted

##### Expected Result

Projected Deleted

##### Additional Information
- Service instance shows a message: Error polling last operation: Status: 500; ErrorMessage: <nil>; Description: templateinstances.template.openshift.io "aca972af-e7f3-4e3c-8d9d-8beb39a5268a" not found; ResponseError: <nil>

-  Api Logs Embeded
[apiserver-qfj42.log](https://github.com/openshift/origin/files/1909975/apiserver-qfj42.log)

**Comment by gbaufake** [comment]
Found a bug similar to this https://bugzilla.redhat.com/show_bug.cgi?id=1551988

**Comment by nak3** [comment]
Yes, [bz#1541350#c3](https://bugzilla.redhat.com/show_bug.cgi?id=1541350#c3) would be the workaround, if serviceinstance caused the isssue.

However, it is interesting for me that you hit the issue on v3.9. As per bz#1541350 (c#8, c#11), the issue was considered as solved on 3.9.

**Comment by jwforres** [comment]
@openshift/sig-ansible-service-broker

**Comment by greg-pendlebury** [comment]
I love the bot policy of closing old bugs just because they are old... particularly when they are confirmed and assigned. It is certainly way better to have a clean ticketing system than bug free software...

We hit this Yesterday as well and _seemed_ to workaround it by deleting the finalizer on the `serviceinstance` (not the project, as per comments in #18125). It didn't really go away though, as later reuse of the same project name remains broken when Jenkins gets deployed. It was interesting to me in reading through the various issues in bugzilla that lots of users are reporting this associated with Jenkins. Most are persistent as well, but I also saw was an ephemeral instance.

[This guy](https://bugzilla.redhat.com/show_bug.cgi?id=1551988) is aware that he consciously removed the template and caused the error, but our template was last touched 12 days ago (and is still there), whereas the instance was only provisioned Yesterday.

I did notice in passing that the stock templates for `jenkins-ephemeral` and `jenkins-persistent` have the same UID... is that an issue?

The delete error is referencing a `templateinstance`, but I didn't check those (via that API) before we blew away the project... still learning I guess. Seems that these objects are being deleted before the last thing using them gets deleted:
```
Error polling last operation: Status: 500; ErrorMessage: <nil>; Description: templateinstances.template.openshift.io "{... random ID here ...}" not found; ResponseError: <nil>
```

I am particularly worried that we seem to have no fix or work around other than to stop using this project name... but that has broader implications because our projects are name aligned to other infrastructure.

```
oc v3.11.0+0cbc58b
kubernetes v1.11.0+d4cacc0
features: Basic-Auth SSPI Kerberos SPNEGO

Server ....
openshift v3.11.117
kubernetes v1.11.0+d4cacc0
```

**Comment by greg-pendlebury** [comment]
We finally have a usable project again, but we were forced to change the Jenkins template parameter for `${JENKINS_SERVICE_NAME}`. I assume whatever is broken under-the-hood remains broken and is related to that; we are just avoiding it.

The symptoms of our 'broken' deployments were traced down to the PVC being mounted with incorrect permissions (for reasons which remain unknown), causing Jenkins pods to crash during startup:
```
sh-4.2$ cd /var/lib/jenkins/
sh-4.2$ ls -la
...
drwxr-xr-x.  3 root root  4096 Oct  2 01:24 .
```

Deploying the template to a fresh project works as expected:
```
sh-4.2$ cd /var/lib/jenkins/
sh-4.2$ ls -la
...
drwxrwsr-x.  17 root    1000560000  4096 Oct  2 00:41 .
```

And deploying Jenkins with a different `${JENKINS_SERVICE_NAME}` works as well:
```
sh-4.2$ cd /var/lib/jenkins
sh-4.2$ ls -la
...
drwxrwsr-x. 11 root    1000640000  4096 Oct  2 02:27 .
```

**Comment by jmrodri** [comment]
@greg-pendlebury yeah, it's definitely a trouble spot and we've been advising to remove the finalizers. Based on your comment above it looks like you're using the template service broker with the service catalog. There are a couple things at play here.

The service catalog will create an manage a serviceinstance. The template service broker will create and manage the templateinstance as well as the service itself, in your example above, Jenkins.

When service catalog is instructed to delete the serviceinstance, it will contact the template service broker to delete its instance. If there is a problem from the broker's side, the service catalog will continue attempting to delete the instance forever or until the template broker can remove its instance either because of some resource or other reason.

**Comment by greg-pendlebury** [comment]
> If there is a problem from the broker's side, the service catalog will continue attempting to delete the instance forever...

Interesting. That explains something else we saw, but I didn't mention because we couldn't reproduce. After deleting the finalizer, then the project, we created the project afresh and deployed Jenkins only to see it delete on us. We only happened once though, then the above errors related to mount permissions happened whenever we deployed.

**Comment by akram** [comment]
Hi @greg-pendlebury and @jmrodri  ,
@waveywaves and I (@akram) are maintaining the Jenkins images and templates for OpenShift, and we got another issue raised by a customer related to this thread.

Indeed, it is catching my eye that many issues related to this talk about Jenkins. So, we want to investigate more on our side also.
@greg-pendlebury you wrote previously that jenkins-ephemeral and jenkins-persistent templates share the same UID? can you elaborate on this? you mean 'uid' as the one generated in the template object? or you are referering to 'USER' directive in the Dockerfile ?

After all, the resolutions/workaround for jenkins seems to be "file permissions related".

**Comment by greg-pendlebury** [comment]
Hi @akram, 

The uid 'issue' was a red herring. I just incorrectly eyeballed two uids that were extremely similar:
`oc edit template jenkins-ephemeral -n openshift` => `uid: a4c43696-a208-11e9-a166-000d3ad2a02b`
`oc edit template jenkins-ephemeral -n openshift` => `uid: a4c73ce4-a208-11e9-a166-000d3ad2a02b`

Definitely wasn't talking about anything that qould correlate back to file permissions.
