### ISSUE TITLE
NodeJS+MongoDB example template only works with the example repo

### ISSUE THREAD

**Issue by ryanj** [openshift/origin#19379]
When using the provided NodeJS+MongoDB template, [custom health checks are included](https://github.com/openshift/origin/blob/master/examples/quickstarts/nodejs-mongodb.json#L217) that are [only resolved in the example repo](https://github.com/sclorg/nodejs-ex/blob/master/server.js#L80).  

Any users who provide a custom repo url will end up with failed deployments if their app does not respond on "/pagecount".

Ideas for a fix:
- Change the default probe url - use a path that is expected to be available on most new repos: replace "/pagecount" with "/"
- Include a disclaimer / warning stating that the example template is not meant to be used for development purposes. Remove the `SOURCE_REPOSITORY_URL` input if it's not meant to be altered.
- include a disclaimer / warning near the template's `SOURCE_REPOSITORY_URL` input - describe the expected runtime requirements (health checks will be performed on a non-standard "/pagecount" endpoint)

##### Version
v3.9.0

##### Steps To Reproduce
1. Add to Project > Browse Catalog
2. Select "NodeJS+MongoDB", then "Next"
3. Find the "Git Repository URL" input. Use our NodeJS+MongoDB roadshow example: http://github.com/openshift-roadshow/nationalparks-js
4. Click "Create"
5. The deployment fails to scale to "1" (liveness, readiness checks fail)

##### Current Result
When providing a custom repo: builds will work, but deployments will fail. I'd expect anyone who brings their own repo code will hit a similar deployment error due to this unpublished runtime requirement: liveness, readiness checks targeting "/pagecount"

##### Expected Result
For a PaaS: provided examples should be a good starting point for actual development (Deployments should not fail when I use my own repo).

**Comment by jwforres** [comment]
@openshift/sig-developer-experience do you guys still own this example or is this SCL?

**Comment by bparees** [comment]
> Change the default probe url - use a path that is expected to be available on most new repos: replace "/pagecount" with "/"

we don't use that because our E2E tests validate that that app is reporting the pagecount correctly and we don't want healthchecks incrementing it in the background.  The test could be made more flexible, but currently that's the main limitation.

@jwforres technically SCL owns the examples now, but if they change this they will break our image_ecosystem tests.  This is the fun world we live in.  So we'll need to collaborate on a fix...probably easiest for us to deliver the PR to their repo as we're updating our tests.

Definitely the path of least resistance is to make our E2E tests tolerate of any non-zero pagecount instead of expecting specific values.  But I think it might get tricky because of some of the hot deploy tests we run.  Anyway we'll start our investigation there.

**Comment by bparees** [comment]
@wozniakjan 

1) need to update our nodejs imageeco system tests to make their page count checking logic more tolerant
2) submit a change to the nodejs-ex repo's templates to change the readiness+liveness probes

**Comment by ryanj** [comment]
For context, I filed this issue based on partner feedback:  The user had expected the catalog entry to be a viable starting point for deploying an existing app that relies on NodeJS+MongoDB.  They already had a working repo, so they choose the "NodeJS+MongoDB" catalog item to launch it.  

I think our intention (currently) is to offer a catalog of examples that can be used as a development references. 

Traditional PaaS users might expect these catalog items to be useful for launching their own apps (in addition to the example repo).
