### ISSUE TITLE
Java mvn build that fails with "Generic Build failure” but no maven error should give a helpful error message

### ISSUE THREAD

**Issue by ge0ffrey** [openshift/origin#19450]
I build a maven project on OpenShift Dedicated with S2I, but the build fails with a "Generic Build failure - check logs for details."

![](https://i.stack.imgur.com/YXqar.png)

However, **the build log shows no error**. So there is no clue what can cause this.

![](https://i.stack.imgur.com/Kx5Lg.png)

Apparently, it might be because the maven build went out of memory (although the log would show that normally) or it was killed because a timeout passed and the build took too long. Either way, OpenShift should mention any of such things happening - for example at the end of the log file.

To reproduce, throw this into SI2: https://github.com/kiegroup/optashift-employee-rostering/tree/c1c0081287917ac8925c170d7325bafdfb3a8a16

Relates to https://stackoverflow.com/questions/49937464/openshift-java-maven-build-generic-build-failure-but-log-shows-no-error

**Comment by bparees** [comment]
yes most likely the container was oom killed for trying to exceed the resource limit.  because of the way builds work (spawning a separate container) k8s is left unaware of what happened.

ultimately we want to move away from doing builds in this way, so once we do that hopefully you'll be able to see a standard oom kill event on the build pod if this happens.

**Comment by bparees** [comment]
https://github.com/openshift/origin/pull/20297 will surface OOMKilled events to the build object.
