### ISSUE TITLE
1 ExistingPodsAntiAffinityRulesNotMatch, 1 MatchInterPodAffinity, 2 CheckServiceAffinity

### ISSUE THREAD

**Issue by priyanka5** [openshift/origin#19506]
I get this error in events - 0/3 nodes are available: 1 ExistingPodsAntiAffinityRulesNotMatch, 1 MatchInterPodAffinity, 2 CheckServiceAffinity

has anyone ever seen this error , pods are stuck in pending state, and I see this in events. Can anyone help me explaining what this means?

**Comment by jwforres** [comment]
@openshift/sig-pod

**Comment by aveshagarwal** [comment]
@priyanka5 agree with what @sjenning said above. Also would like to add that it seems that other 2 nodes (failing with CheckServiceAffinity) seems to have different labels than the first node. Could you verify it?

Seems like what is happening is that when first pod is scheduled to the one node (failing with ExistingPodsAntiAffinityRulesNotMatch,), no other pods can be scheduled to this node due to anti-affinity. However, ServiceAffinity is trying to spread the other pods to the nodes with similar labels but other 2 nodes seem to have some different labels than first node.

**Comment by priyanka5** [comment]
@sjenning thanks , @aveshagarwal  yes I added same value to  label region to all 3, then serviceAffinity error goes :)  thanks I will keep you informed if I face other issue

**Comment by aveshagarwal** [comment]
@priyanka5 if your issue is resolved, could you close it? You can always reopen if you have similar issue or create a new issue for any other errors.
