### ISSUE TITLE
Operation cannot be fulfilled on namespaces (extended image ecosystem tests failure)

### ISSUE THREAD

**Issue by coreydaley** [openshift/origin#19513]
"Operation cannot be fulfilled on namespaces "<namespace>": The system is ensuring all content is removed from this namespace.  Upon completion, this namespace will automatically be purged by the system.

https://ci.openshift.redhat.com/jenkins/job/test_branch_origin_extended_image_ecosystem/458/

**Comment by bparees** [comment]
@coreydaley you may need to pull in the master team, but since we're only seeing this on our pipeline test, for now i'm going to assume it's something specific we are doing in that test.

**Comment by gabemontero** [comment]
Based on
- the description of https://github.com/openshift/origin/commit/9404da7a04f2ae0e2e0e699a48b4f6a51c56ced8 from @smarterclayton 
- when the commit dropped (Apr 23)
- when we started seeing these failures (I believe the first instance was early morning Apr 24 with run https://ci.openshift.redhat.com/jenkins/job/test_branch_origin_extended_image_ecosystem/457/)

Either the changes to that commit need to be adjusted, or we need to make changes in our ext tests since the above commit `Makes openshift e2e tests manage their own namespaces`
