### ISSUE TITLE
Cmd test fails "oc delete all -l app=testapp2"

### ISSUE THREAD

**Issue by adambkaplan** [openshift/origin#19588]
Test flake in cmd tests - the "delete all" test seems to fail, potentially because the application under test has already been deleted.

##### Version
v3.10.0-alpha0

##### Current Result
Test failure: github.com/openshift/origin/test/cmd/newapp test/cmd/newapp.sh:428: executing 'oc delete all -l app=testapp2' expecting success 1.66s

##### Expected Result
Test passes.

##### Additional Information
Failed test: https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/19532/test_pull_request_origin_cmd/13227/
Logs:
```
=== BEGIN TEST CASE ===
test/cmd/newapp.sh:428: executing 'oc delete all -l app=testapp2' expecting success
FAILURE after 1.658s: test/cmd/newapp.sh:428: executing 'oc delete all -l app=testapp2' expecting success: the command returned the wrong error code
Standard output from the command:
deploymentconfig.apps.openshift.io "testapp2" deleted
buildconfig.build.openshift.io "testapp2" deleted
imagestream.image.openshift.io "testapp2" deleted

Standard error from the command:
Error from server (NotFound): builds.build.openshift.io "testapp2-1" not found
=== END TEST CASE ===
```

**Comment by jwforres** [comment]
@openshift/sig-developer-experience

**Comment by bparees** [comment]
this is really an issue w/ how oc delete operates, what is happening is the buildconfig is deleted which triggers reaping (GC i think?) of the builds.  Regardless, oc delete has already grabbed the list of builds while it still existed, and then when it tries to delete it, finds it is already deleted.

there is already an open issue for this, hopefully @soltysh  or @juanvallejo  know where it is (they own it).

That said, we can make the test more robust by explicitly deleting the resources we created, rather than "all".  @adambkaplan  can you make that change and close this issue w/ the PR?

(I think getting oc delete fixed is blocked by upstream, but the correct behavior imho would be to ignore or warn when trying to delete things that are already gone, not error)

**Comment by deads2k** [comment]
I accidentally fixed this in https://github.com/openshift/origin/pull/19616
