### ISSUE TITLE
extended_conformance_install failing with  "Error response from daemon: no such id: openshift/origin:v3.10"

### ISSUE THREAD

**Issue by sjenning** [openshift/origin#19582]
test_pull_request_origin_extended_conformance_install started failing today at about 1020AM with:

`Error response from daemon: no such id: openshift/origin:v3.10"`

https://openshift-gce-devel.appspot.com/builds/origin-ci-test/pr-logs/directory/test_pull_request_origin_extended_conformance_install

@stevekuznetsov @smarterclayton @jpeeler

**Comment by sjenning** [comment]
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/19514/test_pull_request_origin_extended_conformance_install/11077/
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/19580/test_pull_request_origin_extended_conformance_install/11078/
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/19576/test_pull_request_origin_extended_conformance_install/11079/

After that, seems to be masked by yet another issue.

**Comment by smarterclayton** [comment]
I temporarily disabled this and notified vadim

On May 1, 2018, at 4:09 PM, Seth Jennings <notifications@github.com> wrote:

test_pull_request_origin_extended_conformance_install started failing today
at about 1020AM with:

Error response from daemon: no such id: openshift/origin:v3.10"

https://openshift-gce-devel.appspot.com/builds/origin-ci-test/pr-logs/directory/test_pull_request_origin_extended_conformance_install

@stevekuznetsov <https://github.com/stevekuznetsov> @smarterclayton
<https://github.com/smarterclayton> @jpeeler <https://github.com/jpeeler>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/origin/issues/19582>, or mute the thread

**Comment by smarterclayton** [comment]
@vrutkovs
