### ISSUE TITLE
test flake: Timeout due to ruby version mismatch in docker source image tests

### ISSUE THREAD

**Issue by adambkaplan** [openshift/origin#19608]
Extended test `[Feature:Builds][Slow] build can have Docker image source creating a build with an input source image and docker strategy` times out because underlying Docker build fails.

Root cause - ruby version mismatch leads to error running `scl enable rh-ruby22`

##### Version
v3.10.0-alpha0

##### Current Result
Test times out - underlying build errors.

##### Expected Result
Test passes

##### Additional Information
Test Log: https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/19532/test_pull_request_origin_extended_builds/1572/

**Comment by adambkaplan** [comment]
/assign @adambkaplan

@openshift/sig-developer-experience

**Comment by bparees** [comment]
@adambkaplan this test doesn't actually care if the build succeeds or not, so actually these builds always fail.  Fixing it is good to avoid confusion, but it's not the root cause of the test failure.

I think what actually happened here is the build transitioned from new to failed so fast that this check:
```				
g.By("expecting the build pod to start running")
pods, err := exutil.WaitForPods(oc.KubeClient().Core().Pods(oc.Namespace()), dockerBuildLabel, exutil.CheckPodIsRunningFn, 1, 2*time.Minute)
```

never saw the pod as running.  we should make that check more robust.  (Making it wait for the pod to terminate isn't a good solution because it makes the test take longer than necessary...we should wait for the pod to be running || terminated).

I'm going to remove the "fix" comment from your other PR so this issue stays open for a proper solution, but i'll merge it to clean up the confusing failure message.  (Admittedly that will probably fix this flake because the builds will always take much longer w/ that fixed, but i'd still rather fix this correctly)

**Comment by bparees** [comment]
(actually i don't know that this test even needs the pod to be running, i think it just needs the pod to exist, so that might be an easier check to implement)

**Comment by bparees** [comment]
that's weird, i definitely removed your "fixes" text from the PR, dunno why this got closed.  reopening per my comments above.

**Comment by bparees** [comment]
Ah, probably. I looked at that but I guess github just showed me the first line of the text. [shrug]
