### ISSUE TITLE
new_build timeout - can it be increased ?

### ISSUE THREAD

**Issue by oeresundsgruppen** [openshift/origin#19700]
Getting:

Error from server (Timeout): Timeout: timed out waiting for build XXX to start after 10s

oc new-build.... this is not re-produceable, and works 90% of the time, but fails at times, so need the command to wait bit longer...

**Comment by jwforres** [comment]
@openshift/sig-developer-experience

**Comment by bparees** [comment]
@oeresundsgruppen do you mean `start-build`?  I don't think new-build ever waits for the build.  Can you give me your exact command invocation?

We are addressing the logs timeout issues here: https://github.com/openshift/origin/pull/19695

**Comment by oeresundsgruppen** [comment]
Great you are looking into this - we use cmd-lines like : oc --namespace=XX --loglevel=1 new-build https://gitlab.XX --context-dir=deploy --image-stream='XX:0.1' --to=XX --allow-missing-images=true --name=XX -l jenkins=XX --strategy=docker --to-docker=true -o=name

**Comment by oeresundsgruppen** [comment]
can give --request-timeout a try...

**Comment by bparees** [comment]
i don't think --request-timeout will make a difference, but i'm still unclear on why you'd be getting a "timeout waiting for build to start" from that invocation, unless it's related to the -o=name flag.  i'll have to look into it further.

**Comment by adambkaplan** [comment]
@oeresundsgruppen can you please re-run the command with `--loglevel=8` and attach the log here? We'd like to see what is going on, even if the timeout error does not occur.

**Comment by bparees** [comment]
@oeresundsgruppen you can put it in gist.github.com.  Just redact any sensitive information.

**Comment by oeresundsgruppen** [comment]
Log file now in https://gist.github.com/oeresundsgruppen/19826bbbcba02d7486c949789da8a492

**Comment by bparees** [comment]
it looks like you're running a pipeline and the pipeline is executing first `oc new-build` and then `oc logs` and it is the `oc logs` command which is timing out, not `oc new-build`, which makes much more sense.

since https://github.com/openshift/origin/pull/19695 increased the length of time to wait for the build to start from 10s to 30s, this is probably resolved for you in master.

we also have a feature planned to introduce of "oc build status" command or something along those lines which will wait for build completion before returning.  Once that exists you could run that command before running oc logs, to ensure the logs will be available.

In the meantime, you may simply have to wrap your `oc logs` command in a retry to handle the possibility that it times out.

closing this as i think my comments resolve it, but please comment back if you have further concerns.

/close
