### ISSUE TITLE
Seems egress router not works with other cni plugin

### ISSUE THREAD

**Issue by jeffrey4l** [openshift/origin#19780]
The egress router works find when using openshift sdn. But not when using calico plugin. 
the macvlan0 devices seems not added when using calico plugin. 

So question is:

- is egress router supports other cni plugin?
- if so how can i make it work?

##### Version

    origin 3.9

**Comment by jwforres** [comment]
@openshift/sig-networking

**Comment by danwinship** [comment]
Right. The egress router uses a custom annotation to get openshift-sdn to create a macvlan for it.

In the future, when the whole "multi-network" thing is worked out, we can redo it so that it uses two CNI plugins, one for the ordinary network connection, and one for the macvlan, and in that case you'd be able to use an alternative plugin for the "ordinary" connection. But for now, egress-router is openshift-sdn-only.
