### ISSUE TITLE
Can't login to egde terminated route for registry

### ISSUE THREAD

**Issue by praveenkumar** [openshift/origin#19844]
##### Version
$ ./oc version
oc v3.10.0-alpha.0+2dcfb32-1299
kubernetes v1.10.0+b81c8f8
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://192.168.42.111:8443
openshift v3.10.0-alpha.0+2dcfb32-1299
kubernetes v1.10.0+b81c8f8

##### Steps To Reproduce

```
$ oc create route edge docker-registry --service=docker-registry -n default --hostname='docker-registry-default.192.168.42.111.nip.io'
$ sudo mkdir -p /etc/docker/certs.d/docker-registry-default.192.168.42.111.nip.io
$ sudo chown docker /etc/docker/certs.d/docker-registry-default.192.168.42.111.nip.io
$ cp /var/lib/minishift/base/kube-apiserver/ca.crt /etc/docker/certs.d/docker-registry-default.192.168.42.111.nip.io
$  docker login -u developer -p `oc whoami -t` docker-registry-default.192.168.42.110.nip.io
Error response from daemon: Get https://docker-registry-default.192.168.42.110.nip.io/v1/users/: x509: certificate is valid for *.router.default.svc.cluster.local, router.default.svc.cluster.local, not docker-registry-default.192.168.42.110.nip.io
```

##### Current Result
```
Error response from daemon: Get https://docker-registry-default.192.168.42.110.nip.io/v1/users/: x509: certificate is valid for *.router.default.svc.cluster.local, router.default.svc.cluster.local, not docker-registry-default.192.168.42.110.nip.io
```
##### Expected Result
Should able to login.

##### Additional Information
These steps work perfectly on the oc-3.9 binary but not working with latest master binary.

@mfojtik Please assign to relevant folks for this.

**Comment by deads2k** [comment]
The router is a component installed using cluster add.  The components are owned by the individual component owners.  

See the code here: https://github.com/openshift/origin/tree/master/pkg/oc/clusteradd/components/router

@mfojtik is it them or @openshift/sig-networking ?

**Comment by ironcladlou** [comment]
Might be a few days before anybody looks at this unless it's blocking the 3.10 release; /cc @ramr

**Comment by ramr** [comment]
Based on the error message you had:

### Error:
Error response from daemon: Get https://docker-registry-default.192.168.42.110.nip.io/v1/users/: x509: certificate is valid for *.router.default.svc.cluster.local, router.default.svc.cluster.local, not docker-registry-default.192.168.42.110.nip.io


Which means the router is ok but the error you are getting is coming back from the docker daemon. Not sure what the version of the docker daemon you have is? But it is more than likely, the version of docker you have is being correct (stricter) in checking that the certificate presented by the router matches the request host. 

So it is possible that maybe the previous versions you had were a bit lax in checking for this but this looks to be correct. Or then were you passing in a certificate when you created a route for the registry? That might not be set?
Run: `oc get route <your-registry-route> -o yaml` and check the cert, ca and key information.

Without having more context, can't tell your case but It looks more like you probably want to use option 1 in the `fixes` section below.


### Details: 
Since you are creating a router without passing in a certificate, the router will generate a certificate but it will be for the default name: `*.router.default.svc.cluster.local`.
And that name  `*.router.default.svc.cluster.local` will not match your registry name  `docker-registry-default.192.168.42.110.nip.io`.
Even though the signer/CA might be the same, the certificate is valid only for hosts named `*.router.default.svc.cluster.local`.

### Fixes:
1. Pass a correct certificate [+ca+key] for the route you created for the docker registry. 
`oc create route edge <name> --cert=/path/to/cert --key=/path/to/key --ca-cert=/path/to/ca-cert --hostname="registry-default.192.168.42.110.nip.io" --service=<docker-registry-service-name>... `  
   [You can get the docker registry service name via `oc get services`]

2. If you still want to use the default router certificate, then you will need to use a docker registry host name that is within that subdomain of the certifcate the router - e.g. `"docker-registry-default.router.default.svc.cluster.local`
 `oc create route edge <name> --hostname="docker-registry-default.router.default.svc.cluster.local"  --service=<docker-registry-service-name> ...`


3. Or if you want to change the default router certificate to `*.192.168.42.110.nip.io`, you can do that by generating a new wildcard certificate for that host and "bundle" the certificate, CA and key into a single PEM file and create the router using: 
`oc adm router --default-cert=/path/to/bundled/cert+ca+key.pem ...`

It looks like option 1 [more so that maybe option 2] above might be the simplest and possibly the most relevant option for you.

**Comment by mfojtik** [comment]
@bparees since this was working out of box I guess in 3.9, this looks like a regression in 3.10. The minishift folks can fix that, but I think we can do this step in registry cluster up installer. I will defer to registry guys to pick the fix they prefer.

**Comment by praveenkumar** [comment]
I am going to close this issue after having the conversation with @mfojtik for the current location of kubeconfig file.

**Comment by JakhongirAlimov** [comment]
i understood here just only discussion room , nobody could not solve problem useless
