### ISSUE TITLE
resolve handling of RootFsInfo() error on kubelet start

### ISSUE THREAD

**Issue by liggitt** [openshift/origin#19948]
follow-up from https://github.com/openshift/origin/pull/19137

https://github.com/openshift/origin/commit/b61c00c7ff95788abd5e76025fbda0074119ec3f made the RootFsInfo() lookup failure on kubelet startup non-fatal because it was blocking CI (it fails when run on tmpfs/bindmounts I think)

need to determine the impact of continuing the kubelet even without the EphemeralStorageCapacityFromFsInfo results

**Comment by sjenning** [comment]
https://github.com/kubernetes/kubernetes/pull/65595

**Comment by sjenning** [comment]
@liggitt since https://github.com/openshift/origin/commit/b61c00c7ff95788abd5e76025fbda0074119ec3f is already in 3.11 and the upstream PR kubernetes/kubernetes#65595 does roughly the same thing do we want to

1. revert the drop comment and pick the upstream one for 3.11 or
2. stay for 3.11 and get the upstream fix in the 3.12 rebase

**Comment by liggitt** [comment]
if we don't plan to enable the feature in 3.11, it's largely moot. if we do, then we should revert/pick that PR, right?

**Comment by sjenning** [comment]
agreed.  I'll keep this in mind if we decide to go forward with LSI in 3.11 (which would be a stretch, I think)
