### ISSUE TITLE
Unable to reconcile bootstrap cluster roles{-bindings} without backup file

### ISSUE THREAD

**Issue by nak3** [openshift/origin#20040]
##### provide a description of the issue

- Although `oc adm policy reconcile-cluster` is deprecated and it suggests `oc auth reconcile`, `oc auth reconcile` needs a FILE to specify and reconcile. Hence wihtout backup it is not possible to reconcile default(bootstrap) roles.

```
$ _output/local/bin/linux/amd64/oc adm policy reconcile-cluster-roles
Command "reconcile-cluster-roles" is deprecated, use 'oc auth reconcile'
```

##### Version

```
oc v3.10.0-alpha.0+9c74c08-1495-dirty
```

##### Current Result
- No way to reconcile bootstrap cluster roles without backup files.
- Needs some commands to call `GetBootstrapClusterRoles()` in pkg/cmd/server/bootstrappolicy/policy.go 

##### Additional Information
- I know restarting master services reconcile it, but it would be better to reconcile without restart.

**Comment by nak3** [comment]
ping @enj I think you developed oc auth reconcile. Is there any way to achieve this?

**Comment by enj** [comment]
> you developed oc auth reconcile

You are giving me too much credit 😁

https://docs.openshift.org/latest/admin_guide/manage_rbac.html#updating-policy-definitions is incomplete and partially incorrect but it provides an example on how to do this.

`oc adm create-bootstrap-policy-file --filename=policy.json` is the important bit.

Please close if that works for you.

**Comment by nak3** [comment]
Thank you. So, if we did not have `policy.json` by `oc adm create-bootstrap-policy-file --filename=policy.json` beforehand, it is not possible to restore default clsuter-role? (Or `/etc/origin/master/policy.json` on OCP can be used?)

Having said that, I think that `oc adm create-bootstrap-policy-file --filename=policy.json` will not restore cluster roles as `oc adm policy reconcile-cluster-roles`. Please see below:

~~~
  # oc adm create-bootstrap-policy-file --filename=policy-tmp.json
  # oc edit clusterrole admin

// remove pods from clusterrole admin
BEFORE:
```
rules:
- apiGroups:
  - ""
  attributeRestrictions: null
  resources:
  - pods
  - pods/attach
```

AFTER:
```
rules:
- apiGroups:
  - ""
  attributeRestrictions: null
  resources:
  - pods/attach
```

  // oc auth reconcile does not recocile it.
  # oc auth reconcile -f policy-tmp.json 
  #

  // oc adm policy reconcile-cluster-roles outputs reconcile it.
  # oc adm policy reconcile-cluster-roles --confirm -o name
  clusterrole/admin
~~~

Anyway I need to know my first question (=it is not possible to restore default clsuter-role without policy.json?) in this report.

**Comment by enj** [comment]
> if we did not have policy.json by oc adm create-bootstrap-policy-file --filename=policy.json beforehand, it is not possible to restore default clsuter-role?

Correct.  This is the expected behavior.  The deprecated reconcile commands will be removed in a future release.

> (Or /etc/origin/master/policy.json on OCP can be used?)

Do not use that file, as you have no way to know what it contains.  Use `oc adm create-bootstrap-policy-file` with and `oc` binary that matches the version of `openshift` being used (and see below).

> I think that oc adm create-bootstrap-policy-file --filename=policy.json will not restore cluster roles

You need to use the latest `oc` from master for it work (the policy file has the wrong format for `auth reconcile`).  This is why the deprecated commands have not been removed.  Once the docs are sorted and `auth reconcile`/`create-bootstrap-policy-file` work as expected, then the deprecated commands will be dropped.  So today your options for restoring are: use the deprecated command, restart a master or use the latest `oc`.

In practice none of this matters since all masters get restarted on upgrades and that is usually all that is needed.

**Comment by nak3** [comment]
Thank you. I understand.

> Use oc adm create-bootstrap-policy-file with and oc binary that matches the version of openshift being used

It sounds like running `create-bootstrap-policy-file`/`auth reconcile` with mismatched oc and server(openshift binary) causes serioous issue.. Error or warning will not be implemented for this? Another command's same issue https://github.com/openshift/origin/pull/19843 is disregarded, though...

Anyway, I got an answer what I wanted, so please feel free to colse this report.

P.S. I wanted `adm create-bootstrap-policy-file` to output into stdout rather than file. We cannot use pipe like `oc adm create-bootstrap-policy-file | oc auth reconcile -f -`.  :cry:

**Comment by enj** [comment]
> with mismatched oc and server(openshift binary) causes serioous issue

It is no different than `reconcile-cluster-roles` so nothing to worry about.  In the worse case we add something back that we "removed" in a later release, which is always fine because we know we cannot rely on any such behavior (since we never remove anything).

> Error or warning will not be implemented for this

No.  This is exactly why the reconciliation was moved to the server.  You are responsible for knowing what you are doing if you want to mess with this stuff directly.

> Another command's same issue #19843 is disregarded, though

I closed that PR since it is simply incorrect.  Feel free to ping me on IRC if you need further explanation.

> We cannot use pipe like oc adm create-bootstrap-policy-file | oc auth reconcile -f -

I have no issue with such a change.  @openshift/cli-review may have other opinions.

**Comment by enj** [comment]
@nak3 can we close this?

**Comment by nak3** [comment]
Sure, I am closing it now.

**Comment by nak3** [comment]
Oh, that is nice! thank you @enj
