### ISSUE TITLE
File permission issue in application container: Failed to open '/proc/1/fd/2' as root: Permission denied

### ISSUE THREAD

**Issue by anjannath** [openshift/origin#20204]
The issue was originally filed as https://github.com/minishift/minishift/issues/2058

[Copied from the there]
/cc @mhabrnal @xsuchy

I've prepared docker image [1] with suided application which just takes an argument and writes it into /proc/1/fd/2.

[1] https://hub.docker.com/r/mhabrnal/logger-test/

Inside of the image, there is setuid binary (similar to /usr/bin/sudo). When you execute setuid binary owned by root, you should get EUID=0. That works as expected.

So we have binary with EUID=0. But when this binary tries to write to file which is owned by 1000070000:root then it gets "permission denied". This is IMO bug because process with EUID should be able to write to such file.

##### Version
oc v3.9.0+191fece
kubernetes v1.9.1+a0ce1bc657
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://api.starter-ca-central-1.openshift.com:443
openshift v3.10.9
kubernetes v1.10.0+b81c8f8

##### Steps To Reproduce
```
$ oc projects
You have one project on this server: "lkdsjflslfdjsdkf".

Using project "lkdsjflslfdjsdkf" on server "https://api.starter-ca-central-1.openshift.com:443".

$ oc new-app mhabrnal/logger-test
--> Found Docker image b2d2381 (4 months old) from Docker Hub for "mhabrnal/logger-test"

    * An image stream will be created as "logger-test:latest" that will track this image
    * This image will be deployed in deployment config "logger-test"
    * The image does not expose any ports - if you want to load balance or send traffic to this component
      you will need to create a service with 'expose dc/logger-test --port=[port]' later
    * WARNING: Image "mhabrnal/logger-test" runs as the 'root' user which may not be permitted by your cluster administrator

--> Creating resources ...
    imagestream "logger-test" created
    deploymentconfig "logger-test" created
--> Success
    Run 'oc status' to view your app.
$ oc get pods
NAME                  READY     STATUS    RESTARTS   AGE
logger-test-1-sgj9t   1/1       Running   0          28s
$ oc rsh logger-test-1-sgj9t
sh-4.4$ ls
bin  boot  dev	etc  home  lib	lib64  lost+found  media  mnt  opt  proc  root	run  sbin  srv	sys  tmp  usr  var
sh-4.4$ /usr/libexec/suid-logger 
Failed to open '/proc/1/fd/2' as root: Permission denied
sh-4.4$ echo "1" | /usr/libexec/suid-logger 
sh-4.4$ ls -l /usr/libexec/suid-logger      
-rwsr-xr-x. 1 root root 816080 Feb 26 15:09 /usr/libexec/suid-logger
sh-4.4$ ls -l /proc/1/fd/2             
l-wx------. 1 1050940000 root 64 Jul  4 10:40 /proc/1/fd/2 -> pipe:[1906988953]
```

**Comment by jwforres** [comment]
@openshift/sig-pod @openshift/sig-storage

**Comment by sjenning** [comment]
This was pretty much covered in minishift/minishift#2058 but you can not become root inside a container on OpenShift Online.  Kubernetes does not yet support user namespaces which should allow this, but currently, you have to be in the `anyuid` or `privileged` SCC to do this.

However, for your application, you don't *need* to be root as /proc is owned by the UID running the container process (1050940000).  You should not need to do the setuid.

**Comment by joelsmith** [comment]
This application works for me on a vanilla origin v3.9.0+71543b2-33 cluster. I don't get the permission denied error.  On my system, an app runs by default in the `restricted` scc. This scc only drops the following capabilities: `KILL`, `MKNOD`, `SETUID`, `SETGID`.  So because it doesn't drop `DAC_OVERRIDE`, on my system a setuid-root binary is able to open and write `/proc/1/fd/2`.

Here's how you can check to see what capabilities your root user would have:
```
$ capsh --decode=$(oc rsh $(oc get pod -l app=logger-test -o jsonpath="{.items[0].metadata.name}") sed -n s/CapBnd:.//p /proc/1/status)
0x00000000a004251b=cap_chown,cap_dac_override,cap_fowner,cap_fsetid,cap_setpcap,cap_net_bind_service,cap_net_raw,cap_sys_chroot,cap_audit_write,cap_setfcap
```
Your application probably needs `DAC_OVERRIDE` at a minimum (if you really want to run that application as root).

These capabilities come from the scc used by your application. You can see which scc your application is using like this:

```
oc get pod -o yaml | grep -i openshift.io/scc
```

and you can modify the set of capabilities that the scc drops when launching containers by editing the scc in question:

```
oc edit scc foo
```

but be warned that you are modifying permissions of every app in the cluster that uses the scc you're modifying. That could potentially open your cluster up to easy compromises. You might be better off creating a new scc that is a copy of that old one with your new changes, then adding the service account for your project to that new scc.

I don't think this is a bug at all, but just potentially a restrictive scc in use, and modifying it should fix the issue, although as @sjenning said above, you really don't even need to run as root to write to `/proc/1/fd/2` since the user that your pod runs as can write to that fd.  I'm going to close this since I'm not convinced there is any bug.
