### ISSUE TITLE
Permissions being changed in mounted PVCs

### ISSUE THREAD

**Issue by tdudgeon** [openshift/origin#20234]
I've encountered occasions where file permissions in a directory change and present a pod from starting.
What causes this to happen is very unclear. It's been seen for the docker registry pod and for the metrics cassandra pod. Details were reported on the user mailing list here:
https://lists.openshift.redhat.com/openshift-archives/users/2018-July/msg00001.html

In both cases (registry and cassandra) the pods had been running for some time without problem.
Something happened and the pods restarted but failed to start because the permissions on the directories inside the PVC being used by the pod had been changed. The ownership has been set to a user such as 1000040000.65534 which looks very much like an openshift assigned user ID, but those should not be being used for the registry or cassandra containers. One the permissions were set to those the user that the container was running as could no longer write to the directory(ies).
Manually fixing the ownership of the directories allows the pod to start again. 

See the mailing list thread for specific details.

##### Version

openshift v3.7.2+cd74924-1
kubernetes v1.7.6+a08f5eeb62

Openshift was installed using the ansible playbooks.

**Comment by gnufied** [comment]
Looking at the mailing list thread, it could have happened because of change in SCC being applied to the pod. It appears that earlier applied SCC was "anyuser" and the new SCC is restricted which is auto allocating user/groups for your pod.

I am not sure - what caused this, but https://docs.openshift.com/container-platform/3.9/install_config/persistent_storage/pod_security_context.html should clarify some of the inner wrorking.

**Comment by tdudgeon** [comment]
@gnufied That sounds plausible, but I'm not sure how it would have happened. The 2 examples I mention on the mailing list relate to the openshift registry and the hawkular metrics which are both entirely set up by the ansilbe installer and we never mess with the SCC for those projects. So not sure how the SCC could have changed.
