### ISSUE TITLE
OpenShift Routes limit in Namespace and Cluster

### ISSUE THREAD

**Issue by borntorock** [openshift/origin#20406]
Since it was not mentioned in the cluster limits here: https://docs.openshift.com/container-platform/3.9/scaling_performance/cluster_limits.html,

we want to know if there has been scalability tests on the limit of the OpenShift routes that can be created in the particular namespace and in particular OpenShift cluster.

**Comment by jwforres** [comment]
@openshift/sig-network-edge

**Comment by borntorock** [comment]
@ironcladlou Any update on this?

**Comment by borntorock** [comment]
@openshift/sig-network-edge Can you someone Please help with this.

**Comment by ironcladlou** [comment]
@jmencak any data you could share here?

**Comment by jmencak** [comment]
Since OCP 3.6, I regularly test the router with up to 2000 routes split into 40 projects without any issues.  There was an [issue](https://bugzilla.redhat.com/show_bug.cgi?id=1471899]) in 3.6 with more than cca 3300 routes, but that has since been fixed.  Doing a quick test as described in the issue and currently have around 6000 routes per 1 namespace on 3.11, routes work and still happily creating new routes.  Is there a use-case to go beyond that?
