### ISSUE TITLE
High rate of stdout writes from containers causes decreased performance

### ISSUE THREAD

**Issue by calston** [openshift/origin#20444]
This probably seems obvious, but if you have a bunch of small docker containers with even minimal resources attached to them it's possible for them to produce a very high rate of writing to standard output which will then result in large IO writing to syslog, and then even further resource consumption from Fluent ingesting those logs into Elasticsearch.

Effectively this means a tenant could DoS the cluster, impacting all other services.

I can't find or think of a particularly good way to deal with this which doesn't have a lot of drawbacks. Possibly CRI-O has better logging drivers than Docker to handle container standard output more efficiently but I'm not sure.

I wanted to open this issue to draw attention to this concern and see if there are some ideas. 

##### Version
All
##### Steps To Reproduce
1. Produce I high rate of standard output from docker containers

##### Current Result
Extremely high resource utilisation on nodes, reducing performance of other containers.

##### Expected Result
Unknown.

**Comment by jwforres** [comment]
@openshift/sig-logging @openshift/sig-containers

**Comment by richm** [comment]
Is this docker with --log-driver=json-file or --log-driver=journald?   If you aren't sure, do you have `/var/log/containers/*.log` on your nodes?
Is there a particular process that has high resource utilisation on nodes?  e.g. does `top` show that docker has very high cpu/ram/io usage?

**Comment by calston** [comment]
Docker doesn't have usage noticeably higher than normal. Fluentd is pretty much at 100% on the other hand, but at least within its container resource constraints. Of course there's no cgroup for IO (yet). 

This is using journald log driver as per the default openshift ansible configuration with elastic logging.

It could of course be possible to turn off the tee from journald to syslog which might conserve some IO, but this also means loosing all debug opportunity if elasticsearch is behind on indexing or offline.

**Comment by richm** [comment]
fluentd cpu won't get past 100% - single threaded, especially reading from the journal because only 1 fluentd thread/process can read from the journal at a time, regardless

> This is using journald log driver as per the default openshift ansible configuration with elastic logging.

that default has changed over time - you did not specify which version of openshift origin you are using - at some point it was changed to json-file, which may work better for your particular situation - when using docker with json-file log driver, openshift logging fluentd has support for log record throttling based on namespace/project - see https://docs.openshift.org/3.9/install_config/aggregate_logging.html#aggregated-fluentd "Throttling logs in Fluentd"

with openshift 3.6 and later, you can deploy with docker log-driver=json-file - both json-file and journald are supported

> It could of course be possible to turn off the tee from journald to syslog

by "syslog" do you mean "rsyslog"?  If so, then yes, it could save some cycles, but only if you see rsyslog consuming a significant amount of cpu/ram resources, and note that this will mean no more data to `/var/log/messages`, which isn't necessarily a bad thing . . .

> this also means loosing all debug opportunity if elasticsearch is behind on indexing or offline

. . . because your data will still be in the system journal available with `journalctl`, so you won't be "losing" anything.
