### ISSUE TITLE
Suggestion for a new feature: livetime for RoleBinding

### ISSUE THREAD

**Issue by IlonkaO** [openshift/origin#20449]
Suggestion for a new feature

I have actually the challenge to grant temporary access for users.
It would be great to get a possibility to describe a lifetime for example to a RoleBinding.

Regards Ilonka

**Comment by jwforres** [comment]
@openshift/sig-security

**Comment by simo5** [comment]
What is a lifetime for a rolebinding ?
Wouldn't this be easier to do by adding and removing users from groups as needed and keeping a fixed rolebinding ?

**Comment by enj** [comment]
Both role bindings and group are insufficient to truly have temporary access.  For example, during the time of access the user could save service account tokens to use after the access expires.  They could set up a service to proxy their requests.  In general it is possible to escalate or otherwise maintain access.  It is possible through some effort and OAuth to get a close approximation of the desired temporary access (I will write out the steps for this when I have some time).

I am going to close this as the same issue is already being tracked in https://bugzilla.redhat.com/show_bug.cgi?id=1461011.
