### ISSUE TITLE
enabling unsafe sysctls in OSO 3.9

### ISSUE THREAD

**Issue by pheitman** [openshift/origin#20470]
I need to set some sysctls in a couple of my DeploymentConfigs for their pods. I have followed https://docs.openshift.com/container-platform/3.9/admin_guide/sysctls.html but when I deploy the pods they are not created. My dc template file contains:

    template:
      metadata:
        labels:
          app: cl
        annotations:
          openshift.io/scc: "${PROJECT}"
          **security.alpha.kubernetes.io/sysctls: net.ipv4.ip_local_port_range=9000 65500
          security.alpha.kubernetes.io/unsafe-sysctls: net.core.rmem_default=4194304,net.core.rmem_max=16777216,net.core.wmem_default=262144,net.core.wmem_max=16777216,net.ipv4.tcp_rmem=4096 87380 16777216,net.ipv4.tcp_wmem=4096 65536 16777216**
      spec:
        terminationGracePeriodSeconds: 20

and I have updated the node-config.yaml file with

kubeletArguments:
  node-labels:
  - role=app
  **experimental-allowed-unsafe-sysctls:
  - "net.*"**

On the minions I have the same values set for those sysctls at the host level.

I have also tried updating my SCC with 

  **allowedUnsafeSysctls:
  - net.core.*
  - net.ipv4.***

The pods are not getting scheduled because of errors like:

  Warning  FailedCreatePodSandBox  7m (x4 over 7m)   kubelet, ph-dev-psh67-minion1.hcl.com  Failed create pod sandbox: rpc error: code = Unknown desc = failed to start sandbox container for pod "cl-1-cntjl": Error response from daemon: oci runtime error: container_linux.go:247: starting container process caused "process_linux.go:364: container init caused \"open /proc/sys/net/ipv4/tcp_rmem: no such file or directory\""

For some reason OSO recognizes that I am attempting to set unsafe sysctls but does not recognize that the node has explicitly enabled those unsafe sysctls

Peter

##### Version
oc v3.9.0+ba7faec-1
kubernetes v1.9.1+a0ce1bc657
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://ph-dev-psh67-master.hcl.com:8443
openshift v3.9.0+ba7faec-1
kubernetes v1.9.1+a0ce1bc657

##### Steps To Reproduce
See Description above

##### Current Result
Pods are not getting created

##### Expected Result
Pods get created and when I exec in to the pod /proc/sys/net/core/* contains the sysctls I have set in the DeploymentConfig

**Comment by enj** [comment]
@openshift/sig-security @stlaz

**Comment by stlaz** [comment]
I was able to reproduce your issue on the `release-3.9` branch. It seems that the node somehow ignores the settings from `kubeletArguments`. It might be a bug, I'll need to investigate some more.
Please note that the `allowedUnsafeSysctls` and `forbiddenSysctls` fields were just added to SCCs in 3.11 and thus should have no effect in 3.9.

**Comment by pheitman** [comment]
Thank you for looking in to this - the deployment of our application on OpenShift requires that we find a way to achieve this. As for the allowedUnsafeSysctls and forbiddenSysctls I only did this after trying everything else I could think of. I was just reaching :)

**Comment by stlaz** [comment]
So after I managed to reproduce this on pure Kubernetes master, I realized the problem might be somewhere else. If you try to do `docker run --rm -ti --sysctl net.core.rmem_default=4194304 alpine:latest sh `, you'll see the same failure again.

The reason to all of the above is because kernel does not namespace certain `net.*` sysctls as by setting them, they could apparently still negatively affect the rest of the system.

You can read some more information on this topic in https://github.com/moby/moby/issues/30778 which seems to be the issue that people mention the most when it comes to this problem (there are some mentions of `net.core.rmem_*` sysctls in https://github.com/moby/moby/issues/35279 or https://github.com/moby/moby/issues/4717). There  was a kernel patch which should allow setting this in a container (see the mailing thread in https://marc.info/?m=150108862000740) but it was not accepted yet and I am not sure whether it will be.

I suspect, as a workaround, you could run the container privileged and with host network and set the required sysctls during the container runtime, but then again, you would be setting them for the whole system so there is very little point in doing that from the container. More on why doing that is a bad idea in https://github.com/moby/moby/issues/36640.

**Comment by pheitman** [comment]
Thank you for researching this. Since the documentation states that net.* was namespaced, I assumed that meant that all sysctls under net.* were supported, but obviously that isn't true - only a subset of the net.* sysctrls are currently namespaced. 

Just to make sure, my understanding is that for non-namespaced sysctls the setting on the host applies to the pods. They are in effect even though I can't see them within the netns inside the pod. Is that correct?

**Comment by stlaz** [comment]
I had the same assumption about the net.* sysctls given all the docs. It would seem that their adoption in namespaces may differ.

> Just to make sure, my understanding is that for non-namespaced sysctls the setting on the host applies to the pods. They are in effect even though I can't see them within the netns inside the pod. Is that correct?

I believe so. Since the whole host is affected in that case, it should also apply for docker/any other container runtime and thus for the pods as well.

**Comment by pheitman** [comment]
Yes, after writing my previous reply I realized that the easiest way to
find what sysctls were namespaced would be to just exec into a container
and look. I had done that before but didn't realize at the time the
implications of what I was seeing.

**Comment by stlaz** [comment]
Closing since we figured out the root of the problem. Feel free to check the documentation PR mentioned above :slightly_smiling_face:
