### ISSUE TITLE
Jenkins example template has empty image field

### ISSUE THREAD

**Issue by cucushift** [openshift/origin#20531]
https://github.com/openshift/origin/blob/7bd70b0b7e82a9c5cd70f23d76fb773906106f1b/examples/jenkins/jenkins-ephemeral-template.json#L101

why `image` field is empty?

**Comment by enj** [comment]
@openshift/sig-developer-experience

**Comment by bparees** [comment]
This is a workaround to deal w/ the limitations of deploymentconfigs.  We do not actually want to deploy using a value in the image field because the image field will be replaced by something referenced in the deploymentconfig's image change trigger.

So we put an invalid image value in the DC, and just let it get replaced by the image change trigger:

https://github.com/openshift/origin/blob/7bd70b0b7e82a9c5cd70f23d76fb773906106f1b/examples/jenkins/jenkins-ephemeral-template.json#L155-L168

@openshift/sig-master as far as i know this is still necessary, because empty string is still not valid for the image field, right?

**Comment by cucushift** [comment]
@enj @bparees thanks.

**Comment by tnozicka** [comment]
@bparees DC's actually handle even empty image because we control the validation there, not just the space workaround. For upstream workload resources image can't be empty and you need to use the space.

On the general question - You can either specify image directly, or from the trigger/image stream; specifying both at the same time is undefined behaviour.

**Comment by bparees** [comment]
> On the general question - You can either specify image directly, or from the trigger/image stream; specifying both at the same time is undefined behaviour. (Although we try a bit more for DCs.)

ok. once upon a time it was not valid to define a DC w/ no "image" field.  Sounds like that has changed.

**Comment by tnozicka** [comment]
@bparees once upon a time :) https://github.com/openshift/origin/pull/9167

**Comment by bparees** [comment]
> @bparees once upon a time :) #9167

4 digit PR #s.  Stop making me feel old. :)

**Comment by gabemontero** [comment]
On Tue, Aug 7, 2018 at 10:25 AM, Ben Parees <notifications@github.com>
wrote:

> @bparees <https://github.com/bparees> once upon a time :) #9167
> <https://github.com/openshift/origin/pull/9167>
>
> 4 digit PR #s. Stop making me feel old. :)
>

+1 (as the author of said PR)
