### ISSUE TITLE
Max. CPU and RAM supported on a Single node server in Openshift 3.7

### ISSUE THREAD

**Issue by aaryabhatt** [openshift/origin#20568]
Hi Everyone, 

I have a question, what are the maximum CPU core and RAM supported on a node server on openshift 3.7 ? I have a client who have server with 224 CPU cores and 768 GB of RAM and openshift 3.7 installed on that server. It faced sometime node flapping issue due to Pleg timeout. Somebody say me openshift don't handle properly such a large server on node due to so many cpu core and memory . 

Is it the correct statement by him? 

So I am here to get to know what is max. number cpu cores and RAM supported on a single node server with openshift.

Any idea, or example of such hardware running perfectly on openshift / kubernetes will be great. 

##### Version
Openshift version 3.7

--
Regards

Amit Bondwal

**Comment by jwforres** [comment]
@openshift/sig-scalability

**Comment by jeremyeder** [comment]
Need to discuss this with QE and PM.

Real quick though, we certainly have customers running very similar systems to the 224c/768g size you mention.

Important note:  regardless of system dimensions, supported pod density remains at 250 pods per node.  I mention this because you said you saw issues with PLEG timeouts.

Make sure you're running the latest version of docker that is supported with your release of OpenShift, and also make sure you are running the latest OpenShift version that you possibly can (although to my knowledge, 3.7 has all the major structural fixes that were done on these areas).

**Comment by jeremyeder** [comment]
Resolutions for the known issues were code-level as opposed to tuning, which is why I'd recommend you update to the latest versions.

One thing that could be introducing them is slow/flaky docker storage (the directory where images/running containers are written to).  You might want to look into that.  Check dmesg too.  If you're a customer, I encourage you to please file a support ticket.

**Comment by aaryabhatt** [comment]
Support ticket is already there, they could not solve so I am here. Is there possibility if I shift docker storage from overlay2 to thinvolume. Or that bug is also affecting the thinvolume too.

Thanks you very much for your time.

**Comment by jeremyeder** [comment]
What is the support ticket number please?  No, I would expect overlay to be best.  But actually I meant the disks that either overlay/thinp are writing to, rather than the docker storage driver type.

**Comment by aaryabhatt** [comment]
Thanks Jeremyeder, The case number is 02152273. subject name "Nodes are constantly changing status from ready to not ready (vice-versa)". I have uploaded the latest logs today to team to analyse.
