### ISSUE TITLE
can't get scheduledImageImportMinimumIntervalSeconds working

### ISSUE THREAD

**Issue by Mikedu1988** [openshift/origin#20668]
recently we've set up a private docker registry, and I found openshift only trigger "ImageChange" every 20 minutes, after I set scheduledImageImportMinimumIntervalSeconds :30 in master file, and  restart the master service by running:
systemctl restart origin-master-api origin-master-controllers origin-node

The issue still exists.
##### Version
[provide output of the `openshift version` or `oc version` command]
oc version
oc v3.9.0+ba7faec-1
kubernetes v1.9.1+a0ce1bc657
features: Basic-Auth GSSAPI Kerberos SPNEGO

openshift v3.9.0+ba7faec-1
kubernetes v1.9.1+a0ce1bc657

##### Steps To Reproduce
1. push a image to myharbor.mydoaim.com/demo:latest
2. deploy the image to openshift
3. oc import-image demo:latest --scheduled=true
4. push a new image to myharbor.mydoaim.com/demo:latest
##### Current Result
a deployment is triggered 20 minutes later with "Image change"
##### Expected Result
a deployment is triggered in 30 seconds with "Image change"

**Comment by jwforres** [comment]
@openshift/sig-developer-experience

**Comment by bparees** [comment]
it's a minimum interval, not a maximum interval, but it's working for me on 3.11.

I suggest you double check that you've set your configuration correctly.  Feel free to paste your entire master-config.yaml if you'd like me to double check it.  Other than that, I suggest you upgrade and see if you're still having issues on 3.10 because we're not going to pursue this on 3.9 at this point.
