### ISSUE TITLE
The API certificate

### ISSUE THREAD

**Issue by cucushift** [openshift/origin#20680]
hi all, when i use cmd `oc get node --loglevel=10`, The log shows `I0817 10:46:11.221028   26529 round_trippers.go:386] curl -k -v -XGET  -H "Accept: application/json;as=Table;v=v1beta1;g=meta.k8s.io, application/json" -H "User-Agent: oc/v1.11.0+d4cacc0 (linux/amd64) kubernetes/d4cacc0" 'https://qe-xiuwang-master-etcd-1:8443/api/v1/nodes?limit=500'
` ,with **-k** paremeter,so i think the client would not check the API certificate.But when I delete `certificate-authority-data` field in .kube/config file, rerun cmd `oc get node `,it will shows `Unable to connect to the server: x509: certificate signed by unknown authority` so why? Thanks.

**Comment by enj** [comment]
The debug just shows you a curl statement that could be used to accomplish the same API request.  It uses `-k` because it does not provide you with the CA information from inside the kube config file (not sure it even can).  If it did not include `-k`, you would almost always have to add it manually which would make copy-paste annoying.  It also does not cover cert based auth since that information is at the TLS layer.
