### ISSUE TITLE
osadm policy add-role-to-user doesn't validate if user exist or not

### ISSUE THREAD

**Issue by roldancer** [openshift/origin#2068]
Hi All,
    The following command doesn't validate if the user "oseVivaRealMadrid" exist or not, in my environemt that user doesn't exist.

[oseuser@ose1 ~]$ osadm policy add-role-to-user admin oseVivaRealMadrid
[oseuser@ose1 ~]$ echo $?
0

Thanks.

**Comment by smarterclayton** [comment]
We allow you to assign non-existent users up front today so that you can preallocate before the user joins the system.  We should probably warn via stderr if the user doesn't exist yet.  We also haven't added the role cleanup task (that would periodically purge invalid mappings).  @deads2k

**Comment by liggitt** [comment]
warning gets tricky with info leakage... should a project admin be able to effectively probe the list of users by trying to grant permissions to their own project to arbitrary user names?

**Comment by smarterclayton** [comment]
If they have access to list users, maybe, otherwise squelch?  Client could do that check, or we could have a --verify flag that forces the client to check what the user is doing.  That's probably desirable anyway.

**Comment by deads2k** [comment]
This can't be done.  There isn't sufficient information.

We have to allow non-existent users, because client certificates present users, not identities.  That detail means that we can never have a coherent set of known users or groups.  That said, I'm not fully sold on client certs as users and this could be another argument to make them identities instead.
