### ISSUE TITLE
Modifying secret value from web console

### ISSUE THREAD

**Issue by hcandraw** [openshift/origin#20826]
Hi, is there any reason why a secret value can't be changed on the web console?  ConfigMap allows for modifications, but secrets don't.  I know a secret value can be changed using the CLI, but for convenience, I'd suggest for the ability to be added on the web console too.

Apologies if this question doesn't belong here, couldn't find a more appropriate channel.

OpenShift web console v3.9.40.

**Comment by jhadvig** [comment]
@hcandraw currently in our application web-console there is no way how to edit secrets, only through the YAML editor, which is not an idea user-experience. This should be solved in the new cluster admin console, where most of the code for creating/editing secrets is already in place.

**Comment by hcandraw** [comment]
@jhadvig thanks.  When is that coming along?  We would like for our non-technical users to be able to use the console to update secrets.

**Comment by jwforres** [comment]
@hcandraw it will be installed side-by-side with the current console with 3.11, it won't have all the features in it, so its a little more admin focused with 3.11.  Moving towards the release after 3.11 then we'll be looking at only shipping the new console. That console is in this repo https://github.com/openshift/console

Closing this issue since the features are already there in the master branch of that repo. If you have any issues with the new console please open issues in that repo as that is easier for the UI folks to triage.
