### ISSUE TITLE
oc cluster up for 3.11 broken

### ISSUE THREAD

**Issue by deads2k** [openshift/origin#20887]
The v3.11 tag for service-serving-cert-signer has the wrong binary inside.

```
[deads@main ~]$ docker pull openshift/origin-service-serving-cert-signer:v3.11
[deads@main ~]$ docker images
REPOSITORY                                               TAG                 IMAGE ID            CREATED             SIZE
docker.io/openshift/origin-service-serving-cert-signer   v3.11               e60e3942e621        8 hours ago         276 MB
[deads@main ~]$ docker run -ti openshift/origin-service-serving-cert-signer:v3.11 ls bin | grep service
dbus-update-activation-environment  service-ca
```
This breaks `oc cluster up` which expects 

```
[deads@main ~]$ docker run -ti openshift/origin-service-serving-cert-signer:v4.0 ls bin | grep service
dbus-update-activation-environment  service-serving-cert-signer
```

**Comment by deads2k** [comment]
Looks like https://github.com/openshift/service-serving-cert-signer/pull/24 worked.  It just took an hour.  I wonder why that is....

@smarterclayton cronjob on api.ci?

**Comment by smarterclayton** [comment]
It takes an hour for images to be mirrored to the hub, but the signer image in most CI runs is being pulled from the openshift origin-v3.11 namespace.  It's not obvious what the cause is.

This does highlight that we need to do a better job of having binaries print out their code version (as well as having the ci infra tag images with their git commit).
