### ISSUE TITLE
Deploy OKD cluster using rhel base images

### ISSUE THREAD

**Issue by ahmad-hamade** [openshift/origin#20934]
I'm not sure if this is the right place to answer this question but I have setup and deployed an OKD 3.9 cluster on a Subscribed and Licensed RHEL7.5 as below:

[OSEv3:children]
masters
nodes
etcd

[OSEv3:vars]
oreg_url=registry.access.redhat.com/openshift3/ose-${component}:v3.9
openshift_deployment_type=origin
openshift_release=3.9
openshift_pkg_version=-3.9.0
openshift_image_tag=v3.9.41

All is working just fine. Can I continue using this environment or am I breaching licence conditions?

**Comment by mpbarrett** [comment]
In terms of a license, Red Hat only sells support.  There is no support on OKD since it is upstream.  If you wanted support on OKD you would buy OpenShift Container Platform.  As for the RHEL7.5, you are allowed to run whatever you want on RHEL.  It doesn't mean Red Hat is going to support whatever it is you decide to run.  Your RHEL is still supported.  If you start pulling down RHEL containers from the Red Hat Container Catalog, those would not be supported (as in phone support) on OKD.  That's the main reason people decide to use CentOS images with OKD.
