### ISSUE TITLE
"oc set image-lookup" should be "oc get image-lookup"

### ISSUE THREAD

**Issue by galderz** [openshift/origin#21015]
```
  # Print all of the image streams and whether they resolve local names
  oc set image-lookup
```

Calling `set` to print out something does not make sense.

Shouldn't that be `oc get image-lookup` ?

**Comment by jwforres** [comment]
@openshift/sig-master @openshift/sig-developer-experience

**Comment by mfojtik** [comment]
The `image-lookup` is not an resource, just an option (field) to set on ImageStreamTag.

**Comment by galderz** [comment]
Still does not make sense to call `oc set...` to print or list some values 🙃

**Comment by bparees** [comment]
it doesn't, but "get" is used to retrieve resources, so we can't use get here.  in the grand scheme it's a minor thing.

**Comment by galderz** [comment]
Who cares if it's a minor or a major thing. It simply does not make sense... It's a usability/discovery problem. Whether you want to address it or not is what matters here. Seems like you don't.

**Comment by galderz** [comment]
Even something like `oc image-lookup` would make more sense than `oc set image-lookup`. It'd be akin to `git branch` or `git remote`.

**Comment by galderz** [comment]
Btw, not sure I understand this process of closing the issue without a discussion. Not good...

**Comment by deads2k** [comment]
> Btw, not sure I understand this process of closing the issue without a discussion. Not good...

The maintainer of both `oc` and `kubectl` commented in this thread personally, provided the command to do what you want, and knew that `get` both upstream and downstream will never do this.  I think the only thing potentially lacking is a little additional explanation.

`oc get` is a command that generically inspects the discovery doc of a kube-apiserver, uses that information to determine which resource types are present, and then without semantic knowledge of any type retrieves it from the server.  By contrast, `oc set image-lookup --list` requires semantic knowledge of the particular information it retrieves and client-side post-processing to interpret it.  It cannot be combined cleanly into `oc get` and forcing it in would destroy the spirit of the command.

Closing this issue is correct.

**Comment by galderz** [comment]
I understand why you might not want to have `oc get image-lookup...`. I still don't understand why `oc image-lookup` can't be a thing.
