### ISSUE TITLE
oc "--as" flag behaves in an undesired way

### ISSUE THREAD

**Issue by born4new** [openshift/origin#21158]
Passing `--as` flag to impersonate a user does not give me the results I should get.

I tried to impersonate myself in the following example, but similar results occurred when trying out with other users.

That user is bound to a `cluster-admin` role via a `group`.

##### Version
```
oc v3.10.0+dd10d17
kubernetes v1.10.0+b81c8f8
features: Basic-Auth

Server https://openshift.nine.ch:8443
openshift v3.9.41
kubernetes v1.9.1+a0ce1bc657
```

##### Steps To Reproduce

```shell
$ oc whoami
dadie@nine.ch

$ oc get pods
NAME                              READY     STATUS      RESTARTS   AGE
my-service-67-build             0/1       Completed   0          1d

$ oc get pods --as=dadie@nine.ch
Error from server (Forbidden): pods is forbidden: User "dadie@nine.ch" cannot list pods in the namespace "ninech": User "dadie@nine.ch" cannot list pods in project "ninech"
```

##### Current Result

I cannot access the pods when trying to impersonate myself.

##### Expected Result

I should be able to access the pods when trying to impersonate myself.

**Comment by enj** [comment]
@born4new the impersonation code is inherited from upstream, and has no concept of automatic group impersonation (earlier versions of OpenShift had this feature but we gave it up to bring ourselves closer to upstream) because Kube only has virtual users and groups (it cannot look them up via an API).  See the [docs](https://docs.okd.io/latest/architecture/additional_concepts/authentication.html#authentication-impersonation) on how to manually impersonate a group.
