### ISSUE TITLE
Search Gateway: "Unknown resource: gatewaies/networking.istio.io/v1alpha3"

### ISSUE THREAD

**Issue by hhovsepy** [openshift/origin#21202]
When searching for "Gateway" in Resources -> Other Resources, Error is shown:
"Unknown resource: gatewaies/networking.istio.io/v1alpha3"

##### Version
OpenShift Master:    v3.10.14 
Kubernetes Master:    v1.10.0+b81c8f8 
OpenShift Web Console:    v3.10.14 

##### Steps To Reproduce
1. Go to "Resources" -> "Other Resources"
2. Search for "Gateway"

##### Current Result
Error Notification is shown.
No Gateways listed. Search result is "No ."

##### Expected Result
Should list Gateways or empty list.

![screenshot from 2018-10-09 19-39-05](https://user-images.githubusercontent.com/604313/46688081-bd202e00-cbfc-11e8-8d83-546760ed026b.png)

**Comment by jwforres** [comment]
@openshift/sig-user-interface 

looks like the logic for the old console's api service that translates the singular to the plural needs fixing

should probably make sure new console doesnt have the same problem

**Comment by spadgett** [comment]
Closing the Github issue since this is also tracked in Bugzilla:

https://bugzilla.redhat.com/show_bug.cgi?id=1668200

I've confirmed this is fixed in the 4.0 console and 3.11 admin console:

<img width="1337" alt="screen shot 2019-01-22 at 9 59 49 am" src="https://user-images.githubusercontent.com/1167259/51543862-8f1dcd00-1e2c-11e9-91a8-957495c23ca7.png">

/close
