### ISSUE TITLE
Clarify Dockerfile behavior for newbies

### ISSUE THREAD

**Issue by mcandre** [openshift/origin#21368]
Coming from Kubernetes, there are some surprises in OpenShift that took me a while to understand. I actually wish I hadn't used Kubernetes or Docker beforehand, so I wouldn't have come into OpenShift with assumptions about how things work.

For example, the `FROM` line can be silently overwritten by a buildconfig, and do changing the `FROM` doesn't help to troubleshoot why a build is failing. I personally would prefer to use `FROM` as is and not muck with overwriting by buildconfigs, as this adds some unnecessary complexity. Though I think the current user experience could be improved, while maintaining the same OpenShift semantics, as long as

1. OpenShift allows `FROM` lines to be omitted in Dockerfile's.
2. OpenShift allows `from.name` to be omitted in buildconfig's. (Either `FROM` or `from.name` should be present, ideally not both.)
3. OpenShift emits a brief warning when a `FROM` line is specified but overwritten by `from.name`.

With these small changes, I think users would feel more productive and less confused about working with OpenShift.

Similarly, I was surprised to find that `USER 0` is not automatically assumed during image builds. This is exactly the time when most images need to install packages and make other privileged changes, so coming from plain vanilla Docker, it feels awkward to require users to remind OpenShift to elevate privileges here. Is there really a security benefit to dropping root privileges during image builds by default? I'm not sure I immediately see one. I think defaulting to `USER 0` would make more sense, without losing backward compatibility. Even a warning about the absence of `USER 0` in a Dockerfile would have been helpful for debugging my builds.

Finally, I was taken aback to discover that containers also lose root privileges. When a container fails, I often want to install debugging tools to diagnose the problem, so I typically do `-it sh`, enter `<yum|apt|apk> install <packages>`, and continue troubleshooting. With OpenShift, container root accounts appear to be locked out with some password, so I am unable to make privileged changes to the living image. I can appreciate the value of discouraging container modification, as this promotes immutable infrastructure. But it's still annoying when, in an emergency, I want the flexibility to modify the container. Does anyone have recommendations for this kind of situation? Perhaps a flag to `oc rsh` or another way to effectively elevate permissions on containers?

Overall, OpenShift seems like a more disciplined Kubernetes, for more reliable deployments, but some of these restrictions can be cumbersome to deal with.

**Comment by adambkaplan** [comment]
A few (but not all) of the hiccups you ran into are in the [OKD docs](https://docs.okd.io/latest/dev_guide/builds/build_strategies.html#docker-strategy-options), but for brevity some of the context you are looking for has been omitted.

> For example, the FROM line can be silently overwritten by a buildconfig, and do changing the FROM doesn't help to troubleshoot why a build is failing.

This makes it easier to use `ImageStreamTags` with builds. Otherwise you would need to know the service name for OpenShift's internal container registry.

> Similarly, I was surprised to find that USER 0 is not automatically assumed during image builds.

Nope - for the same reason that OpenShift doesn't allow containers to run as root. Builds on 3.11 and earlier use the Docker socket on the host, which increases the potential attack surface. Consider using [source to image builds](https://docs.okd.io/latest/dev_guide/builds/build_strategies.html#source-to-image-strategy-options), which provide plug points that let you install dependencies during the build process.

> With OpenShift, container root accounts appear to be locked out with some password, so I am unable to make privileged changes to the living image.

You can set up your cluster to allow any container to run as root in a namespace - [see here for a helpful guide](https://blog.openshift.com/getting-any-docker-image-unning-in-your-own-openshift-cluster/). **I do not recommend this for production!**

IMO relying on extra tools to debug is an anti-pattern with containers. Ideally you want your container to produce enough logging/telemetry to help debug on its own, or restarted with a CLI/env var set. Ex: most OpenShift components have a `LOGLEVEL` environment variable which produces debug-quality logs.

Hope this helps!
