### ISSUE TITLE
Switching projects prompts to log in immediately after logging in

### ISSUE THREAD

**Issue by liggitt** [openshift/origin#2142]
Inconsistent, but I did the following, and was prompted to log in a second time:

```
osc login
... log in ...
osc project (some project I have access to)
```

My theory is that the context for the project I was switching to referenced a second user stanza for the same user with a stale token

**Comment by fabianofranz** [comment]
@liggitt If there is a context named exactly like the project you are trying to switch to, then the command will just switch to that *context* instead of the project - just setting `current-context` to that name - and that context may have a stale token. 

@smarterclayton This is a corner case where switching to a project may become impossible unless you do `osc login -n project-I-want-to-use`. Maybe we should generate more complex context names, or even reevaluate `osc project` switching to a context logic?

**Comment by liggitt** [comment]
wow, that's annoying. I feel like we've failed if we end up with two user stanzas for the same user.

**Comment by fabianofranz** [comment]
Yeah, I think I agree. Problem is, there is not reference in the config file that points to *who* a user stanza is. The `name` property *may* be the username, but it's not guaranteed. @deads2k

**Comment by liggitt** [comment]
do we have the user info at the time we create the stanza? we should at least make sure that we always use the same stanza name for the same user, even though you can do whatever you want with the file by hand or with `osc config`

**Comment by fabianofranz** [comment]
Related:
https://bugzilla.redhat.com/show_bug.cgi?id=1220507
https://github.com/openshift/origin/issues/2132

**Comment by liggitt** [comment]
@deads2k, were you looking at user-stanza selection? Wasn't sure if this belonged to you or @fabianofranz

**Comment by fabianofranz** [comment]
@liggitt this can be closed.
