### ISSUE TITLE
Official oc build doesn't execute on NixOS

### ISSUE THREAD

**Issue by crawford** [openshift/origin#21635]
When I try to execute `oc`, I get the following error:

```
./oc: error while loading shared libraries: libcrypto.so.10: cannot open shared object file: No such file or directory
```

Looking at the dynamic loader info, I see the following:

```
$ ldd oc
        linux-vdso.so.1 (0x00007ffce6bda000)
        libpthread.so.0 => /nix/store/fg4yq8i8wd08xg3fy58l6q73cjy8hjr2-glibc-2.27/lib/libpthread.so.0 (0x00007f5fd14a8000)
        libcrypto.so.10 => not found
        libdl.so.2 => /nix/store/fg4yq8i8wd08xg3fy58l6q73cjy8hjr2-glibc-2.27/lib/libdl.so.2 (0x00007f5fd12a4000)
        libc.so.6 => /nix/store/fg4yq8i8wd08xg3fy58l6q73cjy8hjr2-glibc-2.27/lib/libc.so.6 (0x00007f5fd0ef0000)
        /lib64/ld-linux-x86-64.so.2 => /nix/store/fg4yq8i8wd08xg3fy58l6q73cjy8hjr2-glibc-2.27/lib64/ld-linux-x86-64.so.2 (0x00007f5fd16c7000)
```

##### Version

Downloaded from: https://mirror.openshift.com/pub/openshift-v3/clients/4.0.0-0.79.0/linux/oc.tar.gz

##### Steps To Reproduce
1. Install NixOS 18.09.1534.d45a0d7a4f5
2. Attempt to run `oc`

##### Current Result

```
./oc: error while loading shared libraries: libcrypto.so.10: cannot open shared object file: No such file or directory
```

##### Expected Result

It runs. I'm not sure if libcrypto can be statically linked in any meaningful way. Feel free to tell me to go away.

**Comment by vdemeester** [comment]
@crawford the `oc` binary released can't work on NixOS, — due to how NixOS works :sweat_smile:  — it needs to be *binary patched* (`patchelf`) or compiled on it (like the [`nixpkgs` derivation](https://github.com/NixOS/nixpkgs/blob/1499b7c4e5d6ee818d42b3a285eccc30766c49db/pkgs/applications/networking/cluster/openshift/default.nix)).

@crawford I am looking into updating to 4.xx on my [personnal packages](https://github.com/vdemeester/nur-packages) soon :wink:

**Comment by sjug** [comment]
None of the v4 oc client binaries work on Arch Linux as well. You need to build from source.

**Comment by wking** [comment]
Dup of #21061?

**Comment by crawford** [comment]
@wking looks like it. Let's move over there.
