### ISSUE TITLE
centos7 oc cluster up error: unexpected error inspecting image openshift/origin-control-plane:v3.10

### ISSUE THREAD

**Issue by SamYuann** [openshift/origin#21650]
I use this Help doc: https://github.com/openshift/origin/blob/v4.0.0-alpha.0/docs/cluster_up_down.md

My physical machine install centos7 and docker1.13.1,and I use openshift-origin-client-tools-v3.10.0-dd10d17-linux-64bit to excute oc cluster up ,but it occurres error:

$ oc cluster up
Getting a Docker client ...
Checking if image openshift/origin-control-plane:v3.10 is available ...
error: unexpected error inspecting image openshift/origin-control-plane:v3.10

$ sudo docker version
Client:
 Version:         1.13.1
 API version:     1.26
 Package version: docker-1.13.1-88.git07f3374.el7.centos.x86_64
 Go version:      go1.9.4
 Git commit:      07f3374/1.13.1
 Built:           Fri Dec  7 16:13:51 2018
 OS/Arch:         linux/amd64

Server:
 Version:         1.13.1
 API version:     1.26 (minimum version 1.12)
 Package version: docker-1.13.1-88.git07f3374.el7.centos.x86_64
 Go version:      go1.9.4
 Git commit:      07f3374/1.13.1
 Built:           Fri Dec  7 16:13:51 2018
 OS/Arch:         linux/amd64
 Experimental:    false

**Comment by SamYuann** [comment]
I use root user install succeed.

**Comment by miuj** [comment]
Ubuntu Bionic too!

**Comment by longkb** [comment]
> Ubuntu Bionic too!

Same to me. I use `sudo` and it worked :)

**Comment by pallabi68** [comment]
I used sudo and it worked. Thanks.

**Comment by laith-leo** [comment]
It works with _sudo_ just because your `$USER `is not within the docker group (so you still need to add _sudo_ before `docker` command). Note that after adding `$USER` into docker group, you'd need to restart the whole system (not just docker) so it works.

**Comment by turek737** [comment]
Hello Everyone,

After trying to fix all possible issues like timeouts, EOF, errors, panic and other random problems (I had all of them around 300 fails during oc cluster up) I revert my vm to state before installing of below things and I've done it in correct way I guess because now it works like it should from the beginning (+ I can do oc cluster up/down without stress)  :) 

sudo apt update && sudo apt upgrade   (the most important step !!!)

sudo apt install curl
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -

sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"

sudo apt update && sudo apt -y install docker-ce

sudo usermod -aG docker XXXX

groups XXXX

wget https://github.com/openshift/origin/releases/download/v3.11.0/openshift-origin-client-tools-v3.11.0-0cbc58b-linux-64bit.tar.gz

cat << EOF | sudo tee /etc/docker/daemon.json
{
    "insecure-registries" : [ "172.30.0.0/16" ]
}
EOF

sudo systemctl daemon-reload
sudo systemctl restart docker

sudo systemctl is-enabled docker
sudo systemctl is-active docker

Regards,
Artur
