### ISSUE TITLE
Unresolved images issue on fresh installation of 3.11 openshift

### ISSUE THREAD

**Issue by shyam-biradar** [openshift/origin#21707]
@Poltorackiy : I am also facing the same issue with openshift 3.11 fresh install. I see default image streams are configured on my cloud. But still I am getting same 'unresolved image' error for all images. I tried for httpd, mysql, postgresql. Please let me know the exact issue and resolution.

_Originally posted by @shyam-biradar in https://github.com/_render_node/MDEyOklzc3VlQ29tbWVudDQ0OTkyOTY3Ng==/timeline/issue_comment#issuecomment-449929676_

**Comment by shyam-biradar** [comment]
I see 'service unavailable' error on image stream sync. But docker pull operation on same image is perfectly working fine. Tried manually.

Name:                   httpd
Namespace:              openshift
Created:                3 days ago
Labels:                 <none>
Annotations:            openshift.io/display-name=Apache HTTP Server (httpd)
                        openshift.io/image.dockerRepositoryCheck=2018-12-23T08:37:35Z
Docker Pull Spec:       docker-registry.default.svc:5000/openshift/httpd
Image Lookup:           local=false
Unique Images:          0
Tags:                   2

2.4 (latest)
  tagged from registry.redhat.io/rhscl/httpd-24-rhel7
    prefer registry pullthrough when referencing this tag

  Build and serve static content via Apache HTTP Server (httpd) 2.4 on RHEL 7. For more information about using this builder image, including OpenShift considerations, see https://github.com/sclorg/httpd-container/blob/master/2.4/README.md.
  Tags: builder, httpd
  Supports: httpd
  Example Repo: https://github.com/openshift/httpd-ex.git

  ! error: Import failed (InternalError): Internal error occurred: Get https://registry.redhat.io/v2/rhscl/httpd-24-rhel7/manifests/latest: received unexpected HTTP status: 503 Service Unavailable
      3 days ago

**Comment by mcdmike74** [comment]
Did you find the root cause for this issue?

I am seeing this same issue with OpenShift Enterprise 3.11.59. Some tags within the default image streams sync correctly while others fail. Most errors are 503 Service Unavailable but I believe I've also seen some 500 Internal Server Error messages. Running oc import-image _imagestream_ fixes most of the imagestream tags which fail initially. However, I have one imagestream tag which fails every time oc import-image is run.

oc import-image rhpam70-businesscentral-indexing-openshift:1.0
error: tag 1.0 failed: Internal error occurred: unknown: Not Found
imagestream.image.openshift.io/rhpam70-businesscentral-indexing-openshift imported with errors

Name:			rhpam70-businesscentral-indexing-openshift
Namespace:		openshift
Created:		16 hours ago
Labels:			<none>
Annotations:		openshift.io/display-name=Red Hat Process Automation Manager Business Central Indexing 7.0
			openshift.io/image.dockerRepositoryCheck=2019-01-23T00:38:38Z
			openshift.io/provider-display-name=Red Hat, Inc.
Docker Pull Spec:	docker-registry.default.svc:5000/openshift/rhpam70-businesscentral-indexing-openshift
Image Lookup:		local=false
Unique Images:		0
Tags:			1

1.0
  tagged from registry.redhat.io/rhpam-7/rhpam70-businesscentral-indexing-openshift:1.0

  Red Hat Process Automation Manager 7.0 - Business Central Indexing image.
  Tags: rhpam, xpaas
  Supports: rhpam:7.0, xpaas:1.4

  ! error: Import failed (InternalError): Internal error occurred: Get https://registry.redhat.io/v2/rhpam-7/rhpam70-businesscentral-indexing-openshift/manifests/1.0: received unexpected HTTP status: 503 Service Unavailable
