### ISSUE TITLE
router fails to start

### ISSUE THREAD

**Issue by patjlm** [openshift/origin#2184]
Hello,
Trying to run a router from a clustered vagrant environment

openshift ex router --create --replicas=1 --credentials="${OPENSHIFTCONFIG}"

The router seems to start correctly but with 0 replica:
```
$ osc get rc
CONTROLLER   CONTAINER(S)   IMAGE(S)                               SELECTOR                                                    REPLICAS
router-1     router         openshift/origin-haproxy-router:v0.5   deployment=router-1,deploymentconfig=router,router=router   0
```

and then after few seconds, the pod goes in failed state
```
$ osc get pods
POD                    IP        CONTAINER(S)   IMAGE(S)                         HOST                            LABELS    STATUS       CREATED     MESSAGE
deploy-router-15eqdi                                                             openshift-minion-1/10.245.2.3   <none>    Failed       3 minutes
                                 deployment     openshift/origin-deployer:v0.5                                             Terminated   3 minutes   exit code 255
```

```
$ osc log deploy-router-15eqdi
2015-05-12T09:27:40.991019898Z F0512 09:27:40.983698       1 deployer.go:64] Get https://10.245.2.2:8443/api/v1beta3/namespaces/default/replicationcontrollers/router-1: dial tcp 10.245.2.2:8443: i/o timeout
```

**Comment by pweil-** [comment]
@patjlm the log output looks like the deployment pod timed out accessing your master so the router pod was never created.   On a successful deployment you'd see a pod running with openshift/origin-ha-proxy-router image.  This may be a networking issue.  Since the ex router command works the client on the machine you ran the ex router command could access master.  A couple things to check:

1.  Are you able to hit the master from the nodes?
1.  Assuming this is a multi-node vagrant env (from the ip address in the log) are there any failures in the openshift-node-sdn, openshift-master-sdn, openshift-node, or openshift-master services?
1.  Can you create a simple pod, nsenter it, and ping the master?
1.  What IPs are your pods getting (that may indicate that the sdn is not running correctly)?

**Comment by patjlm** [comment]
While gathering this info, the router started working....
The only things i did which may have an impact are:
* osc delete all --all
* restart openshift-node-sdn on minion-1 after having updated /etc/hostname. It was containing openshiftdev.local. But restarting the cluster this morning, the router started correctly with the same (bad) hostname value.

**Comment by patjlm** [comment]
No idea why it was not working. I recreated the vagrant cluster from scratch for the nth time and it's now working flawlessly (at least the router creation). Closing this as un-reproducable then
