### ISSUE TITLE
Build Inputs; Using secrets during build, only last secret gets created

### ISSUE THREAD

**Issue by haknick** [openshift/origin#22032]
When using multiple secrets that have 'destinationDir' in BuildConfig, only the very last secret corresponding file gets created. The other secrets get ignored

##### Version
3.11 (I've also tested in version 3.10 and the issue persists)

##### Steps To Reproduce
The simplest way I've narrowed it down to reproduce is:

1. Create new app and save yaml in a temp file :

`oc new-app --name='myapp' -l 'micro-service=myapp' \
   -e DEV_MODE='true'  \
   nodejs:8~git@bitbucket.org:mygroup/myapp.git \
   --context-dir=src --source-secret='bitbucket-sshauth' \
   -o yaml  > /tmp/myapp.yaml`

2. Create the secrets that will be needed as well:

`oc secrets new bitbucket-shared-sshkey id_rsa=~/.ssh/bitbucket-sshauth

oc create secret generic bitbucket-shared-sshkey \
       --from-file=id_rsa=bitbucket-shared-sshkey \
       --type=Opaque

ssh-keyscan -H bitbucket.org >> bitbucket-shared-knownhosts
oc create secret generic bitbucket-shared-knownhosts \
        --from-file=known_hosts=bitbucket-shared-knownhosts \
        --type=Opaque`

3. Go in /tmp/myapp.yaml and add the 2 secrets:

> source:
>     git:
>       ref: master
>       uri: 'git@bitbucket.org:mygroup/myapp'
>     secrets:
>       - destinationDir: /opt/app-root/src/.ssh
>         secret:
>           name: bitbucket-shared-sshkey
>       - destinationDir: /opt/app-root/src/.ssh
>         secret:
>           name: bitbucket-shared-knownhosts

4. Build:

`oc create -f /tmp/dpc.yaml
oc start-build bc/myapp
`

##### Current Result
Only the 'known_hosts' file gets created and is available in /opt/app-root/.ssh
If I swap the order then the 'id_rsa' file will get created only

##### Expected Result
Both files should get created and available in /opt/app-root/.ssh folder

**Comment by adambkaplan** [comment]
@openshift/sig-developer-experience

**Comment by bparees** [comment]
I don't remember how we stitch all this together but mostly like we're losing the content when we mount the secrets into the build pod.  We probably mount both secrets to the same place.  After that, the logic that copies the secrets into the build context obviously only finds one.

The logic that generates the secret mounts (and configmap mounts because i'm sure it has the same issue) should include a sequence number in the mount path.  (and the copy logic needs to respect that sequence number).

@adambkaplan Since this is likely a legitimate bug it should probably be turned into a BZ or jira ticket (and then close this issue) so we don't lose track of it.

**Comment by adambkaplan** [comment]
@haknick as a work-around you can add the `know_hosts` content to the same secret containing the ssh key.

Moving this issue to Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1678901

**Comment by haknick** [comment]
Thanks everyone

@adambkaplan how would you do that? Represent 2 files in the same secret somehow ?

**Comment by adambkaplan** [comment]
@haknick you can pass in as many `--from-file` arguments as you need to `oc create secret`
