### ISSUE TITLE
Using Openshift with AWS ECR

### ISSUE THREAD

**Issue by chin92** [openshift/origin#22422]
I am planning to use AWS ECR (elastic container registry) instead of the built-in image registry to pull images. Tried multiple times but failed. Is it currently supported in openshift? What are the alternative options?

**Comment by adambkaplan** [comment]
You can pull from any authenticated registry as long as you create a pull secret that is linked to the default service account in your namespace [1]. ECR is not great for this, though, since its auth tokens expire every 12 hours and OpenShift does not have the ability to refresh these tokens.

[1] https://docs.okd.io/latest/day_two_guide/docker_tasks.html#authenticated-registries

**Comment by mostafasookar** [comment]
> You can pull from any authenticated registry as long as you create a pull secret that is linked to the default service account in your namespace [1]. ECR is not great for this, though, since its auth tokens expire every 12 hours and OpenShift does not have the ability to refresh these tokens.
> 
> [1] https://docs.okd.io/latest/day_two_guide/docker_tasks.html#authenticated-registries

Greetings, 
I need a small advice from you 
I have one customer he have OKD subscription, and he need to have his own image registry? so what do you advice? shall we go with ECR or something else?
