### ISSUE TITLE
Every page has vertical scrollbar even if content doesn't fill page

### ISSUE THREAD

**Issue by spadgett** [openshift/origin#2275]
Seemingly every page in our web console has a vertical scrollbar even if it's not needed.

/cc @sg00dwin @liggitt

**Comment by sg00dwin** [comment]
Fix verified. Pages with short content no longer have vertical scrollbar.

![screen shot 2015-06-09 at 1 56 19 pm](https://cloud.githubusercontent.com/assets/1874151/8065491/c2c602fc-0eaf-11e5-8e34-fd810f74d14a.png)
![screen shot 2015-06-09 at 1 52 30 pm](https://cloud.githubusercontent.com/assets/1874151/8065490/c2c5a6c2-0eaf-11e5-8c3b-5f15c17fafb8.png)

**Comment by spadgett** [comment]
Still seeing this on most pages.

![ie10_-_win7__running_](https://cloud.githubusercontent.com/assets/1167259/8160629/3e8b96ac-133f-11e5-9eda-045a479d5db4.png)

![ie10_-_win7__running_](https://cloud.githubusercontent.com/assets/1167259/8160632/428216dc-133f-11e5-814f-c8d4bb474ea7.png)

**Comment by liggitt** [comment]
I think pages shorter than 600px will still have it

**Comment by spadgett** [comment]
Seems to happen at larger window heights, too. Also notice the sidebar doesn't extend to the bottom of the page.

![ie10_-_win7__running_](https://cloud.githubusercontent.com/assets/1167259/8160769/59bf4e0e-1340-11e5-9c02-09f15e6bcbac.png)

**Comment by sg00dwin** [comment]
Yes we set a min-height of 600px so that the sidebars extend at least past the side nav on pages with little content.  IE needs .wrap {height: 100%} to extend the sidebars the height of the viewport on short pages, but this will cause a bug in Chrome. 

So the ideal solution would be to target IE with .ie .wrap {height:100%},  but that would require the use of modernizr or something similar to set the .ie class on < html >, which we don't have installed.

**Comment by jwforres** [comment]
@sg00dwin didnt you look into this recently, is it still an issue?  @spadgett ?
