### ISSUE TITLE
osadm manage-node --list-pods should error

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#2384]
It currently returns nothing and exit code 0

**Comment by smarterclayton** [comment]
Also, all of the commands should be erroring if you give it no input.

**Comment by smarterclayton** [comment]
Also, hack/test-cmd.sh can't rely on scheduling working, so these tests belong in integration test cases or need to be redesigned a bit.

**Comment by smarterclayton** [comment]
If you need to test evacuation you can do it from end-to-end

**Comment by pravisankar** [comment]
@smarterclayton 
manage-node takes list of nodes or node selector as input
'osadm manage-node --list-pods' will not error because when no nodes are given, it uses default node selector="". So it will try to list all pods on all nodes.

You said hack/test-cmd.sh can't rely on scheduling working, what's the reason? 
In the current test case, it marks the node as unschedulable but doesn't revert back to schedulable once the testing is done. Is that causing an issue?

**Comment by smarterclayton** [comment]
----- Original Message -----
> @smarterclayton
> manage-node takes list of nodes or node selector as input
> 'osadm manage-node --list-pods' will not error because when no nodes are
> given, it uses default node selector="". So it will try to list all pods on
> all nodes.

We shouldn't do that - user must provide input.  That's why we have --all on 'get'.  Users have to give us some input

> 
> You said hack/test-cmd.sh can't rely on scheduling working, what's the
> reason?

In travis, we don't run as root and you don't have access to cAdvisor info.  Also, it breaks in macs.

> In the current test case, it marks the node as unschedulable but doesn't
> revert back to schedulable once the testing is done. Is that causing an
> issue?

No, it's that scheduling in hack/test-cmd isn't guaranteed because there may be 0 resources on a node.
