### ISSUE TITLE
Update "error" is ambiguous

### ISSUE THREAD

**Issue by wshearn** [openshift/origin#2420]
We got in error in the logs saying:

    imageStream "jboss-mongodb-24" cannot be updated: the resource was updated to 668732

This is unclear as to if there was an error or not.

**Comment by jhadvig** [comment]
This is an upstream issue. Will track it.

**Comment by bparees** [comment]
@jhadvig even if it's an upstream message we should be able to do a better job wrappering more info around it when we catch the error.

**Comment by smarterclayton** [comment]
Suggest `X cannot be updated: another client made an update to this object as version N`

**Comment by jhadvig** [comment]
@smarterclayton thanks for suggestion will fix it later today.

**Comment by jhadvig** [comment]
Upstream PR:https://github.com/GoogleCloudPlatform/kubernetes/pull/9569

**Comment by jhadvig** [comment]
@smarterclayton so the merged commit was reverted, although I'm not fully sure why since the present message contains the same information value then the one we suggested, but the new one was more clear.
Like the suggestions from their side had also point. Personally I would go with combination:
`the resource version has been incremented to %v since you read it; re-read it and try your change again `
Or shall we stick to the suggestions they provided ?

**Comment by jhadvig** [comment]
Fix for this issue has been merged into k8s upstream - https://github.com/GoogleCloudPlatform/kubernetes/pull/9799

**Comment by bparees** [comment]
error message has been made more clear.
