### ISSUE TITLE
oc cluster fails with multiple errors

### ISSUE THREAD

**Issue by rajputvishwas** [openshift/origin#24376]
[provide a description of the issue]
I want to setup OKD (3.11) on ubuntu platform using oc client. Each time oc cluster up command fails with different set of errors.

##### Version
[provide output of the `openshift version` or `oc version` command]
oc version
oc v3.11.0+0cbc58b
kubernetes v1.11.0+d4cacc0
features: Basic-Auth GSSAPI Kerberos SPNEGO

##### Steps To Reproduce
root@CapstoneNode-Test-new2:~/okd# hostname -i
10.65.117.18
root@CapstoneNode-Test-new2:~/okd# oc cluster up --public-hostname=10.65.117.18

Getting a Docker client ...
Checking if image openshift/origin-control-plane:v3.11 is available ...
Pulling image openshift/origin-control-plane:v3.11
E0108 11:08:43.268544     968 helper.go:179] Reading docker config from /root/.docker/config.json failed: open /root/.docker/config.json: no such file or directory, will attempt to pull image docker.io/openshift/origin-control-plane:v3.11 anonymously
Pulled 2/5 layers, 45% complete
Pulled 3/5 layers, 60% complete
Pulled 4/5 layers, 83% complete
Pulled 5/5 layers, 100% complete
Extracting
Image pull complete
Pulling image openshift/origin-cli:v3.11
E0108 11:08:53.231483     968 helper.go:179] Reading docker config from /root/.docker/config.json failed: open /root/.docker/config.json: no such file or directory, will attempt to pull image docker.io/openshift/origin-cli:v3.11 anonymously
Image pull complete
Pulling image openshift/origin-node:v3.11
E0108 11:08:56.276361     968 helper.go:179] Reading docker config from /root/.docker/config.json failed: open /root/.docker/config.json: no such file or directory, will attempt to pull image docker.io/openshift/origin-node:v3.11 anonymously
Pulled 6/6 layers, 100% complete
Extracting
Image pull complete
Creating shared mount directory on the remote host ...
Determining server IP ...
Using public hostname IP 10.65.117.18 as the host IP
Checking if OpenShift is already running ...
Checking for supported Docker version (=>1.22) ...
Checking if insecured registry is configured properly in Docker ...
Checking if required ports are available ...
Checking if OpenShift client is configured properly ...
Checking if image openshift/origin-control-plane:v3.11 is available ...
Starting OpenShift using openshift/origin-control-plane:v3.11 ...
I0108 11:09:03.347978     968 config.go:40] Running "create-master-config"
I0108 11:09:04.787022     968 config.go:46] Running "create-node-config"
I0108 11:09:06.032275     968 flags.go:30] Running "create-kubelet-flags"
I0108 11:09:06.867659     968 run_kubelet.go:49] Running "start-kubelet"
I0108 11:09:07.052453     968 run_self_hosted.go:181] Waiting for the kube-apiserver to be ready ...
I0108 11:09:37.061507     968 interface.go:26] Installing "kube-proxy" ...
I0108 11:09:37.061530     968 interface.go:26] Installing "kube-dns" ...
I0108 11:09:37.061539     968 interface.go:26] Installing "openshift-service-cert-signer-operator" ...
I0108 11:09:37.061544     968 interface.go:26] Installing "openshift-apiserver" ...
I0108 11:09:37.061557     968 apply_template.go:81] Installing "kube-proxy"
I0108 11:09:37.061567     968 apply_template.go:81] Installing "openshift-apiserver"
I0108 11:09:37.061570     968 apply_template.go:81] Installing "kube-dns"
I0108 11:09:37.061604     968 apply_template.go:81] Installing "openshift-service-cert-signer-operator"

##### Current Result

E0108 11:10:34.932472     968 interface.go:34] Failed to install "openshift-apiserver": failed to install "openshift-apiserver": cannot create container using image openshift/origin-cli:v3.11; caused by: cannot create container using image openshift/origin-cli:v3.11
E0108 11:10:34.941047     968 interface.go:34] Failed to install "openshift-service-cert-signer-operator": failed to install "openshift-service-cert-signer-operator": cannot create container using image openshift/origin-cli:v3.11; caused by: cannot create container using image openshift/origin-cli:v3.11
E0108 11:10:34.966134     968 interface.go:34] Failed to install "kube-proxy": failed to install "kube-proxy": cannot create container using image openshift/origin-cli:v3.11; caused by: cannot create container using image openshift/origin-cli:v3.11
E0108 11:10:34.967714     968 interface.go:34] Failed to install "kube-dns": failed to install "kube-dns": cannot create container using image openshift/origin-cli:v3.11; caused by: cannot create container using image openshift/origin-cli:v3.11
I0108 11:10:34.967741     968 interface.go:41] Finished installing "kube-proxy" "kube-dns" "openshift-service-cert-signer-operator" "openshift-apiserver"
Error: [failed to install "openshift-apiserver": cannot create container using image openshift/origin-cli:v3.11; caused by: cannot create container using image openshift/origin-cli:v3.11, failed to install "openshift-service-cert-signer-operator": cannot create container using image openshift/origin-cli:v3.11; caused by: cannot create container using image openshift/origin-cli:v3.11, failed to install "kube-proxy": cannot create container using image openshift/origin-cli:v3.11; caused by: cannot create container using image openshift/origin-cli:v3.11, failed to install "kube-dns": cannot create container using image openshift/origin-cli:v3.11; caused by: cannot create container using image openshift/origin-cli:v3.11]

##### Expected Result
cluster should up and running
##### Additional Information

oc adm diagnostics
[Note] Determining if client configuration exists for client/cluster diagnostics
[Note] No client configuration specified; skipping client and cluster diagnostics.

ERROR: [CED3001 from controller openshift/origin/pkg/oc/cli/admin/diagnostics/util/util.go]
       Encountered fatal error while building diagnostics: Requested diagnostic(s) skipped; nothing to run. See --help and consider setting flags or providing config to enable running.
       
[Note] Summary of diagnostics execution (version v3.11.0+0cbc58b):
[Note] Errors seen: 1

[try to run `$ oc adm diagnostics` (or `oadm diagnostics`) command if possible]
[if you are reporting issue related to builds, provide build logs with `BUILD_LOGLEVEL=5`]
[consider attaching output of the `$ oc get all -o json -n <namespace>` command to the issue]
[visit https://docs.openshift.org/latest/welcome/index.html]

**Comment by kuzmanzs** [comment]
Hi,

did you find any solution for that? I have similar problem.

`Determining server IP ...
Checking if OpenShift is already running ...
Checking for supported Docker version (=>1.22) ...
Checking if insecured registry is configured properly in Docker ...
Checking if required ports are available ...
Checking if OpenShift client is configured properly ...
Checking if image openshift/origin-control-plane:v3.11 is available ...
Starting OpenShift using openshift/origin-control-plane:v3.11 ...
I0320 20:51:55.442878   20111 flags.go:30] Running "create-kubelet-flags"
I0320 20:51:56.435564   20111 run_kubelet.go:49] Running "start-kubelet"
I0320 20:51:56.729511   20111 run_self_hosted.go:181] Waiting for the kube-apiserver to be ready ...
I0320 20:53:14.751325   20111 interface.go:26] Installing "kube-proxy" ...
I0320 20:53:14.751346   20111 interface.go:26] Installing "kube-dns" ...
I0320 20:53:14.751355   20111 interface.go:26] Installing "openshift-service-cert-signer-operator" ...
I0320 20:53:14.751361   20111 interface.go:26] Installing "openshift-apiserver" ...
I0320 20:53:14.751375   20111 apply_template.go:81] Installing "openshift-apiserver"
I0320 20:53:14.751482   20111 apply_template.go:81] Installing "kube-dns"
I0320 20:53:14.751553   20111 apply_template.go:81] Installing "openshift-service-cert-signer-operator"
I0320 20:53:14.751680   20111 apply_template.go:81] Installing "kube-proxy"
E0320 20:54:14.333538   20111 interface.go:34] Failed to install "openshift-service-cert-signer-operator": failed to install "openshift-service-cert-signer-operator": cannot create container using image openshift/origin-cli:v3.11; caused by: cannot create container using image openshift/origin-cli:v3.11
E0320 20:54:14.340403   20111 interface.go:34] Failed to install "kube-proxy": failed to install "kube-proxy": cannot create container using image openshift/origin-cli:v3.11; caused by: cannot create container using image openshift/origin-cli:v3.11
E0320 20:54:14.392327   20111 interface.go:34] Failed to install "kube-dns": failed to install "kube-dns": cannot create container using image openshift/origin-cli:v3.11; caused by: cannot create container using image openshift/origin-cli:v3.11
E0320 20:54:14.392327   20111 interface.go:34] Failed to install "openshift-apiserver": failed to install "openshift-apiserver": cannot create container using image openshift/origin-cli:v3.11; caused by: cannot create container using image openshift/origin-cli:v3.11
I0320 20:54:14.392407   20111 interface.go:41] Finished installing "kube-proxy" "kube-dns" "openshift-service-cert-signer-operator" "openshift-apiserver"
Error: [failed to install "openshift-service-cert-signer-operator": cannot create container using image openshift/origin-cli:v3.11; caused by: cannot create container using image openshift/origin-cli:v3.11, failed to install "kube-proxy": cannot create container using image openshift/origin-cli:v3.11; caused by: cannot create container using image openshift/origin-cli:v3.11, failed to install "kube-dns": cannot create container using image openshift/origin-cli:v3.11; caused by: cannot create container using image openshift/origin-cli:v3.11, failed to install "openshift-apiserver": cannot create container using image openshift/origin-cli:v3.11; caused by: cannot create container using image openshift/origin-cli:v3.11]
zsolt@zsolt-NANUC8:~$ oc version
oc v3.11.0+0cbc58b
kubernetes v1.11.0+d4cacc0
features: Basic-Auth GSSAPI Kerberos SPNEGO
zsolt@zsolt-NANUC8:~$ oc adm diagnostics
[Note] Determining if client configuration exists for client/cluster diagnostics
[Note] No client configuration specified; skipping client and cluster diagnostics.`

**Comment by rajputvishwas** [comment]
If you are using aws instance, you need to restart the instance. This works for me but in few cases. I am still not understand why it not able to start the cluster
