### ISSUE TITLE
Connection refused error while connecting to exposed MongoDB service using curl or from  remote location

### ISSUE THREAD

**Issue by Lakshmi-devgit** [openshift/origin#24384]
My basic requirement is I have to access mongodb which is installed in one cluster from a mean application which is installed on another cluster/host/remote location

How could I do that ? these are the following steps I used to deploy mongodb and created external IP address

Openshift version : 4.2

Steps:
1) deployed mongodb with persistent storage in openshift server 
     $ oc new-app --template=mongodb-persistent 
2) next exposed the service using
     $ oc expose svc/mongodb
3) created external IP for mongodb 
      $ oc patch svc mongodb -p '{"spec": {"externalIPs":["192.174.120.09"]}}'
     then it is successfully patched with success message.
4) result of 
     $ oc get svc
        NAME      TYPE        CLUSTER-IP       EXTERNAL-IP      PORT(S)     AGE
       mongodb   ClusterIP   172.30.180.226   192.165.116.09   27017/TCP   27h
5) when trying with curl statement to connect to it 
     $ curl 192.165.116.08:27017
     curl: (7) Failed to connect to 192.165.116.09 port 27017: Connection refused

this is the error I am getting. Where I am doing wrong ? What are the steps I am missing.
Any suggestion will be appreciated , thank you in advance.

**Comment by maxatcn** [comment]
I have the same issue when connecting to non-HTTP protocol(Openshift 4.3).

https://docs.openshift.com/container-platform/4.2/networking/configuring_ingress_cluster_traffic/overview-traffic.html   Here is the official document and you may add a route and try again.

My issue is still there even adding a route. 
```
[root@test43-inf ~]# oc get svc
NAME                       TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)                         
mysql-jdbc                NodePort    172.30.92.28     <none>        3306:31848/TCP

[root@test43-inf ~]# oc get route
NAME                       HOST/PORT                           PATH   SERVICES                   PORT      
mysql-jdbc                mysql-jdbc-xxx.xxx.com                       mysql-jdbc                31848 
```

The connection to 31848 always returned 'connection refused'.  The connection to 80 returned like 'protocol error'. 

The issue can be fixed by editing haproxy.cfg and add 31848 in the list(by default 80 and 443 there.)

Is there any way to enable it by Route,  Ingress or Network Policy?(rather than editing haproxy.cfg)  Thanks.
