### ISSUE TITLE
Accessing web console via HTTP results in garbage being returned

### ISSUE THREAD

**Issue by rjleaf** [openshift/origin#2448]
**Issue:**
When accessing the web console via a browser, if I fail to connect via HTTPS, the server returns a file called "download."

**Version:**
Latest version available via Docker, using the instructions provided on the README for this repo.

**How to Reproduce:**
Open a browser and navigate to "http://localhost:8443/console".

**Comments:**
Perhaps it should redirect users to an HTTPS connection when an HTTP connection is attempted.

**Comment by liggitt** [comment]
It isn't possible to send a valid http response on a port serving TLS connections (https). Public sites can direct http to https because they are actually serving on different ports:
`http://foo.com` is using the implied port `80`
`https://foo.com` is using the implied port `443`

Because the port is specified in `http://localhost:8443/console`, the server only has a single handler that can respond to it, which responds with a TLS handshake. Your browser is not expecting that and interprets the response as binary content and prompts you to download a file.
