### ISSUE TITLE
Vagrant instructions not up-to-date

### ISSUE THREAD

**Issue by jacobkiers** [openshift/origin#2463]
While trying to start openshift using Vagrant, as shown in the [Contributing Guide](https://github.com/openshift/origin/blob/172863875cb5b7dfe160033455b61e163d6a8270/CONTRIBUTING.adoc#develop-on-virtual-machine-using-vagrant), I ran into two errors:

1. The go version installed is too old, therefore it requires a `yum update`.
2. The systemd file in `/usr/lib/systemd/system/openshift.service` needs the `ExecStartPost` lines removed.

I'm willing to create a PR for this, updating the Contributing Guide and the systemd file. I wasn't able to find the systemd file though, so that's why I created this issue first.

**Comment by kargakis** [comment]
The Docker version also is >1.6

**Comment by gravis** [comment]
Same here, I don't have any openshift.service file :(

**Comment by danmcp** [comment]
@jacobkiers @kargakis @gravis Are you using fedora and vitualbox?  The latest images are using docker 1.6 and the openshift.service is there:

dmcphers@mcpherson:~/gocode/src/github.com/openshift/origin (master)$ vagrant up
Bringing machine 'openshiftdev' up with 'virtualbox' provider...
==> openshiftdev: Importing base box 'fedora_inst'...
==> openshiftdev: Matching MAC address for NAT networking...
==> openshiftdev: Setting the name of the VM: origin_openshiftdev_1432844621076_93215
==> openshiftdev: Clearing any previously set network interfaces...
==> openshiftdev: Preparing network interfaces based on configuration...
    openshiftdev: Adapter 1: nat
==> openshiftdev: Forwarding ports...
    openshiftdev: 80 => 1080 (adapter 1)
    openshiftdev: 443 => 1443 (adapter 1)
    openshiftdev: 8080 => 8080 (adapter 1)
    openshiftdev: 8443 => 8443 (adapter 1)
    openshiftdev: 22 => 2222 (adapter 1)
==> openshiftdev: Running 'pre-boot' VM customizations...
==> openshiftdev: Booting VM...
==> openshiftdev: Waiting for machine to boot. This may take a few minutes...
    openshiftdev: SSH address: 127.0.0.1:2222
    openshiftdev: SSH username: vagrant
    openshiftdev: SSH auth method: private key
    openshiftdev: Warning: Connection timeout. Retrying...
    openshiftdev: 
    openshiftdev: Vagrant insecure key detected. Vagrant will automatically replace
    openshiftdev: this with a newly generated keypair for better security.
    openshiftdev: 
    openshiftdev: Inserting generated public key within guest...
    openshiftdev: Removing insecure key from the guest if its present...
    openshiftdev: Key inserted! Disconnecting and reconnecting using new SSH key...
==> openshiftdev: Machine booted and ready!
==> openshiftdev: Checking for guest additions in VM...
==> openshiftdev: Setting hostname...
==> openshiftdev: Mounting shared folders...
    openshiftdev: /data/src/github.com/openshift/origin => /home/dmcphers/gocode/src/github.com/openshift/origin
==> openshiftdev: Running provisioner: setup (shell)...
    openshiftdev: Running: /tmp/vagrant-shell20150528-26623-gugk2o.sh
==> openshiftdev: Host: localhost
dmcphers@mcpherson:~/gocode/src/github.com/openshift/origin (master)$ vagrant ssh
systLast login: Fri Jan 30 01:20:24 2015 from 10.0.2.2
[vagrant@openshiftdev ~]$ sudo systemctl start openshift
[vagrant@openshiftdev ~]$ sudo systemctl status openshift
● openshift.service - OpenShift
   Loaded: loaded (/usr/lib/systemd/system/openshift.service; disabled)
   Active: active (running) since Thu 2015-05-28 20:29:58 UTC; 5s ago
     Docs: https://github.com/openshift/origin
 Main PID: 2064 (openshift)
   CGroup: /system.slice/openshift.service
           └─2064 /data/src/github.com/openshift/origin/_output/local/go/bin/openshift start --public-master=https:...

May 28 20:29:58 openshiftdev.local systemd[1]: Started OpenShift.
May 28 20:29:58 openshiftdev.local openshift[2064]: I0528 20:29:58.321824    2064 start_allinone.go:223] Starti...-one
May 28 20:29:58 openshiftdev.local openshift[2064]: Generated new CA for openshift-signer@1432844998: cert in o....key
May 28 20:30:00 openshiftdev.local openshift[2064]: Generated new server certificate as openshift.local.config/....key
May 28 20:30:00 openshiftdev.local openshift[2064]: Keeping existing server certificate at openshift.local.conf....key
May 28 20:30:01 openshiftdev.local openshift[2064]: Generated new server certificate as openshift.local.config/....key
Hint: Some lines were ellipsized, use -l to show in full.
[vagrant@openshiftdev ~]$ docker --version
Docker version 1.6.0, build 350a636/1.6.0






Note: for anyone who had previously pulled down the image you might want to try:

`vagrant box remove fedora_inst`

And then vagrant up again.

**Comment by gravis** [comment]
for me, the group addition solved the pb:

```diff
diff --git a/Vagrantfile b/Vagrantfile
index 8660cd3..612622e 100644
--- a/Vagrantfile
+++ b/Vagrantfile
@@ -170,6 +170,9 @@ Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
       if vagrant_openshift_config['rebuild_yum_cache']
         config.vm.provision "shell", inline: "yum clean all && yum makecache"
       end
+      config.vm.provision "shell" do |s|
+        s.inline = "groupadd -f docker"
+      end
       if pre_vagrant_171
         config.vm.provision "shell", path: "hack/vm-provision.sh", id: "setup"
       else
```

**Comment by danmcp** [comment]
@gravis Are you using virtualbox?

**Comment by gravis** [comment]
Nope VMware :)

**Comment by danmcp** [comment]
@gravis Okay that makes sense.  VMWare is in the config but not really being maintained currently. Sorry for the confusion.

**Comment by gravis** [comment]
I'm pretty sure this has nothing to do with vagrant nor vmware :)

**Comment by danmcp** [comment]
@gravis Why would that be?  The images for virtual box are created by running through the os -> deps -> inst states of https://github.com/openshift/vagrant-openshift

And one of those steps is to run:

https://github.com/openshift/vagrant-openshift/blob/master/lib/vagrant-openshift/action/install_openshift_base_dependencies.rb#L62

And so when you launch the _inst images for virtualbox (and libvirt as of now) you get the image that doesn't need the step you added.  VMWare right now is pointing to a pure fedora and so it does need that step.

Note: technically all of them need to be switched to not do the group add at all and always use sudo.  The groupadd is still the old mechanism.

**Comment by gravis** [comment]
Ho, I didn't see this part, sorry :)

**Comment by kargakis** [comment]
@danmcp I still get 1.3.3 for go and 1.4 for docker when running vagrant on the latest master...

**Comment by danmcp** [comment]
@kargakis And you ran 

`vagrant box remove fedora_inst`

before vagrant up on a new instance?

Are you running with DEV_CLUSTER?  If so you would instead want to run:

`vagrant box remove fedora_deps`

**Comment by kargakis** [comment]
I can confirm that the versions are updated :+1:

**Comment by jacobkiers** [comment]
Yes, removing and reinstalling the fedory box also worked for me.
