### ISSUE TITLE
Banner doesn't fill browser width with wide events table

### ISSUE THREAD

**Issue by spadgett** [openshift/origin#2560]
I had to scroll horizontally to see the full events table. The banner filled the visible window width, but not the full width when there's a scrollbar.

![openshift_web_console_and_new_issue_ _openshift_origin](https://cloud.githubusercontent.com/assets/1167259/7861939/f4b07ba0-0520-11e5-8d3d-c10a4e731ce2.png)

/cc @liggitt @sg00dwin

**Comment by liggitt** [comment]
steve is already working on a fix for this

**Comment by sg00dwin** [comment]
Fix verified. Table width doesn't break layout now that .table-responsive sets overflow-scroll-x:auto;

![screen shot 2015-06-09 at 1 28 52 pm](https://cloud.githubusercontent.com/assets/1874151/8064987/6c107c6a-0eac-11e5-8433-c09454b30006.png)

Related note - since events list is not paginated the scrollbar can be further down than optimal

**Comment by spadgett** [comment]
I'm still seeing this on Firefox. I cleared my cache.

![openshift_web_console_and_banner_doesn_t_fill_browser_width_with_wide_events_table_ _issue__2560_ _openshift_origin](https://cloud.githubusercontent.com/assets/1167259/8161059/245688a2-1342-11e5-9924-d87db7711943.png)

Chrome and IE are fine.

**Comment by sg00dwin** [comment]
The fix that I've tested and works would be to "word-break:break-word" the long string in the last td, but since Firefox doesn't support break-word(1) we'd need to assign it break-all then break-word for webkit and microsoft. 

@liggitt acceptable?

.table-events {
  tr td:last-child {
    word-break: break-all; // Firefox
    word-break: break-word; // Webkit and Microsoft
  }
}

1. https://bugzilla.mozilla.org/show_bug.cgi?id=587438

**Comment by liggitt** [comment]
I'd rather have a general purpose utility selector we can put on content we expect to be ill-behaved:
```
.break-word {
  word-break: break-all; // Firefox
  word-break: break-word; // Webkit and Microsoft
}
```
and apply it directly to that table cell in the template
