### ISSUE TITLE
Enable strict dependency injection in web UI

### ISSUE THREAD

**Issue by liggitt** [openshift/origin#2575]
https://docs.angularjs.org/error/$injector/strictdi

Will help prevent minification errors

**Comment by jwforres** [comment]
We run https://github.com/mzgol/grunt-ng-annotate to switch everything over to the safe injection style before minification occurs.

We don't have a way to actually enable strict-di today because it must either be done on the ng-app element if there is one, or on the call to angular.bootstrap.  The call to angular.bootstrap is run by the hawtioPluginLoader and not by us and bootstraps all plugins that are on the page.
