### ISSUE TITLE
cluster operators are still not stable after

### ISSUE THREAD

**Issue by khurley-redhat** [openshift/origin#26400]
[provide a description of the issue]
When running crc start - just before the administrator and user credentials are printed,  I see two errors:

ERRO Cluster is not ready: cluster operators are still not stable after 11m29.507734238s 
INFO Adding crc-admin and crc-developer contexts to kubeconfig... 
ERRO Cannot update kubeconfig: Head "https://oauth-openshift.apps-crc.testing": EOF 

##### Version
[provide output of the `openshift version` or `oc version` command]
INFO Loading bundle: crc_hyperkit_4.8.2... 
INFO Creating CodeReady Containers VM for OpenShift 4.8.2...
INFO Generating new SSH Key pair...
INFO Generating new password for the kubeadmin user
INFO Starting CodeReady Containers VM for OpenShift 4.8.2...
INFO CodeReady Containers instance is running with IP 127.0.0.1

##### Steps To Reproduce
1. [step 1] run crc setup
2. [step 2] run crc start

##### Current Result
I see these two errors:

ERRO Cluster is not ready: cluster operators are still not stable after 11m29.507734238s 
INFO Adding crc-admin and crc-developer contexts to kubeconfig... 
ERRO Cannot update kubeconfig: Head "https://oauth-openshift.apps-crc.testing": EOF 

##### Expected Result

No errors and I'm able to run it and connect to it.
[crc.log](https://github.com/openshift/origin/files/6995448/crc.log)

##### Additional Information
[try to run `$ oc adm diagnostics` (or `oadm diagnostics`) command if possible]
[if you are reporting issue related to builds, provide build logs with `BUILD_LOGLEVEL=5`]
[consider attaching output of the `$ oc get all -o json -n <namespace>` command to the issue]
[visit https://docs.openshift.org/latest/welcome/index.html]

**Comment by shine-fire** [comment]
I meet the same error now
I can start success forenoon but met the error in the afternoon

**Comment by lobmarib** [comment]
I'm having the same problem. Any workaround?
(Running on mac, osx 10.14.3)

**Comment by pmarkiewka** [comment]
You can try to set the used cpu and memory higher. 

I had the same Problem. I used `crc start -c 8 -m 16000` to use 8 cores and 16gig memory.

**Comment by zgramana** [comment]
Ran into the same issue as well. Tried @pmarkiewka's suggestion but it do not resolve the issue for me. Is there a way to extend the wait time longer? Hyperkit does appear to be doing something during this time, but does not seem to leverage more than 1.5 cores during most of it.

**Comment by RidaAbrahams** [comment]
Same issue running CRC on MacOS 12.0.1

INFO Starting OpenShift cluster... [waiting for the cluster to stabilize] 
ERRO Cluster is not ready: cluster operators are still not stable after 10m2.18638s 
INFO Adding crc-admin and crc-developer contexts to kubeconfig... 
ERRO Cannot update kubeconfig: x509: certificate is valid for docker-for-desktop, kubernetes, kubernetes.default, kubernetes.default.svc, kubernetes.default.svc.cluster.local, kubernetes.docker.internal, localhost, vm.docker.internal, not api.crc.testing 

The cluster starts but I'm not able to use the cli. I get this error:
 % oc login -u developer https://api.crc.testing:6443
The server is using a certificate that does not match its hostname: x509: certificate is valid for docker-for-desktop, kubernetes, kubernetes.default, kubernetes.default.svc, kubernetes.default.svc.cluster.local, kubernetes.docker.internal, localhost, vm.docker.internal, not api.crc.testing
You can bypass the certificate check, but any data you send to the server could be intercepted by others.
Use insecure connections? (y/n): y

error: couldn't get https://api.crc.testing:6443/.well-known/oauth-authorization-server: unexpected response status 403

**Comment by Deel96** [comment]
/reopen
Hi,
I also get the first error:
`ERRO Cluster is not ready: cluster operators are still not stable after 10m0.495989372s`
I'm not sure where to open an issue because the comments in the issue templates I found didn't match.

I also tried the workarounds:
secrets file is from today and I also tried with 8 cores and 16 gb of ram.

If I should open a separate issue, please tell me where.

# Steps to reproduce:
1. crc setup
2. crc start --memory 16288 -c 8 --disk-size=64 --pull-secret-file ~/Downloads/pull-secret


I did the installation per quickstart guide: https://access.redhat.com/documentation/en-us/red_hat_openshift_local/2.5/html/getting_started_guide/installation_gsg
Quickstart in a nutshell:
<details>

```console
wget -P ~/Downloads https://developers.redhat.com/content-gateway/rest/mirror/pub/openshift-v4/clients/crc/latest/crc-linux-amd64.tar.xz &&
cd ~/Downloads &&
tar xvf crc-linux-amd64.tar.xz &&

#su -c 'yum install NetworkManager' &&
sudo yum install NetworkManager &&

mkdir -p ~/bin &&
cp ~/Downloads/crc-linux-*-amd64/crc ~/bin &&

export PATH=$PATH:$HOME/bin &&
echo 'export PATH=$PATH:$HOME/bin' >> ~/.bashrc

```

I did the following:
```console
crc setup
crc start --memory 16288 -c 8 --disk-size=64 --pull-secret-file ~/Downloads/pull-secret
```console

**Comment by bmaupin** [comment]
> You can try to set the used cpu and memory higher.
> 
> I had the same Problem. I used `crc start -c 8 -m 16000` to use 8 cores and 16gig memory.

Based on this comment and my own testing, I was able to get it working on my end just by increasing the CPUs:

```
crc start -c 8
```

My guess is that the mobile chipset on the laptop I'm using isn't fast enough to start all the necessary pieces in time, and so it times out after 10 minutes with the default of 4 CPUs:

```
$ crc start --help | grep -i cpu
  -c, --cpus int                  Number of CPU cores to allocate to the instance (default 4)
```

Just by bumping it to 8 CPUs, it starts in time. Increasing the memory didn't seem to be necessary.

**Comment by bmaupin** [comment]
> You can try to set the used cpu and memory higher.
> 
> I had the same Problem. I used `crc start -c 8 -m 16000` to use 8 cores and 16gig memory.

In my case, it always fails the first time I try to start it; it times out after 10 minutes. Then I run `crc stop` and `crc start` again and it works.

I suspect part of the problem is I maybe the CPU on my laptop isn't powerful enough to start it up the first time before it times out? 

But still, it's an 11th gen i7 with 8 virtual cores, so I might create a separate issue because this doesn't seem like intended behaviour. I wonder if there was a way to adjust the timeout if it would eventually start the first time.

It's hard to test because I'd have to reboot just to see if giving it 8 cores/16 GB the first time would work. And that's not really a viable option for me because that's a lot of RAM and I still need some to get work done :sweat_smile:

**Comment by bmaupin** [comment]
I figured I'd leave a comment here since it's currently the top result when searching for 

> crc cluster operators are still not stable

In my case, after playing with cores/memory, I realized I was forgetting to run `crc setup` before running `crc start` :man_facepalming: 

I'm not sure why it's necessary to run `crc setup` every time. It might be because my network configuration changes regularly, but it doesn't seem very intuitive.
