### ISSUE TITLE
Web files served with wrong MIME types

### ISSUE THREAD

**Issue by rhcarvalho** [openshift/origin#2652]
When I browse to a page like "https://localhost:8443/console/project/demo2/create", Chrome's console shows:

```
create:50 Resource interpreted as Font but transferred with MIME type application/font-sfnt: "https://localhost:8443/console/styles/fonts/PatternFlyIcons-webfont.ttf".
create:50 Resource interpreted as Script but transferred with MIME type text/plain: "https://localhost:8443/console/config.js".
Resource interpreted as Image but transferred with MIME type text/html: "https://localhost:8443/console/%7B%7Bicon%7D%7D".
```

@liggitt FYI

**Comment by liggitt** [comment]
application/font-sfnt is correct for TTF:
http://www.iana.org/assignments/media-types/application/font-sfnt

we should fix the config.js type

https://localhost:8443/console/%7B%7Bicon%7D%7D is returning html, so the mime-type is correct. I'm more interested in what is making Chrome request that URL, since it looks like an angular template that didn't get filled in correctly.

**Comment by spadgett** [comment]
@liggitt We should be using `ng-src` to specify the icon `src` in `_custom-icon.html`.

https://docs.angularjs.org/api/ng/directive/ngSrc

**Comment by liggitt** [comment]
when you fix that, can you sweep for any other places we're setting `src` incorrectly?

**Comment by spadgett** [comment]
Looks like this is the only place we use an expression in a `src` attribute.
