### ISSUE TITLE
ConfigChange build trigger

### ISSUE THREAD

**Issue by rhcarvalho** [openshift/origin#2741]
Could we have a ConfigChange trigger for BuildConfigs on par with DeploymentConfigs?

Use case: I want my BC to build from a different branch, use `osc edit bc my-bc-name`, then rebuild.

@bparees @mfojtik PTAL

**Comment by bparees** [comment]
sounds like a reasonable idea to me.

**Comment by mfojtik** [comment]
Yeah, I have 85% of this done, but it is getting more complicated by the fact that we have ImageChangeTrigger.

So what happen when I have ImageChangeTrigger AND the ConfigChange trigger enabled and I create the BC. Following the DeploymentConfig, you should start a new Build immediately. Problem is that the builder image/tags might not be imported (yet) and the first build will fail as the image is not available. Eventually it will keep retrying till the image is available... Now the ICT comes into play and since there is a new image available, it will kick a new build... So now you will have two builds going on. One triggered by ConfigChange and second by ImageChange trigger.

**Comment by bparees** [comment]
@mfojtik we really need to stop and discuss the build controller architecture in depth before we bolt more function in here.

@smarterclayton has already proposed level driven builds like deploymentconfig does (periodically scan the existing builds, compare with what the BC is supposed to look like, and run a build if needed) which would totally alter this logic.

**Comment by smarterclayton** [comment]
Maybe do some thinking this week and do a meeting next week?

**Comment by bparees** [comment]
@mfojtik is the 85% of this you had done sitting in a branch anywhere?  we're probably going to work on this this sprint......

**Comment by mfojtik** [comment]
@bparees I was very, very optimistic this to be 85% done :-( I tried to copy the Deployment ConfigChange trigger but it does not fit that well for BuildConfig.

**Comment by mfojtik** [comment]
@bparees also I must stash the changes but then somehow deleted them :/

**Comment by bparees** [comment]
@mfojtik np, i think the path @csrwng is taking probably diverges from what you did quite a bit anyway.

**Comment by bparees** [comment]
trello'd https://trello.com/c/yr6I8Zrz/687-configchangetrigger-for-builds
