### ISSUE TITLE
update CONTRIBUTING.adoc

### ISSUE THREAD

**Issue by HyunsooKim1112** [openshift/origin#2773]
Hi,
I had some problems when I setup my OpenShift development environment by using CONTRIBUTING.adoc guide.

1. $GOPATH is not clear. In "Installing Go." Web Page, there already exists "$HOME/go" when you use "Installing to a custom location" option.

2. There is no information about cloning, compiling and testing steps in "Develop locally on your host" chapter.

3. There is something confused in "Develop on virtual machine using Vagrant" chapter.
Is it right to execute 6 and 7 steps in the SSH?

Best Regards,
Hyunsoo Kim

**Comment by danmcp** [comment]
> $GOPATH is not clear. In "Installing Go." Web Page, there already exists "$HOME/go" when you use "Installing to a custom location" option.

GOPATH and GOROOT are distinct concepts.  In normal cases GOROOT doesn't need to be set.  But the $HOME/go from Installing Go and $HOME/go examples for the GOPATH are unrelated concepts.  On fedora for example GOROOT would be /usr/lib/golang/ from yum installing golang.  But it's ok if they are set to the same thing.

> There is no information about cloning, compiling and testing steps in "Develop locally on your host" chapter.

Fixed with: https://github.com/openshift/origin/pull/2816

> There is something confused in "Develop on virtual machine using Vagrant" chapter.
Is it right to execute 6 and 7 steps in the SSH?

Yes.
