### ISSUE TITLE
Remove button can wrap onto next line when editing labels at mobile sizes

### ISSUE THREAD

**Issue by spadgett** [openshift/origin#2881]
This can happen with labels and environment variable values.

![openshift_web_console](https://cloud.githubusercontent.com/assets/1167259/8014163/6e4c217c-0b9c-11e5-9a33-33c50377e854.png)

It's supposed to look like this.

![openshift_web_console](https://cloud.githubusercontent.com/assets/1167259/8014179/8e7f1f62-0b9c-11e5-8420-66de219f4b83.png)

**Comment by spadgett** [comment]
@benjaminapetersen

**Comment by benjaminapetersen** [comment]
Also noticed a few other items:
* when you click edit, the text box & buttons that appear break the layout
* if values are invalid, the error messages that appear are on the same row, which is fairly cramped in a smaller (mobile) screen size.

**Comment by benjaminapetersen** [comment]
Migrating a couple tasks form the PR I just closed:

- [ ] change the ```value="{{value}}"``` on the input to ```ng-value="{{value}}"```
- [ ] change ```placeholder="{{keyTitle}}"``` to ```ng-attr-placeholder="{{keyTitle}}"```
- [ ] use ```class="gutter-top"``` rather than inline ```style="margin-top: 20px"```
- [ ] double check and ensure inputs, read-only values && user defined values all line up
- [ ] when the tag-edit mode opens, keep it inline & ensure the buttons/inputs are sized appropriately (as was done in the closed PR)

**Comment by spadgett** [comment]
This happens for the edit build config form, too (#6528).
