### ISSUE TITLE
Include resolved pushspec in build.status

### ISSUE THREAD

**Issue by liggitt** [openshift/origin#2982]
When creating a build pod and resolving the build.output.to to a particular pushspec, save that in the build.status portion of the API object

**Comment by bparees** [comment]
See also: https://trello.com/c/xrPu7upe/590-clean-validation-in-builds-future-build

**Comment by rhcarvalho** [comment]
@liggitt @bparees any particular reason why we would store the resolved spec in the build.status?
I think conceptually the pushspec is part of the build.spec, and not a "status" field. I'm aiming to resolve image stream references when we create a build out of a BC, so that the pushspec will be in build.Output.To.Name.

In case the build is created without a BC, we'll still need to resolve the reference in the controller, I guess, but I don't know how this flow is implemented yet.

**Comment by liggitt** [comment]
We don't want to lose the symbolic destination of the build, which we would if the push spec was resolved to a particular registry ip in the spec

**Comment by rhcarvalho** [comment]
Does it also mean we might re-resolve a pending build? E.g., if the registry IP changes.

**Comment by bparees** [comment]
So the original issue here was that we were updating the build after creating it, to update the push spec.

if we fix that by setting the push spec before we create the build object, i would tend to agree that having it in spec and not status ought to be fine.

but i think what @liggitt is saying is the build object ought to contain the IST in the spec (assuming the original From ref was an IST), and the resolved pullspec in the status.

unfortunately that means changing a bunch of other code to change where it looks for the push spec, with compatibility implications.

**Comment by rhcarvalho** [comment]
Discussed the implementation direction on IRC with @bparees and here's what we decided to do as a first iteration:

1. Create a new field in [`build.status`](https://github.com/openshift/origin/blob/1b11e8625a1cfd6071ad300440c737823765f436/pkg/build/api/v1/types.go#L48-L74). Field name is TBD.

2. Change the [build controller](https://github.com/openshift/origin/blob/1b11e8625a1cfd6071ad300440c737823765f436/pkg/build/controller/controller.go#L118-L170) to resolve the pushspec and put it in the new status field, instead of in a copy of the build object.

3. Change the [S2I](https://github.com/openshift/origin/blob/1b11e8625a1cfd6071ad300440c737823765f436/pkg/build/builder/sti.go#L51) and [Docker](https://github.com/openshift/origin/blob/1b11e8625a1cfd6071ad300440c737823765f436/pkg/build/builder/docker.go#L103) builders to use the `build.status.output` field to do a docker push when available, or fallback to `build.spec.output.to`.

**Comment by rhcarvalho** [comment]
@liggitt does the above sound reasonable to you?

**Comment by rhcarvalho** [comment]
It turned out that step 3 above is more complex than I thought. In several places in the builders (S2I and Docker) we assume that the value of `Build.Spec.Output.To` is the resolved pushspec and make several decisions based on that.
To limit the number of changes that would be required, I started with:

1. Create a new field `Build.Status.Pushspec`.
2. Resolve the pushspec in the controller (as it used to be) and set both `buildCopy.Spec.Output.To` (as it used to be) and `Build.Status.Pushspec` (new).
