### ISSUE TITLE
rollback should disable triggers and users should be able to re-enable them

### ISSUE THREAD

**Issue by abhgupta** [openshift/origin#3008]
This issue is being created to capture the item mentioned in https://github.com/openshift/origin/issues/2455
 - osc rollback should disable triggers, if included
 - users should be able to restore them (probably something osc deploy should do)

**Comment by ironcladlou** [comment]
Should we disable image triggers and leave configChange triggers? If we actually remove all triggers, the trigger restoration command would have to receive a specific deployment as input in order to extract the trigger state from the config embedded in the deployment.

Just disabling the image trigger is enough to prevent the kind of oddities described in #3070.

**Comment by smarterclayton** [comment]
Disable image triggers only SGTM

**Comment by abhgupta** [comment]
@smarterclayton @danmcp Have bumped this up to a P1 since #3070 was marked as a P0.
