### ISSUE TITLE
Deployments: rollback will result in a 0 net change

### ISSUE THREAD

**Issue by csrwng** [openshift/origin#3070]
Using the stream and deployment config here:
https://gist.github.com/csrwng/e9b71aa1d5750390f4be

create the dc with tag v1
edit the dc with tag v2
rollback to tag v1

expected, a new replication controller with image v1 will eventually become the current one. 
actual: a new rc with v1 is created and scaled up properly, however, right afterwards, a new rc with v2 is created and the v1 rc is wound down to 0. Net result is that v2 is still the active image for all replicas.

**Comment by smarterclayton** [comment]
P0 if we merge canary

**Comment by ironcladlou** [comment]
We don't set labels on the deployment for this purpose (as we used to be able to rely only on annotations for correlation), but we can easily make the change now.

**Comment by ironcladlou** [comment]
@csrwng Did you actually observe an RC with the v2 image? After the `osc edit` to set the container image to `v2` manually, this is what happened for me:

```
CONTROLLER   CONTAINER(S)   IMAGE(S)            SELECTOR                                        REPLICAS
gohello-1    gohello        cewong/gohello:v1   deployment=gohello-1,deploymentconfig=gohello   0
gohello-2    gohello        cewong/gohello:v1   deployment=gohello-2,deploymentconfig=gohello   5
```

The reason my edit was effectively discarded is because there's both a config change and an image change trigger. When the container image is updated manually, the config change trigger controller gets the update, sees there's an image change trigger defined, and so updates the config with the latest ImageStream tags based on the trigger. The trigger in your gist is [pinned to gohello:v1](https://gist.github.com/csrwng/e9b71aa1d5750390f4be#file-dc-json-L29) and so during the config change trigger handling the container is updated to the latest pullspec for the `gohello:v1` image stream tag, which is `cewong/gohello:v1`.

Rolling back yields:

```
CONTROLLER   CONTAINER(S)   IMAGE(S)            SELECTOR                                        REPLICAS
gohello-1    gohello        cewong/gohello:v1   deployment=gohello-1,deploymentconfig=gohello   0
gohello-2    gohello        cewong/gohello:v1   deployment=gohello-2,deploymentconfig=gohello   0
gohello-3    gohello        cewong/gohello:v1   deployment=gohello-3,deploymentconfig=gohello   5
```

I didn't observe `cewong/gohello:v2` being used.

If the image change trigger is removed, I get the expected result:

```
CONTROLLER   CONTAINER(S)   IMAGE(S)            SELECTOR                                        REPLICAS
gohello-1    gohello        cewong/gohello:v1   deployment=gohello-1,deploymentconfig=gohello   0
gohello-2    gohello        cewong/gohello:v2   deployment=gohello-2,deploymentconfig=gohello   0
gohello-3    gohello        cewong/gohello:v1   deployment=gohello-3,deploymentconfig=gohello   5
```

Can you confirm exactly how many RCs you saw created in total? I still can't reproduce it exactly as you've described and can't yet think of any conditions that could make it happen (cc @abhgupta).

I think the way the triggers interact right now, users of configChange+imageChange triggers might see surprising behavior if they directly modify the container image in the deploymentConfig if there's a trigger defined for that container/image.

**Comment by csrwng** [comment]
I do observe 4 rc's at the end of the rollback. Let's schedule some time in the morning for a live session. Maybe we're doing things differently.

**Comment by ironcladlou** [comment]
Okay, so @csrwng and I figured out what's happening here.

```
# 1. initial config:
trigger from: gohello:v1, container image: cewong/gohello:v1
# 2. oc edit config to:
trigger from: gohello:v2, container image: cewong/gohello:v2
# 3. rollback to 1 (triggers are NOT included in the rollback by default), config is:
trigger from: gohello:v2, container image: cewong/hello:v1
```

After the rollback, you end up with two deployments:

```
CONTROLLER   CONTAINER(S)
gohello-3    cewong/gohello:v1
gohello-4    cewong/gohello:v2
```

`gohello-3` was created because the rollback updated the container image to `cewong/gohello:v1` directly and also included a bumped version number. So the deployment was created with the current state of the config, not as a result of trigger processing.

Then, because the trigger still points to `cewong:v2`, eventually the imageChangeTrigger syncs and notices that the config container image `cewong/gohello:v1` doesn't match the triggered latest tag value for `cewong:v2` and so updates the config container image to `cewong/gohello:v2`. This update causes `gohello-4` to be created.

This is a case where our default behavior to exclude triggers during rollback is problematic. If you have image triggers defined, they're likely going to cause an update right after your rollback unless:

1. Your trigger "from"s haven't changed since the rollback, AND
2. The triggered tag values haven't changed

#3008 covers disabling triggers on rollback, which I think would prevent this unexpected behavior.

**Comment by ironcladlou** [comment]
>P0 if we merge canary 

Need to merge or otherwise reconcile this issue with #3008 in terms of priority.

**Comment by danmcp** [comment]
Dup of: https://github.com/openshift/origin/issues/3008
