### ISSUE TITLE
Add ability to run certain upstream E2E tests against OpenShift

### ISSUE THREAD

**Issue by pmorie** [openshift/origin#3075]
I think we should have a command like `oc ex e2e` that lets you run upstream e2e tests against an openshift instance.  I routinely run the upstream binaries against OpenShift to help diagnose issues or determine if an issue a user reports is a real bug or user error.  The problem with this is that there is typically drift in the API enough that it can be hit or miss whether the tests will work with the API.

@smarterclayton I know you will not love this idea but it has a lot of utility for certain cases.

**Comment by derekwaynecarr** [comment]
I would say it should be a separate binary, and not in experimental.

**Comment by smarterclayton** [comment]
It's easy to add a new binary for testing or utility.  I'm fine with running upstream e2e - we ourselves eventually want an extended e2e suite for complex behavior.

**Comment by pmorie** [comment]
OK, one of the use-cases for this is have an end-user run an e2e against
their own system to see if a problem they're seeing is a bug in a feature
or PEBCAK

**Comment by stevekuznetsov** [comment]
Today you:

```
yum install atomic-openshift-tests
export KUBECONFIG='...'
/usr/libexec/origin/extended.test --ginkgo.focus='...'
```

Do we need anything else?

**Comment by smarterclayton** [comment]
No

On Apr 8, 2017, at 12:54 PM, Steve Kuznetsov <notifications@github.com>
wrote:

Today you:

yum install atomic-openshift-tests
export KUBECONFIG='...'
/usr/libexec/origin/extended.test --ginkgo.focus='...'

Do we need anything else?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/origin/issues/3075#issuecomment-292730537>,
or mute the thread
