### ISSUE TITLE
Scheduler doesn't take heed of `--selector` during initial deployment

### ISSUE THREAD

**Issue by miminar** [openshift/origin#3087]
I set up my nodes according to beta4 tutorial with a slightly different domain names:

    osc get nodes
    NAME                      LABELS                                                                     STATUS
    os-master.miminar.local   kubernetes.io/hostname=os-master.miminar.local,region=infra,zone=default   Ready
    os-node1.miminar.local    kubernetes.io/hostname=os-node1.miminar.local,region=primary,zone=east     Ready
    os-node2.miminar.local    kubernetes.io/hostname=os-node2.miminar.local,region=primary,zone=west     Ready

Got to a section "Storage for the registry" and run following command:

    osadm registry --create \
    --credentials=/etc/openshift/master/openshift-registry.kubeconfig \
    --images='registry.access.redhat.com/openshift3_beta/ose-${component}:${version}' \
    --selector="region=infra" --mount-host=/mnt/registry

and then watched pods:

    osc get pods
    POD                        IP         CONTAINER(S)   IMAGE(S)                                                                 HOST                                     LABELS                                                      STATUS    CREATED         MESSAGE
    docker-registry-1-deploy                                                                                                      os-node2.miminar.local/                  <none>                                                      Pending   7 seconds       
                                          deployment     openshift3_beta/ose-deployer:v0.5.2.2                                                                                                                                                                   
    router-1-noiee             10.1.0.3                                                                                           os-master.miminar.local/192.168.122.97   deployment=router-1,deploymentconfig=router,router=router   Running   About an hour   
                                          router         registry.access.redhat.com/openshift3_beta/ose-haproxy-router:v0.5.2.2                                                                                                        Running   About an hour

Although the `region=infra` was specified. The initial deployment took place on `os-node2` (`region=primary,zone=west`).

Same command two minutes later shows that router has been rescheduled:

    osc get pods
    POD                       IP         CONTAINER(S)   IMAGE(S)                                                                  HOST                                     LABELS                                                                                  STATUS    CREATED         MESSAGE
    docker-registry-1-kauip                                                                                                       os-master.miminar.local/                 deployment=docker-registry-1,deploymentconfig=docker-registry,docker-registry=default   Pending   28 seconds      
                                         registry       registry.access.redhat.com/openshift3_beta/ose-docker-registry:v0.5.2.2                                                                                                                                                              
    router-1-noiee            10.1.0.3                                                                                            os-master.miminar.local/192.168.122.97   deployment=router-1,deploymentconfig=router,router=router                               Running   About an hour   
                                         router         registry.access.redhat.com/openshift3_beta/ose-haproxy-router:v0.5.2.2                                                                                                                                     Running   About an hour  

It caught me by surprise and made me look for bugs in configuration before I checked the nodes again.

**Comment by ncdc** [comment]
@miminar the deployer pod was scheduled on node2. I'm not sure if we're restricting where the deployer pods run. But as you see, the registry pod was scheduled on the correct node.

@ironcladlou any thoughts?

**Comment by detiber** [comment]
@ncdc @ironcladlou It seems kind of odd that the deployer would run outside of the selected region (since by region we'd tend to think geographic separation).  I've noticed this with build pods as well.  

I can see a potential use case for wanting to target a different specific subset of nodes for build pods and/or deployer pods, but I don't think we'd want that behavior by default.

**Comment by ironcladlou** [comment]
The deployed pods end up on the right nodes because the replicationController template on the deploymentConfig has a nodeSelector field. Node selection for the deployer pod/process itself is not supported. To support node selection for the deployer pod, we'd need to do something like:

1. Add a field to deploymentConfig to drive deployer pod node selection
2. Make deployer pods inherit any node selector from the replicationController template the config contains

There are also hook pods to consider (which the deployer pod may itself create). It would need also need some sort of inheritence rules.

**Comment by detiber** [comment]
@ironcladlou The main use case that I would see is if there is either a system default nodeSelector or a project nodeSelector set.  It may be sufficient to support that use case to start (if it is less work than inheriting from the replicationController).

That said, it may also be preferable to have things like deploymer pods, build pods, etc have a different default nodeSelector for a project or a cluster as well, instead of tying it to the replicationController (or having the replicationController be able to support different node selectors for build pods, deployer pods, etc).
