### ISSUE TITLE
Cannot use ping via 'oc exec'

### ISSUE THREAD

**Issue by sdodson** [openshift/origin#3326]
This used to work a week ago as that's how I was testing the SDN.

```
[root@ose3-master ~]# oc exec -p fedora-net ping www.google.com
ping: icmp open socket: Operation not permitted
error: Error executing remote command: Error executing command in container: Error executing in Docker Container: 2
```

The image I'm using is docker.io/dcbw/fedora-net id a1eff209999c  @mrunalp mentioned that perhaps ping didn't have the correct capabilities set but I'm wondering why this worked a week ago but not now.

**Comment by liggitt** [comment]
@pweil, does the default scc restrict this?

**Comment by smarterclayton** [comment]
It does - you don't have cap sys net for raw sockets.

**Comment by liggitt** [comment]
opened item to document required capabilities

**Comment by pweil-** [comment]
This is actually not an SCC capabilities problem in this case but it did point out an interesting issue.  

1.  To run as a non-root with special caps you must request the cap (SCC/SC) AND have fcaps set on the file (that's the interesting part)
1.  Docker provides cap_net_raw by default 
1.  This image is a bit out of date, the ping command does not have fcaps set

```
[vagrant@openshiftdev ping]$ docker run -it docker.io/dcbw/fedora-net getcap /usr/bin/ping
/usr/bin/ping =


[vagrant@openshiftdev ping]$ docker run -it fedora:latest /bin/bash
[root@43935663d8b1 /]# yum install -y iputils
[root@43935663d8b1 /]# getcap /usr/bin/ping
/usr/bin/ping = cap_net_admin,cap_net_raw+ep
```
Running `setcap cap_net_raw,cap_net_admin+p /usr/bin/ping` fixes this.  Ping should work OOTB for updated Fedora images, no SC request necessary.  

The interesting part is that you must have the container capability and fcaps in order to work properly with the non-root user.  Using `--cap-drop NET_RAW` confirmed that you cannot rely only on the fcaps.

I am going to add a new How-To on how to allow someone to add a cap for the issue that was opened and note that the fcap is still a requirement.

**Comment by smarterclayton** [comment]
We wouldn't encourage the SCC approach unless someone was doing something more important than ping, right?

**Comment by mrunalp** [comment]
That's what I suspected when I first discussed with sdodson. Fedora images had this issue.

**Comment by pweil-** [comment]
> We wouldn't encourage the SCC approach unless someone was doing something more important than ping, right?

Correct, it would be for something docker didn't give OOTB that the image needed.
