### ISSUE TITLE
Websocket support for exec

### ISSUE THREAD

**Issue by jimmidyson** [openshift/origin#3366]
Currently trying to use websocket to create browser terminal running exec for fabric8 console. Websocket request is sent but server returns unexpected 200 rather than 101 for socket upgrade & hence websocket connection is terminated. Should exec support websockets? Seems perfect to be able to create browser based terminal connecting to pods.

Tested also on cmd line using wscat (https://github.com/websockets/wscat) which works great for watches, etc, but not so much for exec:

```
$ wscat -n -c 'wss://localhost:8443/api/v1/namespaces/default/pods/heaps
ter-4roo8/exec?access_token=<validtoken>&command=ash&stdin=true
&stderr=true&tty=true'

error: Error: unexpected server response (200)
```

**Comment by ncdc** [comment]
`exec` currently only talks SPDY. We ultimately want to switch to HTTP/2, but there isn't support for that in Go yet. To support `exec` via websockets, we'd either have to tunnel SPDY through websockets, or find a way to do stream multiplexing in websockets, and then add support for that in Kubernetes. I'll do some research and see what looks easiest.

**Comment by jimmidyson** [comment]
Thanks. Let me know of there's anything I can do to help.

Out of interest when you say http/2 isn't supported in go yet, what about https://github.com/bradfitz/http2? Doesn't do what we need?

**Comment by smarterclayton** [comment]
It doesn't include a client library yet.

**Comment by smarterclayton** [comment]
We supported web sockets over spdy at one point in libchan (it's a simple tunneling problem).  However, you need a client that can speak the protocol you're using over it, so you still need a client library.

I think a websocket compatible exec would just be a slightly different implementation from the master (rather than plumbed all the way through), but would still require some client library to make sense of.  One way commands would be much easier, so I would like us to take a look at that first.

**Comment by bparees** [comment]
@ncdc can you create a card for this?

**Comment by ncdc** [comment]
https://trello.com/c/jgNabqIX/291-add-websocket-support-for-exec

**Comment by jimmidyson** [comment]
How's this going? Any target for this? Thinking on this & wondering why we can't support websockets in the same way docker attach can?

**Comment by smarterclayton** [comment]
We *can* support it, but someone has to do the work :)  It's more
complicated because we have to get the streaming right as it crosses
boundaries (it's HTTP2 between nodes and masters, but web sockets between
master and clients).

On Thu, Aug 20, 2015 at 3:09 AM, Jimmi Dyson <notifications@github.com>
wrote:

> How's this going? Any target for this? Thinking on this & wondering why we
> can't support websockets in the same way docker attach can?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openshift/origin/issues/3366#issuecomment-132914345>.
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by ncdc** [comment]
@smarterclayton not sure how you'd do that offhand, since the master blindly proxies the client's connection (i.e. SPDY) to the Kubelet. Would it make more sense to try to add a websocket implementation that replaces SPDY?

**Comment by smarterclayton** [comment]
I don't know.  It depends on what the stream would look like.  Once the
connection is established its still just shuttling bytes across the wire,
but having the kubelet be multimode seems like it doesn't have much of a
benefit for its own sake.

On Aug 24, 2015, at 11:50 AM, Andy Goldstein <notifications@github.com>
wrote:

@smarterclayton <https://github.com/smarterclayton> not sure how you'd do
that offhand, since the master blindly proxies the client's connection
(i.e. SPDY) to the Kubelet. Would it make more sense to try to add a
websocket implementation that replaces SPDY?

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/issues/3366#issuecomment-134231983>.

**Comment by ncdc** [comment]
You'd need to have an endpoint in the apiserver that accepts websocket connections and translates them to SPDY. This means you'd need to establish the SPDY connection to the Kubelet, and then create streams as needed, io.Copy between the websocket stream and the SPDY stream, etc.

**Comment by smarterclayton** [comment]
Yes, but I can view websockets as a bridge to the backend, vs being a
transport.  Websockets for logs is a more pressing case anyway so don't
want to bog down on exec yet.  That's one where two streams is nice but not
strictly required for the short term.

On Aug 24, 2015, at 12:06 PM, Andy Goldstein <notifications@github.com>
wrote:

You'd need to have an endpoint in the apiserver that accepts websocket
connections and translates them to SPDY. This means you'd need to establish
the SPDY connection to the Kubelet, and then create streams as needed,
io.Copy between the websocket stream and the SPDY stream, etc.

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/issues/3366#issuecomment-134237891>.

**Comment by jimmidyson** [comment]
I'm happily using websockets for exec now thanks- can this be closed or is there more to do?
