### ISSUE TITLE
unable to find tag event for &api.ObjectReference{Kind:"ImageStreamTag", Namespace:"", Name:"late...

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#3374]
Message seems wrong, what is happening?

https://app.getsentry.com/red-hat/openshift-3-stg/group/69631512/

```
*errors.errorString: unable to find tag event for &api.ObjectReference{Kind:"ImageStreamTag", Namespace:"", Name:"latest", UID:"", APIVersion:"", ResourceVersion:"", FieldPath:""}
  File "/builddir/build/BUILD/openshift-git-21.5837ae7/_build/src/github.com/openshift/origin/pkg/cmd/util/serviceability/sentry.go", line 61, in CaptureError
  File "/builddir/build/BUILD/openshift-git-21.5837ae7/_build/src/github.com/openshift/origin/pkg/cmd/util/serviceability/panic.go", line 28, in CaptureError.fm
  File "/builddir/build/BUILD/openshift-git-21.5837ae7/_thirdpartyhacks/src/github.com/GoogleCloudPlatform/kubernetes/pkg/util/util.go", line 82, in HandleError
  File "/builddir/build/BUILD/openshift-git-21.5837ae7/_build/src/github.com/openshift/origin/pkg/image/registry/imagestream/strategy.go", line 192, in tagsChanged
  File "/builddir/build/BUILD/openshift-git-21.5837ae7/_build/src/github.com/openshift/origin/pkg/image/registry/imagestream/strategy.go", line 72, in Validate
...
(8 additional frame(s) were not displayed)
```

**Comment by ncdc** [comment]
This happens if you try to set up a spec tag reference to another tag that doesn't exist. For example:

1. Create ImageStream foo
2. `oc tag foo:latest foo:bar`

You'll also see this when you do this: `oc create -f image-streams-centos7.json`, as it contains streams such as:

```json
{
      "kind": "ImageStream",
      "apiVersion": "v1beta3",
      "metadata": {
        "name": "ruby",
        "creationTimestamp": null
      },
      "spec": {
        "dockerImageRepository": "openshift/ruby-20-centos7",
        "tags": [
          {
            "name": "latest"
          },
          {
            "name": "2.0",
            "annotations": {
              "description": "Build and run Ruby 2.0 applications",
              "iconClass": "icon-ruby",
              "tags": "builder,ruby",
              "supports": "ruby:2.0,ruby",
              "version": "2.0"
            },
            "from": {
              "Kind": "ImageStreamTag",
              "Name": "latest"
            }
          }
        ]
      }
    }
```

Here you'll see it defines a spec tag `2.0` to track `latest`, but `latest` is an imported tag, so it will take a little bit before it's imported.

**Comment by ncdc** [comment]
We should probably make the error message better

**Comment by smarterclayton** [comment]
Yeah, it needs to actually say what is wrong :)

But crucially, whoever is writing this needs to also say why it's happening (and it's possible there should not even be an event)

**Comment by ncdc** [comment]
It comes from https://github.com/openshift/origin/blob/master/pkg/image/registry/imagestream/strategy.go#L192

I don't think this is an event per se, unless I'm misreading the code...

Do you want no message at all, or just a better message? It's not reported to the user, since it's valid to do this (i.e. set up a tracking tag prior to the existence of the tag you're tracking).

**Comment by smarterclayton** [comment]
> On Jun 22, 2015, at 10:57 AM, Andy Goldstein <notifications@github.com> wrote:
> 
> It comes from https://github.com/openshift/origin/blob/master/pkg/image/registry/imagestream/strategy.go#L192
> 
> I don't think this is an event per se, unless I'm misreading the code...
> 
> Do you want no message at all, or just a better message? It's not reported to the user, since it's valid to do this (i.e. set up a tracking tag prior to the existence of the tag you're tracking).
> 
I don't think we should be reporting this.  An empty tag is an empty tag, not an error.
