### ISSUE TITLE
Registry should include image stream uid in repository path

### ISSUE THREAD

**Issue by ncdc** [openshift/origin#3521]
Scenario w/o this proposed change:

1. Create an image stream, push image A1 with layer L1
1. Delete image stream
1. Create image stream with same name

In the registry's storage, the signatures and layers linked into the repository's _manifests and _layers directories are not deleted when the image stream is deleted. It is possible for a registry client to request a layer by id if the layer id is known and it was previously linked into the repository, when in this case, because the image stream was deleted and recreated, it should have a clean state.

Proposed solution:

1. When an image stream is created, if it's managed by OpenShift (spec.dockerImageRepository is empty), automatically add a new annotation indicating the stream is stored in the registry by uid
1. In repositorymiddleware.go, override `Name()` in `repository` to return `<stream name>-<uid>`. This will require retrieving the image stream at least once for every request to the registry.

**Comment by ncdc** [comment]
@smarterclayton

**Comment by smarterclayton** [comment]
Has security implications.  Alternatively, we can do a migration and reset the annotation.

Do we do a SAR to check your access or do we try to fetch the image stream as you?

**Comment by ncdc** [comment]
We create a client using the user's token (https://github.com/openshift/origin/blob/master/pkg/dockerregistry/server/auth.go#L128) and verify the user has access (https://github.com/openshift/origin/blob/master/pkg/dockerregistry/server/auth.go#L253-L258).

All future operations such as retrieving the image stream, retrieving images, etc are performed using the registry's client (e.g. https://github.com/openshift/origin/blob/master/pkg/dockerregistry/server/repositorymiddleware.go#L237).

**Comment by ncdc** [comment]
@smarterclayton after thinking about this some more, I don't think that overriding `Name()` makes sense, as that function is called in various places and I'm not certain that it's safe to return anything other than the client-specified name from the HTTP requests.

Instead of that, what if we added a check in `newRepository` (https://github.com/openshift/origin/blob/master/pkg/dockerregistry/server/repositorymiddleware.go#L38) that checks for a custom file we create (`uid`) that contains the last-known uid for a repo. If it differs from the ImageStream's current uid, update the file and blow away anything in the repos directory tree for that repo. There's probably some races that could occur with this approach, but the other option I can think of would be to get deep into the upstream code to make it possible to manipulate the path mapper used to construct storage paths, and that's all buried and unexposed at the moment, which would make it pretty hard.

Thoughts?

**Comment by smarterclayton** [comment]
Will reflect - I share your concern

On Jul 21, 2015, at 3:25 PM, Andy Goldstein <notifications@github.com>
wrote:

@smarterclayton <https://github.com/smarterclayton> after thinking about
this some more, I don't think that overriding Name() makes sense, as that
function is called in various places and I'm not certain that it's safe to
return anything other than the client-specified name from the HTTP requests.

Instead of that, what if we added a check in newRepository (
https://github.com/openshift/origin/blob/master/pkg/dockerregistry/server/repositorymiddleware.go#L38)
that checks for a custom file we create (uid) that contains the last-known
uid for a repo. If it differs from the ImageStream's current uid, update
the file and blow away anything in the repos directory tree for that repo.
There's probably some races that could occur with this approach, but the
other option I can think of would be to get deep into the upstream code to
make it possible to manipulate the path mapper used to construct storage
paths, and that's all buried and unexposed at the moment, which would make
it pretty hard.

Thoughts?

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/issues/3521#issuecomment-123453831>.

**Comment by smarterclayton** [comment]
Changes coming soon should fix this.  Closing since you have to have permissions on stream first
