### ISSUE TITLE
Clean up older failed deployment pods

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#3543]
When a number of deployment failures have occurred in a row, we should clean up the older deployment pods.

Ran 3 failing deploys in a row, still had pods for each deploy.

**Comment by ironcladlou** [comment]
One way to do this within the existing controller framework would be to make each pod handler invocation query for other deployer pods so that a relative position/age could be determined and then delete, but that seems like an expensive thing to do on every full sync. This seems better handled with a general GC framework.

Is this still a p2 at the moment?

**Comment by smarterclayton** [comment]
Yes for now.

On Aug 18, 2015, at 3:02 PM, Dan Mace <notifications@github.com> wrote:

One way to do this within the existing controller framework would be to
make each pod handler invocation query for other deployer pods so that a
relative position/age could be determined and then delete, but that seems
like an expensive thing to do on every full sync. This seems better handled
with a general GC framework.

Is this still a p2 at the moment?

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/issues/3543#issuecomment-132319673>.

**Comment by ironcladlou** [comment]
@smarterclayton, please close this issue in favor of https://trello.com/c/uoIAABEj.
