### ISSUE TITLE
Docker registry auth checks leave hanging TCP connections

### ISSUE THREAD

**Issue by ncdc** [openshift/origin#3569]
Every operation against the docker registry (image pull, push, prune, etc) requires the registry to check authentication with the master, using the token of the incoming request to the registry. That involves constructing a new API client object for each auth check. Throwaway clients cause lots of open idle connections that hang around until the server times out (master defaults to 1 hour). It is possible to run out of open file descriptors.

Depends on https://github.com/GoogleCloudPlatform/kubernetes/pull/10557

**Comment by ncdc** [comment]
@brenton do you want a bz for this so QE can be sure to test it?

**Comment by brenton** [comment]
@ncdc , what would be the easiest way for them to verify?  Would it require load testing and ensuring file descriptors aren't endlessly growing?  I'm confused why it's only leaking file descriptors.  If it's holding on to the clients I'm guessing it's also leaking memory too.  Is it just that the file descriptor limits typically cause problems first?

I can ask QE if they want a specific bug for this or if it would simply be covered by their other tests.

**Comment by ncdc** [comment]
The easiest way would be to use `lsof` and make sure the # of entries doesn't increase with each request endlessly.

I'm not sure if it's leaking memory or not. It shouldn't be holding on to the clients, but it's definitely holding on to the TCP connections...

**Comment by ncdc** [comment]
@smarterclayton using your SAR impersonator, I'm able to get this down to only leaking 1 fd per login, and 1 per ImageStream auto provisioning. If I can impersonate `client.Users().Get("~")` and `client.ImageStreams(ns).Create()`, I can truly use a single client and not leak. Is it appropriate to create impersonators for these 2 resources? It seems hacky, and I really wish there was a better global way to do this for the entire suite of Client calls...

**Comment by smarterclayton** [comment]
I think we need a global way.  I can't see a way to close out the
transport.  We should probably try to share the core transport (that's one
possible improvement).  But that runs into reuse of TCP connections and the
total number of connections open at a time (and it won't work for TLS).

We'd have to make it easy to create a new method on the RESTClient that
wraps the "new request" call early on - so you'd do
client.WithToken(token).<regular calls>.

On Wed, Jul 22, 2015 at 3:50 PM, Andy Goldstein <notifications@github.com>
wrote:

> @smarterclayton <https://github.com/smarterclayton> using your SAR
> impersonator, I'm able to get this down to only leaking 1 fd per login, and
> 1 per ImageStream auto provisioning. If I can impersonate
> client.Users().Get("~") and client.ImageStreams(ns).Create(), I can truly
> use a single client and not leak. Is it appropriate to create impersonators
> for these 2 resources? It seems hacky, and I really wish there was a better
> global way to do this for the entire suite of Client calls...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openshift/origin/issues/3569#issuecomment-123843768>.
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by smarterclayton** [comment]
We may need to be more flexible to allowing other options in the future -
WithToken won't be enough.  Not sure what the right pattern is but wrapping
/ overriding / altering the RESTClient (somehow) seems like a story.

On Wed, Jul 22, 2015 at 4:26 PM, Andy Goldstein <notifications@github.com>
wrote:

> Yeah, let me see if I can come up with something.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openshift/origin/issues/3569#issuecomment-123852053>.
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by ncdc** [comment]
@smarterclayton I agree we'll probably need more flexibility, but for argument's sake, let's examine just `WithToken` for now.

If you already have a `Client`, and you call `WithToken(token)` on it, ideally it would return a new Client-like instance (`impersonatingClient`) that is able of using the token. We obviously can't store `token` in the `Client` itself as that wouldn't be thread safe.

Now let's look at something like `client.Users()`:

```go
func (c *Client) Users() UserInterface {
  return newUsers(c)
}
```

Here's user-related code:

```go
type users struct {
  r *Client
}

func newUsers(c *Client) *users {
  return &users{
    r: c,
  }
}

func (c *users) Get(name string) (result *userapi.User, err error) {
  result = &userapi.User{}
  err = c.r.Get().Resource("users").Name(name).Do().Into(result)
  return
}
```

Unless the `impersonatingClient` reimplements `Users()` and all the other methods from `Interface`, I don't see a clean and easy way to make this work. Even then, I'm not convinced it would work, since all the client code expects a `Client` when creating the various helpers (e.g. `newUsers(c *Client)`).

Do you have any suggestions?

**Comment by smarterclayton** [comment]
The problem is really c.r. - how do we change that to be a rest client
interface (like resource builder)

On Jul 23, 2015, at 9:53 AM, Andy Goldstein <notifications@github.com>
wrote:

@smarterclayton <https://github.com/smarterclayton> I agree we'll probably
need more flexibility, but for argument's sake, let's examine just WithToken
for now.

If you already have a Client, and you call WithToken(token) on it, ideally
it would return a new Client-like instance (impersonatingClient) that is
able of using the token. We obviously can't store token in the Client
itself as that wouldn't be thread safe.

Now let's look at something like client.Users():

func (c *Client) Users() UserInterface {
  return newUsers(c)
}

Here's user-related code:

type users struct {
  r *Client
}
func newUsers(c *Client) *users {
  return &users{
    r: c,
  }
}
func (c *users) Get(name string) (result *userapi.User, err error) {
  result = &userapi.User{}
  err = c.r.Get().Resource("users").Name(name).Do().Into(result)
  return
}

Unless the impersonatingClient reimplements Users() and all the other
methods from Interface, I don't see a clean and easy way to make this work.
Even then, I'm not convinced it would work, since all the client code
expects a Client when creating the various helpers (e.g. newUsers(c *Client)
).

Do you have any suggestions?

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/issues/3569#issuecomment-124113894>.

**Comment by ncdc** [comment]
Even if we make `c.r` a `resource.RESTClient`, you still need a way for the `r` in `c.r.Get()` to be the `impersonatingClient`, and the only way I can see to do this is to duplicate all the methods on `Client` that implement `Interface` into `impersonatingClient` - yuck.

**Comment by smarterclayton** [comment]
No - you would wrap rest client which is get/post/put/delete

On Jul 23, 2015, at 10:21 AM, Andy Goldstein <notifications@github.com>
wrote:

Even if we make c.r a resource.RESTClient, you still need a way for the r
in c.r.Get() to be the impersonatingClient, and the only way I can see to
do this is to duplicate all the methods on Client that implement Interface
into impersonatingClient - yuck.

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/issues/3569#issuecomment-124122282>.

**Comment by ncdc** [comment]
I tried this but it didn't work:

```go
func (c *Client) WithToken(token string) Interface {
  return &impersonatingClient{c, token}
}

type impersonatingClient struct {
  *Client
  token string
}

func (ic *impersonatingClient) Verb(verb string) *kclient.Request {
  return ic.Client.Verb(verb).SetHeader("Bearer", ic.token)
}
```

The problem being that when you call `impersonatingClient.Users()` it uses the embedded `Client`'s function, which results in the embedded `Client` being passed to `newUsers`. Is there some way to do this without having to duplicate all the Interface methods?

**Comment by smarterclayton** [comment]
Impersonating client should take a restclient interface?

On Jul 23, 2015, at 10:31 AM, Andy Goldstein <notifications@github.com>
wrote:

I tried this but it didn't work:

func (c *Client) WithToken(token string) Interface {
  return &impersonatingClient{c, token}
}
type impersonatingClient struct {
  *Client
  token string
}
func (ic *impersonatingClient) Verb(verb string) *kclient.Request {
  return ic.Client.Verb(verb).SetHeader("Bearer", ic.token)
}

The problem being that when you call impersonatingClient.Users() it uses
the embedded Client's function, which results in the embedded Client being
passed to newUsers. Is there some way to do this without having to
duplicate all the Interface methods?

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/issues/3569#issuecomment-124124543>.

**Comment by ncdc** [comment]
Yeah, but I still need some way for e.g client.Users() to use my impersonatingClient w/o me having to implement Users() in impersonatingClient.

**Comment by smarterclayton** [comment]
Not have an impersonating client.  Have an impersonating rest client.

On Jul 23, 2015, at 12:18 PM, Andy Goldstein <notifications@github.com>
wrote:

Yeah, but I still need some way for e.g client.Users() to use my
impersonatingClient w/o me having to implement Users() in
impersonatingClient.

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/issues/3569#issuecomment-124154623>.

**Comment by ncdc** [comment]
I still don't see how to use that. As a consumer of the client package, I have a mostly opaque `Client`, from which I can get a `UserInterface` which lets me List, Create, Get, Update a User. I can't mutate my `Client` instance by changing the underlying `RESTClient` as that would affect all future usage. I need something that's a per-invocation mutation.

**Comment by ncdc** [comment]
I'm not making any progress on this. I'd like to add impersonation for Users and ImageStreams and make a note that we need to fix this globally later.

**Comment by liggitt** [comment]
(copied from #3885 description)

The leaks we're seeing around repeated throwaway client use is in the `http.Transport` idle connections pool, which holds connections open forever. I'll file a go issue asking for a KeepAliveTimeout, but until that happens, the options to improve this are:

1. Set `Transport.DisableKeepAlives=true` when setting up the transport (bad for places where we want to make several requests before discarding the client, which is pretty much everywhere)
2. Call `Transport.CloseIdleConnections` after we're done with a client (hard to plumb through access after the transport has been wrapped 4-5 times (for debugging, custom wrapping, bearer/basic auth, and user agent header-setting), sometimes hard to know when we're done with a client
3. Avoid constructing lots of identical `http.Transport` objects. If lots of throwaway clients are built with different TLS options, we can still see growth, but this will drastically help the "client per user verification" case

#3885 implements option 3 by building a key around all the unique inputs to the constructed transport. Ideally, a combination of 2 and 3 would be possible, but if we start collecting the constructed `http.Transport` objects in one place, that gives us a potential way to sweep them and call `CloseIdleConnections` occasionally.

**Comment by smarterclayton** [comment]
On Jul 23, 2015, at 8:11 PM, Jordan Liggitt <notifications@github.com>
wrote:

(copied from #3885 <https://github.com/openshift/origin/pull/3885>
description)

The leaks we're seeing around repeated throwaway client use is in the
http.Transport idle connections pool, which holds connections open forever.
I'll file a go issue asking for a KeepAliveTimeout, but until that happens,
the options to improve this are:

   1. Set Transport.DisableKeepAlives=true when setting up the transport
   (bad for places where we want to make several requests before discarding
   the client, which is pretty much everywhere)
   2. Call Transport.CloseIdleConnections after we're done with a client
   (hard to plumb through access after the transport has been wrapped 4-5
   times (for debugging, custom wrapping, bearer/basic auth, and user agent
   header-setting), sometimes hard to know when we're done with a client
   3. Avoid constructing lots of identical http.Transport objects. If lots
   of throwaway clients are built with different TLS options, we can still see
   growth, but this will drastically help the "client per user verification"
   case

#3885 <https://github.com/openshift/origin/pull/3885> implements option 3
by building a key around all the unique inputs to the constructed
transport. Ideally, a combination of 2 and 3 would be possible, but if we
start collecting the constructed http.Transport objects in one place, that
gives us a potential way to sweep them and call CloseIdleConnections
occasionally.


Will our servers have clients against remote servers beyond ourselves?  If
so we have to have the sweep for DefaultTransport (for normal TLS and HTTP)
anyway, because that could grow unbounded.


—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/issues/3569#issuecomment-124273902>.

**Comment by liggitt** [comment]
> Will our servers have clients against remote servers beyond ourselves? If so we have to have the sweep for DefaultTransport (for normal TLS and HTTP) anyway, because that could grow unbounded.

The same transport is shared for multiple servers if the TLS options are the same, but you could certainly construct connection config options that would result in lots of unique transports (lots and lots of distinct client cert credentials or trusted CA bundles, etc). I don't think that's likely, but it's possible.

**Comment by liggitt** [comment]
The connections close when the remote server times out, so they don't stay open forever, but 60 minutes (our default master timeout) is a long time to hold open an idle connection we should be done with.

**Comment by ncdc** [comment]
@liggitt we can close this, right, since #4116 went in?

**Comment by liggitt** [comment]
yup
