### ISSUE TITLE
SubjectAccessReview should include Namespace in body of request, be a cluster scoped resource

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#3668]
There's really no reason that the subject access review request has to be scoped to a particular namespace at submission time, since the policy engine can verify that the caller can make subject access review requests independent of the target (which can be subsequently verified by the implementation).

As is, the dual nature of cluster and namespaced SAR causes issues as we know - it would be better to make the SAR cluster scoped, take namespace as a parameter, check cluster SAR policy at the top level and then do a further check inside the SAR endpoint.

As a consumer trying to use SAR, I expected it to be a self contained request.  The namespace level checking feels awkward.

**Comment by deads2k** [comment]
Right now, it is not possible to create a role/binding that expresses the rule that you can access a resource at the cluster scope, but not a the namespace scope.  This means by granting a user rights to use the existing ClusterSAR, we'd be allowing them to use SARs in every namespace.

We could resolve this by keeping SAR as is and creating a new endpoint with a new kind for ClusterSAR.

Given the upstream issue, are we going to carry a patch or will we break backwards compatibility?

**Comment by smarterclayton** [comment]
On Jul 14, 2015, at 8:44 AM, David Eads <notifications@github.com> wrote:

Right now, it is not possible to create a role/binding that expresses the
rule that you can access a resource at the cluster scope, but not a the
namespace scope. This means by granting a user rights to use the existing
ClusterSAR, we'd be allowing them to use SARs in every namespace.


We can just check again at the invocation point to verify you have
namespace SAR by reading the incoming request.  I think that's better than
having two endpoints.

We could resolve this by keeping SAR as is and creating a new endpoint with
a new kind for ClusterSAR.

Given the upstream issue, are we going to carry a patch or will we break
backwards compatibility?

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/issues/3668#issuecomment-121229084>.

**Comment by deads2k** [comment]
> We can just check again at the invocation point to verify you have
> namespace SAR by reading the incoming request.  I think that's better than
> having two endpoints.

If you have rights to hit the cluster scoped SAR, you **always** have rights to hit any namespaced SAR.

**Comment by smarterclayton** [comment]
There would be no namespaced SAR.  There would be only cluster SAR with a
field that requires you have either get on the namespace to see the
namespace or a specific SAR resource.

On Jul 15, 2015, at 8:54 AM, David Eads <notifications@github.com> wrote:

We can just check again at the invocation point to verify you have
namespace SAR by reading the incoming request. I think that's better than
having two endpoints.

If you have rights to hit the cluster scoped SAR, you *always* have rights
to hit any namespaced SAR.

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/issues/3668#issuecomment-121605768>.

**Comment by deads2k** [comment]
We might be saying the same thing.

Today we have
```
/SubjectAccessReview
/ns/namespace/SubjectAccessReview
```

Assuming we need to keep this for backwards compatibility, I cannot allow all users to hit "/SubjectAccessReview" and then do an internal check for for "/ns/namespace/SubjectAccessReview", because the internal check will always return true due to the access granted for "/SubjectAccessReview".


I will have to create "/ClusterSubjectAccessReview" and keep "/SubjectAccessReview" and "/ns/namespace/SubjectAccess" review as-is.  Agree?

**Comment by deads2k** [comment]
So I tried the approach we discussed:
 1. root scoped `subjectaccessreviews` stays and now accepts a namespace value
 1. project scoped `ns/subjectaccessreviews` stays for backward compatibility and must have a namespace equal to "this" namespace
 1. root scoped `subjectaccessreviews` checks for `ns/localsubjectaccessreviews` to determine if the user can run that particular SAR.

This fails because the API installer is fed with a map.  The name of resource (`subjectaccessreviews`) is the same in both cases and I can't be both `meta.RESTScopeNameRoot` and `meta.RESTScopeNameNamespace` at the same time.
