### ISSUE TITLE
When recreating the (internal) registry the master needs to be restarted

### ISSUE THREAD

**Issue by chmouel** [openshift/origin#3731]
If we are recreating the (internal) docker-registry the nodes would not see the new IP of the new docker-registry until we restart the master(s).

Is it the expected behaviour ?

**Comment by liggitt** [comment]
That being debated in #1723

**Comment by liggitt** [comment]
The issue is deleting and recreating the service, which is what changes the IP. Comment https://github.com/openshift/origin/issues/1723#issuecomment-92885857 indicates what we probably want to do is let you re-run the registry command to recreate underlying deployment config / pods while leaving the service (and associated IP) intact

**Comment by chmouel** [comment]
thanks Jordan, glad this is being worked on, i really should do a better search before filling a bug ;-)
