### ISSUE TITLE
No API for build-chain

### ISSUE THREAD

**Issue by twaugh** [openshift/origin#3737]
In order to know when a a set of rebuilds triggered by an image change has finished, I would like to use `oadm build-chain`. However, in the environment I need to get at that information, I'll only have access to the API entry point, not the `oadm` tool.

Is there any way to get this information via the API entry point?

**Comment by deads2k** [comment]
/cc @kargakis @smarterclayton 

Would want to consider this when think about overall graph access?

**Comment by smarterclayton** [comment]
So in general, "yes, we want to have a graph API".  Would need to close out the discussion about what that API would look like, and what would back it.  Generally when we have complex problems that aren't CRUD we try to design them from a client first, find the core behavior, then abstract them into an API (new-app is an example).

However, we also try to avoid building "all-in-one" APIs, if only because it limits and makes more complex the tools.

build-chain is a pretty clear use case of "I want to explore the relationships between builds from different clients" so I don't think it hits the "bad all-in-one" case.

**Comment by smarterclayton** [comment]
We have no plans to implement this soon, but eventually we would like to do it.  We won't forget, even with this closed.
