### ISSUE TITLE
UI only includes first port in generated service

### ISSUE THREAD

**Issue by liggitt** [openshift/origin#3764]
`oc new-app` exposes all container ports in the generated service (although it looks like it has an option to only include the first port, which is hard-coded to `false` at the moment)

The UI only includes the first container port in the generated service, and leaves it nameless (which is allowed for a single port).

@csrwng was the a reason to only include the first container port in the service?
@spadgett the UI should be consistent with new-app. That probably means including all container ports as service ports, and adding generated names to the service ports

**Comment by spadgett** [comment]
@csrwng @liggitt Can we add this in now?

```
      //TODO add in when server supports headless services without a port spec
//      if(port === 'None'){
//        service.spec.portalIP = 'None';
//      }else{
```

https://github.com/openshift/origin/blob/master/assets/app/scripts/services/applicationGenerator.js#L264

**Comment by spadgett** [comment]
Any reason not to use the port number as the name ("8080") or protocol-port ("tcp-8080")?

**Comment by liggitt** [comment]
new-app now generates the service port name using the port number and protocol

**Comment by liggitt** [comment]
see `portName` in the generate package

**Comment by csrwng** [comment]
> @csrwng was the a reason to only include the first container port in the service?

Sorry @liggitt - just getting to your comment. 
Short answer: because @smarterclayton :-)
Longer answer: At some point services could only point to a single port. To expose every port we would have had to create multiple services which likely would have included ports that you didn't want to expose, plus we had 'oc expose' if you really wanted to expose a port.



> @csrwng @liggitt Can we add this in now?

So headless services exist now, just not sure that we'd want to generate one here when we can't detect a port. If we do decide to generate them, we should do the same in new-app. @smarterclayton ?

**Comment by smarterclayton** [comment]
Headless is weird because you can't change it to non headless (or not).  So
expose is still the easiest way to create a service for a known port.

We can probably support a port argument on new-app

On Jul 20, 2015, at 9:03 PM, Cesar Wong <notifications@github.com> wrote:

@csrwng <https://github.com/csrwng> was the a reason to only include the
first container port in the service?

Sorry @liggitt <https://github.com/liggitt> - just getting to your comment.
Short answer: because @smarterclayton <https://github.com/smarterclayton>
:-)
Longer answer: At some point services could only point to a single port. To
expose every port we would have had to create multiple services which
likely would have included ports that you didn't want to expose, plus we
had 'oc expose' if you really wanted to expose a port.

@csrwng <https://github.com/csrwng> @liggitt <https://github.com/liggitt>
Can we add this in now?

So headless services exist now, just not sure that we'd want to generate
one here when we can't detect a port. If we do decide to generate them, we
should do the same in new-app. @smarterclayton
<https://github.com/smarterclayton> ?

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/issues/3764#issuecomment-123116817>.

**Comment by spadgett** [comment]
Blocked, waiting for route fixes for services with multiple ports:

https://trello.com/c/UyLwfTY6/33-route-spec-and-support-mulitple-ports-protocols-routing

**Comment by smarterclayton** [comment]
Why are you blocked?  Let's not hold off concrete improvements for that...

**Comment by liggitt** [comment]
A route to a multi port service doesn't work

**Comment by smarterclayton** [comment]
So?  Does that block the UI?

On Jul 23, 2015, at 10:52 AM, Jordan Liggitt <notifications@github.com>
wrote:

A route to a multi port service doesn't work

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/issues/3764#issuecomment-124130709>.

**Comment by liggitt** [comment]
Since the UI generates a route, it probably shouldn't start generating a multi port service as well until the two will actually work together

**Comment by smarterclayton** [comment]
But new-app *should* generate a port - and customers will create multi
port.  Not sure why UI would block on that.  Just need to communicate that
multi port and routes works a certain way at via UI text.

On Jul 23, 2015, at 10:55 AM, Jordan Liggitt <notifications@github.com>
wrote:

Since the UI generates a route, it probably shouldn't start generating a
multi port service as well until the two will actually work together

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/issues/3764#issuecomment-124131411>.

**Comment by liggitt** [comment]
You want the UI to create a route pointing at a multi-port service we fully expect to not work yet?

**Comment by spadgett** [comment]
Related: #4603
