### ISSUE TITLE
Add 'oc alias' and let users specify their own aliases for resources 

### ISSUE THREAD

**Issue by kargakis** [openshift/origin#3765]
Forked from https://github.com/openshift/origin/issues/3740#issuecomment-122331567

cc: @liggitt @fabianofranz @smarterclayton

**Comment by kargakis** [comment]
@deads2k @chmouel @christianh814

**Comment by deads2k** [comment]
I don't disagree that this is neat, but having it be a partial substitute for a working export command isn't ideal.

Is there a specific case we can think of or is this just a "handy to have" thing?  It could end up making support more painful: "ok, in order to see what your commands are trying to do, I'll need to have your `~/.kube/config` file".

**Comment by smarterclayton** [comment]
I don't really see this being something we need right now.  Let's hold this
until we understand the problem better:

1. What is the unit of an application
2. Why are secrets and service accounts part or not part of an application
3. What other things should or should not be part of our application

Then we can come back to this.

On Fri, Jul 17, 2015 at 2:13 PM, David Eads <notifications@github.com>
wrote:

> I don't disagree that this is neat, but having it be a partial substitute
> for a working export command isn't ideal.
>
> Is there a specific case we can think of or is this just a "handy to have"
> thing? It could end up making support more painful: "ok, in order to see
> what your commands are trying to do, I'll need to have your ~/.kube/config
> file".
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openshift/origin/issues/3765#issuecomment-122362522>.
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by chmouel** [comment]
The current discussion is about having `oc alias`  being able to alias `all` to whatever resources the user want?

I am not sure if I like it too much either.

- What about instead to have an option to 'concatenate' multiple resources with get, I mean like this : 
 
        oc get all,secret,whatever -o json
 
to produce the whole template with secret and whatever

- Another idea would be to have oc aliases in the sense the same way that we have git aliases so user could have alias : 

<pre>
[alias]
export-all-json=get all,secret,whatever-o json
</pre>

or even things like this : 

<pre>
[alias]
check_uptime=exec $1 -i -- /usr/bin/uptime
</pre>

(this is probably two different user stories)

**Comment by kargakis** [comment]
@chmouel `oc alias` is not just about `all` but for **any** group of resources that makes sense being under an alias.

```sh
$ oc alias chain=buildConfigs,imageStreams
# deletes all build configurations and image streams in the current namespace
$ oc delete chain --all 
# adds secrets to all alias
$ oc alias all=all,secrets
# removes all alias (?)
$ oc alias all- 
# displays a list of aliases
$ oc alias
```

@smarterclayton if we end up realizing all those questions then we might as well skip the command and provide any more alias that would make sense. By having this around, we may identify needs faster, no?

**Comment by smarterclayton** [comment]
If you want to create aliases, you already have a tool for that: Bash.  We
don't need to complicate our tool that way, since I don't know why two
users would need two different aliases set for the same name.  An admin
user and dev user might have different meanings for all, but I also doubt
that.

On Jul 19, 2015, at 9:21 AM, Michail Kargakis <notifications@github.com>
wrote:

@chmouel <https://github.com/chmouel> oc alias is not just about all but
for *any* group of resources that makes sense being under an alias.

$ oc alias chain=buildConfigs,imageStreams# deletes all build
configurations and image streams in the current namespace
$ oc delete chain --all # adds secrets to all alias
$ oc alias all=all,secrets# removes all alias (?)
$ oc alias all- # displays a list of aliases
$ oc alias

@smarterclayton <https://github.com/smarterclayton> if we end up realizing
all those questions then we might as well skip the command and provide any
more alias that would make sense. By having this around, we may identify
needs faster, no?

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/issues/3765#issuecomment-122660659>.

**Comment by smarterclayton** [comment]
Not a short term thing, we can reopen this if a need arises

**Comment by kargakis** [comment]
ps. https://github.com/kubernetes/kubernetes/issues/18023
