### ISSUE TITLE
Improve error message, SCC restricted

### ISSUE THREAD

**Issue by roldancer** [openshift/origin#3797]
If I try to create a pod using the official tomcat image, as a normal user it will not be possible because scc restricted has a special security constraint, where root user is not permitted.

```
$ oc create -f /tmp/tomcat-pod.json
Error from server: Pod "tomcat-openshift" is forbidden: no providers available to validate pod request
```

This error message is not clear enough, I think error message should describe that SCC xxxx (restricted) has no permissions to instantiate a pod with root user or something similar.

Thanks,

**Comment by juliosaraiva** [comment]
I have this problem too


My log say this 

Oct 09 15:54:04 origin.pub.domain.com docker[37942]: I1009 18:54:04.919140       1 sti.go:133] Admit for root user returned error: pods "cakephp-mysql-example-2-build" is forbidden: no providers available to validate pod request

**Comment by stevekuznetsov** [comment]
We could try to link to the [official documentation](https://docs.openshift.org/latest/admin_guide/manage_scc.html#enable-dockerhub-images-that-require-root) on this as I feel it explains things pretty well.

**Comment by php-coder** [comment]
> This error message is not clear enough,

Indeed.

> I think error message should describe that SCC xxxx (restricted) has no permissions to instantiate a pod with root user or something similar.

The error message is technically correct and tell us that there are no SCCs that can admit the pod. Here is an explanation how admission controller works: https://docs.openshift.org/latest/architecture/additional_concepts/authorization.html#admission In the current situation, we have no SCCs after step 1 and that's why pod creation has been failed.
