### ISSUE TITLE
provide upgrade path for admin and edit roles

### ISSUE THREAD

**Issue by deads2k** [openshift/origin#3802]
The `pods/exec` change required changes to the admin and edit roles.  Existing cluster-admins need to have a reasonable way to update those roles if they so choose.

I'm inclined to create a flag for `create-bootstrap-policy-file` that diffs the current etcd cluster-roles against the default cluster-roles and outputs the non-equivalent cluster-roles as a `List` to stdout.

@smarterclayton P1?  How do you like the approach?

**Comment by smarterclayton** [comment]
Can you see where upstream is on "reconcile"?  Because that's the pattern
we're talking about here "generate new, compare to old, apply to old".  If
upstream is close on reconcile key tech I'd want us to be able to use that.

On Jul 21, 2015, at 10:57 AM, David Eads <notifications@github.com> wrote:

The pods/exec change required changes to the admin and edit roles. Existing
cluster-admins need to have a reasonable way to update those roles if they
so choose.

I'm inclined to create a flag for create-bootstrap-policy-file that diffs
the current etcd cluster-roles against the default cluster-roles and
outputs the non-equivalent cluster-roles as a List to stdout.

@smarterclayton <https://github.com/smarterclayton> P1? How do you like the
approach?

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/issues/3802>.

**Comment by deads2k** [comment]
@smarterclayton I'm looking at https://github.com/GoogleCloudPlatform/kubernetes/issues/1702 .  It looks like the decision is moving towards creating patches using the diff maker you used in `oc edit`.  I'll see if that works cleanly for policy rules, but as I recall there were issues making json patches for string arrays.

**Comment by smarterclayton** [comment]
As long as whatever we do fits within the long range im ok with a short
term (where we have a simple/stupid reconcile), just want to have a way to
get to that (even -o yaml on the create command would probably be ok).

On Jul 21, 2015, at 11:22 AM, David Eads <notifications@github.com> wrote:

@smarterclayton <https://github.com/smarterclayton> I'm looking at
GoogleCloudPlatform/kubernetes#1702
<https://github.com/GoogleCloudPlatform/kubernetes/issues/1702> . It looks
like the decision is moving towards creating patches using the diff maker
you used in oc edit. I'll see if that works cleanly for policy rules, but
as I recall there were issues making json patches for string arrays.

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/issues/3802#issuecomment-123368720>.

**Comment by liggitt** [comment]
iirc, patch could add things to string arrays but not remove them

**Comment by deads2k** [comment]
> iirc, patch could add things to string arrays but not remove them

`PolicyRules` are a slice without a merge key, which makes creating patches for them untennable.  I'll create the replacement `List` and we can revisit this when we start working on a v2 api schema.  We might be able to do better by naming rules and merging on them, but truth be told I think the complete replacement would be cleaner overall.  I'd rather avoid an ugly serialization just to make patch easier.
