### ISSUE TITLE
new-app from local file system

### ISSUE THREAD

**Issue by bsideup** [openshift/origin#3824]
Hello

OpenShift usually being compared to Cloud Foundry. One nice thing CF which is not presented in OS is "pushing" apps from local file system. Currently it's impossible to create new app in OS without using Git repository, which increases usage complexity. 

Would be cool if following workflow will be supported:

```bash
$ tree
.
|-- app.jar
`-- Dockerfile
```

STIs could also be helpful here (if there is no Dockerfile in folder)

remote Git repository looks redundant here. Plus, our build process is really complicated and requires dependency resolution from different private Maven repositories, which means that we just can't build our Java app on OpenShift. We already do this on Jenkins, we just need to "push" this final jar file to OpenShift.

Thanks

**Comment by bparees** [comment]
not clear which of two scenarios you want:

1) build the image locally, run it on openshift (you can do this today)
2) given source on a local filesystem, perform a build+deploy in openshift  - you can't do this today because we don't have an internal component that can hold your source code and hand it off for building.  Adding an internal git server that can do this is on our roadmap.

**Comment by danmcp** [comment]
@bsideup Bump

**Comment by mfojtik** [comment]
@bparees isn't think the 'binary' source support @smarterclayton is working on?

**Comment by smarterclayton** [comment]
This is binary source support.

**Comment by smarterclayton** [comment]
Binary source support is in and documented
