### ISSUE TITLE
Command line output for builds

### ISSUE THREAD

**Issue by JimTyrrell** [openshift/origin#3847]
Looking at the output of the "oc get builds" command the words under STATUS are confusing in one case.

The word "running" is really hard to decipher its context.  I know you ran a build command, but without some other outside context it is really hard especially with only one build running to know what it means.  For many developers people see that as the "service" should be up and running, not that the build is running.  I know that is a little bit of a nit, possible suggestions include "building", "building...", "in progress", "progressing", "running build".  In a quick pool in a SA room taking training, "building..." and "running build" are the two that bubbled to the surface.  Other clarifying terms could also be successful.

**Comment by soltysh** [comment]
I don't agree with that. You're talking that "running build" is fine, so let's think about it more. You're in the context of a build `oc get builds` and the actual information returned from that command is `Running` which means the build is running. I don't see any point in renaming that particular status to anything other than it is right now. It's simple yet consistent, imho.

**Comment by thoraxe** [comment]
The difficulty is that the word "Running" is used in several places. For example, pod status and build status.

What does it mean for the build to be "running"? Does that mean the build container is started? Does that mean the build process is actually happening? Does that mean the Docker push is going on? Does that mean we are pulling code?

While the term is technically correct (if the build is "running" it means the pod is up and the processes inside are happening), the "psychology of the user" (@jimtyrrell words) makes it slightly hard to decipher what's really going on during the build process without actually looking at the build logs.

I understand that making more specificity in the status (eg: pulling, pushing, etc) is difficult because it would require the build(assemble) process to call the API to update, it would certainly provide more feedback to the user.

**Comment by soltysh** [comment]
The build statuses match the status of a Pod running a build, that means:
* Pod - Pending -> Build - Pending - which means the builder image is being downloaded (which should rarely happen)
* Pod - Running -> Build - Running - which means the actual builder is executing the build
etc.
Unfortunately for now it might be hard to specify explicit build phases in the status, because we'd have to allow the actual builder image to do that, which we don't for now. 
Additionally, as you've mentioned this matches the terminology used in other places (eg. Deployments), where we also could have more detailed status but we choose to stick with Pod phases (more or less).

**Comment by smarterclayton** [comment]
The things @thoraxe is describing are mostly what we would call sub-status or "conditions".  Additional human readable info about what exactly the build is doing at this time.  @soltysh is correct that we chose deliberately to use phases that corresponded with pods for consistency, and those will also be consistent with Jobs and Deployments (or should be).

Additional info about the sub-status of the build should be provided in a conditions field (we don't add additional phases, we add conditions so that future clients aren't broken when a new phase is added).

If we had sub-status info:

```
NAME      PHASE     STATUS
build-1   Running   Pulling image
build-2   Pending   Waiting for capacity to run build
```

would that resolve the major concern here?

**Comment by thoraxe** [comment]
Yeah that looks great!

**Comment by JimTyrrell** [comment]
That seems like it would handle the concern above, does this type of "update" to grammar need to move to other command line tools?

**Comment by smarterclayton** [comment]
Generally pods already display this, but neither deployments nor builds
roll this data up today.  It's something being tracked in a few different
issues - I'm not sure how fast we'll get there.

On Fri, Aug 28, 2015 at 1:07 PM, JimTyrrell <notifications@github.com>
wrote:

> That seems like it would handle the concern above, does this type of
> "update" to grammar need to move to other command line tools?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openshift/origin/issues/3847#issuecomment-135817626>.
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by soltysh** [comment]
Actually, the phases will be gradually [removed](https://github.com/kubernetes/kubernetes/issues/7856) upstream, which means our phases are going to be deprecated as well (but it'll take a while till we get there). There are no phases in [Jobs](https://github.com/kubernetes/kubernetes/blob/master/docs/proposals/job.md) already and API seems to be moving towards [conditions](https://github.com/kubernetes/kubernetes/blob/master/docs/devel/api-conventions.md#typical-status-properties) and again looking at how Pods or Jobs conditions are specified you won't find there too verbose information about the status, we'll have to provide that on OpenShift side.

**Comment by bparees** [comment]
closing this in deference to: https://bugzilla.redhat.com/show_bug.cgi?id=1262883
