### ISSUE TITLE
host in route specification should follow rfc2616, not DNS 952

### ISSUE THREAD

**Issue by nstrug** [openshift/origin#3864]
When specifying a route, we are able to match on the Host http header. This is provided for in haproxy.config with the rule:

use_backend be_edge_http_%[hdr(host),map(/var/lib/haproxy/conf/os_edge_http_be.map)] if TRUE

However, if we specify a route such as:

"spec": {
  "host": "foo.example.com:8881",
  "to" : {
    "name": "example-service-8881"
  }

this fails, with the error:
host: invalid value 'foo.example.com:8881': host must conform to DNS 952 subdomain conventions.

In my opinion this is incorrect. 'foo.example.com:8881' is a valid http Header, conforming to the relevant RFC2616, and we should be able to match on it. With the current restriction in place, we are unable to perform host-based routing on non-standard ports.

**Comment by nstrug** [comment]
Further to this:

pkg/route/api/v1/types.go:32 states:

// Host is an alias/DNS that points to the service. Optional
	// Can be host or host:port
	// host and port are combined to follow the net/url URL struct
	Host string `json:"host" description:"optional: alias/dns that points to the service, can be host or host:port"`

However, the actual implementation of the validation at /pkg/route/api/validation/validation.go:24 is:

if len(route.Host) > 0 {
		if !util.IsDNS1123Subdomain(route.Host) {
			result = append(result, fielderrors.NewFieldInvalid("host", route.Host, "host must conform to DNS 952 subdomain conventions"))
		}
	}

There is a clear mismatch between these.

**Comment by pweil-** [comment]
@smarterclayton - the use case here is being able to have a frontend that binds to many ports and use rules based on the host/port definition.  That said, when custom frontends are allowed to be created I'm not sure that port based rule mappings are strictly necessary.  In that case there can be a 1:1 mapping between custom frontend and the backend it is trying to reach.

/cc @ramr @rajatchopra

**Comment by smarterclayton** [comment]
I'm not sure we should be specifying ports in the Host.  Why aren't we listing the front end ports we want exposed, and force users to describe when they want an explicit port?  We need mappings anyway, is this just one more type of mapping?

**Comment by smarterclayton** [comment]
I don't really want Host to be a header match rule - I want it to be structured.  A DNS router can use Host without port.

**Comment by pweil-** [comment]
> I'm not sure we should be specifying ports in the Host. Why aren't we listing the front end ports we want exposed, and force users to describe when they want an explicit port? We need mappings anyway, is this just one more type of mapping?

I think we're on the same page.  If you want to expose a custom frontend, in the template we'd make a new frontend binding to the requested port and use the route to determine which backend to go to.  Unless we want to allow you to make a dynamic frontend like we do for `:80` and `:443` we don't need extra mapping configs.  I don't think we are talking about exposing dynamic custom frontends.



> I don't really want Host to be a header match rule - I want it to be structured

Not clear about this one, unless you're excluding the dynamic frontend use case from this statement in which case my above comment is inline with your thoughts.

**Comment by nstrug** [comment]
Host already is a header match rule in the haproxy config that we ship so it seems reasonable to be able to use it as such.

**Comment by smarterclayton** [comment]
On Jul 23, 2015, at 9:29 AM, Paul Weil <notifications@github.com> wrote:

I'm not sure we should be specifying ports in the Host. Why aren't we
listing the front end ports we want exposed, and force users to describe
when they want an explicit port? We need mappings anyway, is this just one
more type of mapping?

I think we're on the same page. If you want to expose a custom frontend, in
the template we'd make a new frontend binding to the requested port and use
the route to determine which backend to go to. Unless we want to allow you
to make a dynamic frontend like we do for :80 and :443 we don't need extra
mapping configs. I don't think we are talking about exposing dynamic custom
frontends.

I don't really want Host to be a header match rule - I want it to be
structured

Not clear about this one, unless you're excluding the dynamic frontend use
case from this statement in which case my above comment is inline with your
thoughts.



Ok


—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/issues/3864#issuecomment-124098820>.

**Comment by smarterclayton** [comment]
That's not the intent.  That's just an accident.

On Jul 23, 2015, at 9:35 AM, Nick Strugnell <notifications@github.com>
wrote:

Host already is a header match rule in the haproxy config that we ship so
it seems reasonable to be able to use it as such.

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/issues/3864#issuecomment-124101829>.

**Comment by nstrug** [comment]
Additionally, the comment on line 32 specifically states that we should be able to use host:port - it's just the validator that is currently stopping us doing this. I don't really mind how we do it, just that we are able to map arbitrary ports on the front to backends for clients that don't support SNI.

**Comment by pweil-** [comment]
https://github.com/openshift/origin/pull/3866 submitted so that comments accurately reflect current validations.

**Comment by smarterclayton** [comment]
We have to be careful if we allow arbitrary ports in routes, because the
router already has to be listening on that port.  I don't see an easy
solution that allows third parties to registers its own ports on routes
without defeating the purpose of routes.  Node Ports on services is
supposed to cover that, or specific route configurations.

On Jul 23, 2015, at 9:45 AM, Paul Weil <notifications@github.com> wrote:

#3866 <https://github.com/openshift/origin/pull/3866> submitted so that
comments accurately reflect current validations.

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/issues/3864#issuecomment-124107945>.

**Comment by pweil-** [comment]
> We have to be careful if we allow arbitrary ports in routes, because the
> router already has to be listening on that port.  I don't see an easy
> solution that allows third parties to registers its own ports on routes
> without defeating the purpose of routes.  Node Ports on services is
> supposed to cover that, or specific route configurations.

Yes, agreed.  I think we would not allow the port in the host config and require someone to ask for a route with some sort of spec indicator that "I want to expose port X as a custom frontend for this route".  That route would then have to be allocated and accepted by a router that can support the configuration or be updated in the v1 status field of failures.  Sounds like it could also support the "use the node port service as my custom frontend configuration" use case.

**Comment by smarterclayton** [comment]
And the "run a loadbalancer" service, which the routing layer should
integrate with.  There needs to be a card for that (user asks for
"LoadBalanced" service, an IP/port combo gets allocated, and an HAProxy
opens a port).  That's a concrete use case that probably is the ideal
solution for this use case.

On Jul 23, 2015, at 10:23 AM, Paul Weil <notifications@github.com> wrote:

We have to be careful if we allow arbitrary ports in routes, because the
router already has to be listening on that port. I don't see an easy
solution that allows third parties to registers its own ports on routes
without defeating the purpose of routes. Node Ports on services is
supposed to cover that, or specific route configurations.

Yes, agreed. I think we would not allow the port in the host config and
require someone to ask for a route with some sort of spec indicator that "I
want to expose port X as a custom frontend for this route". That route
would then have to be allocated and accepted by a router that can support
the configuration or be updated in the v1 status field of failures. Sounds
like it could also support the "use the node port service as my custom
frontend configuration" use case.

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/issues/3864#issuecomment-124122818>.

**Comment by nstrug** [comment]
OK, well in any case I've fixed route/api/validation/validation.go so that it accepts hosts as host:port. This now generates a correct os_edge_http_be.map of the form:

foo.example.com:8889   example-service-8889
foo.example.com:8890   example-service-8890

etc.

We will have to use this at the client until something better comes along.

https://github.com/nstrug/origin/blob/master/pkg/route/api/validation/validation.go

**Comment by smarterclayton** [comment]
To be clear, we were saying that we do not want that.  So I don't know why
we would do that.

On Jul 23, 2015, at 10:53 AM, Nick Strugnell <notifications@github.com>
wrote:

OK, well in any case I've fixed route/api/validation/validation.go so that
it accepts hosts as host:port. This now generates a correct
os_edge_http_be.map of the form:

foo.example.com:8889 example-service-8889
foo.example.com:8890 example-service-8890

etc.

We will have to use this at the client until something better comes along.

https://github.com/nstrug/origin/blob/master/pkg/route/api/validation/validation.go

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/issues/3864#issuecomment-124131015>.

**Comment by nstrug** [comment]
Interim measure until something better comes along. I've got to go off site in 30 minutes and need to leave customer with something that works. Customer aware that it is unsupported.

**Comment by smarterclayton** [comment]
Paul, probably gets into "if we were using the API objects, Nick could use
an annotation for this info" - another argument on that tech debt story

On Jul 23, 2015, at 10:56 AM, Nick Strugnell <notifications@github.com>
wrote:

Interim measure until something better comes along. I've got to go off site
in 30 minutes and need to leave customer with something that works.
Customer aware that it is unsupported.

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/issues/3864#issuecomment-124131926>.

**Comment by nstrug** [comment]
I think in an ideal situation, the ports array in the Service object (which already contains frontend portnumbers) would trigger the configuration of custom frontends without having to create a custom router. Is this what you are aiming at?

**Comment by smarterclayton** [comment]
There is already a feature on services to do that for AWS and GCE.  You
can't set up ssl termination that way.

On Jul 23, 2015, at 11:09 AM, Nick Strugnell <notifications@github.com>
wrote:

I think in an ideal situation, the ports array in the Service object (which
already contains frontend portnumbers) would trigger the configuration of
custom frontends without having to create a custom router. Is this what you
are aiming at?

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/issues/3864#issuecomment-124135158>.

**Comment by pweil-** [comment]
> Paul, probably gets into "if we were using the API objects, Nick could use
> an annotation for this info" - another argument on that tech debt story

Most definitely.  Added this scenario as a use case to the refactoring card.  Having an api object with annotations opens the door to being able to implement any feature you want with a customized plugin template.
