### ISSUE TITLE
new-app unit test takes 8s

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#3886]
Should be mocked instead of calling out remotely (if that's why it is slow)

**Comment by bparees** [comment]
@jupierce based on age, this may not even still be an issue, but please take a look.

**Comment by kargakis** [comment]
There are a couple of slow unit tests that need more eyes: https://github.com/openshift/origin/issues/6801

**Comment by bparees** [comment]
@jupierce here are the devex related tests that should be investigated:
ok      github.com/openshift/origin/pkg/build/builder   6.770s  coverage: 44.6% of statements
ok      github.com/openshift/origin/pkg/generate/app/cmd    39.368s coverage: 62.4% of statements

and anything else under "pkg/generate" that takes a long time, since that's the new-app package.

**Comment by jupierce** [comment]
It looks like these have improved since this issue was opened. From a recent run (https://ci.openshift.redhat.com/jenkins/job/origin_coverage/307/consoleFull)
ok  	github.com/openshift/origin/pkg/build/builder	**3.991s**	coverage: 46.3% of statements
...
ok  	github.com/openshift/origin/pkg/generate/app	**1.111s**	coverage: 36.2% of statements
ok  	github.com/openshift/origin/pkg/generate/app/cmd	**1.121s**	coverage: 39.1% of statements
ok  	github.com/openshift/origin/pkg/generate/dockerfile	**1.009s**	coverage: 56.5% of statements
ok  	github.com/openshift/origin/pkg/generate/git	**1.034s**	coverage: 32.3% of statements

**Comment by bparees** [comment]
good enough for me, thanks @jupierce
