### ISSUE TITLE
Run go vet with other verify scripts

### ISSUE THREAD

**Issue by deads2k** [openshift/origin#3892]
We should run `go vet` (http://godoc.org/golang.org/x/tools/cmd/vet) against our packages to catch potential issues.

**Comment by deads2k** [comment]
@stevekuznetsov ptal

**Comment by stevekuznetsov** [comment]
`go vet` supports quite a lot of options:
```
-printf
-methods
-structtags
-comosites
-asmdecl 
-assign
-atomic
-bool
-buildtags
-copylocks
-nilfunc
-rangeloops
-unreachable
-shadow=false
-unusedresult
-shift
```
Running all of them returns only [126 errors](http://pastebin.test.redhat.com/304555) but I can still see why all of these options would not be necessary or useful.
@smarterclayton @liggitt @deads2k @derekwaynecarr vote on which to keep or which to disregard?

**Comment by stevekuznetsov** [comment]
For instance, our use of tags like `!no-etcd` makes `-buildtags` unhappy, but I think we'd rather disregard `go vet` than change our tags.

**Comment by liggitt** [comment]
just looking at the descriptions, I'd care most about these:
```
-assign
-atomic
-bool
-copylocks
-nilfunc
-rangeloops
-shadow
-unreachable
-unsafeptr
```

**Comment by stevekuznetsov** [comment]
Also, given that `go vet` can and will have false positives, and that it will not find every error in a file but give up after some initial amount how do we implement this test? If we try to whitelist errors we don't care about or somehow detect false-positives, we could be masking actual errors because the tool gives up at that point.

**Comment by smarterclayton** [comment]
Whitelist the ones we care about (only include what we want to enforce).
Try to determine if they have edge cases.  Otherwise someone should just
periodically run go vet like Michailis has been doing.

On Aug 11, 2015, at 3:36 PM, Steve Kuznetsov <notifications@github.com>
wrote:

Also, given that go vet can and will have false positives, and that it will
not find every error in a file but give up after some initial amount how do
we implement this test? If we try to whitelist errors we don't care about
or somehow detect false-positives, we could be masking actual errors
because the tool gives up at that point.

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/issues/3892#issuecomment-130034737>.

**Comment by stevekuznetsov** [comment]
`shadow` looks really nice, and as I'm going through these has caught a lot of shadowed errors, but I don't think it really ever impacts the code and about 30% of everything reported is a false positive.

**Comment by stevekuznetsov** [comment]
I do think this can't really be automated.

**Comment by stevekuznetsov** [comment]
`unreachable` has not had any false positives so far

**Comment by liggitt** [comment]
> I don't think it really ever impacts the code

in my experience, unintentional shadowing has been the number one source of "scratch your head for an hour" bugs which static analysis could have caught

**Comment by stevekuznetsov** [comment]
Sure, but if we trigger a PR test fail because something comes back from `shadow`, how would I fix that case I mentioned above? The vast majority of returns from `shadow` are that, so I don't think we should include it in the automated test. However, the unreachable code test seems to be great - we should include it.

**Comment by stevekuznetsov** [comment]
Output with your whitelist @liggitt :
```
SUCCESS: go vet -assign had no errors
SUCCESS: go vet -atomic had no errors
SUCCESS: go vet -bool had no errors
SUCCESS: go vet -copylocks had no errors
SUCCESS: go vet -nilfunc had no errors
SUCCESS: go vet -rangeloops had no errors
SUCCESS: go vet -unreachable had no errors
FAILURE: go vet -shadow had errors: 
./test/integration/dns_test.go:33: declaration of err shadows declaration at ./test/integration/dns_test.go:19: 
./pkg/api/compatibility_test.go:188: declaration of ok shadows declaration at ./pkg/api/compatibility_test.go:181: 
./pkg/generate/dockerfile/finder.go:59: declaration of err shadows declaration at ./pkg/generate/dockerfile/finder.go:48: 
./pkg/security/controller/repair.go:78: declaration of err shadows declaration at ./pkg/security/controller/repair.go:61: 
./pkg/template/template.go:44: declaration of obj shadows declaration at ./pkg/template/template.go:42: 
./pkg/cmd/experimental/buildchain/buildchain.go:107: declaration of err shadows declaration at ./pkg/cmd/experimental/buildchain/buildchain.go:91: 
./pkg/cmd/cli/secrets/new.go:198: declaration of err shadows declaration at ./pkg/cmd/cli/secrets/new.go:179: 
./pkg/cmd/cli/cmd/startbuild.go:168: declaration of err shadows declaration at ./pkg/cmd/cli/cmd/startbuild.go:158: 
./pkg/cmd/cli/cmd/export.go:138: declaration of err shadows declaration at ./pkg/cmd/cli/cmd/export.go:89: 
./pkg/cmd/cli/cmd/export.go:151: declaration of err shadows declaration at ./pkg/cmd/cli/cmd/export.go:89: 
./pkg/cmd/cli/cmd/env.go:234: declaration of err shadows declaration at ./pkg/cmd/cli/cmd/env.go:196: 
./pkg/cmd/cli/cmd/edit.go:220: declaration of err shadows declaration at ./pkg/cmd/cli/cmd/edit.go:134: 
./pkg/cmd/cli/cmd/deploy.go:172: declaration of err shadows declaration at ./pkg/cmd/cli/cmd/deploy.go:162: 
./pkg/cmd/cli/cmd/deploy.go:187: declaration of err shadows declaration at ./pkg/cmd/cli/cmd/deploy.go:162: 
./pkg/cmd/cli/cmd/deploy.go:217: declaration of err shadows declaration at ./pkg/cmd/cli/cmd/deploy.go:162: 
./pkg/cmd/cli/cmd/cancelbuild.go:84: declaration of err shadows declaration at ./pkg/cmd/cli/cmd/cancelbuild.go:59: 
./pkg/cmd/cli/cmd/process.go:123: declaration of err shadows declaration at ./pkg/cmd/cli/cmd/process.go:97: 
./pkg/cmd/cli/cmd/process.go:171: declaration of err shadows declaration at ./pkg/cmd/cli/cmd/process.go:97: 
./pkg/cmd/cli/cmd/process.go:190: declaration of err shadows declaration at ./pkg/cmd/cli/cmd/process.go:97: 
./pkg/cmd/admin/policy/reconcile_clusterroles.go:113: declaration of err shadows declaration at ./pkg/cmd/admin/policy/reconcile_clusterroles.go:107: 
./pkg/cmd/admin/router/router.go:194: declaration of err shadows declaration at ./pkg/cmd/admin/router/router.go:169: 
./pkg/cmd/admin/router/router.go:206: declaration of err shadows declaration at ./pkg/cmd/admin/router/router.go:169: 
./pkg/cmd/admin/registry/registry.go:145: declaration of err shadows declaration at ./pkg/cmd/admin/registry/registry.go:136: 
./pkg/cmd/admin/registry/registry.go:157: declaration of err shadows declaration at ./pkg/cmd/admin/registry/registry.go:136: 
./pkg/cmd/server/kubernetes/node_test.go:66: internal error: no range for path
./pkg/cmd/server/start/master_args.go:449: declaration of err shadows declaration at ./pkg/cmd/server/start/master_args.go:448: 
./pkg/cmd/server/start/start_master.go:351: declaration of err shadows declaration at ./pkg/cmd/server/start/start_master.go:333: 
./pkg/cmd/server/start/start_master.go:360: declaration of err shadows declaration at ./pkg/cmd/server/start/start_master.go:333: 
./pkg/serviceaccounts/controllers/docker_registry_service.go:186: declaration of err shadows declaration at ./pkg/serviceaccounts/controllers/docker_registry_service.go:156: 
./pkg/user/registry/useridentitymapping/rest.go:143: declaration of err shadows declaration at ./pkg/user/registry/useridentitymapping/rest.go:123: 
./pkg/dockerregistry/client_test.go:20: declaration of err shadows declaration at ./pkg/dockerregistry/client_test.go:15: 
./pkg/dockerregistry/client.go:359: declaration of err shadows declaration at ./pkg/dockerregistry/client.go:340: 
./pkg/image/registry/imagestream/strategy.go:180: declaration of err shadows declaration at ./pkg/image/registry/imagestream/strategy.go:168: 
./pkg/auth/authenticator/password/ldappassword/ldap.go:207: declaration of err shadows declaration at ./pkg/auth/authenticator/password/ldappassword/ldap.go:205: 
./pkg/authorization/authorizer/authorizer.go:40: declaration of err shadows declaration at ./pkg/authorization/authorizer/authorizer.go:30: 
./pkg/client/cache/eventqueue.go:126: declaration of newEventType shadows declaration at ./pkg/client/cache/eventqueue.go:91: 
SUCCESS: go vet -unsafeptr had no errors
```

**Comment by liggitt** [comment]
all the shadows errors I saw look correct

**Comment by stevekuznetsov** [comment]
Looking at the other outputs today - the `printf` results I just went through and they were all legitimate problems. I'm all for keeping them in.

The output of the `buildtags` test is also valid - why do we have tags `no-docker` and `!no-docker`? That's pretty ridiculous if you look at it objectively, we should have `docker` and `!docker`.

**Comment by smarterclayton** [comment]
Probably to get defaulting to work right from the CLI, so that you didn't
always have to say "-t etcd" to run the integration tests.  It's less of an
issue now.

On Aug 12, 2015, at 9:26 AM, Steve Kuznetsov <notifications@github.com>
wrote:

Looking at the other outputs today - the printf results I just went through
and they were all legitimate problems. I'm all for keeping them in.

The output of the buildtags test is also valid - why do we have tags
no-docker and !no-docker? That's pretty ridiculous if you look at it
objectively, we should have docker and !docker.

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/issues/3892#issuecomment-130300620>.

**Comment by liggitt** [comment]
> That's pretty ridiculous if you look at it objectively, we should have !docker and docker, respectively.

That is !not-ridiculous

**Comment by stevekuznetsov** [comment]
@liggitt One common error I see with shadow: https://github.com/golang/tools/blob/master/cmd/vet/shadow.go#L77

Changing it is inconsequential, though, so why not.

**Comment by liggitt** [comment]
isn't it shadowing the closure's access to the outer variable, though?

**Comment by stevekuznetsov** [comment]
Added here, https://github.com/openshift/origin/pull/4153 @deads2k please close this.
