### ISSUE TITLE
Misleading error message creating project when $KUBECONFIG is read-only

### ISSUE THREAD

**Issue by spadgett** [openshift/origin#3918]
When `$KUBECONFIG` is read-only, you see an error message when creating a project.

```
[vagrant@openshiftdev ~]$ ls -l $KUBECONFIG
-rw-r--r--. 1 root root 7284 Jul 27 12:59 /home/vagrant/openshift.local.config/master/admin.kubeconfig
[vagrant@openshiftdev ~]$ oc new-project test
error: open /home/vagrant/openshift.local.config/master/admin.kubeconfig: permission denied
```

The project is created successfully, however, so it's misleading. I suspect we're simply trying to set it as the current project, which fails.

**Comment by jawnsy** [comment]
I must've followed the [same steps as you](https://docs.openshift.org/latest/getting_started/administrators.html#downloading-the-binary). Found this as I was seeing the same error.

For some reason, the code is trying to truncate the file according to `strace`:

```
open("/home/vagrant/openshift/openshift.local.config/master/admin.kubeconfig",
O_WRONLY|O_CREAT|O_TRUNC|O_CLOEXEC, 0600) = -1 EACCES (Permission denied)
```

Thanks to your comment about `$KUBECONFIG` being read-only, I fixed this by setting permissions to `rw-rw-rw-` (666):

`sudo chmod 666 admin.kubeconfig`

Now the error went away. So in case other people finding this didn't quite clue in to the workaround, setting permissions so that the file is writable or I guess changing ownership are options. Sounds like even just ignoring the message is harmless, too.

**Comment by stevekuznetsov** [comment]
@juanvallejo didn't you fix this?

**Comment by juanvallejo** [comment]
@stevekuznetsov No, I believe I only clarified a permissions error message for a non-writable kubeconfig https://github.com/openshift/origin/pull/9968

**Comment by nikhilbandi** [comment]
Looks like this issue still exists. Encountered it right now. It gives the permission denied error but the new project is created. 
However, when I did a chmod for the admin.kubeconfig file and then create another project, it got created successfully.
