### ISSUE TITLE
A build was created - you can run `oc start-build keynote2015-hexboard` to start it.

### ISSUE THREAD

**Issue by burrsutter** [openshift/origin#3931]
This is the response from the new-app command
./oc new-app openshift/nodejs-010-centos7~http://github.com/bleathem/keynote2015-hexboard

But in this case, the build was created and started automatically, there is no need to request another "start-build".

**Comment by bparees** [comment]
we should probably just change this text to say "a build configuration was created, you can run...."

that gives less implication about whether one will run automatically or not (knowing whether one will run automatically or not is a harder question since it depends on the contents of the buildconfig)

though if buildconfigs created by new-app will always have the new configchangetrigger then we can just change this to "a build has been started for you"

@csrwng

**Comment by bparees** [comment]
text now says:
Build "ruby-ex" created and started - you can run `oc status` to check the progress.
