### ISSUE TITLE
Provide a way to categorize or group  common parameters in a template

### ISSUE THREAD

**Issue by jcantrill** [openshift/origin#3973]
@maxandersen requested a way for tooling to be able to group parameters that are common.  This would allow us to display parameters in a hierarchical structure instead of a long list.  Example, one might want to group database items together (e.g. username, password, port) or web-server specific parameters.  Additionally, categories could support a description that would be provided by the template author for display by tooling.

There are probably ways to accomplish the same end-goal utilizing annotations, but they seem hacky at  best.

**Comment by jcantrill** [comment]
cc @smarterclayton @liggitt  @jwforres

**Comment by jcantrill** [comment]
@bparees

**Comment by jcantrill** [comment]
cc @fbricon @knrc

**Comment by smarterclayton** [comment]
This seems a lot like FIELDSET and form elements.  Field sets have titles - would these have titles?  Are field sets required or optional?

**Comment by liggitt** [comment]
Yeah, it's exactly like that, only we're talking about grouping based on attributes. Seems like the group must have an id (used as the attribute value in the parameter), optional name and description. A name and description imply the existence of a group stanza.

What order are groups presented in? First-use order? Alphabetical?

What happens when you have groups disjoint from parameter order? Do the parameters get reordered in the presentation to organize themselves by groups?

Where do ungrouped parameters go? At the beginning? end? interspersed?

**Comment by rcernich** [comment]
Take one of the xPaas EAP DB templates as an example: there are generic parameters (e.g. APPLICATION_NAME, GIT_URI), there are SSL specific parameters (e.g. EAP_HTTPS_*) and there are DB specific parameters (e.g. DB_USER).  In addition to that, some of these parameters are required, others are generated and others might be be optional, but apply to advanced users.

**Comment by liggitt** [comment]
sure, I'm just wanting to more fully define the expected behavior. the HTML fieldset element contains its fields, which takes care of a lot of those edge cases. We're talking about overlaying an optional grouping construct, which we just need to think through

**Comment by jcantrill** [comment]
Ref: https://trello.com/c/HcplFhUP

**Comment by bparees** [comment]
@jcantrill assigning to you as you're driving what this api change is going to look like.

**Comment by jcantrill** [comment]
Closing in deference to https://github.com/kubernetes/kubernetes/issues/28847
