### ISSUE TITLE
Generated route hostnames can't be secured with a single wildcard certificate

### ISSUE THREAD

**Issue by liggitt** [openshift/origin#4015]
Because generated route hostnames have two variable subdomain segments (I blame myself... c.f. https://github.com/openshift/origin/pull/2165#issuecomment-100986574 and https://github.com/openshift/origin/pull/2177), no wildcard certificate can be configured in the router to secure all generated hostnames.

Ideally, we'd generate names like $route-$project.$suffix, but that allows conflicts like [foo]-[bar-baz] and [foo-bar]-[baz].

Additionally, multiple routes can specify identical hosts (non-generated) today and run into trouble when the router attempts to honor all the requested hostnames.

We probably need to move to a spec/status model where the route API object optionally requests a host, and a controller loop accepts the requested host (or allocates one if none is requested) and records the results in a route.status field.

/cc @smarterclayton @pweil- @ramr

**Comment by pweil-** [comment]
I agree with the spec/status model which is what the new api is shooting for.  We need this type of thing anyway to allow routers to accept or reject an allocated route if they can't support it in the case of sharding or some other implementation detail of the router (ie. I was given a request for a custom front end but cannot open that port for any reason).  

How contentious do you think it would be to eliminate - as an acceptable char in the project name in the short term?

**Comment by liggitt** [comment]
> How contentious do you think it would be to eliminate - as an acceptable char in the project name in the short term?

Very

**Comment by pweil-** [comment]
:cry:

**Comment by liggitt** [comment]
wow, we actually allow dots in route names themselves... ugh

**Comment by pweil-** [comment]
Linking references:

BZ for this same issue: https://bugzilla.redhat.com/show_bug.cgi?id=1249108
Discussion of route uniqueness: https://github.com/openshift/origin/pull/2606#issuecomment-106911193

**Comment by smarterclayton** [comment]
Here's a strawman proposal:

1. Switch route to have a Status field substruct slice "Routers" (or
similar) with two fields - "Name" and "Host"
2. Remove the inline defaulting of Host
3. Controller loop would (today) populate a name of "default" and a Host
that is either the provided host (if not taken already), a generated host
(if not exists), or a generated host that is incremented
4. Figure out how to report failure to acquire host name (probably on a per
router basis)

On Wed, Aug 5, 2015 at 11:34 AM, Paul Weil <notifications@github.com> wrote:

> Linking references:
>
> BZ for this same issue:
> https://bugzilla.redhat.com/show_bug.cgi?id=1249108
> Discussion of route uniqueness: #2606 (comment)
> <https://github.com/openshift/origin/pull/2606#issuecomment-106911193>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openshift/origin/issues/4015#issuecomment-128041979>.
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by smarterclayton** [comment]
We need to get a card / plan together to tackle this - has to be fixed for 3.0.2.

**Comment by ramr** [comment]
@smarterclayton  so re: the proposal we would either need some k-v storage for the routes already allocated or we have to build them up and keep 'em in memory in the controllers for handling collisions. 
Is the latter what you intended/meant?  It probably has implications with multiple controllers running as things could be processed in parallel (or did you mean just a singleton)? 

As re: the generated routes themselves, if we don't have a name provided, using 
```$name-$namespace.$<dns-suffix>``` we could support the wildcard certificates support as well (probably also need to make sure no dots (```.```) are in the prefixed name+namespace).

In case, the generated name already exists, the case is similar to @liggitt ```foo-bar-baz``` example where name/namespace has 2 of those parts and collide. The collision detection check would add a ```-<collision-fix>``` to the prefix ala ```$name-$namespace.[-<collision-fix>].$<dns-suffix>``. 

And a last question was the collision-fix part -- increment assuming you meant a numeric one 
ala  ```large-hadron-collider-42.v3.openshift.local```  - since name and namespace are unbounded strings and dns names have implications in the length - each component could be 63 octets and a max of 255 octets (well 251 if you exclude the dots + 1 trailing dot for the root of the tree).

So maybe the addendum here is a length check at the end would handle the overflows and reset the name to something of the ```<guid-or-timestamp-or-hash>.v3.openshift.local```.

That should satisfy all the cases - does that work for y'all ?

**Comment by smarterclayton** [comment]
On Aug 7, 2015, at 2:18 AM, ramr <notifications@github.com> wrote:

@smarterclayton <https://github.com/smarterclayton> so re: the proposal we
would either need some k-v storage for the routes already allocated or we
have to build them up and keep 'em in memory in the controllers for
handling collisions.
Is the latter what you intended/meant? It probably has implications with
multiple controllers running as things could be processed in parallel (or
did you mean just a singleton)?


Generally we'd run a controller loop and a cache.Store and maintain the
invariant ourselves.  It would open a race in parallel is possible ,
however we always process in order so the outcome is deterministic across
machines.  So a controller loop for routes that keeps the map of routes for
the default router and uses the prefix.

Later we'd just move this to the routers and have them write the status.
We *could* do this now - it would support other cases.  We'd need to
prepare for having the array for router status and I don't think we've
thought through it that much.

As re: the generated routes themselves, if we don't have a name provided,
using
$name-$namespace.$<dns-suffix> we could support the wildcard certificates
support as well (probably also need to make sure no dots (.) are in the
prefixed name+namespace).


Yes - convert dot to dash

In case, the generated name already exists, the case is similar to @liggitt
<https://github.com/liggitt> foo-bar-baz example where name/namespace has 2
of those parts and collide. The collision detection check would add a
-<collision-fix> to the prefix ala `
$name-$namespace.[-<collision-fix>].$<dns-suffix>.


No dot but yes

And a last question was the collision-fix part -- increment assuming you
meant a numeric one
ala large-hadron-collider-42.v3.openshift.local - since name and namespace
are unbounded strings and dns names have implications in the length - each
component could be 63 octets and a max of 255 octets (well 251 if you
exclude the dots + 1 trailing dot for the root of the tree).



So maybe the addendum here is a length check at the end would handle the
overflows and reset the name to something of the
<guid-or-timestamp-or-hash>.v3.openshift.local.


We have existing code for this for deployment and build names


That should satisfy all the cases - does that work for y'all ?


Yes

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/issues/4015#issuecomment-128609373>.

**Comment by liggitt** [comment]
> since name and namespace are unbounded strings and dns names have implications in the length

they're not unbounded. route.namespace is limited to a single dns segment (63 chars, no dots). route.name is (unfortunately) allowed to be a dns subdomain (253 chars, allows dots), so it could eat up all available length. it really should be validated the same way a namespace is, limiting it to a single dns segment.

We could still hit a length issue if route.name and route.namespace add up to more than 63 chars and we try to make a single segment by concatenating them

**Comment by liggitt** [comment]
see namer.GetName()

could use it something like this:
```
i := 0
for {
  suffix := ""
  if i > 0 {
    suffix = fmt.Sprintf("-%d", i)
  }
  desiredName := namer.GetName(fmt.Sprintf("%s-%s%s", route.Name, route.Namespace, suffix), "", 63)
  if hostExists(desiredName + dnsSuffix) {
    i++
    continue
  }
  break
}
```

**Comment by liggitt** [comment]
When computing uniqueness, we need to remember that multiple routes can target the same host if they differ in TLS or path options.

We also probably want to blacklist some hosts or DNS suffixes from requested hosts (so "my-route" in "my-namespace" can request "foo.com" but not "your-route.your-namespace.apps.example.com")

**Comment by smarterclayton** [comment]
Generating a hash for an automatic name is fine (same as our other
statements).

On Fri, Aug 7, 2015 at 10:18 AM, Jordan Liggitt <notifications@github.com>
wrote:

> When computing uniqueness, we need to remember that multiple routes can
> target the same host if they differ in TLS or path options.
>
> We also probably want to blacklist some hosts or DNS suffixes from
> requested hosts (so "my-route" in "my-namespace" can request "foo.com"
> but not "your-route.your-namespace.apps.example.com")
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openshift/origin/issues/4015#issuecomment-128712209>.
>



-- 
Clayton Coleman | Lead Engineer, OpenShift
