### ISSUE TITLE
"Operation not permitted" inside pods

### ISSUE THREAD

**Issue by sebiwi** [openshift/origin#4078]
Hello,

I'm trying to deploy a pod using this manifest: http://www.fpaste.org/253439/14392147/ , which I just translated from api v1beta1 to api v1. (It used to work on v1beta1) 

The pod failed, so I saw the logs with `docker logs <container-id> and I got the following result:

"chown: changing ownership of '/var/lib/postgresql': Operation not permitted"

I get the same error with every pod I try to deploy. Here's the error of a similar deployment, with a redis container:

"mkdir: cannot create directory '/run/redis': Permission denied"

I already disabled Selinux, and it's still not working. I don't know what to do anymore. I saw a similar issue here, but in that case the user was able to deploy a pod using permissive mode, whereas whereas I am not able to do so.

I'm running a single node installation on a CentOS 7 host, deployed with openshift-ansible.

[cloud@master ~]$ oc version
oc v1.0.4-1-g85eea33
kubernetes v1.0.0

Any ideas?

**Comment by smarterclayton** [comment]
By default, images are run as a high, predictable UID.  That means that the image doesn't automatically have access to files that it was created as.  You can disable this protection per project, or use an image that doesn't require being run as a particular UID.  @bparees can you link the other items?

**Comment by bparees** [comment]
@sebiwi please see "support arbitrary user ids" here:
https://docs.openshift.org/latest/creating_images/guidelines.html#openshift-specific-guidelines

specifically:
 This means directories that need to be written to by processes in the image should be world-writable.

Other options include:
  - creating an emptydir volume for content you want your process to be able to write to (the volume will be created such that the uid of the container can write to it)

Also you need to make sure your process isn't trying to listen on a privileged port since it's not going to be running as root.

**Comment by bparees** [comment]
i've also just updated the docs to make things a bit clearer:
https://github.com/openshift/openshift-docs/pull/868

**Comment by sebiwi** [comment]
Ok, this solved the problem. Thanks.
