### ISSUE TITLE
Improve the rebase process to reduce developer cost

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#4083]
We currently have a fairly manual rebase process.  We have to prevent upstream commits from being accidentally dropped, which is fairly easy.  We should do what we can to automate risky/tedious parts of the process.

Suggestions:
- Provide tools for automatically listing all upstream commits since the last rebase, and identify which have merged into the pending Kubernetes rebase commit
- Provide tools for easily creating upstream commits / down porting
- Investigate moving back to having a forked Kube repo that we carry patches on
- Reduce risk of UPSTREAM patches introduced prior to a rebase being reverted (merge conflicts should usually identify, but not easy)

???

@deads2k @liggitt @pweil- @bparees @mfojtik @ncdc

**Comment by smarterclayton** [comment]
@eparis as well

**Comment by bparees** [comment]
can we start this discussion w/ a doc of the current rebase process?

**Comment by smarterclayton** [comment]
You mean: https://github.com/openshift/origin/blob/master/HACKING.md#2-rebase-origin-to-the-new-kubernetes-version
?

**Comment by bparees** [comment]
yes.

**Comment by pweil-** [comment]
> Reduce risk of UPSTREAM patches introduced prior to a rebase being reverted (merge conflicts should usually identify, but not easy)

This was/is the biggest issue for me when I'm rebasing.  This occurs in both the godeps and the OpenShift code and may not show up as upstreams since the last rebase.  Sometimes there are conflicts and sometimes not.  The last one that bit me didn't show until a final run of e2e-docker.  

Maybe we can inspect each dep and identify the dependencies we're carrying patches for (other than Kube) and list those out as well as reconcile what the last rebase PR carried in addition to upstreams since the last rebase.

**Comment by smarterclayton** [comment]
Or before you rebase we turn them into patches, and then a user has to go
through them one by one and apply and delete them.

On Mon, Aug 10, 2015 at 1:11 PM, Paul Weil <notifications@github.com> wrote:

> Reduce risk of UPSTREAM patches introduced prior to a rebase being
> reverted (merge conflicts should usually identify, but not easy)
>
> This was/is the biggest issue for me when I'm rebasing. This occurs in
> both the godeps and the OpenShift code and may not show up as upstreams
> since the last rebase. Sometimes there are conflicts and sometimes not. The
> last one that bit me didn't show until a final run of e2e-docker.
>
> Maybe we can inspect each dep and identify the dependencies we're carrying
> patches for (other than Kube) and list those out as well as reconcile what
> the last rebase PR carried in addition to upstreams since the last rebase.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openshift/origin/issues/4083#issuecomment-129529025>.
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by deads2k** [comment]
One of the first issues I run into is figuring out which godeps are actually being bumped.  I build a correct list by going through the list of updated godeps, comparing to `Godeps.json` and making sure that the `rev` tag was changed.  If the tag was changed, I look to see if it was changed because kube updated and then I inspect to see which tag is newer to decide which copy to keep.

That would be nice to have scripted.
