### ISSUE TITLE
Altering an ImageStream should invalidate the imported images and re-import?

### ISSUE THREAD

**Issue by sdodson** [openshift/origin#4100]
I've been working on setting up an air gapped (sort of) environment where OSE pulls images from Satellite 6.1 rather than from dockerhub or registry.access.redhat.com. Unfortunately when I deployed the environment it imported the image streams while they were pointed at registry.access.redhat.com, if this were truly air gapped then that wouldn't have happened. I then subsequently modified all the imagestreams to point at my Satellite 6.1 environment, however since the images were already imported subsequent imports won't update any of the existing docker docker references as the image ids are the same.

If I delete them manually and re-import everything is fine. I believe modifying the image stream should invalidate the images that are tied to that image stream.

**Comment by sdodson** [comment]
```
# oc get -n openshift is/php
NAME      DOCKER REPO                                                                                            TAGS                           UPDATED
php       sdodson-sat6.example.com.os1.phx2.redhat.com:5000/openshift-openshift_images-openshift3_php-55-rhel7   5.5,latest,v3.0.0.0,v3.0.1.0   57 minutes ago

# oc get images -n openshift | grep php                                                                                                                                                                                                             
2b8583f742ac6c759a342033dceedf360f5e4d7a1c3eef4d073f3ecbb9f492e2          registry.access.redhat.com/openshift3/php-55-rhel7:v3.0.0.0
3c7c6d0b04516295ae6f699bfb8b3562eb3acd60b95a3bc4d013a9496de49a54          registry.access.redhat.com/openshift3/php-55-rhel7:latest

# oc delete image -n openshift 3c7c6d0b04516295ae6f699bfb8b3562eb3acd60b95a3bc4d013a9496de49a54
images/3c7c6d0b04516295ae6f699bfb8b3562eb3acd60b95a3bc4d013a9496de49a54
# oc delete image -n openshift 2b8583f742ac6c759a342033dceedf360f5e4d7a1c3eef4d073f3ecbb9f492e2

# oc import-image -n openshift php
# oc get images -n openshift | grep php                                                                                                                                                                                                             
2b8583f742ac6c759a342033dceedf360f5e4d7a1c3eef4d073f3ecbb9f492e2          sdodson-sat6.example.com.os1.phx2.redhat.com:5000/library/openshift-openshift_images-openshift3_php-55-rhel7:v3.0.0.0
3c7c6d0b04516295ae6f699bfb8b3562eb3acd60b95a3bc4d013a9496de49a54          sdodson-sat6.example.com.os1.phx2.redhat.com:5000/library/openshift-openshift_images-openshift3_php-55-rhel7:latest
```

**Comment by sdodson** [comment]
@ncdc Thoughts on what the proper behavior should be here?

**Comment by ncdc** [comment]
@sdodson I agree there's a problem we probably need to solve, but I don't think it's appropriate to delete the images associated with an image stream when you change the stream's spec.dockerImageRepository. This is mainly because you could have other image streams pointing to these images, and you'd end up with dangling references when you delete them.

I don't have a good solution in mind but I'll keep thinking.

@smarterclayton here's another issue where having the pull spec live in the Image is causing a problem. Maybe we need a way to "rehome" an image...

**Comment by smarterclayton** [comment]
Rehome is a registry proxy feature I think, but i suspect you get a toggle
on the spec tag if you want that.  Not for 3.1 :)

On Aug 11, 2015, at 11:21 AM, Andy Goldstein <notifications@github.com>
wrote:

@sdodson <https://github.com/sdodson> I agree there's a problem we probably
need to solve, but I don't think it's appropriate to delete the images
associated with an image stream when you change the stream's
spec.dockerImageRepository. This is mainly because you could have other
image streams pointing to these images, and you'd end up with dangling
references when you delete them.

I don't have a good solution in mind but I'll keep thinking.

@smarterclayton <https://github.com/smarterclayton> here's another issue
where having the pull spec live in the Image is causing a problem. Maybe we
need a way to "rehome" an image...

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/issues/4100#issuecomment-129927758>.

**Comment by soltysh** [comment]
#5932 addresses that partially by clearing the import annotation, but that's only for tags that are pointing to external images (eg. docker hub).

**Comment by smarterclayton** [comment]
Modifying the IS should not reset the annotation.  Eventually, we will formalize the annotation as a field on the object.  When we do that, you'll have to clear the "latest" state in order to import.

**Comment by smarterclayton** [comment]
With scheduled import and the importer this is now done
