### ISSUE TITLE
Router: Add a default value for the service account parameter

### ISSUE THREAD

**Issue by ramr** [openshift/origin#4133]
Add in a default value for ```--service-account``` parameter - value of ```router```. 

See discussions in https://github.com/openshift/origin/pull/3977  for more details.

**Comment by ramr** [comment]
@liggitt   Hmm, would a default of ```default``` (yeah, I know sounds weird - DoD but ...) work better here?
Or do we want to add a ```router``` serviceaccount in addition to the ```builder, deployer, default```?

**Comment by liggitt** [comment]
builder, deployer, and default are different, since we need those in every namespace. We'd only have a single 'router' service account in the namespace where they created the router deployment.

**Comment by samsong8610** [comment]
Is there any restriction to the router service account? Special roles? Or in special groups?

**Comment by liggitt** [comment]
the service account should be in a securityContextContraint that allows host network usage (see https://docs.openshift.org/latest/admin_guide/install/deploy_router.html#haproxy-router)

ideally, it would also have the `system:router` role, for when the router starts to use its service account to contact the API, rather than the passed `--credentials`

**Comment by liggitt** [comment]
why wouldn't we default this to `router` and have the `oadm` router command create the service account for you?

**Comment by ramr** [comment]
Hmm, not sure I like the adding the service account to the privileged scc ```post-facto``` ... its more prone to failure (easy to miss a step and things are just broken).

Why not create a default openshift infrastructure system router account (akin to the build-controller),
which is part of the privileged scc? And default the router to using that new router service account.

**Comment by liggitt** [comment]
Because the router doesn't run in the openshift infra namespace

**Comment by liggitt** [comment]
We would still document it and you would still be expected to do it, but if you hadn't, you could recover without deleting things and starting over

**Comment by ramr** [comment]
Well, it doesn't have to be the openshift infra namespace (though that is a good fit for infrastructure components), it could be the default namespace.

imho, this makes for pretty bad OOTB experience -- we are basically saying:  you can start the router with n copies a simple command (```oadm router --replicas=3```) and it picks up defaults but you have to do add this router service account (its the default and you didn't even specify it)  to the privileged scc.

We still need to document it if you wanted to do it in a custom namespace and/or service account - but the default is what I am a little concerned about.  Also, I think if this runs in another namespace, there needs to be the network isolation work to consider as well, because the router container needs to talk to the actual pods [which wouldn't happen if network isolation is place]. 

/cc  @rajatchopra @danwinship

**Comment by knobunc** [comment]
Is it reasonable for me to get started with this and initially implement:
 a) Default the `--service-account` parameter of `oadm router` to be the user `router`
 b) Determine if the named service account exists, and if not, do the equivalent of: `echo '{"kind":"ServiceAccount","apiVersion":"v1","metadata":{"name":"router"}}' \ | oc create -f -`

Then we can work out whether we want to make the privileged account automatically or not in parallel.

Seem reasonable?

**Comment by liggitt** [comment]
I don't want to auto-create a service account at server start... doing it as part of the router command seems reasonable to me...

Possible flows:
* Post-create grant
  1. `oadm router ...`
  2. everything is set up, but pods aren't created because of scc permissions
  3. user adds router service account to scc
  4 pods start getting created and working
* Pre-create grant
  1. User actually reads documentation and adds the service account to the scc
  2. Everything works on create
* Non-hostport
  1. `oadm router --host-network=false`
  2. Pods are created, since host network isn't required

In the `--host-network=true` case, we could still do the SCC detection in the router command and tell them what they need to do to add the service account before the pods can be created

**Comment by liggitt** [comment]
Also do the following:

* move the secret add after the bulk.Create
* add the service account to the list of objects to bulk.Create (or output when -o yaml)
* only check scc when --host-network=true

**Comment by knobunc** [comment]
Pull request: https://github.com/openshift/origin/pull/5265

**Comment by knobunc** [comment]
This has been resolved under a different PR, but the functionality is present.
