### ISSUE TITLE
oc build-logs is a pain to use

### ISSUE THREAD

**Issue by deads2k** [openshift/origin#4188]
`oc build-logs` can't operate on a `buildconfig`, which is annoying when transitioning between `oc status` `oc build-logs`.  It should guess at the logs for the latest build.

Also, `oc build-logs` doesn't access `builds/build-name` which makes it painful to pipe values from a label limited `oc get`.

@bparees @fabianofranz Not sure who owns the CLI build commands.

**Comment by bparees** [comment]
having oc build-logs automatically return logs for the most recent build would be confusing automatic behavior given that you could have multiple buildconfigs in your project, any one of which might have the most recent build at any given point in time.  if you want to add a "oc build-logs --latest" flag for that sort of magic behavior i guess i could get behind it, but not default behavior.

We did investigate at great length the idea of having build-logs return a list of the 10 most recent builds if you ran it with no commands, but due to the latency of getting the build list back, we ultimately decided the best approach would be to just tell users "run oc get builds" if they run oc build-logs with no arguments.  they're going to quickly learn they need to get the build list before running it, so baking that behavior into build-logs (which would still require two commands, once with no args to get the list and once with the right arg) doesn't provide much benefit): https://github.com/openshift/origin/pull/4044  (and the --latest flag would suffer from similar latency problems)

As for oc build-logs being able to take builds/build-name...  oc build-logs is likely going to ultimately go away in favor of a variant of oc log that takes builds/build-name.  (or at a minimum you will be able to use that for the behavior you want)  I know @kargakis was pushing on that, not sure the current state.

**Comment by deads2k** [comment]
I meant something like `oc build-logs bc/foo` shows me the logs for the most recent build.  `oc deploy --logs dc/foo` is going to do that.

**Comment by deads2k** [comment]
In `oc status`, I get bc names, but only build numbers because the build names themselves aren't important or interesting.

**Comment by mfojtik** [comment]
@jhadvig CC

**Comment by bparees** [comment]
@deads2k I stand by the statement that oc build-logs should be going away in favor of oc logs.  the oc logs behavior for bc/somebc could be what you propose, but again it has latency implications.

**Comment by kargakis** [comment]
@bparees the latency you observed in `oc build-logs` was due to the client tool fetching a list of builds while `oc deploy --logs dc/foo` leaves that fetching to the api server. We actually don't even get the whole list but the [desired deployment](https://github.com/kargakis/origin/blob/f68fd9084c7ca8d63497a0d3d85dc3ac376e31dd/pkg/deploy/registry/deploylog/rest.go#L105) so I guess something similar can be done for `build-logs`.

**Comment by bparees** [comment]
@deads2k is all of this resolved by @kargakis 's changes?  namely in that you can just use "oc logs" and oc logs has the behavior you desire, i believe.

**Comment by bparees** [comment]
assigning to @kargakis on the assumption his changes fixed this.  if there's anything still not covered by those changes, we'll find a new owner.

**Comment by kargakis** [comment]
`oc logs` supports bcs and soon I'll add `--no-wait` so `build-logs` will be fully superceded. I guess this issue can close.

**Comment by bparees** [comment]
@deads2k agree?

**Comment by deads2k** [comment]
agree
