### ISSUE TITLE
My sti builder can not reference OpenShift services

### ISSUE THREAD

**Issue by jorgemoralespou** [openshift/origin#4303]
I have created a nexus server in OpenShift, and created a service for it:
````
nexus.ci-tools.svc.cluster.local
````
I`m using the https://github.com/openshift/sti-wildfly builder image, and have a settings.xml file to build using my nexus server, referenced via the service. 

The problem I'm seeing is that the assemble does not get to the service:
````
Downloading: http://nexus.ci-tools.svc.cluster.local:8081/content/groups/public/org/jboss/spec/jboss-javaee-6.0/3.0.2.Final-redhat-15/jboss-javaee-6.0-3.0.2.Final-redhat-15.pom
[ERROR] The build could not read 1 project -> [Help 1]
````

If I try to access same url from the registry pod, I can:
````
--2015-08-21 11:59:02--  http://nexus.ci-tools.svc.cluster.local:8081/content/groups/public/org/jboss/spec/jboss-javaee-6.0/3.0.2.Final-redhat-15/jboss-javaee-6.0-3.0.2.Final-redhat-15.pom
Resolving nexus.ci-tools.svc.cluster.local (nexus.ci-tools.svc.cluster.local)... 127.0.53.53, 172.30.22.4
Connecting to nexus.ci-tools.svc.cluster.local (nexus.ci-tools.svc.cluster.local)|127.0.53.53|:8081... failed: Connection refused.
Connecting to nexus.ci-tools.svc.cluster.local (nexus.ci-tools.svc.cluster.local)|172.30.22.4|:8081... connected.
HTTP request sent, awaiting response... 200 OK
Length: 18316 (18K) [application/xml]
Saving to: 'jboss-javaee-6.0-3.0.2.Final-redhat-15.pom.5'
````

Is the origin-sti-builder:v1.0.3 image propagating the information in resolv.conf to the sti-wildfly? If not, I think this is a big problem, since I can not use internal service references for maven builds.

**Comment by bparees** [comment]
I thought docker always propagated the /etc/resolv.conf from the host into the running container.  is your hosts /etc/resolv.conf correct?

**Comment by jorgemoralespou** [comment]
Do you mean that resolv.conf is get from the host in case of a builder,  as it's plain docker daemon the one executing the build? I'll check it on Monday, once I have access to my laptop.

**Comment by bparees** [comment]
@smarterclayton you indicated this was might be considered a bug in the email thread... can we discuss how to approach it here?  I guess the k8s managed containers get the /etc/resolv.conf with the master ip injected, but the build containers don't since they aren't managed by k8s.

So i assume you'd like to see us manipulating the container's resolv.conf in the same way that k8s does?

**Comment by bparees** [comment]
@jorgemoralespou yes exactly.

**Comment by smarterclayton** [comment]
Yes when we invoke docker we should copy our own DNS settings in.

On Aug 22, 2015, at 4:47 PM, Ben Parees <notifications@github.com> wrote:

@smarterclayton <https://github.com/smarterclayton> you indicated this was
might be considered a bug in the email thread... can we discuss how to
approach it here? I guess the k8s managed containers get the
/etc/resolv.conf with the master ip injected, but the build containers
don't since they aren't managed by k8s.

So i assume you'd like to see us manipulating the container's resolv.conf
in the same way that k8s does?

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/issues/4303#issuecomment-133752991>.

**Comment by liggitt** [comment]
Should be a straight copy of the sti container's mounted resolv.conf, right?

**Comment by smarterclayton** [comment]
You have to parse it, but yes.  We should be setting the flags the kubelet
sets.

On Aug 23, 2015, at 6:01 PM, Jordan Liggitt <notifications@github.com>
wrote:

Should be a straight copy of the sti container's mounted resolv.conf, right?

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/issues/4303#issuecomment-133943652>.

**Comment by jorgemoralespou** [comment]
Hi,
I'm not a DNS or networking expert but if I set my hosts DNS to be able to resolve the services that means I would have to add SkyDNS in front, not? Then I would loose all the real DNS resolution for everything else, so not even an option IMHO.
We need to inject the resolv.conf into the builder as @smarterclayton says.

**Comment by bparees** [comment]
you would not lose the ability to resolve everything else.

**Comment by bparees** [comment]
trello'd https://trello.com/c/f3azg2K1/685-builder-containers-don-t-have-openshift-cluster-dns
