### ISSUE TITLE
deployment controller in rapid delete - create sequence with same name causes incorrect version info

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#4330]
`test/cmd/deployments.sh` runs rapidly and creates, then deletes, then creates the same DC.  It looks like the controller gets confused and creates a new RC 2 for the first deployment, but the second deployment is still at latest version 1 (or 2, in some cases).

@ironcladlou @kargakis

**Comment by ironcladlou** [comment]
I'm running `test/cmd/deployments.sh` and am not entirely sure I'm seeing what you saw... do you happen to have some sample output from a case where things are wrong?

**Comment by ironcladlou** [comment]
Nevermind, I think based on #4328 I have enough to go on to try and reproduce.

**Comment by kargakis** [comment]
@ironcladlou I can reproduce this but not reliably.

First, I have edited `deplyoments.sh` like
```sh
...
echo "deploymentConfigs: ok"

oc create -f test/integration/fixtures/test-deployment-config.json
oc deploy test-deployment-config --latest
oc scale dc test-deployment-config --replicas=1 --loglevel=2
oc describe dc/test-deployment-config
...
```

Then in `pkg/deploy/scaler/scale.go#L102` I have added
```go
glog.V(2).Infof("Trying to get deployment %q", util.LatestDeploymentNameForConfig(dc))
```

Possible outcomes by running `hack/test-cmd.sh`:
1) The first deployment will still be pending when `deploy --latest` runs so the script will fail.
2) Everything runs normally.
3) On the client:
```
deploymentConfigs: ok
deploymentconfig "test-deployment-config" created
Started deployment #2
I0916 13:15:20.933744   18216 scale.go:102] Trying to get deployment "test-deployment-config-3"
I0916 13:15:20.936584   18216 scale.go:42] No deployment found for dc/test-deployment-config. Scaling the deployment configuration template...
deploymentconfig "test-deployment-config" scaled
Name:		test-deployment-config
Created:	2 seconds ago
Labels:		<none>
Latest Version:	3
Triggers:	Config
Strategy:	Recreate
Template:
  Selector:	name=test-deployment
  Replicas:	1
  Containers:
  NAME			IMAGE						ENV
  ruby-helloworld	127.0.0.1:5001/openshift/origin-ruby-sample	TEST=value
Latest Deployment:	<none>
Deployment #2:
	Created:	3 seconds ago
	Status:		Pending
	Replicas:	0 current / 0 desired
No events.
```

Server log: http://pastebin.com/8bSCq3bD

**Comment by ironcladlou** [comment]
I finally reproduced it and at least understand where version 3 is coming from: environment vars for the containers in the DC are being updated back to their original state at some point, which is detected as a config change.

version 1->2:
```
Env: ([]api.EnvVar) (len=1 cap=1) {
 (api.EnvVar) {
  Name: (string) (len=4) "TEST",
  Value: (string) (len=5) "value",
  ValueFrom: (*api.EnvVarSource)(<nil>)
 }
},

to

Env: ([]api.EnvVar) (len=2 cap=2) {    
 (api.EnvVar) {                        
  Name: (string) (len=4) "TEST",       
  Value: (string) (len=3) "bar",       
  ValueFrom: (*api.EnvVarSource)(<nil>)
 },                                    
 (api.EnvVar) {                        
  Name: (string) (len=5) "OTHER",      
  Value: (string) (len=3) "baz",       
  ValueFrom: (*api.EnvVarSource)(<nil>)
 }                                     
},                                     
```

version 2->3:

```
Env: ([]api.EnvVar) (len=2 cap=2) {
 (api.EnvVar) {
  Name: (string) (len=4) "TEST",
  Value: (string) (len=3) "bar",
  ValueFrom: (*api.EnvVarSource)(<nil>)
 },
 (api.EnvVar) {
  Name: (string) (len=5) "OTHER",
  Value: (string) (len=3) "baz",
  ValueFrom: (*api.EnvVarSource)(<nil>)
 }
},

to

Env: ([]api.EnvVar) (len=1 cap=1) {     
 (api.EnvVar) {                         
  Name: (string) (len=4) "TEST",        
  Value: (string) (len=5) "value",      
  ValueFrom: (*api.EnvVarSource)(<nil>) 
 }                                      
},                                      
```
```

**Comment by ironcladlou** [comment]
I need to do a lot more testing, but I have a theory now: deployment v2 (for the env change produced by `oc env`) is being continually requeued in the change controller due to the in-flight deployment for  v1 which will never complete. The DC is deleted. Sometimes the deletion happens while the change controller has v2 still queued in memory (or has just started processing v2) after the DC (and the v1 deployment) are deleted but before the re-creation of the DC on the following test lines. Now that there's no "in flight" deployment, the config controller creates deployment 2 even though it's orphaned. Then, the config is re-created, auto-bumped to v1 from its config trigger, and then gets stalled in the config change queue because the orphaned v2 deployment is now "in flight".

**Comment by ironcladlou** [comment]
This is related to #3660

**Comment by ironcladlou** [comment]
So, we're not going to be able to prevent creating the RC when the DC has been deleted (because we can't guarantee we have the latest DC state at the time of creation, and we can't establish an FK relationship between the RC and the DC to cause an atomic create breakage). The reality seems to be that it'll be possible to create the deployment RC (and as another possible byproduct, a deployer pod) right after the DC was deleted.

So then,

1. What should become of the orphan if the DC is never re-created?
2. What should the state of a new DC with the same name be? Letting it persist with a version less than the orphan breaks stuff.

Same sort of discussions from #3660.

**Comment by smarterclayton** [comment]
The RC from a different DC uid should not be considered part of the
sequence probably.

On Sep 17, 2015, at 2:29 PM, Dan Mace <notifications@github.com> wrote:

So, we're not going to be able to prevent creating the RC when the DC has
been deleted (because we can't guarantee we have the latest DC state at the
time of creation, and we can't establish an FK relationship between the RC
and the DC to cause an atomic create breakage). The reality seems to be
that it'll be possible to create the deployment RC (and as another possible
byproduct, a deployer pod) right after the DC was deleted.

So then,

   1. What should become of the orphan if the DC is never re-created?
   2. What should the state of a new DC with the same name be? Letting it
   persist with a version less than the orphan breaks stuff.

Same sort of discussions from #3660
<https://github.com/openshift/origin/issues/3660>.

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/issues/4330#issuecomment-141178114>.

**Comment by ironcladlou** [comment]
>The RC from a different DC uid should not be considered part of the sequence probably.

I don't know we can make the distinction that the RC is technically owned by the DC but should only be excluded for sequence computation (and making sequence computed like that is itself a big unknown in terms of LOE). The problem would be resolved easily if the DC didn't adopt the orphan in any respect. Unfortunately, supporting such a concept at this point seems like a big effort. I think at the least RCs would need correlated to DCs by UID instead of (or in addition to) name, and anything that wants to find RCs by DC would need to (one way or another) use that association.

Am I missing a simpler solution?

**Comment by smarterclayton** [comment]
We could see the annotation and fail the deployment maybe?  Not sure

On Sep 17, 2015, at 4:07 PM, Dan Mace <notifications@github.com> wrote:

The RC from a different DC uid should not be considered part of the
sequence probably.

I don't know we can make the distinction that the RC is technically owned
by the DC but should only be excluded for sequence computation (and making
sequence computed like that is itself a big unknown in terms of LOE). The
problem would be resolved easily if the DC didn't adopt the orphan in any
respect. Unfortunately, supporting such a concept at this point seems like
a big effort. I think at the least RCs would need correlated to DCs by UID
instead of (or in addition to) name, and anything that wants to find RCs by
DC would need to (one way or another) use that association.

Am I missing a simpler solution?

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/issues/4330#issuecomment-141211696>.

**Comment by ironcladlou** [comment]
Discussed on IRC. Right now the assumption throughout the deployment system is that deployments/deployer pods/etc ownership is established by matching on config name. If new configs can inherit related objects from previous but same-named configs, it seems consistent to me that the version of that new config should be either:

1. The latest existing deployment version, if the config's pod template still matches what's deployed, or
2. The latest existing deployment version + 1 (if the templates don't match)

If version continuity isn't to be maintained, to me that implies that the new config doesn't really own the old resources, and they should somehow be disassociated.

**Comment by smarterclayton** [comment]
How would this work in upstream?

**Comment by ironcladlou** [comment]
>How would this work in upstream?

There's no version number to consider upstream, so none of these consistency issues apply.

If you recreated the deployment and its template hash still matched the latest, nothing would happen... if the hash was different, then the recreated deployment would be probably be considered new and everything else would get scaled down.

**Comment by smarterclayton** [comment]
Do you mean on the RC?

**Comment by ironcladlou** [comment]
Yeah, I meant RC... if the recreated deployment pod template doesn't match any existing RC pod templates, a new RC would be created based on the recreated deployment, and all other RCs for that deployment would be considered "old" and would be targetted for scale-down.

**Comment by smarterclayton** [comment]
So in the future, we'd adopt the RC automatically.  Today, we want to
adopt, but can't exactly.

**Comment by kargakis** [comment]
Is this still an issue? I've got an idea about adoption but that's a separate issue.

**Comment by kargakis** [comment]
I don't think this is an issue anymore, but reopen if you see it again.
