### ISSUE TITLE
Ginkgo Extended Tests Start 7 Nodes For One Test

### ISSUE THREAD

**Issue by stevekuznetsov** [openshift/origin#4490]
When running just one extended test, six nodes are spawned that never do anything and one that does. Can we scale the number of parallel nodes executing tests to the number of tests to be run, when the number of tests to be run is less than seven?

**Comment by mfojtik** [comment]
@stevekuznetsov I think this might be a bug in Ginkgo, where if you have a lot of skipped tests, it miscalculate the number of nodes spawned.  I think there is a way to control the number of nodes manually by ginkgo CLI, but you will first have to determine how many test cases you will run and do the math yourself.

I think it would be worth to try to fix this in Ginkgo, so the ginkgo command can do the math for us.

**Comment by stevekuznetsov** [comment]
asked upstream: https://github.com/onsi/ginkgo/issues/184

**Comment by stevekuznetsov** [comment]
@smarterclayton Now that you have refactored the starter code, do you think it is reasonable to externalize the `-p` notation so that you choose to add it to an invocation of `core.sh` if you are also choosing a `-focus` that will match multiple specs?

**Comment by smarterclayton** [comment]
You can pass any argument you want to core - so if you set focus, specify
-p if you want it.

On Sep 25, 2015, at 9:01 AM, Steve Kuznetsov <notifications@github.com>
wrote:

@smarterclayton <https://github.com/smarterclayton> Now that you have
refactored the starter code, do you think it is reasonable to externalize
the -p notation so that you choose to add it to an invocation of core.sh if
you are also choosing a -focus that will match multiple specs?

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/issues/4490#issuecomment-143215363>.

**Comment by stevekuznetsov** [comment]
@smarterclayton Currently `core.sh` has `-p` on by default. My question is if you're ok with removing that and requiring people to specify when they want it.

**Comment by smarterclayton** [comment]
I'm removing it in another pull.

**Comment by stevekuznetsov** [comment]
@smarterclayton Ok, awesome.

**Comment by stevekuznetsov** [comment]
With the parallel test flag now not inherent, this is a non-issue.
