### ISSUE TITLE
Add oc deploy --commit option

### ISSUE THREAD

**Issue by mfojtik** [openshift/origin#4571]
In addition to https://github.com/openshift/origin/pull/4569 it would be nice if we can follow up and add something similar to the `oc deploy` command. The use case for this is that in Jenkins, when I tested revision `112233` and I build an image out from the revision `112233`, I want to re-deploy and make sure the Docker image I use for deploy match with revision `112233`. Since the Docker image does have information about what source revision it was build from, when calling `oc deploy` we should make sure, that the image that is being deployed is the one with this label. 

@liggitt @ironcladlou i'm totally crazy or this makes sense?

The workflow I want is:

```console
$ oc start-build sample-app-build --commit=f497b20
$ oc deploy sample-app --commit=f497b20
```

**Comment by deads2k** [comment]
Wouldn't a `DeploymentConfig` linked to the `ImageStream` that your build is pushing to automatically kick off with the correct image once your build completed?

**Comment by mfojtik** [comment]
@deads2k yes, if you have ImageChangeTrigger, but this case is when you want to manually promote the build image without using ImageChangeTrigger (for example your company is doing some crazy verification before deploy).

**Comment by mfojtik** [comment]
@deads2k maybe you can do `oc deploy sample-app --latest` but in that case you are not sure that the current ImageStream has the Docker image built from the sources you want to deploy (unless you use Docker image tags in some crazy way)

**Comment by deads2k** [comment]
> @deads2k yes, if you have ImageChangeTrigger, but this case is when you want to manually promote the build image without using ImageChangeTrigger (for example your company is doing some crazy verification before deploy).

Wouldn't you want to use an a tag on the image in that case instead of the github commit?  I was pretty sure the ability to know which git commit was used was openshift specific, not supported by kube constructs or direct docker commands.  If we used an image tag or image hash instead, you'd be able to properly construct the lower level constructs as well.  Tagging the image with the git commit id, would allow both in a reasonable way.

**Comment by mfojtik** [comment]
@deads2k the image tags makes sense as long as I'm able to pair them with the source code revision the images were build from. We are adding the labels with ref currently during the S2I build, but I dunno if that labels are something ImageStream import and show (as annotation?).

**Comment by deads2k** [comment]
https://github.com/openshift/origin/issues/4198 is an issue for tagging the built image multiple ways, including with a git commit.

**Comment by ironcladlou** [comment]
The net effect of this command would be to update the deploymentConfig spec pod template to change some container definitions so they use a pullspec derived from the CLI input.

1. How is the specified commit hash ultimately converted into a pullspec?
2. How does the tooling know which container(s) within the deploymentConfig's pod template to update with the pullspec?
3. Would this logic be more appropriately located behind an API endpoint instead of a CLI command?

**Comment by mfojtik** [comment]
@ironcladlou my initial brainstorm:

1) We store the commit hash as an label/annotation of the `ImageStreamTag` when we import the Docker image. We are not importing any labels from the Docker image (but we will in near future) yet, but we already adding the "source.ref" label to all output images that are produced by OpenShift build system.

2) I guess we can make it as part of the Docker pullspec: `image@source:112233` (or invent some other query mechanism to get the ImageStreamTag that has label/annotation set to `source:"112233"`. Or we can add new field to ImageChangeTrigger (similar to `automatic`) where you can just specify the selector.

3) Agree, if we make this part of API, thinks like Jenkins plugin can benefit from this, but I think we can also expose this via `oc deploy`.

**Comment by bparees** [comment]
annotation on the IST probably won't work.  We need an actual IST for each commit.  If we did an annotation on the IST then we'd only have an IST for the last commit which isn't super useful.

so i think we need to do this via tags, which means we need builds to be able to output multiple tags.

1) build pushes commitid tag
2) IST gets created for that tag
3) deploy flow needs to be able to deploy that tag

**Comment by smarterclayton** [comment]
I'm not sure multiple tags is the solution.  For one thing, how do you know when to clean up old tags?  We definitely should support deploy of an exact image.  We should probably also have "precondition deploys" that attempt to deploy a specific image.

However... The point of having an image stream is to get this behavior.  If you need deterministic deployment, make you image stream tag action that way.  Our option for deploying an exact image is "oc tag image:id something:tag"

**Comment by bparees** [comment]
how do you find the image build from a particular commit, if not by tagging it with the commit?

yes you can annotate the IST, but then every time you push to that IST you'll lose the previous commit, so you have no ability to go back and deploy an old commit.

yes cleaning up the old tags is a problem, but if you want the ability to deploy by commit, then you need to keep the old image tags around and now it's on you to decide how/when to prune them (or we add some tooling for that).

Those images will share 99% of their layer content anyway.

**Comment by smarterclayton** [comment]
You look at the image metadata.  If we are putting commit info into labels,
we should be using that.  If you want to output the git commit to an image
stream, you need a way to garbage collect that.  That pruning has to be a
user option, we can't just junk up an image stream with hundreds of tags
and not take into account how that falls out for the user experience.
Let's talk in person.

On Wed, Sep 9, 2015 at 10:11 AM, Ben Parees <notifications@github.com>
wrote:

> how do you find the image build from a particular commit, if not by
> tagging it with the commit?
>
> yes you can annotate the IST, but then every time you push to that IST
> you'll lose the previous commit, so you have no ability to go back and
> deploy an old commit.
>
> yes cleaning up the old tags is a problem, but if you want the ability to
> deploy by commit, then you need to keep the old image tags around and now
> it's on you to decide how/when to prune them (or we add some tooling for
> that).
>
> Those images will share 99% of their layer content anyway.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openshift/origin/issues/4571#issuecomment-138922162>.
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by bparees** [comment]
@smarterclayton and I discussed, highlights from the conversion:

- using the git commit as a tag and creating a new IST for each build is ok if and only if we also introduce a pruning strategy that will keep the number of ISTs under control
- introducing an oc deploy semantic that allows you to specify a particular IST makes sense in conjunction with that.
- More generically, we'd want to introduce a way to oc deploy "find me an image with this label from the imagestream"
- Doing either of the above requires solving the problem of deployments with multiple containers, but that's a CLI syntax implementation detail
- We need to ensure docker LABELs from images are being imported somewhere.  I'm pretty sure that information is not available in etcd today, we need to change that (annotation on the IST?  part of the Image virtual resource?  something).  @ncdc or @pweil- can correct me if this information is already available somewhere.
- For CI flows, the right approach is probably to create a new DC for each image we want to test, rather than redeploying an existing DC with a new image.  The latter solution has race condition problems when multiple new images become available simultaneously.
- As part of that flow it would also make sense to introduce a new deployment strategy which runs the image exactly once, allows for some testing (post-deploy hook?) and then deletes itself.

**Comment by ncdc** [comment]
@bparees labels are in etcd: https://github.com/openshift/origin/blob/master/pkg/image/api/dockertypes.go#L54

**Comment by smarterclayton** [comment]
* We need to ensure that labels from images are visible in all of the CLI
and UI flows that show images.
* We should allow you to search an IST or an IS to find images that have
particular labels or metadata.

On Wed, Sep 9, 2015 at 1:57 PM, Ben Parees <notifications@github.com> wrote:

> @smarterclayton <https://github.com/smarterclayton> and I discussed,
> highlights from the conversion:
>
>    - using the git commit as a tag and creating a new IST for each build
>    is ok if and only if we also introduce a pruning strategy that will keep
>    the number of ISTs under control
>    - introducing an oc deploy semantic that allows you to specify a
>    particular IST makes sense in conjunction with that.
>    - More generically, we'd want to introduce a way to oc deploy "find me
>    an image with this label from the imagestream"
>    - Doing either of the above requires solving the problem of
>    deployments with multiple containers, but that's a CLI syntax
>    implementation detail
>    - We need to ensure docker LABELs from images are being imported
>    somewhere. I'm pretty sure that information is not available in etcd today,
>    we need to change that (annotation on the IST? part of the Image virtual
>    resource? something). @ncdc <https://github.com/ncdc> or @pweil-
>    <https://github.com/pweil-> can correct me if this information is
>    already available somewhere.
>    - For CI flows, the right approach is probably to create a new DC for
>    each image we want to test, rather than redeploying an existing DC with a
>    new image. The latter solution has race condition problems when multiple
>    new images become available simultaneously.
>    - As part of that flow it would also make sense to introduce a new
>    deployment strategy which runs the image exactly once, allows for some
>    testing (post-deploy hook?) and then deletes itself.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openshift/origin/issues/4571#issuecomment-138990510>.
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by smarterclayton** [comment]
Do we display the images?

On Wed, Sep 9, 2015 at 2:03 PM, Andy Goldstein <notifications@github.com>
wrote:

> @bparees <https://github.com/bparees> labels are in etcd:
> https://github.com/openshift/origin/blob/master/pkg/image/api/dockertypes.go#L54
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openshift/origin/issues/4571#issuecomment-138991973>.
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by bparees** [comment]
@ncdc those are for a running container, right?  what about the labels associated with an image that we imported as an imagestreamtag but we aren't running anywhere?

**Comment by ncdc** [comment]
@bparees you'll want to look at image.config.labels, not image.containerConfig.

**Comment by bparees** [comment]
ok @ncdc showed me the information is available via "oc get istag foo:tag -o yaml" so that part at least is there.  (the UI should probably be using that to figure out which imagestreams are builder images instead of just relying on the annotation, @jwforres @spadgett, or we ought to be propagating those labels into imagestreamtag annotations, @pweil-  )

**Comment by smarterclayton** [comment]
If you can't see labels under `oc get istag foo:tag` we should fix that soon

**Comment by kargakis** [comment]
> If you can't see labels under oc get istag foo:tag we should fix that soon

Output of getting a tag is already big
```
$ oc get istag/ruby-20-centos7:latest
NAME                     DOCKER REF                                                                                          UPDATED          IMAGENAME
ruby-20-centos7:latest   openshift/ruby-20-centos7@sha256:97630cc0a75f553315ea7723fcfb23c281fe879ffb02dde85834312db07833a8   40 minutes ago   sha256:97630cc0a75f553315ea7723fcfb23c281fe879ffb02dde85834312db07833a8
```

Since the docker reference is already including the image name, how about dropping the latter and adding a LABELS field? Then, in case of a ton of labels[1], how should we structure the output? Also I guess `describe` should also include those labels too.[2]

[1] 
```
$ oc get istag/ruby-20-centos7:latest -o yaml
apiVersion: v1
image:
  dockerImageMetadata:
    Architecture: amd64
    Author: SoftwareCollections.org <sclorg@redhat.com>
    Config:
      [ ... ]
      Labels:
        License: GPLv2
        Vendor: CentOS
        io.k8s.description: Platform for building and running Ruby 2.0 applications
        io.k8s.display-name: Ruby 2.0
        io.openshift.builder-base-version: da8a37c
        io.openshift.builder-version: 86fb96b
        io.openshift.expose-services: 8080:http
        io.openshift.s2i.scripts-url: image:///usr/local/sti
        io.openshift.tags: builder,ruby,ruby20
        io.s2i.scripts-url: image:///usr/local/sti
     [ ... ]
```

[2]
```
$ oc describe istag/ruby-20-centos7:latest
Name:		sha256:97630cc0a75f553315ea7723fcfb23c281fe879ffb02dde85834312db07833a8
Created:	40 minutes ago
Labels:		<none>
Docker Image:	openshift/ruby-20-centos7@sha256:97630cc0a75f553315ea7723fcfb23c281fe879ffb02dde85834312db07833a8
Image Name:	sha256:97630cc0a75f553315ea7723fcfb23c281fe879ffb02dde85834312db07833a8
[ ... ]
```

**Comment by bparees** [comment]
@soltysh the last few comments here relate to our discussion about docker labels and imagestreamtag annotations.  as noted by @ncdc the docker labels are available on the Image definition in etcd, but not the imagestreamtag.

**Comment by ncdc** [comment]
They are available from the IST, since it contains the Image.

**Comment by kargakis** [comment]
@mfojtik you can do this now by having an ICT set to automatic: true and use no config change trigger. Your new image will always be resolved in the podtemplate and you will always need to run manually a deployment.
