### ISSUE TITLE
e2e build fails: "Error pushing to registry: Unknown device"

### ISSUE THREAD

**Issue by deads2k** [openshift/origin#4591]
e2e fails because the build fails.  The error from "container-ruby-sample-build-1-build-sti-build.log" is:

```
I0909 01:29:03.773338       1 sti.go:406] Your bundle is complete!
I0909 01:29:03.773343       1 sti.go:406] It was installed into ./bundle
I0909 01:29:03.799857       1 sti.go:406] ---> Cleaning up unused ruby gems ...
I0909 01:29:07.581662       1 sti.go:149] Using provided push secret for pushing 172.30.75.130:5000/test/origin-ruby-sample:latest image
I0909 01:29:07.581686       1 sti.go:151] Pushing 172.30.75.130:5000/test/origin-ruby-sample:latest image ...
F0909 01:29:44.016440       1 builder.go:54] Build error: Failed to push image: Error pushing to registry: Unknown device f6f39725d938c8ad3941b20fc230e9eb17c7d2d9bbb760733de1c32562b5c86a
```

@bparees

**Comment by deads2k** [comment]
https://ci.openshift.redhat.com/jenkins/job/merge_pull_requests_origin/3267 and https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin/4858 as examples

**Comment by liggitt** [comment]
looks like a docker issue.. not sure of the priority on this

**Comment by bparees** [comment]
@jhadvig can we add this to the list of retry conditions?  though i'm guessing a retry won't help.

**Comment by liggitt** [comment]
yeah, looks like a general error with docker-storage-setup on the devenvs (https://gist.github.com/ncdc/b7a32522ce37da1ea349)

**Comment by vbatts** [comment]
@danmcp issues with docker-storage-setup need to go to @rhatdan and @rhvgoyal

**Comment by rhatdan** [comment]
Lets assign to @rhvgoyal unless it is a packaging error.

**Comment by danmcp** [comment]
@rhvgoyal isn't in the list so I have assigned to Jhon for reporting purposes.

**Comment by rhvgoyal** [comment]
Well, the primary error is not because of docker-storage-setup. I think that's coming from docker device mapper and it simply seems to say that it does not have the device one is looking for. Either it has already been deleted or we are dealing with some sort of issue. May be related to concurrent pull races.

docker-storage-setup error just says that a thin pool could not be setup. On these systems, no lvm is being used looks like. Now I have put a patch which will error out little early if a volume group is not found.

https://github.com/projectatomic/docker-storage-setup/commit/aa69e77568c54132d606d5f62df57f64f75b4332

So few questions.

- Why are we running images without lvm. docker-storage-setup can not setup lvm thin pool in that case and that means docker will be setting thin pool on top of loop devices. So first need to fix that.

- Once that is fixed, see if error is still happening. If it is happening, then we need to debug further what's wrong.

**Comment by jwhonce** [comment]
@deads2k Do you have the answers for @rhvgoyal 's quetions?

**Comment by deads2k** [comment]
closing due to age.
