### ISSUE TITLE
Integration test flake in concurrent build

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#4659]
From https://s3.amazonaws.com/archive.travis-ci.org/jobs/80162163/log.txt

```
--- FAIL: TestConcurrentBuildControllers-16 (18.71s)
	buildcontroller_test.go:111: The build was modified an unexpected number of times. Got: 0, Expected: 1
	buildcontroller_test.go:114: The build pod was created an unexpected number of times. Got: 0, Expected: 1
FAIL
```

@csrwng

**Comment by csrwng** [comment]
It's failing to create a pod because of a missing SA token:

I0914 01:57:51.400445   21751 factory.go:37] Retrying Build integration/mock-build6oxge with error: Build failed with error integration/mock-build6oxge: failed to create pod for Build integration/mock-build6oxge: Pod "mock-build6oxge-build" is forbidden: no API token found for service account integration/default, retry after the token is automatically created and added to the service account

... earlier:

I0914 01:57:51.050464   21751 tokens_controller.go:337] Deleting secret integration/default-token-ew88c because reference couldn't be added (serviceaccounts "default" cannot be updated: the object has been modified; please apply your changes to the latest version and try again)

@liggitt - what can cause the SA to be modified simultaneously?

**Comment by liggitt** [comment]
Multiple controllers adding secrets to the service account (API token and dockercfg secret, probably)

**Comment by csrwng** [comment]
In this case, it's only the build controller that we should be running multiple of though. Is the secret added when the controller tries to use the SA?

**Comment by csrwng** [comment]
@deads2k ^^

**Comment by deads2k** [comment]
ServiceAccounts and their Secrets are modified by multiple controllers (4 maybe?).  The controllers do deconflict amongst themselves, but some amount of churn can happen.

Eventually a token will be created for the service account.  Since the only way to end up with a resource conflict on an SA is if the SA was updated, then the `tokens_controller` will have a ServiceAccountUpdate in its action queue, so the token will created for that update.  You shouldn't have to wait too long.

You should watch for SA readiness by ensuring that the SA has an API token secret associated with it.

**Comment by csrwng** [comment]
thx, I'll update the test

**Comment by csrwng** [comment]
@deads2k shouldn't this do the trick? 
https://github.com/openshift/origin/blob/master/test/integration/buildcontroller_test.go#L316

**Comment by csrwng** [comment]
ahh nm, that's just waiting on the SA, not on whether the token has been created. I'll fix that.
