### ISSUE TITLE
`hack/verify-godeps.sh`

### ISSUE THREAD

**Issue by deads2k** [openshift/origin#4736]
@kargakis @pweil- @liggitt https://github.com/kubernetes/kubernetes/blob/master/hack/verify-godeps.sh looks useful for our rebases, to at least help with the first hurdles.

If we forced it to pass during our ami tests (a weird extended bucket or in the extended job?), then we'd be a little cleaner.

**Comment by liggitt** [comment]
I like the idea. I would be more enthusastic if it wasn't giving me fits upstream

**Comment by eparis** [comment]
It's fixed upstream.

**Comment by smarterclayton** [comment]
Won't this fail for carried patches?

**Comment by eparis** [comment]
yup, that's the whole point. To see if your godeps really are godeps.  Hacked up stuff is 'supposed' to live in third_party....

**Comment by smarterclayton** [comment]
You mean like the entire /kube directory, and the five to ten other
packages we carry patches for?  So this would basically be "test godeps to
verify that we're carrying patches.  Yup, we're carrying patches!"

**Comment by eparis** [comment]
It will (as written) absolutely fail since origin's `Godeps/` are not reproducible (aka you know you carry patches in _workspace).

The script could be (pretty easily) changed to ignore directories you know you're carrying your own patches to. And thus make it obvious where you are patching things and where you are doing something reproducible.

I'm not advocating you 'need' to do this, but the test did allow me to remove lots of files which became dead.  And to make sure they don't come back...

**Comment by smarterclayton** [comment]
It might be good for us to have the discussion about how we make patches
more maintainable (eg lessons learned from brew and dist git)

On Sep 23, 2015, at 5:15 PM, Eric Paris <notifications@github.com> wrote:

It will (as written) absolutely fail since origin's Godeps/ are not
reproducible (aka you know you carry patches in _workspace).

The script could be (pretty easily) changed to ignore directories you know
you're carrying your own patches to. And thus make it obvious where you are
patching things and where you are doing something reproducible.

I'm not advocating you 'need' to do this, but the test did allow me to
remove lots of files which became dead. And to make sure they don't come
back...

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/issues/4736#issuecomment-142730767>.

**Comment by kargakis** [comment]
Doesn't seem like an issue anymore.
