### ISSUE TITLE
users can't predict whether an SCC will satisfy their DC

### ISSUE THREAD

**Issue by deads2k** [openshift/origin#4782]
The chain from DC to SCC is maze of twisty passages.

1. User creates deployment config
2. deployment controller creates rc
4. rc manager creates pod

In order to know if his DC is going to work, the user must be able to determine if the podspec in the DC will result in a pod that the SCC admission plugin will admit.  That requires knowledge of the SCCs available to the podspec's SA.  Right now, that information is unavailable.

We need to allow editors (and maybe viewers) enough power to figure out which SA they should use for a particular DC/RC/Pod.  That means exposing a way for them to see which SCCs a given SA has and which SCCs they have available.  Off the top of my head, this could be done with:

1. an AccessReview style check
2. with subresources on SAs and users (less desireable I think)
3. get/list on SCCs (we probably don't want this, since it exposes the list of subjects, giving attack targets)

@pweil- @smarterclayton @liggitt

**Comment by deads2k** [comment]
forgot @ironcladlou

**Comment by ironcladlou** [comment]
5. You have been eaten by a grue

**Comment by ironcladlou** [comment]
Your initial description is slightly inaccurate. The flow is:

1. User creates deployment config
2. System creates a new RC for the config (if the version is new)
3. System creates a deployer pod to scale up the RC

There's actually a stateless utility which builds the RC from a deploymentConfig which could be used by any code wishing to simulate the creation of the RC.

**Comment by deads2k** [comment]
> 5 - You have been eaten by a grue

@stevekuznetsov "older than steve" :)

**Comment by deads2k** [comment]
> Your initial description is slightly inaccurate. The flow is:

Updated

**Comment by smarterclayton** [comment]
In general, there are two parts of this.  Defaulting (seeing the effective
outcome of a pod template on submission) and understanding what the
defaults would be allowed by.  The former has been discussed upstream and
is a really concrete path (let you submit a resource and do non-mutating
operations in admission controllers).  The latter is probably a good focus
on this.

On Sep 24, 2015, at 10:00 AM, David Eads <notifications@github.com> wrote:

The chain from DC to SCC is maze of twisty passages.

   1. User creates deployment config
   2. deployment config creates deployment pod
   3. deployment pod creates rc
   4. rc creates pod

In order to know if his DC is going to work, the user must be able to
determine if the podspec in the DC will result in a pod that the SCC
admission plugin will admit. That requires knowledge of the SCCs available
to the podspec's SA. Right now, that information is unavailable.

We need to allow editors (and maybe viewers) enough power to figure out
which SA they should use for a particular DC/RC/Pod. That means exposing a
way for them to see which SCCs a given SA has and which SCCs they have
available. Off the top of my head, this could be done with:

   1. an AccessReview style check
   2. with subresources on SAs and users (less desireable I think)
   3. get/list on SCCs (we probably don't want this, since it exposes the
   list of subjects, giving attack targets)

@pweil- <https://github.com/pweil-> @smarterclayton
<https://github.com/smarterclayton> @liggitt <https://github.com/liggitt>

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/issues/4782>.

**Comment by deads2k** [comment]
Closing for trello: https://trello.com/c/YqfYqKdS/545-policy-related-endpoints-need-work
