### ISSUE TITLE
Build Labels are not namespaced

### ISSUE THREAD

**Issue by stevekuznetsov** [openshift/origin#4810]
After creating a build, if you look at the contents:
```sh
$ oc get build openldap-2 -o json
{
    "kind": "Build",
    "apiVersion": "v1",
    "metadata": {
        "name": "openldap-2",
        "namespace": "ldap",
        "selfLink": "/oapi/v1/namespaces/ldap/builds/openldap-2",
        "uid": "9c4bd9e5-63fa-11e5-94a4-54ee753e2644",
        "resourceVersion": "3674",
        "creationTimestamp": "2015-09-26T02:59:31Z",
        "labels": {
            "buildconfig": "openldap",
            "name": "openldap"
        },
        "annotations": {
            "openshift.io/build.number": "2"
        }
    },
```

Labels are not namespaced with `openshift.io`, whereas the annotations are. Should both be?
cc: @bparees @csrwng

**Comment by bparees** [comment]
yes they probably should be, though i suspect both of those labels are used by the webconsole (and maybe the CLI in describers) at this point to do grouping, so we'd have to add the new labels and not remove the old ones.

@jwforres ?

**Comment by jwforres** [comment]
Yes we are definitely using the buildconfig label in the console.  If we are going to switch anyway, should we be using a label or an annotation?

**Comment by csrwng** [comment]
I don't think we namespace labels anywhere else. The user experience would
have to change since one of the main purposes of labels is to filter
objects in the UI.

**Comment by bparees** [comment]
>  If we are going to switch anyway, should we be using a label or an annotation?

i think we still want the buildconfig to be a label since it's a grouping concept.  the name..well it was probably done as a label originally also to aid in selection/grouping, but i think that's more an artifact of us not having a selector for annotations than it making logical sense as a label.

@csrwng makes a good point about whether we namespace labels elsewhere and that's probably why we didn't do it here, but i don't know that that means we chose correctly in the other places either.

probably need to pull @smarterclayton in to assess if this is something we'd want to change.  the OCD side of me does like the idea of namespacing them.

**Comment by jwforres** [comment]
We do have some namespaced labels.  On replication controllers that are deployments we have openshift.io/deployment-config.name which if we were going to be consistent we should have openshift.io/build-config.name and @smarterclayton and I were discussing long term switching tags on images and templates to be namespaced labels, something like tag.openshift.io/tagname  so that we can actually do server side filtered queries by tag

**Comment by smarterclayton** [comment]
Namespaced labels are now ok, although Brian wanted them always to be
overrideable by an end user.  Nothing wrong with both

On Sep 28, 2015, at 3:57 PM, Ben Parees <notifications@github.com> wrote:

If we are going to switch anyway, should we be using a label or an
annotation?

i think we still want the buildconfig to be a label since it's a grouping
concept. the name..well it was probably done as a label originally also to
aid in selection/grouping, but i think that's more an artifact of us not
having a selector for annotations than it making logical sense as a label.

@csrwng <https://github.com/csrwng> makes a good point about whether we
namespace labels elsewhere and that's probably why we didn't do it here,
but i don't know that that means we chose correctly in the other places
either.

probably need to pull @smarterclayton <https://github.com/smarterclayton>
in to assess if this is something we'd want to change. the OCD side of me
does like the idea of namespacing them.

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/issues/4810#issuecomment-143750397>.

**Comment by php-coder** [comment]
Just for a history:

```
<semushin> In example we have 2 labels: "buildconfig" and "name". How I should
change them? To "openshift.io/build-config.name" and "openshift.io/name"?
<bparees1> semushin: we can't change them due to backwards compatibility requirements,
we can only add the new namespaced form.
<semushin> bparees1, ok, thanks. So I need to add 2 new labels, right?
What's their names? "openshift.io/build-config.name" and "openshift.io/name" is ok?
<bparees1> semushin: i think we should only add openshift.io/build-config.name
<bparees1> semushin: "name" is so generic that namespacing it seems silly
```

**Comment by php-coder** [comment]
Now it looks like this:

```json
        "labels": {
            "buildconfig": "ruby-sample-build",
            "name": "ruby-sample-build",
            "openshift.io/build-config.name": "ruby-sample-build",
            "template": "application-template-stibuild"
        },
```
