### ISSUE TITLE
Layout problem with tables when browser window too narrow

### ISSUE THREAD

**Issue by spadgett** [openshift/origin#4832]
See screenshot. You can scroll past the edge of the banner. @sg00dwin fixed a similar problem with the events table before.

![fullscreen_9_28_15__3_08_pm](https://cloud.githubusercontent.com/assets/1167259/10145735/e6eb3c84-65f2-11e5-8b92-a2a5cd0e7337.png)

/cc @jwforres

**Comment by spadgett** [comment]
I feel like we're trying to put too much information in these tables. For builds in particular, the type and source is usually the same for every row.

**Comment by sg00dwin** [comment]
@spadgett can you check if this is happening and that it has a table-responsive div wrapping it.

IIRC this happens when the table-responsive is missing. My environment has it so I'm not seeing the issue.

Also, in the 769 - 1100 px range we could combine columns down to 3, like we do with events.

**Comment by spadgett** [comment]
It's happening for me with the table-responsive div. (I didn't have to add the div. It was already there.)

![screen shot 2015-09-29 at 2 47 34 pm](https://cloud.githubusercontent.com/assets/1167259/10174700/2404ec48-66b9-11e5-89dd-54c688e6c65b.png)

**Comment by sg00dwin** [comment]
I see what's going on. table-responsive doesn't have the latest default styles[1]. (should have a min-height:.01% and overflow-x:auto) This was fixed in a newer version of bootstrap, which patternfly has, so we will pick it up once we've updated patternfly.

[1]https://github.com/twbs/bootstrap/blob/ab412b2404d12a3c55d1c4b798bd42ef32e80fab/dist/css/bootstrap.css#L2443
