### ISSUE TITLE
openshift-node did not restart after boot - docker daemon not yet ready

### ISSUE THREAD

**Issue by readonly** [openshift/origin#4903]
Following up on #4837, when testing cluster reboots, it happened at least once that a openshift-node failed to start because the docker daemon was not ready yet:

```
Oct  2 09:18:21 microsd6 openshift-node: I1002 09:18:21.281017    3318 start_node.go:177] Starting a node connected to https://microsd6.xx.xx.xx:8443
Oct  2 09:18:21 microsd6 openshift-node: I1002 09:18:21.547627    3318 docker.go:295] Connecting to docker on unix:///var/run/docker.sock
Oct  2 09:18:21 microsd6 openshift-node: I1002 09:18:21.548657    3318 start_node.go:263] Starting node microsd6.xx.xx.xx (v1.0.4-1-g85eea33)
Oct  2 09:18:21 microsd6 openshift-node: I1002 09:18:21.849256    3318 node.go:53] Connecting to Docker at unix:///var/run/docker.sock
Oct  2 09:18:21 microsd6 openshift-node: I1002 09:18:21.850907    3318 common.go:66] Self IP: 10.18.209.17.
Oct  2 09:18:23 microsd6 openshift-node: F1002 09:18:23.198628    3318 node.go:85] ERROR: Unable to check for Docker server version.
Oct  2 09:18:23 microsd6 openshift-node: unexpected EOF
```

A manual restart of openshift-node was necessary but fixed the problem.

Should we add `Restart=always` to `/usr/lib/systemd/system/openshift-node.service` in the `[Service]` section, too, or is there more to it?

**Comment by smarterclayton** [comment]
The node should be Restart=Always for sure (@sdodson), and it should be Wants=Docker.

**Comment by sdodson** [comment]
@smarterclayton  Node service has Restart=always in master but not in v1.0.6. It has always had Wants=Docker. https://github.com/openshift/origin/blob/master/contrib/systemd/origin-node.service

@readonly The node should actually tolerate docker being unavailable at startup because it has to restart docker in order to initialize the SDN anyway. However, I imagine Restart=always will fix what you're seeing if only through brute force. Can you modify your services and let us know?

**Comment by sdodson** [comment]
@readonly I suggest closing this. I believe everything is as it should be in the master branch.

**Comment by readonly** [comment]
We have not yet upgraded to a newer release, so we can't verify it's fixed then, but I'll close the issue and can reopen it in case it isn't.
