### ISSUE TITLE
HAProxy template has bind ports hardcoded

### ISSUE THREAD

**Issue by e-minguez** [openshift/origin#4907]
The oadm router command supports binding to other ports, but it doesn't work because of the hardcoded values in the haproxy template (bind :443, bind :80)

**Comment by e-minguez** [comment]
https://github.com/openshift/origin/blob/master/images/router/haproxy/conf/haproxy-config.template#L36
&
https://github.com/openshift/origin/blob/master/images/router/haproxy/conf/haproxy-config.template#L53

**Comment by ramr** [comment]
@e-minguez  yeah, the router expects/uses ports 80 and 443 today as that's the default for http/https traffic. So for now if you want to use custom ports, one option is to create a custom router docker image which binds to your ports and use that with the ```oadm router``` command.

Example: Assuming you want to use say 10080 and 10443 instead of 80 and 443, copy the haproxy-config.template and edit it as per your environment and create a new docker image with that config and use it. Something like: 
```
mkdir /tmp/custom/  
cd /tmp/custom  
sed 's/bind\s*\:\(80\|443\)/echo "bind :$((10000+\1))"/ge' /path/to/original/haproxy-config.template > haproxy-config.template    

cat > Dockerfile <<EOF
FROM openshift/origin-haproxy-router:latest
ADD haproxy-config.template /var/lib/haproxy/conf/
WORKDIR /var/lib/haproxy/conf
EXPOSE 10080 10443
ENV TEMPLATE_FILE=/var/lib/haproxy/conf/haproxy-config.template \\
    RELOAD_SCRIPT=/var/lib/haproxy/reload-haproxy
ENTRYPOINT ["/usr/bin/openshift-router"]
EOF

docker build -t  myrouter  ./   
#  expose router on ports 4{080,443} instead of 80+443 - the container binds to ports 10{080,443}
oadm router --replicas=1 --credentials=$KUBECONFIG  --latest-images  --images=myrouter --service-account=router --host-network=false --ports='10080:4080,10443:4443'  
```

**Comment by ramr** [comment]
Closing this issue as it has been fixed.
