### ISSUE TITLE
oadm router liveness wrong when a different port is specified

### ISSUE THREAD

**Issue by e-minguez** [openshift/origin#4908]
If you specify different ports for node and port (like --ports '80:8080') when you create a router with hostnetwork=false, the liveness probe is configured to query 8080, but it checks the pod IP, so it fails because it should check the port 80.
Modifying the dc to set the liveness probe to query port 80 works, but I think it should be done by default.

**Comment by ramr** [comment]
@e-minguez What version of OpenShift are you running? In the latest codebase, the liveness probe uses the container port. 

Example if I start the router as follows:
```oadm router --replicas=1 --credentials=$KUBECONFIG  --latest-images --service-account=router --host-network=false --ports="80:8888,443:8843"```

What that does is expose port 80 on the container on port 8888 on the host (and 443 as 8443).  And the liveness probe has 
```
   "livenessProbe": {
                            "tcpSocket": {
                                "port": 80
                            },
                            "initialDelaySeconds": 10,
                            "timeoutSeconds": 1
                        },
 ```

Which is the correct behavior.

**Comment by e-minguez** [comment]
OSE3.0.2

**Comment by ramr** [comment]
@e-minguez  Hmm, ok that's odd then - its probably something else in your env. Because the f5 router support and host-networking support went in that release and it does have the correct code (ContainerPort). 
Can you please provide the command you used to start the router:  ```oadm router ...``` and the output of the generated deployment config ```oc get dc router -o json```   (if you used a custom named router, then replace the DC name ```router```  with that name in the ```oc get``` command).  That will help determine what the issue is.  Thx

**Comment by e-minguez** [comment]
I tried again from scratch and it works, so excuse me for opening the issue and sorry to bother you with this.
Thanks.

**Comment by ramr** [comment]
No worries. Cool - glad its working for you.
