### ISSUE TITLE
Should reference the eclipse IDE on the next steps page

### ISSUE THREAD

**Issue by jwforres** [openshift/origin#4914]

**Comment by jwforres** [comment]
@sspeiche opinion on this?

**Comment by sspeiche** [comment]
Seems like a reasonable/helpful thing to do. I do wonder though, if we just want a general link-to page that isn't part of the product for "other clients".

Though I'd check with @jcantrill It seems like a lot of the links one the Eclipse plugin have a lot of references to v2, which I think should be pushed off to another page and linked to as "other versions" http://tools.jboss.org/features/openshift.html#openshift-3

**Comment by jwforres** [comment]
Yeah i like that idea better

@ahardin-rh @adellape do we have anything like that in the docs, a page that lists our other clients you can use against openshift, like the jboss tools.

**Comment by jwforres** [comment]
@jcantrill see question above ^ do we not have any references in the documentation to the JBT?

**Comment by adellape** [comment]
@jwforres We had this small page at one point:

https://github.com/openshift/openshift-docs/blob/master/dev_guide/jboss_tools.adoc

But it was pulled from the build before 3.0 GA'd (https://github.com/openshift/openshift-docs/issues/534) since all the JBoss Tools docs we linked to were still only for OSE v2 at the time. We could add our page back now though.

**Comment by jwforres** [comment]
/assign @spadgett

Not sure we've got room to add more stuff at this point with it in the modal

**Comment by spadgett** [comment]
Since we've even removed references to the CLI from next steps as recommended by @ncameronbritt, I think we can just close this. Any objection @jwforres?
