### ISSUE TITLE
"--env" param does not work on oc new-app <template>

### ISSUE THREAD

**Issue by jorgemoralespou** [openshift/origin#4967]
While creating an app from a template, I want to set up additional envs to the containers and I use:

```
 oc new-app --template=<Template> -p APPLICATION_NAME=test  -e MYKEY=MYVALUE,MYKEY2=MYVALUE2
```

I've tried with multiple variations of the command (--env, no specifying -e or --env as stated in another issue).

**Comment by nak3** [comment]
@jorgemoralespou 
Please use `--param` option instead of `--env` for the `oc new-app --template=<template>`.
- https://github.com/openshift/origin/blob/master/docs/generated/oc_by_example_content.adoc#oc-new-app

**Comment by nak3** [comment]
Ah, sorry I misunderstood your question. You want to set up additional envs to the containers.

**Comment by bparees** [comment]
Reasons we didn't do this last time it was discussed:

1) we'd have to add distinct -e flags for "add this to buildconfigs" vs "add this to deploymentconfigs" because users don't necessarily want the environment variable added to both all the time.
2) new-app would have to either edit the template before submitting it for processing, or edit the results of the processing (the DC and BC objects) to add the env before submitting them for creation, which doesn't feel like something new-app should do.
3) template authors should be defining the env experience via parameters.  if a user of the template finds the template is lacking env configuration that they want, they can clone the template and add it themselves to a new version of the template.

@smarterclayton pretty sure you were on the side of not doing this last time.  @jhadvig can you locate/link the discussion from your original PR where this was debated?

**Comment by csrwng** [comment]
4) 'oc env' can be used after the fact to add variables if needed.

**Comment by jorgemoralespou** [comment]
@bparees 
I can understand 1. I can not understand 2 as a user stand-point, as it seems that a justification of not providing a feature is that the client is heavy weight, but somethings should not be done in the heavyweight client. We could argue on 3, but ok, fair enough.
@csrwng 4 triggers deployments everytime there is a Change in the DC to add an env, so adding this envs would trigger a new deployment :-( It seems an empty array for Triggers can override the behavior of adding a CCT to a DC without a trigger defined. I yet have to test it.

**Comment by smarterclayton** [comment]
1. We will not do - build configs don't get environment variables in new-app
2. We should post process the environment after process is invoked
3. I believe the argument that a deployer should be able to override the
environment is compelling at new-app time.

So we should allow command line passed env to override templates passed to
new-app in a similar way as env and have the same outcome.

**Comment by csrwng** [comment]
> So we should allow command line passed env to override templates passed to
> new-app in a similar way as env and have the same outcome.

Would the env argument apply only to DC's or also to any stand-alone RC's & pods? Could it also apply to other type of resources?

**Comment by smarterclayton** [comment]
It would apply to anything that "oc env" mutates.

**Comment by smarterclayton** [comment]
But we can explicitly exclude build configs and builds for the reasons
discussed before.  I believe oc env is targeted at pod template.

**Comment by kargakis** [comment]
Should be fixed now I think, please reopen otherwise

**Comment by jorgemoralespou** [comment]
Woooohooooo
