### ISSUE TITLE
Most oc command responses should use the new cmdutil.PrintSuccess

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#5059]
In most of the cases where we print object type / name from the CLI, we should be using `cmdutil.PrintSuccess`.  This includes the following:

* new-app / new-build
* start-build / cancel-build
* all core commands we reuse from upstream
* oadm commands

Commands which do not support `-o name` need to be reviewed before being converted - we may need to add `-o` support, or skip the command.

This *must* be fixed for 1.1.

**Comment by fabianofranz** [comment]
Other than places where `-o name` is not yet supported but could (e.g. `start-build` and `cancel-build`) there are not many changes to be made. Most places already print correctly by the use of printers or `NewPrintNameOrErrorAfter`. @smarterclayton would you like merge https://github.com/openshift/origin/pull/5438 for now but keep this issue with a lower priority, so that we can get back to it after the release?

**Comment by jwforres** [comment]
Remaining issues are not P1

**Comment by smarterclayton** [comment]
@stevekuznetsov didn't you just fix this?

**Comment by stevekuznetsov** [comment]
@smarterclayton in progress https://github.com/openshift/origin/pull/5334
