### ISSUE TITLE
new-build / new-app should report error if input and output image stream tags are identical

### ISSUE THREAD

**Issue by rhcarvalho** [openshift/origin#5072]
if we generate a build config and the source tag and the destination tag are identical we should report an error (if the user hasn't specified --to https://github.com/openshift/origin/issues/4980)

@smarterclayton FYI

**Comment by rhcarvalho** [comment]
Example:

```
$ oc new-build -D $'FROM centos\nRUN yum install -y httpd'
```

The input and the output are both `centos:latest`. Expected:

```
$ oc new-build -D $'FROM centos\nRUN yum install -y httpd'
error: the input and output image stream tags are identical, please specify a
different output tag with --to.
```

**Comment by rhcarvalho** [comment]
@smarterclayton is it an error to specify `--to` to a value that will cause the circular conflict?

**Comment by smarterclayton** [comment]
No, it is not.  We should warn you, but it is not an error to take user
input like that (if it is an error, it should be something enforced on the
server, not in a client).

On Mon, Oct 12, 2015 at 10:17 AM, Rodolfo Carvalho <notifications@github.com

**Comment by mfojtik** [comment]
@smarterclayton we don't do any pre-validation in that command and I think when you specify something that might cause circular conflict we should error out instead of warning (if you specify something like that there is 80% chance you're doing something wrong and we should stop you).

Also the problem @rhcarvalho was showing me is that in code we don't have a good way to give warnings to users (stderr writer) and having this will make the NewBuildPipeline() more complex...

So I think we should error for now and take this into account when we will be doing general refactoring of new-app (post 3.1?)

**Comment by smarterclayton** [comment]
We can't error because there is no way for the user to fix the problem -
they're just broken without --to.

If we need conditional warnings, return them as a new return value.

On Oct 14, 2015, at 11:30 AM, Michal Fojtik <notifications@github.com>
wrote:

@smarterclayton <https://github.com/smarterclayton> we don't do any
pre-validation in that command and I think when you specify something that
might cause circular conflict we should error out instead of warning (if
you specify something like that there is 80% chance you're doing something
wrong and we should stop you).

Also the problem @rhcarvalho <https://github.com/rhcarvalho> was showing me
is that in code we don't have a good way to give warnings to users (stderr
writer) and having this will make the NewBuildPipeline() more complex...

So I think we should error for now and take this into account when we will
be doing general refactoring of new-app (post 3.1?)

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/issues/5072#issuecomment-148086778>.
