### ISSUE TITLE
Editing a build config Git repo doesn't start a new build

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#5117]
Even though a build config config change trigger was specified

```
$ oc new-build openshift/nodejs-010-centos7~https://bitbucket.com/user/nodejs-app
# wait for build to fail
$ oc edit bc/nodejs-app
# change git to https://github.com/openshift/nodejs-ex.git
# save and exit
# ... wait
# ... still no build
# resync loop runs, build created
```

**Comment by smarterclayton** [comment]
This is a tracking issue for the fact that the build is hard to understand

**Comment by mfojtik** [comment]
@smarterclayton so the build starts eventually but you have to wait a long time for controller to catch up?

**Comment by smarterclayton** [comment]
Maybe it didn't start.  I could be confused about which # i had.

**Comment by bparees** [comment]
Can you elaborate? Editing a BC never starts a new build, even with a
config change trigger defined, but we have a trello card for that so we
don't need an issue for it.  If you aren't referring to editing the BC I'm
not clear on what "editing a BC git repo" means.

If the issue is that you couldn't tell if a new build was created or not,
can you update this issue with
1) what information you did get?
2) what information you expected/wanted to get?

We show you timestamps for builds so it should be easy to know if a build
just got created.

Ben Parees | OpenShift
On Oct 14, 2015 2:20 PM, "Clayton Coleman" <notifications@github.com> wrote:

Maybe it didn't start. I could be confused about which # i had.

On Wed, Oct 14, 2015 at 10:46 AM, Michal Fojtik <notifications@github.com>
wrote:

> @smarterclayton <https://github.com/smarterclayton> so the build starts

> eventually but you have to wait a long time for controller to catch up?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openshift/origin/issues/5117#issuecomment-148072704>.

>

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/issues/5117#issuecomment-148143723>.

**Comment by bparees** [comment]
@smarterclayton bump

**Comment by smarterclayton** [comment]
I haven't seen this recently.

**Comment by bparees** [comment]
@smarterclayton i'd still like to understand what it was you saw, per my questions above?
