### ISSUE TITLE
Change oadm router stats port parameter to an admin configuration parameter to expose haproxy stats

### ISSUE THREAD

**Issue by ramr** [openshift/origin#5166]
Based on monitor-uri changes and a follow up to #5151  - as per comments from @pweil- and @liggitt 
Change "stats port" to "admin port", and key exposing stats on something other than port > 0 (--enable-stats=false, so we can continue defaulting pw/username) and ensure backward compatibility for stats-port set to 0.

**Comment by knobunc** [comment]
So @liggitt @pweil @smarterclayton: We want to leave the existing --stats-port argument to oadm router, but deprecate it?  We add --admin-port to replace it, support both for a while?  Then if --stats-port is 0, that implied --admin-port 1936 with --enable-stats=false?  Otherwise, if --stats-port is not set, use either the explicit --admin-port or the default of 1936, but set --enable-stats=true as a default?

**Comment by pweil-** [comment]
Based on some previous conversation (https://github.com/openshift/origin/pull/5151#issuecomment-149661323) I think the use cases are:

1.  --stats-port set > 0: use stats port and expose stats (healthz and stats may not be on the same listener)
1.  --stats-port unset: default to 1936 and expose stats (healthz and stats are on the same listener)
1.  --stats-port = 0: do not expose stats

And then always expose the healthz uri on 1936 so we have a consistent mechanism regardless of other configuration.  I think changing where we expose the healthz check is nice but may lead to debugging issues later on.

@ramr @smarterclayton thoughts on always exposing healthz on 1936 but allowing stats to be configurable?

**Comment by smarterclayton** [comment]
If stats-port happens to be the healthz port, that's fine.  I don't think
we need two ports (one for stats, one for health) as long as a caller
pinging /healthz doesn't have to auth.

**Comment by pweil-** [comment]
> I don't think
> we need two ports (one for stats, one for health) as long as a caller
> pinging /healthz doesn't have to auth.

Fair enough, I was shooting for something more stable that we could always ping in case of troubleshooting customer installations but I can see the point of not taking up more ports than necessary

**Comment by knobunc** [comment]
So, would we add a separate admin-port?  The way I read the bug and
previous discussion, I thought we were intending to obsolete --stats-port
in favor of --admin-port.

-ben

**Comment by smarterclayton** [comment]
Do we have to obsolete stats-port?  We will almost always have to have
stats-port running to provide info for admins.  As long as we can convince
ourselves its secure I don't see it being disabled very often.

**Comment by pweil-** [comment]
We just need to make it clear that even if you set it to 0 we're going to expose the health check on that port rather than not exposing the port at all.  We just won't enable the stats uri.

@knobunc could just be a simple change to the template to use either StatsPort if > 0 or 1936 for the existing listener and still key on StatsPort > 0 to add the stats exposure.

**Comment by knobunc** [comment]
So:
1. Keep the existing --stats-port parameter (i.e. don't create an --admin-port parameter)
2. Change the docs to state that the health check is always on, even if stats are disabled
3. Change the behavior to make the health check be enabled, and if stats-port is 0, use 1936 for healthz

Note:
1. This means that if you disable stats by setting to 0, there is no way to control the port that the health check is on

**Comment by smarterclayton** [comment]
Yes

**Comment by ramr** [comment]
Completed via #6030 and #6032
