### ISSUE TITLE
prune deployments should set annotations

### ISSUE THREAD

**Issue by kargakis** [openshift/origin#5211]
After https://github.com/openshift/origin/issues/5163 gets resolved (hopefully soon) and we are going to support viewing the logs from older deployments, there will be two cases where trying to get the logs from an older deployment may be inaccurate: 

1) when the older deployment the user is trying to view is manually deleted (imho should not happen at all: https://github.com/openshift/origin/issues/2809#issuecomment-148664133)
2) after deployment pruning
```sh
$ oc get dc/mydc -o go-template={{.status.latestVersion}}
4
# admin prunes
$ oadm prune deployments
# user tries to retrieve older deployment logs; the deployer pod is missing so we consider the deployment successful
$ oc logs dc/mydc --version=2
Deployment mydc-2 successfully made active, no logs to show.
```

How about `prune deployments` setting something like `openshift.io/pruned` or even better add the exact versions of pruned deployments (say `openshift.io/pruned-{1..3}`) in the annotations of the config (the latest though would need to interplay nice with `oc rollback`)? Then we could return an appropriate message when a user would try to view a pruned deployment.

@ironcladlou @smarterclayton @deads2k @liggitt

**Comment by ironcladlou** [comment]
So this would be accumulating kind of an audit history of RCs on the deploymentConfig. I'm not sure if that's a path we want to go down. Doesn't seem much different than just keeping all the old RC states on the DC other than a modest amount of extra storage. Conceptually I don't see much difference.

If the user tries to get logs for a deployment which doesn't exist (because it never did or was pruned), is it not enough to just tell the user it doesn't exist? If the version is less than known existing records, it seems reasonable to assume that the RC may have existed at one time in the past, which we could offer in explanation. I don't like the idea of accumulating some subset of history on the DC just so we can tell the user that an RC definitely existed in the past. Either way they can't act: they don't have the old RC. Plus, I thought there was parallel work to cover etcd resource history generally...

It's possible I'm misunderstanding what problem this solves.

**Comment by kargakis** [comment]
> If the user tries to get logs for a deployment which doesn't exist (because it never did or was pruned), is it not enough to just tell the user it doesn't exist? 

Hm, I was thinking that we had to reason about **every** deployment for a config but I guess you are right about 

> Either way they can't act

I guess this is it for this issue.
