### ISSUE TITLE
Enviroment variables creation from buildconfig in dockerstrategy

### ISSUE THREAD

**Issue by charliemaiors** [openshift/origin#5241]
Hi I'm trying to create an enviroment variable in my buid config using dockerstrategy, but after the build if I run docker run <my-output-image> env the variable is not in the list of enviroment variables

{
  "kind":"BuildConfig",
  "apiVersion":"v1",
  "metadata":{
    "name":"mybuildconfig-bc",
    "selfLink":"",
    "resourceVersion":""
  },
  "spec":{
    "triggers":[
    {
      "type":"ConfigChange"
    }
  ],
  "source":{
    "type":"Git",
    "git":{
      "uri":"git@myprivaterepo/docker-repo.git"},
      "sourceSecret":{
        "name":"mysecret"
      }
  },
  "strategy":{
     "type":"Docker","dockerStrategy":{
       "env":[
       {
         "name":"MY_ENV_VAR",
         "value":"ciaoPippo"
       }
       ]
  }
},
 "output":{
    "to":{
      "kind":"DockerImage",
      "name":"172.30.87.129:5000/myproject/mybuildconfig"
    }
  },"resources":{}
  }
}

**Comment by rhcarvalho** [comment]
@charliemaiors what version of the server/client are you using?

**Comment by charliemaiors** [comment]
I'm using binaries version 1.0.5 for server, rest API to send the buildconfig

**Comment by rhcarvalho** [comment]
Also, how do you start the server? (--latest-images flag would make a difference here).
Most likely your `openshift/origin-docker-builder` is old and does not support that functionality (which is recent and was not included in any release yet if I'm not wrong).

**Comment by charliemaiors** [comment]
openshift start --master-config=openshift.local.config/master/master-config.yaml --node-config=openshift.local.config/node-openshift/node-config.yaml &> openshift.log &

This is my start command (I've configured a different identity provider and I've to include the configuration files)

**Comment by rhcarvalho** [comment]
@charliemaiors there are two things you can try:

1. Start the server with --latest-images.

  This will make OpenShift use the `:latest` tag for builder images, registry, etc, instead of the version that matches your release. IOW, without that flag you'll be using `openshift/origin-docker-builder:v1.0.5`, prior to that feature was implemented.

2. Manually pull and re-tag `openshift/origin-docker-builder`.

  If you don't want to use the --latest-images flag, that will affect images other than the docker builder, you can manually re-tag your image so that you start openshit without --latest-images, but use the most recent docker builder. No warranties here.
  ```
$ docker pull openshift/origin-docker-builder:latest
$ docker tag openshift/origin-docker-builder:latest openshift/origin-docker-builder:v1.0.5
```

The next release will include setting env for docker builds out of the box.

**Comment by rhcarvalho** [comment]
@charliemaiors if the solutions I proposed work for you, could you please close this issue?
Seems that it's just a matter of using an unreleased feature.

**Comment by charliemaiors** [comment]
I've tested the first solution and doesn't work, but the second work
perfectly. Thanks.

2015-10-21 17:15 GMT+02:00 Rodolfo Carvalho <notifications@github.com>:

> @charliemaiors <https://github.com/charliemaiors> if the solutions I
> proposed work for you, could you please close this issue?
> Seems that it's just a matter of using an unreleased feature.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openshift/origin/issues/5241#issuecomment-149928395>.
>



-- 
Pasquale Carlo Maiorano Picone
