### ISSUE TITLE
ImageStreamTag possibly should not return 404 when a status exists and the image does not

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#5391]
An image stream that has only referential (but no import) tags currently returns 404 when you try to look up the tag

```
  apiVersion: v1
  kind: ImageStream
  metadata:
    creationTimestamp: 2015-10-26T01:41:23Z
    name: installable
    namespace: default
    resourceVersion: "303"
    selfLink: /oapi/v1/namespaces/default/imagestreams/installable
    uid: aa34c0dd-7b82-11e5-8dcb-080027c5bfa9
  spec:
    tags:
    - annotations:
        io.openshift.generate.job: "true"
      from:
        kind: DockerImage
        name: openshift/origin:v1.0.6
      name: installable
    - from:
        kind: ImageStreamTag
        name: installable:installable
      name: latest
  status:
    dockerImageRepository: ""
    tags:
    - items:
      - created: 2015-10-26T01:41:23Z
        dockerImageReference: openshift/origin:v1.0.6
        image: ""
      tag: installable
    - items:
      - created: 2015-10-26T01:41:23Z
        dockerImageReference: openshift/origin:v1.0.6
        image: ""
      tag: latest
```

```
$ oc get istag/installable:latest
Error from server: imageStreamTag "installable:latest" not found
```

I'm not sure it's correct to return a 404 for a tag that clearly exists.  We don't have a way to indicate the image has no metadata today, but we probably should.

**Comment by smarterclayton** [comment]
@miminar @ncdc @pweil-

**Comment by pweil-** [comment]
@soltysh

**Comment by miminar** [comment]
For image pruning, we are going to extend `imageapi.Image` for `Finalizers` and `Status` saying whether an image is about to be deleted. We could extend the `Status` to indicate that metadata are being imported (e.g. `Status == Importing`). Although it's a redundant information because such an image will have `Name` and `DockerImageMetadata` empty.

**Comment by smarterclayton** [comment]
We don't know what the images digest is until we import it, so there's no
place to put in Importing on an Image.

**Comment by soltysh** [comment]
Since we're returning [ImageStreamTag](https://github.com/openshift/origin/blob/master/pkg/image/api/types.go#L126), I'd suggest returning ist information but with empty Image field, maybe eventually filled in DockerImageReference pointing to exact image. Which would then mean there's no information about that particular image. How's that?
