### ISSUE TITLE
Unable to create recycler pod

### ISSUE THREAD

**Issue by pweil-** [openshift/origin#5399]
From @ebalsumgo: 

i seem to be getting: Message: %!d(string=Recycling error: Unexpected error creating a pod to scrub volume :  Pod "pv-scrubber-hostpath-" is forbidden: unable to validate against any security context constraint: [provider restricted: .spec.containers[0].securityContext.VolumeMounts: invalid value 'vol', Details: Host Volumes are not allowed to be used])

i am on ose 3.0.2 and claytonc helped me with a permissions bug on friday. so could it be that its an already fixed bug?

@markturansky it looks like the controller creating the recycler pod does not have permissions granted to create a pod with host mounts.  We should have an identity that allows this if it is necessary similar to how build pods, routers, etc have.

cc @liggitt

**Comment by ebalsumgo** [comment]
I was trying to deploy the built in jenkins-persistent template btw.

**Comment by liggitt** [comment]
@markturansky is it expected the recycler pod will use a host mount?

**Comment by ebalsumgo** [comment]
Oh yeah another note/info on this. My PVs are setup as follows:
They are all HostPath volumes that live on a NFS mount which is mounted across my cluster.

**Comment by liggitt** [comment]
@pweil- since persistent volumes can use host mounts, recycler pods also need to be able to use them to clean up. I think we need the following:
1. A service account for the recycler controller
2. A role for the recycler controller
3. An SCC which only grants host mounts (not all of privileged), with the recycler controller service account in that SCC by default

**Comment by markturansky** [comment]
@pweil- @liggitt the recycler does *not* expect to use a host mount.  NFS is the sole supported recycler today.  It uses an NFS volume, not HostPath, when recycling.

Using HostPath in a PV triggers the recycler and mounts that HostPath, but that is for local dev/testing only and requires editing the SCC to allow HostPath.

Otherwise, there is no condition under which we support local storage using HostPath and therefore have no expectations of the recycler working for HostPath.

**Comment by pweil-** [comment]
Should this be something that is flaggable and turned off by default then?  Is it documented?  What if someone is using a recycler in production and also using host mounts (which appears to be the case here)?

**Comment by liggitt** [comment]
@markturansky, there's a disconnect here, then:

> They are all HostPath volumes that live on a NFS mount which is mounted across my cluster.

If the system allows this, and the mounts work as intended, but the recycler pod died, we need to resolve that.

**Comment by ebalsumgo** [comment]
@markturansky I actually have not done anything on the SCC end to do this, plus the only reason I went down this path is because @smarterclayton and @liggitt and yourself told me it should work. In our env, the expectation of NFS volumes for everyone that wants PV is unacceptable, which is why I am trying to do it this way, aka, export a volume to my entire cluster and let my server handle quota while exposing all the PVs i want and need as HostPaths.

**Comment by markturansky** [comment]
@ebalsumgo I remember our IRC chat and I believe you said you have a single big NFS mount on all the hosts, correct?  If so, then you can, strictly speaking, use HostPath.  HP isn't supported for local storage, but you've got remote storage and you're only using HP to point to a dir.

But then we run into security issues and we now require @liggitt's solution w/ a service account that is allowed to make HostPath volumes.  If we allow recyclers for HostPath, we allow HostPath as a PV, which was never the intent (even though it would work with nodeSelector's on pods).

I can add the new service account, if that is what is desired.  I'd like to know if that's what we *want* to do, though.

**Comment by ebalsumgo** [comment]
@markturansky right, which is what I have, single big NFS mount with subdirs exposed at PVs, the server handles the quota using netapp qtrees. I dont see how else to expose the said mount as chunks other than using HostPath.

**Comment by markturansky** [comment]
@smarterclayton @liggitt @pweil- @wattsteve @childsb  this issue isn't a bug, per se, and the question is whether or not we create a service account that allows HostPath recyclers and, if so, when it fits into the release schedule.

**Comment by pweil-** [comment]
If the system let's me get into a state where infrastructure no longer works I'd consider it a p1/p0 bug.

**Comment by markturansky** [comment]
Implementing the service account per @liggitt's suggestion would solve the immediate need of creating recyclers for HostPath PVs.  See https://github.com/openshift/origin/issues/3286

**Comment by liggitt** [comment]
well, it would give us a way to do it... it's slightly scary to give the recycler service account host mount access...

**Comment by markturansky** [comment]
any pod today that uses HostPath must be explicitly allowed to do so via scc, correct?

The admin granting HostPath for a pod would be the same person making the PV requiring that rights.  The recycler pod is created, on behalf on the admin.  Admin is also the person overriding the default recycler pod via configuration.  Service account kills two birds with one stone.

**Comment by markturansky** [comment]
Service account added: https://github.com/openshift/origin/pull/5465

**Comment by markturansky** [comment]
The service account PR merged yesterday but the new security functionality seems to break the recycler in some situations.

**Comment by liggitt** [comment]
@markturansky are you referring to the FSGroup/SupplementalGroup bits? I think your issue was that a PV got mounted with one uid/gid, and the recycler pod ran with another uid/gid that couldn't delete the files from the PV. @pmorie, what would you recommend we do for a recycler pod that needs to be able to remove files from any PV?

**Comment by liggitt** [comment]
also, I would resolve this issue, and open a new one for the recycler pod uid/gid issue

**Comment by markturansky** [comment]
@liggitt yes, that is exactly the issue.  The writer of the data was one UID, the recycler is running as another.  Security works as expected.  Permission denied for the non-writer UID.
