### ISSUE TITLE
Build status message doesn't look nice, sentence not capitalized

### ISSUE THREAD

**Issue by jwforres** [openshift/origin#5422]
Seeing this status message on builds:

"the referenced output image stream example-project/origin-ruby-sample does not exist"

UIs should be able to take what we get from the API and render it as is.  At least need to capitalize the first letter and if there are multiple sentences include punctuation.

**Comment by jwforres** [comment]
@bparees

**Comment by jwforres** [comment]
In the CLI this message is prefixed in the event with a generic message:
```
Build example-project/ruby-sample-build-3 has error: the referenced output image stream example-project/origin-ruby-sample does not exist
```

The first section seems redundant when you already know you are looking at ruby-sample-build-3, since the event in the api has name and kind associated with it, and when you are looking at it from describe you chose to see that specific build.

**Comment by bparees** [comment]
> UIs should be able to take what we get from the API and render it as is. At least need to capitalize the first letter and if there are multiple sentences include punctuation.

pretty sure @smarterclayton has been enforcing that we do NOT capitalize error messages, but if i'm wrong i'd be more than happy to change them all.

**Comment by jwforres** [comment]
the status messages on deployment configs were, so we are definitely
inconsistent either way

**Comment by smarterclayton** [comment]
This isn't an error message per se.  If the UI has to assume the thing is intended to be shown to the user, and sometimes that message is longer than a single phrase (i.e. if it would be clearer to use sentences instead of an indefinite number of semicolons), it's probably best for the UI to assume that a sentence has been returned.  I guess the UIs could come up with some magic heuristic - but it's probably better to create a sentence at the API level when creating these for maximum legibility to all generic clients.

**Comment by smarterclayton** [comment]
Error messages should never be capitalized (fmt.Errorf).

This is transforming from a Go error to an API string Message field.
During the transformation we need to assert the new rules.  The new rules
should probably be "Our messages are sentences" in both builds and
deployment config status.

On Tue, Oct 27, 2015 at 1:17 PM, Jessica Forrester <notifications@github.com

**Comment by smarterclayton** [comment]
We should change deployment configs to use this same code @ironcladlou
