### ISSUE TITLE
Current memory usage on metrics tab has different values for half hour vs. one week

### ISSUE THREAD

**Issue by spadgett** [openshift/origin#5471]
The problem is the "current" usage is the average for the last bucket we get back from Hawkular. We always request the same number of buckets (60), so the bucket duration is much different for one week vs. a half hour. This is confusing, however, because the current usage value shouldn't change.

/cc @jwforres

**Comment by mwringe** [comment]
There was a jira for this added to Hawkular Metrics to support this. It should be in the version used for origin-metrics, but may be a bit before its in the enterprise images: https://issues.jboss.org/browse/HWKMETRICS-334

Instead of using the last  bucketed data, it should always have been possible to fetch the last few minutes of data and then used that as the current value.

**Comment by spadgett** [comment]
@mwringe Matt, thanks. I'll look at that.

We can't reliably get the last few minutes of data. If the client's clock is ahead of the server, it comes back empty.

**Comment by jwforres** [comment]
@spadgett are we blocked on this in some way?

**Comment by spadgett** [comment]
> are we blocked on this in some way?

I don't think so
