### ISSUE TITLE
skewed clients destroy resources

### ISSUE THREAD

**Issue by deads2k** [openshift/origin#5505]
OId clients strip unknown fields from current serializations because their local copies are old.  This results in stripping fields set by newer clients and accepted by the server.  This is known limitation, but its going to be really annoying.

For example:  David and Kristen are working in the same project.  The master is updated to the latest level, David upgrades his client, and starts using new `v1` fields like `podSecurityContext` inside his deploymentconfigs.

Kristen comes along with an older client and runs `oc edit` against a deploymentconfig that David updated.  Suddenly, `podSecurityContext` is gone, the next deployment fails, and David is very unhappy.

@smarterclayton is there already an issue for this?

**Comment by smarterclayton** [comment]
On edit?  Probably not.

On Oct 29, 2015, at 5:14 PM, David Eads <notifications@github.com> wrote:

OId clients strip unknown fields from current serializations because their
local copies are old. This results in stripping fields set by newer clients
and accepted by the server. This is known limitation, but its going to be
really annoying.

For example: David and Kristen are working in the same project. The master
is updated to the latest level, David upgrades his client, and starts using
new v1 fields like podSecurityContext inside his deploymentconfigs.

Kristen comes along with an older client and runs oc edit against a
deploymentconfig that David updated. Suddenly, podSecurityContext is gone,
the next deployment fails, and David is very unhappy.

@smarterclayton <https://github.com/smarterclayton> is there already an
issue for this?

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/issues/5505>.

**Comment by deads2k** [comment]
> On edit?  Probably not.

I meant more along the lines of, "do we have a plan to avoid stripping unknown fields?"

**Comment by smarterclayton** [comment]
Convince someone to build a better JSON parser in Go?

**Comment by deads2k** [comment]
@DirectXMan12 was messing around with the yaml AST, right?

**Comment by smarterclayton** [comment]
YAML has the same "behavior"
