### ISSUE TITLE
Need a diagnostic for the following node checks

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#5757]
- Containerized install has access to the various folders and permissions it needs
  - pid=host
  - net=host
  - /sys, a few others
- Image can be pushed to the integrated registry from a node
  - Lots of reasons this can fail, such as:
    - Docker not having --insecure registry
    - Registry is busted
    - No network connectivity from node to pods

Diagnostics needs to be ++ more awesome, I want to tell someone to run it.

Also, we should promote diagnostics into oc and oadm.

**Comment by smarterclayton** [comment]
Need a DNS resolution diagnostic

**Comment by smarterclayton** [comment]
@deads2k @liggitt @danmcp I want diagnostics to be the answer to every problem an admin hits - "you are having a problem, send us diagnostics" and I'd like by 3.1.1 or 2 to be able to do that.

**Comment by smarterclayton** [comment]
* A running container should be able to access its service account token

**Comment by sosiouxme** [comment]
@smarterclayton I'd certainly like diagnostics to do as much as possible. Regarding promoting to `oc` @deads2k contends that everything specific to a project (as opposed to the whole cluster) should be reported via `oc status` or similar mechanism and diagnostics won't be too useful to end users. I'm of two minds about it as it would be nice not to have a bunch of different commands to run in order to figure out what's going on; on the other hand, "status" is a different mindset from "what's going wrong?" so I could maybe make the case for having `oc diagnostics` for telling you that e.g. you have duplicate routes, your service has no endpoints, your builds are failing due to registry problems, your RC is scaled to 0 because the deployer failed -- things that take a little digging and/or might be too much detail if you just want to see "what's there?"

Some of the things you've mentioned would involve having diagnostics run a diagnostics pod, which shouldn't be hard to arrange, since all you really need is a container with the openshift binary.

**Comment by sosiouxme** [comment]
https://github.com/openshift/origin/pull/6397 implements some of this. It checks that a pod's service account token authenticates to master and registry (doesn't test registry push though). It tests that the nameservers in `/etc/resolv.conf` are responsive and that the first knows about cluster.local domains, as well as checking for search domains that are wildcards. Being able to assess the situation from within a pod should open up more things to diagnose.

**Comment by smarterclayton** [comment]
Awesome
