### ISSUE TITLE
How do we approach translation (i18n) of openshift

### ISSUE THREAD

**Issue by jwforres** [openshift/origin#5831]
See https://github.com/openshift/origin/pull/4332#issuecomment-155479889  for some background.

**Comment by tagoh** [comment]
Maybe good to follow up here.

> 1) This approach is using the strings themselves as the message ID for translation, what happens if you have the same word in english but intended for two different contexts that may need two different translations in certain languages? We should probably be using an actual identifier.

angular-gettext supports "contexts". see https://github.com/rubenv/angular-gettext/issues/223#issuecomment-145459238 for what I got from upstream when I have same question earlier.
Honestly speaking, I don't mind either but IMO using an actual identifier like the way angular-translate and so on takes may introduces the poor outlook during the development cycle, particularly for an UI designer. or need extra toolset to replace translatable strings to identifiers, which needs an extra cost to do and has a risk not replaced as expected perhaps.

> 2) The web console is made up of UI bits coming from a number of shared UI repositories, each of which would have to be independently translated. We need to agree amongst the various projects contributing angular components what angular translation tool we are going to use. There are at least three other repos right now besides this one that would need translation.

How can we negotiate them for this? I've sent PR for some components already though.

> 3) We also have all of the templates the user can use to create content in their project. Those templates contain names and descriptions that the UI exposes to end users. https://github.com/openshift/openshift-ansible/tree/master/roles/openshift_examples/files/examples

We may need to take another approach for this indeed.

> 4) The API returns status messages, error messages, phases, and other various things that we show directly to end users.

Well, I'm not sure what is a concern though, frankly speaking there are no problem if targeted strings to be translated is in the translation database. just need to ensure if those are available in PO. it could be applied to the json things as well.

> We need to have a larger discussion about the translation approach across the project stack, and need to approve a proposal before implementing something. ( https://github.com/openshift/origin/tree/master/docs/proposals ) Once we add the framework and the English translation we will have to maintain that for every new feature we add moving forward. It will add overhead to the project and slow it down. We need to make sure we are taking the correct approach before we agree to take on that overhead.
@jwforres

Aha. Thank you for the explanation. apparently I'm not well understanding the process to propose something. I need to learn about it.
I guess this issue is the place to discuss about the translation approach. so hope we have constructive discussion soon.

**Comment by jwforres** [comment]
cc'ing some folks @spadgett @liggitt @smarterclayton @bparees @stefwalter

**Comment by stefwalter** [comment]
The translation approach that I've seen openshift is in the right direction. My comments would be:

 * The source for translations needs to be pluggable. We have Cockpit loading po JSON files for a long time now (even though our i18n stuff isn't perfect), we probably want to keep the loading/delivery parts.
 * As @tagoh said contexts are the accepted solution for the same string meaning different things. We just have to get our contexts to line up between projects.
 * It needs to be dead easy for translation tools to scan for text to be translated, and it cannot be limited to a single set of tools. And this includes HTML attributes. That causes one of the problems that we see today in the Cockpit i18n infrastructure.
 * We need to come up with a standard place to push translations. We use Zanata right now.

CC @petervo

**Comment by juhp** [comment]
Should we create a document at https://github.com/openshift/origin/tree/master/docs/proposals to cover this proposal?

Is it possible to increase the priority for this?  There is real demand for this for Japanese, Korean and Chinese users.

**Comment by vanloswang** [comment]
How about the progress now? Is there some design details for origin i18n?

**Comment by jwforres** [comment]
Some progress happening in upstream kubectl for the CLI https://github.com/kubernetes/kubernetes/pull/36802

**Comment by stefwalter** [comment]
For reference, in Cockpit we're using angular-gettext now for translating angular-code. We've found it easy to transform PO files to the angular-gettext require format, as well as share extraction tooling.

**Comment by vanloswang** [comment]
@jwforres The translation work done in Cockpit project is a good example.

**Comment by vanloswang** [comment]
@jwforres @stefwalter @tagoh @juhp @bparees @danmcp Kubernetes dashboard has already released v1.6.1 with English, Janpanese and Chinese. Could we take the advantage of it?

**Comment by xiaods** [comment]
How about the progress now?

**Comment by eliu** [comment]
what is the progress now? no one follow up this issue?

**Comment by xiaods** [comment]
OMG. /close it asap.
