### ISSUE TITLE
Extended test output still verbose

### ISSUE THREAD

**Issue by mnagy** [openshift/origin#5871]
There should be exactly two lines of output for successful tests. What tests produce on stdout (and stderr perhaps) gets printed out right away. This goes for fmt.Printf() and running oc exec. We should capture the output and hide it, making sure it only gets printed out if the test fails, along with rest of ginkgo output (e.g. STEPs). This will make debugging a lot easier.

As a bonus, it'd also be nice if we could turn on automatic outputing from the command line, so I can see directly what's happening when I'm debugging a test.

Feel free to assign this to me, I'd love to take a look at it.

**Comment by mfojtik** [comment]
@mnagy I thought we do that now with the custom formater. There are some cases when the stdout is not easy to capture and even ginkgo does not capture it.

**Comment by mnagy** [comment]
@mfojtik It seems that lines that get printed out are printed out by us, explicitly, for example here:
https://github.com/openshift/origin/blob/master/test/extended/util/cli.go#L297

**Comment by mnagy** [comment]
@mfojtik I think we basically just need to turn any outstanding Printfs (if there are any) into logging statements and also handle the output in the function I mentioned in the same way.

**Comment by stevekuznetsov** [comment]
I am currently going through all of our test output and changing it one at a time. At the moment I am working on `test-cmd` but once that's done, I'll move on to extended tests. I agree with you on what the best type of output would be on the tests, that's exactly what I am implementing for the other test suites. The simple, concise, human-readable output will be paralleled with verbose output to be parsed and transformed into jUnit XML so that Jenkins can consume it and keep track of historic trends for the tests we run.

**Comment by mnagy** [comment]
@stevekuznetsov fyi: https://github.com/kubernetes/kubernetes/pull/17212

**Comment by mnagy** [comment]
After latest rebase, while running extended tests, I get spammed constantly with a lot of these:
```
I1118 11:21:58.911229   28603 loader.go:229] Config loaded from file /tmp/openshift-extended-tests/core/extended-test-postgresql-replication-1-jlgsb-user.kubeconfig
```

**Comment by smarterclayton** [comment]
The relevant message was fixed
