### ISSUE TITLE
s2i perl hot deploy extended test failure

### ISSUE THREAD

**Issue by bparees** [openshift/origin#5930]
```
• Failure [321.526 seconds]
images: s2i: perl Dancer example [It] should work with hot deploy 
/data/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/test/extended/images/s2i_perl.go:74

  Expected
      <bool>: false
  to be true

  /data/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/test/extended/images/s2i_perl.go:46
------------------------------
    fail    images: s2i: perl Dancer example should work with hot deploy (5m21.526261095s)
```

**Comment by php-coder** [comment]
Just saw it here: https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin/9398/consoleFull

**Comment by smarterclayton** [comment]
Still happening?

**Comment by bparees** [comment]
probably won't be able to tell until we get the extended image tests jenkins job straightened out, i believe that's the one @gabemontero is looking into for the disk quota issue.  The job isn't currently completing so we don't get decent test results and i don't want to crawl through them to see.

**Comment by gabemontero** [comment]
Have not seen this error in quite a while.  And since late April, in addition to the disk quota issue getting resolved, we also nailed down the ICT / Pod template container image issue, which was impacting many of the image tests, including hot deploy and these count tests, where the app pod could be up, but the DB pod was unhealthy.

I think we can close this out.  Doing so now.
