### ISSUE TITLE
SSL termination method: Reencrypt is not recognized

### ISSUE THREAD

**Issue by lorenzvth7** [openshift/origin#5977]
I want to create a secure route to my application using the termination method reencrypt.
I already did it for the edge and the passthrough-method and they are both working.
In the beginning, reencrypt is very similar to edge. So the first thing I'm doing is editing my existing route and changing the tls determination method:
```
tls:
    termination: reencrypt
  to:
    kind: Service
    name: test
```
When I want to save this I get this error: 
```
# Route test was not valid:
# * required value
```
(I know I did not add the certificate, key, destinationCaCertificate at the moment. But even when I'm adding this parameters and right keys etc it's not working).

When I'm replacing reencrypt by edge or passthrough I can easily save the route. When I'm typing something totally different. I get this error:
```
# Route test was not valid:
# * invalid value 'sdfsdfsdr', Details: invalid value for termination, acceptable values are edge, passthrough, reencrypt, or emtpy (no tls specified)
```
So it's telling me to use reencrypt but my route does not recognize it.

**Comment by ramr** [comment]
@lorenzvth7 the errors are because of an invalid configuration. The second error is only printed out when the tls Termination field value is not set - see: 
https://github.com/openshift/origin/blob/master/pkg/route/api/validation/validation.go#L81

Looks like your yaml config is not correct/valid.  Here's an example of a reencrypt route - try that: 
https://github.com/ramr/nodejs-header-echo/blob/master/openshift/reencrypt-route.json

For `reencrypt` termination, you need to specify at least the `destinationCaCertificate` value. This is because the connection between the router and the backend / pod is secure and the router needs to know the Certificate Authority that generated the certificates for pod secure communication, so that it can validate the certificate.  
You can off course also specify the cert,key and CA certificate along with that but it optional because the
front end connection from the web-client/user can use either the default router certificate/key/cacert if none is specified or then use your specific certs using SNI.

Let me know if using that as template works or if you can post the actual yaml / json file you used to configure the route and we can check what the error is (because something in there is incorrect there since the `tls.Termination` field is not set).

**Comment by ramr** [comment]
@lorenzvth7  /bump  Let me know if you are still running into problems, otherwise will close in the next few days. Thx

**Comment by lorenzvth7** [comment]
Can be closed
