### ISSUE TITLE
Allow to annotate the build started manually

### ISSUE THREAD

**Issue by mfojtik** [openshift/origin#5978]
Related discussion: https://github.com/openshift/origin/pull/5961#issuecomment-158159105

This will work similar to the `-e` parameter, but will accept a list of annotations that will be applied to the build output image (if the build output is set).

It should also be added as label to the Build object itself. Alternatively we can copy all labels from the Build object to the Docker image.

We might need this to identify what started the build (and additional metadata, like if the build was started from verified source ref, etc.)

**Comment by mfojtik** [comment]
@smarterclayton @bparees FYI

**Comment by bparees** [comment]
@mfojtik please don't do any work on this until we determine how we actually want to implement build pipelines.

**Comment by mfojtik** [comment]
@bparees yeah, I'm holding off this till we reach some agreement/have some user stories out.

**Comment by smarterclayton** [comment]
The data I had envisioned was annotations.  Labels are relevant for a subset of use cases, so I would like to see that set before it's clear

**Comment by mfojtik** [comment]
@smarterclayton @bparees annotations make more sense to me as well. How about starting a list of annotations we want to set and then see if we want to allow to set any custom annotation or just have fixed list of them?

So far I think it would be useful:

* `openshift.io/build/started-by` - specify what started a build (can be a Jenkins URL, CI, username, etc)
* `openshift.io/build/reason` - why the build was started (?)
* `openshift.io/build/signed-by` - signature of the person that started the build (?)

**Comment by bparees** [comment]
@mfojtik your specific use cases are covered by this card:
https://trello.com/c/wozDHSJ2/717-5-track-reason-a-build-was-run-triggered

so let's keep this issue to the generic "i want to add random annotations" request.

and i'm confused..you say annotations to apply to the output image.  but we don't put annotations on docker images.  So is this for applying docker labels to the output image, or annotations to the imagestreamtag?

**Comment by mfojtik** [comment]
@bparees we add labels to output Docker image, but we will also add annotations to the Build object created by  "start-build".

**Comment by mfojtik** [comment]
@bparees when the Docker image is pushed to registry and when we can import the image labels as annotations to image streams, then the annotations will also show up in the image stream object.

**Comment by mfojtik** [comment]
@bparees having this "i want to add random annotations" is also saying that we can't do anything useful with them in OpenShift :-) Like, I can use "created-by" annotation and other organization "started-by", etc... My idea was to first think about those we know about (and we 'can' add first-class support for).

**Comment by smarterclayton** [comment]
Annotations are for end users.  we have no examples today of namespaced
resources that have annotations users aren't allowed to set.  Can you come
up with an example of a restriction we would place on a build?

On Dec 9, 2015, at 8:05 AM, Michal Fojtik <notifications@github.com> wrote:

@bparees <https://github.com/bparees> having this "i want to add random
annotations" is also saying that we can't do anything useful with them in
OpenShift :-) Like, I can use "created-by" annotation and other
organization "started-by", etc... My idea was to first think about those we
know about (and we 'can' add first-class support for).

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/issues/5978#issuecomment-163224015>.

**Comment by mfojtik** [comment]
@smarterclayton i'm not saying that users can't set certain annotation, I'm saying that if we pick "started-by" annotation on the build as "standard" (I hate that word), then we can profit from that by showing it in the console and possibly pointing users back to the Jenkins URL, etc...

If we say "you can use random annotation" then we don't know what that annotation mean. I'm also fine with "we don't need to know" and "it is up to user to understand that annotation".

**Comment by smarterclayton** [comment]
Started-by on a build is really a generic created-by, which should be
created for you, not by the client.  Started-by as a build annotation being
part of the image and shown in UI is very reasonable.  What I'm getting at
is that we will not prevent end users from mucking with annotations on
objects in namespaces normally.  So any case where we treat some
annotations as special is unusual and we should be careful to justify it.

 i'm not saying that users can't set certain annotation, I'm saying that if
we pick "started-by" annotation on the build as "standard" (I hate that
word), then we can profit from that by showing it in the console and
possibly pointing users back to the Jenkins URL, etc...

If we say "you can use random annotation" then we don't know what that
annotation mean. I'm also fine with "we don't need to know" and "it is up
to user to understand that annotation".

**Comment by bparees** [comment]
>  Started-by as a build annotation being part of the image and shown in UI is very reasonable. 

i don't think it is.  I already linked the card in which we want to provide an audit trail for builds, and when we do that, i don't think we should be doing it via a "start-by" annotation, we should be adding a first class field to the Build object.

Doing it as a annotation makes it much more difficult for us to prevent users from mucking with the value, and we have to prevent users from mucking with it to make it useful for an audit trail.

So i'm still unclear on the goal of this issue, is this the proposal:  
```
annotations on a Build object should be turned into Labels on the output docker image (which eventually will turn into annotations on the imagestreamtag when the image gets imported, someday)
```

?

If so, I don't like it because just because something is an annotation on a Build doesn't mean it should be a Label on the docker image.

Alternatively is the proposal:
```
Users can provide a list of values that should be turned into Labels on the output docker image (which eventually will turn into annotations on the imagestreamtag when the image gets imported, someday)
```

?

Please give me a concrete flow (what is defined on the build object and where).

**Comment by smarterclayton** [comment]
On Dec 9, 2015, at 10:45 AM, Ben Parees <notifications@github.com> wrote:

Started-by as a build annotation being part of the image and shown in UI is
very reasonable.

i don't think it is. I already linked the card in which we want to provide
an audit trail for builds, and when we do that, i don't think we should be
doing it via a "start-by" annotation, we should be adding a first class
field to the Build object.


I'm talking about image metadata, not build objects.  Images *should* be
decorated with metadata on their provenance.  We have not yet settled how
we represent users in the API, but it's going to start with an annotation.
Having started by show up in the API first is probably not likely.


Agree with your other points below.


Doing it as a annotation makes it much more difficult for us to prevent
users from mucking with the value, and we have to prevent users from
mucking with it to make it useful for an audit trail.

So i'm still unclear on the goal of this issue, is this the proposal:

annotations on a Build object should be turned into Labels on the
output docker image (which eventually will turn into annotations on
the imagestreamtag when the image gets imported, someday)

?

If so, I don't like it because just because something is an annotation on a
Build doesn't mean it should be a Label on the docker image.

Alternatively is the proposal:

Users can provide a list of values that should be turned into Labels
on the output docker image (which eventually will turn into
annotations on the imagestreamtag when the image gets imported,
someday)

?

Please give me a concrete flow (what is defined on the build object and
where).

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/issues/5978#issuecomment-163298088>.

**Comment by mfojtik** [comment]
I think we don't understand each-other ;-)

What I want to achieve is this:

1) I have Jenkins server that test changes in my source repository
2) When test pass, it kicks the build using the `start-build` command.
3) I want to be able to identify what started the Build and I want to be able to go back to Jenkins and see the testing job if something goes wrong with deploying that image/building it.

For that I propose:

1) When Jenkins starts the build, Jenkins should be able to pass an "annotation" to the Build object via "start-build". The annotation will be `started-by: https://jenkins/jobs/test/123`.
2) When the build runs, the Build object is annotated so I can see this annotation in "oc get builds" and in web console. For that, we can't say "users can set random annotation, because if they do, we don't know which annotation to show in the web console/CLI, right?"
3) Now when the build passed, I want to add Label "started-by" that will be set to the annotation value. When the image is pushed to the ImageStream, the Label should be imported and transformed to a ImageStreamTag annotation.
4) Now when deployment starts and fail, I can see the pointer to a Build and also I can see the URL to a Jenkins that was testing the change.

**Comment by smarterclayton** [comment]
That started by is different - I would call that annotation "ci-job.href"
or similar.

**Comment by bparees** [comment]
> 1) When Jenkins starts the build, Jenkins should be able to pass an "annotation" to the Build object via "start-build". The annotation will be started-by: https://jenkins/jobs/test/123.

and i'm saying i don't think that should be an annotation, it should be a first class field on the Build object, and we have a card to cover this.  However @smarterclayton seems to disagree about it being a first class field, i'm not clear on why.  I still think an annotation is too easy for a user to modify, ruining your audit trail.  And I still think this should be covered by the card I linked above.

> 2) When the build runs, the Build object is annotated so I can see this annotation in "oc get builds" and in web console. For that, we can't say "users can set random annotation, because if they do, we don't know which annotation to show in the web console/CLI, right?"

setting a random annotation was a different use case.  I was trying to understand if your goal was to allow users to provide other arbitrary metadata that should be attached to the Build object as annotations, and possible attached to the resulting image as Docker labels.  It sounds like you are not suggesting that use case.

> 3) Now when the build passed, I want to add Label "started-by" that will be set to the annotation value. When the image is pushed to the ImageStream, the Label should be imported and transformed to a ImageStreamTag annotation.

no disagreement here, other than i don't want "started-by" to come from an annotation on the Build, I want it to come from a first class field definition.

**Comment by bparees** [comment]
One other suggestion...  the final output build image should not contain "started by - jenkins job link", it should contain "produced by - openshift build reference".

that is a generic solution which is useful whether you use jenkins or manually launch builds.

you can then go look at the openshift build, and the openshift build should contain a "started by - XXXX" where XXXX is either the user who launched the build, or the link to the jenkins job, etc.

it's a chain, you don't want to skip a link in the chain.

**Comment by smarterclayton** [comment]
@jwforres should weigh in on what she'd want to show in the UI if all we
had was an image (that showed up on a different deployment, even)

**Comment by jwforres** [comment]
images should at least refer back to the openshift build  that created them, if we think we would want to link to the build config, then have the build config name as well so we dont have to fetch the build to create the URL to the config

it would be nice if they also contained the link to what started that build when we know it, although it brings up the question... if I don't have the rights to view the build object that created this image... should I be able to know what started the build?  odds are it might be say a private CI system that internal OPs team has access to but maybe no one else?

**Comment by bparees** [comment]
yeah the more information we pack into the output image the more worried i get in terms of exposing the inner workings of a CI system that the end-consumer of an image should not be aware of.

**Comment by bparees** [comment]
(hence my preference to only provide the next back link in the chain.  if you have access to that resource, you can continue following the chain backwards.  Though i understand that makes @jwforres 's life difficult :) )

**Comment by mfojtik** [comment]
@bparees I think the work @PI-Victor is doing covers this, right?

**Comment by bparees** [comment]
no, it does not.

**Comment by bparees** [comment]
@jwforres @smarterclayton @mfojtik we now have:

1) triggered-by information on the build object itself (https://github.com/openshift/origin/blob/master/pkg/build/api/types.go#L148)

2) the ability to define labels to be added to the image being produced: https://github.com/openshift/origin/blob/master/pkg/build/api/types.go#L841-L843

What we do not have:  automatic additional of labels to the output image that point back to the specific build object that produced the image.

Per the last few comments, @jwforres and I have some security concerns around providing that information in the image since it will be seen by consumers of the image who have no business knowing how the image was constructed.

As such I'm currently in favor of closing this, but I do understand there could be a desire to include more provenance information in the images being produced, so i'll give you guys a last chance to weigh in before i close it.

If we did implement provenance, I think it:

1) has to be optional
2) should leverage the existing label mechanism, but provide a way to have the label value auto-generated.

**Comment by mfojtik** [comment]
To what object we want to pin point the image to? BuildConfig or Build object? If later, it won't be that useful if the Build object gets pruned, or do you want to serialize the entire object into an annotation?

I think, for the sake of "rebuild" or auditing of the image, only "source repo/ref" and builder image are useful (for "normal" builds, not builds like dockerfile/custom). I can see the point of leaking information
if we store the link the private GIT repo. And I believe we already set the "builder" image?

**Comment by smarterclayton** [comment]
We're probably going to (over time) record changes that happen to etcd
so that we have more complete history.  If we have that, we don't
really need this for audit since we can reconstruct that info.

How would someone use this info?

**Comment by jwforres** [comment]
for regular builds i don't think this gains us anything that we can't already determine (linking a build to an image) without leaking information.  Today we look at the output image stream on the build and we look at the OPENSHIFT_BUILD_NUMBER metadata on the image.

But for the purpose of discussion, if I've got a Jenkins build that is pushing images itself, then today we have no way to tie that image in the console back to the build it came from.  I think the question is just whether we want an optional convention for annotating an image with an openshift build object ref.

To @mfojtik 's point about pruned builds, yes that eventually becomes a problem, but thats easily handled from the console.  That doesn't outweigh the benefits of making the connection when we can. Odds are that if you care about referencing a particular build its because you are trying to get back to either the configuration at that point in time, or to get to the logs.  E.g. why does image abc work fine but image 123 blows up, let me check the config / logs to look for the difference.

**Comment by bparees** [comment]
so as it turns out (thanks to @jwforres for bringing it up) we do have OPENSHIFT_BUILD_NAME already on the images as an env variable.

here's the env variables we define:
```
               "OPENSHIFT_BUILD_NAME=nodejs-ex-1",
                "OPENSHIFT_BUILD_NAMESPACE=test",
                "OPENSHIFT_BUILD_SOURCE=https://github.com/openshift/nodejs-ex",
                "OPENSHIFT_BUILD_COMMIT=e81cacfa03b026dd9860de2d2774df6e6d421250
```

and the labels:

```
               "io.k8s.description": "Platform for building and running Node.js 4 applications",
                "io.k8s.display-name": "test/nodejs-ex-1:6d3ddff5",
                "io.openshift.build.commit.author": "Ben Parees \u003cbparees@users.noreply.github.com\u003e",
                "io.openshift.build.commit.date": "Wed Feb 15 16:27:18 2017 -0500",
                "io.openshift.build.commit.id": "e81cacfa03b026dd9860de2d2774df6e6d421250",
                "io.openshift.build.commit.message": "Merge pull request #95 from bparees/sc_metadata",
                "io.openshift.build.commit.ref": "master",
                "io.openshift.build.image": "centos/nodejs-4-centos7@sha256:e16bab0dd7dd920ea3682a26766e0a8178720082c19d724f3a2033fd864886f9",
                "io.openshift.build.source-location": "https://github.com/openshift/nodejs-ex",
                "io.openshift.builder-base-version": "915990b",
                "io.openshift.builder-version": "bfa0385c10df2000b36738bd5142f6d0746a005a",
                "io.openshift.expose-services": "8080:http",
                "io.openshift.s2i.scripts-url": "image:///usr/libexec/s2i",
                "io.openshift.tags": "builder,nodejs,nodejs4",
                "io.s2i.scripts-url": "image:///usr/libexec/s2i",
```

So we can create labels that align w/ the env variables we already have (we wouldn't be leaking any information we're not already leaking), if people think that is of value.  @mfojtik would that satisfy this request in your opinion?

**Comment by mfojtik** [comment]
@bparees yes this seems to be fine. thanks!

**Comment by bparees** [comment]
reopening since we should still actually create said labels (instead of leaving them just as env vars)
