### ISSUE TITLE
oc delete all should actually delete all

### ISSUE THREAD

**Issue by withinboredom** [openshift/origin#6006]
When putting a label on a persistent volume claim and doing `oc delete all -l some=label` the pvc still remains. This seems to create issues when using templates that have claims in them, ie, `oc delete all -l template=jenkins`

**Comment by liggitt** [comment]
Dupe of https://github.com/openshift/origin/issues/3740

**Comment by annesadleir** [comment]
But #3740 has been closed because there's no intention to delete secrets when you do delete all.  Do the same arguments apply to persistent volume claims?  I'm a developer using a template which includes a pvc.  When I want to delete it all and try again it's annoying that I have to remember to do the pvc separately.  Plus I'm going to be asking other members of my team to use the template, and I need to keep things as simple as possible for the non-developers.

**Comment by collinbachi** [comment]
Any update on this?
