### ISSUE TITLE
Message for deprecated 'oc build-logs' doesn't give pod name

### ISSUE THREAD

**Issue by sspeiche** [openshift/origin#6021]
Receiving this message:

```
oc build-logs green-1
Command "build-logs" is deprecated, use "logs" instead.
```
A user doesn't know what pod name to use, perhaps the message could be updated to say:
"Command "build-logs" is deprecated, use "oc logs green-1-build" instead"

**Comment by php-coder** [comment]
This message generated and shown by Cobra (framework that we're using for dealing with command line options). It allows to specify static message that will be shown for deprecated options. I didn't find a way how to add dynamic information (like a pod name) to this message.

I even can't get the first non-option (like `green-1` in the example above) and append `-build` to it, because we're defining possible command-line arguments in the functions that don't have direct access to the command-line arguments. Probably, I can pass real arguments through the functions but it looks a bit ugly.

@bparees WDYT? Maybe you would suggest a better way?

But I can improve message from:
`Command "build-logs" is deprecated, use "logs" instead.`
to
`Command "build-logs" is deprecated, use "oc logs <build pod name>" instead.`

**Comment by bparees** [comment]
the actual command recommendation should be:
`use "oc logs build/<build-name>" instead.`

if you can substitute the actual build-name in there, great, if not, the static message is fine.

we don't want to send them to the pod logs though, we want to send them to the build logs resource still.
