### ISSUE TITLE
origin-pod v1.1.0 not found on dockerhub

### ISSUE THREAD

**Issue by vbehar** [openshift/origin#6158]
Hi,

on a node on v1.1.0, I got the following errors : 

> pulling image "openshift/origin-pod:v1.1.0"
> Failed to pull image "openshift/origin-pod:v1.1.0": Tag v1.1.0 not found in repository docker.io/openshift/origin-pod

and indeed, the tag v1.1.0 is not on https://hub.docker.com/r/openshift/origin-pod/tags/, but the tag v1.1 is.

The node has been installed with openshift-ansible.

would it be possible to tag the v1.1 as v1.1.0 please ?

Thanks,
Vincent

**Comment by smarterclayton** [comment]
None of our other images are tagged with 1.1.0.  I suspect the ansible script is wrong. @jdetiberus @sdodson

**Comment by sdodson** [comment]
The problem is that when I built the RPMs for 1.1 they were tagged 1.1.0. I've since removed that build and there's RPMs for 1.1 now. Detailed instructions for how to remedy this here https://github.com/openshift/openshift-ansible/issues/1001#issuecomment-161007686

As a matter of release tagging I think it'd be best if we kept a fixed number of version segments. OSE keeps four, if Origin always had 3 I think that'd be a good idea.

**Comment by sdodson** [comment]
Or four, whatever works best as long as it's consistent.

**Comment by vbehar** [comment]
ok thanks !

**Comment by smarterclayton** [comment]
Ok, we'll do that for 1.2

On Dec 2, 2015, at 10:31 AM, Scott Dodson <notifications@github.com> wrote:

The problem is that when I built the RPMs for 1.1 they were tagged 1.1.0.
I've since removed that build and there's RPMs for 1.1 now. Detailed
instructions for how to remedy this here openshift/openshift-ansible#1001
(comment)
<https://github.com/openshift/openshift-ansible/issues/1001#issuecomment-161007686>

As a matter of release tagging I think it'd be best if we kept a fixed
number of version segments. OSE keeps four, if Origin always had 3 I think
that'd be a good idea.

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/issues/6158#issuecomment-161333607>.
