### ISSUE TITLE
TestAuthorizationRestrictedAccessForProjectAdmins flake

### ISSUE THREAD

**Issue by kargakis** [openshift/origin#6173]
```
--- FAIL: TestAuthorizationRestrictedAccessForProjectAdmins-4 (14.12s)
	authorization_test.go:45: unexpected error: policybinding ":default" cannot be updated: the object has been modified; please apply your changes to the latest version and try again
FAIL
```
https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin/7608/consoleFull

**Comment by rhcarvalho** [comment]
One more https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin/7628/console

**Comment by bparees** [comment]
```
I1216 23:46:18.431236   18818 create_dockercfg_secrets.go:163] View of ServiceAccount openshift/deployer is not up to date, skipping dockercfg creation
Could not add service accounts to the system:deployer role: policybinding ":default" cannot be updated: the object has been modified; please apply your changes to the latest version and try again
--- FAIL: TestAuthorizationRestrictedAccessForProjectAdmins-4 (15.18s)
	authorization_test.go:45: unexpected error: policybinding ":default" cannot be updated: the object has been modified; please apply your changes to the latest version and try again
FAIL
```

https://ci.openshift.redhat.com/jenkins/job/merge_pull_requests_origin/4374/console

**Comment by liggitt** [comment]
likely the same issue as https://github.com/openshift/origin/issues/6065#issuecomment-164042634, still trying to figure out how we appear to have multiple etcd writers

**Comment by liggitt** [comment]
Same cause as https://github.com/openshift/origin/issues/6065 (failed etcd update). The issue is not specific to a test, it's a response to an etcd server error that is seen about 30-60 seconds into the integration tests. If a client request is in progress when that server error is received, the client gets a 500 error, and reacts by retrying the request. If the request is one that would fail on a retry (like a delete or a conditional update), the test fails.
