### ISSUE TITLE
automatic required env var generation

### ISSUE THREAD

**Issue by soltysh** [openshift/origin#6180]
Although I'm targeting new-app, this applies to all UI.
Here's my thought: our db images require user to provide [certain environment variables](https://docs.openshift.org/latest/using_images/db_images/mysql.html#configuration-and-usage). This is pretty cumbersome. I'd like to see the new-app/other UIs to read those requirements from image metadata, generate them for me and print them upon creation, assuming user did not provide them already. 

@openshift/ui-review @bparees @csrwng wdyt?

**Comment by bparees** [comment]
i think it would make more sense to just default them in the image, if we want that sort of behavior, though i realize that doesn't allow for producing unique/secret values.

generating values based on labels in the image crosses over into the realm of problems we're solving with templates/parameterization, and i don't want to see us do it in two places.

**Comment by liggitt** [comment]
be aware that the UI can't read any data from docker images, only from things in the API

**Comment by soltysh** [comment]
@bparees I was rather suggesting to reuse the logic from templates in here.

@liggitt there's a [card](https://trello.com/c/RPTugJoZ/515-import-docker-labels-as-annotations) which will import labels as annotations.

**Comment by bparees** [comment]
> @bparees I was rather suggesting to reuse the logic from templates in here.

yes but you'd still be doing it in two places, specifying in two places.

**Comment by jwforres** [comment]
@bparees going through the backlog, do you feel like this issue should be closed?  I tend to agree that the UI detecting env var requirements and trying to generate ENV VARs on behalf of the user is going too far.

At best I could see us doing something like reading off a README type field from the image for when people use the Deploy Image page and we can show them that information.

**Comment by bparees** [comment]
yeah i think at this point we've bought in that templates and imagestreams are our mechanisms for layering metadata onto images.  Creating another set of metadata (at the image level) and expecting users to learn it and create images containing it seems unlikely.  I'd rather push harder at the template and imagestream level.

Otherwise we're going to create yet another experience where the UI looks great for our images that provide all the expected metadata, and looks terrible for "random dockerhub image" and users will ask us why and we'll have to tell them to go extended the dockerhub image w/ a bunch of labels.  Better to tell them to wrapper the dockerhub image into an imagestream or template to get a better experience, imho.
