### ISSUE TITLE
oc status should inform me that a particular route doesn't work...

### ISSUE THREAD

**Issue by kargakis** [openshift/origin#6266]
...because it cannot be associated with an endpoint (uses a named port while the endpoint is not). Issues like https://github.com/openshift/origin/issues/6265 are pretty common lately.

@deads2k please assign

**Comment by liggitt** [comment]
Shouldn't we work on named port issue in the endpoints?

**Comment by kargakis** [comment]
> Shouldn't we work on named port issue in the endpoints?

Will fixing single-port endpoints to be named, fix already existing endpoints that have no names? If yes, then fixing that will be ebough, if no then it's a separate issue.

**Comment by deads2k** [comment]
> Will fixing single-port endpoints to be named, fix already existing endpoints that have no names? If yes, then fixing that will be enough, if no, then it's a separate issue.

In my mind, its about time.  This is broken now and its hard to find.  If we don't fix the underlying problem for 1.1.1, we should at least detect that problem (its an error).

If we do this in `oc status`, you should have a test that actually makes sure that the condition you're checking is still broken.  It's probably as easy as a reflective test on the fields of the `Endpoint`, right?  That way, when the problem is fixed, we remove the `oc status` warning.  I'm probably ok forcing matched sets instead of using a swagger doc to determine true server state.

**Comment by liggitt** [comment]
we should warn in the following cases:

* route has no targetPort, service has multiple ports defined
* route has named targetPort, service has no port with that name
* route has numeric port, service has no port with that number as a targetPort

**Comment by kargakis** [comment]
> route has no targetPort, service has multiple ports defined

We already do this. On the rest.
