### ISSUE TITLE
How to fix the IP of router and registry service

### ISSUE THREAD

**Issue by thincal** [openshift/origin#6284]
You know:
- the router should have a fixed IP to be configured in DNS for providing the internal service routing
- registry service is monitoring 5000 port instead of 80, so it seems the routing can't be done by the router, my solution is still using a fixed IP for registry service and configure the DNS.

So, is there a way to specify a fixed IP to router and registry service ?
or do you have other solution to solve above requirements ? many thanks !

Btw, I am using the openshift-ansible to install the openshift..

**Comment by thincal** [comment]
It seems that the restrict the service to some host can be achieved by [configuring the scheduler](https://docs.openshift.org/latest/install_config/install/deploy_router.html#haproxy-router).

Is that true ? and is there some example for that? many thanks.

**Comment by pweil-** [comment]
@thincal - here is the documentation for the scheduler https://docs.openshift.org/latest/admin_guide/scheduler.html

By using the scheduler you can ensure that the router lands on a specific node so you can guarantee the ip address (since it uses host networking).

For exposing a registry via the router you can create a passthrough route that points to the registry's service.   In this case the router would accept traffic on port 80 and/or 443 and direct the traffic the whatever the service is exposing.  For docs on this please see https://docs.openshift.org/latest/install_config/install/docker_registry.html#exposing-the-registry

**Comment by pweil-** [comment]
pr to fix the broken link https://github.com/openshift/openshift-docs/pull/1334

**Comment by thincal** [comment]
Thanks for your info. I still have two questions:
1. Could you help show an example about how to deploy the router service to a specific host ? From the scheduler doc, I can understand the concept but don't know how to.

2. Router can only redirect the service through port 80/443, but registry service is exposing 5000 port, how to rout it via. the router ?

Many thanks for your kind help !

**Comment by pweil-** [comment]
> Could you help show an example about how to deploy the router service to a specific host ? From the scheduler doc, I can understand the concept but don't know how to.

This can be accomplished in a number of different ways.  One of the common ways is to label your nodes and use a selector in the scheduler.  For example, you can use the `oc label` command to add annotations to your nodes and then update a namespace's `node-selector` annotation so that all pods for the namespace go to a specific node.  

Here is a more detailed walk through that sets up a primary and infra region with the scheduler.  The infra region is targeting a specific node while the primary region targets multiple nodes:  https://github.com/openshift/training/blob/master/02-Installation-and-Scheduler.md#regions-and-zones

> Router can only redirect the service through port 80/443, but registry service is exposing 5000 port, then how to rout it via. the router ?

The router will accept the external traffic on port 80/443 and use the route information that you create to determine where the traffic will be routed.  This is based on the endpoints that the service is using which will point to <your registry pod>:5000.  So traffic will flow from <outside connect to :80/:443> -> router:80/443 -> registry pod:5000.

**Comment by thincal** [comment]
@pweil- many thanks!

**Comment by thincal** [comment]
@pweil- it seems that can edit the node-selector of a namespace, is that possible to let one specific pod be scheduled to infra region ?

**Comment by pweil-** [comment]
@thincal by changing the namespace's `node-selector` you would be indicating that anything in the namespace should go to that node.  For an infra namespace (like where you'd deploy the router and registry) this is appropriate.

For more fine grained control you can use the `MatchNodeSelector` predicate in the scheduler, labels on your nodes, and set the `nodeSelector` on the pod spec.

https://docs.openshift.org/latest/rest_api/kubernetes_v1.html#v1-podspec
https://docs.openshift.org/latest/admin_guide/scheduler.html#static-predicates

**Comment by thincal** [comment]
@pweil- thanks for your reply.

Sorry that I want to confirm with you about the detailed steps.

1. set the ```nodeSelector``` on the pod spec

the [doc] (https://github.com/kubernetes/kubernetes/blob/release-1.1/docs/user-guide/node-selection/README.md) tells very clearly that it could be done like this
```
nodeSelector:
    disktype: ssd
```
also the label ```disktype: ssd``` should be assigned to one node firstly...

2.  then is there anything need to be done by myself about using the ```MatchNodeSelector``` predicate in the scheduler? should it be chosen automatically according to the nodeSelector presence ?

Thanks again, I hope this should be the last question.

**Comment by pweil-** [comment]
> then is there anything need to be done by myself about using the MatchNodeSelector predicate in the scheduler? should it be chosen automatically according to the nodeSelector presence ?

The default scheduler configuration should be using the `MatchNodeSelector` already so you should just be able to label your nodes and set the appropriate values on your pod and have it work.
