### ISSUE TITLE
GlusterFS volume error : glusterfs: failed to get endpoints

### ISSUE THREAD

**Issue by arrawatia** [openshift/origin#6331]
I followed the instructions from [1] and [2] to setup Gluster FS PV but when I try to use the PVC in a pod it fails.

The error in node logs is : 

```
Dec 15 21:48:52 node-compute-8c258955.dev.aws.qtz.io origin-node[405]: E1215 21:48:52.824595     405 glusterfs.go:89] glusterfs: failed to get endpoints glusterfs-dev[endpoints "glusterfs-dev" not found]
Dec 15 21:48:52 node-compute-8c258955.dev.aws.qtz.io origin-node[405]: E1215 21:48:52.832670     405 glusterfs.go:89] glusterfs: failed 
```

But the "glusterfs-dev" service and endpoint exists in the "default" namespace:

```
$ oc get service glusterfs-dev -n default -o yaml
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: 2015-12-15T21:32:23Z
  name: glusterfs-dev
  namespace: default
  resourceVersion: "2894020"
  selfLink: /api/v1/namespaces/default/services/glusterfs-dev
  uid: 5424624c-a373-11e5-b562-06302f7b1fe5
spec:
  clusterIP: 172.30.224.96
  portalIP: 172.30.224.96
  ports:
  - port: 1
    protocol: TCP
    targetPort: 1
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}

$ oc get endpoints glusterfs-dev -n default -o yaml
apiVersion: v1
kind: Endpoints
metadata:
  creationTimestamp: 2015-12-15T11:03:46Z
  name: glusterfs-dev
  namespace: default
  resourceVersion: "2839215"
  selfLink: /api/v1/namespaces/default/endpoints/glusterfs-dev
  uid: 82f60af3-a31b-11e5-b562-06302f7b1fe5
subsets:
- addresses:
  - ip: 172.18.1.89
  - ip: 172.18.1.90
  ports:
  - port: 1
    protocol: TCP
```

It looks like the glusterfs plugin looks for the endpoint in the pod namespace [3] rather that the "default" namespace as documented. 

I tried creating the endpoint in the project and it worked.

Is this a document bug or a regression ? Creating endpoints per project is cumbersome as the endpoints need glusterfs cluster IPs and do not work with hostname (as per [1]) and any change in glusterfs cluster will mean that every project on the cluster needs to be updated.

[1] https://docs.openshift.org/latest/install_config/persistent_storage/persistent_storage_glusterfs.html
[2] https://github.com/kubernetes/kubernetes/issues/12964
[3] https://github.com/openshift/origin/blob/master/Godeps/_workspace/src/k8s.io/kubernetes/pkg/volume/glusterfs/glusterfs.go#L86

**Comment by smarterclayton** [comment]
The instructions are wrong - you need to create a service.  See https://github.com/openshift/origin/pull/6167

**Comment by smarterclayton** [comment]
Docs will be created with https://github.com/openshift/openshift-docs/issues/1356

**Comment by smarterclayton** [comment]
Oops, missed that you had the service :)  Regarding the mismatch, agree that is ugly.

**Comment by smarterclayton** [comment]
@rootfs how do we fix this so end users can easily have gluster that the whole cluster can use?

**Comment by rootfs** [comment]
@smarterclayton 
Ideally glusterfs volume spec should embed the endpoint instead of referring to external endpoints. This is how ceph rbd volume spec does too. 
To make it backward compatible, the embeded endpoint will be optionally but if supplied, it overwrites the external endpoint. If this doesn't sound too bad, I'll make an upstream PR.

**Comment by smarterclayton** [comment]
Sounds fine to me.

**Comment by karelstriegel** [comment]
@rootfs , @smarterclayton to be clear, to only workaround is to define the endpoints in each namespace?

**Comment by rootfs** [comment]
@karelstriegel you need to have a service to associate the endpoint.

**Comment by karelstriegel** [comment]
@rootfs I have a service to associate the endpoints, both are in the default namespace. So guess I need to have both for each namespace? (as a workaround)

**Comment by rootfs** [comment]
yes, service and endpoints live in the same namespace.

**Comment by ibotty** [comment]
@rootfs I personally like to specify the gluster endpoints separately, it is an abstraction I do like and use. What about adding a `namespace` key, so that the `default` glusterfs endpoint can be chosen, also from pods in a different namespace.

**Comment by rootfs** [comment]
sure, i'll look into that. @smarterclayton

**Comment by erictune** [comment]
Putting the server list into every pod/podTemplate does not seem to solve the OPs requirements:

>  any change in glusterfs cluster will mean that every project on the cluster needs to be updated.

Changing an endpoints in all namespaces is easier than changing the volume spec in all pods.

**Comment by erictune** [comment]
Also, you cannot really make an required field optional, because clients other than kubelet might be relying on the definition of the Glusterfs volume, and will be broken if a required field is not set.

**Comment by erictune** [comment]
Have you considered either (1) adding an optional "endpointsNamespace" field (which is super easy to implement but has authz implications or (2) making a thing that helps you broadcast an service's endpoints from a source namespace into headless endpoints in all other namespaces.

**Comment by smarterclayton** [comment]
For PVC we would already have the security protection (end users can't
change endpointsNamespace) so we could be reasonably sure that any kubelet
can look up that endpoint.  We already block regular users from specifying
PVC, and technically DNS already returns endpoints for everyone, so I think
it's ok for Gluster endpoints to be a reference across namespaces.

**Comment by erictune** [comment]
Good point about DNS.  Option 1 is looking best.

**Comment by rootfs** [comment]
@erictune @smarterclayton I like the namespace as a  parameter pattern. I already used it in one of the PRs.

Here, server list doesn't replace endpoint. Server list is used only when endpoint is not working. It solves the following issues:

- We have to ensure a headless service uses the endpoint to keep it alive, This is really a poor user experience. In case endpoint is not associated with a service and gets lost, server list is our insurance.

- The server list approach makes more sense from volume provisioning perspective. When gluster plugin uses Heketi (the external gluster provisioner) to provision a gluster volume, the plugin gets gluster hosts and volume path. 

If the hosts are in the endpoint, all is good. But if the hosts are not in the endpoint, then we have a split brain problem. If we decide to go option (1), then we have to either create a new endpoint (and the headless service) or update an existing endpoint, a quite unprecedented  pattern. But if we use the hosts in the proposed server list, then we at least can get updated working hosts.

**Comment by humblec** [comment]
My thoughts are same as what @rootfs shared here. Also, to ensure the backward compatibility, the endpoint is still kept and the preference is given to endpoint than the servers list. The servers list is only used when endpoint is not working.

**Comment by erictune** [comment]
Are the scenarios you are talking about primarily when GlusterfsVolumeSource is embedded in a Pod or in a PersistentVolume?

**Comment by rootfs** [comment]
@erictune Mostly about PV. 
We had an internal discussion. Humble is going to keep endpoint direction.

**Comment by humblec** [comment]
@erictune as @rootfs mentioned, I am working on a PR based on 'endpointnamespace' instead of 'server list' in the volume source. I will update this thread soon with the details. Thanks!

**Comment by jonathan-kosgei** [comment]
Is there any other way around this? Other than placing the endpoints.yml and the service in each yml? I have numerous namespaces and I imagine it'd be painful to add a new endpoint clusterwide.

**Comment by jonathan-kosgei** [comment]
Wouldn't this work?
```
 glusterfs:
  endpoints: "glusterfs-cluster.default"
  path: "gluster_vol-1"
  readOnly: false
```

**Comment by humblec** [comment]
@jonathan-kosgei I am not sure I interpreted it properly. However I would like to mention that, the endpoint "glusterfs-cluster.default" will be validated in pod's namespace and if it does not exist in that namspace the mount will fail. Thats what the limitation we have now. So, you have to define endpoint in the namespace of the pod.  With this patch ( https://github.com/kubernetes/kubernetes/pull/33020) we are trying to come up with one more field called 'endpointnamespace" also dynamically create the endpoint/service when we provision the volume.

**Comment by erictune** [comment]
@humblec When I looked at  kubernetes/kubernetes#33020 it sounds like it allows you to reference an existing endpoints in another namespace.  For example, if my namespace is called "ericsns" and there is a gluster cluster in the "gluster" namespace, then I can refer to that and kubelet will use those other endpoints.

But, your description in your last comment uses the words `dynamically create the endpoint/service when we provision the volume.`  I didn't see anything about dynamic creation in that PR.

**Comment by humblec** [comment]
@erictune yes, in the new PR, the provided 'endpointnamespace' is used. Regarding `dynamic creation of endpoint/service` , the provisioner dynamically collect  the cluster IPs and create an endpoint/service if it doesnt exist  https://github.com/kubernetes/kubernetes/pull/33020/files#diff-e97253dd603331ffca81131a4b67264fR555

**Comment by liggitt** [comment]
So this would allow me to make a kubelet create a service and endpoint for me in someone else's namespace by creating a pod with a specially crafted glustervolumesource? That's not something we should enable

**Comment by eparis** [comment]
@liggitt I'm not sure I understand why a kubelet would ever create a service and endpoint. Although I haven't read to see if the patch is doing something different that it should.

The idea was supposed to be that the provisioner, the trusted component which creates PVs, will create, in a namespace controlled by the provisioner configuration (lets call it `provisionNS`), the service and endoints (`endpointName`). It will then create the PV listing both `provisionNS` and `endpointName`. The end user should have NO control over this.

While this may be triggered by an end user creating a PVC, which causes the provisioner to do its work, the end user, nor the kubelet, create services, endpoints, etc. The provisioner does that. The kubelet will USE the `provisionNS`/`endpointName` tuple in order to look up the server location and mount the storage.

**Comment by liggitt** [comment]
The GlusterVolumeSource object can be part of a PersistentVolume, or part of a Volume definition inside a pod spec. I'm primarily concerned about adding a namespace field to the latter (though the more params we add to PV provisioners that end users shouldn't be able to see/modify, the harder ACL will be). I would not want the possibility of part of the system acting in another namespace thinking the GlusterVolumeSource came from a PersistentVolume under cluster admin control, when in reality it came from a pod spec Volume under user control.

**Comment by eparis** [comment]
So that I thought we discussed as well. Although now I have a new 'concern' which you just brought up. I'd been thinking that it was irrelevant if we let a user set the endpointName and endpointNamespace in the pod spec volume definition.

But I'm afraid that is not true. While discovering the IP addresses which are part of the endpoint in another namespace does not seem security sensitive we are subtly changing how those can be used. Since this will cause the `kubelet` to connect to those endpoints, instead of the `pod` connecting to those endpoints. Connections from the kubelet may have different access permissions as connections from the pod. So @liggitt is right, we do have the `system` acting on behalf of something the user can control. Uggh.

Is the only answer to abandon endpoints altogether?

**Comment by erictune** [comment]
I agree with Jordan that cross-namespace references are to be avoided for
security reasons.

Another reason to avoid them is that they expose an implementation detail.
For example, if the cluster admin decides to run gluster in the "gluster"
namespace, then all the consumers have to refer to
"endpointsns: gluster, endpoint: default".

But, what happens if, say, the cluster admin decides to try out a new
version of gluster running in namespace "gluster-new".
And the cluster admin wants to move 10% of namespaces to the new storage
system.  How would the admin even do that?

I think that the service producer and consumer need to be loosely coupled,
and endpointsns does not accomplish that.

Some other options to explore:

Continue to use a local-to-consumer-namespace endpoints, and try harder to
make sure that endpoints was always correct (such as by having the cluster
admin run a controller to reconcile it.)  (I still don't understand why
this is not an option).

Refer to the gluster cluster via a DNS name, which could be, but is not
necessarily a KubeDNS name.  If it is not a KubeDNS name, but it is a DNS
suffix that is controlled by the cluster admin, then the cluster admin can
retarget it.  Would it be possible to do split-horizon DNS for this based
on the PodIP?  Does DNS see PodIP as the source IP?  Or is it the node IP
of kubelet doing the request?  hostNet?  Gets confusing.

**Comment by erictune** [comment]
Okay, prepare for backpedaling.

- the security concerns might be mitigated if the cluster admin maintained
a namespace whose only purpose was to hold endpoints for "global
namespaces", and didn't hold anything else interesting.  You could make
sure that kubelets didn't have write permission to that ns, if you wanted
to.  Or you could make it so that all namespaces can read endpoints in this
namespace, and make the kubelet act as the Pod's service account when
resolving the endpoints (using Impersonate-User)

- the fact that users have the option of maintaining their own local
endpoints means it is harder for a cluster admin to "move" the location of
the gluster cluster.  The pattern that Eric Paris descrbes does allow for
this, because the provisioner can change the contents of the endpoints
object.

- If the endpoints are resolved once and then never re-resolved, this is
going to cause a problem at some point.  Periodic re-resolution will be
more flexible.  This could be via DNS, but I guess it could be by a Kube
client periodically re-resolving endpoints.

**Comment by eparis** [comment]
@erictune although a kube-DNS solution might be even better. Instead of listing ANY endpoints in the volume list a DNS address. That address could obviously be of the form `endpointName.endpointNamespace`, but we would not have any cross API object reference. Only the indirect reference via the DNS results...

Not sure that really helps the fact that the user can cause the kubelet to act on their behalf connecting to this address. Then again no solution involving the in pod volume definitions can overcome these issues...

**Comment by erictune** [comment]
Impersonate-User feature would address the latter issue.

**Comment by humblec** [comment]
Just to clarify what the code does now, if the `endpoint namespace` is mentioned in storage class parameter, the provisioner create `endpoint/svc` in the mentioned namespace if those didnt exist.    As a second case, if 'endpoint namespace' is filled directly via 'pv volume source spec` or  ` specially crafted glustervolumesource`, at time of mounting,  kubelet give preference to the `ep/svc` existence in mentioned namespace and use it. If no namespace is mentioned ( as its optional) in the volume source,  'pod's namepsace' is used by kubelet   ie  only access happens and  no creation of ep/svc happens  in the latter case.

**Comment by rootfs** [comment]
@erictune @eparis @liggitt DNS looks good solution, can I assume this is the way to go?

**Comment by lpabon** [comment]
Is this closed by https://github.com/kubernetes/kubernetes/pull/31854 ?

**Comment by ReToCode** [comment]
Hello,

A customer using glusterfs in a pretty large OpenShift cluster (3k containers, > 400 PVs) here :)

No I think this is not closed by kubernetes/kubernetes#31854. With heketi you just create/delete the service & endpoints dynamically, but the problem still remains. 

I still don't like that gluster pv definition is different from all the other storage types. Why are not all the information inside the gluster pv object like with other storage types? The current solution has several downsides:

- Mixes things that cluster admins (PV) manage with things project admins manage (Services, Endpoints). Also exposes information to the projects that are not relevant to them.
- Noise in UI/exports/templates/cli and so on
- Redundancy (we have >500 namespaces) so we would have 500x the same services/endpoints
- Updating gluster server IPs is a pain! (even if heketi takes care of parts of it)
- Project admins will (an already did) delete the configs by mistake (read-only seems like a hack...)

I know about your limitations with changing the existing object. Here a few ideas:
```
kind: PersistentVolume
spec:
  ...
  glusterfs:
    path: MyVolume
    endpoints: glusterfs-cluster
    namespace: global-gluster-config  # new optional field
```

If this field is not specified it takes the data from the current namespace. If specified and no access right just write an event with an error message. We would have no problem to add this config to one of our global namespaces where everyone has read permissions.

Or even better, add the information directly to the pv object:
```
kind: PersistentVolume
spec:
  ...
  glusterfs:
    path: MyVolume
    glusterIPs:  # new optional list
    - 10.1.1.1
    - 10.1.1.2
    endpoints: # make optional if possible or we just put a dummy string in there
```
Then if glusterIPs is present, take these IPs, otherwise fallback to current solution.

DNS seems also like a good way to go. I would like to "re-activate" the discussion around this topic.

**Comment by humblec** [comment]
HI @ReToCode, you got most of it, one blocker  was `backward compatibility` or the difficulty to just discard `endpoint` from spec. What we are working on atm is `endpoint namespace` in PV spec and we are on it, it should take are of this issue.

**Comment by eduardobaitello** [comment]
Is that problem solved? I'm in the same situation, my endpoints are in th `default` namespace and pods in another namespaces can't got them.

Too bad that this issue is stalled :(

**Comment by eduardobaitello** [comment]
@hostingnuggets I used the ugly workaround: Create an endpoint and a headless service for every namespace in the cluster that has pods using GlusterFS...

**Comment by hostingnuggets** [comment]
@eduardobaitello thanks for your answer. Uh oh yes that's really ugly but I tried it out and it works... This means that an admin needs to create an endpoint and service for each project within the namespace of that project :-(
