### ISSUE TITLE
Is openshift-master dns required for pull source for build?

### ISSUE THREAD

**Issue by deads2k** [openshift/origin#6355]
I didn't have the master's dns working and my builds were constantly failing immediately on:
```
F1217 01:19:18.531701       1 builder.go:59] Build error: dial tcp: i/o timeout
```
I enable DNS and then I'm able to clone source.  Is this a known limitation?

Also, `oc start-build --follow bc/mythtv-backend-base --build-loglevel=8` doesn't say what its doing before that failure line.  That probably ought to be fixed.

@bparees @csrwng

**Comment by bparees** [comment]
builds run in pods just like anything else, so they get whatever resolv.conf is being injected into any other pod.  if it's not valid, it's going to break builds just like it would break any other code that needs to resolve a hostname. 

and you should see this output in current builds:
`glog.V(4).Infof("git ls-remote %s --heads", url)`
https://github.com/openshift/origin/blob/master/pkg/build/builder/source.go#L84

before that failure.  (i'm assuming that's where you're failing, anyway, since that comes before we attempt to actually clone the repo)

**Comment by deads2k** [comment]
> builds run in pods just like anything else, so they get whatever resolv.conf is being injected into any other pod

Something must have come changed in resolv.conf when I upgrade.  I'll have a look later.

I'll try using the newer builder image with an older master to get the new logging.
