### ISSUE TITLE
oc status doesn't tell me the "to" or "from" image streams

### ISSUE THREAD

**Issue by deads2k** [openshift/origin#6357]
Without this information, its annoying to try to figure out why it thinks a link is missing.

```
[deads@main mythtv-backend-docker]$ oc status -v
In project mythtv-backend on server https://eads-nas:8443

bc/mythtv-backend-base docker build of https://github.com/deads2k/mythtv-backend-docker
  #6 build running for 2 minutes (can't push to image)
    #5 build failed 14 minutes ago (can't push to image)

View details with 'oc describe <resource>/<name>' or list everything with 'oc get all'.
```

**Comment by gabemontero** [comment]
Things appear to have evolved a bit since this was opened.

When a dc consumes the image produced by a bc, the bc's output image is denoted via [this](https://github.com/openshift/origin/blob/master/pkg/cmd/cli/describe/projectstatus.go#L690)

When a standalone bc situation exists, the bc's output image is denoted via [this](https://github.com/openshift/origin/blob/master/pkg/cmd/cli/describe/projectstatus.go#L677)

Leaving the outputs as is, I'm just going to do a small amount of consolidation of how the input image stream is expressed across the various strategies.

**Comment by gabemontero** [comment]
sorry ... forgot to mention that the output image wasn't always set in the image pipeline;  fixing that
