### ISSUE TITLE
Clean-up DC client interface

### ISSUE THREAD

**Issue by kargakis** [openshift/origin#6478]
I am opening this issue specifically for the Scale actions we have added in the interface. Upstream the two interfaces ([Deployment](https://github.com/kubernetes/kubernetes/blob/e24b328f4fe678b880aa111b1c35883785a24c62/pkg/client/unversioned/deployment.go#L31) and [Scale](https://github.com/kubernetes/kubernetes/blob/e24b328f4fe678b880aa111b1c35883785a24c62/pkg/client/unversioned/scale.go#L29)) are separate. I hadn't followed closely the PR that was integrating the HPA stuff with our deployments so I am not sure what was the problem here. 

Is this an issue? Do we really want those calls in our DC interface? Can we change it? If yes, what needs to happen so we can re-use the upstream Scale interface and drop [GetScale](https://github.com/openshift/origin/blob/2fb6435a015a8dacaf984c3e529a6a8f0001171e/pkg/client/deploymentconfigs.go#L28) and [UpdateScale](https://github.com/openshift/origin/blob/2fb6435a015a8dacaf984c3e529a6a8f0001171e/pkg/client/deploymentconfigs.go#L29)?

@DirectXMan12 @ironcladlou @ncdc @deads2k

**Comment by deads2k** [comment]
I like having nicely typed methods sitting directly on the DC interface.  When we're dealing with something specific to DCs, it makes sense to call those methods instead of calling the generic scale.

**Comment by ironcladlou** [comment]
Scaling is totally decoupled from specific resources conceptually, so I think the upstream approach makes more sense. We also need to converge the deployment API with upstream generally.

**Comment by deads2k** [comment]
> Scaling is totally decoupled from specific resources conceptually, so I think the upstream approach makes more sense. We also need to converge the deployment API with upstream generally.

Let's say we have something that wants to specifically scale a DC.  In that case, there's little value in making them go through a generic interface.  In fact, that loses the clarity of what they're doing for most tools.

I'm not arguing against allowing the usage of a `Scale` interface when actually operating generically, but when operating in a non-generic fashion, I'd prefer to have the strong typing and clarity of intent.

One concrete example of this is a `Reaper`.  An RC reaper should only ever scale an RC.  There's no valid reason to allow an RC reaper to ever scale anything else.  There might be an argument for a generic `ScalableResourceReaper`, but that's not what we have today and we don't have sufficient information available via discovery to build on today.

**Comment by ironcladlou** [comment]
>>Scaling is totally decoupled from specific resources conceptually, so I think the upstream approach makes more sense. We also need to converge the deployment API with upstream generally.

>Let's say we have something that wants to specifically scale a DC. In that case, there's little value in making them go through a generic interface. In fact, that loses the clarity of what they're doing for most tools.

>I'm not arguing against allowing the usage of a Scale interface when actually operating generically, but when operating in a non-generic fashion, I'd prefer to have the strong typing and clarity of intent.

>One concrete example of this is a Reaper. An RC reaper should only ever scale an RC. There's no valid reason to allow an RC reaper to ever scale anything else. There might be an argument for a generic ScalableResourceReaper, but that's not what we have today and we don't have sufficient information available via discovery to build on today.

We're not talking about reaper here, but the concrete implementation of the deploymentConfig scaler doesn't accept a `DeploymentConfig`, it accepts a namespace/name and should enforce the type internally (as it conforms to a generic scaling interface that deals in object references).

I think the notion of generic operations applied to object references is pretty common throughout the API and so as a Go client user it doesn't concern me personally. In any case, my main concern right now is consistency with the upstream interfaces. The upstream deployment namespacer doesn't have scale methods. If you feel strongly about it, we should probably be pushing a patch upstream first rather than diverging here and then dealing with the inconsistency when it's time to reconcile our interfaces. All deployment related API refactoring considerations should be upstream-first at this point.

**Comment by deads2k** [comment]
Having typed methods on a `DeploymentConfigInterface` does not preclude using the untyped interfaces `ScaleNamespacer`/`ScaleInterface` that require a discovery/RESTMapper lookup (which don't exist today) in order to function properly.

You're saying we shouldn't provide a fully functional interface and instead force all Go clients to use the generic discovery/RESTMapper instead?

**Comment by ironcladlou** [comment]
>Having typed methods on a DeploymentConfigInterface does not preclude using the untyped interfaces ScaleNamespacer/ScaleInterface that require a discovery/RESTMapper lookup (which don't exist today) in order to function properly.

I agree. I'm just saying that the upstream deployment namespacer (which should ultimately replace ours) does not follow that pattern, and since we're actively trying to replace origin's with upstream's, it seems reasonable to drive a pattern change from upstream downward.

>You're saying we shouldn't provide a fully functional interface and instead force all Go clients to use the generic discovery/RESTMapper instead?

I'm saying clients can use `ScaleNamespacer`.

**Comment by deads2k** [comment]
> I'm saying clients can use ScaleNamespacer.

Yeah, that's the one that requires a discovery/RESTMapper lookup to function correctly.  Its definitely less efficient in some cases (discovery is a remote call), doesn't function properly at all today (the information isn't present to make a choice), and eliminates the ability for compiler to help with validity.

I'd prefer to have both so that we can avoid all three of those problems when possible and still have the generic API when we want to do generic things.

**Comment by ironcladlou** [comment]
I don't really have a problem with the specific interface methods. If they were available, I'd use them. My only overriding concern here is pattern divergence with upstream. If the consensus is it's not a big deal in this case, I'll be perfectly fine to go with the flow.

**Comment by kargakis** [comment]
This is ok for now
