### ISSUE TITLE
how to fix the pod run user?

### ISSUE THREAD

**Issue by pstinghua** [openshift/origin#6493]
My app is spring cloud config server. It use git to pull config files. So It uses git-config file to disable http ssl verify or use ssh private key to authenticate with git server. These files reside in the user home. The default user is 1001.

**Comment by stevekuznetsov** [comment]
For security reasons OpenShift randomizes the uid that any pod is run under. There are two ways of fixing your problem. First, you could change your Docker image to not require a specific UID to run as (the `USER` field in the Dockerfile). Secondly, if you have the cluster administrative rights, you can edit the `restricted` security context constraint:
```
$ oc edit scc restricted
```
To change `runAsUser.Type` strategy to `RunAsAny`. More information [here](https://docs.openshift.com/enterprise/3.0/admin_guide/manage_scc.html#enable-images-to-run-with-user-in-the-dockerfile).

I would strongly suggest changing your Docker image, however, instead of relaxing the security settings.

**Comment by pstinghua** [comment]
@stevekuznetsov Thanks a lot!
