### ISSUE TITLE
About translate the existing docker image to s2i enabled image

### ISSUE THREAD

**Issue by thincal** [openshift/origin#6505]
Is there any tool could adding the s2i stuff automatically into the existing docker image ? Since there should be many repeated settings/scripts to add the s2i support.

**Comment by bparees** [comment]
There's not currently, but s2i (the standalone tool) does have the capability to generate a default set of scripts which you can then customize and add in to your docker image.

A generic tool would be tough since the assemble and run scripts are always going to be image specific, but something that added the standard labels+paths could be possible.
