### ISSUE TITLE
Running extended tests messes with existing kubernetes checkout

### ISSUE THREAD

**Issue by rhcarvalho** [openshift/origin#6583]
Since #5718, an existing working k8s checkout in GOPATH and run extended tests will interfere with each other.

A first execution of `test/extended/core.sh` leaves k8s with HEAD detached at 4c8e6f4, and a subsequent execution fails for me, unless I manually checks out master again.

If I had uncommitted changes or any other thing in my k8s checkout, the test execution will fail (failing to git checkout into 4c8e6f4).

**Comment by rhcarvalho** [comment]
@smarterclayton since it was added as a WIP, do we still need that step in `core.sh`?

**Comment by smarterclayton** [comment]
Yes, we need the examples.  How we get the examples can be cleaned up.

**Comment by rhcarvalho** [comment]
What examples? Why can't we use the vendored copy of kube?

**Comment by smarterclayton** [comment]
Because you can't vendor directories via godep that don't have go source
code.

On Jan 11, 2016, at 5:02 AM, Rodolfo Carvalho <notifications@github.com>
wrote:

What examples? Why can't we use the vendored copy of kube?

—
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/issues/6583#issuecomment-170494653>.

**Comment by rhcarvalho** [comment]
@smarterclayton could you point what files you're referring to?

**Comment by smarterclayton** [comment]
Everything in examples/

**Comment by rhcarvalho** [comment]
Fixed by #7094
