### ISSUE TITLE
Use swagger (or something) to detect client/server drift

### ISSUE THREAD

**Issue by deads2k** [openshift/origin#6600]
Since our clients have built-in conversions that used prior to contacting a server, an old client talking to a new server can strip out fields.  (See the problem this caused in https://github.com/openshift/origin/issues/6555).  

Since we build both, we can detect whether the server level of a particular group,version,kind is different from our own.  There is enough information to know ahead of time whether we will strip fields, but it is certainly not trivial.  

@smarterclayton is this something we want/need?

**Comment by smarterclayton** [comment]
Interesting.  Another suggestion has been a schema version (the unique
number that corresponds to the rev of this object schema, within an api
group). A third suggestion has been feature flags.  Swagger is a good place
to start since we have it available.  Detection of drift is more fraught,
since we can only apply the grossest calculations.

**Comment by smarterclayton** [comment]
We should try to get maximum value for minimum complexity - i.e. an "doesServerSupportFieldX" that returns `ok bool, err` and checks the local swagger cache for the field for an object.  I suspect in most places we would display warnings, rather than errors.
