### ISSUE TITLE
Provide official homebrew package

### ISSUE THREAD

**Issue by luebken** [openshift/origin#6689]
Homebrew is the de facto standard for installing packages on a Mac and used a lot in the developer community. Providing an official package and including them in the docs would ease the onboarding for Mac developers. An unofficial package can be found here https://github.com/nak3/homebrew-openshift

**Comment by elyscape** [comment]
I have improved some on @nak3's recipe [in this commit on my fork of Homebrew][recipe]. I haven't yet submitted a pull request because @nak3's recipe is licensed under the Apache license, whereas Homebrew is licensed under [something else][homebrew-license]. I've sent him an email asking permission to release a derivative work under the Homebrew license.

[recipe]: https://github.com/elyscape/homebrew/commit/f0a0e4fa8e793f93df2bb388972983d2944e60aa
[homebrew-license]: https://github.com/Homebrew/homebrew/blob/master/LICENSE.txt

**Comment by elyscape** [comment]
Update: @nak3 emailed me back and authorized me to go ahead.

**Comment by smarterclayton** [comment]
That's fantastic - thanks!

**Comment by elyscape** [comment]
There is now an `openshift-cli` package in Homebrew. This should probably be added to the documentation somewhere.

**Comment by smarterclayton** [comment]
@adellape perhaps this would be on the developer getting started in the origin docs?

**Comment by adellape** [comment]
Docs PR created: https://github.com/openshift/openshift-docs/pull/1467

**Comment by smarterclayton** [comment]
This has now been completed.
