### ISSUE TITLE
Exposing container port in OpenShift

### ISSUE THREAD

**Issue by lorenzvth7** [openshift/origin#6813]
I have a selfcreated image. Created from a dockerfile which is exposing a port (8888).
So I just perform a ```docker run my-nodejs-image```. The port is open (but not mapped). This is what I try to achieve in OpenShift.
When I let OpenShift create a container of my image, it does not show an open port. And so my other container is going in a restarting-loop because it can't access the nodejs-container with the exposed port.
I tried to edit it manually but it was not possible to change ge ports in die pod-config of a running container.
```
oc v1.1.0.1-1-g2c6ff4b
kubernetes v1.1.0-origin-1107-g4c8e6f4
```

But when I go to the logs of my container I see:
```CORS-enabled web server listening on port 8888```
But nowhere I can see that the port is open and the container container can't connect with it.
My service shows ```80/TCP → 80 ``` so this will probably mean: 80 is open and mapped on 80 of the server. So I think I need ```8888/TCP``` for my container/pod.

**Comment by pweil-** [comment]
Container ports can be specified in the pod spec.  Here is an example of exposing a port on a simple pod: https://github.com/openshift/origin/blob/master/examples/hello-openshift/hello-pod.json#L18

After creation, you should then be able to curl the pod's ip address and port.  However, since pods can be moved (node failure, etc) and the ip address could change you should use a Service or Route to address your pod.

Service documentation: https://docs.openshift.org/latest/architecture/core_concepts/pods_and_services.html#services

Route documentation: https://docs.openshift.org/latest/architecture/core_concepts/routes.html

**Comment by fabiand** [comment]
@pweil- According to the k8s docs all pods can reach all ports of all other pods. Further more the k8s pod spec tells us that the [containerPort is optional](https://kubernetes.io/docs/api-reference/v1.6/#podspec-v1):

> List of ports to expose from the container. Exposing a port here gives the system additional information about the network connections a container uses, but is primarily informational. Not specifying a port here **DOES NOT** prevent that port from being exposed. Any port which is listening on the default "0.0.0.0" address inside a container will be accessible from the network. Cannot be updated.

So I wonder - Does OpenShift behave different than K8s?

**Comment by pweil-** [comment]
@fabiand this depends on your networking setup.  Some administrators prefer to have per-tenant isolation in which case pods in one namespace would not be able to reach pods in another namespace.  But you'd likely know if this was the case because the cluster would've been configured to use the `ovs-mutitenant` plugin for the SDN

If you are just using the `ovs-subnet` plugin you would have a flat network.  More information on the plugins [can be found here](https://docs.openshift.org/latest/architecture/additional_concepts/sdn.html#architecture-additional-concepts-sdn)

**Comment by fabiand** [comment]
Oh right, I was not even speaking about multi-tenancy, but rather trying to clarify the question for the single tenant/namespace case.

So, within a namespace, on OpenShift, can all pods reach all ports of all other pods (like it is in kubernetes) without specifying the containrePort? @pweil-

**Comment by pweil-** [comment]
@fabiand right, the network should be flat and pods should be able to reach other pods.  

I would still recommend defining the container ports. The container ports and protocols are used in validation as well as some of the cli interactions (like `expose`).  In some use cases, like exposing a host port (which is generally not recommended), the container port is required.

**Comment by fabiand** [comment]
Thanks. Twice.

because now I see why the containerPort has value - for i.e. `expose` :)

And yes, I was just asking because of a particular case where we are running a daemon in a cluster (libvirt) which is dynamically opening ports. The questionwas if we need to poen the ports ahead of time or not. But this is not the case as I understood and now confirmed it.

(I guess that our confusion came up because we were mixing it with `hostNetwork` and `publicIP` settings)
