### ISSUE TITLE
oc rollout support for DCs

### ISSUE THREAD

**Issue by kargakis** [openshift/origin#6896]
Forked from https://github.com/openshift/origin/issues/6752

`rollout` is curently added in kubectl, will be brought in most probably by the rebase after the next one (unless we choose to pull it as UPSTREAM commits). 

It will supersede `oc deploy` which we should deprecate and burn.

cc: @ironcladlou @fabianofranz

**Comment by smarterclayton** [comment]
I'd like to get oc deploy repurposed for "deploy a microservice" as part of the new-app split as soon as possible. What are the implications of adding rollout?

**Comment by kargakis** [comment]
We just need to conform to a bunch of kubectl interfaces. Unfortunately most of the subcommands are still wip so I am not really sure at this point if there will be something more than that.

**Comment by kargakis** [comment]
@smarterclayton how do you feel about pausing all deployers' containers on `oc rollout pause`? Should also remove any config change trigger. `oc rollout resume` would unpause and add the trigger back. It would have to play well with ProgressDeadlineSeconds

**Comment by smarterclayton** [comment]
We'd have to add that feature check into both recreate and rolling
updater.  But in general I think we want it.

On May 12, 2016, at 7:38 PM, Michail Kargakis <notifications@github.com>
wrote:

@smarterclayton <https://github.com/smarterclayton> how do you feel about
pausing all deployers' containers on oc rollout pause? Should also remove
any config change trigger. oc rollout resume would unpause and add the
trigger back. It would have to play well with ProgressDeadlineSeconds

—
You are receiving this because you were mentioned.
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/issues/6896#issuecomment-218915781>
