### ISSUE TITLE
Logs in the web console don't support ANSI escape sequences and carriage returns

### ISSUE THREAD

**Issue by rassie** [openshift/origin#6931]
Logs in the web console do not support any kind of escape sequences. In particular, carriage return (`^M`) is not supported which leads to following output when Maven is downloading files (`^M` is included in the output, but obviously not visible):

![image](https://cloud.githubusercontent.com/assets/23448/12712890/e34d1e3a-c8cb-11e5-97b3-ed708e0a178b.png)

Neither are ANSI color sequences supported, which leads to the following output with `npm`:

![image](https://cloud.githubusercontent.com/assets/23448/12712897/f5b01ffa-c8cb-11e5-81bc-84ecad268cb5.png)

Normal console logs (`oc logs build/...`) work, however I suspect there is just no special treatment, since the sequences are output to the terminal, which supports them.

Would be nice if log output on the web could be as colorful as in the terminal :)

**Comment by benjaminapetersen** [comment]
We may already have an issue/enhancement for this.  I'll check.

**Comment by jwforres** [comment]
the colorization is a dup of https://github.com/openshift/origin/issues/5453  but any other escape codes werent being considered in that original issue so we can leave this open for the newline problem

**Comment by benjaminapetersen** [comment]
We have a couple options for doing this.  I don't think we want to reuse [our terminal](https://github.com/chjj/term.js/blob/master/src/term.js) for the logs, though it probably handles all the escape codes fine.  I imagine it would work for small logs, but once we get thousands of lines performance would worry me.

I'm looking at [ansi_up](https://github.com/drudru/ansi_up/blob/master/ansi_up.js), [ansi2html](https://github.com/agnoster/ansi2html/blob/master/lib/index.js), and [ansispan](https://github.com/mmalecki/ansispan/blob/master/lib/ansispan.js).  As far as features go, ansi_up looks the best, but I'll have to check performance as well. It's gonna do a `new Ansi_Up()` on every line, which will probably be expensive.  ansi2html is just basic functions, no prototype chain to setup, but looks like it may only be doing colors :confused:

Otherwise, may just have to home grow the transformer function...

**Comment by jwforres** [comment]
Moving to trello https://trello.com/c/goZPKVEm

**Comment by MetaMmodern** [comment]
hello, @spadgett . I see you implemented this. My team uses openshift web version 3.10 and I don't see color output when logging from node.js using chalk library(and also when logging Jest output). The text is just white on black. Is this implemented in newer version or somethins is wrong?

**Comment by spadgett** [comment]
@MetaMmodern Unfortunately, we haven't implemented this yet in 4.x. We have https://issues.redhat.com/browse/CONSOLE-402 and https://github.com/openshift/console/issues/9126 tracking.
