### ISSUE TITLE
Role composability

### ISSUE THREAD

**Issue by kargakis** [openshift/origin#6955]
I stumbled across https://github.com/openshift/origin/issues/5228 and it occured to me that in order to add an admin(=images,builds,deployments) pruner I basically need to re-use all the rules used by an imagepruner, a buildpruner, and a deploymentpruner. Wouldn't it make sense to optionally compose roles out of other roles?

Pros:
- Composability per se; I don't need to reimplement everything if previous roles overlap with new.
- Maintainability. We need to edit one role, changes propagate to any dependent roles w/o the need to update those.

Cons:
- More complexity at the same time in the authz api? We should take care of things like cyclic deps.

@openshift/api-review  thoughts?

**Comment by deads2k** [comment]
I don't think that ready to do that.  From a technical perspective its not very difficult, but I don't think that it will enhance the understandability of the system and that's a problem that we're already facing.  I'm also not sure that I've seen enough cases of people wanting to compose new roles from existing ones.  Usually they want to start with one role and add or remove unique powers to it.

If you're interested in authorization, there are two problems I'm very interested in trying to solve :)
 1. Field level authorization.  I want to be able to describe ranges and limits for arbitrary fields and bind those rules to users.
 1. Resource name bindings.  Right now resource name restrictions are on the role.  That makes a lot of sense from an ease of expression point of view, but it would be nice to be able to express it on a binding.  The problem is deciding which policy rule a name restriction should be applied to.

**Comment by deads2k** [comment]
@smarterclayton I'm inclined to close.  Do you disagree?

**Comment by smarterclayton** [comment]
I think complexity of this is sufficient that it would need a very strong use case to justify (not just "it makes internal dev easier" but "as a user I need to compose roles in order to accomplish X"), which isn't included here.  Reopen with that use case if necessary.
