### ISSUE TITLE
Pulling image should create an Event

### ISSUE THREAD

**Issue by jhadvig** [openshift/origin#6996]
When the image is being pulled into ImageStream we should be able to detecting by creating an Event. We should use that eg. in the web console to show that the build is not running yet, just "Pulling the image" at this moment.

@mfojtik @bparees @jwforres @spadgett @thesteve0

**Comment by pweil-** [comment]
@soltysh

**Comment by jhadvig** [comment]
@pweil- :+1:

**Comment by smarterclayton** [comment]
You mean like:

```
23m         23m        1         router-1-i4vvh    Pod                     spec.containers{router}       Normal    Pulling             {kubelet openshiftdev.local}     pulling image "openshift/origin-haproxy-router:v1.1.1"
```

**Comment by mfojtik** [comment]
@smarterclayton yes, but they want to see that in overview page...

**Comment by smarterclayton** [comment]
Practically, aren't most builds that haven't yet started running but have been scheduled pulling?

**Comment by mfojtik** [comment]
@smarterclayton yes, if we can get that information to overview page, so you know what is happening when you just create the app. At least that was what marketings guys want.

**Comment by thesteve0** [comment]
Having a spinning wheel for 3 minutes without saying why it is spinning
looks a lot like "broken". It is just to give the end user feedback about
why it is taking so long

**Comment by smarterclayton** [comment]
We can just say "pulling image".  It's right 90% of the time.

**Comment by thesteve0** [comment]
Well right now we look vague and broken 100% of the time

**Comment by bparees** [comment]
There are (at least) two image pulls in question here:

1) pulling the origin-sti-builder image in order to start the build pod.  the pod will be in pending while this is happening (and this will be exceptionally rare)
2) pulling the base s2i builder image (eg ruby-s2i) as part of the s2i process.  This will happen when the pod is running and it may not be pulling via an imagestream at all (s2i can do direct docker references).  

What case are we actually talking about?  Because in case (2) it shouldn't look "stuck" because at a minimum the git clone operation will have happened, which should be obvious from the build logs.

**Comment by bparees** [comment]
@jhadvig bump.  please see my question 2 comments up.

**Comment by bparees** [comment]
@jhadvig bump again or you're not getting your package :)

**Comment by bparees** [comment]
closing since i can't get details on what is being asked for here.
