### ISSUE TITLE
Kubernetes does not restore state for Pods after reboot

### ISSUE THREAD

**Issue by mfojtik** [openshift/origin#700]
This happen after rebase, when you start the cluster (OPENSHIFT_DEV_CLUSTER=true), create bunch of Pods and wait for them to be running and then reboot (vagrant halt/vagrant up) all Pods remain in the Unknown state.

When I checkout to 05759a0 and retry, then the Pods gets into Running state.

**Comment by mfojtik** [comment]
@goldmann @smarterclayton  fyi

**Comment by goldmann** [comment]
This is probably related to https://github.com/openshift/origin/issues/711.

**Comment by smarterclayton** [comment]
It looks like the kubelet, on startup, wipes all the pods.  Then it never brings them back up.

**Comment by smarterclayton** [comment]
Maybe because the sync loop isn't running...

**Comment by smarterclayton** [comment]
Looks like the watch from the kubelet to etcd fails during startup, and then since the source isn't ready, it's not until the next sync interval that we check again and find the pods.  That's 30seconds.  So it seems to be a race between kubelet and master - we may want to do a quick poll until the master becomes available instead of doing a long loop.

**Comment by smarterclayton** [comment]
This was a bug upstream, I'm going to back port the fix 009c5e1129a2998400ea56212d50498bedebd66c

**Comment by smarterclayton** [comment]
Upstream was https://github.com/GoogleCloudPlatform/kubernetes/pull/3479
