### ISSUE TITLE
Cannot list all componentstatuses in the cluster

### ISSUE THREAD

**Issue by moortimis** [openshift/origin#7140]
Seem to be still experiencing the issues discussed in https://github.com/openshift/origin/issues/5973. Hoping someone can help. 

**Methods to reproduce**

1. Install OpenShift Origin v3.1 using byo playbook
2. Deploy ManageIQ Capablanca (capablanca-1.20160209142121_d9bbf5f)
3. Configure Kubenetes service account  
- https://access.redhat.com/documentation/en/red-hat-cloudforms/version-4.0/managing-providers/#configuring_service_accounts
4. Ensure additional permissions have been applied as per previous issue.   https://github.com/openshift/origin/issues/5973

**ERROR**
```
[KubeException]: User "system:serviceaccount:management-infra:management-admin" cannot list all componentstatuses in the cluster  Method:[rescue in block in refresh]
```

**Software Versions**
- origin-sdn-ovs-1.1.1.1-0.git.0.ce0e67f.el7.centos.x86_64
- origin-node-1.1.1.1-0.git.0.ce0e67f.el7.centos.x86_64- 
- origin-master-1.1.1.1-0.git.0.ce0e67f.el7.centos.x86_64
- origin-clients-1.1.1.1-0.git.0.ce0e67f.el7.centos.x86_64
- origin-1.1.1.1-0.git.0.ce0e67f.el7.centos.x86_64

**Related**
- https://github.com/openshift/origin/issues/5973

**Comment by liggitt** [comment]
Component status API objects are not enabled in default OpenShift policy because of inflexible assumptions in the way they were built that do not allow them to work within an openshift deployment. See https://github.com/openshift/origin/issues/3667 for details and to track enablement of that API object if upstream changes allow it to be enabled.
