### ISSUE TITLE
The </> character in overview page

### ISSUE THREAD

**Issue by mfojtik** [openshift/origin#7179]
![screen shot 2016-02-10 at 15 28 30](https://cloud.githubusercontent.com/assets/44136/12949971/126b58f8-d00b-11e5-8fcf-9ffa48b3bdbb.png)

I don't really get what that character is standing for :-) Also:

1) It prevents from selecting the text if you double-click :-)
2) If the reason it exists is to divide between build number and commit message, maybe we can just make the commit message italic? :)

**Comment by mfojtik** [comment]
@jhadvig and me talked about this some time ago :-)

**Comment by jwforres** [comment]
That is a standard icon that means "code" or "source" but I will think about alternatives.

@danmcp is there a reason you marked this as P1 ?

**Comment by danmcp** [comment]
@jwforres Feel free to change.  I think I thought it was worse when I first looked it over.

**Comment by jwforres** [comment]
The icon looks better when its next to the repo URL, when we have the commit info instead it does look a little off.

**Comment by jwforres** [comment]
@spadgett putting in 1.2 since you already have that change we discussed

**Comment by mfojtik** [comment]
<img width="18" alt="screen shot 2016-02-12 at 12 33 43" src="https://cloud.githubusercontent.com/assets/44136/13005818/e29a4686-d184-11e5-9bc9-3bc0b9781c1a.png">

@spadgett @jwforres can't we steal the Github "commit" icon? It is just simple SVG ;-)

**Comment by spadgett** [comment]
Interesting, that icon means less to me than the one we're using :) Maybe it's because I've done so much XML and HTML.

Note it's not always a commit. It's sometimes just the Git repository. We could use different icons depending on whether we have commit information.

The icon we have now is the Font Awesome icon for code:

http://fortawesome.github.io/Font-Awesome/icon/code/

@mfojtik Is there any you can suggest from Font Awesome?

https://fortawesome.github.io/Font-Awesome/icons/
