### ISSUE TITLE
[RFE] webui should show events/info related to a pod's pending status

### ISSUE THREAD

**Issue by thoraxe** [openshift/origin#7215]
As an example, if an NFS mount is failing, the pod status is permanently "pending" with no real way to figure out what's going on unless you dive into the events list.

**Comment by mfojtik** [comment]
@jhadvig FYI

**Comment by jhadvig** [comment]
There already is a PR for this -> https://github.com/openshift/origin/pull/7164
where you will be able to filter events based on the type

**Comment by jwforres** [comment]
Yeah @jhadvig's PR should help a lot.

We also have a plan to improve it further if it doesn't cause perf issues by fetching the events as soon as you go to the pod page and showing the number of "warning" level event on the events tab label. 

A third improvement we are considering would be to always watch for warning events across the whole project and surface them at the top as a flagged list of issues, but again we need to make sure it doesnt' become a perf problem (events are really chatty).

Closing since this is in trello https://trello.com/c/DRFgGKxF
