### ISSUE TITLE
Web console should allow editing project display name and descr.

### ISSUE THREAD

**Issue by thesteve0** [openshift/origin#7315]
As a user I want to be able to add or edit the display name and description. It should appear on the project overview page

**Comment by spadgett** [comment]
This is on the settings page now, but not the overview.

**Comment by thesteve0** [comment]
Yeah I saw it there and I forgot the 3 dots are the shortcut to edit. Can we please just add a delete and edit icon after the title for ALL THINGS (tm) :)

**Comment by spadgett** [comment]
We're discussing the dropdown more in #6973. I agree it's too easy to miss. Feel free to weigh in there.

It's like that now as a Patternfly recommendation where primary actions are buttons and secondary actions are in the menu. (Everything collapses to a menu on mobile.) We purposely made edit YAML and delete secondary actions for better or worse because

1. Edit YAML was seen as advanced, and we're adding regular edit forms to resources (see the build config editor).
1. Delete is uncommon and destructive. We didn't want it to be easy to accidentally click.

Whatever we do, we'll need room to add additional actions. For instance, this is the deployment config menu (with one action that hasn't merged yet).

<img width="209" alt="screen shot 2016-02-15 at 5 34 20 pm" src="https://cloud.githubusercontent.com/assets/1167259/13062165/766eb98c-d40a-11e5-80d4-ac734dc787e5.png">

We might add attach storage to that menu as well.

/cc @jwforres @ajacobs21e

**Comment by thesteve0** [comment]
I agree maybe about edit YAML if we had forms but for now the only way to edit items is to edit the YAML. Delete should be exposed since people want to do it a lot and it is hard to find

**Comment by ajacobs21e** [comment]
@thesteve0 - @rhamilto and I spoke about this and he pointed out that whether or not delete is a primary action may be contextual. For example it may be more common to delete a pod than a service. 
Would it make sense to make delete a primary or secondary action based on context?
@spadgett

**Comment by spadgett** [comment]
@thesteve0 When do you find that you delete items?

@ajacobs21e I'd say deleting a pod is uncommon since it is often controlled by a replication controller. When it is, deleting the pod will result in another just like it being created. It's not something we'd encourage. If the pod doesn't have a replication controller, then it makes sense. It's contextual even for resource types.

I'm also hesitant to make it a primary action for some resources because we don't do cascading deletes. If you delete a build config in the web console, none of the builds are deleted. Same for deployment config. You probably want to delete those using the CLI. In fact, we might add a warning about this to the dialog.

**Comment by ajacobs21e** [comment]
@spadgett makes sense. I'm not familiar enough with the use cases so I'll default to you and @thesteve0 to determine if/when any of these actions should be primary. 

At some point in the future will the console be able to do cascading deletion?

**Comment by jwforres** [comment]
Yes we have an open trello card for it, we are blocked waiting on API
support, the CLI is doing the cascade itself when it really should have
been handled by the API.

**Comment by thesteve0** [comment]
I delete build configs, deployment configs, basically everything when I am trying to clean up or things get stuck. 

I definitely delete pods since then I can control which pod goes away. Scaling down with a RC does not let me control that.

**Comment by jwforres** [comment]
we have moved the edit project icon to the project list page now, and for all other resource we have switched to a big Actions dropdown instead of the kebab menu.
