### ISSUE TITLE
Scaling router to zero and then back up sometimes causes conflicting routes to be admitted

### ISSUE THREAD

**Issue by jwforres** [openshift/origin#7386]
Create two routes in a namespace that request the same host, one will be admitted and one will be rejected.
Scale the router DC to 0
Scale the router DC back to 1
Expected: The admission status of the existing routes shouldn't change
Actual: The admission status of the existing routes sometimes changes.  You can end up with both routes saying they are admitted.

Exported svcs and routes from an example project, this is in the correct state: https://gist.github.com/jwforres/4a234e526754e3624465

And these are specifically the two routes that are conflicting after scaling down/up the router:
https://gist.github.com/jwforres/2aa298e977b9f13ad794

**Comment by smarterclayton** [comment]
Two problems here:

1. We weren't doing resync / initial sync in a stable order - so newer routes could go first, get assigned, then removed.  Also, we need to defer the first sync until all routes have been processed, which avoids a massive amount of churn.  Will handle that separately.
2. Rejections were generating identical writes (except for a new timestamp) to the server because a condition was removed that compared based only on the reason and message.  Fixed that.
