### ISSUE TITLE
Router should test config before reloading

### ISSUE THREAD

**Issue by pweil-** [openshift/origin#7403]
In order to prevent a completely broken router the router should be able to:
1.  test config if the implementation supports it to ensure validity before reloading
2.  if there isn't a way to ensure validity it should be able to revert to a previous config if it cannot restart with the new config

In the event that an invalid configuration is generated the router should send an event and log any message received from validation or command execution.

@ramr @rajatchopra

**Comment by ramr** [comment]
I guess we can do `haproxy -c` before doing the reload to check if the config is syntactically correct but this is not going to catch everything - there are other possibilities for breakage. 
Would also need to store 2 versions of the config in memory for the openshift-router - the previous valid config and current config.

**Comment by marun** [comment]
@ramr Is there a reason to accept bad key/cert data in the first place?  That seems like something that would best be caught on object creation/update.  Assuming routes/router objects that were sufficiently validated, how likely is it that configuration generation is going to produce a syntactically correct result but subsequently fail to do so?

**Comment by ramr** [comment]
@marun it is true that we can and should do a better job validating the routes (certs + keys) but there could be scenarios beyond the initial validation where it could fail. Example key and certificate combination is not valid (both could be valid independently) or dest CA cert has no provided keys etc. And some errors might be only occur at run-time (when the pod returns content) - certificate not for host, etc. I think we have to be resilient on all "fronts".

**Comment by marun** [comment]
@ramr I understand that field-level validation (i.e. certs and keys in isolation) wouldn't be enough, but what would object-level validation (i.e. all fields of a route) not be able to catch?  

Regarding runtime cert issues in a 'reencrypt' configuration, what kind of resiliency would be possible?  Even with a previous configuration that was known to be 'good', reverting might not fix the problem if the the endpoint certificates had changed in the interim.

**Comment by liggitt** [comment]
it's the multi-tenant nature of the router that is the issue. if a bad cert/config for a particular route made if through other validation layers, the router shouldn't take down other routes because of a bad generated config

**Comment by marun** [comment]
@liggitt So long as the configuration generation mechanism is well-tested, and the data is validated before generation is attempted, how would bad configuration result?

**Comment by marun** [comment]
Apologies if this is an obvious question.  I'm still learning about routes/routers and don't understand how bad cert/config could slip through creation/update validation.

**Comment by liggitt** [comment]
unless we can prove we know all the conditions that could cause a config to fail (doubtful), we should make sure we handle the failure case gracefully

**Comment by marun** [comment]
Fair enough.  So failing gracefully involves reverting to known-good configuration and potentially blocking further router updates until the bad routes are fixed or removed manually?  If bad routes can't be caught on creation/update I'm not clear how they could be otherwise detected after the fact, and configuration updates being coalesced would seem to further complicate detection of the offending routes.

**Comment by pweil-** [comment]
also, last time I checked, golang didn't provide the ability to validate all the different kinds of cert formats that a router could support.  We would have to enforce particular formats on the api side which is too restrictive.  Much better to require the routers handle failures gracefully and update route status with rejection reasons.

**Comment by ramr** [comment]
So how's this sound as a potential fix/solution here:

-  Do some validation on route creation (we can add more here as golang gets better support). 
-  In this case the error handling in the haproxy/template case is an issue, F5 is a lil' more resilient in
    that it would just ignore the invalid config and still manage routes/endpoints as they change.   
   So for the haproxy/template case - inside the router `AddRoute` method, how about if we  generate a 
   temporary config using the templates. Let's assume that the config file gets written to a new path 
   `$haproxy_config_new`. And we would also ensure the certs/keys/related config get written to say a 
   temporary directory (ala /tmp/$config_check/*) and it gets used from there in the temporary config.
-  We would then run a config checker script (`config-test` or whatever we call it) that really just
   needs to do a `haproxy -c $haproxy_config_new` to check if the config is valid. 
- If the config check fails, add a status to route indicating that the route has not allowed in because of
   the relevant error and not store that route. 
- We probably also need to beef up some of the checks in add/delete endpoints as we don't have the 
   service unit.

That way we could ignore the badly configured routes but still process the good ones that follow. And the status indicates why a route was not allowed in.   How's that sound?

/cc @smarterclayton

**Comment by pweil-** [comment]
> Do some validation on route creation (we can add more here as golang gets better support).

What additional validation would you implement? If we can't guarantee the integrity of a cert I'm not sure it's worth all the extra effort.  Especially if we're going to say that the router needs to handle it gracefully. 

> We would then run a config checker script

I think this is the way to go.  Are you thinking that we would do this in a separate worker process or in the main thread that calls AddRoute?  I guess for simplicity doing it inline may be a good first step and if it's fast enough then no big deal.

Would you do the config check write with total state or just the incoming route?  Using a single route would be faster but I guess there is still the chance that something goes wrong when it is written in conjunction with other routes.

**Comment by smarterclayton** [comment]
What's the cost of doing the check?  Is it as expensive as trying to
load haproxy?  If we have 100k routes will we double the reload CPU
and time?

What do we do if the config check fails?  How would an admin know the
config is bad?  How would they fix it?

**Comment by ramr** [comment]
To answer specific questions.
@pweil- The extra validation might not be needed if the config checker is in place (Clayton's comments addressed ahead). But it doesn't hurt to do some checking beforehand as it is part of the route creation flow. It could be as simple as just checking the PEM format/contents are valid. That could be done at a later time as well.
And yes, was looking at doing the config-test inline (in the AddRoute processing flow) for the first pass.

We would specifically just test the new route [realized I hadn't put that down/made it clear]. So it would be as if _only_ a single service unit existed in the config and the template was processed with that.
So just 1 cert, key, cacert, dest cacert would be written to a temp location and the generated haproxy test config would have just a single backend (for the route). 

@smarterclayton The cost of doing the check would be minimal as its only validating the config and not doing a reload. Plus its only generating the config as if the router configuration just had a single route.
As a rough comparison point using `time` on my vm with a configuration containing 12 routes - its on an average 200ms for a reload vs 8ms for config check. That's roughly about 4-5% of the cost of a reload.
But that said, there would be some extra overhead with each route add/modification. 

And the second part re: recovery or a config check failing, we would not admit that route in and the route status would indicate the error [similar to a route was already admitted status]. The admin could see the errors via the router container logs (we would log the error from `haproxy -c` in the router container). 
As re: the admin needing to fix it, the operational workflow would be a lot simpler. The onus would be on fixing the config on the route rather than an admin needing to intervene.
As an example if you have 10 routes and 1 of them has a bad config - we would still use the remainder of the 9 routes to generate the haproxy config. The 1 bad route would have its status set to indicate the error. As more routes get added (good config), they would also pass the config-check and so get added to the haproxy configuration and would work better than the way we do it currently - where reload fails and the admin has to remove the bad route in order for the router to pick up the rest of the "good" routes.

**Comment by smarterclayton** [comment]
How often do we have "bad" routes?  If we validated certs in admission, do
we need to do anything else?  I don't really like the idea of factoring the
admission code so that it has to know about config testing, although I'm
sure we can factor it in a minimally invasive way.  I don't really like the
idea of closely coupling routes with how the template generates them in
config (for one thing, it makes it harder to extend a router).  I like
checking the config before we reload.  If we allowed custom annotations, we
increase the chance of "bad" routes.

Can we guarantee routes are added in isolation and that the individual test
is good enough (i.e. can two routes conflict when individually they load
fine)?  If we add the optional "test this config in isolation", how well
will that hold up as we refactor the router?  Do admins who want to
customize our template have to provide a different template config for the
route?  What if someone's template config fails when run with the test
route?  If I restart the router, do we have to test all 100k routes in
sequence before loading?  Can we afford to do that?

A less invasive change might be to add a sequence number to the admission
process that increments each time something changes, and we log info about
the route name and its sequence number, and if we fail the config check we
just exit reload with 0 and write a log message about the config sequence
we failed to load.  That's still hard to debug though.

**Comment by ramr** [comment]
@smarterclayton  valid points re: startup + testing in isolation as opposed in conjunction but all this is keyed off the route host - we don't allow duplicates, so there is some merit to testing it in isolation vs in conjunction which will happen anyway (when the config is reloaded). We can't guarantee anything even today - a custom router config or even a bad route prevents anything new from being added  - so we are in the worst case, much better off than today. 
There is a startup issue to consider - we could be a bit smarter and not do a validation on every single attempt - aka check it once or really only do it if the object has been modified. That reduces the cost considerably. The status would indicate when we last checked the route. 

As re: coupling routes to the template - I think we need to do some validation of routes on admission - in some implementations this would be a noop (aka for F5s), in others it would well be more involved - imagine a custom router which uses some scripting (ala lua) which does validation before adding/allowing a route in.  

Admins shouldn't need to customize with a different config specifically for a route - they could if they wanted but the current template would work - instead of it being run on a set of routes, its done on a single one [set size = 1].

I'd say its more of downside today where when we have a broken route - it basically prevents any more routes being admitted in. The config check /reload fails and requires operator intervention to remove the bad route from the system.

**Comment by smarterclayton** [comment]
Fairly certain this was all resolved during the cert fix run-up.
