### ISSUE TITLE
Router should not write config until initial sync has completed

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#7409]
It appears that the router is not waiting to write state to disk for the initial sync to be completed (not totally positive, but I don't see any of the code that would allow it).  We should not perform the first write until the cache store indicates all routes, namespaces, and endpoints have performed their initial sync.  That's possible to check by looking at the cache store resource version - if it is set, then the store has viewed all objects.

Setting p1 since this can result in fluttering routes - rejections during a restart.

**Comment by smarterclayton** [comment]
@ramr fyi

**Comment by smarterclayton** [comment]
Brought up while looking at #7386

**Comment by smarterclayton** [comment]
This can slip to 1.2.x if necessary.

**Comment by marun** [comment]
I'm going to tackle this.

**Comment by marun** [comment]
@smarterclayton Routes and endpoints each use a reflector which track separate resource versions for their respective collection, but at present the router doesn't have a way to get those versions.  The reflector does pass the resource version to the event queue's Replace() method but at present the queue does nothing with the value.  The resource version of namespaces doesn't appear relevant because the namespaces are used to filter routes rather than being stored on their own.

Even if the resource version were propagated such that the router could use it to know when the initial sync to a given event queue had been performed, would that be useful without the router having actually processed the queue?  What do you think of adding a new event type indicating the end of the events for the initial sync and have the event queue signal the router by adding an instance of the new event to the end of the queue in Replace()?

Given that the sync is performed separately for endpoints and routers, there exists the possibility that the endpoints and routes initial sync will be disjoint, but I'm assuming this is not relevant and that the primary consideration is that the route cache is as current as possible.

I'm assuming that once the initial sync for endpoints and routes was complete, the router would have to ensure that FilterNamespaces was called at least once on the resulting state, and that only then could configuration safely be written.

Thoughts?

**Comment by knobunc** [comment]
This is also bug https://bugzilla.redhat.com/show_bug.cgi?id=1320233

**Comment by liggitt** [comment]
> What do you think of adding a new event type indicating the end of the events for the initial sync and have the event queue signal the router by adding an instance of the new event to the end of the queue in Replace()?

Are you referring to a watch event?

**Comment by smarterclayton** [comment]
That could work.  Another option - have a boolean on the router that
indicates whether a write could fire, and have the template plugin check
whether that boolean is available before writing.  I'm a *little* weirded
out about including a new type of events, but we've discussed it in the
past.  From a general code separation, I'd say that upstream in all the
code we've tried to avoid adding new event types into the reflector / watch
/ queues, and instead rely on a separate path to indicate whether the data
is allowed.  The project cache does something similar, and they recently
updated the controllers to more clearly utilize LastSyncResourceVersion().
In the future, we may have to watch more items (ingress + services) so
we'll definitely want a solution that combines those.

I'm ok with a fake event I think, but taking a look at the most recent
additions to the controllers upstream would be good.  Ultimately the router
probably needs to hew more closely to being treated like a controller (and
may be refactored onto the upstream controller library) so an approach that
fits into that long term path is a good hedge.

**Comment by rajatchopra** [comment]
Extending on the boolean on the router - use a Peek() function accompanying the Pop() on the Event Queue. The peek function will help to coalesce all events at initial sync and write the config only when queue is empty. Its an out-of-band implementation of the 'new event indicating sync is complete' idea as suggested by Maru.
Specifically, the peek function is just a non-popping non-blocking but synchronous call that tells whether the queue is empty or not.
The router code will have to sync itself because it watches both routes and endpoints but even if that is inefficiently done the current problem of reloading the router at fine hew will go away.

**Comment by smarterclayton** [comment]
I'd rather not use peek - that's usually a code smell, and we've rejected
that upstream multiple times (others have made convincing arguments that we
will not be adding Peek to the core cache stores and reflectors).

**Comment by marun** [comment]
Fixed by #8287
