### ISSUE TITLE
`oc rsh` should set TERM

### ISSUE THREAD

**Issue by rhcarvalho** [openshift/origin#7424]
Extracted from https://github.com/openshift/sti-base/pull/77

There is a known Docker issue (https://github.com/docker/docker/issues/9299) that `docker exec -t` does not set TERM while `docker run -t` does.

Users run into problems running applications that rely on term after running `oc rsh`, e.g.:

```console
[vagrant@localhost origin]$ oc get pods
NAME                      READY     STATUS    RESTARTS   AGE
docker-registry-1-x5d7z   1/1       Running   0          1d
[vagrant@localhost origin]$ oc rsh docker-registry-1-x5d7z
bash-4.2$ top
TERM environment variable not set.
```

The proposed solution is to inherit the value of TERM from the environment where `oc` is run.

Maybe: do the same for `oc exec -t`.

Also: the Web Console terminal should set TERM.

**Comment by rhcarvalho** [comment]
@bparees @mfojtik FYI 

@caruccio thanks from bringing this up!

**Comment by mfojtik** [comment]
@fabianofranz PTAL.

**Comment by rhcarvalho** [comment]
I will defer adding a new issue specifically for the Web Console terminal, since it uses an API endpoint with `exec -t` semantics, perhaps solving this on the server side will require no changes to the Web Console itself.

Example web socket URL: `wss://10.1.2.2:8443/api/v1/namespaces/testphp/pods/test-4-73q81/exec?stdout=1&stdin=1&stderr=1&tty=1&container=test&command=%2Fbin%2Fsh&command=-i`

**Comment by fabianofranz** [comment]
Pretty interesting. @jwforres look.

**Comment by smarterclayton** [comment]
Is the client TERM going to be reasonable for the server?

**Comment by bparees** [comment]
@smarterclayton the client TERM should be all that matters...everything is being rendered by the client TERM, right?  What are you envisioning?

**Comment by smarterclayton** [comment]
Just wondering whether Mac terminals are going to be straight up
accepted by remote Linux.

**Comment by caruccio** [comment]
Iterm2 is shipped with TERM=linux-color by default (at least mine was).
Em 20/02/2016 22:05, "Clayton Coleman" <notifications@github.com> escreveu:

**Comment by ncdc** [comment]
When you SSH to a server, part of the SSH protocol includes retrieving the client's TERM and sending that over the wire to the SSH server. When the SSH server starts bash for you, it sets up the process's environment to include the TERM it received from the client.

When you `docker run -it`, Docker will set up TERM for you.

When you `docker exec -it`, Docker executes a process that inherits the same environment as the process created by `docker run`. Therefore, if you `docker run -it` and then `docker exec -it`, your exec session will inherit TERM from the primary process, meaning it should be set correctly. On the other hand, if you `docker run -i` (note the lack of `-t`), TERM will be set to "dumb". If you then `docker exec -it`, because the exec'd process inherit's the primary process's environment, it has TERM=dumb also.

AFAIK there are 3 possible ways to fix this:

- add a `.bashrc` to your container with TERM set appropriately
- work with Docker upstream to add support for setting the exec process's environment
- modify `oc rsh` to exec `bash -c 'TERM=xterm bash'` (change xterm as appropriate)

**Comment by bparees** [comment]
option (3) seems expedient and no worse than the current behavior (dumb terminal).

i always like vt100 as a default term value myself, as a pure lowest common denominator.

**Comment by ncdc** [comment]
I think 3 is the best option. I'm currently working on terminal resizing support, so that + 3 will be a nice win.

**Comment by caruccio** [comment]
#3 looks good for me too.
Maybe a flag (-t $TERM ?) could be useful.
Em 21/04/2016 16:02, "Andy Goldstein" <notifications@github.com> escreveu:

**Comment by rhcarvalho** [comment]
Does it need to be `bash` for this to work? We had agreed to use `/bin/sh` whenever possible -- that's what we use in build hooks.

**Comment by ncdc** [comment]
Presumably it'd be ok with `sh` too. Would need to test
