### ISSUE TITLE
Improve circular input/output detection in oc new-build

### ISSUE THREAD

**Issue by rhcarvalho** [openshift/origin#7453]
From https://github.com/openshift/origin/pull/7321/files#r53043941

We should be able to detect a circular input/output when the output is a DockerImage (`oc new-build ... --to-docker`).

**Comment by rhcarvalho** [comment]
@bparees FYI

**Comment by jupierce** [comment]
@bparees As best I can tell, this would require the user doing something like:
```
oc new-build https://github.com/openshift/ruby-hello-world --to-docker=true --to=172.30.96.226:5000/myproject/ruby-22-centos7
```
(Where --to is pointing to the openshift docker registry/authorized project)

To guard against this behavior, it would seem necessary to implement one of the following approaches: 

1. Determine the current IP address/port of the default registry and compare whether   defaultRegistryURL+"/"+imagesream.Name == toFlag .
The check itself is not problematic, but I have not been able to find other client code trying to acquire the registry URL, so I'm concerned it is bad practice to try to find it.

2. Create the image stream before the buildconfig and wait for the is.status.dockerImageRepository to reflect the problematic destination. This would significantly change the current flow (creating one resource before the check is performed).

3. Move the check to the build controller to perform the cycle check so that all necessary information is available. 

Unless I'm missing something, the complexity of these approaches seem to outweigh the value (given the very odd user behavior the issue requires).

**Comment by bparees** [comment]
@jupierce after reading back through the discussion linked at the top of this issue, I think the scenario we actually care about (and can fix relatively easily) here is if the value of --to exactly matches what we're defining as the input image (either based on the image the user named, or the dockerfile contained within the repo, or the dockerfile the user supplied).

In most cases that won't result in an immediately circular build (Assuming the target is dockerhub for example) but you can auto-import imagestreams, so it could still be circular.

**Comment by jupierce** [comment]
@bparees Thanks. I'll start on that. It still might be worth considering moving this logic into the server to prevent cyclic buildconfigs from affecting the system if created through other interfaces (e.g. templates). An build request for a cyclic buildconfig could result in fast failing build with a message blaming the buildconfig.

**Comment by bparees** [comment]
@jupierce our current structure makes that difficult, because things are resolved lazily and we will retry waiting for them, meaning we might not actually know all the information we need to make that determination, at the time the build request is submitted.

but we could fail build once we do realize it's a loop.  That said, I don't know that i want us to be in the position of making that decision for users.
