### ISSUE TITLE
oc new-build gives confusing/wrong error message when local image stream for S2I builder not yet built.

### ISSUE THREAD

**Issue by GrahamDumpleton** [openshift/origin#7613]
If you create an S2I builder by building it in OpenShift, e.g.:

```
oc new-build https://github.com/soltysh/sti-lighttpd.git --name s2i-lighttpd
```

Between the time that the empty imageStream definition has been created and the build of that image has completed, 'oc new-build' will give confusing/wrong error messages.

For example, ``s2i-lighttpd`` not yet finished building.

```
$ oc get is s2i-lighttpd
NAME           DOCKER REPO                                 TAGS      UPDATED
s2i-lighttpd   172.30.93.207:5000/s2i-tests/s2i-lighttpd
```

When run ``oc new-build``, not realising image not yet built, get:

```
$ oc new-build s2i-lighttpd~https://github.com/GrahamDumpleton/lektor-empty-site.git --name blog-phase2 --dry-run -o json
error: only a partial match was found for "s2i-lighttpd": "s2i-tests/s2i-lighttpd"

The argument "s2i-lighttpd" only partially matched the following Docker image or OpenShift image stream:

* Image stream s2i-lighttpd in project s2i-tests
  Use --image-stream="s2i-tests/s2i-lighttpd" to specify this image or template
```

Try adding project name in reference.

```
$ oc new-build s2i-tests/s2i-lighttpd~https://github.com/GrahamDumpleton/lektor-empty-site.git --name blog-phase2 --dry-run -o json
error: only a partial match was found for "s2i-tests/s2i-lighttpd": "s2i-tests/s2i-lighttpd"

The argument "s2i-tests/s2i-lighttpd" only partially matched the following Docker image or OpenShift image stream:

* Image stream s2i-lighttpd in project s2i-tests
  Use --image-stream="s2i-tests/s2i-lighttpd" to specify this image or template
```

Try instead the ``--image-stream`` option it says to use:

```
$ oc new-build s2i-tests/s2i-lighttpd~https://github.com/GrahamDumpleton/lektor-empty-site.git --name blog-phase2 --dry-run -o json --image-stream="s2i-tests/s2i-lighttpd"
Error: unknown flag: --image-stream

.... followed by usage messages
```

So says to use ``--image-stream`` but that option doesn't exist.

This was with Origin 1.1.2. Not known if 1.1.3 is different as don't have access to that version yet.

**Comment by bparees** [comment]
The behavior seems unchanged in current master.  We need to make it clearer on these failures that the issue is that while we found the imagestream, there is no "latest" tag available in the imagestream (which is what we default to since no tag was specified).

And obviously any message where we say "a partial match was found for 'foo'" and the partial match name is 'foo' needs to be enhanced to indicate why they aren't actually matching.

the --image-stream flag is presumably a bug due to code sharing between new-app and new-build.

**Comment by GrahamDumpleton** [comment]
I think I mentioned some time previously the lack of parity between new-app and new-build with respect to --docker-image and --image-stream options. The new-build command still only has --image. If that was addressed, then message would be correct. :-)

I can't seem to find where I mentioned that. Must have been as comment in some issue as can't find distinct issue for it.

So can we just add --image-stream to new-build and mark as obsolete the --image option?

**Comment by bparees** [comment]
> So can we just add --image-stream to new-build and mark as obsolete the --image option?

sounds reasonable, that's what was done in new-app.

**Comment by csrwng** [comment]
Created a PR to add the --image-stream flag to new-build

@bparees if we find an image stream but can't find any matching tags, does it make sense that we return a different error (similar to ErrNoMatch, but indicating that a tag wasn't found). And the suggestion to get around it would be to specify --allow-missing-images. What do you think?

**Comment by bparees** [comment]
> @bparees if we find an image stream but can't find any matching tags, does it make sense that we return a different error (similar to ErrNoMatch, but indicating that a tag wasn't found)

@csrwng you mean if there are *no* tags in the imagestream?  if there are any tags in the imagestream, you should get a partial match for each of them.  If there are no tags in the imagestream, a new error sounds ok, I guess... (an ErrNoMatch but hey here's what we did find).  I almost want to call that a partial match but i guess it's not because there's nothing returned that you could specify more explicitly.

>  And the suggestion to get around it would be to specify --allow-missing-images. What do you think?

allow-missing-images is for docker images, not imagestreams.  if you specify --allow-missing-images you're going to end up with a docker image reference, not an imagestreamtag reference, so that's probably not what you want in this case.  (i guess i'm not sure how --image-stream and --allow-missing-images interact?  ideally if you specified --image-stream, then the "fake match" created by --allow-missing-images would be an ImageStreamTag match instead of a DockerImage match, but that's not the case today i don't think)

**Comment by csrwng** [comment]
> you mean if there are no tags in the imagestream?

yes, you're right, it would have to be only if there are no tags

> allow-missing-images is for docker images, not imagestreams.

my thinking was to repurpose the flag to also mean to use imagestreams that have no tags. Alternatively we could have a different flag like --allow-missing-imagestreamtags

**Comment by bparees** [comment]
> my thinking was to repurpose the flag to also mean to use imagestreams that have no tags. Alternatively we could have a different flag like --allow-missing-imagestreamtags

repurposing(add-purposing) is ok as long as you're confident you can determine when an imagestreamtag ref should be created instead of a dockerimage ref.  Basically i think the only time that is the case is when you matched an imagestream but not the tag *and* the user explicitly requested --image-stream.

the new flag might be better :)

**Comment by csrwng** [comment]
ok, new flag it is :) one less "magical" thing

**Comment by abdennour** [comment]
adding `--insecure-registry` option solves my issue.
