### ISSUE TITLE
Data gaps in web console metrics graph

### ISSUE THREAD

**Issue by spadgett** [openshift/origin#7679]
I'm seeing spikey graphs in the web console. The gaps are in the response data coming back from Hawkular.

![metrics-spikes](https://cloud.githubusercontent.com/assets/1167259/13373220/3dcf046e-dd2f-11e5-85a4-f166ff193cd3.png)

Here's a sample of the response:

```
[
  {
    "start": 1456579001292,
    "end": 1456579018879,
    "min": "NaN",
    "avg": "NaN",
    "median": "NaN",
    "max": "NaN",
    "samples": 0,
    "empty": true
  },
  {
    "start": 1456579018879,
    "end": 1456579036466,
    "min": 6.2087168E7,
    "avg": 6.2087168E7,
    "median": 6.2087168E7,
    "max": 6.2087168E7,
    "samples": 1,
    "empty": false
  },
  {
    "start": 1456579036466,
    "end": 1456579054053,
    "min": 6.2087168E7,
    "avg": 6.2087168E7,
    "median": 6.2087168E7,
    "max": 6.2087168E7,
    "samples": 1,
    "empty": false
  },
  {
    "start": 1456579054053,
    "end": 1456579071640,
    "min": "NaN",
    "avg": "NaN",
    "median": "NaN",
    "max": "NaN",
    "samples": 0,
    "empty": true
  }, ...
]
```

If I change the graph to show 1 hour instead of 30 minutes, the gaps disappear.

<img width="720" alt="openshift_web_console" src="https://cloud.githubusercontent.com/assets/1167259/13373230/842f8924-dd2f-11e5-8473-a0fd171ec557.png">

@mwringe @jwforres

**Comment by spadgett** [comment]
hawkular-metrics version 0.13.0-SNAPSHOT

(Git SHA1 - 7dee24acfcfb3beac356e2c4d83b7b1704ebf82f)

**Comment by spadgett** [comment]
Example web console request for 30 minutes of data:

```
GET /hawkular/metrics/counters/heapster%2Fa1474743-dcc9-11e5-aa71-080027242396%2Fcpu%2Fusage/data?buckets=61&start=1456579490308 HTTP/1.1
Host: hawkular.localhost.dev
Connection: keep-alive
Pragma: no-cache
Cache-Control: no-cache
Hawkular-Tenant: openshift-infra
Accept: application/json
Origin: https://localhost:9000
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36
Authorization: Bearer biK6AIUY74b9sz1ziJga3AzPbqzlRxOy9BD7F7C6Uxw
DNT: 1
Referer: https://localhost:9000/project/openshift-infra/browse/pods/heapster-yu7zv
Accept-Encoding: gzip, deflate, sdch
Accept-Language: en-US,en;q=0.8
```

**Comment by mwringe** [comment]
Ok, the gaps are due to Hawkular Metrics not having any data for the time requested (eg "empty": true from the json response). I will need to debug why exactly this is happening. 

Which version of OpenShift? I assume also this is with the latest origin-metrics containers? Anything else you can explain about your setup?

**Comment by spadgett** [comment]
Latest master, metrics setup late last week following the doc, so should be the latest images.

**Comment by spadgett** [comment]
This doesn't happen always, but I've seen it more than once now. This morning I don't see any gaps.

**Comment by spadgett** [comment]
Only error I see in the logs. This is from the hawkular-metrics log.

```
11:27:59,061 WARN  [org.hawkular.metrics.tasks.impl.TaskSchedulerImpl] (lease-pool-0) HAWKMETRICS400006: There was an error observing leases: rx.exceptions.MissingBackpressureException
70		at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.onNext(OperatorObserveOn.java:138)
71		at rx.internal.operators.OperatorDoOnEach$1.onNext(OperatorDoOnEach.java:84)
72		at rx.internal.operators.OperatorTakeUntilPredicate$ParentSubscriber.onNext(OperatorTakeUntilPredicate.java:43)
73		at rx.internal.operators.OperatorMap$1.onNext(OperatorMap.java:55)
74		at rx.internal.operators.OnSubscribeTimerPeriodically$1.call(OnSubscribeTimerPeriodically.java:51)
75		at rx.Scheduler$Worker$1.call(Scheduler.java:120)
76		at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
77		at rx.schedulers.ExecutorScheduler$ExecutorSchedulerWorker.run(ExecutorScheduler.java:98)
78		at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
79		at java.util.concurrent.FutureTask.run(FutureTask.java:266)
80		at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
81		at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
82		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
83		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
84		at java.lang.Thread.run(Thread.java:745)
```

**Comment by mwringe** [comment]
I have tried with the latest from OpenShift Origin as well as images built from the latest origin-metrics and I can't seem to reproduce the problem described. Do you know of any way to reasonably reproduce this problem?

Can you verify that this is not the problem described here: https://lists.openshift.redhat.com/openshift-archives/dev/2016-February/msg00091.html

The Hawkular Metrics team seems to think that the 'MissingBackpressureException' issue could be caused by the system being under too much load or waiting for connections to go through to Cassandra (which makes me think it could be related to the SDN issue mentioned above)

If you were monitoring a large cluster, I would recommend to increase the number of Hawkular Metrics and Cassandra instances, but from a chat on irc this doesn't appear to be the case.

If you could provide some more information about your setup that might help in order to reproduce the problem.

**Comment by spadgett** [comment]
@mwringe I can no longer reproduce. We can close or lower severity if we think it's a duplicate of the SDN issue.

I might look to see if we can render the chart differently so it's clear there are simply data gaps instead of the memory usage going to 0.

**Comment by spadgett** [comment]
I have a change to show gaps in the chart for gaps in data.

![openshift_web_console](https://cloud.githubusercontent.com/assets/1167259/13410163/411a9fe4-df04-11e5-9967-1eb4630a2a04.png)
