### ISSUE TITLE
Regular project admins or editors should not be able to create DaemonSets by default

### ISSUE THREAD

**Issue by csrwng** [openshift/origin#7716]
Right now anyone that can create a project can create a daemonset. Why would regular project admins be allowed to schedule something on every node (or a subset of nodes)? Seems more like an admin type of power.

**Comment by csrwng** [comment]
@deads2k @pweil- @dobbymoodge

**Comment by liggitt** [comment]
not sure about this... regular project admins can create pods with nodeNames set by default

**Comment by deads2k** [comment]
This is a good point, but removing it from project admins would make it hard for our users to try out daemon sets.  I see the options as saying: 
 1. well, if you want that you want a cluster-admin
 2. we could create an intermediate role, someone who can't create nodes, but who can create daemon sets and the like.
 3. leave it as is and count on quota to keep things from getting out of hand.

**Comment by deads2k** [comment]
> not sure about this... regular project admins can create pods with nodeNames set by default

That doesn't mean we should make it easy.  Also, having not looked through the code are daemon set pods still restricted by the node label selector on a project?

**Comment by liggitt** [comment]
all pods are restricted, so yes. daemonsets respect the nodeselector on their podtemplate... we should probably apply the project nodeselector to daemonsets during admission as well

**Comment by pweil-** [comment]
> we should probably apply the project nodeselector to daemonsets during admission as well

I thought this was already happening?  https://github.com/openshift/origin/pull/7133

**Comment by csrwng** [comment]
sorry meant to hit the comment button... so yeah, there's no admission control on the daemonset but there is on the pod, so the pod name would be set but also limited by the node selector applied to it

**Comment by pweil-** [comment]
oh, I see what you're saying...appending it to the DS selector.  It already constrains the pod on admission.

**Comment by liggitt** [comment]
denormalizing the project nodeSelector into the DS would make the DS not try to create bad pods, but would also mean the DS could get out of sync if the project nodeSelector changed.

**Comment by deads2k** [comment]
I don't think we should denormalize during admission.  Changing the project ndoe selector later on would bork us.

**Comment by deads2k** [comment]
We should probably patch the daemonset controller to use a namespace cache to pull the project node selector limitations so that it doesn't try to create pods that will constantly be rejected.

**Comment by csrwng** [comment]
But even if you are constrained to the nodes that your project node selector allows you to schedule on... does it make sense for a regular project admin to be able to schedule something on EVERY node they're allowed to run on? What's the use case?

**Comment by liggitt** [comment]
If the project is allowed to run pods on these nodes, and the number of pods fits in their quota, why wouldn't we allow that?

**Comment by deads2k** [comment]
> If the project is allowed to run pods on these nodes, and the number of pods fits in their quota, why wouldn't we allow that?

It feels wrong and I like to default to "no"?  I don't feel very strongly, but with proper updates to the daemonset controller to understand the per-namespace node restriction this could be acceptable.

**Comment by liggitt** [comment]
Opened PR that would allow us to inform the daemonset controller of project restrictions: https://github.com/kubernetes/kubernetes/pull/22286

**Comment by csrwng** [comment]
@derekwaynecarr

**Comment by derekwaynecarr** [comment]
The intent in kube 1.3 timeframe is to not evict a pod that is controlled by a daemon set when a kubelet is starved for compute resource (memory, cpu_load, etc.).  This implicitly confers a higher priority to pods derived from a daemon set than pods derived from other controllers like jobs and replica sets; see [1] for details.  There is discussion about disabling the ability to create a daemon set that has best effort QoS for that exact reason.  When the re-scheduler comes, it seems like a daemon set would have to have highest scheduling priority as well [2] and could result in other pods from being evicted from the nodes in question that were derived from other controllers.

Just because I have restricted the set of nodes that a project may schedule against does not mean I have conferred exclusive access to those nodes or guaranteed scheduling.  Daemon sets are largely intended in my view for cluster-admins to control configuration of the node to run core cluster services.  I think offering daemon sets to non cluster-admin roles by default encourages bad practice and confuses the intended use cases behind daemon set.

[1] https://github.com/kubernetes/kubernetes/pull/18724/files#diff-4f041a84410028611000aef9b5deaa53R171
[2] https://github.com/kubernetes/kubernetes/pull/22217/files#diff-8141aabac2eced92d5560d2d24c1a2d7R137

**Comment by liggitt** [comment]
if a daemonset-created pod (which is actually unknowable today, given the current state of annotation-level authorization) is treated differently than a raw pod or a RC-created pod, then I could see the admin/edit roles not conferring that by default.

Also, closed my upstream PR in favor of an issue to make the daemonset controller back off on pod rejection, no matter the cause.

**Comment by deads2k** [comment]
> Also, closed my upstream PR in favor of an issue to make the daemonset controller back off on pod rejection, no matter the cause.

That limits a looping problem, but won't make the daemonset status look correct.  It will always look like the daemonset should have more pods scheduled:  `desiredNumberScheduled` won't equal `currentNumberScheduled`.  Without fixing `nodeShouldRunDaemonPod`, it will be impossible to distinguish good status from bad status.

**Comment by liggitt** [comment]
> it will be impossible to distinguish good status from bad status

if you expect daemonsets to be namespace-limit-aware

**Comment by deads2k** [comment]
> if you expect daemonsets to be namespace-limit-aware

I'd really like to be able to inspect a resource's status and know if its satisfied its spec or not.  I can do that for every other resource type, but this limitation means that I won't be able to do that for daemonsets.

**Comment by liggitt** [comment]
it still indicates if it satisfied its spec. it doesn't indicate if it satisfied it's spec + other external factors.

**Comment by liggitt** [comment]
@smarterclayton need to decide what we want for this for 1.2

**Comment by smarterclayton** [comment]
There's nothing special about daemon set compared to an RC with a pod spreading policy (in either case I can run a pod on all nodes I have access to).  So "I can run on all nodes" is not a strong enough argument by itself.

The better argument is about daemon sets and priority.  If a daemon set allows an implicit higher priority on a given node for a pod than an RC, that means users would be incentivized to use them to get preferential placement.  I suspect admins *will* want to delegate this authority to end users on a per namespace basis - ie, I don't want to grant you access to create daemon sets in production, etc, so a blanket role isn't going to be enough.

I think this highlights a potential weakness in our authn / restriction tooling we have available.  I suspect the decision on whether an end user should be able to create daemon sets is not about their project or their role, but about the nodes they have a "role" on.  We lack any way to express that concept, but it seems more likely that an admin would want to blanket grant daemon set priv on a set of nodes rather than try to hammer something together with namespaces and namespace node selectors and policy.

**Comment by liggitt** [comment]
so.... keep it in admin/edit roles or remove it for 1.2?
