### ISSUE TITLE
Latest builders should include warning message

### ISSUE THREAD

**Issue by jhadvig** [openshift/origin#7731]
When picking a builder image in the "create" page, all the ones that are tagged as "latest" should be include a warning with a message that this image should not be used since it could cause failing builds cause its changing pretty often and that the versioned(released) images should be used instead. Or some similar explanation.
@jwforres @spadgett I think we should have the warning since not all the users wanna have 'living on the edge' experiance.
Thoughts ?

**Comment by spadgett** [comment]
@bparees

**Comment by bparees** [comment]
it's actually not changing all the frequently.  Take mongo as an example.  Today the mongo latest tag changes exactly as frequently as the mongo 2.6 tag does.

The risk you are opening yourself up to is that at some point in the future your administrator might change the "latest" tag to follow mongo "2.8" instead of "2.6" and now you'll get bumped up a major release version.

So if you want control over what major version you are running on, you don't use the latest tag.  If there's going to be a warning, that's what it needs to convey.

As for whether or not there should be a warning... i'm a little indifferent.  I think this is primarily an education problem, but i'm not sure how users get that education.  As long as the warning is unobtrusive enough (it should not require me to click an acknowledgement, for example), i guess it'd be ok.

**Comment by jwforres** [comment]
What if we check if its a builder AND it doesn't specify a version
annotation and then warn.  In which case maybe we should put something in
image authors guide that explains this distinction?

And yeah I agree with @bparees, it shouldn't prompt you about it, maybe
just show a warning in the top of the create form.

**Comment by jhadvig** [comment]
> The risk you are opening yourself up to is that at some point in the future your administrator might change the "latest" tag to follow mongo "2.8" instead of "2.6" and now you'll get bumped up a major release version.

And thats my point. If that happens there will definitely some decent number of users (talking about online offering) that will get broken and start to raise bugs/issues/questions. By this warning (or the one @jwforres is proposing) we could lower that number.

**Comment by jwforres** [comment]
Just had a chat with @luciddreamz and he agrees lets do a small warning

**Comment by jhadvig** [comment]
@jwforres could you please assign me to this. Thanks :)
