### ISSUE TITLE
statuscake uptime monitor on console causes openshift process to leak memory

### ISSUE THREAD

**Issue by danni** [openshift/origin#7784]
Uptime monitoring was added to our openshift cluster at `/console` after a certain amount of time we start having problems and the openshift process is now consuming 80-90% of memory. No debugging yet.

**Comment by mfojtik** [comment]
@danni what version of openshift are you using? can you paste the output of `openshift version` ?

**Comment by jwforres** [comment]
1. What sort of request is being used to check /console?   HTTP?  GET / HEAD? 
2. How often is the request being made
3. Does the monitoring you have enabled actually behave like a real browser and load all the JS/CSS etc and parse / render the content? Or is it ONLY checking /console is reachable?   This matters because hitting /console will result in a redirect to /login if the JS is actually being run.

**Comment by jwforres** [comment]
Also do you have a rough estimate of how long the uptime monitoring was running before you noticed the memory consumption?

**Comment by danni** [comment]
origin v1.1.3
kubernetes v1.2.0-origin
etcd 2.2.2+git

**Comment by danni** [comment]
Check was 1 minute, which probably took around 12h to eat all the memory on the node. Now it's 5 minutes and about 5 times as long.

**Comment by danni** [comment]
I don't know what the request structure is exactly, can I get this information from Openshift somewhere? I'm guessing it doesn't execute JS.

**Comment by jeremyeder** [comment]
Hi @danni what else is going on in your cluster during "certain period of time"...has this really been isolated to hitting /console ?

Can you enable pprof debugging for the master daemon, and then reproduce this issue?

Here are instructions:
https://github.com/openshift/origin/blob/master/HACKING.md#performance-debugging

**Comment by danni** [comment]
I can't reproduce this any more since upgrading to Openshift v1.1.5.
