### ISSUE TITLE
autoscale not working with proxy configuration

### ISSUE THREAD

**Issue by born2fail** [openshift/origin#7789]
I'm using openshift v1.1.3

Master and nodes doesn't have direct internet access so I've configured sysconfig files for docker, openshift-master and openshift-nodes to use a proxy and not use it with local services.

I'm trying to configure autoscale but the current CPU is always in waiting state
oc get hpa
NAME      REFERENCE                     TARGET    CURRENT     MINPODS   MAXPODS   AGE
test      DeploymentConfig/test/scale   70%       <waiting>   2         15        21m

Looking at proxy logs I've found this:
1456761184.220    112 10.54.219.10 TCP_DENIED/403 3444 CONNECT 10.1.3.2:8082 - HIER_NONE/- text/html

Seems like hpa is trying to access to heapster pod IP (10.1.3.2) via proxy.
Since there is no way to add a range (like 10.1.0.0/16) in sysconfig files for docker and openshift I don't know how to workaround this behaviour. 

Disabling proxy configuration in sysconfig files I get CPU usage with oc get hpa without problems.

**Comment by mfojtik** [comment]
@kargakis FYI

**Comment by kargakis** [comment]
cc: @DirectXMan12

**Comment by DirectXMan12** [comment]
So, the way the HPA works is that it accesses heapster through the API server's HTTP proxy resource (i.e., it makes an HTTP request to https://$MASTER_ADDRESS/api/v1/proxy/namespaces/openshift-infra/services/https:heapster:/$SOME_SUB_URL_HERE).  The master then makes this request against the heapster service, which goes through the OpenShift/Kubernetes service proxy (which is done with iptables), to the heapster pod.

So it seems like the apiserver service proxy --> heapster service IP might be the issue here.  Is the IP showing up in the proxy logs the *pod* IP or *service* IP?  If it's the service IP, you could just hypothetically whitelist the service IP and make sure that it's set explicitly if you ever recreate the service object.

**Comment by liggitt** [comment]
This is a broader issue with master -> {pod,service} proxying. See https://github.com/openshift/origin/issues/7694

**Comment by kargakis** [comment]
@deads2k is https://github.com/openshift/origin/pull/8016 fixing this too?

**Comment by liggitt** [comment]
Yes, that would allow putting the service and pod CIDRs in NO_PROXY
