### ISSUE TITLE
oc status should inform me that my route won't work...

### ISSUE THREAD

**Issue by kargakis** [openshift/origin#7832]
...because there is no router running... Similar to how we inform about a missing integrated registry. Not sure though how can we convey the information about a running router to the route. Probably a status field?

cc: @ramr @pweil- @deads2k

**Comment by deads2k** [comment]
It doesn't have to be right 100% of the time.  If a route has no status updates for X minutes, it's probably doomed, right?

**Comment by jwforres** [comment]
We debated this for the console too... whether we should add a warning about the router possibly being down for a route that has been pending longer than X amount of time.  Is there any other reason why the route would have no status on it?

**Comment by ramr** [comment]
@kargakis @jwforres  a route would have no status on it if a router is not running or because the selectors passed to any configured router (infra router configured via `--fields`, `--labels`, `--project-labels`, `--namespace-labels`)  don't include that route.
We did chat a while back about adding some router status information that allows the user interface (UI + command line + any integrations) to know about configured/running routers in the cluster.

**Comment by kargakis** [comment]
Darn, didn't realize we now include info about the route being admitted by the router in its status. I guess the first thing to warn about is that: a route that hasn't been admitted yet.

**Comment by kargakis** [comment]
Hm, we already do that: https://github.com/openshift/origin/blob/d513e9739d778ff2ea576619c0ec8d1ad02c5361/pkg/route/graph/analysis/analysis.go#L175

So, looking at the status and not finding any condition at all would most probably mean that a router is not running.
