### ISSUE TITLE
Route warnings not visible when route hostname truncated on overview

### ISSUE THREAD

**Issue by spadgett** [openshift/origin#7844]
The warning icon is truncated along with the route.

Route not truncated:

![openshift_web_console](https://cloud.githubusercontent.com/assets/1167259/13581836/ea1eaf0a-e476-11e5-8c47-91c956825471.png)

Same route truncated:

![openshift_web_console](https://cloud.githubusercontent.com/assets/1167259/13581866/fd343024-e476-11e5-92ab-ac8e9c12ecf6.png)

/cc @jwforres

**Comment by rhamilto** [comment]
@spadgett, it appears that [the display of the warning is different now](https://github.com/openshift/origin/blob/master/assets/app/views/project.html#L122).

<img width="534" alt="screen shot 2016-04-26 at 5 30 25 pm" src="https://cloud.githubusercontent.com/assets/895728/14834853/ad9e0bcc-0bd4-11e6-8fa5-7f978df64dcc.PNG">

Am I missing something?

**Comment by spadgett** [comment]
I think that only happens when the you have more than one route. We're not showing you the route that has the warning on the overview.

**Comment by rhamilto** [comment]
The only reliable fix I've come up with so far is to put the warning icon before the route hostname instead of after.  

![screen shot 2016-04-27 at 10 42 34 am](https://cloud.githubusercontent.com/assets/895728/14856130/dade1a9c-0c64-11e6-8529-63b7174f592b.PNG)

Any objections, @spadgett, @jwforres, @benjaminapetersen, @sg00dwin?

**Comment by benjaminapetersen** [comment]
Works for me!

**Comment by jwforres** [comment]
this was fixed
