### ISSUE TITLE
Builder version should be sorted as numbers when possible in UI

### ISSUE THREAD

**Issue by spadgett** [openshift/origin#7847]
Builder wildfly:10.0 should appear after wildfly:9.0. Versions aren't always numbers, but we should compare them as numbers when sorting if possible.

<img width="380" alt="openshift_web_console" src="https://cloud.githubusercontent.com/assets/1167259/13589056/f8bb137e-e4a2-11e5-9ca9-318f7f320c25.png">

/cc @bparees @jwforres

**Comment by jawnsy** [comment]
I think this can be a difficult problem to solve in general, though perhaps it would be reasonable to assume that all versions match the [Semantic Versioning](http://semver.org/) conventions.

For example, in some languages (I think Perl works like this), 1.9 > 1.10, because the versions are treated simply as floating-point numbers, and 1.9 = 1.90, which is greater than 1.10 = 1.1.

If we're okay assuming semver, then there should be libraries available to help with this. Would the sorting need to happen on the client side (browser) or in the server?

**Comment by jwforres** [comment]
@smarterclayton did something server side to sort by semver on the image
stream import api.  Don't think that has been added to the regular IS APIs
yet?

**Comment by smarterclayton** [comment]
We need to sort by the Version using the library method on the way out
(in decorate or in conversion).

**Comment by spadgett** [comment]
Need to remove the client sort here if the server sorts for us.

https://github.com/openshift/origin/blob/master/assets/app/views/catalog/_catalog-category.html#L18
