### ISSUE TITLE
Pushing to the internal registry with a corporate proxy in play

### ISSUE THREAD

**Issue by donovanmuller** [openshift/origin#7879]
I have the unfortunate requirement to use a corporate proxy in our environment.
I have configured (Chef) both Docker and OpenShift to use this proxy and in general it works well.

However, there is one scenario that I cannot seem to automate.
I'm using the `Docker` build strategy to build images. So once the container is built successfully it pushes the image to the internal registry.
The URI of the internal registry will be something like `172.30.171.142:5000/blah/deeblah:latest`.
The problem is that the Docker daemon will try to use the configured proxy to push to `172.30.171.142`, which will obvisouly not work.

The workaround is to add the registry Service IP to the `no_proxy` configuration of the Docker daemon:

```
[x@master01 ~]$ cat /etc/systemd/system/docker.service.d/http-proxy.conf
[Service]
Environment="HTTP_PROXY=http://127.0.0.1:3128/"
Environment="HTTPS_PROXY=http://127.0.0.1:3128/"
Environment="NO_PROXY=172.30.171.142,..."
```

Pushing then works fine... until the registry gets rescheduled/recreated/... and gets another IP.
Which means you then have to go change your `no_proxy` entry to match.

This is difficult to automate.

Is there any recommended way to address this?
I.e. can we create a route and somehow use that to reference the internal registry?

Please advise.

**Comment by pweil-** [comment]
A route can be created for the registry using the following steps: https://docs.openshift.org/latest/install_config/install/docker_registry.html#exposing-the-registry

However, since a change in the registry service IP address requires a restart of the master it is recommended that you reuse the IP address if recreating the internal registry: https://docs.openshift.org/latest/install_config/install/docker_registry.html#maintaining-the-registry-ip-address

**Comment by liggitt** [comment]
a route cannot be used with the internal registry until the generated credentials take additional hostnames into account
