### ISSUE TITLE
GitHub Organizations Delayed Update

### ISSUE THREAD

**Issue by paralin** [openshift/origin#7970]
## Version
v1.1.3

## Description

Signing in with the GitHub auth provider with the membership to an organization private, as expected, results in an authentication error as the OpenShift system can't see the organization membership. However, I changed my membership visibility and tried again 5+ minutes later, and the organization list doesn't update.

This might be a GitHub API problem, but I suspect it's some kind of caching within OpenShift.

## How reproducible

1. Try signing in with an organization requirement for an organization that is hidden.
2. Reveal your affiliation with the organization on GitHub
3. Attempt to sign in again.

## Current result

Authentication error.

## Expected result

Successful signin.

**Comment by liggitt** [comment]
There is no organization caching on the openshift side. Has the organization allowed third party access? 

"If the GitHub OAuth application configured in clientID is not owned by the organization, an organization owner must grant third-party access in order to use this option. This can be done during the first GitHub login by the organization admin, or from the GitHub organization settings."

**Comment by paralin** [comment]
Ah this is probably the case. I suspected it wasn't an OpenShift issue

**Comment by liggitt** [comment]
With sufficient verbosity (--loglevel=4 or higher, I think), the server will log information about the group membership retrieved during login, which might help debugging

**Comment by paralin** [comment]
It does log the organizations. I think it is the case that the public view permissions aren't set on GitHub's end.

Should be all good here. I would love it if there was a better error message than "Authentication error" but this is good for now.
