### ISSUE TITLE
External kubernetes: Implement namespace upgrade command

### ISSUE THREAD

**Issue by paralin** [openshift/origin#8120]
A command should exist to upgrade an existing Kubernetes namespace to be considered an OpenShift cluster. I think there should similarly exist a command to downgrade a namespace to be a bare namespace without the OpenShift decorations.

See #8101

**Comment by deads2k** [comment]
Right now its:
 1. description, displayname, requester annotations on the namespace
 1. role bindings from`GetBootstrapServiceAccountProjectRoleBindings`
 1. service accounts from `master-config.yaml|serviceaccountconfig.managednames` (@derekwaynecarr @liggitt do we start the SA controller when running on top of kube?  Seems dirty to start stomping over every namespace)
 1. finalizer normally added during project `BeforeCreate`

**Comment by liggitt** [comment]
> service accounts from master-config.yaml|serviceaccountconfig.managednames (@derekwaynecarr @liggitt do we start the SA controller when running on top of kube?

We do if there are managed names listed in the service account config

**Comment by liggitt** [comment]
I thought the origin finalizer got added if missing the first time an origin resource was created

**Comment by paralin** [comment]
This is somewhat related to the kubernetes deployment in that my cleanup code needs to deal with adjusting all the finalizers when downgrading a namespace.

I think downgrading a namespace would also require removing any openshift resources too, right?

**Comment by liggitt** [comment]
If we envision an end user running the upgrade command, it doesn't seem like they should be using the bootstrap role bindings directly. I don't want another path where the admin-customized template's rolebindings don't take effect

**Comment by deads2k** [comment]
> We do if there are managed names listed in the service account config

So we just start stomping every namespace we see with new service accounts?  That's crazy, we should be more judicious, they didn't ask us to take ownership of the cluster.

**Comment by liggitt** [comment]
Then empty managed names. There's a lever

**Comment by deads2k** [comment]
> Then empty managed names. There's a lever

Empty managed names means no builds or deployments in projects.  That lever is, "stomp everything or don't let me use any openshift concepts".  Its broken.

**Comment by liggitt** [comment]
Managed == auto create
You can still create builder/deployer manually if you want

**Comment by paralin** [comment]
I agree that deploying OpenShift right now basically causes it to grab control of a lot of stuff in the cluster such that uninstalling it (by deleting it or turning off the master) breaks a lot of stuff that really shouldn't break. I don't know enough about how the setup works yet to say how that could be improved, just my 2 cents though

**Comment by deads2k** [comment]
> If we envision an end user running the upgrade command, it doesn't seem like they should be using the bootstrap role bindings directly. I don't want another path where the admin-customized template's rolebindings don't take effect

I wasn't thinking of "upgrade to openshift" as a template that gets applied.  Setting a description and display name seems reasonable, but it can't be expressed in a template.  I think in the "run on top of kube" we should have a marker on namespaces that are ours.

**Comment by smarterclayton** [comment]
@derekwaynecarr hadn't you been considering this as part of finalizer / setup?

**Comment by derekwaynecarr** [comment]
I think we need to be careful about how this command is structured.

Before we get too excited on this command, I want to set the stake in the ground that we do the following:

* I think the `finalizerToken` that is used by a particular openshift cluster on top of kubernetest MUST be driven my a new field in `master-config.yaml` that uniquely identifies that openshift cluster.  So while we always use `openshift.io/origin` today, we really should have something more like `openshift.io/origin.<clusterid>` when running on top of kube.
* As a result of 1, I want to be careful about how we choose to write an `upgrade` command so that it does not blindly assume it should just use `openshift.io/origin` as the finalizer token.

**Comment by deads2k** [comment]
> I think the finalizerToken that is used by a particular openshift cluster on top of kubernetest MUST be driven my a new field in master-config.yaml that uniquely identifies that openshift cluster. So while we always use openshift.io/origin today, we really should have something more like openshift.io/origin.<clusterid> when running on top of kube.

Can you elaborate on why we'd do this?  Are we trying to support the notion of multiple openshifts managing the same kubernetes cluster?

**Comment by deads2k** [comment]
> In summary, it should be possible to deploy more than one OpenShift cluster on a Kube cluster.

Heh, got to the end.  Why would I want to have more than one openshift trying to manage the same cluster?  You've envisioning a world where openshift isn't a cluster-wide concept, but instead users run their own openshift against their own projects?

**Comment by derekwaynecarr** [comment]
@deads2k and I had a conversation to discuss this and I think we are both too tired to know the right answer.

To summarize the discussion:

* If you deploy openshift master on kubernetes, you share a common set of namespaces.  openshift master uses the "openshift.io/origin" finalizer token to allow it to delete its etcd content as desired.
* If you deploy openshift master A on openshift master B, where you treat the lower B as a kubernetes cluster only, you have overlap on finalizer tokens since B will stick the same finalizer token on the namespace as A.  This could prevent either openshift from cleaning up their etcd appropriately.

Running OpenShift on OpenShift in this manner with a shared non-segregated list of namespaces may not actually make sense in the same way running OpenShift on Kubernetes could make sense.  

Running multiple OpenShift masters on a Kubernetes would require finalizer token separation as well, but I am not sure what that means yet either.

**Comment by deads2k** [comment]
The big wrinkle for a second openshift on openshift, was which set of resources is authoritative.  Let's say you install openshift-2 in `ns-origin` and have it manage `ns-foo`.  openshift-2 will have its own etcd where its storing buildconfigs in `ns-foo` AND there will the potential for buildconfigs in `ns-foo` on openshift-1.  Since openshift-2 will share the namespace resource with openshift-1, if they have the same finalizer string the first one wins and the second one orphans resources.

I don't think we need resolve the problem before the initial cut of the "run on kube" command goes in, but I do recognize that running the same command on openshift will lead to insanity.

**Comment by derekwaynecarr** [comment]
I think I have come around that it only makes sense for a single openshift master to share an underlying kubernetes, and it does not make sense to let people have multiple.  I also think it does not make sense to deploy multiple.  Having openshift host openshift would also require the hosted openshift to run a full kubernetes, bring its own nodes, etc.

To summarize, I don't think we need to worry about the finalizer problem.

**Comment by paralin** [comment]
It indeed doesn't make sense to run multiple masters, at least with how masters work currently. 

I would like to be able to run multiple of the web ui, though. Since I noticed the ui getting laggy when scaling up to very high pod counts in some circumstances

**Comment by liggitt** [comment]
> I would like to be able to run multiple of the web ui, though

that's client-side lag... running more copies server-side wouldn't help
