### ISSUE TITLE
External kubernetes: Assume SecurityContextDeny enabled on default

### ISSUE THREAD

**Issue by paralin** [openshift/origin#8121]
I mounted a PersistentVolumeClaim to /registry

The logs of the registry give:

```
time="2016-03-18T12:12:50.184636555Z" level=error msg="response completed with error" err.code=UNKNOWN err.detail="filesystem: mkdir /registry/docker: permission denied" err.message="unknown error" go.version=go1.4.2 http.request.host="10.0.236.164:5000" http.request.id=0ee200ec-2e75-4926-95cc-5c753d8de8b3 http.request.method=POST http.request.remoteaddr="172.20.0.11:49270" http.request.uri="/v2/test/docker-node-hello/blobs/uploads/" http.request.useragent="docker/1.9.1 go/go1.4.2 git-commit/a34a1d5 kernel/4.2.0-34-generic os/linux arch/amd64" http.response.contenttype="application/json; charset=utf-8" http.response.duration=176.227048ms http.response.status=500 http.response.written=156 instance.id=c68a2d6e-a0c9-49c5-8965-3417cf473c16 vars.name="test/docker-node-hello" 
```

Inside the container, I checked /registry and it is `root:root`.

As a temporary solution I was going to chown it to whatever user the registry was running under, but `whoami` yields `whoami: cannot find name for user ID 1001`

So the user doesn't exist in `/etc/passwd` or something. Looks super corrupt.

**Comment by deads2k** [comment]
Have you tried setting up the FSGroup settings: https://docs.openshift.org/latest/install_config/persistent_storage/pod_security_context.html#fsgroup ?

**Comment by paralin** [comment]
@deads2k Nope, will try that now. Seems a bit iffy though to need to set this for a registry. I guess it might be something that needs to be mentioned in the documentation. Setting something to '1001' seems a bit arbitrary.

**Comment by paralin** [comment]
@deads2k SecurityGroup FSGroup is forbidden: https://github.com/kubernetes/kubernetes/blob/master/plugin/pkg/admission/securitycontext/scdeny/admission.go#L74

**Comment by paralin** [comment]
@deads2k What do I need to do to enable this? I'm guessing it's because I have SCDeny set right now?

**Comment by paralin** [comment]
RunAsUser is denied too, so I think I need to just build a custom image for now without the "user" line

**Comment by deads2k** [comment]
Why did you choose SCDeny?  Is it because kube doesn't have any way to actually control access?  If so, you're pretty likely to hit problems running many different kinds of images.

Shutting it off is safe, but very restrictive.  That's why openshift built features around controlling access.  To my knowledge, kube doesn't have a model that allows safe multi-tenancy on nodes.

@pweil- They have no SCC or PSP controls yet, so you end up either allowing root access on your node or not being able to perform things like builds or running many kinds of images from dockerhub, right?

**Comment by pweil-** [comment]
Until recently, SCDeny was a default plugin for many of the canned run scripts in Kubernetes.  It was recently removed.  The intent was to disallow a user to set specific fields on the `SecurityContext`.  

Since Kubernetes does not have the same admission control around `SecurityContext` what @deads2k  is saying is correct - disabling the plugin would allow users to set whatever they'd like in those fields, including the ability to override the user that runs a container.  However, if you're already running against an external Kube instance then you're already allowing folks to run root containers just by not setting a `USER` directive in the dockerfile.

**Comment by paralin** [comment]
@deads2k @pweil- It's the default to have the SCDeny plugin in a kubernetes deploy at the moment I think

**Comment by pweil-** [comment]
> @deads2k @pweil- It's the default to have the SCDeny plugin in a kubernetes deploy at the moment I think

Yes.  You should be able to override that on the kube api server with the `--admission-control` flag which takes a comma delimited list of admission controllers to run

**Comment by paralin** [comment]
@pweil- With the AWS deployment I'm using editing the master flags are a bit difficult. So for now I'm just going to redeploy the cluster with the plugin disabled in the cluster deploy script.

**Comment by paralin** [comment]
Nearly every cloud provider has this plugin enabled on default and it's a bit hard to change that (no env variable to set, you need to edit the config-default.sh instead of overriding env defaults). 

So I think we ought to assume it's going to be enabled everywhere, including the registry.

**Comment by deads2k** [comment]
@smarterclayton how do you want to handle variants on what's almost a template?

**Comment by smarterclayton** [comment]
On Kube, deploying a registry that needs access to a root:root mount probably means that the registry service account should have access to the anyuid SCC.  So `oadm add-scc-to-user anyuid -z registry`.

**Comment by liggitt** [comment]
@smarterclayton this is external kube, so no SCC

**Comment by smarterclayton** [comment]
Was forgetting the higher levels don't invoke admission on the deployment config.

**Comment by pweil-** [comment]
this is tracked upstream in https://github.com/kubernetes/kubernetes/issues/16456 and has been [removed from at least some of the envs](https://github.com/kubernetes/kubernetes/pull/21004/files) already.  Since this is only for the external kubernetes use case I'm going to close this in favor of the upstream issue.
