### ISSUE TITLE
Router reload failing to find socket because LSOF can't read the network

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#8143]
Running the router under its default SCC (host network), LSOF is unable to lookup the TCP port:

```
lsof: no pwd entry for UID 1000000000
lsof: no pwd entry for UID 1000000000
lsof: no pwd entry for UID 1000000000
lsof: no pwd entry for UID 1000000000
lsof: no pwd entry for UID 1000000000
lsof: no pwd entry for UID 1000000000
 - Exceeded 30 retries waiting for HAProxy to start listening on port 1936
```

Seems like this is because 

```
lsof: no pwd entry for UID 1000000000
openshift    1  12 10000000  cwd   unknown                           /proc/1/task/12/cwd (readlink: Permission denied)
```

(this is even as root in the container).  `/proc/net/tcp` lists

```
# cat /proc/net/tcp | grep 100000000
   0: 0100007F:28CB 00000000:0000 0A 00000000:00000000 00:00000000 00000000 1000000000        0 496524 1 ffff8800769ab000 100 0 1 10 0               
   1: 0100007F:28CC 00000000:0000 0A 00000000:00000000 00:00000000 00000000 1000000000        0 496523 1 ffff880155692000 100 0 1 10 0               
   2: 00000000:0050 00000000:0000 0A 00000000:00000000 00:00000000 00000000 1000000000        0 496521 1 ffff88015ed8b000 100 0 1 10 0
```

This is f23 docker 1.9.1

**Comment by ramr** [comment]
Looked at this a bit and the uid stuff is a bit of noise - we can ignore that since we don't really care about it right now. Earlier this afternoon, @mrunalp and I looked thru' the selinux labels on the /proc/<pid>/fd files - which are the same for both the haproxy and the reload-script.  And if we do a 
   `oc exec <router-pod>   -- lsof -n -P -p <pid>` 
which runs under the same context, we can see the files under /proc/<pid>/fd/ for the reload-script but weirdly not for the haproxy process. Still debugging it ...

**Comment by ramr** [comment]
@smarterclayton  - so @mrunalp  and I looked at this morning - we tried setting changing the capabilities for lsof/netstat and the reload script so that we can read proc fs. Basically would need dac_override capability and sys_admin - it is sorta comes down to running `privileged` (as that needs to be in bounding set for the process started in the container). 
Also did notice that since we weren't checking return codes from haproxy earlier, so adding that (already in) + a healthz check for determining that haproxy is up might also work. Might be cleaner that way and removes the need for lsof/netstat. Does that alternative work for you?

**Comment by smarterclayton** [comment]
What do we lose?

**Comment by ramr** [comment]
We don't lose anything.

**Comment by smarterclayton** [comment]
Let's do it.

On Mar 21, 2016, at 7:49 PM, Ram Ranganathan <notifications@github.com>
wrote:

We don't lose anything.

—
You are receiving this because you were mentioned.
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/issues/8143#issuecomment-199540683>

**Comment by ramr** [comment]
@smarterclayton  PR got merged - don't have permissions to close this. The "fixes #<id>" comment  didn't take from the PR - like a problem with my use of it.

**Comment by liggitt** [comment]
"Fixes …" has to be in the PR description, not just in a comment
