### ISSUE TITLE
Replace Bootstrap affix with position: sticky polyfill

### ISSUE THREAD

**Issue by spadgett** [openshift/origin#8175]
http://v4-alpha.getbootstrap.com/migration/#components

See discussion starting here https://github.com/openshift/origin/issues/7963#issuecomment-198499392

/cc @jwforres @benjaminapetersen @sg00dwin @rhamilto

**Comment by benjaminapetersen** [comment]
Cool, ~ once we upgrade patternfly/boostrap up to BS4 or think we should do this earlier & eliminate affix?

**Comment by spadgett** [comment]
I think we can probably use https://github.com/filamentgroup/fixed-sticky without needing to update Bootstrap.

**Comment by jwforres** [comment]
@spadgett does this help us fix the related issue for making the Follow log link affixed?

**Comment by jwforres** [comment]
yeah im going to close this in favor of investigating it while fixing the log buttons

**Comment by spadgett** [comment]
> does this help us fix the related issue for making the Follow log link affixed?

Yeah, it's the proposed fix for that.

**Comment by jorgemoralespou** [comment]
@spadgett Is there a PR related to closing this issue?

**Comment by jwforres** [comment]
No not yet, we are trying to consolidate duplicate/related issues in favor
of issues in the new repo.  The issue I linked above is the one we will be
tracking.

On Nov 18, 2016 3:45 AM, "Jorge Morales Pou" <notifications@github.com>
wrote:

@spadgett <https://github.com/spadgett> Is there a PR related to closing
this issue?

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/origin/issues/8175#issuecomment-261478423>,
or mute the thread
