### ISSUE TITLE
Allow labels & annotations to be passed to Build via instantiate

### ISSUE THREAD

**Issue by jimmidyson** [openshift/origin#8352]
It would be very useful to be able to add labels & annotations to builds created via instantiate. Currently if a user wishes to add labels/annotations to a build, the user first has to call instantiate & then add labels/annotations in an update to the build object. This would be very useful for the Jenkins Pipeline strategy (#7949) so that builds can be created with necessary annotations/labels in a single operation & reduce the need for the build sync controller keeping track of builds that it has created (this detail will be contained in the annotations).

**Comment by bparees** [comment]
So there are two options here:
1) we could just copy the annotations/labels from the buildrequest object into the build we create.
2) we can add new labels/annotations fields to the build request struct and use those.

(1) feels a little hacky, but since there is no reason for you to have annotations/labels on a buildrequest today (it's not a resource), i feel like maybe it would make sense.

@openshift/api-review do you have an opinion one way or the other?  this is the existing buildrequest struct:
https://github.com/openshift/origin/blob/master/pkg/build/api/v1/types.go#L637-L661

**Comment by liggitt** [comment]
are there annotations/labels on builds we'd need to protect? (not everyone who can instantiate a build has the ability to create/update a build directly)

**Comment by bparees** [comment]
we have a few cases where we'd probably want to ensure our value took precedence:
the build pod name annotation and the build name label come to mind.

but that's orthogonal to how the labels/annotations are provided on the BuildRequest object.
