### ISSUE TITLE
Make the list of builds sortable/default sort to most-recent-at-the-top

### ISSUE THREAD

**Issue by jeremyeder** [openshift/origin#8503]
Hi, right now the list of builds in the web interface doesn't seem to be sorted "most recent at the top".
Also, the headers are not clickable to allow the user to sort these columns.  And finally, it does not list the "completed" time.

Is it possible to add these?

**Comment by jwforres** [comment]
@jeremyeder i assume you are talking about the list of different build configurations?  If you go to a particular build configuration those builds should be sorted most recent first.

Sortable columns is something we want to do, but we want to do it across all of these tables at the same time.

Also curious why you specifically want to see the completed time, i think we just removed it from the CLI because we show start time and duration. @bparees @php-coder

**Comment by livelace** [comment]
The large list (Project -> Browse -> Builds) - it's not comfortable. If we can sort by columns, it will be great.

**Comment by jwforres** [comment]
Moving this RFE to trello https://trello.com/c/f6tBGkpM
