### ISSUE TITLE
reconcile-cluster-roles restores build capabilities to project roles

### ISSUE THREAD

**Issue by liggitt** [openshift/origin#8526]
The default policy includes docker, custom, and source build permissions for the admin and edit roles.

We [document](https://docs.openshift.org/latest/admin_guide/securing_builds.html#disabling-a-build-strategy-globally) removing those permissions, but running `oadm policy reconcile-cluster-roles --confirm` re-adds those permissions.

cc @deads2k

**Comment by liggitt** [comment]
talking with @deads2k, the options we see are:

1. Track all released versions, remember the default policy for each version, record the release version at reconcile time, and make reconcile optionally only add permissions added to the default policy since that version.
2. Special-case reconcile to not add permissions we expect people will want to remove (or we document removing)
3. Record removed permissions in an annotation when updating clusterroles, and make reconcile optionally avoid re-adding user-removed permissions
4. Split permissions we expect people to want to remove (or we document removing) into their own granular roles.

**Comment by deads2k** [comment]
> Split permissions we expect people to want to remove (or we document removing) into their own granular roles.

This would change the doc to do things like granting a cluster-wide permission to "create" "builds/docker".  It's safe because it doesn't actually commute the power to create builds, just that if you *can* create builds, those builds can be docker builds.



> Record removed permissions in an annotation when updating clusterroles, and make reconcile optionally avoid re-adding user-removed permissions

This could resolve the general problem of "I've changed a role and I want reconcile to the 'right' thing".  Its possible, but its a lot more work and doesn't help anyone currently facing the problem.
