### ISSUE TITLE
Properly handle multiple webhook triggers for a BuildConfig

### ISSUE THREAD

**Issue by jhadvig** [openshift/origin#8551]
Currently the buildConfig trigger array can hold multiple triggers per one type - eg. multiple github/generic triggers. This could lead to a confusion since there is no point to have multiple triggers of one type and so it should be limited one per type.
Based on conversation with @bparees

**Comment by liggitt** [comment]
> there is no point to have multiple triggers of one type

not true... I like being able to trigger builds from different repos with different secrets so I can revoke just one

**Comment by bparees** [comment]
@liggitt well you can't today since the existing implementation is broken :)

**Comment by liggitt** [comment]
then we should fix that

**Comment by bparees** [comment]
the issue here is this code:
https://github.com/openshift/origin/blob/master/pkg/build/webhook/generic/generic.go#L27
(and the equivalent in the github webhook) which just finds the first trigger of type Generic and tries to match the secret against it.

I guess we should be iterating all the triggers of type Generic and checking if the supplied secret matches any of them, though something about that bothers me since it makes it easier to brute force guess a secret (each guess you make is automatically tried against all possible matches).

**Comment by PI-Victor** [comment]
i'm on it, will submit a PR shortly.
