### ISSUE TITLE
Builds should not inherit log level 3 or below from master

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#8738]
Currently builds are set to exactly the log level of the master - this works great for debugging, but most users do not need log level 2 output from the build.

We should only set BUILD_LOGLEVEL if V(4) or above on the master.  And even then, this needs to be an admin config flag, not directly tied to what the master is doing.

**Comment by bparees** [comment]
at that point it seems like we should just dump the inherit behavior and make you set the log level in the buildconfig.  which btw you can already do w/ the buildoverride plugin, i think, unless the env variables you add there don't get applied to the build pod itself (which may be the case since i think we have another open issue for that).  @csrwng can confirm.

**Comment by csrwng** [comment]
We actually need to update the BuildDefaults plugin specifically to set the --loglevel argument on the build pod command line. At the point the pod executes the BUILD_LOGLEVEL env var is no longer relevant.

**Comment by smarterclayton** [comment]
The one place we want this is for our e2e tests - I want all builds to be
running at loglevel=5 for traceability.

**Comment by bparees** [comment]
@csrwng I was proposing we instead change the BuildDefaults plugin to set the env variables on the build pod itself and not just on the build definition env variable.  Which would solve @sdodson's issue
https://github.com/openshift/origin/issues/8663 and solve this at the same time (we'd just have to setup the BuildDefaults for our tests)

**Comment by bparees** [comment]
actually it wouldn't solve @sdodson's problem since he wants the values on the build object, not the build pod.  but at least having them on the build pod would be *slightly* better :)

**Comment by jupierce** [comment]
As someone who will probably need to change the build log level regularly, is there any chance to agree on something more accessible than the kube config? 
--build-logevel  could be an independent/global  (potentially even hidden) option for oc.

**Comment by bparees** [comment]
you can change the log level for any build by setting the BUILD_LOGLEVEL in the buildconfig if you need to change the log level.

we could consider adding a flag to "oc start-build" which let you explicitly set the loglevel for that build (which it would do by overriding the BUILD_LOGLEVEL env variable in the build it constructed)

**Comment by jupierce** [comment]
I believe it already exists for start-build (that is where I drew the suggested name). Relying on setting BUILD_LOGLEVEL/start-build after the fact seems to reduce our ability to debug build flows as part of higher level orchestrations (e.g. by new-app). Is it conceivable that new-app could unintentionally introduce temporary (and difficult to detect) environment/configuration/invocation differences that would trigger a build outcome not easily replicated by a subsequent invocation of start-build/elevated BUILD_LOGLEVEL?

Even if the answer is no, the the alternatives raise the barrier to acquiring problem determination data from users. As a new user to OpenShift, I would not think twice about re-running new-app with an additional parameter to get help from the community, but:
(1) the process of finding/altering a buildconfig might be daunting. 
(2) the process of altering a kube config in a simple cluster up environment is.. impossible? since it is generated.

All that said, I understand if these are not concerns if we rarely need to receive these logs from users.

**Comment by bparees** [comment]
> I believe it already exists for start-build (that is where I drew the suggested name).

hm, so it does. good for us :)

>  Is it conceivable that new-app could unintentionally introduce temporary (and difficult to detect) environment/configuration/invocation differences that would trigger a build outcome not easily replicated by a subsequent invocation of start-build/elevated BUILD_LOGLEVEL?

plausible..not incredibly likely, but the bigger problem is that any test that relies on new-app for buildconfig creation today (not including template instantiation since that can include the log setting in the template) would not be able to get verbose logging in that initial build, which would mean we'd have to do two builds or something else ugly.  So I agree that's definitely undesirable, but that's where the global build override defaulter comes in.  We would want to set the gobal default in our test environments.

If we had a scenario where new-app's initial buildconfig was not working correctly, we can always run new-app with "-o yaml" and then pipe it to oc set or just hack the yaml, before creating the buildconfig, to ensure the first build has the right loglevel.

> (1) the process of finding/altering a buildconfig might be daunting. 

i think it's just "oc new-app blah blah -o yaml | oc set env BUILD_LOGLEVEL=5"

> *(2) the process of altering a kube config in a simple cluster up environment is.. impossible? since it is generated.

would have to ask @csrwng but in any case i agree we aren't going to tell a cluster up user to go add a bulidconfig override to their cluster config.

All that said, for a "normal user" they aren't going to be able to update the cluster loglevel either, so the existing solution doesn't really work for them.  When we need build logs from a customer we don't tell them to "go restart your cluster with loglevel 5", we tell them "go update your buildconfig to level 5 and rerun the build"  (we should be telling them, go rerun the build with "--build-loglevel=5" but i didn't even know we had that option until you pointed it out :) )

So if your key point/question here is "there needs to be a way to set the build loglevel on the bulidconfig created by new-app" then I think the answer is that 1) there sort of is today and 2) once we implement the other issue you own (having a "-e" equivalent for new-app that sets env on buildconfigs) that will be another viable solution.

**Comment by jupierce** [comment]
Cool. The yaml trick didn't cross my mind. Thank you.
