### ISSUE TITLE
forbid webhook secrets smaller than at least 4 characters

### ISSUE THREAD

**Issue by PI-Victor** [openshift/origin#8752]
right now a user can define a webhook secret to just one letter e.g.: `a` i think the correct behavior security wise would be to prevent the user from defining a webhook secret smaller than at least 4 chars.

```
Triggered by:       ImageChange, Config
Webhook GitHub:
    URL:    https://localhost:8443/oapi/v1/namespaces/demo/buildconfigs/django-psql-example/webhooks/a/github
Webhook Generic:
    URL:        https://localhost:8443/oapi/v1/namespaces/demo/buildconfigs/django-psql-example/webhooks/a/generic
    AllowEnv:   false
```

@mfojtik @bparees PTAL.

**Comment by mfojtik** [comment]
@PI-Victor right, we should set some minimal length for the secrets.

**Comment by bparees** [comment]
whatever change we introduce here needs to be backwards compatible so we don't break existing webhook definitions that might be shorter.

(i'm also not totally sold on us enforcing this policy, it should be up to administrators to enforce a policy on these secrets, so it should probably be a cluster config setting or something, not an arbitrary limit).

**Comment by PI-Victor** [comment]
indeed, i didn't think about it from a backwards compatible perspective. i opened this issue for two reasons, the first is this comment: 
https://github.com/openshift/origin/pull/7518#issuecomment-212570186
and this:
https://github.com/openshift/origin/issues/8551#issuecomment-211522933

unrelated to this, i found a fix for the first comment :) 
https://github.com/openshift/origin/pull/7518/files#diff-93604b5222ea82b22529d3c4550a7685R80
(if it is just one letter, the secret gets obfuscated to ***)

i guess we can't be enforcing this, since it would potentially break other webhooks users already have, so your suggestion is the best. who do we have to bring in to this for clusters config, i'm guessing it's not done by us? i'm guessing this would be a bit more complicated than i have first imagined.

**Comment by bparees** [comment]
it can be done by us, but yes it's more complicated :)  (and i'm not an expert on it).
@csrwng has more experience adding things to the cluster config.

**Comment by PI-Victor** [comment]
@csrwng can you give me some pointers regarding this issue?

**Comment by csrwng** [comment]
@PI-Victor There's 2 ways that we can add to the cluster config:
1) Change the config API type to have some setting for the minimum secret length. For this you'd have to change the master config type:
https://github.com/openshift/origin/blob/master/pkg/cmd/server/api/types.go#L215
I'm not sure that this is the best approach, since I don't think we affect validation in this way for other types.

2) Introduce an admission plugin that will enforce the minimum secret length. If that's the case, then you can define your own config type for the admission plugin. Something like what we have for build defaults:
https://github.com/openshift/origin/blob/master/pkg/build/admission/defaults/api/types.go

If you decide that we should use an admission plugin, then you'd need to copy the structure of one our build admission plugins (like defaults and overrides) and modify the types/logic to suit the new plugin.

**Comment by PI-Victor** [comment]
@csrwng thank you, will look into it and see what solution is better.

**Comment by bparees** [comment]
no user has raised this as a concern, and the backwards compatibility challenges remain unsolved, so i'm closing this.
