### ISSUE TITLE
clusterrole and role registries don't do conflict detection on resourceVersion

### ISSUE THREAD

**Issue by liggitt** [openshift/origin#8781]
the following command does not return a resource conflict on the replace call, but should:
```
oc get clusterroles admin -o yaml > admin.yaml
oc edit clusterroles admin
... modify role and save...
oc replace -f admin.yaml
```

**Comment by deads2k** [comment]
A brief write up of history:


A resourceVersion is an opaque string.  A resourceType/resourceVersion tuple should have a stable meaning.  If you create a fake resourceVersion that isn't stable for the resource type, then there's a caching layer that relies on that for a decoding cache and will give bad information.  If you create a fake resourceVersion that can be duplicated on multiple resources of that type, then you break the same caching layer.  If you give one that isn't a monotonically increasing number, there's a watch cache that will break, but you probably don't care. 

Let's say you're willing to break the watch cache.  Now you need to be sure that your resourceVersion never collides with another in same type.  So you say, I know, I'll make it a UUID that I assign whenever I update the object.  That seems to work, until you attempt a watch.  Now you need to establish an ordering, not for a cache, but for any watch you ever want to make.  Without an ordering, you can't do a watch from version.  @liggitt rejects your pull because watch doesn't work and year later opens this issue.  

You best hope is that he's softened over the intervening year.

**Comment by stevekuznetsov** [comment]
Why is a `ClusterRole` not a first-class etcd citizen?

**Comment by deads2k** [comment]
> Why is a ClusterRole not a first-class etcd citizen?

@smarterclayton wanted to have a central place to track, "when were my roles last changed".  Another argument I lost and really wish I hadn't.  We're fixing it as the types move upstream.

**Comment by liggitt** [comment]
> Why is a ClusterRole not a first-class etcd citizen?

Because @smarterclayton

**Comment by stevekuznetsov** [comment]
So do we want the fix to this to be that `ClusterRole` becomes a first-class etcd citizen? Or do we want something intermittent before that is implemented? What's the time-table for the upstream migrations? How fast do we want this fixed?

**Comment by deads2k** [comment]
> So do we want the fix to this to be that ClusterRole becomes a first-class etcd citizen? Or do we want something intermittent before that is implemented? What's the time-table for the upstream migrations? How fast do we want this fixed?

We haven't said for sure that we're moving to the upstream types, though I suspect we'll probably try. 

You could try to sort out migration problems and claim it fixes this eventually :).  I'd start by creating a job that does a direct etcd select of all objects of a type, streams the response (its going to be big), decimates the list based on selection criteria (storage encoding version as a for instance), writes the new work to a series of files holding a fixed amount of records, then starts streaming the new files and applying changes.

That structure would allow us to easily split the job based on other criteria for an indexed job implementation.
