### ISSUE TITLE
Atomic Registry install fails with Oauth issue

### ISSUE THREAD

**Issue by rastapopulous** [openshift/origin#8913]
Installing the atomic registry fails with:

--> Creating resources ...
    deploymentconfig "registry-console" created
    service "registry-console" created
    imagestream "registry-console" created
    error: OAuthClient "cockpit-oauth-client" is invalid: scopeRestrictions: Required value: required when allowAnyScope is false

##### Version
[root@host origin]# oc version
oc v1.3.0-alpha.0-167-g4589987
kubernetes v1.3.0-alpha.1-331-g0522e63

##### Steps To Reproduce
Following the atomic commands:
sudo atomic install projectatomic/atomic-registry-quickstart
sudo atomic run projectatomic/atomic-registry-quickstart 

I did also attempt to run the commands that the run script executes. This is how I was able to capture all of the output from the script.
##### Additional Information
[try to run `$ oadm diagnostics` command if possible]
[if you are reporting issue related to builds, provide build logs with `BUILD_LOGLEVEL=5`]
[consider attaching output of the `$ oc get all -o json -n <namespace>` command to the issue]
[visit https://docs.openshift.org/latest/welcome/index.html]

**Comment by liggitt** [comment]
@deads2k for backwards compatibility issue

**Comment by deads2k** [comment]
@openshift/api-review It would really be a shame to have to default to dangerous.  

`allowAnyScope` was intended to be a very explicit choice by a cluster-admin to indicate "I trust this client so much that I'll allow him to request any scope he wants on the entire cluster, including policy, nodes, and direct token access"  Previously, that level of access was the default (and only) choice we had.

Can anyone think of a clever way to distinguish between "I'm an old object" and "I'm an object the cluster-admin forgot to restrict"?  If not, I see options as:
 1. maintain backwards compatibility and default to dangerous behavior for incomplete objects
 2. break backwards compatibility and default to safe behavior.

**Comment by smarterclayton** [comment]
Which class of users and usecases is affected?

On May 18, 2016, at 8:05 AM, David Eads <notifications@github.com> wrote:

@openshift/api-review <https://github.com/orgs/openshift/teams/api-review>
It would really be a shame to have to default to dangerous.

allowAnyScope was intended to be a very explicit choice by a cluster-admin
to indicate "I trust this client so much that I'll allow him to request any
scope he wants on the entire cluster, including policy, nodes, and direct
token access" Previously, that level of access was the default (and only)
choice we had.

Can anyone think of a clever way to distinguish between "I'm an old object"
and "I'm an object the cluster-admin forgot to restrict"? If not, I see
options as:

   1. maintain backwards compatibility and default to dangerous behavior
   for incomplete objects
   2. break backwards compatibility and default to safe behavior.

—
You are receiving this because you are on a team that was mentioned.
Reply to this email directly or view it on GitHub
<https://github.com/openshift/origin/issues/8913#issuecomment-220006323>

**Comment by deads2k** [comment]
> Which class of users and usecases is affected?

cluster-admins trying to migrate OAuthClients they've created in the past or re-use OAuthClient objects they previously stored.  I didn't think anyone was actually using them, so I fixed up ours, but no one else's.

This would be a very ugly problem, I don't want to downplay it.  Current OAuthClients would be restricted from even creating new tokens based on old authorizations, because validation enforces the `allowAnyScope` all the way down the referential chain.

It's pretty easy to describe the fix-up steps, but integrations that relied on the old pre-scope behavior would be broken by an upgrade in its current state.

**Comment by liggitt** [comment]
If an OAuthClient that used to work (or a newly created OAuthClient with a minimal definition) is now unusable, I think we chose wrong.

**Comment by deads2k** [comment]
> a newly created OAuthClient with a minimal definition

Can you think of any other field where we've chosen empty to mean "full powers"?  You had also suggested having  "full-access" scope instead of empty meaning full-access.  That would also break everyone, so is that a thing we want to do or no?

If it didn't default so dangerously I'd agree without hesitation.

**Comment by liggitt** [comment]
Restricting the scopes an OAuth client is allowed to request isn't a normal thing to do. The safeguard is typically at the point of grant approval
