### ISSUE TITLE
Give PVC priority when creating resources from a file?

### ISSUE THREAD

**Issue by jwendell** [openshift/origin#8999]
Hi guys.

I have a json file which defines 2 resources:
 - A pod which uses a dir mounted as a PVC
 - A PVC
In this order. The file: http://pastebin.test.redhat.com/376116

I run: oc create -f this-file.json

Then, on events page, I see:
```
Failed mount  Unable to mount volumes for pod "pod-jwendell-test_jwendell(95961d78-1e8d-11e6-b342-52540092d7e2)": failed to instantiate volume builder for xuxa: The claim claim-jwendell-test is not yet bound to a volume

Failed sync      Error syncing pod, skipping: failed to instantiate volume builder for xuxa: The claim claim-jwendell-test is not yet bound to a volume
```
If I change the order within the json file: first define PVC then the pod - the message is gone.

I'm wondering if this is due to the way the file is processed by kubernetes.
Maybe we should have a priority when creating resources based on a file? PVC's should be created first, then all others?

**Comment by liggitt** [comment]
Items are submitted one at a time in order to the server. I don't think we want to make all clients responsible for understanding all partial ordering implications of all types, including eventual third party resources. Ordering the items in the JSON file in create order is what I would recommend instead.
