### ISSUE TITLE
deployments with ICTs on images from image source/docker builds not firing

### ISSUE THREAD

**Issue by gabemontero** [openshift/origin#9120]
With as recent a commit level as 

`commit 7afe72b7bde43e291b4dac2c45ee92ee9f620ab3`
`Merge: 5af4c07 7302258`
`Author: OpenShift Bot <dmcphers+openshiftbot@redhat.com>`
`Date:   Wed Jun 1 07:07:54 2016 -0400`

`    Merge pull request #9079 from miminar/wait-until-registry-is-ready`
    
`    Merged by openshift-bot`

run `oc create -f ` on https://github.com/openshift/origin/blob/master/test/extended/fixtures/test-imagesource-build.yaml

then run `oc start-build imagesourcebuild` or `oc start-build imagedockerbuild`

You'll see the build complete and the image stream get updated with the resulting image, but neither of the deployments ever get launched.

This was originally seen with the extended test https://github.com/openshift/origin/blob/master/test/extended/builds/image_source.go, but I see it running against a local install, executing the above `oc` commands manually.

@bparees @csrwng FYI

**Comment by kargakis** [comment]
Yes, this is because the deployment configs don't have any config change triggers. 
@smarterclayton @ironcladlou we used to run deployments with ICTs, absent of ConfigChange triggers until https://github.com/openshift/origin/pull/8746. It is a breaking change but I am not sure how big. Most deployments should be using config change triggers. I really don't want to go back in the old behavior as it will inevitably reintroduce the races I have been chasing with https://github.com/openshift/origin/pull/8746. Btw, I started writting up about deployment triggers in https://github.com/openshift/openshift-docs/pull/2150

**Comment by bparees** [comment]
@gabemontero i'm ok w/ updating the tests in question to add ConfigChangeTriggers but that may further break the tests since most of them probably assume there will be no deployment until the build completes, so additional refactoring may be necessary to get back to a working state.

It would be nice if ConfigChangeTrigger offered an option to not cause an immediate deployment on creation (this would also solve the whole "the image field is wrong until the ICT fires and fixes it, so you get a failed deployment" problem).

**Comment by gabemontero** [comment]
@bparees adding the ConfigChange trigger was sufficient to getting the image_source.go tests to pass again.  Based on the tracing in the master on my local run, it appears to pull the image produced by the build.

I'll create a PR to update the test case - close this out.

+1 on the ConfigChangeTrigger option around creation / immediate deployment (even if such an option is only valid if an ICT is also defined).

**Comment by smarterclayton** [comment]
We can't break old users.  We have to deal with this case cleanly.

On Jun 1, 2016, at 7:05 PM, Michail Kargakis <notifications@github.com>
wrote:

Yes, this is because the deployment configs don't have any config change
triggers.
@smarterclayton <https://github.com/smarterclayton> @ironcladlou
<https://github.com/ironcladlou> we used to run deployments with ICTs,
absent of ConfigChange triggers until #8746
<https://github.com/openshift/origin/pull/8746>. It is a breaking change
but I am not sure how big. Most deployments should be using config change
triggers. I really don't want to go back in the old behavior as it will
inevitably reintroduce the races I have been chasing with # 8746
<https://github.com/openshift/origin/pull/8746>. Btw, I started writting up
about deployment triggers in openshift/openshift-docs#2150
<https://github.com/openshift/openshift-docs/pull/2150>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/origin/issues/9120#issuecomment-223150881>,
or mute the thread
<https://github.com/notifications/unsubscribe/ABG_pxP0jAfWsM-uPBHbraYsSxYozsoSks5qHhAogaJpZM4Ir8tQ>
.

**Comment by kargakis** [comment]
> @gabemontero i'm ok w/ updating the tests in question to add ConfigChangeTriggers but that may further break the tests since most of them probably assume there will be no deployment until the build completes, so additional refactoring may be necessary to get back to a working state.
> It would be nice if ConfigChangeTrigger offered an option to not cause an immediate deployment on creation (this would also solve the whole "the image field is wrong until the ICT fires and fixes it, so you get a failed deployment" problem).

@bparees I thought we already discussed about this. It's the current behavior in master.

**Comment by kargakis** [comment]
> We can't break old users. We have to deal with this case cleanly.

This is totally understandable. Can we decide what do we want to do with triggers in general though? Do we want to separate ICT from CC and trigger only on CC, or do we want to keep the old behavior as the correct behavior?

**Comment by kargakis** [comment]
Opened #9132

**Comment by smarterclayton** [comment]
I think the presence of automatic ict should imply cc.

**Comment by bparees** [comment]
> @bparees I thought we already discussed about this. It's the current behavior in master.

Sorry I lost track of that bit...  so if i have an ICT and CCT, the CCT won't cause anything to happen until the ICT is resolved?  I guess you did explain that, sorry.  your docs pull may need to make that behavior clearer though (https://github.com/openshift/openshift-docs/pull/2150)

**Comment by kargakis** [comment]
> Sorry I lost track of that bit... so if i have an ICT and CCT, the CCT won't cause anything to happen until the ICT is resolved?

Exactly. Note that we need to restore ICTs triggering deployments without CCTs (#9132) so I need to update my docs pull to reflect that.

**Comment by kargakis** [comment]
> I think the presence of automatic ict should imply cc.

I have been leaning towards this too but note that by making ICT trigger always (on automatic:true) we lose the ability to have image updates with manual deployments (something @bparees was interested in).

**Comment by smarterclayton** [comment]
Image updates on manual deployments is what the generator / instantiate
endpoint should solve.

**Comment by kargakis** [comment]
How should a user ask for it on a deployment config? "I want the image on
my template to be updated every time there is a new image but I want to
trigger manually".
I am not sure the generator or the instantiate endpoint solve this.

**Comment by smarterclayton** [comment]
automatic:true is not manual deployments.  Manual deployments is "I
literally am the person doing the deployments, but when I hit the 'button'
that does the deployment I want the latest image".

**Comment by kargakis** [comment]
Oh, I see. So you want a variant of --latest that will actually deploy what's latest.

**Comment by smarterclayton** [comment]
Yeah, that's ben's request.  And I think that's actually more correct for
most people when you say "--latest".  The closer we get to upstream, the
harder it is for us to support the "plan a deployment" flow where we
pre-create an RC, but that's ok.   I think these are the scenarios that
matter:

1. I can get automatic deployments whenever images change
2. When I change a DC, I get a new deployment
3. When I need to, I can "plan" a deployment and then at a time of my
choosing let the deployment proceed (could be "pause", "edit", then
"unpause")
4. I want to disable automatic deployments from images, but run deploy
--latest and pick up the latest images
5. I want to disable automatic deployments from images, and decide myself
whether to pick up the latest images

These are in order of importance - the last scenario can be emulated by not
having any triggers at all, and just using oc set image.  So I think 1-4
are what we want to have clear experiences around.

**Comment by bparees** [comment]
automatic=false, but always being resolved when a deployment occurs, would also solve my use case i believe.  (automatic=true -> do a deploy when the image changes.  automatic=false -> don't trigger a deploy, but if a deploy happens for another reason (CCT, manual), use this ICT to resolve the image).

that was always my preferred behavior, but since the model appears to be "only CCTs trigger deploys, ICTs only update the config", that's not possible today (except that we're reverting some of that behavior to stay backwards compatible).

in anycase i think i agree with @smarterclayton's set of scenarios, whatever mechanism we use to get there.  Maybe the one missing one is "when i create a DC i get a deployment that uses the latest image and does not use the existing image field value".  It's pretty much the same as (1) but as we've seen, is tricky to get right.

**Comment by kargakis** [comment]
I am not sure we want to deploy things not in the dc template but magically resolved in the rc. We already diverge from upstream deployments, doing that would move us more away. At the very least, I want the template of my config to be the template I am deploying.
