### ISSUE TITLE
Please ~ How to make the external network access the pods？

### ISSUE THREAD

**Issue by lifei825** [openshift/origin#9127]
Please ~ Why now openshift can only do 7 layer load balancing ，can not do  4 layer load balance？Any good methods?

How to make the external network access the pods

**Comment by knobunc** [comment]
Several options.

You can run a load balancer image on an edge node: https://docs.openshift.com/enterprise/3.2/install_config/routing_from_edge_lb.html

You would have to give the image permission to access the host network so that it can be reached from outside, as you do with a router: https://docs.openshift.com/enterprise/3.2/install_config/install/deploy_router.html#creating-the-router-service-account

You can also use the externalIP http://kubernetes.io/docs/user-guide/services/#external-ips or the nodePort.

We also have high-availability services documented here: https://docs.openshift.com/enterprise/3.2/admin_guide/high_availability.html


We are looking at making it easier with the feature tracked here: https://trello.com/c/9TXvMeS2/54-13-supporting-non-http-s-80-443-traffic-routes-traffic-ingress

**Comment by lifei825** [comment]
Thank you very much ！
