### ISSUE TITLE
[builds][Conformance] build without output image building from templates [It] should create an image from "test-s2i-no-outputname.json" S2i template without an output image reference defined

### ISSUE THREAD

**Issue by stevekuznetsov** [openshift/origin#9221]
```
   9708 Jun 08 08:11:35 ESC[91mESC[1m• Failure [33.538 seconds]ESC[0m
   9709 Jun 08 08:11:35 [builds][Conformance] build without output image
   9710 Jun 08 08:11:35 ESC[90m/data/src/github.com/openshift/origin/test/extended/builds/no_outputname.go:49ESC[0m
   9711 Jun 08 08:11:35   building from templates
   9712 Jun 08 08:11:35   ESC[90m/data/src/github.com/openshift/origin/test/extended/builds/no_outputname.go:48ESC[0m
   9713 Jun 08 08:11:35     ESC[91mESC[1mshould create an image from "/data/src/github.com/openshift/origin/test/extended/fixtures/test-s2i-no-outputname.json" S2i template without an output image reference defined [It]ESC[0m
   9714 Jun 08 08:11:35     ESC[90m/data/src/github.com/openshift/origin/test/extended/builds/no_outputname.go:47ESC[0m
   9715 Jun 08 08:11:35 
   9716 Jun 08 08:11:35     ESC[91mExpected error:
   9717 Jun 08 08:11:35         <*exec.ExitError | 0xc820be22e0>: {
   9718 Jun 08 08:11:35             ProcessState: {
   9719 Jun 08 08:11:35                 pid: 26591,
   9720 Jun 08 08:11:35                 status: 256,
   9721 Jun 08 08:11:35                 rusage: {
   9722 Jun 08 08:11:35                     Utime: {Sec: 0, Usec: 103657},
   9723 Jun 08 08:11:35                     Stime: {Sec: 0, Usec: 9805},
   9724 Jun 08 08:11:35                     Maxrss: 23636,
   9725 Jun 08 08:11:35                     Ixrss: 0,
   9726 Jun 08 08:11:35                     Idrss: 0,
   9727 Jun 08 08:11:35                     Isrss: 0,
   9728 Jun 08 08:11:35                     Minflt: 6007,
   9729 Jun 08 08:11:35                     Majflt: 0,
   9730 Jun 08 08:11:35                     Nswap: 0,
   9731 Jun 08 08:11:35                     Inblock: 0,
   9732 Jun 08 08:11:35                     Oublock: 0,
   9733 Jun 08 08:11:35                     Msgsnd: 0,
   9734 Jun 08 08:11:35                     Msgrcv: 0,
   9735 Jun 08 08:11:35                     Nsignals: 0,
   9736 Jun 08 08:11:35                     Nvcsw: 2008,
   9737 Jun 08 08:11:35                     Nivcsw: 2,
   9738 Jun 08 08:11:35                 },
   9739 Jun 08 08:11:35             },
   9740 Jun 08 08:11:35             Stderr: nil,
   9741 Jun 08 08:11:35         }
   9742 Jun 08 08:11:35         exit status 1
   9743 Jun 08 08:11:35     not to have occurredESC[0m
   9744 Jun 08 08:11:35 
   9745 Jun 08 08:11:35     /data/src/github.com/openshift/origin/test/extended/builds/no_outputname.go:45


 12613 Jun 08 08:19:02 [Fail] [builds][Conformance] build without output image building from templates [It] should create an image from "/data/src/github.com/openshift/origin/test/  12613 extended/fixtures/test-s2i-no-outputname.json" S2i template without an output image reference defined
  12614 Jun 08 08:19:02 /data/src/github.com/openshift/origin/test/extended/builds/no_outputname.go:45
```

**Comment by bparees** [comment]
1) please include links the jenkins job for these failures so i can look into the other artifacts
2) this is probably all tied to the current docker 1.10 fiasco which is causing build failures all over the place.

**Comment by stevekuznetsov** [comment]
@bparees there is no Jenkins job, ran it through AWS and have artifacts locally if you need them

**Comment by bparees** [comment]
@stevekuznetsov i'd be interested the see the container/pod logs for the build container/pod.

**Comment by stevekuznetsov** [comment]
@bparees I don't think we keep those by default -- I only see the registry, router and router deployment logs

**Comment by bparees** [comment]
not enough info for me to do anything w/ this.  if you see it again after the docker 1.10 issue is resolved we can revisit it.

**Comment by smarterclayton** [comment]
We have more output now:

https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_conformance/2188/testReport/junit/(root)/Extended/_builds__Conformance__build_without_output_image_building_from_templates_should_create_an_image_from___data_src_github_com_openshift_origin_test_extended_testdata_test_docker_no_outputname_json__docker_template_without_an_output_image_reference_defined/

and potentially

```
    Pull complete
    Pull complete
    Digest: sha256:e563afa6ad4c5308ce3d26fd8a77424fc872f34cf206463b9dc454bd68d4ee50
    Status: Downloaded newer image for docker.io/centos/ruby-22-centos7:latest
     ---> d93cfcb54fe8
    Step 2 : USER default
     ---> Running in 03e56520fa00
     ---> d5062fa69803
    Removing intermediate container 03e56520fa00
    Step 3 : EXPOSE 8080
     ---> Running in a73ff5fcbcf9
     ---> 80686777e299
    Removing intermediate container a73ff5fcbcf9
    Step 4 : ENV RACK_ENV production
     ---> Running in c08c1dc66c70
     ---> cd1eb89a90fd
    Removing intermediate container c08c1dc66c70
    Step 5 : ENV RAILS_ENV production
     ---> Running in bb07a16c6de2
     ---> 7acae3703c72
    Removing intermediate container bb07a16c6de2
    Step 6 : COPY . /opt/app-root/src/
     ---> 6f9b8dae5a7a
    Removing intermediate container 800d84cbf57c
    Step 7 : RUN scl enable rh-ruby22 "bundle install"
     ---> Running in f61a991337de
    Fetching gem metadata from https://rubygems.org/..........
    Installing rake 10.3.2
    Installing i18n 0.6.11
    Installing json 1.8.3
    Installing minitest 5.4.2
    Installing thread_safe 0.3.4
    Installing tzinfo 1.2.2
    Installing activesupport 4.1.7
    Installing builder 3.2.2
    Installing activemodel 4.1.7
    Installing arel 5.0.1.20140414130214
    Installing activerecord 4.1.7
    Installing mysql2 0.3.16
    Installing rack 1.5.2
    Installing rack-protection 1.5.3
    Installing tilt 1.4.1
    Installing sinatra 1.4.5
    Installing sinatra-activerecord 2.0.3
    Using bundler 1.7.8
    Your bundle is complete!
    Use `bundle show [gemname]` to see where a bundled gem is installed.
    net/http: request canceled
to contain substring
    <string>: Build complete, no image push requested
```

**Comment by smarterclayton** [comment]
@csrwng issues

**Comment by smarterclayton** [comment]
I'm going to disable the test for now because it's blocking the queue

**Comment by csrwng** [comment]
@smarterclayton so for the `net/http: request canceled` problem, the cause is the use of the new Docker client in the kubelet. We're basically timing out any container logs call at 2 minutes:

https://github.com/openshift/origin/blob/master/Godeps/_workspace/src/k8s.io/kubernetes/pkg/kubelet/dockertools/kube_docker_client.go#L241

https://github.com/openshift/origin/blob/master/Godeps/_workspace/src/k8s.io/kubernetes/pkg/kubelet/dockertools/kube_docker_client.go#L400

https://github.com/openshift/origin/blob/master/Godeps/_workspace/src/k8s.io/kubernetes/pkg/kubelet/dockertools/kube_docker_client.go#L57

**Comment by liggitt** [comment]
Does that apply to pulls as well?

**Comment by liggitt** [comment]
Or exec/attach?

**Comment by csrwng** [comment]
> Does that apply to pulls as well?

Looks that way:
https://github.com/openshift/origin/blob/master/Godeps/_workspace/src/k8s.io/kubernetes/pkg/kubelet/dockertools/kube_docker_client.go#L201

I don't think the timeout applies to exec/attach because it only times out the call to get/hijack the connection, but then you own the connection.

**Comment by smarterclayton** [comment]
Let's open an upstream issue - logs and pull are both concerning.  We def
want the ability to selectively choose this.

On Jun 16, 2016, at 8:58 PM, Cesar Wong <notifications@github.com> wrote:

Does that apply to pulls as well?

Looks that way:
https://github.com/openshift/origin/blob/master/Godeps/_workspace/src/k8s.io/kubernetes/pkg/kubelet/dockertools/kube_docker_client.go#L201

I don't think the timeout applies to exec/attach because it only times out
the call to get/hijack the connection, but then you own the connection.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/origin/issues/9221#issuecomment-226655239>,
or mute the thread
<https://github.com/notifications/unsubscribe/ABG_p3AZ5-ZaPAAwKz6tM4s6Uypj59a0ks5qMfEggaJpZM4IxAji>
.

**Comment by csrwng** [comment]
There's already an issue for pulls https://github.com/kubernetes/kubernetes/issues/26626

**Comment by csrwng** [comment]
Looks like upstream the timeout for pulls was removed, but not for logs:
https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/dockertools/kube_docker_client.go#L300

**Comment by smarterclayton** [comment]
I think that's a 1.3 blocker

On Jun 16, 2016, at 9:11 PM, Cesar Wong <notifications@github.com> wrote:

Looks like upstream the timeout for pulls was removed, but not for logs:
https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/dockertools/kube_docker_client.go#L300

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/origin/issues/9221#issuecomment-226656799>,
or mute the thread
<https://github.com/notifications/unsubscribe/ABG_p6lMBTZ1ONcnl4Z9ilP62EfuHXisks5qMfRTgaJpZM4IxAji>
.

**Comment by csrwng** [comment]
Issue created for logs: https://github.com/kubernetes/kubernetes/issues/27588

**Comment by smarterclayton** [comment]
I'm going to create and merge a carry patch for both of those.

**Comment by smarterclayton** [comment]
https://github.com/openshift/origin/pull/9392
