### ISSUE TITLE
need to dump build logs on any extended test failure

### ISSUE THREAD

**Issue by bparees** [openshift/origin#9235]
Many of our extended tests wait for a build to succeed.  Some of them will dump the logs if that build fails, like this one:
https://github.com/openshift/origin/blob/master/test/extended/builds/docker_pullsecret.go#L54-L57

but other ones don't.  Any place where we're doing a waitforabuild we should be dumping the logs on failure (unless the test is expecting the build to fail).

we also have another pattern in some places:
https://github.com/openshift/origin/blob/master/test/extended/builds/no_outputname.go#L41-L46

we should change it, as was done in this PR:
https://github.com/openshift/origin/pull/9186/files

because the --wait --follow pattern is problematic if the build immediately fails, and we don't end up getting any logs.

**Comment by bparees** [comment]
@stevekuznetsov fyi

**Comment by jupierce** [comment]
Appears to pre-req fix for #9247 before I can test my changes. @csrwng

**Comment by bparees** [comment]
@jupierce no that shouldn't be a prereq, this is about test code logging, not product logging.

**Comment by csrwng** [comment]
@bparees, what @jupierce was seeing is that some extended tests that expect to find certain strings in the log are failing. He didn't want to deliver his change with failing tests.

**Comment by bparees** [comment]
@csrwng ah, ok.

**Comment by jupierce** [comment]
@bparees , @csrwng Unfortunately, fixing #9247 does not address the extended build test failures in my environment.

Focusing in on one spec failure (of 5 in my env): secrets.go, which checks build output for the presence of a string "secret1=secret1" which is supposed to be echo'd from test/extended/testdata/build-secrets/Dockerfile during build.

This echo is only sporadically visible in my bc/test log output, so my extended build tests nearly always fails here. 

Failing run build logs:
`Step 5 : RUN test -f /secrets/secret1 && echo -n "secret1=" && cat /secrets/secret1
 ---> Using cache
 ---> b00dec33854a
Step 6 : RUN test -f /secret2 && echo -n "relative-secret2=" && cat /secret2
 ---> Using cache
 ---> 666a6b7c4bf8
`

Cesar suggested moving these echos out of the Dockerfile and performing a test on the resultant container instead of the build log.

**Comment by bparees** [comment]
if you setup the dockerfile to always fail (RUN exit 1 as the last line), you'll always get the full output.  See:
https://github.com/openshift/origin/blob/master/test/extended/testdata/build-quota/Dockerfile#L7-L8

(this is only an acceptable solution if it's ok for the test to expect failure of the build, of course).

**Comment by jupierce** [comment]
@bparees  Unfortunately, secrets.go expects a successful build. Your description sounds like stdout from RUN can be buffered and lost, so I tried forcing the secrets to unbuffered stderr:
RUN (test -f /secrets/secret1 && echo -n "secret1=" && cat /secrets/secret1) >&2
RUN (test -f /secret2 && echo -n "relative-secret2=" && cat /secret2) >&2

See screenshot for ginkgo output
![screenshot from 2016-06-15 09-42-03](https://cloud.githubusercontent.com/assets/19783215/16081885/7eb50cfe-32dd-11e6-84a3-9630bfa0cf37.png)

You can clearly see the desired secret string in the build output. I assume this means Docker is inserting control characters to colorize the stderr output. Spoke with @csrwng and decided to change approaches and output secrets as part of running the image.

**Comment by stevekuznetsov** [comment]
Yes, this definitely does not seem like it should be done within the Dockerfile. If you can't make that switch work, you could always do a 'contains' check for your output instead of a 'equal' check so that you can ignore the colorization output sent to the terminal.

This actually is a little bit of a pain point for me working with Ginkgo and not with a TTY -- in our text lib I make sure to only use colorization chars if we're in a TTY where they mean something, but Ginkgo doesn't seem to follow that convention. Perhaps there's a flag we could flip to change that? Unclear.

**Comment by jupierce** [comment]
@stevekuznetsov The check that is failing is actually a contains (vs equals). So it as if Docker is colorizing each character and throwing off the string substring match.

**Comment by stevekuznetsov** [comment]
@jupierce incredible

**Comment by bparees** [comment]
@csrwng's approach sounds fine.

**Comment by jupierce** [comment]
Tried using a deployment config to run the newly designed docker image, but DC's do not allow restartPolicy:Never. Changing to define/launch Pod manually.

**Comment by jupierce** [comment]
I was able to get the docker s2i secrets.go test passing using a pod template and new-app, but found another, more direct, pattern in the test cases to achieve the same thing using k8s test APIs directly. The docker s2i secrets test now passes consistently in my environment.
Moving on to the other test spec in secrets.go which relies on the inconsistent docker build output stream capture.

**Comment by csrwng** [comment]
@jupierce are you going to submit a PR for that fix?

**Comment by jupierce** [comment]
@csrwng PR for secrets failure submitted & merged: #9412
