### ISSUE TITLE
First build image pushes are very slow, even though the registry already has the base layers

### ISSUE THREAD

**Issue by sspeiche** [openshift/origin#9284]
As a new user create a new project and performs a build for the very first time, the initial image push time takes minutes but subsequent image pushes takes seconds. This doesn't make sense as the registry already has the base builder image, so we should streamline it so the client doesn't have to push it back.

Here are some samples:

1. Existing user, deleted and created project sspeiche-test2
Build times (base wildfly:10 + sample):
   1. 46 seconds
   2. 43 seconds
   3. 49 seconds
   4. 41 seconds

2. Existing user, new project sspeiche-test3
Build times (base wildfly:10 + sample):
  1. 4 minutes, 2 seconds
  2. 41 seconds
  3. 42 seconds
  4. 51 seconds
  5. 46 seconds

3. Existing user, deleted and created project sspeiche-test3
Build times (base wildfly:10 + sample):
  1. 48 seconds
  2. 49 seconds
  3. 45 seconds
  4. 43 seconds

##### Version
v3.2.0.44
Kubernetes Master:
v1.2.0-36-g4a3f9c5

**Comment by smarterclayton** [comment]
@legionius I assume this is the link store on disk rejecting the link action on the initial pull.

**Comment by sspeiche** [comment]
fyi @mffiedler

**Comment by smarterclayton** [comment]
Beyond the change in the linkedBlobStore (which is the bulk of the issue), there may be further problems.  Working with Jason I was seeing some long delays and other unexpected timeouts on push.

Pullthrough #9394 issue is partially to blame, and *think* that we may have a a flake that is caused by us initializing the client libraries once per registry request that also sometimes fails (which I plan on fixing shortly).  My worry is the there is another issue beyond this.
