### ISSUE TITLE
Investigate turning off the deployer pod controller

### ISSUE THREAD

**Issue by kargakis** [openshift/origin#9296]
The only job of the deployer pod controller is to monitor the deployer pod status and update the status of the deployment. Having the deployment status being updated from two different places (deployer pod controller, deployment controller) is racy although we guarantee the direction of the deployment phase.

The deployment controller already fetches the deployer pod in a couple of places to ensure it exists. We are going to share a pod cache with the deployment controller anyway and we could also requeue deployments when their deployer pods are updated. Then the deployment controller could simply observe the status of the deployer pod and be the single update source of deployments.

@ironcladlou @smarterclayton @mfojtik

**Comment by smarterclayton** [comment]
Sgtm but do we have to inform on the pod as well?

On Jun 12, 2016, at 8:28 AM, Michail Kargakis <notifications@github.com>
wrote:

The only job of the deployer pod controller is to monitor the deployer pod
status and update the status of the deployment. Having the deployment
status being updated from two different places (deployer pod controller,
deployment controller) is racy although we guarantee the direction of the
deployment phase.

The deployment controller already fetches the deployer pod in a couple of
places to ensure it exists. We are going to share a pod cache with the
deployment controller anyway and we could also requeue deployments when
their deployer pods are updated. Then the deployment controller could
simply observe the status of the deployer pod and be the single update
source of deployments.

@ironcladlou <https://github.com/ironcladlou> @smarterclayton
<https://github.com/smarterclayton> @mfojtik <https://github.com/mfojtik>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/origin/issues/9296>, or mute the thread
<https://github.com/notifications/unsubscribe/ABG_p3MW9YJmD3Wm_0S1X0nWbshO5_P9ks5qK_t0gaJpZM4Izx8n>
.

**Comment by kargakis** [comment]
What do you mean with this? The deployer controller isn't updating anything
on the pod.

**Comment by smarterclayton** [comment]
Today we trigger edges based on pod status changes - so I was asking
whether you had an alternative approach that avoided the needed to be
informed on pod changes.  But it sounds like you're saying no.

**Comment by kargakis** [comment]
Well, actually there is a way just by looking at the deploymentconfig
status and that's what we are going to do upstream:
`dc.Status.ObservedGeneration >= dc.Generation && dc.Spec.Replicas ==
dc.Status.UpdatedReplicas` means Complete
We can throw in the mix `dc.Status.AvailableReplicas` to ensure minimum
availability.

**Comment by kargakis** [comment]
If we want to do this for us, then the deployer pod needs to update the
status of the deployment config.

**Comment by kargakis** [comment]
And it will need to retry on update conflicts

**Comment by kargakis** [comment]
> If we want to do this for us, then the deployer pod needs to update the status of the deployment config.

Scratch that, once we add caches in the deployment config controller, changes on the replication controllers will requeue the deployment config so its status will always be synced with the deployer pod.

**Comment by kargakis** [comment]
> Scratch that, once we add caches in the deployment config controller

Done. #9327
