### ISSUE TITLE
Go Deps in code is out of sync with external vendors repos

### ISSUE THREAD

**Issue by mjudeikis** [openshift/origin#9416]
Origin Go libs uses some libraries for external repos. And they where moved or does not exist anymore. 
/github.com/openshift/origin/pkg/cmd/cli/describe/describer.go:14:2: cannot find package "github.com/docker/docker/pkg/units" in any of:

Describer.go uses docker units, which does not exist anymore on 
https://github.com/docker/docker/tree/master/pkg

and looks like it was moves to:
htps://github.com/docker/go-units
##### Steps To Reproduce
1. Create new go project
2. include "github.com/openshift/origin/pkg/cmd/util/clientcmd"
3. try resolve dependencies using godep (go get)
4. see how it fails

**Comment by mfojtik** [comment]
@Mangirdaz I believe we vendor docker/docker so it might exists in the version OpenShift uses. @legionus do you know if we migrated ourself to docker/go-units with the distribution bump?

**Comment by mfojtik** [comment]
@eparis ptal

**Comment by Mangirdaz** [comment]
@mfojtik  it exists. But its so frustrating to handle all stuff. In example if you just coding with origin project all is good, you just take your branch and make things happen.

But if you want to use origin pkg as imports in external project, and do not take your dependencies but doing fresh install with "go get" it downloads origin, which specifies k8s and some docker, and other dependencies, which noes not exist anymore (or is broken with code breaking changes) in the main repos.
So all stuff breaks. 

Now basically I copy half stuff from your local copy, other from k8s project,  etc...

Its just wrong :D *nostalgically thinking about maven*

**Comment by legionus** [comment]
> @legionus do you know if we migrated ourself to docker/go-units with the distribution bump?

No. Last time it was [updated](https://github.com/openshift/origin/commit/faef31672d86b3b55a6e639f5558c5d8cba9aa94) by @deads2k .

**Comment by legionus** [comment]
@Mangirdaz `go get` will not be enough anyway. You need to use our dependencies placed in Godeps. Some of them have specific patches. We care about these patches until they will be moved to upstream. So even if you get all the dependencies yourself you can't compile the origin.

**Comment by Mangirdaz** [comment]
@legionus so basically i'm stuck with your version of Dep as long as I want to use origin packages (like api and cmd ones...) and as they have hard deps to k8s ones, they are locked too..

**Comment by eparis** [comment]
Right. One should do
`godep restore`
Which will fill out $GOPATH with the package versions necessary in origin. if you then choose to update or change those versions of course you will need to update everything...

But should then be able to use origin in your code since all of the deps will be solved in GOPATH.

That's the theory. Reality is quite different. At the moment origin has 3 major Godep problems.

1. is fixed by https://github.com/openshift/origin/pull/9440
2. is that speter.net/go/exp/math/dec/inf doesn't exist AT ALL any more and origin hasn't updated (everything) to gopkg.in/inf.v0. This can be solved by manually cloning gopkg.in/inf.v0 into $GOPATH/src/speter.net/go/exp/math/dec/inf
3. Godeps/Godeps.json lists a SHA for etcd which is in fact NOT the sha of the code. I think that @sjenning is currently looking at this particular problem.
4. We do crazy stuff like use the contents of github.com/openshift/kubernetes but pretend it is from k8s.io/kubernetes...

I tried to write a script to automate `godep restore` but never got it merged. And today I know someone is extending it. 
https://github.com/eparis/origin/blob/81346a238c0978d9543f5bb59b04d6bf0d9ae563/hack/godeps/restore.sh was my start.

So 2/4 of the problems with `godep restore` are likely things we broke in the last rebase and have no automated testing.
1/4 was code.google.com just plain disappearing from the face of the earth which really conflicts with the golang import model.
1/4 is just how we do things.

I hope the @sjenning will post a PR with a functioning "godep-restore.sh" very soon now...

**Comment by Mangirdaz** [comment]
For this main reason we have like 4-6 good projects in github which all of them I tried to fork, but failed due they all use different version of origin code which is now broken and does not even compile (for the cases kike 1 or 4 )

Thanks for info and hints... and looking forward to some dep tiding.

**Comment by sjenning** [comment]
The last bump for github.com/coreos/etcd didn't update Godeps.json
https://github.com/openshift/origin/commit/e20b7480b71d75bc7d165bef35e0788009cc4e0f
