### ISSUE TITLE
oc status should warn about missing rolebindings

### ISSUE THREAD

**Issue by kargakis** [openshift/origin#9479]
See https://github.com/openshift/origin/issues/9216#issuecomment-225552898

We should warn about missing rolebindings for the default service accounts (default, deployer, builder) in a project and show appropriate warnings depending on the role of the user? Throwing out some ideas: If you cannot touch rolebindings, we should have a warning similar to the missing registry/router warning. If you are the administrator, we should walk you through it? We could also suggest the use of `oc new-project`.

@deads2k handing this to you, maybe @enj or somebody else wants to have it.

**Comment by deads2k** [comment]
I like the idea of having a "project should have things that look roughly like this" check, but I'd probably want to build it as a set of those things rather than a one off for particular rolebindings.

RoleBindings and Roles in `oc status` are an interesting idea in their own right.  Given the rules review endpoint and API discovery, it's now possible to make more intelligent choices.
