### ISSUE TITLE
Add a pvc reaper

### ISSUE THREAD

**Issue by kargakis** [openshift/origin#9534]
Scoped to deployment configs at start

Forked from https://github.com/openshift/origin/issues/9059

cc: @smarterclayton @mfojtik @ironcladlou

**Comment by smarterclayton** [comment]
I struggle with why I want this.  Pvcs don't own deployment configs or vice
versa.  How often does a user actually want this behavior (total, as well
as on deletes)?

On Jun 23, 2016, at 7:01 PM, Michail Kargakis <notifications@github.com>
wrote:

Scoped to deployment configs at start

Forked from #9059 <https://github.com/openshift/origin/issues/9059>

cc: @smarterclayton <https://github.com/smarterclayton> @mfojtik
<https://github.com/mfojtik> @ironcladlou <https://github.com/ironcladlou>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/origin/issues/9534>, or mute the thread
<https://github.com/notifications/unsubscribe/ABG_p1voVLhyA6t0Xxot-5_n120u_-B9ks5qOxBGgaJpZM4I9Ui0>
.

**Comment by smarterclayton** [comment]
Note that my general opinion is that no one should be allowed to
deleted PVCs without filling out forms in triplicate and solving
Fermat's Last Theorem.

**Comment by liggitt** [comment]
Agree. That's like saying your documents folder should be deleted automatically when you uninstall OpenOffice

**Comment by liggitt** [comment]
The title of this may be misleading… is this to remove PVC references from DCs when a PVC is deleted?

**Comment by smarterclayton** [comment]
What if the reason I deleted my PVC was to get a new one?

On Jun 23, 2016, at 7:51 PM, Jordan Liggitt <notifications@github.com>
wrote:

The title of this may be misleading… is this to remove PVC references from
DCs when a PVC is deleted?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/origin/issues/9534#issuecomment-228219264>,
or mute the thread
<https://github.com/notifications/unsubscribe/ABG_pzG3zZ6UejahxcIp6Hp4hxwb_B5Eks5qOxwBgaJpZM4I9Ui0>
.

**Comment by smarterclayton** [comment]
(And thus want my references)?

**Comment by liggitt** [comment]
Yeah, and I'm not even sure what the reference reaper would do. Remove the volume (It would have to remove any volume mounts as well. At which point your DC redeploys and those paths are no longer persisted or shared between containers) or change the volume to empty dir (at which point the DC redeploys and maaaaybe keeps working with ongoing ephemeral data loss)

**Comment by kargakis** [comment]
> (And thus want my references)?

`oc delete pvc/foo --cascade=false`

Anyway, this is keeping track of the cli work for https://bugzilla.redhat.com/show_bug.cgi?id=1337696. I don't really carea bout it, just wanted to discuss it further.

> At which point your DC redeploys and those paths are no longer persisted or shared between containers) or change the volume to empty dir (at which point the DC redeploys and maaaaybe keeps working with ongoing ephemeral data loss)

We could pause the DC so no new deployment would run.

**Comment by liggitt** [comment]
defaulting to removing data is what concerns me, especially when there's not a clear ownership relationship either direction between pvcs and dcs
```
oc delete pvc/foo --cascade=false
```

**Comment by smarterclayton** [comment]
Yeah, pvcs don't "own" DCs or vice versa unless a user explicitly tells us.

**Comment by kargakis** [comment]
> Yeah, pvcs don't "own" DCs or vice versa unless a user explicitly tells us.

How can they explicitly tell us this?

**Comment by smarterclayton** [comment]
The new "ownership" field that server side cascading deletion will use.

On Jun 24, 2016, at 10:30 AM, Michail Kargakis <notifications@github.com>
wrote:

Yeah, pvcs don't "own" DCs or vice versa unless a user explicitly tells us.

How can they explicitly tell us this?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/origin/issues/9534#issuecomment-228361342>,
or mute the thread
<https://github.com/notifications/unsubscribe/ABG_p4UIM8FlbI_Nc0QXUBfLcyTpw5Rqks5qO-nxgaJpZM4I9Ui0>
.

**Comment by kargakis** [comment]
Closing until anybody finds a reason for this
