### ISSUE TITLE
extended network tests failing due to docker/image/something problems (again)

### ISSUE THREAD

**Issue by danwinship** [openshift/origin#9599]
https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_networking/ is currently failing/aborting for *all* builds, apparently due to:

```
Jun 27 14:29:03.964: INFO: At {2016-06-27 14:24:04 -0400 EDT} - event for service-webserver: {kubelet nettest-node-1} FailedSync: Error syncing pod, skipping: failed to "StartContainer" for "POD" with RunContainerError: "runContainer: Error response from daemon: Cannot start container 98da81fa7462f15af1e4406e2e4f6c628f4587d18d0cae34fd28bfaed0933c76: [9] System error: mkdir /sys/fs/cgroup/cpuset/docker: read-only file system"
```

(repeated multiple times and then eventually resulting in `Expected error: "timed out waiting for the condition" not to have occurred`)

@stevekuznetsov @runcom ?

**Comment by mrunalp** [comment]
From the error it looks like these tests are using docker in docker. can you confirm?

**Comment by danwinship** [comment]
correct

**Comment by stevekuznetsov** [comment]
@danwinship is there version drift between the host daemon and the DIND daemon? Isn't the runc stuff in Docker 1.11? I think our host is still on 1.10.3 -- not sure if this could be a source of errors.

**Comment by mrunalp** [comment]
It expects to be able to write to cgroups in the container. Did we change anything in the setup?

**Comment by danwinship** [comment]
looks like both sides are 1.10.3: the vagrant host has "docker-common-1.10.3-44.el7.x86_64" and the docker image has "docker-2:1.10.3-24.gitf476348.fc23.x86_64"

**Comment by mrunalp** [comment]
@marun how are we setting up cgroups in the container? Is it by bind mounting them, making the container privileged or mounting them inside with a script? It looks like this os failing as the container is defaulting to read only cgroups bind mounted from outside.

**Comment by marun** [comment]
@mrunalp dind has been relying on docker setting up cgroups with the correct permissions when the container is run with --privileged.

**Comment by marun** [comment]
@mrunalp I've traced the problem to oci-systemd-hook.x86_64 being installed on the host running the tests (thanks to @ncdc's gist of the package changes [1] for the new ami).  The read-only cgroup mounting that was causing this issue is consistent with the container modification done by oci-systemd-hooks [2], and disabling the hook resulted in dind containers working again.

In the near term the dind deployment script can ensure that oci-systemd-hook is disabled before a test run, but I think it would be useful to allow the hook and dind to co-exist.  They aren't compatible at present since nested docker cgroups must be rw.  How would you suggest resolving this?  Could a container advertise to oci-systemd-hooks that systemd fixup should not be done (e.g. via an env var like SKIP_OCI_HOOK=1)?  Could a container hardlink init to something else (e.g. dind_init) and use that as the entrypoint to avoid triggering the hook?  Or...?

cc: @openshift/networking 

1: https://gist.github.com/ncdc/d3777bf02ed042c30720d2880a0bd012
2: https://github.com/projectatomic/oci-systemd-hook#oci-systemd-hooks

**Comment by mrunalp** [comment]
If hard linking works then that would be the simplest fix for now.
