### ISSUE TITLE
Continue returning logs when a new deployment starts

### ISSUE THREAD

**Issue by kargakis** [openshift/origin#9626]
Right now when a deployer pod goes away[1], users that follow its logs need to rerun `oc logs` for getting the logs for the next deployment. We should look at providing a better experience by continuing to stream logs from the next deployer pod.

[1] Assuming that the deployment was cancelled by a newer deployment.

@smarterclayton @ironcladlou @mfojtik

**Comment by mfojtik** [comment]
@kargakis I think I agree, but we will have to make it somehow consistent wit builds... I think what we need to builds in this case will be `oc logs bc/foo` where it will stream the build logs (when one build finish, it will continue to stream the next one until there are no builds scheduled (assuming serial builds)).

@bparees

**Comment by bparees** [comment]
@mfojtik personally i'd find it a bit confusing if i'm streaming logs for one thing and suddenly i start getting logs from the next thing.  it may not be obvious that build1 finished(or was canceled or failed) and now you're looking at logs for build2, and i can't think of when that's what i'd really want.

**Comment by smarterclayton** [comment]
Agree with Ben here

On Jun 29, 2016, at 7:55 AM, Ben Parees <notifications@github.com> wrote:

@mfojtik <https://github.com/mfojtik> personally i'd find it a bit
confusing if i'm streaming logs for one thing and suddenly i start getting
logs from the next thing. it may not be obvious that build1 finished(or was
canceled or failed) and now you're looking at logs for build2, and i can't
think of when that's what i'd really want.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/origin/issues/9626#issuecomment-229382072>,
or mute the thread
<https://github.com/notifications/unsubscribe/ABG_pxYMD5Tv_q_uO-0zl1EKdbFyp1lUks5qQoc_gaJpZM4JBEUm>
.

**Comment by kargakis** [comment]
@smarterclayton you agree on the build side or for deployments too? Because you asked it for deployments.

**Comment by mfojtik** [comment]
@kargakis I think it applies to deployments as well... it might be confusing to watch logs from deployment1 and then the stream will start streaming deployment2... Maybe we can add some marker in the log separating those two :)

**Comment by smarterclayton** [comment]
Sorry, when I said "see the logs for the next deployment" I meant "if there
is nothing that constitutes "a deployment" yet, wait until there is.  Did
not mean to suggest we roll over across deployments.

On Jun 29, 2016, at 8:03 AM, Michail Kargakis <notifications@github.com>
wrote:

@smarterclayton <https://github.com/smarterclayton> you agree on the build
side or for deployments too? Because you asked it for deployments.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/origin/issues/9626#issuecomment-229384671>,
or mute the thread
<https://github.com/notifications/unsubscribe/ABG_pyTHdQBk2IiiKACMqZzqxJqUOVIhks5qQokSgaJpZM4JBEUm>
.

**Comment by kargakis** [comment]
Since we show logs from user pods, this would stand only for the initial deployment right?

**Comment by smarterclayton** [comment]
Correct.  Sorry for not being clear what I meant.   Might also apply
to a test deployment as well - successful, no pod, but want to say "oc
logs" and never flake (even if DC controller lags a bit).

**Comment by kargakis** [comment]
Ok, thanks for clearing this out. We already have an issue for waiting for the deployer pod to come up: https://github.com/openshift/origin/issues/9627
