### ISSUE TITLE
Rolling back to a previous deployment should add a cause in the DC

### ISSUE THREAD

**Issue by kargakis** [openshift/origin#9632]
There is a TODO about it in the code but with `oc rollout history` it will be really needed.

@mfojtik @ironcladlou @smarterclayton

**Comment by kargakis** [comment]
@smarterclayton @mfojtik rolling back a config right now is not atomic. `deploymentconfigs/rollback` is generating the rolled back config which in turn needs to be POSTed. Does it make sense to have the endpoint touch etcd in a similar fashion to `deploymentconfigs/instantiate`? Only in that way we can add a separate cause for rollback. Otherwise, we either need to open a hole in our normal update path or have the new specstatus endpoint type @deads2k was talking about.

**Comment by smarterclayton** [comment]
I don't like specstatus in general - that's what PUT / should do in a
"dumb apiserver" and it gets too close to the line.

Either rollout cause should be settable by an end user (because when a
user says deploy --latest they want to provide what the release does)
like builds, or that instantiate should be able to trigger a
deployment via only status (which is probably backwards incompatible
with old clients).

**Comment by kargakis** [comment]
Upstream is using annotations (change-cause) in replica sets for storing the cause of a rollout. I believe it's more flexible than our mechanism mainly because the cause in the DC is always for the latest rollout thus we end up losing history.

**Comment by mfojtik** [comment]
@kargakis so tu summarize this what we want:

1) annotation for every RC created by DC (whether it is ICT, config, rollback or manual (are there more?))
2) update `oc rollout history` to display the annotation (if set)
3) maybe update `oc status` as well?

**Comment by kargakis** [comment]
sgtm - we may want to deprecate the status field in the DC but that's not
necessary here
