### ISSUE TITLE
[Question]: haproxy reload script may cause old haproxy process not exit

### ISSUE THREAD

**Issue by adohe** [openshift/origin#9640]
I am studying origin router implementation and deploying origin in our test environment and just noticed this [reload_haproxy](https://github.com/openshift/origin/blob/master/images/router/haproxy/reload-haproxy) script. The main command in this script is: `/usr/sbin/haproxy -f $config_file -p $pid_file -sf $old_pids`, origin use `-sf` option to do some graceful reload and according to HAProxy document: `HAProxy remains running as long as there is a live connection (i.e. it will not terminate an established connection)`. Suppose there are tcp services(i.e redis) or websocket in cluster, every time we reload HAProxy, the old process will not exist as the tcp connection may still be established. Thus will cause lots of haproxy processes exist after a long running. I am not sure there is a good way to fix this in HAProxy but really want to know how to improve this. @smarterclayton @pmorie please take a look. Really thanks :)

**Comment by smarterclayton** [comment]
Expectation is you'd tune connection timeout and the reload grace period
(rate limiter) as necessary.  The overhead per connection in haproxy should
be low and process memory reuse should mitigate some of it.  We did tests
in this scenario and found reasonable compromise.

On Jun 29, 2016, at 9:17 PM, TonyAdo <notifications@github.com> wrote:

I am studying origin router implementation and deploying origin in our test
environment and just noticed this reload_haproxy
<https://github.com/openshift/origin/blob/master/images/router/haproxy/reload-haproxy>
script. The main command in this script is: /usr/sbin/haproxy -f
$config_file -p $pid_file -sf $old_pids, origin use -sf option to do some
graceful reload and according to HAProxy document: HAProxy remains running
as long as there is a live connection (i.e. it will not terminate an
established connection). Suppose there are tcp services(i.e redis) or
websocket in cluster, every time we reload HAProxy, the old process will
not exist as the tcp connection may still be established. Thus will cause
lots of haproxy processes exist after a long running. I am not sure there
is a good way to fix this in HAProxy but really want to know how to improve
this. @smarterclayton <https://github.com/smarterclayton> @pmorie
<https://github.com/pmorie> please take a look. Really thanks :)

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/origin/issues/9640>, or mute the thread
<https://github.com/notifications/unsubscribe/ABG_pxAZPPQGH5ZEgfjeYt_6Hj3cQw5dks5qQ0NBgaJpZM4JByXp>
.

**Comment by jameseck** [comment]
Hi,
I'd like to comment that I am seeing significant impact from this currently.
We have a number of busy clusters, each with 24 nodes and ~1000-1500 pods.
On the three masters where the routers are running, we are constantly seeing 10s and sometimes 100s of haproxy -sf processes.  These are often triggering the oom killer.

What we're seeing looks something like this:

https://gist.github.com/jameseck/27c21329e5c8c28ce10af6861abb8ee4

As can be seen, many haproxy -sf procs with the same pids as the previous one, plus another pid.
So the previous reload isn't happening before the next reload comes in.
Maybe the reload-haproxy script can be modified to kill the old -sf procs if the new pids are the same as the old ones?

**Comment by smarterclayton** [comment]
@openshift/networking

**Comment by ramr** [comment]
The default tunnel timeout is 1 hour. So if you have websockets/tcp connections (and any time haproxy is reloaded), the old haproxy processes would "linger" around for that period. It can be tuned for your environment w/ an environment variable.
See: https://github.com/openshift/origin/blob/master/images/router/haproxy/conf/haproxy-config.template#L73
E.g. `oc env dc/router ROUTER_DEFAULT_TUNNEL_TIMEOUT=15m # 15 mins.`

@jameseck  from your gist if I am reading the columns correctly, the 8:54 ... 9:09 look to be timestamps when the process was started (correct?) and it looks to be within that interval window.

**Comment by jameseck** [comment]
Yes that's correct.
We've tweaked the tunnel timeout and that has mitigated this issue.
However, we are definitely not using any tunnels/web sockets.  It seems
that haproxy keeps the processes around for the longest timeout, regardless
of what connections are actually open.  We observed that the haproxy
processes that had been signalled to die had just fin_wait2/close_wait
connections, no established connections.

**Comment by jameseck** [comment]
And in regard to the columns, yes the 8:54..9:09 are timestamps for proc
start.
The more we looked at this earlier, the more obvious it was that it was
exactly an hour before processes died.
Obviously the workaround of the tunnel timeout doesn't help if we were
using websockets.  I presume that haproxy 1.6 will fix this problem though.

**Comment by ramr** [comment]
The tunnel timeout works for websockets (and tcp connections) in haproxy 1.5.x 

Hmm, so as re: haproxy keeping the processes around - not sure but would be good to know if setting `timeout client-fin 30s` in the haproxy.config fixes that for you? 

It does require you to get and change the template, so its a wee bit of work. There's docs on how to use a custom template with config maps:
https://docs.openshift.com/container-platform/3.4/install_config/router/customized_haproxy_router.html#using-configmap-replace-template

And the section before that on how to get the current haproxy template.

**Comment by mgjadoul** [comment]
Hello,
We have a similar issue. We have only 200 to 300 established connections but 20k+ connections in fin_wait2 and 20k+ connections in closed_wait.  This means that there is a lot of port used on 127.0.0.1 and I am worrying about increasing the maxconn further. Today it is at 20k too... 
And we do not use websocket. 20k+ connections are to port 10444 so I think it is more related to reencryption in the case of SNI connections. This connections between the haproxy and itselfs stay open.... I am wondering it is is required and what is the impact of having 20k + connections open between 127.0.0.1 and itselfs on the node. At the end, are we exhausting port on 127.0.0.1?

**Comment by knobunc** [comment]
We landed https://github.com/openshift/origin/pull/14220 in 1.6 that will add the recommended FIN timeouts that will hopefully resolve this issue.

You can apply this change by using a custom router template with an older router if you want.  See @ramr's comment above.
