### ISSUE TITLE
Service/pod proxying not working

### ISSUE THREAD

**Issue by jimmidyson** [openshift/origin#965]
Seems as though recent changes have broken the service & pod proxying available at `/api/v1beta2/proxy/*`. Simply returns 404s for every proxy request. This was working until recently & is of course very useful to have.

**Comment by ncdc** [comment]
I'll take this

**Comment by ncdc** [comment]
@jimmidyson since you mentioned on IRC that you're running OpenShift all-in-one, we actually didn't change anything in OpenShift itself related to proxying, other than we recently upgraded the version of Kubernetes that we bundle. It's possible something changed there. I tested on both Kubernetes master (from yesterday) and OpenShift master (from this morning), and here is what I see:

If you request `/api/v1beta2/proxy/services/<service>/`, you get a 404. For some reason it's not proxying the root URL (`/`) to the service.

If you request `/api/v1beta2/proxy/services/<service>/<anything else>`, it will proxy that correctly. For example, I created a registry service for a docker registry, and, `/api/v1beta2/proxy/services/registry/v1/_ping` works fine.

/cc @smarterclayton

**Comment by ncdc** [comment]
See https://github.com/GoogleCloudPlatform/kubernetes/pull/4283

**Comment by jimmidyson** [comment]
Thanks @ncdc!

**Comment by smarterclayton** [comment]
Will probably rebase tomorrow

**Comment by derekwaynecarr** [comment]
We need to fix the proxy issue prior to this rebase.  Let's settle on solution.

**Comment by jimmidyson** [comment]
This particular issue is fixed upstream AFAIK.

**Comment by smarterclayton** [comment]
Should be fixed now
