### ISSUE TITLE
ssh connection to App

### ISSUE THREAD

**Issue by Lunik** [openshift/origin#9689]
Is there a way to connect on an OpenShift App without using `oc rsh`
And by the way do `oc rsync` directly on an App.

##### Version
v1.3.0-alpha.2

##### Current Result

I can't connect to an App directly. I search PODS and use it for rsync

##### Expected Result

I want to use a simple `oc rsync ./local/dir/ APP:/remote/dir` and `oc rsh APP`

**Comment by bparees** [comment]
Oc rsh is the way to get shell access to a running pod. 
Oc rsync is the way to copy files to/from a running pod. 

It's not clear to me:

1) what you are looking for instead of those things 
2) what problem you are having using those tools?

**Comment by Lunik** [comment]
Instead of having to search the pods with `oc get pods`, I want to use `oc rsync` with an App name and `oc` redirect my request on a Pod.

**Comment by bparees** [comment]
there is no first class concept of an "app" in openshift.  the closest analogs are:
1) labels if you group all the resources (replication controller, services, routes, etc) for a particular app under a single label
2) replication controllers since they represent the scaling unit for instances of a particular pod/image.

However in both cases if you attempted to rsh or rsync against one of those things, it would not be clear which specific instance you were trying to operate against, so what you are asking is not possible.

The best we could do is allow you to specify a deployment config or replication controller name and then, *if* you only have a single pod associated with that deployment, allow the rsh/rsync to proceed against that pod.

**Comment by bparees** [comment]
adding @mfojtik for the rsh half of this RFE, rsync is owned by devex.

we will need to discuss if this enhancement is worth doing (making it easier to rsync/rsh to a DC when your replica count is 1, or possibly reporting back all the pod names when the replica count is > 1).

**Comment by Lunik** [comment]
I understand what you meen, this seems to be a legit reasons.

So if I want to access to the storage of the pod, I need to use `rsync or rsh` on a specific pod. (work with a volume too).

Anyway thanks for your answer 😉

**Comment by bparees** [comment]
> So if I want to access to the storage of the pod, I need to use rsync or rsh on a specific pod.

exactly.

**Comment by bparees** [comment]
@mfojtik based on my suggestion in https://github.com/openshift/origin/issues/9689#issuecomment-230310413
feel free to either just close this, or trello and close it.

**Comment by mfojtik** [comment]
yeah, if you have RC/RS with replicas > 1 then it is basically impossible to `oc rsh` and pick the 'right' pod. I think we should in that case give users error message with clues about pod names they can rsh to, something like:

```
$ oc rsh dc/foo # -> DC with 3 replica
You can RSH into one of the 'pod-1234, pod-3456, pod-2312'
```
