### ISSUE TITLE
ssh through HAProxy router 

### ISSUE THREAD

**Issue by Lunik** [openshift/origin#9690]
I have created an ssh server App I want to connect to it
How should I configure my router (or route ?) to accept ssh request ?
##### Version

oc v1.3.0-alpha.2
##### Steps To Reproduce

`ssh -p 80 foo@sftp-test.exemple.fr -vvv`
##### Current Result

```
debug1: Enabling compatibility mode for protocol 2.0
debug1: Local version string SSH-2.0-OpenSSH_6.6.1
debug1: ssh_exchange_identification: HTTP/1.0 400 Bad request
debug1: ssh_exchange_identification: Cache-Control: no-cache
debug1: ssh_exchange_identification: Connection: close
debug1: ssh_exchange_identification: Content-Type: text/html
debug1: ssh_exchange_identification: 
debug1: ssh_exchange_identification: <html><body><h1>400 Bad request</h1>
debug1: ssh_exchange_identification: Your browser sent an invalid request.
debug1: ssh_exchange_identification: </body></html>
ssh_exchange_identification: Connection closed by remote host
```
##### Expected Result

The ssh connection

**Comment by wtrocki** [comment]
Reason why that's failing is that HAProxy is working only http protocol:
https://github.com/openshift/origin/blob/master/images/router/haproxy/conf/haproxy-config.template#L72

TCP type should be enabled in next release by binding public addresses to service
There is also option do deploy your own modification of haproxy router:
https://docs.openshift.com/enterprise/3.0/install_config/install/deploy_router.html#deploying-a-customized-haproxy-router

**Comment by Lunik** [comment]
Should I do something like that ?
```
frontend public
  bind :{{env "ROUTER_SERVICE_HTTP_PORT" "80"}}
  mode tcp
  tcp-request inspect-delay 5s
  tcp-request content accept if TCP
```

**Comment by wtrocki** [comment]
It's not so easy to do. TCP mode would not allow some http protocol modifications that happening later. When you connect to running router you would see that openshift is redirecting backed for each route here:
https://github.com/openshift/origin/blob/master/images/router/haproxy/conf/haproxy-config.template#L83

Each backed would have `mode http`  so hack may involve to create static route and redirect to that before any http transformations. If you looking for hacky solution this article may be good example:
https://confluence.atlassian.com/bitbucketserver/setting-up-ssh-port-forwarding-776640364.html

**Comment by l0rd** [comment]
@wtrocki do you know if and when you will support TCP?

**Comment by wtrocki** [comment]
@l0rd I tried to do it but then realized that this is against the router responsibilities and carries some problems with it. OpenShift documentation has really good introduction for possible options:

https://docs.openshift.com/container-platform/3.4/dev_guide/getting_traffic_into_cluster.html

Since 3.4 node ports are supported in templates. We can reuse pool of public IP's and attach ports to it. Works great for ssh, git etc.

**Comment by ankur4u007** [comment]
I am also facing this issue, Any workaround to host a ssh server in openshift origin and connect to it from local machine ? @wtrocki ?

**Comment by wtrocki** [comment]
@ankur4u007 As mentioned above: "Since 3.4 externalIP for services are supported in templates.
We can reuse pool of public IP's and attach ports to it. Works great for ssh, git etc."

**Comment by ankur4u007** [comment]
@wtrocki Thanks, i tried setting up my ymal config with external ip : 
and it looks like this : 
spec:
  ports:
    - name: 8022-tcp
      protocol: TCP
      port: 8022
      targetPort: 8022
      nodePort: 31043
    - name: 8080-tcp
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30826
  selector:
    deploymentconfig: docker-remote-forward
  clusterIP: 172.30.83.16
  type: LoadBalancer
  externalIPs:
    - 10.130.79.198
  deprecatedPublicIPs:
    - 10.130.79.198
  sessionAffinity: None

If I understand correctly here 10.130.79.198 , is the IP i will need to connect to from my local ssh on port 31043 which then forwards it to the service port 8022 which then dorwards to container port 8022 where the ssh server is running, the problem is the i am not able to connect to this external ip.
"debug1: connect to address 10.130.79.198 port 31043: Connection timed out"
I got this external IP from the pod -> dashboard page -> external IP. Is this external IP needs to be configured anywhere or is my above config has any issue with setup ? please help.

**Comment by canit00** [comment]
The question is why are you trying to ssh into a pod in the first place? @ankur4u007 

Am not saying that there's not a legitimate use case for a container running SSH, but I've not seen any background posted in re: to this concern?!

**Comment by ankur4u007** [comment]
@canit00 I have a use case where i am running services on the my local machine which is behind a router behind a NAT, so i can't port forward to my public ip. The only way to do it is via ssh tunneling or a VPN, for both i would need an exposed port to connect from my local.

**Comment by wtrocki** [comment]
@ankur4u007 github issues are not the best place to talk about specific use cases. 
I will recommend to create stack overflow ticket with tag #openshift 
You will get some help there.

**Comment by wtrocki** [comment]
Issue is outdated. Multiple options to do that at the moment.

**Comment by sachin-badgujar** [comment]
@ankur4u007 Did you find workaround? I am trying run Bastion as a Kubernetes pod to perform SSH Tunneling.
