### ISSUE TITLE
How to replace the scheduler in openshift

### ISSUE THREAD

**Issue by enlinxu** [openshift/origin#9833]
[provide a description of the issue]
##### Version

[provide output of the `openshift version` or `oc version` command]
[root@OSMaster images]# oc version
oc v1.2.0
kubernetes v1.2.0-36-g4a3f9c5
##### Question:

I can replace the kube-scheduler in k8s easily, but in openshift-origin, is this an option? How can I replace the default scheduler? Do I need to modify the ansible script?

Any help is highly appreciated.

**Comment by ncdc** [comment]
It is not currently possibly to replace the scheduler. You can customize which predicates and priorities are in use (see https://docs.openshift.org/latest/admin_guide/scheduler.html#modifying-scheduler-policy).

cc @smarterclayton @timothysc do you want a Trello card for this?

**Comment by timothysc** [comment]
Parallel scheduling via annotation is a potential out-path depending on the use case for this one.

**Comment by smarterclayton** [comment]
Yeah, I want to extend component enablement to the controller manager so
admins can disable controllers by name.

On Jul 14, 2016, at 9:49 AM, Andy Goldstein <notifications@github.com>
wrote:

It is not currently possibly to replace the scheduler. You can customize
which predicates and priorities are in use (see
https://docs.openshift.org/latest/admin_guide/scheduler.html#modifying-scheduler-policy
).

cc @smarterclayton <https://github.com/smarterclayton> @timothysc
<https://github.com/timothysc> do you want a Trello card for this?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/origin/issues/9833#issuecomment-232670778>,
or mute the thread
<https://github.com/notifications/unsubscribe/ABG_p1ThcWStLePXxXczHLLo54JrROXMks5qVj55gaJpZM4JL5E3>
.

**Comment by enlinxu** [comment]
It will be great if the scheduler can be decoupled into a separate service/container, so that it can be easily replaced

**Comment by smarterclayton** [comment]
Doesn't the scheduler respect the alternate scheduler annotation?

**Comment by ncdc** [comment]
Yes, we do have that now. So if you annotate the pod with `scheduler.alpha.kubernetes.io/name=<some scheduler name here>`, the built-in scheduler will not process it.

**Comment by enlinxu** [comment]
Hi, I do see there's option other than the default scheduler, like navops command. (http://blogs.univa.com/2016/06/using-navops-command-on-red-hat-openshift/). I wonder if that is relying on the annotation in pod? or it actually replace the scheduler?

**Comment by ncdc** [comment]
I'm not familiar with navops, but we have not made any changes to how the scheduler is configured and started in OpenShift, so it is still not yet possible to swap it out completely for something else.

**Comment by ingvagabund** [comment]
I'm not familiar with Navops either nor I could find any details how the Navops's scheduler is deployed.
However, the scheduler is "just" a client with capabilities of pushing changes into the Apiserver (there are other implementation details as metrics and event recording). As long as there is a blackbox which is capable of deciding what node a given pod gets schedule to, it can replace the Scheduler.

In OpenShift, the scheduler is part of the master service so it can not be completely replaced.

**Comment by ingvagabund** [comment]
@detiber is the openshift master service deployment the only way? Are the ansible scripts capable of deploying everything up to the scheduler (replacing the scheduler with pod manifest and running the scheduler in a container)?

**Comment by ingvagabund** [comment]
In addition, the master service sets up additional OpenShift specific features. So one has to run the master service. What I can think of is to introduce an admission that will check if a pod has ``scheduler.alpha.kubernetes.io/name`` set and if not (meaning the default scheduler gets used), introduce the annotation and set it to your scheduler. This way, the default scheduler will be running but will not do anything, just eat some amount of resources.

**Comment by smarterclayton** [comment]
We did change the scheduler startup so that navops is possible in 1.3.  Set
kubernetesMasterConfig: schedulerArguments: with key value pairs that map
to flags.  You can pass the default scheduler name.

**Comment by smarterclayton** [comment]
Specifically change the "scheduler-name" flag under those keys to "-
ANOTHER_NAME" and the default scheduler will no longer run for pods without
the annotation.

**Comment by enlinxu** [comment]
That's great news, thanks @smarterclayton . Basically we are trying to integrate with origin and provide a full stack controller. (We are trying to contribute to Kubernetes as well https://github.com/kubernetes/kubernetes/issues/9125). Now we don't need to modify the origin code to prevent scheduler from starting. 

There's one more code change needed to enable static pods so as to deploy our scheduler as static pod. Basically we added the following in create_nodeconfig.go:
+		PodManifestConfig: &configapi.PodManifestConfig{
+			Path: "/etc/kubernetes/manifest",
+			FileCheckIntervalSeconds: 5,
+		},

Any suggestion if we can do that without code change? We are trying to avoid any code change and make our scheduler plug and play.

Thanks a lot in advance.

**Comment by detiber** [comment]
@sdodson @abutcher ptal

**Comment by smarterclayton** [comment]
You should be able to craft a patch to node config that is applied for
those settings today - see the use of "openshift ex config patch" in
hack/test-cmd.sh for an example.  Alternatively, if that patching is done
in ansible you should be able to add that in as necessary.

**Comment by ingvagabund** [comment]
As Clayton says:

```yaml
...
kubeletArguments:
  config:
    - "/etc/kubernetes/origin"
...
```

**Comment by sdodson** [comment]
For the kubelet this is available today in ansible, `openshift_node_kubelet_args` can be set to the json encoded contents you want for kubeletArguments.  kubernetesMasterConfig: schedulerArguments is not available via ansible however schedulerConfigFile is, I don't know if you can achieve the same via a scheduler config file or not.

**Comment by cameronbrunner** [comment]
> Hi, I do see there's option other than the default scheduler, like navops command. (http://blogs.univa.com/2016/06/using-navops-command-on-red-hat-openshift/). I wonder if that is relying on the annotation in pod? or it actually replace the scheduler?

@enlinxu Navops Command respects the annotation as does the default scheduler included in OpenShift.  By having a value specified other than 'default' the default scheduler ignores it.  When running Navops Command we typically use the default scheduler to manage Navops Command since it runs as a pod inside of OpenShift and then annotate the pods we wish command to scheduler.  With the enhancement @smarterclayton referenced earlier (the `schedulerArguments` feature) you can configure the default scheduler to no longer be the default by setting its name to something other than 'default'.  You can additionally change Navops Command to run with the name 'default' effectively becoming the default scheduler of the cluster.  The convention in Kubernetes is that the default scheduler (the one that will scheduler pods that do not have an annotation or have the annotation of 'default') must have the scheduler name 'default'.  If you are using Navops Command and you want it to be your default scheduler I would still recommend using the OpenShift default scheduler to start Navops Command by annotating the Navops Command pod with the name assigned via the `schedulerArguments` configuration option.

**Comment by cameronbrunner** [comment]
The PR @smarterclayton and I referenced regarding the configuration of the default scheduler

https://github.com/openshift/origin/pull/10064
