### ISSUE TITLE
`oc get pods --show-all=false -o name` doesn't work

### ISSUE THREAD

**Issue by rhcarvalho** [openshift/origin#9901]
The `--show-all=false` flag is documented as:

```
-a, --show-all=true: When printing, show all resources (false means hide terminated pods.)
```

However, when used together with `--output name`, all pods are listed, terminated pods are **not** omitted.

##### Upstream bug

This bug was also filled in Kubernetes: https://github.com/kubernetes/kubernetes/issues/29115

##### Version

```
$ openshift version
openshift v1.3.0-alpha.2-267-g2fe486f-dirty
kubernetes v1.3.0-alpha.3-599-g2746284
etcd 2.3.0+git
$ oc version
oc v1.3.0-alpha.2-267-g2fe486f-dirty
kubernetes v1.3.0-alpha.3-599-g2746284
```

##### Steps To Reproduce
1. In a new project, start a build like origin/examples/sample-app:

  ```
oc new-app https://raw.githubusercontent.com/openshift/origin/master/examples/sample-app/application-template-stibuild.json
```

2. After the build is complete and the app is deployed, you should see two pods, one in `Completed` state, and the other `Running`:

  ```
$ oc get pods
NAME                       READY     STATUS      RESTARTS   AGE
ruby-hello-world-1-build   0/1       Completed   0          9d
ruby-hello-world-1-sg623   1/1       Running     0          9d
```

##### Current Result

Now, the `--show-all` flag works with the default output, but doesn't when the output is set to `name`:

```
$ oc get pods --show-all=false
NAME                       READY     STATUS    RESTARTS   AGE
ruby-hello-world-1-sg623   1/1       Running   0          9d
$ oc get pods --show-all=false -o name
pod/ruby-hello-world-1-build
pod/ruby-hello-world-1-sg623
```

##### Expected Result

```
$ oc get pods --show-all=false
NAME                       READY     STATUS    RESTARTS   AGE
ruby-hello-world-1-sg623   1/1       Running   0          9d
$ oc get pods --show-all=false -o name
pod/ruby-hello-world-1-sg623
```

**Comment by juanvallejo** [comment]
What `NamePrinter` currently does is take a generic `runtime.Object` and use `meta.Accessor`'s [GetName() method to obtain its name](https://github.com/openshift/origin/blob/master/vendor/k8s.io/kubernetes/pkg/api/meta/interfaces.go#L40-L65). Since `NamePrinter` does not know the specific type of resource it is dealing with, it has no way of knowing if the current `runtime.Object` has a status, and if it should be skipped based on that status.

A quick solution would be to have an `if` statement that checks to see if the current generic object being printed is of kind `pod`, then cast it to `*api.Pod`, and then access its status to determine if it should be printed.

A better solution would be to call the same handler functions that `HumanReadablePrinter` calls, and include a flag that tells that function to only print the resource's name.

What are your thoughts on this?

cc @fabianofranz @deads2k @liggitt @smarterclayton

**Comment by deads2k** [comment]
> A quick solution would be to have an if statement that checks to see if the current generic object being printed is of kind pod, then cast it to *api.Pod, and then access its status to determine if it should be printed.

No.  Generic methods should be generic.  Sounds like you should be filtering the list before calling the printer function, right?

**Comment by smarterclayton** [comment]
Filtering should happen before printing.

**Comment by juanvallejo** [comment]
Thanks for the feedback. I'll filter the list of resources as they're iterated through in [get.go](https://github.com/openshift/origin/blob/master/vendor/k8s.io/kubernetes/pkg/kubectl/cmd/get.go)

**Comment by smarterclayton** [comment]
When you do that, you can also extract out the recent changes that went in
to filter hidden pods (having filtering happen before printing is much
superior).  Remember though that printing needs to be generic, so you'll
likely have to have an abstraction that allows that (which means a lot more
work)
